cert-manager/cert-manager

deploy/charts/cert-manager/values.yaml
The `http_proxy` key was defined twice and is therefore replaced once with the `https_proxy` key.
```release-note
NONE
```
=> Include HTTPS proxy variable in Helm values

pkg/issuer/acme/dns/util/wait.go
Spent a couple of days tracking down bad `SERVFAIL` for some of our
domains, and had a hard time finding where this was coming from. Make
the error slightly more descriptive to help locate it, and more inline
with the terminal error of the function.
Makes the FindZoneByFqdn error more descriptive.
```release-note
Updated details of FindZoneByFqdn error message when an unexpected DNS response code is received.
```
=> Add a more descriptive FindZoneByFqdn error message

deploy/crds/crd-certificaterequests.yaml, deploy/crds/crd-certificates.yaml, deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, deploy/crds/crd-orders.yaml
Related to #3876
See #3876
Very similar to #3876, just addition for CRD conversions.
```release-note
NONE
```
=> Add support to allow CRD conversion webhooks from outside of the cluster

pkg/controller/BUILD.bazel, pkg/controller/controller.go
This PR stops the pollution of cert-manager-controller logs with errors from multiple controllers attempting to update the same object version. Instead, we log to info, however we _still_ re-queue the object so has not functional change to any controller.
```
E0323 18:09:56.487221       1 controller.go:158] cert-manager/controller/CertificateReadiness "msg"="re-queuing item due to error processing" "error"="Operation cannot be fulfilled on certificates.cert-manager.io \"osm-ca\": the object has been modified; please apply your changes to the latest version and try again" "key"="default/osm-ca" 
```
/assign @irbekrm @jakexks @maelvls @wallrj 
/milestone v1.3
/cleanup
fixes #3667
```release-note
Optimistic locking messages (the object has been modified) are now logged at the Info level …
```
=> Log Info when a re-queue happens due to optimistic locking

hack/bin/deps.bzl
I was wrong in https://github.com/jetstack/cert-manager/pull/3939#pullrequestreview-648068051 to think that this script should have caught the internal import error.
I dug through the history of `hack/verify-staticcheck.sh` found https://github.com/jetstack/cert-manager/pull/3037 where @munnerz writes:
> This script will need to be run manually and requires the Go toolchain to be installed on the host machine running it.
> It cannot be triggered via Bazel yet.
> In future (once supported) we should look at run staticcheck as part of nogo - for now though, this gives us some simple (albeit manual) visibility and things to work on/fix
And I see that https://github.com/bazelbuild/bazel-gazelle/issues/578 is still open.
So meanwhile, this updates the version of staticcheck and I will make a …
=> Upgrade to Staticcheck 2020.2.3 (v0.1.3)

go.mod, pkg/api/util/BUILD.bazel, pkg/api/util/warnings.go, pkg/internal/api/validation/BUILD.bazel, pkg/internal/api/validation/registry.go, pkg/internal/api/validation/registry_test.go, pkg/internal/api/validation/warning.go, pkg/internal/apis/acme/validation/BUILD.bazel, pkg/internal/apis/acme/validation/challenge.go, pkg/internal/apis/acme/validation/challenge_test.go, pkg/internal/apis/acme/validation/order.go, pkg/internal/apis/acme/validation/order_test.go, pkg/internal/apis/certmanager/identity/certificaterequests/BUILD.bazel, pkg/internal/apis/certmanager/identity/certificaterequests/certificaterequests.go, pkg/internal/apis/certmanager/identity/certificaterequests/certificaterequests_test.go, pkg/internal/apis/certmanager/validation/BUILD.bazel, pkg/internal/apis/certmanager/validation/certificate.go, pkg/internal/apis/certmanager/validation/certificate_test.go, pkg/internal/apis/certmanager/validation/certificaterequest.go, pkg/internal/apis/certmanager/validation/certificaterequest_test.go, pkg/internal/apis/certmanager/validation/clusterissuer.go, pkg/internal/apis/certmanager/validation/issuer.go, pkg/internal/apis/certmanager/validation/issuer_test.go, pkg/internal/apis/certmanager/validation/warnings.go, pkg/webhook/handlers/testdata/apis/testgroup/v2/validation.go, pkg/webhook/handlers/testdata/apis/testgroup/validation/BUILD.bazel, pkg/webhook/handlers/testdata/apis/testgroup/validation/validation.go, pkg/webhook/handlers/testdata/apis/testgroup/validation/validation_test.go, pkg/webhook/handlers/validation.go
This PR:
-  allows for validation functions that are called by validating webhook to return a [warning](https://kubernetes.io/blog/2020/09/03/warnings/) that would be displayed to the caller by Kubernetes. Top level validation functions now return warnings as well as errors.
- adds an actual warning if ACME issuer's EAB key algorithm field, that was deprecated by #3877, is set.
See #3220 for additional context.
This is what the warning added by this PR looks like:
(The warning text was written with the assumption that we will not actually remove the key algorithm field in `cert-manager` `v1`. Else the warning should have included in which version we intend to remove it.)
```release-note
Validating webhook returns a warning if the legacy ACME issuer EAB key algorithm is set.
```
=> Webhook warnings

deploy/crds/crd-certificaterequests.yaml, deploy/crds/crd-certificates.yaml, deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, deploy/crds/crd-orders.yaml
Fixes https://github.com/jetstack/cert-manager/issues/3943. The controller-gen tool is quite rude and won't tell you when one of the CRD manifests cannot be parsed when the option schemapatch is used. As an example, the following:
```
sed -i 's/RFC8555/RFC8556/g' pkg/apis/certmanager/v1/types_issuer.go
controller-gen schemapatch:manifests=./deploy/crds output:dir=./deploy/crds paths=./pkg/apis/...
```
should trigger a change in the crd-clusterissuers.yaml:
```diff
--- a/deploy/crds/crd-clusterissuers.yaml
+++ b/deploy/crds/crd-clusterissuers.yaml
@@ -3184,7 +3184,7 @@ spec:
type: object
properties:
acme:
-                  description: ACME configures this issuer to communicate with a RFC8555 (ACME) server to obtain signed x509 certificates.
+                  description: ACME configures …
```
=> Controller-gen can now update CRDs like before

test/e2e/suite/conformance/certificates/venafi/venafi.go, test/e2e/suite/issuers/venafi/tpp/doc.go
Currently all Venafi e2e tests are failing, see TestGrid i.e [here](https://testgrid.k8s.io/jetstack-cert-manager-next#ci-cert-manager-next-e2e-v1-18)
This should be a very short term revert, so people's PRs can get tested & merged- we should investigate and revert this PR soon.
=> Temporarily revert "Re-enable the Venafi TPP E2E tests"

pkg/internal/vault/vault.go, pkg/internal/vault/vault_test.go, pkg/util/pki/parse.go, pkg/util/pki/parse_test.go
```release-note
The Vault issuer now constructs a certificate chain after signing, and populates the CertificateRequest.Status.CA with the root most certificate if available.
```
This PR is to separate the work from https://github.com/jetstack/cert-manager/pull/3978 into separate PRs. This PR includes only the `ParseCertificateChain` function, as well as the change to the vault issuer to make use of this new func.
/assign @maelvls @munnerz @SgtCoDFish @jakexks
=> Change Vault Issuer to construct the certificate chain to populate the CertificateRequest CA with the root most cert.

test/e2e/suite/conformance/certificates/venafi/venafi.go, test/e2e/suite/issuers/venafi/tpp/doc.go
Re-enable Venafi TPP tests that were disabled whilst we were having some issues with out test TPP instance.
The issues have been fixed and I have verified that Venafi TPP tests pass again, see https://github.com/jetstack/cert-manager/pull/3938#issuecomment-840456612
```release-note
NONE
```
/kind cleanup
=> Re-enable e2e tests that connect to Venafi TPP.

pkg/controller/certificaterequests/acme/acme_test.go, pkg/controller/certificaterequests/ca/ca.go, pkg/controller/certificaterequests/ca/ca_test.go, pkg/internal/vault/vault.go, pkg/internal/vault/vault_test.go, pkg/util/kube/BUILD.bazel, pkg/util/kube/pki.go, pkg/util/pki/csr.go, pkg/util/pki/csr_test.go, pkg/util/pki/parse.go, pkg/util/pki/parse_test.go
```release-note
The CA issuer now constructs a certificate chain after signing, and populates the CertificateRequest.Status.CA with the root most certificate if available. Correctly passes down CA certificate when chaining CA Issuers together.
```
This PR is branched from https://github.com/jetstack/cert-manager/pull/3982 and should be merged first. EDIT: This should say "and that PR should be merged first" instead of "and should be merged first"
Updates `SignCSRTemplate` to use new `ParseCertificateChain` func, and passes through CA certificate when chaining CA Issuers together.
/assign @maelvls @munnerz @SgtCoDFish @jakexks
=> Parse certificate chain CA Issuer

pkg/controller/certificaterequests/acme/acme.go, pkg/internal/vault/vault.go, pkg/internal/vault/vault_test.go, pkg/util/pki/parse.go, pkg/util/pki/parse_test.go
```release-note
The ACME issuer now constructs a certificate chain after signing, and populates the CertificateRequest.Status.CA with the root most certificate if available.
```
This PR is branched from #3982 and should be merged first. EDIT: This should say "and that PR should be merged first" instead of "and should be merged first"
/assign @maelvls @munnerz @SgtCoDFish @jakexks
=> Parse certificate chain acme

BUILD.bazel, pkg/acme/accounts/client.go, pkg/acme/accounts/test/BUILD.bazel, pkg/acme/accounts/test/registry.go, pkg/acme/client/fake.go, pkg/issuer/acme/BUILD.bazel, pkg/issuer/acme/acme.go, pkg/issuer/acme/setup.go, pkg/issuer/acme/setup_test.go, test/unit/coreclients/BUILD.bazel, test/unit/coreclients/secrets.go, test/unit/gen/BUILD.bazel, test/unit/gen/conditions.go, test/unit/gen/issuer.go
This PR adds unit tests for ACME issuer's `Setup` function.
This follows #3877 , see the comment about testing [here](https://github.com/jetstack/cert-manager/pull/3877#discussion_r610749443) .
Some notes:
- This test is not a particularly good unit test- all the methods of `Acme` struct should be refactored to make them more testable. However, maybe it would be better if we merged (if we are going to at all) #3695 first. Also maybe already having _some_ unit test in place would make refactoring easier.
- We usually unit test using [test builder](https://github.com/jetstack/cert-manager/blob/master/pkg/controller/test/context_builder.go#L60), which helps with mocking requests to kubernetes API server. It did not seem to make sense to use the test builder here because `Setup` does not have …
=> 3879 test acme issuer setup

devel/lib/lib.sh
1.17 is no longer supported by upstream, and 1.21 didn't work with just
a trivial version change, suggesting more work may need to be done
Signed-off-by: Ashley Davis <ashley.davis@jetstack.io>
```release-note
Update default development version of Kubernetes in kind from 1.17 to 1.20
```
=> Change default devel K8S_VERSION to 1.20

cmd/controller/app/BUILD.bazel, cmd/controller/app/controller.go
This is a follow-up work to #3926 where we changed how leader election is done for `cainjector` , see the comment [here](https://github.com/jetstack/cert-manager/pull/3926#issuecomment-842187486) and #4013 .
This PR changes the lock used for `controller`'s leader election from `ConfigMap`s to a  [ConfigMapsLeasesResourceLock](https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/resourcelock/interface.go#L38) [Multilock](https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/resourcelock/multilock.go#L32) so that leader election is done in the same way for both `controller` and `cainjector`.
From user's perspective, the difference will be the new `Lease`s object created in the leader election namespace. This is not a breaking change.
We already …
=> Use ConfigmapsLeases Multilock for controller's leader election

devel/cluster/config/v1beta2.yaml, devel/cluster/create-kind.sh, devel/lib/lib.sh, hack/bin/deps.bzl
This enables e2e tests to be run on k8s 1.21
```release-note
NONE
```
=> Update to kind 0.11.0/K8s 1.21

CODE_OF_CONDUCT.md, deploy/charts/cert-manager/Chart.yaml
**What this PR does / why we need it**: This changes old email addresses to use a new, non-Jetstack, `cert-manager-maintainers@googlegroups.com` point of contact. See #4025 
/release-note-none
/kind cleanup
/milestone v1.4
=> Update old references to replaced/obsolete email addresses

build/images.bzl
**What this PR does / why we need it**: Updates distroless/static base images used to build cert-manager containers to the latest version. Also adds a comment explaining how to retrieve the latest version, to make this easier in the future and potentially for when we automate this in the future.
Sort-of arises from #4033 
This could also arguably be backported into new releases of v1.2 and v1.3 as our current supported versions, but I don't think that's required.
```release-note
Updates distroless/static base image to latest version as of 2021-05-20
```
=> Update distroless/static base images to latest version

test/e2e/framework/addon/vault/setup.go, test/e2e/suite/issuers/vault/certificate/approle.go, test/e2e/suite/issuers/vault/certificate/approle_custom_mount.go
This PR modifies the setup of the Vault intermediate CA used in e2e tests so that it can be optionally configured with a root CA cert (not just the intermediate) and changes Vault issuer's e2e tests to run with both configurations (and verify that the `ca.crt` contains the root if that is expected).
Note: this is a very simple fix. I started refactoring the e2e tests so that it is easier to add new config options as well as the setup of the addons, but perhaps that could be done after the `v1.4` release.
Fixes #3894 
/kind cleanup
=> e2e Vault intermediate CA optionally configured with root

pkg/controller/certificates/readiness/readiness_controller.go, pkg/controller/certificates/readiness/readiness_controller_test.go, pkg/controller/certificates/trigger/policies/policies.go, pkg/controller/certificates/util.go, pkg/controller/certificates/util_test.go
See #3897 for context.
This PR changes cert's renewBefore period to be calculated as `min(renewBefore, cert duration / 3)` where `renewBefore` is either `cert.spec.renewBefore` or 30d.
It fixes a bug, where when cert's duration is very slightly longer than the `renewBefore` period, we enter a renewal loop.
This has so far hit a number of Vault issuer's users.
**The bug:**
See the below section of cert status:
```
nextPrivateKeySecretName: example-com-l2g4c
notAfter: "2021-06-06T09:06:50Z"
notBefore: "2021-05-07T09:06:20Z"
renewalTime: "2021-05-07T09:06:50Z"
revision: 185
```
See [these functions](https://github.com/jetstack/cert-manager/blob/master/pkg/controller/certificates/util.go#L273-L294) where we calculate renewal time.
This cert has `defaultRenewBefore`=30d, …
=> Handle cert renewal correctly

pkg/controller/acmeorders/util.go, pkg/controller/certificaterequests/approver/approver.go, pkg/controller/certificaterequests/vault/vault_test.go, pkg/controller/certificates/readiness/readiness_controller.go, pkg/controller/certificates/readiness/readiness_controller_test.go, pkg/controller/certificates/trigger/policies/policies.go, pkg/controller/certificates/util.go, pkg/controller/certificates/util_test.go, pkg/controller/clusterissuers/sync_test.go, pkg/controller/ingress-shim/sync.go, pkg/controller/test/context_builder.go, pkg/ctl/scheme.go, pkg/internal/apis/certmanager/validation/certificate_for_issuer_test.go, pkg/issuer/acme/dns/acmedns/acmedns.go, pkg/issuer/acme/dns/rfc2136/provider_test.go, pkg/issuer/vault/setup.go, pkg/issuer/venafi/client/request.go, pkg/logs/logs.go, pkg/webhook/server/BUILD.bazel, pkg/webhook/server/server.go
**What this PR does / why we need it**: Fixes arising from https://github.com/cert-manager/website/issues/538 - mostly low-hanging-fruit changes and not relating to doc comments.
/kind cleanup
```release-note
Panic when failing to register schemes during initialization for pkg/webhook/server
Various static analysis fixes across many files including removing unused or redundant code
```
=> Static Analysis Fixes from Static Analysis Party

devel/addon/ingressnginx/BUILD.bazel, devel/addon/ingressnginx/install.sh
Spun out from https://github.com/jetstack/cert-manager/pull/4036
```release-note
NONE
```
/kind cleanup
=> Upgrade ingress-nginx Helm Chart and Docker image

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/service.yaml, deploy/charts/cert-manager/values.yaml
Signed-off-by: Eddie Hoffman <eddie.hoffman@truelayer.com>
This PR adds the ability to add custom labels to the controller service. This is required for some prometheus setups where metrics scraping is only carried out when a configured label is present.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3775
```release-note
Add serviceLabels to helm chart for adding custom labels to the controller service
```
=> add service labels to helm chart

deploy/crds/crd-certificates.yaml, pkg/apis/certmanager/v1/types_certificate.go, pkg/apis/certmanager/v1alpha2/types_certificate.go, pkg/apis/certmanager/v1alpha3/types_certificate.go, pkg/apis/certmanager/v1beta1/types_certificate.go
This PR is a follow up work to #4040 where cert's `renewBefore` period was changed to `min(duration/3, renewBefore)`.
This just updates `Certificate`'s `spec.duration` `spec.renewBefore` fields descriptions.
```release-note
NONE
```
=> Updates duration and renewBefore field descriptions

build/helm.bzl, deploy/charts/cert-manager/BUILD.bazel, deploy/charts/cert-manager/Chart.template.yaml
In https://github.com/jetstack/jetstack-charts/pull/15#pullrequestreview-648213790 @wallrj wrote:
> think it'd be nice to instead use the Charts.yaml annotations artifacthub.io/prerelease , so that people get to see the alphas and betas on Artifcact Hub
> 
> https://artifacthub.io/docs/topics/annotations/helm/
I hacked away at Bazel + shell script to parse the `//:version` artifact for `\d.\d.\d` to see if it is a release or a prerelease and use that to fill in in the `artifacthub.io/prerelease` annotation.
There may be a cleaner way to do this.
We're aiming to make it so that the next alpha / beta release of cert-manager doesn't show up here:
* https://artifacthub.io/packages/helm/cert-manager/cert-manager
And when 1.4.0 is finally released, that will show up. …
=> Add ArtifcactHUB pre-release annotation to the Helm chart

build/helm.bzl, deploy/charts/cert-manager/BUILD.bazel, deploy/charts/cert-manager/Chart.yaml
Reverts jetstack/cert-manager#4049
Because the Awk script fails in some environments:
```
ERROR: /home/josh/go/src/github.com/jetstack/cert-manager/build/helm.bzl:148:37: invalid escape sequence: \.. You can enable unknown escape sequences by passing the flag --incompatible_restrict_string_escapes=false
ERROR: /home/josh/go/src/github.com/jetstack/cert-manager/build/helm.bzl:148:45: invalid escape sequence: \.. You can enable unknown escape sequences by passing the flag --incompatible_restrict_string_escapes=false
```
```release-note
NONE
```
/kind bug
=> Revert "Add ArtifcactHUB pre-release annotation to the Helm chart"

deploy/charts/cert-manager/BUILD.bazel, deploy/charts/cert-manager/Chart.template.yaml
A simpler and hopefully more widely compatible version of https://github.com/jetstack/cert-manager/pull/4049 
This time I use grep and sed  with hopefully only regexp and command line options which are available on Debian / Fedora and MacOS, instead of awk, which turned out to be installed as mawk on Debian rather than gawk on Fedora.
Please test as follows:
```sh
[richard@drax cert-manager]$ bazel build //deploy/charts/cert-manager:cert-manager 
INFO: Analyzed target //deploy/charts/cert-manager:cert-manager (1 packages loaded, 9 targets configured).
INFO: Found 1 target...
Target //deploy/charts/cert-manager:cert-manager up-to-date:
bazel-bin/deploy/charts/cert-manager/cert-manager.tgz
INFO: Elapsed time: 1.170s, Critical Path: 0.68s
INFO: 7 processes: 1 internal, 6 linux-sandbox.
INFO: …
```
=> Add ArtifactHUB pre-release annotations to the Helm chart

pkg/controller/certificaterequests/acme/acme.go
This PR reverts the ACME CR controller changes in https://github.com/jetstack/cert-manager/pull/3984/files
Though I have tested that with the changes made above, ingress controllers like NGINX still work correctly, I'm not confident that we are breaking someone somewhere silently.
```release-note
REVERTS: The ACME issuer now constructs a certificate chain after signing, and populates the CertificateRequest.Status.CA with the root most certificate if available.
```
=> Reverts ACME issuer from forming a chain bundle and populating the ca.crt

devel/addon/certmanager/install.sh, pkg/controller/certificatesigningrequests/ca/ca.go, pkg/controller/certificatesigningrequests/sync.go, pkg/controller/certificatesigningrequests/util/BUILD.bazel, pkg/controller/certificatesigningrequests/util/conditions.go, pkg/controller/certificatesigningrequests/util/signername.go, test/e2e/framework/helper/BUILD.bazel, test/e2e/framework/helper/certificatesigningrequests.go, test/e2e/suite/issuers/ca/BUILD.bazel, test/e2e/suite/issuers/ca/certificatesigningrequest.go
This PR adds e2e tests for the Kubernetes CertificateSigningRequest CA Issuer. 
This also adds the field `featureGates="ExperimentalCertificateSigningRequestControllers=true"` to the `/devel/addons/cert-manager/install.sh` script for the cert-manager deployment. This enables the Kube CSR controllers for testing.
```release-note
testing: Adds Kubernetes CertificateSigningRequest CA Issuer E2E tests.
```
=> Certificate Signing Request CA e2e

test/e2e/suite/issuers/vault/certificate/approle.go, test/e2e/suite/issuers/vault/certificate/approle_custom_mount.go
With the changes made in https://github.com/jetstack/cert-manager/pull/3982 we should check the certificate chain for the Vault Issuer in E2E tests.
```release-note
NONE
```
=> Check certificate chain for Vault Issuer in E2E

Makefile, WORKSPACE, build/BUILD.bazel, build/README.md, build/container.bzl, build/images.bzl, build/release-tars/BUILD.bazel, cmd/acmesolver/BUILD.bazel, cmd/cainjector/BUILD.bazel, cmd/controller/BUILD.bazel, cmd/webhook/BUILD.bazel, hack/bin/deps.bzl, hack/build/docker.bzl
Adds a README and some comments to document how the component images are built with Bazel.
Allows to specify a different base image and whether cgo is enabled for a build.
```release-note
NONE
```
fixes #3969
=> 3969 parameterize and document image building

cmd/controller/app/controller.go, pkg/controller/test/context_builder.go, pkg/metrics/BUILD.bazel, pkg/metrics/certificates_test.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, test/integration/acme/orders_controller_test.go, test/integration/certificates/issuing_controller_test.go, test/integration/certificates/metrics_controller_test.go, test/integration/certificates/revisionmanager_controller_test.go, test/integration/certificates/trigger_controller_test.go
This PR adds a `clock_time_seconds` metric as suggested in https://github.com/jetstack/cert-manager/pull/3746
This metric allows for monitoring systems that do not have a built in time function (e.g. DataDog) to calculate the number of seconds until a certificate expires by subtracting this metric from the existing certificate_expiration_timestamp metrics.
fixes https://github.com/jetstack/cert-manager/issues/3730
Signed-off-by: kit837 <66801824+kit837@users.noreply.github.com>
```release-note
Adds clock_time_seconds metric for calculating expiration time in monitoring systems without a built in function.
```
/assign @jakexks @JoshVanL
/kind feature
=> Add clock_time_seconds metric

Makefile
Having .PHONY next to the target which it's marking helps with identifying which targets have been marked and makes it easier to spot a missing .PHONY
also, tweaks the find command to avoid piping, and cleans up a duplicated ctl target
```release-note
Minor cleanup of make targets, to prepare for more use of make in cert-mangaer
```
=> Add .PHONY next to make targets

test/e2e/framework/config/acme.go, test/e2e/framework/config/addons.go, test/e2e/suite/issuers/acme/issuer.go
Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>
**What this PR does / why we need it**: Allowing passing config for the acme tests using flags so that we can use them with the EKS cluster for testing.
```release-note
NONE
```
/assign @jakexks
=> adding flags for config in the acme issuer tests

cmd/ctl/BUILD.bazel, cmd/ctl/cmd/cmd.go, cmd/ctl/pkg/create/BUILD.bazel, cmd/ctl/pkg/create/certificatesigningrequest/BUILD.bazel, cmd/ctl/pkg/create/certificatesigningrequest/certificatesigningrequest.go, cmd/ctl/pkg/create/certificatesigningrequest/certificatesigningrequest_test.go, cmd/ctl/pkg/create/create.go, cmd/ctl/pkg/experimental/BUILD.bazel, cmd/ctl/pkg/experimental/experimental.go, pkg/api/util/kube.go
This PR adds the command:
`ctl experimental create certificatesigningrequest`
`ctl x create csr`
This behaves the same as the `ctl create certificaterequest` command, expect that it creates Kubernetes CertificateSigningRequest resources, rather than CertificateRequest resources.
Note that the `signerName` is built using the discovery API to determine whether the signer is namespaced or not.
Documentation: https://github.com/cert-manager/website/pull/615
```release-note
Adds CLI command: `ctl experimental create certificatesigningrequest` for creating a Kuberenetes CertificateSigningRequest based upon a cert-manager Certificate manifest file
```
/milestone v1.5
=> ctl experimental create certificatesigningrequest

test/e2e/suite/issuers/ca/BUILD.bazel, test/e2e/suite/issuers/ca/certificatesigningrequest.go
This PR will prevent the CertificateSigningRequest e2e tests to run if the environment variable `FEATURE_GATES` does no include `ExperimentalCertificateSigningRequestControllers=true`. This prevents tests from failing for kube versions pre 1.9.
/assign @irbekrm 
```release-note
NONE
```
=> Disable running e2e tests for CertificateSigningRequests if feature gate not enabled

pkg/controller/certificates/requestmanager/BUILD.bazel, pkg/controller/certificates/requestmanager/requestmanager_controller.go, pkg/controller/certificates/requestmanager/requestmanager_controller_test.go, pkg/controller/certificates/trigger/trigger_controller.go, pkg/controller/certificates/util.go
This PR fixes a bug where failed certificate issuance is not retried by deleting the failed `CertificateRequest` in the next issuance cycle, so that a new one gets created for the same revision.
This will then work in the same way as retrying of failed issuances when private key rotation policy is 'Always' or when it is the fist `CertificateRequest` where the failed requests _are_ deleted in the next issuance cycle [here](https://github.com/jetstack/cert-manager/blob/master/pkg/controller/certificates/requestmanager/requestmanager_controller.go#L286).
The downside is that once we implement exponential back off for failed `Certificate`s, we will no longer be able to use the static 1 hour period. But I think even then it will still make sense to …
=> 4082 Fix retrying of failed CertificateRequests

pkg/api/util/conditions.go, test/e2e/framework/helper/BUILD.bazel, test/e2e/framework/helper/certificates.go, test/e2e/suite/conformance/certificates/acme/acme.go, test/e2e/suite/conformance/certificates/suite.go, test/e2e/suite/conformance/certificates/tests.go, test/e2e/suite/conformance/certificatesigningrequests/suite.go, test/e2e/suite/conformance/certificatesigningrequests/tests.go, test/e2e/suite/issuers/acme/certificate/dns01.go, test/e2e/suite/issuers/acme/certificate/http01.go, test/e2e/suite/issuers/acme/certificate/notafter.go, test/e2e/suite/issuers/ca/certificate.go, test/e2e/suite/issuers/selfsigned/certificate.go, test/e2e/suite/issuers/vault/certificate/approle.go, test/e2e/suite/issuers/vault/certificate/approle_custom_mount.go, test/e2e/suite/issuers/venafi/tpp/certificate.go, test/e2e/suite/serving/cainjector.go, test/e2e/util/util.go
There was some duplicate WaitForCertificateReady/ WaitForCertificateIssued logic, also waiting for a status update to the same state was not possible (eg. Ready=true -> Ready=true). (part of #4128)
Other included cleanups:
- UseIngressIPAddress was added, so HTTP01 IP certificates can be tested
- some TODOs were removed from s.complete(...) & shared variables are initialized better
```release-note
```
=> cleanup tests: WaitForCertificateReady

build/go_binary.bzl
Based on https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/, adding -s and -w flags as go_binary linkops arguments reduces the binary size.
From the article:
> Interestingly, what gets stripped is only the DWARF tables needed for debuggers, not the annotations needed for stack traces, so our panics are still readable!
The cert-manager kubectl plugin's size shrinks from 68M to 43M.
Kubernetes also applies these flags when compiling their binaries; https://github.com/kubernetes/kubernetes/blob/1861e4756df1818a2d4ca60c869780bf742fff6b/hack/lib/golang.sh#L798-L804.
```release-note
reduce binary sizes by adding "-s -w" as ldflags
```
/kind feature
=> add -s and -w flags to the go_binary linkopts

LICENSES, pkg/issuer/acme/dns/cloudflare/BUILD.bazel, pkg/issuer/acme/dns/cloudflare/cloudflare.go, pkg/issuer/acme/dns/cloudflare/cloudflare_test.go
Bottomline the current implementation isn't using the official Cloudflare API for finding the nearest Zone-ID, instead it uses the generic utility method `/pkg/issuer/acme/dns/util/wait.go#FindZoneByFqdn` which tries to find the Zone by getting SOA records for the public domain. If there are any DNS-Issues (for example if your local DNS-Resolver e.g. is misconfigured or even more common - the Domain is simply incorrectly setup) and there are no SOA-Records returned then this method does not work at all. Or also common in relation with the DNS-Challenge if the Domain in question points to a LAN-Address if its just used for certification.
Furthermore FindZoneByFqdn also is bugged in that it returns the TLD as the default zone to try to access the …
=> Cloudflare: refactor DNS01 challenge to use API for finding the nearest Zone

build/go_binary.bzl
In https://github.com/jetstack/cert-manager/pull/4169, the "-w" and "-s" flags were introduced when building go binaries.
These options remove both the DWARF tables and the symbol tables from the binary. However, removing the symbols table from the binaries causes some issues https://github.com/jetstack/cert-manager/pull/4169#issuecomment-873947733.
@SgtCoDFish noticed that the binary size reduction is mostly thanks to removing the DWARF tables.
Results for the kubectl plugin:
- no flags: 74M
- "-w": 62M
- "-w", "-s": 49M
This PR removes the "-s" flag and only keeps the "-w" flag for building go binaries.
```release-note
reduce binary sizes by adding "-w" as ldflag
```
\kind feature
=> Set linkopts "-w" instead of "-w -s" when building go binaries

deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, pkg/apis/certmanager/v1/types_issuer.go, pkg/apis/certmanager/v1alpha2/types_issuer.go, pkg/apis/certmanager/v1alpha3/types_issuer.go, pkg/apis/certmanager/v1beta1/types_issuer.go, pkg/internal/apis/certmanager/types_issuer.go
| NOTE | This PR is a copy of https://github.com/jetstack/cert-manager/pull/3633 due to https://github.com/jetstack/cert-manager/pull/3633 being stale (and can't push to author's branch) |
|-|-|
/release-note-none
=> vault issuer: specify that the caBundle must be base64-encoded

pkg/controller/certificates/issuing/BUILD.bazel, pkg/controller/certificates/issuing/issuing_controller_test.go, pkg/internal/apis/certmanager/validation/certificaterequest.go, pkg/issuer/acme/dns/acmedns/acmedns_test.go, pkg/issuer/acme/dns/cloudflare/cloudflare.go, pkg/issuer/acme/dns/cloudflare/cloudflare_test.go, pkg/issuer/acme/dns/rfc2136/rfc2136.go, pkg/issuer/ca/setup.go, pkg/logs/testing/log_testing.go, pkg/util/kube/pki.go
From https://github.com/cert-manager/website/issues/538: here is the PR with my batch of linter fixes.
Suggestion: I propose to have a common `.golangci.yml` so that we all have the same linter configuration:
- `golangci-lint` would be the single binary to run,
- no need to install `staticcheck` or `golint`.
Suggestion 2: I propose to not enforce the "exported function should have a comment" as discussed [here](https://github.com/golangci/golangci-lint/issues/21).
=> Static analysis tool party: fix my batch of linter warnings

deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml, deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml
This PR changes the cert-manager webhook configuration so that the Kubernetes API server will now convert legacy versions of cert-manager custom resources to v1 before sending them to the cert-manager admission webhooks.
This will help ensure that all users have a working conversion webhook and help ensure that all legacy versions of cert-manager CRs are upgraded to v1 before we drop support for the legacy versions of the API in cert-manager v1.6 and to avoid race conditions during upgrade to v1.6.
Note:
Initially I also  removed the v1beta1 versions from accepted `AdmissionReview` versions for mutating and validating webhook and accepted `ConversionReview` version for conversion webhook as part of this PR (as a cleanup), but it no longer seems like …
=> Restrict api versions

.gitignore
On VS Code, when running `./hack/update-deps.sh`, the git menu crashes because of the large amount of changed files.
VS Code tries to keep track of all file changes, the update script introduces a lot of changes and this causes the crash.
An easy fix is to add the vendor folder to the .gitignore file.
```release-note
```
=> Fix vscode crash

WORKSPACE
Bump the version of Go SDK that Bazel downloads v1.16.5 -> v1.16.6.
I was looking at bumping Bazel Go rules at the same time, but looks like the latest release only supports Bazel v4.0.0 which we cannot use, because Bazel base images used for GCB release builds don't have a v4.0.0 version.
```release-note
NONE
```
/kind cleanup
=> Bump the version of Go SDK being downloaded

test/integration/acme/orders_controller_test.go
This fixes a dropped error in `test/integration/acme`.
```release-note
NONE
```
=> test/integration/acme: fix dropped error

cmd/ctl/BUILD.bazel, cmd/ctl/cmd/BUILD.bazel, cmd/ctl/cmd/cmd.go, cmd/ctl/main.go, cmd/ctl/pkg/check/BUILD.bazel, cmd/ctl/pkg/check/api/BUILD.bazel, cmd/ctl/pkg/check/api/api.go, cmd/ctl/pkg/check/check.go, devel/addon/certmanager/install.sh, pkg/util/BUILD.bazel, pkg/util/cmapichecker/BUILD.bazel, pkg/util/cmapichecker/cmapichecker.go, pkg/util/cmapichecker/cmapichecker_test.go
Adds the kubectl 'cert-manager check api' command.
This check attempts to perform a dry-run create of a cert-manager *v1alpha2*
Certificate resource in order to verify that CRDs are installed and all the
required webhooks are reachable by the K8S API server.
We use v1alpha2 API to ensure that the API server has also connected to the
cert-manager conversion webhook.
```release-note
Added the kubectl 'cert-manager check api' command
```
/kind feature
=> Add kubectl 'cert-manager check api' command

Makefile, hack/update-codegen.sh, test/e2e/framework/helper/certificates.go, test/e2e/framework/helper/featureset/featureset.go, test/e2e/framework/helper/validation/certificates/certificates.go, test/e2e/framework/helper/validation/validation.go, test/e2e/suite/conformance/certificates/acme/acme.go, test/e2e/suite/conformance/certificates/external/external.go, test/e2e/suite/conformance/certificates/tests.go, test/e2e/suite/conformance/certificates/vault/vault_approle.go, test/e2e/suite/conformance/certificates/venafi/venafi.go, test/e2e/suite/conformance/certificates/venaficloud/cloud.go
Adds support for checking the CA basic constraint in e2e tests, and a conformance suite test for the same.
Currently enabled only for CA and SelfSigned issuers.
There are also other minor changes to the Makefile and hack/update-codegen.sh. These changes are explained in commit messages. `ValidateIssuedCertificate` is also removed since it doesn't appear to be used anywhere; again, this is explained by the commit message.
This is the first part of implementing #2820 
```release-note
Add e2e test checks for the CA basic constraint, enabled on CA and SelfSigned issuers
```
=> CA Basic Constraint checks in e2e tests

hack/build/version.sh, hack/verify-upgrade.sh
Upgrade tests should always upgrade from latest published non-alpha/beta release.
This PR just fixes a bug where the calculation of release version in the upgrade test broke after `v1.5.0-alpha.0` was released, see https://github.com/jetstack/cert-manager/pull/4218#issuecomment-884089497
```release-note
NONE
```
=> Fix how last published release version is calculated for upgrade tests

pkg/util/pki/csr.go, pkg/util/pki/csr_test.go, pkg/util/pki/parse_test.go
See also https://github.com/jetstack/cert-manager/issues/4142
EncodeX509Chain checked for self-signed certs by comparing the subject
and issuer of the cert in question, which is invalid since it's
perfectly fine for those to match.
the correct behavior is to use cert.CheckSignatureFrom(cert). this bug
was exposed in 1.4 when ParseSingleCertificateChain started using
EncodeX509Chain in the critical path of several issuers; when end-users
had leaf certificates with subjects matching their issuer's subject, the
bug was triggered.
includes tests for EncodeX509Chain, a test for
ParseSingleCertificateChain, and some defence-in-depth measures
```release-note
Fix check for self-signed certificates in EncodeX509Chain which broke certs whose subject DN matched their issuer's subject DN
```
fixes …
=> Fix check for self-signed certs in EncodeX509Chain

hack/verify-upgrade.sh
In https://github.com/jetstack/cert-manager/pull/4205 the 'kubectl cert-manager check api' was introduced.
This can be used in `verify-upgrade.sh` and simplify that script.
```release-note
```
/kind cleanup
=> Use 'kubectl cert-manager check api' in verify-upgrade.sh

devel/addon/ingressnginx/BUILD.bazel, devel/addon/ingressnginx/install.sh, devel/addon/sample-external-issuer/install.sh, devel/addon/samplewebhook/chart/templates/apiservice.yaml, devel/cluster/create-kind.sh, devel/lib/lib.sh, test/e2e/images.bzl
This PR:
- adds an option to create an e2e test kind cluster with Kubernetes v1.22 (using `eu.gcr.io/jetstack-build-infra-images/kind:v1.22.0-beta.2` kind image)
This option would be triggered by the optional Prow presubmit `pull-cert-manager-e2e-v1-22` that's going to be added in [testing#536](https://github.com/jetstack/testing/pull/536).
- Bumps NGINX Ingress versions for e2e tests: with Kubernetes `v1.16` -  `v1.21` it now installs ingress controller image `v0.48.1`, Helm chart `v3.34.0`.  With Kubernetes v1.22 ingress controller image `v1.0.0-alpha.2`, Helm chart `v3.34.0`
- Bumps version of sample external issuer used in e2e tests `v0.1.0` -> `v0.1.1`
```release-note
NONE
```
/kind cleanup
Signed-off-by: irbekrm …
=> Adds an option to build k8s 1.22 kind cluster

pkg/controller/certificatesigningrequests/ca/ca_test.go, pkg/controller/certificatesigningrequests/controller_test.go, pkg/controller/certificatesigningrequests/selfsigned/selfsigned_test.go, pkg/controller/certificatesigningrequests/sync.go, pkg/controller/certificatesigningrequests/vault/vault_test.go, pkg/controller/certificatesigningrequests/venafi/venafi_test.go
Signed-off-by: joshvanl <vleeuwenjoshua@gmail.com>
/assign @maelvls 
/milestone v1.5
/kind feature
```release-note
Fire event when a CertificateSigningRequest has not yet been approved, so will skip processing until it is.
```
=> Fire event when CertificateSigningRequest hasn't been Approved yet

pkg/controller/acmeorders/controller.go, pkg/controller/certificates/trigger/trigger_controller.go, pkg/scheduler/BUILD.bazel, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
A memory leak was identified in #4224. I found out that it was caused by our scheduler that was not stopping its timers. We probably thought that [timer.Stop](https://pkg.go.dev/time#Ticker.Stop) would close the `timer.C` channel, but it does not as per the documentation:
> Stop turns off a ticker. After Stop, no more ticks will be sent. Stop does not close the channel, to prevent a concurrent goroutine reading from the channel from seeing an erroneous "tick".
[This go playground](https://play.golang.org/p/jTqwrumTqly) example shows that `timer.C` is never closed.
I wrote a unit test to show the leakage:
```sh
% go test ./pkg/scheduler
--- FAIL: Test_afterFunc (0.22s)
--- FAIL: Test_afterFunc/stop_works (0.12s)
scheduler_test.go:56: 3 goroutines before, 10003 goroutines after …
```
=> Memory leak: fix the scheduler's goroutine leakage

pkg/controller/certificaterequests/approver/sync.go, pkg/controller/certificates/internal/secretsmanager/secret.go
cert-manager keeps crashing every now and then on clusters with more than 1000 certificates due to a bug of concurrent read and write of Secret annotations as detailed in https://github.com/jetstack/cert-manager/issues/3664. This bug was introduced in v0.15.0 (https://github.com/jetstack/cert-manager/commit/ffb5201d95b25861168df8dec26138878e5bcad0) and affect all cert-manager versions since then.
The panic can be reproduced by creating and constantly renewing 5000 certificates:
<details>
<summary>🎩 Steps to reproduce the panic (takes about 1 minute to see a panic)</summary>
```sh
#! /bin/bash
#
set -e
k3d cluster create bomb
helm upgrade --install cert-manager jetstack/cert-manager --version 1.4.0 --namespace cert-manager --set installCRDs=true --create-namespace --wait
kubectl wait …
```
=> Data race: fix concurrent read and write of secret annotations and certificaterequests

test/e2e/framework/helper/certificates.go, test/e2e/suite/serving/cainjector.go, test/e2e/util/util.go
This PR should resolve most of the flakes that look similar to "Operation cannot be fulfilled on certificates.cert-manager.io \"serving-certs\": the object has been modified; please apply your changes to the latest version and try again".
This flake is caused by the Issuing=True certificate condition that is removed by the issuing controller.
The best fix is to wait for the Issuing=True certificate condition to get removed when waiting for the certificate to become ready.
```release-note
```
/kind bug
=> Resolve test flakes "the object has been modified"

design/20210209.certificates.k8s.io-adoption.md
This PR contains a design document for adding support for `certificates.k8s.io` `CertificateSigningRequests`
related: https://github.com/jetstack/cert-manager/issues/3473
/cc @jetstack/team-cert-manager @munnerz @meyskens 
```release-note
NONE
```
=> DESIGN: certificates.k8s.io Adoption

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/webhook-service.yaml, deploy/charts/cert-manager/values.yaml
Signed-off-by: Marco Ortega <mortega@brightcove.com>
My company the Kubernetes administrator enforces the resource labeling and I'm not able to install cert-manager using helm so this PR enables the option to add custom serviceLabels for the webhook service. 
Hello @irbekrm, I closed the previous PR to add my signoff.
```release-note
Allows to configure labels on cert-manager webhook service via a Helm value.
```
=> Enabling serviceLabels for webhook service.

pkg/internal/vault/vault_test.go, pkg/util/pki/parse.go, pkg/util/pki/parse_test.go
This fixes the issue detailed [here](https://github.com/jetstack/cert-manager/pull/4195#issuecomment-887512357) in #4195. That PR focused on Vault, but this issue is actually more widely applicable; it's not valid to trim anything except a root certificate from a chain.
This is raised as a separate PR to be clear that it's widely applicable to all issuer types which use ParseSingleCertificateChain, and to speed development, aiming to merge before 1.5 and possibly cherry-pick into 1.4
/kind bug
```release-note
- Fix handling of chains which don't have a root in ParseSingleCertificateChain, and improve handling in situations where that function is passed a single certificate.
```
=> CA chain fix without root

pkg/scheduler/BUILD.bazel, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
For release-1.3
As mentioned in #4271 and in the cert-manager biweekly meeting on 28/07, this PR cherrypicks two commits from #4233 which fix memory leaks.
The two commits are taken from:
- https://github.com/jetstack/cert-manager/commit/eb947f98eaea83cc5b660f805daba2b6f109502b
- https://github.com/jetstack/cert-manager/commit/8e872632f4a1ab7536ade7163ff9d9c21ee01ed1
/kind bug
```release-note
Fixed a goroutine leak that was causing the controller's memory usage to grow with time
```
=> [release-1.3] Cherry-pick memory leak fixes into 1.3

pkg/controller/acmeorders/controller.go, pkg/controller/certificates/trigger/trigger_controller.go, pkg/scheduler/scheduler.go
~~As [pointed out](https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1627484902047400?thread_ts=1627481906.043900&cid=CDEQJ0Q8M) by @munnerz, we feel not very confident in back-porting #4233 knowing that `Forget` is called on all three event types (`Deleted`, `Updated`, `Added`). We had [a discussion](https://github.com/jetstack/cert-manager/pull/4233/files#r675442778) about that with @irbekrm. I changed this in f03d48f, where the only event on why we run `Forget` is `Deleted`.~~
After tonight's biweekly dev meeting, @wallrj asked the team why we would not accept backporting the `Forget` fix (641960b) in 1.4.2 and 1.3.2 but still accept it in 1.5.
The team agrees on the fact that it needs more testing (since it is not tested at all). I thus suggest we revert the untested `Forget` change …
=> Revert the `Forget` call that was happening on every Certificates and Orders sync

pkg/scheduler/BUILD.bazel, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
For release-1.4
As mentioned in #4271 and in the cert-manager biweekly meeting on 28/07, this PR cherrypicks two commits from #4233 which fix memory leaks.
The two commits are taken from:
- https://github.com/jetstack/cert-manager/commit/eb947f98eaea83cc5b660f805daba2b6f109502b
- https://github.com/jetstack/cert-manager/commit/8e872632f4a1ab7536ade7163ff9d9c21ee01ed1
/kind bug
```release-note
Fixed a goroutine leak that was causing the controller's memory usage to grow with time
```
=> [release-1.4] Cherry-pick memory leak fixes into 1.4

test/integration/conversion/conversion_test.go, test/integration/framework/BUILD.bazel, test/integration/framework/apiserver.go
Changes admissionregistration.k8s.io from v1beta1 to v1 in integration tests as they are no longer served in 1.22. v1 has been available since 1.16.
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#webhook-resources-v122
With the changes to controller-runtime, our client to the api-server used for integration tests now has real user info :)
The conversion integration tests have been updated to now reflect the inclusion of the user info fields in the CertificateRequests after they have been plumbed through the webhook.
/milestone v1.5
/kind cleanup
```release-note
NONE
```
=> Change admissionregistration.k8s.io v1beta1 to v1 in integration tests

devel/cluster/create-kind.sh
See:
https://console.cloud.google.com/gcr/images/jetstack-build-infra-images/EU/kind@sha256:fa600aa4b8234235e141fab085126e2a72c3d8f05eed44d38bf343091c51d192/details?tab=info
```release-note
NONE
```
=> Updates the kind cluster for v1.22 to v1.22.0-rc.0

build/images.bzl
Bumps base image versions.
Perhaps worth looking at automating this.
```release-note
NONE
```
=> Bump base image versions

test/e2e/framework/helper/featureset/featureset.go, test/e2e/suite/conformance/certificates/acme/acme.go, test/e2e/suite/conformance/certificates/suite.go, test/e2e/suite/conformance/certificates/tests.go
Signed-off-by: Arsh Sharma <arshsharma461@gmail.com>
```release-note
NONE
```
=> adding a new feature set for Public ACME servers

deploy/charts/cert-manager/templates/service.yaml
Signed-off-by: Fran Sanjuán <francesc.sanjuan@marfeel.com>
If applied, this PR will add a name to service port used for Prometheus scraping.
This will make the service follow Istio's requirements about port naming for explicit protocol selection.
https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection
```release-note
Add a name to Prometheus scraping service port
```
=> Add a name to Prometheus scraping service port for Istio compatibillity

BUILD.bazel, build/BUILD.bazel, deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/_helpers.tpl, deploy/charts/cert-manager/templates/startupapicheck-job.yaml, deploy/charts/cert-manager/templates/startupapicheck-rbac.yaml, deploy/charts/cert-manager/templates/startupapicheck-serviceaccount.yaml, deploy/charts/cert-manager/values.yaml, deploy/crds/BUILD.bazel, deploy/manifests/BUILD.bazel, devel/addon/certmanager/BUILD.bazel, devel/addon/certmanager/install.sh, hack/verify-upgrade.sh
Add `startupapicheck` Job that waits for the cert-manager api to become ready.
This Job can be awaited for by adding the `--wait` flag to the `helm install` command.
Alternatively, the following kubectl command can be used to wait for the cert-manager api to be ready:
```bash
kubectl wait -n cert-manager --for=condition=complete job/cert-manager-startupapicheck
```
fixes #4155
```release-note
Added a startup api check Job that waits for the cert-manager api to become ready
```
/kind feature
=> Add startup api check Job

test/e2e/util/util.go
Current the tests output:
```
Expected Certificate serving-certs condition Ready=True but it has: 0
```
Instead the conditions should be printed.
```release-note
```
/kind bug
=> Correctly print conditions during tests

deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/templates/webhook-service.yaml
Actually it's a [k8s bug](https://github.com/kubernetes/kubernetes/commit/dab511224020f6f7a896560d7c48770187a683c1).
In order to allow server side apply in most running clusters currently, we have to explicitly specify port `protocol` field in yaml manifest.
**Which issue this PR fixes**: fixes #4020 
This is the result after specifying the protocol field in the manifest:
```sh
$ k apply --server-side -f cert-manager.yaml
customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io serverside-applied
customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io serverside-applied
customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io serverside-applied …
```
=> explicitly specify port protocol field to allow server side apply

devel/cluster/create-kind.sh
Makes the v1.22 e2e tests run with a KIND image built with the just released `v1.22` Kubernetes.
https://console.cloud.google.com/gcr/images/jetstack-build-infra-images/EU/kind@sha256:2e335fce9c7b1d9be39042e46dc604264143c349f56cd7f566b03d0ccb7bd5e2/details?tab=info&project=jetstack-build-infra-images&authuser=1&organizationId=108816157281
```release-note
NONE
```
/kind cleanup
=> Bump k8s v1.22 test image sha

CODE_OF_CONDUCT.md, deploy/charts/cert-manager/Chart.yaml
This fix was made for cert-manager 1.4 in #4038  but wasn't backported; the old maintainer email was noticed while releasing 1.3.2.
Cherry picking this commit to update the maintainer email for 1.3.3.
/release-note-none
/kind cleanup
```release-note
NONE
```
=> [release-1.3] Update old references to replaced/obsolete email addresses

test/e2e/suite/conformance/certificates/venafi/venafi.go, test/e2e/suite/conformance/certificatesigningrequests/venafi/tpp.go, test/e2e/suite/issuers/venafi/tpp/certificate.go, test/e2e/suite/issuers/venafi/tpp/certificaterequest.go
Disable the TPP E2E tests while we resolve a problem with the TPP server.
They can be run manually with /test pull-cert-manager-e2e-v1-20-feature-issuers-venafi-tpp
xref: https://github.com/jetstack/cert-manager/issues/3555
```release-note
NONE
```
=> Disable the TPP E2E tests

deploy/charts/cert-manager/README.template.md
Updates the helm chart for release-1.3 to highlight the correct version range it supports, and to point out that it won't work with
Kubernetes 1.22+
Part of #4076 
```release-note
Clarify the exact supported kubernetes version range for cert-manager 1.3
```
=> [release-1.3] Helm Chart k8s compat update

deploy/charts/cert-manager/README.template.md
Make supported Kubernetes version in helm chart readme match: https://cert-manager.io/docs/installation/supported-releases/
fixes https://github.com/jetstack/cert-manager/issues/4076
```release-note
NONE
```
=> Fix chart prerequisites Kubernetes version

deploy/charts/cert-manager/README.template.md
Updates the helm chart for release-1.4 to highlight the correct version range it supports, and to point out that it won't work with
Kubernetes 1.22+
Part of #4076
/kind cleanup
```release-note
Clarify the exact supported kubernetes version range for cert-manager 1.4
```
=> [release-1.4] Helm chart k8s compat update

pkg/issuer/acme/http/http.go
As discussed in standup 2021-08-05.
```release-note
Adds an explicit 10 second timeout when checking HTTP01 challenges for reachability
```
=> Adds an explicit timeout when pre-checking HTTP-01 challenges

cmd/controller/app/BUILD.bazel, cmd/controller/app/controller.go, cmd/controller/app/options/options.go, devel/addon/certmanager/install.sh, devel/run-e2e.sh, pkg/feature/features.go
After discussion in the stand-up and on slack, the gateway-api support is now gated behind `--feature-gate=ExperimentalGatewayAPISupport=true`
Adds an alpha-level feature gate for enabling the gateway-shim and the gateway HTTPRoute ACME HTTP-01 challenge solver.
The cert-manager controller will now crash with the following error if the feature gate is enabled but the gateway API CRDs are not installed: `the Gateway API CRDs do not seem to be present, but ExperimentalGatewayAPISupport is set to true. Please install the gateway-api CRDs.`
```release-note
Support for the sig-network Gateway API is gated behind the --feature-gates=ExperimentalGatewayAPISupport=true command line flag on the …
```
=> Put Gateway-API support behind a feature-gate.

deploy/charts/cert-manager/README.template.md
* Fix helm install command to install version correct for version of CRDs installed
* Fix helm install command to not use `--name` which was deprecated between helm 2.x(past End of LIfe) and helm 3.x
* ```
$ helm version
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"dirty", GoVersion:"go1.16.5"}
$ helm install --name my-release --namespace cert-manager jetstack/cert-manager
Error: unknown flag: --name
```
fixes: https://github.com/jetstack/cert-manager/issues/4077
```release-note
NONE
```
=> Fix chart readme install command

.github/workflows/release.yml, .krew.yaml
The krew-release-bot action will use the `GITHUB_REF` envvar to detect the tag; that envvar is set to the tag corresponding to the release according to the [release event docs](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release).
The [release event](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release) is set to `released` so that it's not triggered on a prerelease (like a beta or alpha). The docs also state:
>  Note: The release event is not triggered for draft releases.
So we should be safe when doing our draft releases during the release process.
`.krew.yaml` was generated with [krew-release-bot-helper](https://rajatjindal.com/tools/krew-release-bot-helper/)
Fixes #4193 
/kind feature
```release-note
Add automatic krew …
```
=> add krew automation for releases

BUILD.bazel, cmd/ctl/pkg/install/install.go, test/integration/ctl/BUILD.bazel, test/integration/ctl/ctl_install.go, test/internal/apiserver/envs.go, test/internal/util/BUILD.bazel, test/internal/util/paths.go
Integration tests are failing with a timeout error due to newly released Helm chart.
The integration test is performed against a fake kubernetes api-server, and the test only checks if the resources are created correctly.
The resources are not used to really deploy cert-manager in the tests, that is why we have to disable the post-install checks.
The newly-added post-install Helm hook in the v1.5 release was not yet disabled in the test; this causes a timeout error.
This PR disables the post-install Helm hook for the integration test.
Also included: use local chart instead of published chart in the integration test -> this should prevent this problem in the future
```release-note
NONE
```
/kind bug
=> Don't wait for hooks in `kubectl cert-manager x install` integration test

devel/cluster/create-kind.sh
This PR makes the script that spins up kind cluster for tests use the official kind image for Kubernetes v1.22 instead of our own build as there now is one available.
Once this gets merged it might make sense to run v1.22 tests by default on presubmits instead of v1.21.
```release-note
NONE
```
/kind cleanup
=> Use the official kind image for testing against Kubernetes v1.22

cmd/webhook/app/testing/BUILD.bazel, cmd/webhook/app/testing/testwebhook.go, pkg/api/testing/BUILD.bazel, pkg/webhook/server/server.go, test/integration/acme/orders_controller_test.go, test/integration/certificates/issuing_controller_test.go, test/integration/certificates/metrics_controller_test.go, test/integration/certificates/revisionmanager_controller_test.go, test/integration/certificates/trigger_controller_test.go, test/integration/conversion/conversion_test.go, test/integration/ctl/ctl_create_cr_test.go, test/integration/ctl/ctl_install.go, test/integration/ctl/ctl_renew_test.go, test/integration/ctl/ctl_status_certificate_test.go, test/integration/framework/BUILD.bazel, test/integration/framework/apiserver.go, test/integration/framework/helpers.go, test/integration/validation/certificaterequest_test.go, test/integration/webhook/dynamic_authority_test.go, test/integration/webhook/dynamic_source_test.go, test/internal/apiserver/BUILD.bazel
The integration tests are still flaky and are hard to debug. This PR makes the tests use the correct context everywhere. The logic for adding cert-manager CRDs on startup has been updated also: now, no restart of the api-server is required.
BONUS: changed bazel to have build dependencies linked to the right files.
BONUS 2: the test-duration improved significantly by doing this cleanup:
before:
```
//test/integration/acme:go_default_test                                  PASSED in 31.5s
//test/integration/certificates:go_default_test                          PASSED in 149.5s
//test/integration/conversion:go_default_test                            PASSED in 126.1s
//test/integration/ctl:go_default_test                                   PASSED in 156.0s …
```
=> Integration tests cleanup

cmd/ctl/pkg/install/install.go, test/internal/util/paths.go
Integration tests are failing with a timeout error due to newly released Helm chart.
The integration test is performed against a fake kubernetes api-server, and the test only checks if the resources are created correctly.
The resources are not used to really deploy cert-manager in the tests, that is why we have to disable the post-install checks.
The newly-added post-install Helm hook in the v1.5 release was not yet disabled in the test; this causes a timeout error.
This PR disables the post-install Helm hook for the integration test.
Also included: use local chart instead of published chart in the integration test -> this should prevent this problem in the future
part 1: #4342
```release-note
NONE
```
/kind bug
=> Don't wait for hooks in kubectl cert-manager x install integration test (part 2)

deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, pkg/apis/acme/v1beta1/types_issuer.go
As reported in #4352 
/kind bug
```release-note
Fix CRDs which were accidentally changed in cert-manager v1.5.0
```
=> Fix mistakenly changed CRDs for v1beta1

pkg/util/versionchecker/testdata/BUILD.bazel
The `git_tags` genrule generates other outputs depending on the released git tags for cert-manager.
Bazel however, thinks that this genrule can be cached (no `srcs` attribute & no changes to the rule).
This fix adds the `stamp = 1` option to the `git_tags` genrule, this option makes sure that the rule is re-run when `bazel-out/stable-status.txt` changes (more info: https://docs.bazel.build/versions/main/user-manual.html#workspace_status).
fixes https://github.com/jetstack/cert-manager/issues/4350
```release-note
NONE
```
/kind bug
=> rerun git tags command when //:version changes

cmd/cainjector/app/BUILD.bazel, cmd/cainjector/app/start.go, cmd/controller/app/options/BUILD.bazel, cmd/controller/app/options/options.go, cmd/util/BUILD.bazel, cmd/util/defaults.go
As discussed in #2362, this makes the defaults for leader election parameters consistent across controllers
I don’t think it actually fixes #2362, but it can help mitigate cainjector crashing due to apiserver being slow.
```release-note
The defaults for leader election parameters are now consistent across cert-manager and cainjector.
```
=> Make leader election defaults consistent

.github/workflows/release.yml, .krew.yaml
Tested in a separate repo, this tag filter pattern won't trigger for our prereleases.
Also adds the arm64 darwin image to our `.krew.yaml`, and references the krew-release-bot by hash.
It's preferable to have the workflow be triggered on a release rather than a tag but unless I'm missing something that doesn't seem to be an easy thing to configure. 
/kind cleanup
```release-note
NONE
```
=> update trigger for gh action, add arm64 darwin for krew

test/e2e/framework/addon/venafi/cloud.go
The Venafi Cloud e2e tests are currently creating an issuer that uses the v1 Venafi Cloud endpoint.
It looks like that now fails and v2 appears to be the new default.
We should really change the defaults, but it would be good to verify that this will work and unblock the CI first.
```release-note
NONE
```
=> Explicitly set Venafi Cloud e2e tests to use v2 endpoint

pkg/issuer/acme/http/ingress.go
While upgrading from v1beta1 Ingress to v1 Ingress, the PathType was hardcoded to exact, which broke compatibility with Ingress-GCE.
This changes the PathType to ImplementationSpecific, which is the same behaviour as omitting it in a v1beta1 Ingress.
**Which issue this PR fixes**: fixes #4371 
For what it's worth, this means ingress-gce is not a valid Ingress controller, as controllers must support all 3 valid path types. 
```release-note
Fix regression in Ingress PathType introduced in v1.5.0
```
=> Fix regression in ACME HTTP-01 Ingress Solver introduced in v1.5.0

deploy/crds/crd-certificaterequests.yaml, deploy/crds/crd-certificates.yaml, deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, deploy/crds/crd-orders.yaml
This PR removes `status` fields from CRD configs, so that they don't clash with configuration tools that enforce that `status` fields should not be pre-defined.
See [controller-tools#456](https://github.com/kubernetes-sigs/controller-tools/issues/456) for context.
**Which issue this PR fixes**  fixes #4376 
I've checked that running `./hack/update-all.sh` don't put the statuses back and running `./hack/verify-crds.sh` doesn't fail.
The statuses of the created CRDs don't seem differ with this change:
```
status:
acceptedNames:
categories:
- cert-manager
kind: CertificateRequest
listKind: CertificateRequestList
plural: certificaterequests
shortNames:
- cr
- crs
singular: certificaterequest
conditions:
- …
```
=> Removes status fields from CRD definitions

pkg/controller/BUILD.bazel, pkg/controller/util.go
This PR changes the utility function that enqueues the owner of a resource to not error, but instead log an info message if it does not find the owner in the informers cache.
This is to fix a situation where at the time when the controller is started (often after cert-manager upgrade, when folks are watching the logs) owned resources' handlers run when the owners are not yet in cache and cert-manager throws errors.
In the 'certificaterequests' control loop, [we watch for changes to `Order`s](https://github.com/jetstack/cert-manager/blob/master/pkg/controller/certificaterequests/acme/acme.go#L69) and reconcile the owning `CertificateRequest`. The owning `CertificateRequest` is obtained by [getting it from the informers' …
=> Improve owner not found errors

deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, pkg/apis/acme/v1/types_issuer.go, pkg/apis/acme/v1alpha2/types_issuer.go, pkg/apis/acme/v1alpha3/types_issuer.go, pkg/apis/acme/v1beta1/types_issuer.go, pkg/internal/apis/acme/types_issuer.go, pkg/issuer/acme/http/service.go, pkg/issuer/acme/http/service_test.go
Prior to v1.5.0, not setting the service type on an Ingress solver meant that cert-manager created a NodePort service. This was accidentally changed to empty (ClusterIP) in 1.5.
This PR restores the previous behaviour and adds a test to ensure this doesn't happen again.
**Which issue this PR fixes**: fixes #4370 
```release-note
Fixed the HTTP-01 solver creating ClusterIP instead of NodePort services by default.
```
=> Regression: restore the previous service type defaulting behaviour

pkg/controller/certificaterequests/acme/acme_test.go, pkg/controller/certificaterequests/ca/ca_test.go, pkg/controller/certificaterequests/venafi/venafi_test.go, pkg/controller/certificatesigningrequests/ca/ca_test.go, pkg/util/pki/csr.go, pkg/util/pki/csr_test.go, pkg/util/pki/generate_test.go, pkg/util/pki/kube_test.go, pkg/webhook/authority/authority.go, pkg/webhook/server/tls/dynamic_source.go, pkg/webhook/server/tls/file_source_test.go
Basically all modern X.509 certs are version 3, but confusingly to specify "version 3" in an encoded cert, the version number is actually 2.
For PKCS#10 CSRs, the only valid version is 1, which again confusingly has the value "0" when encoded.
This was incorrect in many places, including one place in which the version number on a CSR was used as a certificate's version number, when the two are entirely unrelated.
Go ignores these values, so there's no functional changes here; still, it's better to be accurate.
Go ignoring CSR version and specifying 0: https://cs.opensource.google/go/go/+/refs/tags/go1.17:src/crypto/x509/x509.go;l=1958
Go ignoring Certificate version and specifying 2: https://cs.opensource.google/go/go/+/refs/tags/go1.17:src/crypto/x509/x509.go;l=1534
PKCS#10 CSR …
=> Fix manually specified Certificate and CertificateRequest versions

cmd/ctl/pkg/create/certificaterequest/certificaterequest.go, cmd/ctl/pkg/create/certificaterequest/certificaterequest_test.go, cmd/ctl/pkg/inspect/secret/util.go, cmd/webhook/app/testing/testwebhook.go, pkg/controller/cainjector/setup.go, pkg/internal/vault/vault_test.go, pkg/issuer/acme/dns/clouddns/clouddns.go, pkg/issuer/acme/http/http.go, pkg/webhook/server/server.go, pkg/webhook/server/tls/file_source.go, pkg/webhook/server/tls/file_source_test.go, test/acme/dns/options.go, test/e2e/e2e.go, test/e2e/framework/addon/chart/addon.go, test/integration/certificates/metrics_controller_test.go, test/integration/ctl/ctl_convert_test.go, test/integration/ctl/ctl_create_cr_test.go, test/integration/framework/apiserver.go, tools/cobra/main_test.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
N/A
No breaking change introduced.
```release-note
refactor: move from io/ioutil to io and os package
```
/kind cleanup
=> refactor: move from io/ioutil to io and os package

pkg/controller/certificates/util.go, pkg/controller/certificates/util_test.go
See #4345 and [Slack](https://kubernetes.slack.com/archives/C4NV3DWUC/p1628851369196000) for context.
It appears like in cases where a certificate has a slightly skewed duration, the certs don't get renewed.
This seems to happen because the renewal time value on the `Certificate` is truncated to the nearest second, whereas [the function we use to calculate renewal time](https://github.com/jetstack/cert-manager/blob/master/pkg/controller/certificates/util.go#L293-L312), returns a value to higher precision.
We use the truncated renewal time from the certificate's status when we re-queue `Certificate` for renewal [here](https://github.com/jetstack/cert-manager/blob/master/pkg/controller/certificates/trigger/trigger_controller.go#L168), but then when it has been popped from the queue at the …
=> Fix renewalTime skew issue

devel/run-e2e.sh, test/e2e/e2e_test.go, test/e2e/suite/conformance/certificates/venaficloud/cloud.go
This PR:
- allows for `GINKGO_SKIP`/`GINKGO_FOCUS` env vars to be passed from CI so particular tests can be skipped (see i.e AWS tests that are all marked as red since they cannot run the Gateway tests)
- Re-instates Venafi Cloud tests that should now be passing (they are already being run for `CertificateSigningRequest`s)
It does not change the existing way of skipping Gateway tests for k8s below `v1.19`.
Related PR- [testing#522](https://github.com/jetstack/testing/pull/552) where the `GINKGO_FOCUS`, `GINKGO_SKIP` env vars are used to ensure only specific test suites are run in aws tests.
```release-note
NONE
```
=> Ginkgo skip/focus can be optionally passed in from CI

deploy/charts/cert-manager/templates/startupapicheck-psp-clusterrole.yaml, deploy/charts/cert-manager/templates/startupapicheck-psp-clusterrolebinding.yaml, deploy/charts/cert-manager/templates/startupapicheck-psp.yaml, deploy/charts/cert-manager/values.yaml, hack/verify-chart-version.sh
Adds the PSP and related RBAC resources for the Startup API Check job, new job in 1.5.0 but missing these resources.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4361 
```release-note
Pod Security Policy for startup api check job
```
=> Add startup api check job PSP

pkg/acme/accounts/BUILD.bazel, pkg/acme/accounts/client.go
At some point we removed the ACME logging middlware to the client factory. This was important for me when trying to debug what calls cert-manager was making to ACME servers and in which order.
This PR re-adds to logging wrapper to all new ACME client, which logs at trace level.
/milestone v1.6
```release-note
Adds middleware logging back to ACME client for debugging
```
=> Adds the ACME client middleware when create an ACME account

devel/addon/ingressnginx/install.sh, devel/lib/lib.sh, hack/BUILD.bazel, hack/bin/BUILD.bazel, hack/bin/deps.bzl, hack/update-deps-licenses.sh, hack/update-deps.sh, hack/verify-deps-licenses.sh, hack/verify-staticcheck.sh, hack/verify-upgrade.sh
This PR adds a [new Bazel `config_setting`](https://docs.bazel.build/versions/main/configurable-attributes.html) `darwin_arm` that gets selected when host's cpu is `darwin_arm64`  to download darwin/arm builds of tools we use in various scripts.
This _should_ allow darwin/arm users to run all the `./hack/update-*` and `./hack/verify-*` scripts except for the staticcheck one.
This will not yet allow darwin/arm users to run `bazel test //...` because the `kube-apiserver` and `etcd` are still currently downloaded only for linux/amd, darwin/amd. [There are no darwin/arm builds for those](https://console.cloud.google.com/storage/browser/kubebuilder-tools;tab=objects?prefix=&forceOnObjectsSortingFiltering=false).  We may be able to build those directly by …
=> Update and verify scripts can be run from darwin-arm64

deploy/charts/cert-manager/values.yaml
I've  configured the post-install hook deletion policy to be `before-hook-creation,hook-succeeded` so that you can re-run the `helm install` command despite any previous helm install failures which leave behind the hook resources.
https://helm.sh/docs/topics/charts_hooks/#hook-deletion-policies
I decided to use `before-hook-creation` rather than `hook-failed` because I thought it is useful to be able to see and diagnose the failed hook resources if they fail....as they have done in 
* https://github.com/jetstack/cert-manager/issues/4361
Here's the output of `helm install` after a previous failed install left behind startupapicheck resources:
```sh
$ helm install cert-manager bazel-bin/deploy/charts/cert-manager/cert-manager.tgz --set installCRDs=true --wait --set image.tag=v1.5.3 --set …
```
=> Cleanup hook resources from previous failed installs

Makefile
While looking into [issue 3648](https://github.com/jetstack/cert-manager/issues/3648) I've found that `build` and `release_tars` are not mentioned in `make help`
Comments get outdated pretty fast. Another solution for `make help` that is super powerful is here: [Alacritty's Makefile Help](https://github.com/alacritty/alacritty/blob/master/Makefile#L29-L30). It moves the comments closer to the targets.
No code change.
=> Add help entry for build and release_tars in Makefile

build/images.bzl
`reg` isn't trivially installable with `go install`, and `go get` now has a deprecation warning. `crane` solves this issue!
I was alerted to this by the automated reminder as part of #4033 
/kind cleanup
```release-note
Update cert-manager base image versions
```
=> Update base images + update instructions for checking

pkg/internal/vault/vault.go
/kind bug
/area vault
/milestone v1.6
/assign @irbekrm 
Fixes #4011 
```release-note
FIX: Prevent Vault Client from panicing when request to Vault health endpoint fails.
```
Should we consider this for backporting?
=> Vault internal client should check health conn err before checking response status

pkg/issuer/acme/dns/cloudflare/cloudflare.go, pkg/issuer/acme/dns/cloudflare/cloudflare_test.go
Error messages (e.g., invalid access token) returned by the Cloudflare API were being swallowed with a blanket and misleading message ("Found no Zones for domain ..."). This PR exposes the last network or API error message from the request/response to the user in the form:
```
while attempting to find Zones for domain _acme-challenge.sub.domain.
while querying the Cloudflare API for GET "/zones?name=_acme-challenge.sub.domain"
Error: 9109: Invalid access token
```
This PR also allows live testing using a Cloudflare API token (which are more tightly scoped than API keys). 
Probably not the best way to do this, but I'm a golang newbie and didn't want to dive in to completely re-writing error handling for the whole …
=> Clouldflare: Show API error messages (e.g., invalid access token)

cmd/ctl/pkg/status/certificate/certificate_test.go, pkg/metrics/acme.go, pkg/metrics/certificates.go, pkg/metrics/certificates_test.go, pkg/metrics/metrics.go, test/integration/certificates/metrics_controller_test.go, test/unit/gen/certificate.go
Adds an additional RenewBefore metric to certificates. This allows for finer grained alerting of certificate issues. If a certificate has not been renewed before its RenewBefore time an alert can be triggered. This is helpful for clusters where certificates may have different lifetimes.
```release-note
Add Certificate RenewBefore prometheus metrics
```
=> Add Certificate RenewBefore prometheus metrics

build/platforms.bzl, hack/bin/BUILD.bazel, hack/bin/deps.bzl
Adds support for running `bazel build //...` and `bazel test //...` on M1 macs successfully. This requires Bazel version v4.2.1 to work, or otherwise requires a full Xcode installation alongside Bazel v4.1.x.
**Which issue this PR fixes**: fixes #3804
For any binaries that _don't_ offer a darwin/arm64 build, I've just used the darwin/amd64 version instead on the assumption that Rosetta 2 is installed/available.
I've also noticed some issues with `verify-errexit` that I can't seem to place.. I don't _think_ this is specific to M1, though I've not had chance to test yet :)
```release-note
Add support for building & developing on M1 macs
```
=> Add support for building all Bazel targets on M1 macs

hack/verify-upgrade.sh
This PR bumps timeout to wait for cert-manager API to become ready in upgrade test 1min -> 2min (we've seen a bunch of upgrade test failures recently https://testgrid.k8s.io/jetstack-cert-manager-master#ci-cert-manager-upgrade and #4579 ).
The lease duration is [1minute](https://github.com/jetstack/cert-manager/blob/master/cmd/util/defaults.go#L26), but I guess since it is retried [every 15s](https://github.com/jetstack/cert-manager/blob/master/cmd/util/defaults.go#L28), the actual period the cainjector is waiting to become leader after an upgrade can be longer, see logs below:
```
I1101 04:15:52.080481       1 leaderelection.go:248] attempting to acquire leader lease kube-system/cert-manager-cainjector-leader-election...
I1101 04:17:05.997851       1 leaderelection.go:258] successfully …
```
=> Bumps timeout to wait for cm api in upgrade test

build/images.bzl
Backport from #4588, done manually because of a merge conflict
/kind cleanup
```release-note
NONE
```
=> [release-1.5] Bump base images to latest versions

deploy/charts/cert-manager/templates/servicemonitor.yaml
`servicemonitor`'s `namespaceSelector` defaults to the namespace that the ServiceMonitor is in. Avoid specifying it if we don't need to.
```release-note
NONE
```
=> No need to specify namespaceSelector when in same namespace

devel/addon/kyverno/install.sh, test/e2e/images.bzl
This PR takes the first two commits from #4507 and commits them separately. This fixes an immediate problem where the installation of kyverno is just completely broken.
#4507 is still something we should do, but because of the [seccompProfile issue](https://github.com/jetstack/cert-manager/pull/4507#issuecomment-940786514) it'll take a little more work; this fix is needed now.
/kind cleanup
```release-note
NONE
```
=> Fix kyverno images for CI

deploy/charts/cert-manager/templates/_helpers.tpl, deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/cainjector-psp-clusterrole.yaml, deploy/charts/cert-manager/templates/cainjector-psp-clusterrolebinding.yaml, deploy/charts/cert-manager/templates/cainjector-psp.yaml, deploy/charts/cert-manager/templates/cainjector-rbac.yaml, deploy/charts/cert-manager/templates/cainjector-serviceaccount.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/rbac.yaml, deploy/charts/cert-manager/templates/service.yaml, deploy/charts/cert-manager/templates/serviceaccount.yaml, deploy/charts/cert-manager/templates/servicemonitor.yaml, deploy/charts/cert-manager/templates/startupapicheck-job.yaml, deploy/charts/cert-manager/templates/startupapicheck-psp-clusterrole.yaml, deploy/charts/cert-manager/templates/startupapicheck-psp-clusterrolebinding.yaml, deploy/charts/cert-manager/templates/startupapicheck-psp.yaml, deploy/charts/cert-manager/templates/startupapicheck-rbac.yaml, deploy/charts/cert-manager/templates/startupapicheck-serviceaccount.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml, deploy/charts/cert-manager/templates/webhook-psp.yaml, deploy/charts/cert-manager/templates/webhook-rbac.yaml, deploy/charts/cert-manager/templates/webhook-service.yaml, deploy/charts/cert-manager/templates/webhook-serviceaccount.yaml, deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml, devel/addon/samplewebhook/chart/templates/deployment.yaml
Apply more consistent helm style in templates.
Fixes wrong renders when 'resources' field is empty https://github.com/jetstack/cert-manager/pull/4209#discussion_r706397410 -> should be only functional change in this PR
```release-note
NONE
```
=> Cleanup helm templates & fix empty 'resources' in deployment

deploy/charts/cert-manager/README.template.md
This will need to be bumped for the next release, as per the latest versions listed in [this PR](https://github.com/cert-manager/website/pull/762).
Also updates a link to k8s docs which seems to be broken now (and is old in any case)
/kind cleanup
```release-note
NONE
```
=> Update supported k8s versions in chart README

devel/cluster/create-kind.sh
This PR allows to create a Kubernetes 1.23 kind cluster (using an image built from the latest alpha release of kube 1.23) for running cert-manager e2e tests.
This is needed so that we can start testing cert-manager against Kubernetes v1.23 which [will come out on 7th December](https://www.kubernetes.dev/resources/release/) and should be supported by cert-manager v1.7.
- To test run `K8S_VERSION=1.23 ./devel/cluster/create-kind.sh` then verify that the created cluster version with `kubectl version`
- Once this PR gets merged, I will create a Prow periodic and an Prow presubmit with kube version set to 1.23
```release-note
NONE
```
=> Add an option to create a kube 1.23 cluster

pkg/controller/acmeorders/sync.go, pkg/controller/acmeorders/sync_test.go
This PR ensures that no requests for new ACME orders are issued for cert-manager `Order` CRs that are already in a failed state.
Currently if the cert-manager 'orders' controller reconciles an `Order` CR without `status.url` set, it will attempt to create a new `Order` - see [here](https://github.com/jetstack/cert-manager/blob/master/pkg/controller/acmeorders/sync.go#L87). An order that has failed and is in errored state may not have the `status.url` field set, so this would cause an unneccesary call to ACME server.
If an order is in a failed state the associated `CertificateRequest` is set to `Ready: False` and the issuance will be attempted again after the 1 hour backoff period by creating a new `CertificateRequest` and a new `Order` (this is the …
=> Don't make extra ACME calls for Order CRs that have failed

go.mod, go.sum, hack/build/repos.bzl
These dependencies include a minor update to the OCI spec to address https://github.com/opencontainers/distribution-spec/security/advisories/GHSA-mc8v-mgrf-8f4m and https://github.com/opencontainers/image-spec/security/advisories/GHSA-77vh-xpmg-72qh
```release-note
NONE
```
=> Update helm, opencontainers, containerd.

devel/addon/ingressnginx/BUILD.bazel, devel/addon/ingressnginx/install.sh, test/e2e/images.bzl
This PR ensures that v1 version of nginx-ingress is used for cert-manager e2e tests against Kubernetes v1.23. Also bumps the nginx-ingress image versions.
The ingress-nginx release notes actually suggest [Kubernetes v1.18 is not supported even for the (latest known) pre-v1 nginx-ingress releases](https://github.com/kubernetes/ingress-nginx#support-versions-table), but it seems to work
```release-note
NONE
```
=> Installs v1 ingress-nginx for e2e tests against kube 1.23

pkg/util/versionchecker/fromservice.go, pkg/util/versionchecker/getpodfromtemplate_test.go
Some clusters may have failed pods that are not garbage collected. These pods should not be considered when determining version numbers.
Signed-off-by: John Chadwick <86682572+johnwchadwick@users.noreply.github.com>
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4614
```release-note
Fixed a bug that can cause `cmctl version` to erroneously display the wrong webhook pod versions when older failed pods are present. (#4616)
```
=> Only consider running pods when determining version

pkg/controller/certificates/issuing/issuing_controller.go, pkg/controller/certificates/keymanager/keymanager_controller.go, pkg/controller/certificates/readiness/readiness_controller.go, pkg/controller/certificates/requestmanager/requestmanager_controller.go, pkg/controller/certificates/revisionmanager/revisionmanager_controller.go, pkg/controller/certificates/trigger/trigger_controller.go
Currently, Certificate controllers will log an _error_ when a Certificate has been deleted and therefore will be ignored. This isn't an error and is part of normal operation. Erroring on deleted Certificates clutters the logs and is confusing to users since it can be safely ignored.
This PR changes these log lines to instead log with `Info` at the global `Debug` level.
```release-note
No longer log an error when a Certificate is deleted during normal operation.
```
/milestone v1.7
=> Change Certificates controller to no longer error for a Certificate that no longer exists

deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml, deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml
Previously, cert-manager supported Kubernetes `v1.16` which meant that cert-manager's webhook configuration needed to include `v1beta1` as a `admissionReviewVersions`, even though it wasn't actually served. See: https://github.com/kubernetes/kubernetes/issues/82025
Since we longer support Kubernetes `v1.16`, we can remove that version from the configuration.
```release-note
Clean up: Remove `v1beta1` form the webhook's admissionReviewVersions as cert-manager no longer supports v1.16
```
/kind cleanup
/milestone v1.7
=> Removes v1beta1 from webhook's admissionReviewVersions as we no longer support Kubernetes v1.16

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/servicemonitor.yaml, deploy/charts/cert-manager/values.yaml
With setting honorLabels to "true" one can get rid of the "exported_namespace" label in scraped cert-manager metrics.
So far all scraped metrics which used the serviceMonitor for scrape configuration included the 'external_namespace' label next to a 'namespace' label. This happens because cert-manager also exports a 'namespace' label and Prometheus renames that to 'external_namespace', because it conflicts with its own namespace label. Setting honorLabels to `true` in the serviceMonitor will lead to Prometheus respecting the namespace label it retrieves from cert-manager metrics.
**Special …
=> allow to honor the labels of cert-manager on conflicts

go.mod, go.sum, hack/build/repos.bzl
Resolves GitHub security warning. I don't think the CVE mentioned actually affects us: https://github.com/advisories/GHSA-v95c-p5hm-xq8f
```release-note
NONE
```
=> Update runc dependency to 1.0.3

deploy/charts/cert-manager/.helmignore
Signed-off-by: Terry Howe <tlhowe@amazon.com>
Remove some extraneous files from helm chart.
```release-note
NONE
```
=> Minor clean-up to helm chart

make/licenses.mk
As suggested by @munnerz [on slack](https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1639739884409500?thread_ts=1639739346.406900&cid=CDEQJ0Q8M)
This adds a link to the specific LICENSES file for a commit when we're doing a build. It won't be constantly re-run locally (because the `bin/scratch/license-footnote.yaml` target doesn't depend on `$(GITCOMMIT)` in any way) but since we build actual releases from scratch it should do nicely for those.
```release-note
NONE
```
=> Add a specific link to the LICENSES file in the repo

test/e2e/suite/conformance/certificates/venafi/venafi.go
At the moment the Venafi TPP e2e test case names don't indicate whether it is a Venafi TPP or Venafi Cloud test, which makes it harder to understand the logs, see i.e the failed test case names [here](https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/logs/ci-cert-manager-venafi/1472528021104627712).
```release-note
NONE
```
=> Mark Venafi TPP [Cluster]Issuer tests with 'Venafi TPP'

make/tools.mk
This PR ensures that we always do checksum validation when installing tools, and that as such repeating a command like `make -f make/Makefile tools` can't fail checksum validation first time and then succeed second time.
**Which issue this PR fixes**: fixes #4678 
**Note for reviewers**: May be worth reviewing this on a per-commit basis
/kind bug
```release-note
Improve checksum validation in makefile-based tool installation
```
=> make: Don't write tools if hash doesn't match

cmd/cainjector/app/start.go, cmd/webhook/app/options/options.go, deploy/charts/cert-manager/values.yaml
This is a small helm values cleanup PR following #4698:
- removes the example where `--cluster-resource-namespace` flag is passed via extra args as there is already a top level helm value for the same flag
- adds some comments as to how users can view all available cert-manager component flags
```release-note
NONE
```
fixes #4698 
/kind cleanup
=> Helm values cleanup

pkg/controller/certificates/issuing/issuing_controller.go, pkg/controller/certificates/issuing/issuing_controller_test.go, pkg/controller/certificates/requestmanager/requestmanager_controller.go, pkg/controller/certificates/requestmanager/requestmanager_controller_test.go
This PR fixes a bug where after a certificate request fails and the next one succeeds, the `Certificate`'s 'Ready' condition remains false and the contents of the `Secret` are not updated.
See  #4642 for detailed bug description and instructions how to reproduce it.
fixes #4642 
This bug was caused by a race condition where during an issuance where the _previous_ issuance failed, the failed `CertificateRequest` gets picked up by the issuing controller and used to update `Certificate`'s status.
This issue is fixed in https://github.com/jetstack/cert-manager/pull/4688/commits/ff67b2a9a0bc5e1520c875496fbd728b915ca738 by making the issuing controller compare timestamp on the `Issuing` …
=> Fixes a bug where a previous failed CertificateRequest was picked up during next issuance

build/images.bzl
Backport of #4706 for release-1.6
This likely isn't worth doing a release for on its own, but it seems worth backporting so this is ready to go if we need to do another release of 1.6, which is currently scheduled to be supported until [Mar 30, 2022](https://cert-manager.io/docs/installation/supported-releases/#supported-releases)
/kind cleanup
```release-note
Bump base images to latest versions
```
=> [release-1.6] bump base images

devel/run-e2e.sh, test/e2e/e2e_test.go, test/e2e/framework/config/BUILD.bazel, test/e2e/framework/config/config.go, test/e2e/suite/conformance/certificatesigningrequests/BUILD.bazel, test/e2e/suite/conformance/certificatesigningrequests/suite.go
Since https://github.com/jetstack/testing/pull/612 merged, we are no longer running e2e tests that predicate on string matches against the feature flag env var and the feature name- namely CertificateSigningRequests. This PR registers the feature gate flag on the e2e suite binary and pipes them in from the test script.
Since the feature gates package uses pflag which is incompatible (or extremely tedious to get working properly!) with ginkgo, we simply register a golang flag, copy the resulting value to a pflag set once parsed, then register it with the feature gate map.
This should get the feature gate tests running correctly.
```release-note
Cleanup: Pipe feature gate flag to the e2e binary. Test against shared Feature Gate map for feature enabled and whether they should be tested …
```
=> Pipes in the feature gates from environment to e2e binary

deploy/charts/cert-manager/templates/service.yaml, deploy/charts/cert-manager/templates/webhook-service.yaml, deploy/charts/cert-manager/values.yaml
Add optional annotations to the Kubernetes Service created by the helm chart.  Annotations are helpful for [human service discovery](https://kubernetes.io/blog/2021/04/20/annotating-k8s-for-humans/).
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: None
**Special notes for your reviewer**: none
```release-note
Added helm value `.Values.serviceAnnotations`
```
=> [Helm Chart] Add optional service annotations

hack/verify-goimports.sh, make/Makefile, make/ci.mk, make/tools.mk
This adds a step by which we can run `goimports` against the codebase.
It's also the first part of moving "testing" more generally from bazel to make. A lot of the existing steps are tied to bazel in some way, but since this is greenfield it's an easy place to start.
After this merges, we can add `make -f make/Makefile ci-presubmit` to the [presubmits](https://github.com/jetstack/testing/blob/master/config/jobs/cert-manager/cert-manager-presubmits.yaml).
Sort-of related to #4705
/kind feature
```release-note
Add goimports verification step for CI
```
=> Add goimports verification and skeleton ci presubmit check

make/tools.mk
This is currently done by a bazel rule, but we need a local install of gingko that's done via Make.
This is part of the [migration to make](https://github.com/jetstack/cert-manager/issues/4712).
/kind feature
```release-note
NONE
```
=> Add install for ginkgo which is used for e2e tests

hack/verify_boilerplate.py
The regex being replaced doesn't match files which only contain `//go:build` although as of go 1.17 (which we require for cert-manager) that seems [totally valid](https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md).
This commit updates the regex to match upstream k8s, which is the original source of the boilerplate verification script in any case.
See the [upstream](https://github.com/kubernetes/kubernetes/blob/47ff335d4c678f8ebe12369055d4b3806d0fb9f4/hack/boilerplate/boilerplate.py#L219-L223) version of the script for more details
/kind feature
```release-note
NONE
```
=> Match upstream boilerplate verification for files w/ go:build

make/tools.mk
As suggested in [this comment](https://github.com/jetstack/cert-manager/pull/4714#issuecomment-1006677980)
/kind feature
```release-note
NONE
```
=> Install ginkgo version from go.mod rather than specifying an explicit version

internal/BUILD.bazel, internal/apis/acme/install/BUILD.bazel, internal/apis/acme/install/pruning_test.go, internal/apis/certmanager/install/BUILD.bazel, internal/apis/certmanager/install/pruning_test.go, internal/test/paths/BUILD.bazel, internal/test/paths/bazel.go, internal/test/paths/paths.go, pkg/api/BUILD.bazel, test/integration/framework/BUILD.bazel, test/integration/framework/apiserver.go, test/internal/apiserver/BUILD.bazel, test/internal/apiserver/envs.go
Prior to this change, running integration tests using anything other than Bazel would fail unless environment variables pointing the integration test framework to copies of the binaries needed were set.
This PR adds additional checks into the path loading logic to attempt to load these binaries from the `bazel-bin` directory if it exists. This means that once a user has run `bazel build //hack/bin/...` (or has indirectly caused these targets to be built by running or building other targets), IDEs like Goland will be able to run these tests like normal without any additional configuration changes by the user.
```release-note
NONE
```
/kind cleanup
/area testing
=> Re-organise and extend path loading logic to make it easier to run integration tests using Delve/GoLand

pkg/acme/webhook/apiserver/BUILD.bazel, pkg/acme/webhook/apiserver/apiserver.go, pkg/acme/webhook/apiserver/apiserver_test.go
If we register multiple DNS providers while running the webhook server, it will cause an unexpected exit with `WebService with duplicate root path detected` error. 
This issue happens because the root path of each DNS provider is equal since they share the group name.
To resolve this issue, this commit installs APIGroup once for multiple DNS providers by extracting apiGroupInfo variable and InstallAPIGroup call from solver (DNS provider) loop in ChallengeServer constructor.
None
None
```release-note
Fix unexpected exit when multiple DNS providers are passed to `RunWebhookServer` 
```
/kind bug
=> Install APIGroup once for multiple DNS providers

pkg/controller/acmeorders/sync.go, pkg/controller/acmeorders/sync_test.go
- fixes a typo in `finalizeOrder` that caused an error to not be checked
- small refactor in orders controller `Sync` function to prevent ACME server being called twice in scenarios where an existing ACME Order needs to be retrieved to update a cert-manager `Order`'s status
- a few more test cases
- the extra ACME calls should have been maximum 1 extra per reconcile in a few scenarios only
```release-note
NONE
```
=> Order sync cleanup

pkg/controller/acmeorders/sync.go, pkg/controller/acmeorders/sync_test.go
This PR is part of the work to reduce the number of calls to ACME. The bug that this PR fixes would have caused an extra call to ACME to create a new order in cases where the previous order was successfully finalized, but the status of the `Order` CR was not updated correctly, due to i.e a network issue.
See the ACME spec description of valid order states and state transitions [here](https://datatracker.ietf.org/doc/html/rfc8555#:~:text=Order%20objects%20are,for%20Order%20Objects).
If cert-manager orders controller has finalized an ACME order, but has failed to update the status of the Order CR to 'valid', the next reconcile of the order will again result in an attempt to finalize the order. The ACME spec does not explicitly state what the ACME …
=> Don't fail an order that has been finalized, but the status has not been synced to Order CR

test/e2e/suite/issuers/ca/BUILD.bazel, test/e2e/suite/issuers/ca/certificate.go
/assign @irbekrm 
/kind cleanup
/area e2e
The AdditionalOutputFormats feature is gated behind a feature flag. Being Alpha, the feature is not enabled on e2e tests targeting Kubernetes v1.18. This PR adds a feature gate check to ensure it is skipped on those test runners.
```release-note
NONE
```
=> Don't run AdditionalOutputFormats e2e test if the feature gate is not enabled

test/e2e/BUILD.bazel, test/e2e/e2e_test.go
This was initially part of #4565 which was closed in favour of moving integration tests, but the consensus was that the e2e test is a special case.
The e2e test requires so much more ahead-of-time setup that our bazel build flow special cases it by marking it manual. This is a `go test` equivalent to that, which enables the e2e test to remain under the `test/` directory while still allowing `go test ./test/...` to work generally for all other tests.
We'll add make targets for the e2e tests down the road. For now, we add the build tag and define it in bazel so this commit should be a no-op in effect.
/kind cleanup
```release-note
NONE
```
=> Add a build tag for the e2e test only

test/integration/versionchecker/testdata/fetch.sh
I doubt anyone used this path directly, but I didn't spot that fetch.sh hardcoded the path to the bazel target which was moved.
This wouldn't have affected any tests, since they'll all still use bazel directly and won't invoke this script directly. Might as well fix it though.
/kind bug
```release-note
NONE
```
=> Fix manual invocation of versionchecker testdata fetch

internal/apis/acme/types_issuer.go, internal/apis/certmanager/types_certificate.go, test/e2e/framework/helper/validation/certificates/certificates.go
/assign @munnerz @jahrlin 
See https://github.com/jetstack/cert-manager/pull/4745
Removes the JSON tags from our internal API types.
Also removes the `5` from the e2e helper func to not make it an array.
/kind cleanup
/area api
```release-note
NONE
```
=> Remove json tags from internal API types.

cmd/ctl/pkg/install/install.go
I am sure that `cmctl x install` *used* to install into the `cert-manager` namespace by default, but somehow that behaviour changed.
I hacked in this change which seems to work for me, but I am fairly confused about when the flags get configured and when they get parsed, and why the `DefVal` that we were always setting (and which always appeared as the default value in the --help) is suddenly not being used as the default value.
Fixes: #4739 
```release-note
NONE
```
=> Make sure that cmctl x install uses the cert-manager namespace 

hack/update-codegen.sh
By default the gengo tools were writing the generated files to $GOPATH if set.
(which it was on my laptop)
```
$ deepcopy-gen -h 2>&1 | grep output-base
-o, --output-base string               Output base; defaults to $GOPATH/src/ or ./ if $GOPATH is not set. (default "/home/richard/go/src")
```
Alternative would be to set  GOPATH in the script to the working directory, but I wasn't sure if that might 
The script used to do that when it used to download everything to a temporary directory:
* https://github.com/jetstack/cert-manager/commit/8f1fb874ed72b54435b29c80585684bab6c83c25
Fixes: #4765 
```release-note
NONE
```
=> Specify an --output-base directory for all the gengo tools

internal/ingress/BUILD.bazel, internal/ingress/convert.go, internal/ingress/convert_test.go, pkg/issuer/acme/http/ingress.go, pkg/issuer/acme/http/ingress_test.go
As discussed in https://github.com/jetstack/cert-manager/issues/4537 the `spec.ingressClassName` field is not equivalent to the `kubernetes.io/ingress.class` annotation. This changes the HTTP-01 solver to create ingresses that only have the annotation.
**Which issue this PR fixes** : fixes #4537
```release-note
The HTTP-01 ACME solver now uses the `kubernetes.io/ingress.class` annotation instead of the `spec.ingressClassName` in created Ingress resources.
```
We are currently testing the full impact of this change for the release notes and upgrade guide
=> Always use the kubernetes.io/ingress.class annotation (#4537)

devel/cluster/create-kind.sh
Explicitly passes `client` option to `--dry-run` argument when applying coredns config to test kind cluster.
Since `kubectl` v1.23 it is required to explicitly pass one of  `client|server|none` options to `--dry-run` (although [the docs](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#:~:text=formats%20are%20accepted.-,Usage,-%24%20kubectl%20create%20%2Df) aren't explicit about that) so this script was failing with
```
error: --dry-run flag without a value was specified. A value must be set: "none", "server", or "client".
error: no objects passed to apply
```
- `client` option is also what they use for the same in test-infra see https://github.com/kubernetes/test-infra/pull/24593/commits/9a …
=> Fixes ./devel/cluster/create.sh script

.github/PULL_REQUEST_TEMPLATE.md
1. Removes link to k8s contributor guidelines; they're _way_ more complicated than what we require. We don't want to link to docs suggesting the user needs to sign the k8s CLA.
2. Removes link to k8s "faster reviews" - again, waaaay more complicated than we need. We don't want to link to docs suggesting "File a Kubernetes Enhancement Proposal"
3. Adds link to _our_ contributor guidelines.
4. Adds special note about DCO signoff since it's often something that people get confused about
5. Adds a link explaining how to allow edits by maintainers, inspired by [the DocSearch PR instructions](https://github.com/algolia/docsearch-configs/blob/da4190d9c7d0e3d22e9e04e4fd0a6f6e6c8afa43/.github/PULL_REQUEST_TEMPLATE#L8).
6. Removes a couple of headings that nobody ever followed; instead have simpler …
=> Update PR template to be simpler and mention allowing edits

deploy/charts/cert-manager/templates/service.yaml, deploy/charts/cert-manager/templates/webhook-service.yaml, deploy/charts/cert-manager/values.yaml
This PR removes duplicated service annotations fields from Helm values files and Helm templates.
These were added by merging #4329 on top of changes added by #3639 and #4556 .
I have verified that this change actually works (also with multiple service annotations, see https://github.com/jetstack/cert-manager/pull/4329#issuecomment-1021023685) by building the chart (`bazel build //deploy/charts/cert-manager`) and deploying with a values file with multiple service annotations:
```
irbe@yamls$ cat helm-values.yaml 
installCRDs: true
serviceAnnotations:
foo: bar
bar: baz
baz: foo
webhook:
serviceAnnotations:
foo: bar
bar: baz
baz: foo
```
and verified that the installation succeeds and the annotations get added.
```release-note
NONE
```
=> Removes duplicated service annotations from Helm chart

deploy/crds/crd-certificates.yaml, internal/apis/certmanager/types_certificate.go, internal/apis/certmanager/v1alpha2/types_certificate.go, internal/apis/certmanager/v1alpha3/types_certificate.go, internal/apis/certmanager/v1beta1/types_certificate.go, internal/apis/certmanager/validation/BUILD.bazel, internal/apis/certmanager/validation/certificate.go, internal/apis/certmanager/validation/certificate_test.go, internal/controller/feature/features.go, internal/webhook/feature/features.go, pkg/apis/certmanager/v1/types_certificate.go
This PR fixes a bug where the Certificate's `additionalOutputFormats' field was only ever being validated by the webhook at admission time if the `privateKey` on the Certificate field was also set. The webhook was also incorrectly using the _controllers_ feature set.
```console
Webhook component providing API validation, mutation and conversion functionality for cert-manager (canary) ()
...
--feature-gates mapStringBool                  A set of key=value pairs that describe feature gates for alpha/experimental features. Options are:
AdditionalCertificateOutputFormats=true|false (ALPHA - default=false)
AllAlpha=true|false (ALPHA - default=false)
AllBeta=true|false (BETA - default=false)
ExperimentalCertificateSigningRequestControllers=true|false (ALPHA - default=false) …
```
=> Bug: Fix Certificate's AdditionalOutputFormat in admission within Webhook

pkg/issuer/acme/dns/route53/route53.go
Use multivalue records instead of simple records for the AWS Route53 ACME DNS challenge solver.
When using simple records, it would be impossible to create a second record in a Route53 hosted zone with the same name/type.
This way when either using the same domain name on multiple clusters or using the same CNAME record for multiple domains would create a new challenge instead of overwriting the other challenges.
Fix https://github.com/jetstack/cert-manager/issues/3460
bug
```release-note
Use multivalue records instead of simple records for the AWS Route53 ACME DNS challenge solver, to allow for multiple challenges for the same domain at the same time
```
=> Use multivalue records instead of simple records 

pkg/controller/certificates/issuing/internal/secret.go, pkg/controller/certificates/issuing/internal/secret_test.go
It is superfluous for cert-manager to log an _error_ in the secrets manager about a conflict, when it is going to force apply anyway. This should clear up the logs.
Regretting my response here :slightly_frowning_face:  https://github.com/jetstack/cert-manager/pull/4638#discussion_r784922732
```release-note
Cleanup: No longer log an error when cert-manager encounters a conflict in the secrets manager, in favour of always force applying.
```
/kind cleanup
=> Always Force apply in issuing controller's secret manager

cmd/controller/app/options/options.go
Fixes #4832 
I don't think we can apply any meaningful validation here, and it seems like a good feature to allow any other issuer `kind`s. Let me know what you all think.
/kind feature
```release-note
External issuers may now be referenced as the default Issuer name / group / kind for the ingress-shim.
```
=> Relax the validation on the default Issuer Kind for certificate-shim

.bazelrc, .gitignore
This PR allows developers to use a `user.bazelrc` at the root of the workspace to configure bazel without affecting other users' environments.
In my case, I want to prevent "spontaneous" protobuf recompilations which are caused by changes to `PATH` so I use the following config. Theoretically the last 2 lines should be enough
```bash
$ cat user.bazelrc
build --action_env=PATH="/usr/local/bin:/Users/joakim/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin"
run --action_env=PATH="/usr/local/bin:/Users/joakim/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin"
build --incompatible_strict_action_env
run …
```
=> support user.bazelrc

pkg/scheduler/scheduler_test.go
This test can easily fail on a heavily loaded machine, such as one running many tests in parallel or a weaker developer laptop.
1. The afterFunc could be delayed _massively_ on a heavily loaded machine, such as one running a lot of tests in parallel.
2. Requiring an accuracy of 1ms seems like a flake waiting to happen (it was such a flake which inspired this PR)
3. When we write code which uses this scheduler, we can't even safely assume the afterFunc will _ever_ be run, let alone run within a 1ms margin of time error.
Put simply, as implemented this test is more of a test of how loaded the test server is than a test of any functionality.
By increasing the allowable delta hugely, we keep this test as a sanity check but basically remove the chance of a flake. The test essentially becomes …
=> Increase margin of error in an otherwise unsound test

cmd/cainjector/app/BUILD.bazel, cmd/cainjector/app/start.go, devel/addon/certmanager/install.sh, devel/lib/lib.sh, internal/BUILD.bazel, internal/cainjector/feature/BUILD.bazel, internal/cainjector/feature/features.go
This PR adds the feature gates flag to cainjector (currently empty).
All feature gates passed to the cert-manager install scripts (via `FEATURE_GATES` env var), are parsed and given to each component that supports each particular feature. This simplifies setting feature gates during an install for both CI and developers, as only the component that supports that feature gate will have it applied, and not cause the component to error during start.
/kind cleanup
```release-note
NONE
```
=> Parse and distribute feature gates in devel script

deploy/charts/cert-manager/templates/cainjector-rbac.yaml
/kind cleanup
AuditSinks was an alpha feature in Kubernetes, and was added as a supported ca-injector target https://github.com/jetstack/cert-manager/pull/2027
This alpha feature was removed from Kubernetes, as well as cert-manager.
This PR just removes the permissions that were forgotten about when the feature was removed.
```release-note
NONE
```
=> Remove auditsinks permissions from ca-injector as it is no longer supported

devel/addon/certmanager/install.sh
/kind cleanup
Adds `ServerSideApply` as a known feature gate for the controller component.
```release-note
NONE
```
=> Adds ServerSideApply as a feature gate for the controller

test/e2e/suite/certificates/additionaloutputformats.go
/kind cleanup
This e2e test case requires that the ServerSideApply feature gate is enabled to pass successfully.
```release-note
NONE
```
=> Adds check in additionaloutputformat e2e test suite for ServerSideApply feature gate

deploy/crds/crd-certificaterequests.yaml, deploy/crds/crd-certificates.yaml, deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml
In cert-manager v1.7 conversion webhook was removed (#4635 ) so cainjector no injects CA bundles to cert-manager CRDs.
This PR removes leftover [cainjector annotations](https://cert-manager.io/docs/concepts/ca-injector/) from the CRDs.
As far as I am aware, cainjector reconciles _all_ CRDs so removing these annotation does not make it _not_ reconcile these CRDs and this PR is a cleanup rather than a bugfix.
```release-note
NONE
```
/kind cleanup
=> Removes cainjector annotations from CRDs

test/e2e/framework/BUILD.bazel, test/e2e/framework/util.go, test/e2e/suite/certificates/additionaloutputformats.go, test/e2e/suite/conformance/certificates/BUILD.bazel, test/e2e/suite/conformance/certificates/tests.go, test/e2e/suite/conformance/certificatesigningrequests/suite.go, test/e2e/suite/issuers/ca/certificate.go
e2e tests which do not have the Gateway API feature gate enabled are currently failing.
https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/pr-logs/pull/cert-manager_cert-manager/4792/pull-cert-manager-e2e-feature-gates-disabled/1492211977156562944
This PR adds a feature gate check for the Gateway API e2e tests, and also adds a helper function for checking whether to skip tests based on a feature gate not being enabled.
```release-note
NONE
```
=> Require Gateway API feature gate for Gateway API tests. Add a helper func

USERS.md
- Renames Acoss -> Urssaf Caisse nationale
- Uses a commit SHA rather than a branch for jetstack logo
- Rewords things + fixes typos / grammar errors
```release-note
NONE
```
=> Rework USERS doc

SECURITY.md
We called the cert-manager repo out as a special case in SECURITY.md before we migrated it, but now it's in the cert-manager org we can simplify the language.
```release-note
NONE
```
=> Improve language in SECURITY file post-migration

make/manifests.mk
In #4853, I noticed that the Helm chart built when running `make -f make/Makefile helm-chart` does not contain the `templates/crds.yaml` file.
I checked that the `crds.yaml` created by Bazel and by make are identical. You can check with the command:
```sh
git checkout 9df26703dd41fb54d1dc3b3501080e167333cac4
bazel build //deploy/charts/cert-manager --ui_event_filters=-info --noshow_progress
make -f make/Makefile helm-chart
diff -u \
<(tar tfO bazel-bin/deploy/charts/cert-manager/cert-manager.tgz cert-manager/templates/crds.yaml) \
<(tar tfO bin/cert-manager-$(git describe --tags).tgz cert-manager/templates/crds.yaml)
```
The diff is empty.
/kind cleanup
```release-note
NONE
```
=> make -f make/Makefile helm chart now includes templates/crds.yaml

make/Makefile
Double quotes are not interpreted by make, which meant that the variable `CMREL_KEY` was set to `""` (i.e., a string with two double quotes) and was never empty, which means the following `$(error ...)` block was never interpreted:
https://github.com/cert-manager/cert-manager/blob/75b49ab641663bd4cd5ce76b0a0270b723e2d204/make/manifests.mk#L55-L57
xref: https://github.com/cert-manager/cert-manager/issues/4853
/kind cleanup
```release-note
NONE
```
=> make/Makefile: fix message when CMREL_KEY isn't set

deploy/charts/cert-manager/templates/rbac.yaml, internal/controller/feature/features.go, pkg/controller/certificatesigningrequests/acme/acme.go, pkg/controller/certificatesigningrequests/ca/BUILD.bazel, pkg/controller/certificatesigningrequests/ca/ca.go, pkg/controller/certificatesigningrequests/controller.go, pkg/controller/certificatesigningrequests/selfsigned/BUILD.bazel, pkg/controller/certificatesigningrequests/selfsigned/selfsigned.go, pkg/controller/certificatesigningrequests/sync.go, pkg/controller/certificatesigningrequests/util/BUILD.bazel, pkg/controller/certificatesigningrequests/util/apply.go, pkg/controller/certificatesigningrequests/util/conditions.go, pkg/controller/certificatesigningrequests/util/conditions_test.go, pkg/controller/certificatesigningrequests/vault/BUILD.bazel, pkg/controller/certificatesigningrequests/vault/vault.go, pkg/controller/certificatesigningrequests/venafi/venafi.go
Branched from #4773 which should be merged first.
This PR implements Server Side Apply for CertificateSigningRequest controllers when the `SeverSideApply` Feature Gate (default `disabled`) is enabled.
Where `UpdateStatus` was previously, a new func are used to check for this feature gate.
---
```release-note
ServerSideApply: The feature gate `ServerSideApply=true` configures the certificatesigningrequest controllers to use Kubernetes Server Side Apply on CertificateRequest resources. 
```
/kind feature
=>  Server Side Apply: Adds support for CertificateSigningRequest controllers to use SSA with Feature Gate

deploy/charts/cert-manager/templates/rbac.yaml, deploy/crds/crd-certificaterequests.yaml, internal/BUILD.bazel, internal/apis/certmanager/v1alpha2/types_certificaterequest.go, internal/apis/certmanager/v1alpha3/types_certificaterequest.go, internal/apis/certmanager/v1beta1/types_certificaterequest.go, internal/controller/certificaterequests/BUILD.bazel, internal/controller/certificaterequests/OWNERS, internal/controller/certificaterequests/apply.go, internal/controller/certificaterequests/apply_test.go, internal/controller/feature/features.go, pkg/apis/certmanager/v1/types_certificaterequest.go, pkg/controller/certificaterequests/BUILD.bazel, pkg/controller/certificaterequests/approver/BUILD.bazel, pkg/controller/certificaterequests/approver/approver.go, pkg/controller/certificaterequests/approver/sync.go, pkg/controller/certificaterequests/controller.go, pkg/controller/certificaterequests/sync.go, pkg/controller/certificates/requestmanager/BUILD.bazel, pkg/controller/certificates/requestmanager/requestmanager_controller.go, test/integration/BUILD.bazel, test/integration/certificaterequests/BUILD.bazel, test/integration/certificaterequests/apply_test.go, test/integration/certificaterequests/condition_list_type_test.go
Branched from #4773 which should be merged first.
This PR implements Server Side Apply for CertificateRequests's controllers when the `SeverSideApply` Feature Gate (default `disabled`) is enabled.
Where `Update` or `UpdateStatus` was previously, two new funcs are used to check for this feature gate. If the feature gate is enabled, a new CertificateRequest object is made, and the relevant fields are copied across. 
The Open API tags `+listType=map`, `+listMapKey=type` have been added to the CertificateRequest's Condition field so that each condition can be added, updated, removed, without a conflict, even if another independent manager is concerned with another existing condition. 
---
```release-note …
```
=> Server Side Apply: Adds support for CertificateRequests controller to use SSA with Feature Gate

internal/plugin/admission/resourcevalidation/resourcevalidation.go, pkg/webhook/admission/chain_test.go, test/integration/ctl/migrate/ctl_upgrade_migrate_test.go
This is according to our policy on organizing imports, see: https://cert-manager.io/docs/contributing/coding-conventions/#organizing-imports
This is following what `goimports` says.
/kind cleanup
```release-note
NONE
```
=> Fix imports in a few files

pkg/controller/context_test.go
Assert these variables are the same pointer rather than value. This is a stronger test to ensure that the rate limiter is shared between controller contexts.
/kind cleanup
```release-note
NONE
```
=> Change controller context rate limiter test to ensure they are the same pointer

.dockerignore, hack/containers/Containerfile.acmesolver, hack/containers/Containerfile.cainjector, hack/containers/Containerfile.controller, hack/containers/Containerfile.ctl, hack/containers/Containerfile.webhook, make/containers.mk, make/git.mk
| This PR is part of the effort 'moving away from Bazel' tracked in #4712 |
|--|
Previously, we had one `.dockerignore` that would do its best to only have the binaries and licenses copied into the Docker (or nerdctl, or buildah). Unfortunately, that meant it had to copy all of bin/server and bin/cmctl, which could become quite large (I measured 1.1 GB).
Instead of relying on a single .dockerignore file, we copy the licenses and binaries into a "scratch context" directory. The downside is that all the binaries are in two different places (bin/server and bin/scratch/containers). Note that we can't use symlinks because Docker won't dereference them.
I also added a target `bin/release-version` so that container images get rebuilt when a different commit is checked out. When switching …
=> Make: faster "make all-containers" and rebuild on commit change

cmd/ctl/pkg/inspect/secret/BUILD.bazel, cmd/ctl/pkg/inspect/secret/secret_test.go, cmd/ctl/pkg/inspect/secret/util_test.go, test/unit/gen/certificate.go
I would like to be able to merge PRs again 🙂 
This PR removes a hardcoded certificate that was used in unit tests that has now expired.
/kind cleanup
```release-note
NONE
```
=> Remove hardcoded cert from cmctl inspect secret unit tests

cmd/ctl/BUILD.bazel, cmd/ctl/pkg/experimental/experimental.go, cmd/ctl/pkg/uninstall/BUILD.bazel, cmd/ctl/pkg/uninstall/uninstall.go
This PR adds an experimental `uninstall` command to `cmctl`.
The command attempts to uninstall a Helm release named `cert-manager` in the given namespace.
```console
$ bazel run //cmd/ctl -- x install -n my-custom-namespace
$ bazel run //cmd/ctl -- x uninstall
> release cert-manager not found in namespace cert-manager, did you use the correct namespace?
$ bazel run //cmd/ctl -- x uninstall -n my-custom-namespace
uninstall: Deleting cert-manager
Starting delete for "cert-manager" Service
Starting delete for "cert-manager-webhook" Service
Starting delete for "cert-manager-cainjector" Deployment
Starting delete for "cert-manager-webhook" Deployment
Starting delete for "cert-manager" Deployment
Starting delete for "cert-manager-webhook:dynamic-serving" RoleBinding
Starting delete for …
```
=> cmctl x uninstall

test/e2e/framework/helper/certificates.go, test/e2e/suite/conformance/certificates/acme/acme.go, test/e2e/suite/conformance/certificates/ca/ca.go, test/e2e/suite/conformance/certificates/selfsigned/selfsigned.go, test/e2e/suite/conformance/certificates/vault/vault_approle.go, test/e2e/suite/conformance/certificates/venafi/venafi.go, test/e2e/suite/conformance/certificates/venaficloud/cloud.go, test/e2e/suite/conformance/certificatesigningrequests/acme/dns01.go, test/e2e/suite/conformance/certificatesigningrequests/acme/http01.go, test/e2e/suite/conformance/certificatesigningrequests/ca/ca.go, test/e2e/suite/conformance/certificatesigningrequests/selfsigned/selfsigned.go, test/e2e/suite/conformance/certificatesigningrequests/vault/approle.go, test/e2e/suite/conformance/certificatesigningrequests/vault/kubernetes.go, test/e2e/suite/conformance/certificatesigningrequests/venafi/cloud.go
This PR adds e2e tests to verify Issuer/Cluster Issuer is ready or not.
Closes #4906 
bug
=> e2e for issuers and cluster issuers ready state

cmd/cainjector/app/BUILD.bazel, cmd/cainjector/app/start.go, cmd/controller/app/controller.go, deploy/charts/cert-manager/templates/cainjector-rbac.yaml, deploy/charts/cert-manager/templates/rbac.yaml
#3766 
/kind cleanup
```release-note
Previously, cert-manager supported both ConfigMap & Lease objects for leader election. This change modifies
the leader-election code to now solely use Lease objects. Existing ConfigMap resources used for leader election
will remain and need deleting manually.
This change means that you cannot upgrade to the version containing this change from cert-manager 1.3.
```
=> Switch leader election to use Lease objects

README.md
/kind cleanup
```release-note
NONE
```
=> Readme: link to the contributing guide instead of giving the information straight in the README

deploy/crds/crd-certificates.yaml, pkg/apis/certmanager/v1/types_certificate.go, test/integration/validation/BUILD.bazel, test/integration/validation/certificate_test.go
Fixes #4898
```sh
cat <<EOF | kubectl apply -f -
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
name: testing
namespace: testing
spec:
secretName: testing-tls
privateKey:
rotationPolicy: Alway
issuerRef:
name: letsencrypt-staging
dnsNames:
- 'myhostname.com'
EOF
The Certificate "testing" is invalid: spec.privateKey.rotationPolicy: Unsupported value: "Alway": supported values: "Never", "Always"
```
/kind bug
```release-note
Added kube validation for certificate.spec.privateKey.rotationPolicy. Valid options are Never, Always. Existing Certificate resources with incorrect values needs to be updated. (#4898, @jahrlin)
```
=> add validation for certificate.spec.privateKey.rotationPolicy

pkg/issuer/acme/http/ingress.go, pkg/issuer/acme/http/ingress_test.go
This PR allows a user to override the hardcoded `whitelist-source-range` ingress annotation. This is needed as some users will have custom ingress prefixes set on their controllers, so the hardcoded annotation will not work as intended.
This also unblocks an issue with version >= 0.40.0 of ingress-nginx when using a custom prefix, as the ingress is blocked from being created because the prefix is not correct.
Fixes https://github.com/jetstack/cert-manager/issues/4760
feature
```release-note
Ingress whitelist-source-range annotation prefix can now be overridden via an IngressTemplate
```
=> Allow whitelist-source-range ingress annotation to be overridden

test/e2e/suite/conformance/certificates/BUILD.bazel, test/e2e/suite/conformance/certificates/tests.go
The test:
[Conformance] Certificates with issuer type ACME DNS01 Issuer should allow updating an existing certificate with a new dns name
is flaky due to an update that was not properly retried on conflict. The error looks like this:
Operation cannot be fulfilled on certificates.cert-manager.io \"testcert\": the object has been modified
This error appeared in 127 different prow jobs lately:
- job `pull-cert-manager-e2e-v1-20`, build [`1392114116054749184`](https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/pr-logs/pull/jetstack_cert-manager/3963/pull-cert-manager-e2e-v1-20/1392114116054749184/build-log.txt) (#3963)
- job `pull-cert-manager-e2e-v1-17`, build [`1415672048419606528`](https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/pr-logs/pull/jetstack_cert-manager/4158/p …
=> Retry on conflict for the end-to-end test "added an additional dnsName"

test/e2e/suite/serving/BUILD.bazel, test/e2e/suite/serving/cainjector.go
The end-to-end test case:
[cert-manager] CA Injector for api services should update data when the certificate changes
caused the failure of 162 different prow builds. The error message is:
Operation cannot be fulfilled on certificates.cert-manager.io "serving-certs": the object has been modified; please apply your changes to the latest version and try again
The affected builds were:
- job `pull-cert-manager-e2e-openshift-v3-11`, build [`1259777916972044288`](https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/pr-logs/pull/jetstack_cert-manager/2788/pull-cert-manager-e2e-openshift-v3-11/1259777916972044288/build-log.txt) (#2788)
- job `pull-cert-manager-e2e-openshift-v3-11`, build [`1277628841539407872`](https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/pr-logs/pull/jetsta …
=> Retry on conflict for the end-to-end test "CA Injector for api services should update data when the certificate changes"

make/manifests.mk, make/release.mk
Part of #4712
Ensures that `make release` is a one-stop target for building _everything_, similar to how `make staged-release` was used in the original makefile flow in #4554  
/kind cleanup
```release-note
NONE
```
=> Tweak release targets

deploy/charts/cert-manager/templates/rbac.yaml, deploy/charts/cert-manager/values.yaml
Signed-off-by: Richard Johansson <richard.jimmy.johansson@gmail.com>
It might not always be desirable to aggregate the -edit and -view ClusterRoles to the default user-facing roles. There should be an option to disable this, for example in order to adhere to a least privilege principle in a multi-tenant cluster setup.
Follow-up/enhancement of #902
/kind feature
```release-note
Optional to aggregate cert-manager ClusterRoles to K8s default user-facing ClusterRoles (admin/edit/view)
```
=> Make aggregation to user-facing ClusterRoles optional

cmd/ctl/pkg/create/certificatesigningrequest/certificatesigningrequest.go, pkg/controller/certificatesigningrequests/ca/ca_test.go, pkg/controller/certificatesigningrequests/selfsigned/selfsigned_test.go, pkg/util/pki/kube.go, pkg/util/pki/kube_test.go, test/e2e/framework/helper/validation/certificatesigningrequests/certificatesigningrequests.go, test/e2e/suite/conformance/certificatesigningrequests/BUILD.bazel, test/e2e/suite/conformance/certificatesigningrequests/tests.go, test/unit/gen/certificatesigningrequest.go
This change adds the ability to express certificate duration using
the Kubernetes CSR spec.expirationSeconds field alongside the existing
approach of using the experimental.cert-manager.io/request-duration
annotation.  Both approaches are supported as the expirationSeconds
field requires Kubernetes v1.22+.
Signed-off-by: Monis Khan <mok@vmware.com>
/kind feature
```release-note
Signers now honor Kubernetes CSR duration expressed via the spec.expirationSeconds field.
```
=> Use Kubernetes CSR spec.expirationSeconds to express cert duration

make/release.mk
This makes it trivial to tell when a build was made by the makefile workflow and therefore to adjust `cmrel publish` to adapt to changes.
/kind feature
```release-note
NONE
```
=> Add a build source indicator to metadata

cmd/ctl/pkg/inspect/secret/BUILD.bazel, cmd/ctl/pkg/inspect/secret/secret_test.go, cmd/ctl/pkg/inspect/secret/util_test.go, devel/cluster/create-kind.sh, test/unit/gen/certificate.go
Cherry pick required manual intervention to fix imports.
This backports #4905 to release-1.6
Depends on https://github.com/jetstack/testing/pull/649 for test matrix fixes
Also updates a couple of kind image versions.
/kind bug
```release-note
Fixes an expired hardcoded certificate which broke unit tests
```
=> [release-1.6] Remove hardcoded cert from cmctl inspect secret unit tests

pkg/issuer/acme/dns/route53/route53.go
Signed-off-by: Florin Vlaicu <19238716+fvlaicu@users.noreply.github.com>
In my previous PR: https://github.com/cert-manager/cert-manager/pull/4793, I thought that given the fact that each record that we'll create will be unique would not require to upsert records. It turns out I am wrong.
On our clusters, we've been using this code for almost a month and it turns out that sometimes cert-manager tries to write the same record twice. I have not pinpointed the source of the problem, it might be a restart of the controllers during the validation process that restarts the process from the beginning.
```
failed to change Route 53 record set: InvalidChangeBatch: [Tried to create resource record set [name='_acme-challenge.domain.com.', type='TXT', set-identifier='"unique_ID_goes_HERE"'] but it …
```
=> Route53 challenges: upsert records instead of create

Makefile, make/cmctl.mk, make/manifests.mk, make/release.mk, make/tools.mk
This is to work around the fact that binaries in hostPath-mounted directories cannot be executed even if the permissions are correct. 
I also fixed how tool versions are handled when switching across branches. Previously, if you were switching back and forth between two versions of Go or Kind, the second time would not work. Thanks @munnerz for raising this issue in https://github.com/jetstack/testing/pull/651.
I also propose to remove all the env vars (HELM, COSIGN, CMREL, YQ, KUBECTL, KIND, CRANE, CLIENT_GEN, CONVERSION_GEN, CONTROLLER_GEN, DEEPCOPY_GEN, DEFAULTER_GEN, INFORMER_GEN, LISTER_GEN) since it makes it a bit clearer using e.g. `bin/tools/yq` as both the binary path and a prerequisite.
For example, in the following example, we are referring to cosign in two different ways: …
=> make: in CI, copy binaries from "bin/downloaded" to "bin/tools"

deploy/charts/cert-manager/templates/rbac.yaml, internal/BUILD.bazel, internal/controller/orders/BUILD.bazel, internal/controller/orders/OWNERS, internal/controller/orders/apply.go, internal/controller/orders/apply_test.go, pkg/controller/acmeorders/BUILD.bazel, pkg/controller/acmeorders/controller.go, pkg/controller/acmeorders/sync.go, pkg/controller/certificaterequests/acme/acme.go, pkg/controller/certificatesigningrequests/acme/acme.go, test/integration/acme/orders_controller_test.go
Branched from #4773 which should be merged first.
This PR implements Server Side Apply for the Order controller when the `SeverSideApply` Feature Gate (default `disabled`) is enabled.
Where `UpdateStatus` was previously, a new func are used to check for this feature gate.
---
```release-note
ServerSideApply: The feature gate `ServerSideApply=true` configures the order controller to use Kubernetes Server Side Apply on Order resources. 
```
/kind feature
=> Server Side Apply: Adds support for Order controllers to use SSA with Feature Gate 

internal/controller/certificates/apply.go, internal/controller/certificates/apply_test.go, pkg/controller/certificate-shim/BUILD.bazel, pkg/controller/certificate-shim/gateways/controller.go, pkg/controller/certificate-shim/ingresses/controller.go, pkg/controller/certificate-shim/sync.go, pkg/controller/certificate-shim/sync_test.go
This PR implements Server Side Apply for the certificate-shim controllers when the `SeverSideApply` Feature Gate (default `disabled`) is enabled.
---
```release-note
ServerSideApply: The feature gate `ServerSideApply=true` configures the certificate-shim controllers to use Kubernetes Server Side Apply on Certificate resources. 
```
/kind feature
=> Server Side Apply: Adds support for certificate-shim controllers to use SSA with Feature Gate

build/images.bzl
As reminded by #4033 - this is a manual cherry pick of the latest base image for release-1.6, since the latest-base-images script wasn't present there.
We don't need to cut a release for this, but it's worth having it backported in case we do release.
/kind cleanup
```release-note
NONE
```
=> [release-1.6] bump base image

make/manifests.mk, make/tools.mk
Fixes the breakage created by #4988
Part of the migration to make: #4712 
/kind bug
```release-note
NONE
```
=> Use absolute path of cmrel

Makefile, make/e2e-setup.mk
| This PR is part of the effort 'moving away from Bazel' tracked in https://github.com/cert-manager/cert-manager/pull/4712 |
|--|
When checking how User-Agent headers would differ from v1.7.1 to v1.8.0, The User-Agent looked off:
cert-manager-issuers/v1.8.0 (linux/amd64) cert-manager/
The ending "/" should be followed by the git commit hash. It seems like we forgot to port [what Bazel does](https://github.com/cert-manager/cert-manager/blob/068c5f08703aa31f48346657343424b73f722fe0/build/version.bzl#L25-L27) to fill AppVersion, AppGitCommit, and AppGitState. This commit adds this feature to the Makefile. The User-Agent should now look like this:
cert-manager-issuers/v1.8.0 (linux/amd64) cert-manager/9dd5f6c85fde2c3ed58cd6c9e465bb5a4c1ca2b2
<----->
This part depends
on the component. …
=> make: the AppVersion and AppGitCommit weren't set

pkg/controller/controller.go, pkg/metrics/metrics.go
This adds more visibility to potential issues ranging from things like connection problems to the API or webhooks to possible hard errors.
For context, please see #4956
/kind feature
```release-note
Introducing a new metric `controller_sync_error_count` counting the number of errors during sync() of a controller.
```
=> Add controller_requeue_count metric

design/20220118.certificate-issuance-exponential-backoff.md
Design for expontial backoff for retrying failed certificate issuances.
Note: this design currently assumes binary exponential backoff with delay periods 1h, 2h, 4h etc up to 32h at which point it would remain at 32h till reset (resetting can only happen via a successful issuance). The delay periods could be changed and that would not affect this design.
Related issues:
- #4727 
=> Design for exponential backoff

deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, internal/apis/acme/types_issuer.go, internal/apis/acme/v1alpha2/types_issuer.go, internal/apis/acme/v1alpha3/types_issuer.go, internal/apis/acme/v1beta1/types_issuer.go, internal/apis/certmanager/validation/BUILD.bazel, internal/apis/certmanager/validation/issuer.go, internal/apis/certmanager/validation/issuer_test.go, pkg/apis/acme/v1/types_issuer.go
Previously, in v1alpha1, an HTTPRoute was matched to a Gateway using the label selectors present on the Gateways. For example, with the following Gateway:
```yaml
apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata:
name: acmesolver
spec:
listeners:
- protocol: HTTP
port: 80
routes:
kind: HTTPRoute
selector:
matchLabels:
app: foo
```
You would have to use the following labels on the HTTPRoute in order to get the above Gateway to be used:
```yaml
apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
labels:
app: foo
```
With v1alpha2, the label selectors have been dropped. Instead, the HTTPRoute has to give a direct reference to the Gateway:
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
spec:
parentRefs:
- kind: Gateway
name: acmesolver …
```
=> Gateway API: with v1alpha2, the labels have become optional

hack/fetch-old-crd.sh, make/test.mk
If we're in the middle of a cert-manager release we'll have a git tag created for that release, but won't have a GitHub release created yet. That means that an attempt to download old CRDs for our versionchecker test will fail for that version, with a 404 error.
An alternative approach would be to use the GitHub API to query for existing non-draft releases - but that introduces a new point of failure whereby we can easily hit a rate limit, or else introduces the need for a GitHub API token.
The GitHub API also has the issue that it doesn't present every release in one API call, which complicates fetching releases using curl and uses even more rate-limit capacity.
The approach here is simple; we ignore tags for which the release 404s, download manifests for which the release gives a 200, …
=> Gracefully handle 404s when fetching old CRDs

Makefile
The GOFLAGS make variable was set after "include make/cmctl.mk", leading to the warning:
Makefile:34: warning: undefined variable 'RELEASE_VERSION'
Makefile:34: warning: undefined variable 'GITCOMMIT'
~I also fixed the warning `warning: undefined variable 'CI'` that was caused by referencing a make variable that may not exist. Note that `ifdef CI` didn't seem to work when running:~
```sh
CI=true make e2e-setup -j8
```
~I haven't investigated why, and fell back to using `printenv CI`.~
/kind cleanup
```release-note
NONE
```
=> make: GOFLAGS missing when building cmctl and kubectl_cert-manager

make/release.mk
The bundles target is incorrect in a release since it won't generate release metadata which we require when publishing a release
/kind bug
```release-note
NONE
```
=> Fix target when building containers for release

deploy/charts/cert-manager/templates/rbac.yaml, internal/BUILD.bazel, internal/controller/challenges/BUILD.bazel, internal/controller/challenges/OWNERS, internal/controller/challenges/apply.go, internal/controller/challenges/apply_test.go, pkg/controller/acmechallenges/BUILD.bazel, pkg/controller/acmechallenges/controller.go, pkg/controller/acmechallenges/sync.go, pkg/controller/acmeorders/util.go, test/integration/BUILD.bazel, test/integration/challenges/BUILD.bazel, test/integration/challenges/apply_test.go
Branched from #4773 which should be merged first.
This PR implements Server Side Apply for the Challenge controller when the `SeverSideApply` Feature Gate (default `disabled`) is enabled.
Where `UpdateStatus` was previously, a new func are used to check for this feature gate.
---
```release-note
ServerSideApply: The feature gate `ServerSideApply=true` configures the challenges controller to use Kubernetes Server Side Apply on Challenge resources. 
Warning: if you upgrade to cert-manger v1.8 with `ServerSideApply=true`, do make sure there are no `Challenge` resources currently in the cluster. If there are some, you will need to manually delete them once they are in 'valid' state as cert-manager post-v1.8 …
```
=> Server Side Apply: Adds support for Challenge controllers to use SSA with Feature Gate

deploy/charts/cert-manager/OWNERS
The helm chart OWNERS need not be different from the maintainers any more.
```release-note
NONE
```
=> Remove OWNERS from helm chart

deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/values.yaml
Our environment has some restrictions on service-accounts: We're not allowed to use automountServiceAccountToken=true as default for a service-account but have to explicit enable the service-account-mount in each deployment.
It would be nice, if you could merge that change to make Reloader usable in such einvironments.
Here link to K8s issue
https://github.com/kubernetes/kubernetes/issues/57601
design
```release-note
Implementation for https://github.com/kubernetes/kubernetes/issues/57601
```
=> explicitly mount service-account-token in deployment

make/e2e-setup.mk
We have a number of e2e tests that use the make targets that are failing at setup stage from which we don't get logs at the moment https://testgrid.k8s.io/jetstack-cert-manager-master#ci-cert-manager-e2e-v1-20
When I run the setup steps locally, I see a number of errors, one of which appears to be because of `--force` option that was added to `helm upgrade` command recently https://github.com/irbekrm/cert-manager/commit/3405edf821961bb0bc601ec9bd4381fb8ce3b24f
This appears to have known issues on older versions of Kubernetes as it errors out on repeated runs of the command, see i.e https://github.com/helm/helm/issues/7516 and is likely one of the causes for test failures.
To reproduce the issue locally and see the fix:
1. Run `make e2e-setup-kind K8S_VERSION=1.20`
2. Run `make -j …
=> Don't use --force option to install addons with helm

make/cmctl.mk, make/manifests.mk
Fixes #5027 
/kind bug
These changes are compatible with BSD and GNU `find`, `sed` and `tar`
```console
$ tar ztv -f bin/release/cert-manager-manifests.tar.gz
drwxr-xr-x  0 joakim staff       0 Apr 14 10:47 ./
drwxr-xr-x  0 joakim staff       0 Apr 14 10:47 ./deploy/
drwxr-xr-x  0 joakim staff       0 Apr 14 10:47 ./deploy/chart/
drwxr-xr-x  0 joakim staff       0 Apr 14 10:47 ./deploy/manifests/
-rw-r--r--  0 joakim staff  372226 Apr 14 10:47 ./deploy/manifests/cert-manager.crds.yaml
-rw-r--r--  0 joakim staff  407270 Apr 14 10:47 ./deploy/manifests/cert-manager.yaml
-rw-r--r--  0 joakim staff   62172 Apr 14 10:47 ./deploy/chart/cert-manager-v1.8.0-18-g25b3786e5dbbfd.tgz
-rw-r--r--  0 joakim staff    1746 Apr 14 10:47 ./deploy/chart/cert-manager-v1.8.0-18-g25b3786e5dbbfd.tgz.prov
$ tar …
```
=> trim leading ./ from release archives created by Make

go.mod, go.sum, hack/build/repos.bzl
It looks like one of the dependencies, `golang.org/x/crypto/ssh` has a vulnerability. Updating it to the latest version resolves the issue.
Links:
https://nvd.nist.gov/vuln/detail/CVE-2022-27191
https://avd.aquasec.com/nvd/2022/cve-2022-27191
```release-note
NONE
```
=> Bump golang.org/x/crypto to v0.0.0-20220411220226-7b82a4e95df4

make/e2e-setup.mk, make/e2e.sh
This PR ensures that logs from e2e tests are always saved, by default to ./bin/artifacts
I think that anyone who runs e2e tests locally wants to see the logs if their tests fail without putting in too much effort to figure out how to do that and/or having to re-run the tests.
This should not change the behaviour when tests are run in CI where the `ARTIFACTS` env var should currently be used to determine the location of logs ([here](https://github.com/jetstack/testing/blob/master/images/bazelbuild/coalesce.py#L85))
```release-note
NONE
```
/kind cleanup
=> Always save e2e test logs

LICENSES, go.mod, go.sum, hack/build/repos.bzl, internal/controller/certificaterequests/apply.go, internal/controller/certificates/apply.go, internal/controller/challenges/apply.go, pkg/controller/certificate-shim/sync.go, test/e2e/suite/approval/BUILD.bazel, test/e2e/suite/approval/approval.go, test/e2e/suite/approval/userinfo.go, test/e2e/suite/certificates/BUILD.bazel, test/e2e/suite/certificates/additionaloutputformats.go, test/e2e/suite/certificates/secrettemplate.go, test/e2e/suite/conformance/certificates/BUILD.bazel, test/e2e/suite/conformance/certificates/tests.go, test/e2e/suite/serving/BUILD.bazel, test/e2e/suite/serving/cainjector.go, test/integration/acme/BUILD.bazel, test/integration/acme/orders_controller_test.go, test/integration/certificates/BUILD.bazel, test/integration/certificates/issuing_controller_test.go, test/integration/certificates/metrics_controller_test.go, test/integration/certificates/revisionmanager_controller_test.go, test/integration/certificates/trigger_controller_test.go
This PR attempts to fix resource update conflicts in e2e and integration tests (such as [this](https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/pr-logs/pull/cert-manager_cert-manager/5050/pull-cert-manager-make-e2e-v1-23/1516326073632034816)) by making updates to test resources via server-side apply instead of `Update`/`UpdateStatus`.
- For core resources (`Secret`s) I used client-go's applyconfigurations](https://github.com/kubernetes/client-go/tree/master/applyconfigurations) that seems like really nice functionality
- For our own resource types I used the same functionality that [Josh wrote for server-side apply](https://github.com/cert-manager/cert-manager/tree/master/internal/controller) in controller code
- In cases where fields are being removed from test resources I …
=> Use Apply instead of Update to modify resources in tests

LICENSES, go.mod, go.sum, hack/build/repos.bzl, internal/controller/certificaterequests/apply.go, internal/controller/certificates/apply.go, internal/controller/challenges/apply.go, pkg/controller/certificate-shim/sync.go, test/e2e/suite/approval/BUILD.bazel, test/e2e/suite/approval/approval.go, test/e2e/suite/approval/userinfo.go, test/e2e/suite/certificates/BUILD.bazel, test/e2e/suite/certificates/additionaloutputformats.go, test/e2e/suite/certificates/secrettemplate.go, test/e2e/suite/conformance/certificates/BUILD.bazel, test/e2e/suite/conformance/certificates/tests.go, test/e2e/suite/serving/BUILD.bazel, test/e2e/suite/serving/cainjector.go, test/integration/acme/BUILD.bazel, test/integration/acme/orders_controller_test.go, test/integration/certificates/BUILD.bazel, test/integration/certificates/issuing_controller_test.go, test/integration/certificates/metrics_controller_test.go, test/integration/certificates/revisionmanager_controller_test.go, test/integration/certificates/trigger_controller_test.go
Reverts cert-manager/cert-manager#5077
As this seem to still have resource conflicts, see https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1651567807840999
```release-note
NONE
```
=> Revert "Use Apply instead of Update to modify resources in tests"

deploy/charts/cert-manager/Chart.template.yaml
Add minimum supported Kubernetes version to helm chart. Ref: https://cert-manager.io/docs/installation/supported-releases/
fixes https://github.com/jetstack/cert-manager/issues/4132
```release-note
NONE
```
=> Add minimum Kubernetes version constraint to chart

pkg/controller/acmechallenges/BUILD.bazel, pkg/controller/acmechallenges/sync.go, pkg/controller/acmechallenges/sync_test.go, test/unit/gen/challenge.go
I've added a test for the happy path of running cleanup when the Challenge has a DeletionTimestamp and the finalizer is present.
I'll try and improve things further in later PRs. Here are some of the problems I see:
/kind cleanup
```release-note
NONE
```
=> Challenge cleanup improvements

deploy/crds/crd-issuers.yaml, deploy/crds/crd-orders.yaml
In #4841 the cainjector annotations were removed from most of our CRDs except `Order` and `Issuer` (by mistake).
This PR removes the annotations from those two CRDs.
Note that the annotations being present should have had no effect as cainjector anyway parses all CRDs, but only acts on ones that have the conversion webhook's client config section- so this PR is just cleanup.
```release-note
NONE
```
Fixes #5107 
/kind cleanup
=> Remove leftover cainjector annotations from our CRDs

pkg/controller/certificatesigningrequests/venafi/venafi.go
certificate signing request e2e tests with Venafi TPP/Cloud issuers [are now failing](https://testgrid.k8s.io/jetstack-cert-manager-master#ci-cert-manager-venafi), it appears because the Venafi client is not initialized with metrics.
The functionality with the new Venafi metric was added in https://github.com/cert-manager/cert-manager/pull/5053 which has not been released yet.
We're not running the Venafi tests together with the rest of the e2e tests and looking at https://github.com/cert-manager/cert-manager/pull/5053 I think we didn't run the Venafi tests for that PR, so this issue was not caught.
I've ssh-ed to test pod and saw that there was a nil pointer exception:
```
I0516 15:56:27.317893       1 logs.go:59] vCert: Got 200 OK status for POST …
```
=> Ensure that Venafi client for CSRs gets initialized with metrics

deploy/charts/cert-manager/values.yaml
When deploying on a cluster with Windows nodes the startupapicheck pod is scheduled on to a Windows node rather than a Linux node. The other pods in the chart are correctly assigned to Linux nodes.
bug/missing
```release-note
Select startupapicheck on to Linux nodes only.
```
=> Set the startupapicheck nodeSelector to linux

pkg/webhook/server/tls/dynamic_source.go
The purpose of this PR is to make it clear what certificate cert-manager is renewing in the DynamicSource webhook. Specifically, it addresses Issue #4684. 
Screenshots: 
cleanup
```release-note
Added more verbose logging info for certificate renewal in DynamicSource webhook to include DNSNames. 
```
=> Improve logging output for webhook cert renewal

README.md, deploy/charts/cert-manager/Chart.template.yaml
The SHA for the logo is the latest master in my local checkout.
/kind cleanup
```release-note
NONE
```
=> Add URL for cert-manager website to chart + update logo URL

design/template.md
This PR adds a design template as discussed earlier in dev meetings.
This template could be used by folks who want to contribute a more complex feature/enhancement to cert-manager and need to submit a design beforehand. The general approach of requiring a design should help us improve the review process and make it easier for maintainers and users to understand and evaluate new features.
The template partially adapted from https://github.com/kubernetes/enhancements/blob/a86942e8ba802d0035ec7d4a9c992f03bca7dce9/keps/NNNN-kep-template/README.md - I have tried to remove the more strict or unusual for us requirements as generally I would like to _not_ introduce new 'policies' in this PR- they can always be added later separately as need arises.
If this gets merged, I will update our …
=> Adds design template

.gitignore, make/manifests.mk, make/release.mk
The intention of `make release-artifacts` was to build everything possible locally, ignoring signatures which most people won't want to do locally. As part of the development of the makefile workflow the signed helm chart image crept into the target which removed its usefulness.
This PR will ensure that that target only builds unsigned things.
(Also adds alternative namings for the `bin` directory to `.gitignore`, in preparation for #5130 )
/kind bug
```release-note
Ensure that `make release-artifacts` only builds unsigned artifacts as intended
```
=> Fix `release-artifacts` target

make/config/kind/config_etcd_no_fsync.yaml
This PR ensures that `--unsafe-no-fsync` flag is actually passed to etcd as part of creating kind cluster for running e2e tests.
It appears that etcd flags are not passed when using `v1beta2` kubeadm ClusterConfiguration resource, see https://github.com/kubernetes-sigs/kind/issues/1839
To verify the bug:
1. Run ` kind create cluster --config make/config/kind/config_etcd_no_fsync.yaml` against current master
2. Run `kubectl get po -n kube-system etcd-kind-control-plane  -oyaml` and verify that the flag is not passed
To verify the fix repeat the same steps from this PR and check that the flag is set
```release-note
NONE
```
/kind cleanup
=> Fix etcd flags

hack/verify-goimports.sh, make/tools.mk
1. Prefixes `goimports` output to make it clear what's going on when `goimports` fails
2. Adds install for `rclone` on different platforms. This'll be used in place of `gsutil` for uploading files to GCS.
/kind feature
```release-note
NONE
```
=> Goimports improvement / rclone tool install

deploy/charts/cert-manager/templates/servicemonitor.yaml
As discussed in our standup and on https://github.com/cert-manager/cert-manager/pull/4844 this PR reverts the check for whether Prometheus monitoring API exists before creating `ServiceMonitor` to avoid introducing a dependency ordering which does not fit GitOps installers model.
I am planning to backport this to 1.8 and release a patch release with this revert and Go patch version bump to reduce scanner spam for folks who run those https://github.com/cert-manager/cert-manager/issues/5161
```release-note
Reverts additional check for ServiceMonitor
```
/kind cleanup
=> Reverts additional check for whether Prometheus APIs exist before creating ServiceMonitor

WORKSPACE, make/tools.mk
This PR bumps Go 1.17.8 -> 1.17.11 to get latest security fixes.
(We are not aware of any of the security issues actually affecting cert-manager. See https://github.com/cert-manager/cert-manager/issues/5161 for context)
```release-note
Bumps Go 1.17.8 -> 1.17.11 to get latest security fixes
```
/kind cleanup
=> Bump patch version of Go

make/release.mk
Follows on from #5200 . Will be followed by a change to https://github.com/cert-manager/release
/kind feature
```release-note
Add a make target for publishing cert-manager releases to GCS
```
=> Add target for publishing a release to GCS using rclone

make/release.mk, make/tools.mk
This backports #5205 and part of #5200 for release-1.8, allowing us to use `make publish-release` to stage a release rather than having custom logic in `cert-manager/release`.
The reason for backporting this is that it'll enable us to use the exact same commands for releasing both 1.8 and 1.9, which will allow us to avoid having to check out separate versions of `cert-manager/release` to release different versions.
/kind feature
```release-note
Adds rclone-based method for staging cert-manager releases to GCS
```
=> release-1.8: rclone

pkg/issuer/venafi/client/BUILD.bazel, pkg/issuer/venafi/client/fake/venafi.go, pkg/issuer/venafi/client/venaficlient.go, pkg/issuer/venafi/setup.go, pkg/issuer/venafi/setup_test.go, test/e2e/framework/addon/venafi/cloud.go, test/e2e/framework/addon/venafi/tpp.go, test/e2e/suite/issuers/venafi/BUILD.bazel, test/e2e/suite/issuers/venafi/cloud/BUILD.bazel, test/e2e/suite/issuers/venafi/cloud/setup.go, test/e2e/suite/issuers/venafi/import.go, test/e2e/suite/issuers/venafi/tpp/setup.go
Fixes #5154 
This is the first PR that fixes the immediate problem: a Venafi Issuer does not verify its access token or API key.
This PR changes the Venafi Issuer to remotely verify its access token (TPP) or API key (Cloud) with a remote server during setup. An invalid (expired, malformed) access token or API key will result in the Issuer setting `Ready=False`.
A follow-up PR will add functionality to periodically periodically perform this check.
Follow-up issue here: https://github.com/cert-manager/cert-manager/issues/5201
bug
```release-note
Fixed a bug where the Venafi Issuer would not verify its access token (TPP) or API key (Cloud) before becoming ready. Venafi Issuers will now remotely verify the access token or API key.. (#5154, @jahrlin)
```
=> add VerifyCredentials to Venafi issuers setup

cmd/ctl/pkg/install/install.go
Signed-off-by: Mark Shields <4237425+beejiujitsu@users.noreply.github.com>
Fix a simple spelling typo.
documentation
```release-note
NONE
```
=> fix(cmctl): typo in 'x install --help' text

pkg/controller/certificaterequests/BUILD.bazel, pkg/controller/certificaterequests/controller.go
The CertificateRequests controllers are not waiting for the core secrets informer to be fully synced, leading to race conditions where the indexer does not contains the Secret being queried during the sign process.
This PR is adding an explicit condition into the `mustSync` list that will make sure the secrets informer must be fully synced before the controller starts.
Fixes #5216 
/kind bug
```release-note
CertificateRequests controllers must wait for the core secrets informer to be synced
```
Signed-off-by: Rodrigo Fior Kuntzer <rodrigo@miro.com>
=> Fix secrets informer race condition on CertificateRequests controllers

Makefile, hack/build/.kazelcfg.json, hack/update-bazel.sh, hack/verify-goimports.sh, internal/test/paths/paths.go, make/README.md, make/ci.mk, make/cluster.sh, make/cmctl.mk, make/containers.mk, make/e2e-setup.mk, make/e2e.sh, make/git.mk, make/licenses.mk, make/manifests.mk, make/release.mk, make/server.mk, make/test.mk, make/tools.mk, make/util.mk
As per [this doc](https://pkg.go.dev/cmd/go#hdr-Package_lists_and_patterns):
> Directory and file names that begin with "." or "_" are ignored by the go tool, as are directories named "testdata". 
We never want any go files inside `bin` to add dependencies for our go.mod - nor do we want them to be scanned by anything. By making the whole dir ignored by go, we avoid a class of issues where the go tooling might consider files under `bin` to be part of the project.
To achieve this, we change manual uses of `bin` to `$(BINDIR)`, so it's easier to change permanently or temporarily in the future.
After this PR merges we should immediately merge https://github.com/jetstack/testing/pull/699 which will re-enable download cacheing in CI.
/kind feature
```release-note
Change default build dir from …
```
=> Change name of `bin` dir to `_bin` and make it configurable

.gitignore, pkg/acme/accounts/client.go, pkg/acme/client/middleware/logger.go, pkg/controller/BUILD.bazel, pkg/controller/certificates/issuing/issuing_controller.go, pkg/controller/clusterissuers/BUILD.bazel, pkg/controller/clusterissuers/sync.go, pkg/controller/globals/BUILD.bazel, pkg/controller/globals/timeout.go, pkg/controller/issuers/BUILD.bazel, pkg/controller/issuers/sync.go
This is a manual cherry-pick of #5226, intended as a sister PR for #5231 .
This required manual intervention since we added an import for these changes and that needed to be changed back to our old import path which was used for 1.7 (i.e. changing `github.com/cert-manager/cert-manager/pkg/controller/globals` to `github.com/jetstack/cert-manager/pkg/controller/globals` in the Issuer and ClusterIssuer controllers)
This also - as a bonus - adds our new bindir to `.gitignore` which is a pure developer QoL improvement with absolutely no runtime impact at all.
```release-note
Increase timeouts for issuer and clusterissuer controllers to 2 minutes and increase ACME client HTTP timeouts to 90 seconds, in order to enable the use of slower ACME issuers which take a long time to process certain …
```
=> [release-1.7] ACME Timeout Increases

make/ci.mk, make/e2e-setup.mk, make/tools.mk
We only use python in one place and probably won't start using it more without some kind of policy change.
We don't need to require that everyone has it installed, and can instead only require it for people who're running the boilerplate check.
/kind cleanup
```release-note
Only require python for the one test we have which needs it, rather than requiring it globally
```
=> Don't require python to be installed for everything

pkg/issuer/venafi/client/request.go
Based on recent discussions around timeouts discussed broadly in [design document](https://github.com/cert-manager/cert-manager/blob/master/design/20220614-timeouts.md) I am following on from the [work on the ACME issuers](https://github.com/cert-manager/cert-manager/pull/5226) to increase an existing timeout in the Venafi Issuer.
This is to resolve https://github.com/cert-manager/cert-manager/issues/5108
`60` seconds is arbitrary and could be changed. Perhaps it should be `90` to be consistent with ACME?
Either way, my goal is to ensure its longer than 10s.
```release-note
Venafi Issuer timeout for retrieving a certificate increased from 10 to 60 seconds. This gives TPP instances longer to complete their workflows and make the certificate available, before cert-manager times out and …
```
=> Increase Venafi issuer timeout on retrieving certificate

cmd/controller/app/options/options.go
The `--dns01-check-retry-period` flag's value is used to configure the period after which a `Challenge` whose propagation check failed should be resynced. Despite the name, it is used for both DNS01 and HTTP01 `Challenge`s.
We cannot change the name of the flag now I suppose, but this PR updates the help output for anyone wanting to configure this period for an HTTP01 `Challenge`. I cannot necessarily think of good use cases for this flag for HTTP01 challenges, but nevertheless I think the description should be correct
(see also https://github.com/cert-manager/cert-manager/issues/5193)
See the flag's value being used [here](https://github.com/cert-manager/cert-manager/blob/master/pkg/controller/acmechallenges/sync.go#L199)
```release-note
NONE
```
Signed-off-by: irbekrm …
=> Corrects the --dns01-check-retry-period flag description

pkg/controller/certificates/keymanager/keymanager_controller.go, pkg/controller/certificates/keymanager/keymanager_controller_test.go, pkg/controller/certificates/util.go, pkg/controller/certificates/util_test.go
This PR improves the warning that is thrown when a user has changed some key size or algorithm in `Certificate`'s spec, but cert-manager is unable to regenerate the private key because `.spec.rotationPolicy` is set to `Never` or is unset.
At the moment user would see this warning on cert's spec:
```
Warning  DecodeFailed  30m   cert-manager-certificates-key-manager  Existing private key in Secret "myib-prod-ca" does not match requirements on Certificate resource, mismatching fields: [spec.keySize]
```
I have changed it to:
```
Warning  CannotRegenerateKey  15s (x2 over 15s)  cert-manager-certificates-key-manager      User intervention required: existing private key in Secret "test1" does not match requirements on Certificate resource, mismatching fields: [spec.privateKey.size], but …
```
=> Fix keyrotation warning

hack/build/print-workspace-status.sh, hack/update-gofmt.sh, test/integration/versionchecker/testdata/fetch.sh
`no such file or directory: /bin/bash`
/kind bug
```release-note
NONE
```
=> Change all scripts #!/bin/bash -> #!/usr/bin/env bash

make/e2e-setup.mk, make/tools.mk
Adds support for using native arm64 binaries for kubebuilder assets
Also adds checks for sha256sum on gateway api assets
To show that the directory structure is unchanged by this PR, on `master` currently:
```console
$ make _bin/downloaded/gatewayapi-v0.4.1
$ tree _bin/downloaded/gatewayapi-v0.4.1 | head -n5
_bin/downloaded/gatewayapi-v0.4.1
└── gateway-api-0.4.1
├── apis
│   ├── v1alpha1
│   │   ├── backendpolicy_types.go
```
And using this PR:
```console
$ make _bin/downloaded/gatewayapi-v0.4.1
$ tree _bin/downloaded/gatewayapi-v0.4.1 | head -n5
_bin/downloaded/gatewayapi-v0.4.1
└── gateway-api-0.4.1
├── apis
│   ├── v1alpha1
│   │   ├── backendpolicy_types.go
```
/kind cleanup
```release-note
NONE
```
=> Kubebuilder Assets darwin/arm64

make/e2e-setup.mk, make/tools.mk
This adds multiple retries on every attempt we make to use curl, which should help to reduce flakes. Uses a $(CURL) variable where possible so that we have the same invocation everywhere.
Also switches to using the more verbose curl arguments, in an attempt to make it easier to reason about how curl is configured.
Note the documentation for curl's retry flag:
```text
--retry <num>
If a transient error is returned when curl tries to perform a transfer, it will retry this number of times
before giving up. Setting the number to 0 makes curl do no retries (which is the default).
Transient error means either: a timeout,  an  FTP  4xx  response
code or an HTTP 408 or 5xx response code.
When  curl is about to retry a transfer, it will first wait one second and then for all forthcoming
retries it …
```
=> Use variable for curl, add retries

make/e2e-setup.mk, make/tools.mk
Manual backport of #5272
This adds multiple retries on every attempt we make to use curl, which should help to reduce flakes. Uses a $(CURL) variable where possible so that we have the same invocation everywhere.
Also switches to using the more verbose curl arguments, in an attempt to make it easier to reason about how curl is configured.
The backport of this was manual because of conflicts relating to `$(BINDIR)`, and our new methods of installing kubebuilder tools and the gatewayapi code
/kind feature
```release-note
Use multiple retries when provisioning tools using `curl`, to reduce flakes in tests and development environments
```
=> [release-1.8] Use variable for curl, add retries

deploy/charts/cert-manager/values.yaml, devel/addon/kyverno/BUILD.bazel, devel/addon/kyverno/install.sh, devel/addon/kyverno/kustomization.yaml, devel/addon/kyverno/policy.yaml, make/config/kyverno/kustomization.yaml, make/config/kyverno/policy.yaml, make/e2e-setup.mk, pkg/issuer/acme/http/pod.go, test/e2e/images.bzl
Updates kyverno to v1.7.1, kyverno `policy.yaml` to the current PSS/restricted policies,
and fixes cert-manager deployments to comply with the updated policies.
Fixes #5258 
Fixes #4693 @wallrj 
See #4036 for prior work.
Notes to maintainers:
1. The first commit updates the kyverno version and policies, but the e2e tests still pass because kyverno and its policies are installed *after* the cert-manager deployment
2. The second commit updates the cert-manager and ACME/http deployments to comply
The following command demonstrates that cert-manager v1.8.2 does not comply with the updated policies:
```bash
kustomize build https://github.com/joebowbeer/cert-manager//make/config/kyverno\?ref=kyverno-sync | \
kyverno apply --policy-report -r \
<(wget -qO- …
```
=> fix: update kyverno version, policy.yaml and securityContexts

deploy/charts/cert-manager/README.template.md
Update `securityContext` descriptions in the helm README. (Follow-up to #5259)
Default security context values are documented in a new section.
Bumped minimum Kubernetes version to 1.20+ as per cert-manager release 1.9. The securityContext defaults require Kubernetes 1.19+
/kind cleanup
```release-note
NONE
```
=> Update helm README file

Makefile, make/cmctl.mk, make/server.mk, make/tools.mk
I also took the opportunity to document the three most important "build" variables in "make help".
Fixes #5020 
/kind bug
```release-note
`cmctl` and `kubectl cert-manager` now report their actual versions instead of "canary", fixing issue [#5020](https://github.com/cert-manager/cert-manager/issues/5020)
```
=> Make: cmctl and kubectl-cert_manager are using two -ldflags, the second -ldflags is cancelling the first one

Makefile, make/cmctl.mk, make/server.mk, make/tools.mk
Manual backport of #5022 - part of #5020 
(Actually not that manual; this is the original commit which @maelvls wrote. #5022 now applies against master and release-1.9 and the original applies against release-1.8)
/kind bug
```release-note
`cmctl` and `kubectl cert-manager` now report their actual versions instead of "canary", fixing issue [#5020](https://github.com/cert-manager/cert-manager/issues/5020)
```
=> [release-1.8] make: cmctl and kubectl-cert_manager were using two -ldflags

make/tools.mk
[This change](https://github.com/cert-manager/cert-manager/commit/35f2206404785659deaf674cb1d79bf6176dd1fd#r78206534) added in #5130 introduced a bug where the target to create `$(BINDIR)` was accidentally removed. Sometimes when running in parallel a [dependency](https://github.com/cert-manager/cert-manager/blob/44a022a83c7d18374b3f7f4ce6c6fbee9ae3a372/make/git.mk#L44) on `$(BINDIR)` would fail since there's no target for creating it. It was often implicitly created by `mkdir -p`.
This PR adds an explicit target for `$(BINDIR)`
/kind bug
/cherry-pick release-1.9
```release-note
NONE
```
=> add missing target for $(BINDIR)

test/e2e/suite/certificates/BUILD.bazel, test/e2e/suite/certificates/secrettemplate.go
Helps avoid flakes such as https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/logs/ci-cert-manager-next-e2e-v1-22/1546362296777838592
Previously we created a Certificate at the start of this `It` block & waited for it to become ready before proceeding. We perform quite a few other steps before we then go onto actually attempt an update of the SecretTemplate field.
During this time, in some cases there are updates being made to the Certificate that we *don't* observe, which leaves us with a stale resource.
/kind flake
```release-note
NONE
```
=> Retry update on conflicts during SecretTemplate tests to avoid test flakes

make/tools.mk
Manual cherry-pick of #5288  since the bot didn't raise the cherry-pick PR.
/kind bug
```release-note
NONE
```
=> [release-1.9] Add missing target for $(BINDIR)

make/README.md, make/e2e-setup.mk
https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html
This is kinda academic since this change affects PHONY targets, but I think it's worth maintaining this pattern where possible
/kind cleanup
```release-note
NONE
```
=> Use order-only prerequisites where possible for tools

test/e2e/suite/certificates/additionaloutputformats.go
/kind flake
This PR is part of the larger [flaky e2e test initiative](https://github.com/cert-manager/cert-manager/issues/4950).
The `AdditionalOutputFormat` e2e tests are regularly featured in the periodic e2e testing as failing or flaky. [testgid](https://testgrid.k8s.io/jetstack-cert-manager-next#ci-cert-manager-next-e2e-v1-22).
I was able to reliably replicate the `AdditionalOutputFormats` e2e test flakes locally. I did this by setting up the e2e kind cluster and dependencies, then running the following in **2** separate terminals simultaneously with the `-untilItFails` flag set on ginkgo. This forces the cert-manager controller to come under load and queue workers, which subsequently surfaces the raciness in the tests which cause test failures
```terminal
make e2e …
```
=> E2E test flakes: Additional output formats

pkg/controller/certificatesigningrequests/selfsigned/selfsigned.go, pkg/controller/certificatesigningrequests/selfsigned/selfsigned_test.go
/kind bug
As part of the [flaky e2e test initiative work](https://github.com/cert-manager/cert-manager/issues/4950), one of the reoccurring flaky tests is the  CertificateSigningRequest with SelfSigned issuer. Upon investigating, the reason for this is that there is a race in our test whereby [the Secret we create to contain the private key](https://github.com/cert-manager/cert-manager/blob/519d4dd80378581381b19ee32c5cbc7446307132/test/e2e/suite/conformance/certificatesigningrequests/selfsigned/selfsigned.go#L67) may not be yet observed by the [Secret lister in the cert-manager controller](https://github.com/cert-manager/cert-manager/blob/519d4dd80378581381b19ee32c5cbc7446307132/pkg/controller/certificatesigningrequests/selfsigned/selfsigned.go#L113).
Currently, cert-manager will mark a …
=> [SelfSigned] CertificateSigningRequest: don't mark failed when referenced Secret doesn't exist

internal/apis/certmanager/validation/issuer.go, internal/apis/certmanager/validation/issuer_test.go
In PR https://github.com/cert-manager/cert-manager/pull/5194, we introduced a validation whereby an issuer would be rejected if it did
not contain `AccessKeyID` or `SecretAccessKeyID` when using the route53 DNS
solver. This is incorrect, since neither should need to be defined when
using AWS ambient credentials.
This is a critical bug which should be backported to `v1.9`.
/kind bug
fixes https://github.com/cert-manager/cert-manager/issues/5334
```release-note
DNS Route53: Remove incorrect validation which rejects solvers that don't define either a `accessKeyID` or `secretAccessKeyID`.
```
=> Remove incorrect Route53 validation on AccessKeyID and SecretAccessKeyID

Makefile, make/scan.mk, make/tools.mk
NB: If this is merged before #5361 and #5360 both merge, `make trivy-scan-all` will report vulnerabilities. After those PRs merge, all vulns should be fixed (at the time of writing!)
This was motivated by a [slack thread](https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1659436139392089) pointing out we were marked poorly on artifacthub vuln scans. We can use the same scanner locally to catch things in CI / on local machines.
After this PR merges, we can use https://github.com/cert-manager/release/pull/85 to generate periodic tests which will scan each container regularly.
/kind feature
```release-note
Add make targets for running scans with trivy against locally built containers
```
=> Add Trivy scanning make targets

hack/concat-yaml.sh, hack/extractcrd/main.go, make/manifests.mk
The current makefiles for generating static manifests and CRDs are quite complex.
I changed the process, such that the CRD templates are generated from the same chart as the other static manifests.
/kind feature
```release-note
NONE
```
=> Simplify static manifest generation

deploy/crds/crd-certificaterequests.yaml, deploy/crds/crd-certificates.yaml, internal/apis/certmanager/types.go, internal/apis/certmanager/v1alpha2/types.go, internal/apis/certmanager/v1alpha3/types.go, internal/apis/certmanager/v1beta1/types.go, internal/cainjector/feature/features.go, internal/controller/certificates/policies/checks.go, internal/controller/certificates/policies/policies.go, internal/webhook/feature/features.go, pkg/api/scheme.go, pkg/api/util/conditions.go, pkg/apis/certmanager/v1/types.go, pkg/controller/certificate-shim/gateways/controller.go, pkg/controller/certificate-shim/helper.go, pkg/controller/certificate-shim/ingresses/controller.go, pkg/controller/certificate-shim/sync.go, pkg/controller/certificates/util.go, pkg/issuer/acme/dns/acmedns/acmedns.go, pkg/issuer/acme/dns/akamai/akamai.go, pkg/issuer/acme/dns/akamai/akamai_test.go, pkg/issuer/acme/dns/cloudflare/cloudflare.go, pkg/util/pki/parse.go, pkg/webhook/admission/initializer/interfaces.go, test/unit/gen/certificate.go
Some devs might use go1.19 already.
Often IDEs will try to format documents on save, causing unrelated doc changes.
```release-note
NONE
```
=> Apply go fmt for go1.19

hack/verify-goimports.sh, make/ci.mk
Backports #5124 to release-1.8; we have a separate test to verify the chart (see commit message). I'm not sure why I ever added `verify-chart` to `ci-presubmit` but it was a mistake.
This will unblock the [periodic tests](https://testgrid.k8s.io/cert-manager-periodics-release-1.8#ci-cert-manager-release-1.8-make-test).
Also stops goimports from looking in bin; this is fixed by the BINDIR change in release-1.9 and onwards, but that would be too big to backport
/kind bug
```release-note
NONE
```
=> [release-1.8]: Don't verify chart in ci-presubmit

pkg/controller/certificates/issuing/issuing_controller.go, pkg/controller/certificates/readiness/readiness_controller.go, test/integration/certificates/generates_new_private_key_per_request_test.go, test/integration/framework/helpers.go
Increase test coverage & verify behaviour of certificates controller.
This also fixes a bug when an issuer implementation marks a CertificateRequest with `InvalidRequest`, leading to the usual failure handling code not being invoked and the CR being 'stuck'/not retried.
/kind bug
/area testing
```release-note
Fix issue where CertificateRequests marked as InvalidRequest did not properly trigger issuance failure handling leading to 'stuck' requests
```
/cc @JoshVanL
=> Ensures CertificateRequests marked as 'InvalidRequest' are properly handled as failures & retried

test/e2e/suite/serving/cainjector.go
This PR fixes a flaky test with minimal effort by adding a few random characters to the names of some resources being created.
```console
from-secret-not-allowed-hook
from-secret-not-allowed-hook-k4fp8
```
Here is the flake: https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/logs/ci-cert-manager-master-e2e-v1-23/1555250074131369984
Reproduce by running this command in two terminals simultaneously:
```console
make e2e GINKGO_FOCUS='.CA Injector'
``` 
/kind flake
```release-note
NONE
```
=> Flaky test: add random suffix to webhooks in CA Injector e2e tests

deploy/charts/cert-manager/values.yaml
As of #4935 cert-manager no longer uses a ConfigMap for leader election. The Leases resource is used instead.
Changed the note in the chart values.yaml to reflect this change, to avoid future confusion.
Signed-off-by: Peter Fiddes <peter.fiddes@gmail.com>
Keep chart "documentation" up to date
documentation
```release-note
NONE
```
=> docs: Correct reference to lease not config map

cmd/controller/app/options/options.go, pkg/issuer/acme/http/pod.go
Document that new configuration options for ACME HTTP-01 solver pod need to be added via pod spec template on issuer config instead of adding new flags to controller.
See https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1660041935692369 for context
I considered documenting this in the contributing section on the website, but it feels too small for that and seems like it would be more noticeable by anyone looking to add extra config options as code comments.
```release-note
NONE
```
Signed-off-by: irbekrm [irbekrm@gmail.com](mailto:irbekrm@gmail.com)
=> Document that pod template spec should be used instead of flags

deploy/charts/cert-manager/templates/webhook-deployment.yaml
Signed-off-by: Eugen Fohlenweider <eugen.fohlenweider@hotmail.com>
If you are using Linkerd service mesh in the latest stable version with [Authorization Policy](https://linkerd.io/2.11/features/server-policy/) (think of it as a sort of traffic management) then you will stumble upon this [Issue](https://github.com/linkerd/linkerd2/issues/7640). 
All ports where this "traffic management" is applied to needs to be in the CointainerPort spec.
This issue is already fixed in the linkerd-proxy, but it is not part of an stable version yet and this might take a while.
The only port which is missing in the ContainerPort spec is the healthcheck port for the cert-manager-webhook deployment.
```release-note
NONE
```
=> added healthcheck to containers port spec

pkg/controller/certificatesigningrequests/acme/acme.go, pkg/controller/certificatesigningrequests/controller.go, pkg/controller/certificatesigningrequests/selfsigned/checks.go, pkg/controller/certificatesigningrequests/selfsigned/checks_test.go, pkg/controller/certificatesigningrequests/selfsigned/selfsigned.go, pkg/controller/certificatesigningrequests/selfsigned/selfsigned_test.go, test/e2e/suite/certificatesigningrequests/doc.go, test/e2e/suite/certificatesigningrequests/selfsigned/selfsigned.go, test/unit/crypto/crypto.go
Related: #5336
/milestone v1.10
This PR adds a workqueue function to re-sync CertificateSigningRequests when the target Secret contained in `experimental.cert-manager.io/private-key-secret-name` is informed. This results in fixing a problem where a request would never be signed if the target Secret was miss-configured or created _after_ the request.
To do this, the base CertificateSigningRequest controller has been updated to no longer accept extra resources which will be informed on ownership, to now a more extendable function which is needed here.
Added some e2e tests to prove functionality (which were failing before the controller changes).
**Note** This also changes the behavior for when the private key secret has invalid data- now just firing an event and no longer marking the …
=> CertificateSigningRequest: re-sync SelfSigned CertificateSigningRequest when target Secret is informed

test/e2e/suite/certificatesigningrequests/selfsigned/selfsigned.go
Currently e2e test periodics are failing because we don't have the CSR e2e tests gated on feature gates.
/assign @jahrlin 
```release-note
NONE
```
=> Adds `ExperimentalCertificateSigningRequestControllers` to CSR e2e tests.

deploy/charts/cert-manager/templates/servicemonitor.yaml, deploy/charts/cert-manager/values.yaml
I need this:
```yaml
prometheus:
servicemonitor:
enabled: true
annotations:
argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
```
(More info [here](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types))
feature
```release-note
Add annotations for ServiceMonitor in helm chart
```
=> Add annotations for ServiceMonitor in helm chart

make/e2e-ci.sh, make/test.mk
This should fix an issue where kind-logs from CI builds would not always be uploaded
Moved it to a script so that the commands can be run independently
/kind bug
```release-note
NONE
```
=> move e2e-ci to a script

make/tools.mk
In #5398, I introduced Makefile target generation for the tools.mk file.
Somehow, I missed that the rclone target was not working yet.
This PR fixes that bug.
/kind bug
```release-note
NONE
```
=> Use new tools.mk structure for rclone

pkg/controller/controller.go, test/e2e/suite/issuers/selfsigned/certificaterequest.go
This fixes two instances where loop variables were being incorrectly
used:
- using a loop variable in a closure passed to `ginkgo.It()` is
incorrect, as the capture happens by reference and only the last test
case will be executed (multiple times).
- a similar issue happens in the context of a goroutine; specifically,
we need to create a copy of the `runDurationFunc` before calling it in
a goroutine as done by the controller's `Run` function.
With regards to the second issue, I believe it never came to the
surface because, in production code, only one `runDurationFunc` is
passed; tests don't exercise the multiple funcs path either.
Issues were automatically found with the `loopvarcapture` linter.
bug
```release-note
NONE
```
=> Fix incorrect uses of loop variable

pkg/acme/webhook/registry/challengepayload/challenge_payload.go
Fixes #5450, avoiding mismatched interfaces between cert-manager and k8s.io/apiserver
```release-note
NONE
```
---
Aside from that, I didn't bump k8s deps at the same time, since these breaking commits aren't tagged yet (neither on apiserver nor on components-base), as they landed in the default branches there a few hours ago only.
=> Ensure forward-compatibility with k8s.io/apiserver's Storage interface

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/networkpolicy-egress.yaml, deploy/charts/cert-manager/templates/networkpolicy-webhooks.yaml, deploy/charts/cert-manager/values.yaml
Add support for NetworkPolicies in helm chart, so we can deploy cert-manager into NetworkPolicies enabled cluster without external actions
This is new feature inside helm charts deployment 
```release-note
Helm: Add NetworkPolicy support
```
=> helm: Add NetworkPolicy support

test/e2e/suite/certificates/secrettemplate.go
This is a manual cherry-pick of #5318. As explained in https://github.com/cert-manager/cert-manager/issues/5444#issuecomment-1251183185, I had to manually create the cherry-pick PR due to a conflict.
The commands I had to run on my machine are the following:
```sh
git fetch origin refs/pull/5318/head:test-e2e-flake-secret-template
git checkout test-e2e-flake-secret-template
git checkout release-1.8
git pull
git cherry-pick test-e2e-flake-secret-template
```
The reason I run `git cherry-pick` only once is because this branch has a single commit. Otherwise, I would have to run `git cherry-pick` for each commit in the branch.
```release-note
NONE
```
=> [release-1.8] E2E test flakes: SecretTemplate

pkg/controller/certificates/metrics/controller.go, pkg/metrics/certificates.go, pkg/metrics/certificates_test.go, pkg/metrics/metrics.go, test/integration/certificates/metrics_controller_test.go
closes #4454, replaces #5038
Thanks to @4molybdenum2 for doing the initial work, hopefully this can help get this across the finish line.
/cc @irbekrm
Adding issuer name, group and kind to the following metrics:
```
certmanager_certificate_expiration_timestamp_seconds
certmanager_certificate_renewal_timestamp_seconds
certmanager_certificate_ready_status
```
/kind feature
```release-note
Add issuer_name, issuer_kind and issuer_group labels to "certificate_expiration_timestamp_seconds", "certmanager_certificate_renewal_timestamp_seconds" and "certmanager_certificate_ready_status" metrics
```
=> Add issuer_{group|kind|name} labels to prom metrics

internal/controller/feature/features.go, pkg/controller/certificates/requestmanager/requestmanager_controller.go, pkg/controller/certificates/requestmanager/requestmanager_controller_test.go, test/unit/gen/certificaterequest.go
Modify certificaterequest controller to generate CertificateRequest with name as function of certificate name and revision.
As mentioned in #4956 , multiple CertificateRequest objects are created for a fixed certificate object and fixed revision. This happens when the CertificateRequest creation request from `requestmanager` controller takes more than 5 seconds to create the resource in the api server.
On timeout, the request is re-tried and a new CertificateRequest is created but with a different name. This results in multiple CertificateRequests for a given certificate name and given revision.
In this PR, this issue is being fixed by making the CertificateRequest name to be a function of certificate name and the revision. This makes sure, even if there are multiple CertificateRequest …
=> Generate Certificate Request with predictable name

pkg/controller/certificaterequests/acme/acme_test.go, pkg/controller/certificaterequests/ca/ca_test.go, pkg/controller/certificaterequests/selfsigned/selfsigned_test.go, pkg/controller/certificaterequests/sync.go, pkg/controller/certificaterequests/sync_test.go, pkg/controller/certificaterequests/vault/vault_test.go, pkg/controller/certificaterequests/venafi/venafi_test.go
When the default approver is disabled and an approver is not currently running, it can be not clear to uses why a request is not progressing. This can be frustrating for users are can seem like things are not working correctly.
PR updates the internal signers to fire an event on CertificateRequests which are not yet approved so is clear why the request is not progressing.
/milestone v1.11
/kind feature
/assign @irbekrm 
```release-note
Signers fire an event on CertificateRequests which have not been approved yet. Used for informational purposes so users understand why a request is not progressing.
```
=> Fire event on CertificateRequest when it has not been Approved yet.

.github/workflows/scorecards.yml, README.md
Closes #5440 
This is about the activation of [Scorecard GitHub Action][sc-gha] as described in the [issue](https://github.com/cert-manager/cert-manager/issues/5440) above.
feature
```release-note
NONE
```
[sc-gha]: https://github.com/ossf/scorecard-action
=> Enable OpenSSF Scorecard Github Action and Badge

.github/workflows/scorecards.yml
Regarding an error after merging the issue #5440 
I've noticed that the Scorecard Github Action is not running with success (https://github.com/cert-manager/cert-manager/actions/runs/3345975741). Don't know for sure when it stoped working since I've tested in the forked repo, but I've upgraded the Scorecard Github Action version and tested again to fix it.
Sorry for not noticing it before.
Here is the screenshot of the action running after the version upgrade
I've tested the badge refering the joycebrum/cert-manager repo (as seen in the print bellow) and it worked too.
bug
```release-note
NONE
```
=> Fix Scorecard Github Action not running

make/tools.mk
There are a few vulns that've been fixed in the two new go 1.19 releases.
/kind bug
```release-note
Upgrade to latest go minor release
```
=> Bump to latest go minor version to fix vulns

make/tools.mk
Go version bump to fix vulns - related to #5559 but adjusted for release-1.9 which used go 1.18
/kind bug
```release-note
Upgrade to latest go minor release
```
=> [release-1.9] Bump to latest go minor version to fix vulns

pkg/issuer/venafi/client/venaficlient.go
When the IIS server that serves the TPP REST API is configured to "Accept" or "Require" client certificates at a particular URL path, it sends TLS 1.2 renegotiate messages to the client.
But by default the Go TLS client rejects any attempt to renegotiate and fails.
This change allows the HTTP client used by the Venafi Issuer code to renegotiate the TLS connection once,
for compatibility with such IIS configurations.
Fixes: #5517
Fixes: #3544
```release-note
Bug fix: The Venafi Issuer can now connect to TPP servers which are configured to allow client certificates. (The Venafi Issuer does not support client certificate authentication however).
```
=> Use RenegotiateOnceAsClient in the Venafi Issuer client and explain why

cmd/controller/app/controller.go, cmd/controller/app/options/options.go, pkg/controller/context.go, pkg/issuer/acme/http/pod.go
Signed-off-by: Corey McGalliard <cmcgalliard@redventures.com>
Hey! we met at kubecon - I chatted about wanting to help contribute to this project because cert-manager been super beneficial for my team!  I grabbed a good-first-issue and here's the PR for Issue #5295 I was able to build and run this locally - but am having issues running the test suite locally. 
feature 
This PR gives us the ability to allow changing acmesolver pod SecurityContext - this will be helpful to use the newer `kubectl debug ... ` commands as well as having the ability to use sidecar pods that run as root.
=> Adding support to elevate acme-solver pod to root during testing

deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/values.yaml
Signed-off-by: lv <yanru.lv@daocloud.io>
/bug
```release-note
Bug fix: When using feature gates with the helm chart, enable feature gate flags on webhook as well as controller
```
fixes: https://github.com/cert-manager/cert-manager/issues/5578
=> fix: featureGates add webhook deployment in chart yaml

internal/vault/fake/client.go, internal/vault/fake/vault.go, internal/vault/vault.go, internal/vault/vault_test.go
This is an alternative approach to https://github.com/cert-manager/cert-manager/pull/5589, written with input from @zscholl  and @inteon . @zscholl 's description applies to this PR so I've copied it: 
> ### Pull Request Motivation
> 
> This change fixes #5563 by changing the vault client logic to instead use the vault client's functions to set the namespace, rather than passing in a new request object with custom headers.
> #### Why is this necessary?
> 
> The behavior of the vault client changed in vault api version `v1.11.0` with [this commit](https://github.com/hashicorp/vault/commit/a442461f81783cd0abec312e910e3a720ab7fd68). The impact of this change means that any headers that are set in the request object passed in to `RawRequest` are wiped out if there are no headers set in the …
=> Set the Vault namespace using vault SDK client methods instead of using raw request object

internal/apis/certmanager/validation/certificate_test.go, make/e2e.sh, pkg/util/pki/parse.go, test/e2e/suite/certificates/literalsubjectrdns.go
* Add OID translation for mandatory DC component
* Used extensively in LDAP certificates, also required by rfc5280
* Add support for UID, mentioned in LDAP RFC
* Fix bug #5582
Signed-off-by: SpectralHiss <houssem.elfekih@jetstack.io>
```release-note
Add support for DC and UID in `LiteralSubject` field, all mandatory OIDs are now supported for LDAP certificates (rfc4514).
```
=> Add support for required LDAP (rfc4514) RDNs in LiteralSubject

make/manifests.mk
This avoids a race condition with the `release-manifests` and `release-manifests-signed` targets.
When running in parallel, one could execute `rm -rf $(BINDIR)/scratch/manifests` while the other was running.
This could also conceivably have led to incorrectly packaged manifests when both were run in parallel.
I confirmed in local testing that this leaves both signed and unsigned bundles unchanged.
/kind bug
```release-note
NONE
```
=> Use distinct manifest dirs for signed / unsigned manifests

pkg/issuer/acme/dns/azuredns/azuredns.go, pkg/issuer/acme/dns/azuredns/azuredns_test.go
This PR brings support for Workload Identity to AzureDNS issuer.
There's another PR #5308, which also introduces support for Workload Identity, though it has two drawbacks:
- It doesn't handle access token renewal:
- A federated token is renewed every hour by default (it's supposed to be re-read from disk), whereas AAD token received in exchange - every 24h.
- `adal` doesn't read federated tokens from disk itself and doesn't expose any methods to dynamically replace `jwt`. Thus, token renewal would fail due to stale federated token;
- It supports only one Client ID:
- As it was explained [in details](https://github.com/cert-manager/cert-manager/pull/5308#discussion_r1007280573) by @pinkfloydx33, Workload Identity supports scenarios where you map multiple MSIs to one service account, so …
=> feat(AzureDNS): Add support for Workload Identity

deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, make/config/projectcontour/gateway.yaml, make/e2e-setup.mk, make/e2e.sh, make/tools.mk, pkg/apis/acme/v1/types_issuer.go, test/e2e/util/util.go
Updates a couple things related to Gateway API tests:
- test setup now downloads and installs a release of [Gateway install bundle](https://gateway-api.sigs.k8s.io/guides/#installing-gateway-api) instead of downloading the whole https://github.com/kubernetes-sigs/gateway-api/ Git repo
- bumps the version of Contour chart and Gateway lib and makes a few small fixes to get it working
- ensures that `Gateway` and `GatewayClass` are created for v1beta1 Gateway API
```release-note
NONE
```
/kind test
=> Updates Gateway API test setup

make/tools.mk
Fixes some [CVEs](https://twitter.com/golang/status/1600212086994370561). See [announcement](https://groups.google.com/g/golang-announce/c/L_3rmdT0BMU).
/kind bug
```release-note
Upgrade to go 1.19.4 to fix CVE-2022-41717
```
=> Bump go to 1.19.4

make/ci.mk
Since verify-licenses relies on third party servers it can flake for reasons unrelated to changes in a PR. [cmrel#111](https://github.com/cert-manager/release/pull/111) adds the ability for tests to be triggered only when a named file changes; this will remove the license check from our default "make test" in favour of the version which will be invoked only when go.mod is updated.
/kind flake
```release-note
NONE
```
=> Remove verify-licenses from ci-presubmit

make/e2e-setup.mk, test/e2e/framework/addon/vault/setup.go, test/e2e/framework/addon/vault/vault.go, test/e2e/suite/conformance/certificatesigningrequests/vault/kubernetes.go, test/e2e/suite/issuers/vault/issuer.go
The main reason for bumping Vault's version is because 1.2.3 is not compatible with the config parameter `disable_iss_validation`, which is needed for accommodating the future tests coming in https://github.com/cert-manager/cert-manager/pull/5502 that rely on bound tokens and static tokens.
For context, Vault 1.2.3 was released on Sep 9, 2019 ([1]) but `disable_iss_validation` was only added on July 21st, 2020 in Vault 1.5.0.
Due to a breaking change that happened in Vault 1.5.0 ([2]) in which Vault started loading the pod's token instead of using the token to be reviewed for authenticating, I had to tweak the end-to-end tests. I renamed `serviceAccountName` and `namespace` to `boundSA` and `boundNS`, since these two variables now refer to the service account of the token to be reviewed, …
=> End-to-end tests: use Vault 1.12.1 instead of the outdated Vault 1.2.3

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/values.yaml
Set the max-concurrent-challenges value with -set maxConcurrentChallenges=value when deploying with helm
Fixes: https://github.com/cert-manager/cert-manager/issues/5627
```release-note
Add the `--max-concurrent-challenges` controller flag to the helm chart
```
=> feat: Add max-concurrent-challenges parameter to helm

hack/latest-kind-images.sh, make/cluster.sh, make/e2e-setup.mk, make/kind_images.sh
Adds k8s 1.26 kind images, and uses that version by default on master.
A followup, separate PR will add k8s 1.26 images for the release-1.10 branch
This was blocked behind https://github.com/cert-manager/release/pull/113 which enabled us to manually run the 1.26 e2e test on this PR.
/kind feature
```release-note
Enable testing against Kubernetes 1.26 and test with Kubernetes 1.26 by default
```
=> Enable + use k8s 1.26 for e2e tests by default

SECURITY.md
We've received several emails to our security mailing list which simply paste vuln reports from tools with no useful context.
In every case I've seen, every reported "vulnerability" has been a false positive which was trivial to verify.
In the worst cases, these reports link to proprietary vuln identifiers which we can't even verify, which I personally believe to be absolutely atrocious and a concerning development for the entire security industry.
This PR updates the security policy to make it clear that such reports aren't helpful (at least without further context or investigation).
Part of the idea here is to give us a section to link to when we receive such reports in the future.
```release-note
NONE
```
=> Update SECURITY policy to exclude vuln reports

LICENSES, go.mod, go.sum
Fixes a vuln (CVE-2022-41717) reported by trivy
/kind bug
```release-note
Upgrade golang.org/x/net to 0.4.0 to fix CVE-2022-41717
```
=> Bump golang.org/x/net version to fix trivy vulns

make/e2e-setup.mk
This matches the version used on the master branch at the time of this commit. This version was chosen because it was tested on master. It implies a bump of the underlying version of contour from 1.20 -> 1.23, but it seems better to use a tested version of the chart rather than a previously untested version.
This update is required because the previous version was removed from the bitnami helm chart repo. That has broken our periodics for the release-1.10 branch.
/kind bug
```release-note
NONE
```
=> Bump contour

make/e2e-setup.mk
Also adds a note about how to update the helm chart version, in the future
See also [slack conversation](https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1671538282648159)
/kind cleanup
```release-note
NONE
```
=> Bump version of contour helm chart + images

Makefile, make/ko.mk, make/tools.mk
This allows me to quickly compile the code in my working directory and deploy it on any Kubernetes cluster.
On Google GKE or Azure AKS for example. 
I used it to manually test Azure specific features in the absence of any automated E2E tests on Azure.
I have used `ko` to build the images because I it uses the local go cache which allows to to very quickly create updated Docker images.
And it makes it quick and easy to compile multi-arch images, which will allow people to compile and deploy to arm Kubernetes clusters. 
The existing `e2e- setup-certmanager` target compiles linux/amd64 images only (AFAICS).
Ultimately I hope that cert-manager might switch to `ko` for building the release images, which would allow us to remove a lot of the complex build code dedicated to creating our …
=> Experimental make targets for pushing images to a Docker registry and redeploying cert-manager

deploy/charts/cert-manager/Chart.template.yaml
This reflects the latest supported releases as of an update on 2022-12-16
See https://github.com/cert-manager/website/pull/1131
/kind cleanup
```release-note
NONE
```
=> Bump supported versions of k8s mentioned in the helm chart

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/values.yaml, make/e2e-setup.mk
When deploying cert-manager using the Helm chart, overriding ACME HTTP-01 thanks to the extraArgs value doesn’t allow to only set the repository only without the tag (so that the default tag is used). This PR tries to address this issue.
feature
```release-note
Helm: allow configuring the image used by ACME HTTP-01 solver
```
=> helm: add option to override ACME HTTP-01 solver image

LICENSES, go.mod, go.sum
cert-manager was not able to retry some failed TPP certificates due to the fact that TPP does not automatically restarts the enrollment from 0 when the certificate already has a failed enrollment status from a previous enrollment.
More specifically, cert-manager was getting stuck on either:
WebSDK CertRequest Module Requested Certificate
or
This certificate cannot be processed while it is in an error state.
Fix any errors, and then click Retry.
With vcert v4.23.0, a call to "reset" is made when one of these two messages are found while polling for the certificate (i.e., while calling vcert's RetrieveCertificate function).
```release-note
A bug that was preventing the Venafi issuer from renewing certificates when using TPP has been fixed. You should no longer see your certificates getting …
```
=> vcert: upgrade to v4.23.0 to fix certificate renewal stuck on TPP errors ("Click Retry" and "WebSDK CertRequest")

hack/check-crds.sh
Due to [a bug in controller-gen][bug] certain paths are incorrectly split and part of these paths can be interpreted as a numeric literal, which will cause controller-gen to fail. We observe this as occasional test flakes in the "verify-crds" target, when the tmpdir starts with a zero, such as in `/tmp/tmp.0PFqFSHBID`
This commit attempts to avoid this bug by specifying a template for the tmpdir we generate when verifying CRDs which doesn't include any "." characters, which seem to be being split incorrectly.
[bug]: https://github.com/kubernetes-sigs/controller-tools/issues/734
/kind bug
```release-note
Use manually specified tmpdir template when verifying CRDs
```
=> Use template when generating tempdir in verify-crds

make/config/lib.sh, make/e2e-ci.sh, make/e2e.sh
1. Remove deprecated args (progress, slow spec threshold)
2. Disable colors in CI
Deprecation notice given by Ginkgo on current tests is below:
```text
You're using deprecated Ginkgo functionality:
=============================================
--slow-spec-threshold is deprecated --slow-spec-threshold has been deprecated and will be removed in a future version of Ginkgo. 
This feature has proved to be more noisy than useful. 
You can use --poll-progress-after, instead, to get more actionable feedback about potentially slow specs and understand where they might be getting stuck.
--progress is deprecated . 
The functionality provided by --progress was confusing and is no longer needed.
Use --show-node-events instead to see node entry and exit events included in the timeline of failed and …
```
=> Various ginkgo tweaks

make/ko.mk
This is a fix for an oversight  in #5655  where I renamed one of the targets in response to a [code review comment](https://github.com/cert-manager/cert-manager/pull/5655#discussion_r1054119875), but forgot to also update the `.PHONY` line above.
```release-note
NONE
```
/kind cleanup
=> Remove duplicate ko-deploy-cert-manager make target

make/ko.mk
I wanted a way to quickly compile and deploy cert-manager with the following custom helm chart values
```yaml
serviceAccount:
labels:
azure.workload.identity/use: "true"
```
<details>
<summary>`make ko-deploy-certmanager KO_HELM_VALUES_FILES=values.yaml`</summary>
```bash
$ make ko-deploy-certmanager KO_HELM_VALUES_FILES=values.yaml
cd _bin/tools/ && ln -f -s ../downloaded/tools/yq@v4.27.5_linux_amd64 yq
cd _bin/tools/ && ln -f -s ../downloaded/tools/helm@v3.10.0_linux_amd64 helm
/home/richard/projects/cert-manager/cert-manager/_bin/tools/ko build ./cmd/controller \
--bare \
--sbom=none \
--platform=linux/amd64 \
--tags=v1.11.0-alpha.2-10-g33ba0f3ae7508f \
| /home/richard/projects/cert-manager/cert-manager/_bin/tools/yq 'capture("(?P<ref>(?P<repository>[^:]+):(?P<tag>[^@]+)@(?P<digest>.*)) …
```
=> Allow custom helm values files to be supplied to make ko-deploy-certmanager

pkg/controller/certificaterequests/selfsigned/checks.go, pkg/controller/certificaterequests/selfsigned/checks_test.go
See https://github.com/cert-manager/cert-manager/issues/5601 for details.
When referring to external issuers whose kind is not "Issuer" or "ClusterIssuer" we log an error message thanks to a new check added in a [previous PR](https://github.com/cert-manager/cert-manager/pull/5336) which should only trigger for SelfSigned issuers.
The error previously looked like:
```text
"error"="invalid value \"x\" for issuerRef.kind. Must
be empty, \"Issuer\" or \"ClusterIssuer\""
```
/kind bug
```release-note
Don't log errors relating to selfsigned issuer checks for external issuers
```
=> Avoid logging confusing error messages for external issuers

pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/rfc2136/provider.go, test/acme/dns/fixture.go, test/acme/dns/options.go, test/integration/rfc2136_dns01/provider_test.go
Fixes #5689 
See #5689 for context.
Cert-manager controller was starting two `Secret`s watches resulting in all `Secret`s being cached twice.
This PR removes the redundant informer factory that was being started in the rfc2136 DNS solver and instead passes a secrets lister from the default informer factory to the solver.
Comparison of memory consumption improvement
Create 300 `Secret`s about 1Mb each:
Memory spikes up to 900Mb, then stabilizes around 700Mb:
Create 300 `Secret`s about 1Mb each:
Memory spikes up to 450Mb, then stabilizes around 300Mb:
To observe that only one watch is started:
Start cert-manager controller with `--v=5` flag
Look at the logs and observe that `Secret`s watch is started only once:
```
I0105 10:15:42.906265       1 reflector.go:221] Starting reflector …
```
=> Ensures that only one secrets cache is created for cert-manager controller

cmd/cainjector/app/start.go, pkg/controller/cainjector/controller.go, pkg/controller/cainjector/setup.go, pkg/controller/cainjector/sources.go
Ensures that when cainjector has the namespace flag passed, namespaced resource caching is scoped to that namespace
```release-note
Fix cainjector's --namespace flag. Users who want to prevent cainjector from reading all `Secret`s and `Certificate`s in all namespaces (i.e to prevent excessive memory consumption) can now scope it to a single namespace using the --namespace flag. A cainjector that is only used as part of cert-manager installation only needs access to the cert-manager installation namespace.
```
/kind bug
=> Fix cainjector's namespace flag

deploy/charts/cert-manager/templates/deployment.yaml
Since the acmesolver image has defaults (i.e. the repository is set by [default][values]), the helm chart changes introduced in #5554 will always set the `--acme-http01-solver-image` parameter.
This can break users who previously had this parameter set via the extraArgs Helm option, which was found and reported on [Slack][slack].
This commit moves the new Helm value added in #5554 above extraArgs, so that if extraArgs is set it will take precedence and nothing should change as users upgrade.
[values]: https://github.com/cert-manager/cert-manager/blob/a5d67d3a21f86fb21b8194808601da429a1c4752/deploy/charts/cert-manager/values.yaml#L504-L516
[slack]: https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1672925692339849
/kind bug
```release-note
Ensure extraArgs in Helm takes precedence over the …
```
=> Move custom acmesolver image above extraArgs

internal/controller/certificates/policies/checks.go, internal/controller/certificates/policies/constants.go, internal/controller/certificates/policies/policies.go, pkg/apis/certmanager/v1/types.go, pkg/controller/certificates/issuing/internal/secret.go, pkg/controller/certificates/issuing/internal/secret_test.go, pkg/controller/certificates/issuing/secret_manager_test.go, pkg/controller/certificates/keymanager/keymanager_controller.go, pkg/controller/certificates/keymanager/keymanager_controller_test.go
See #5639 for context.
In order to make it possible to filter `Secret` resources that cert-manager is interested in, for example to filter which `Secret`s are cached, it would be great if cert-manager would label those `Secret` resources. Adding the labels now would make it easier for us to implement caching improvements that use the new labels in a future release as at a point when users upgrade to a version of cert-manager with caching improvements their resources should already be labelled (assuming that they upgrade one minor release at a time as per our recommendation).
This PR:
- adds a new `controller.cert-manager.io/fao` label to cert-manager API
- ensures that all `Secret`s referenced in `certificate.spec.secretName` as well as temporary private key `Secret`s created during …
=> Ensures that certificate.spec.secretName and temporary private key Secrets are labelled

pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/rfc2136/provider.go, test/acme/dns/fixture.go, test/acme/dns/options.go, test/integration/rfc2136_dns01/provider_test.go
Implements @irbekrm 's  #5691 as a backport for release-1.10
Related to #5689
/kind bug
```release-note
Fixes a bug where the cert-manager controller was caching all Secrets twice
```
=> [release-1.10] Remove redundant secret cache

make/tools.mk
Signed-off-by: yanggang <gang.yang@daocloud.io>
[release go1.19.5)](https://golang.google.cn/doc/devel/release#go1.19)
```
go1.19.5 (released 2023-01-10) includes fixes to the compiler, the linker, and the crypto/x509, net/http, sync/atomic, and syscall packages. See the [Go 1.19.5 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.19.5+label%3ACherryPickApproved) on our issue tracker for details.
```
```release-note
Upgrade to go 1.19.5
```
=> Bump go to 1.19.5

cmd/ctl/pkg/install/install.go
See #5720 - this backports the fix for helm version check.
A backport for 1.10 isn't needed since the [`kubeVersion` for 1.10](https://github.com/cert-manager/cert-manager/blob/6bf1457f6de0fc9e029818d580d9fedf1065bb9c/deploy/charts/cert-manager/Chart.template.yaml#L6) includes k8s 1.20.
/kind bug
```release-note
Use a fake kube apiserver version when generating helm template in `cmctl x install`, to work around a hardcoded Kubernetes version in Helm.
```
=> [release-1.11] Fix helm version check

LICENSES, go.mod, go.sum
This version points to the same commit as v4.4.0, so there is no actual code change. However, trying to build cert-manager with v4.4.0 errors out due to a checksum mismatch. Bumping to the new tag solved the issue.
Pavlo was kind enough to cut a new tag: https://github.com/pavlo-v-chernykh/keystore-go/issues/41
If this gets approved, could it be backported to 0.11 and 0.10? Thanks!
/kind cleanup
```release-note
Bump keystore-go to v4.4.1 to work around an upstream rewrite of history
```
=> Bump keystore-go to v4.4.1

LICENSES, go.mod, go.sum
This version points to the same commit as v4.4.0, so there is no actual code change. However, trying to build cert-manager with v4.4.0 errors out due to a checksum mismatch. Bumping to the new tag solved the issue.
This commit was manually cherry-picked from the original to fix a merge conflict. The original commit SHA was:
`7528760e6548abc278e735fa021fddaf44eea0f4`
The original PR was #5724
/kind cleanup
```release-note
Bump keystore-go to v4.4.1 to work around an upstream rewrite of history
```
=> [release-1.10] Bump keystore-go to v4.4.1

hack/containers/Containerfile.acmesolver, hack/containers/Containerfile.cainjector, hack/containers/Containerfile.controller, hack/containers/Containerfile.ctl, hack/containers/Containerfile.webhook
I'd like to take advantage of renovate's changelog support (https://docs.renovatebot.com/modules/datasource/docker/)
To do so, the recommended way is to add the standard OCI label `org.opencontainers.image.source`.
This is useful for all sorts of tools.
A full list of pre-defined annotations is available at: https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
feature
```release-note
container images are have an OCI source label
```
=> Add org.opencontainers.image.source OCI label to containers

pkg/acme/webhook/apiserver/apiserver.go, pkg/acme/webhook/cmd/cmd.go, pkg/acme/webhook/cmd/server/start.go, pkg/acme/webhook/webhook.go, pkg/issuer/acme/dns/rfc2136/provider.go, test/acme/dns/fixture.go, test/acme/dns/options.go, test/integration/rfc2136_dns01/provider_test.go
Fixes #5725 
This PR fixes DNS webhook solver conformance test bug introduced in #5691 - in that PR I changed a webhook Solver interface implentation for RFC2136 to not start a Secrets informer factory and made some associated changes to integration tests which are a bit clunky for this particular Solver implementation.
The tests are being used as conformance tests by external webhook implementations and the changes broke their tests.
This PR:
- reverts changes to tests that would affect third party solver implementations using them
- makes some changes to the RFC2136 Solver implementation to make it work in the integration test setup (which does not generally match how it would normally run, but I think this is acceptable)
- adds a bunch of comments to make it clearer which parts of the …
=> Webhook solver conformance bugfix

deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/startupapicheck-job.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/templates/webhook-psp-clusterrole.yaml, deploy/charts/cert-manager/values.yaml
We needed to be able to setup an explicit volume and volumeMount for the service accounts, this PR enables setting both as an array, mirroring the functionality already in place for the controller deployment
feature
```release-note
Added the ability to set volumes and volumeMounts via helm variables for cainjector, webhook, and startupapicheck
```
=> Added the ability to set volumes and volumeMounts to all pods  via helm

cmd/ctl/pkg/create/certificatesigningrequest/certificatesigningrequest.go, internal/apis/certmanager/validation/certificate.go, internal/controller/certificates/policies/checks.go, internal/controller/certificates/policies/checks_test.go, pkg/controller/certificates/issuing/issuing_controller.go, pkg/controller/certificates/keymanager/keymanager_controller.go, pkg/controller/certificates/readiness/readiness_controller.go, pkg/controller/certificates/readiness/readiness_controller_test.go, pkg/controller/certificates/requestmanager/requestmanager_controller.go, pkg/controller/certificates/trigger/trigger_controller.go, pkg/controller/certificates/util.go, pkg/util/pki/basicconstraints.go, pkg/util/pki/csr.go, pkg/util/pki/csr_test.go, pkg/util/pki/generate.go, pkg/util/pki/keyusage.go, pkg/util/pki/match.go, pkg/util/pki/match_test.go, pkg/util/pki/parse.go, pkg/util/pki/parse_test.go, pkg/util/pki/renewaltime.go, pkg/util/pki/renewaltime_test.go, pkg/util/pki/subject.go, pkg/util/pki/temporarycertificate.go, test/e2e/framework/helper/certificaterequests.go, test/e2e/suite/conformance/certificates/tests.go, test/integration/certificates/generates_new_private_key_per_request_test.go, test/unit/crypto/crypto.go
The PR tries to achieve the following goals:
1. move utility functions to reduce fragmentation
moved from `pkg/controller/certificates/util.go` to `pkg/util/pki`
2. rename functions for consistency
Since I didn't remove any functionality, projects that import cert-manager should be able to easily upgrade (possibly after changing import paths/ renaming functions).
```release-note
NONE
```
=> Move and rename Certificate util functions

pkg/issuer/acme/http/pod.go
This reverts commit 954eb0d875cb79d6da8eca233ccc9267ebf1420c.
I accidentally pushed that commit to master while setting up visual studio code on a new laptop.
Apologies everyone. 
I will also look into automatically applying the necessary branch protection in the github.com/jetstack/testing repo.
```release-note
NONE
```
=> Revert "automount service account tokens off by default"

pkg/controller/cainjector/controller.go, pkg/controller/cainjector/indexers.go, pkg/controller/cainjector/setup.go, pkg/controller/cainjector/sources.go
Cainjector can inject CA data to 'injectables' that can be CRDs, Validating/MutatingWebhookConfigurations or APIServices.
Users specify the source of CA via an annotation on the injectable-
- `cert-manager.io/inject-apiserver-ca` to inject CA from kubeconfig
- `cert-manager.io/inject-ca-from-secret` to inject CA from a Secret
- `cert-manager.io/inject-ca-from` to inject CA from a cert-manager Certificate's Secret
At the moment cainjector lists and watches all resources of injectable types and trigger reconciles on all associated events. Unfortunately there is no way how to filter List/Watch on annotation and we cannot change this to labels as this would constitute a breaking change.
This PR ensures that reconciles are only triggered on events against annotated objects of injectable types. …
=> Cainjector: only reconcile annotated injectables

make/tools.mk
As mentioned in https://github.com/cert-manager/cert-manager/pull/5711#issuecomment-1416193485, the kubebuilder tarball for linux/amd64 seems to have been changed.
Because of it, the periodic job [ci-cert-manager-master-make-test](https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/logs/ci-cert-manager-master-make-test/1622544090765725696) has been failing since Feb 03 01:31:58
To check that this fix works, run the following:
```bash
rm -f _bin/downloaded/tools/kubebuilder_tools_1.26.0_linux_amd64.tar.gz
make _bin/downloaded/tools/kube-apiserver@1.26.0_linux_amd64 HOST_ARCH=amd64 HOST_OS=linux
```
/kind cleanup
```release-note
NONE
```
NOTE: I don't think this fix needs to be backported since the `make test` command is only run in our master periodics and our PR jobs, but not in …
=> make: the kubebuilder 1.26.0 hash for linux/amd64 changed

pkg/issuer/vault/setup_test.go
As part of #5502, I wish to prevent any possible breakage due to a possibly stricter validation.
I wish to avoid people upgrading to cert-manager 1.12 and see that their Vault issuers stop working.
For context, we have two types of validation for Vault (we also have this in all the other controllers):
- The controller-side validation, which happens in the `Setup` func. The controller-side validation happens every time a resync of an Issuer happens.
- The webhook-side validation, which happens somewhere else.
These unit test are meant to test the controller-side validation.
/kind cleanup
```release-note
NONE
```
=> Vault: add unit tests for the controller-side validation of the Vault Issuer

deploy/charts/cert-manager/values.yaml
Rel: #5787
This PR add 6443/tcp to the egress rules of the webhook network policy.
bug
```release-note
Add 6443/TCP to webhook egress rules
```
=> Add 6443/TCP to webhook egress NetworkPolicy

deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, internal/apis/acme/types_issuer.go, internal/apis/acme/v1/zz_generated.conversion.go, internal/apis/acme/v1alpha2/types_issuer.go, internal/apis/acme/v1alpha2/zz_generated.conversion.go, internal/apis/acme/v1alpha2/zz_generated.deepcopy.go, internal/apis/acme/v1alpha3/types_issuer.go, internal/apis/acme/v1alpha3/zz_generated.conversion.go, internal/apis/acme/v1alpha3/zz_generated.deepcopy.go, internal/apis/acme/v1beta1/types_issuer.go, internal/apis/acme/v1beta1/zz_generated.conversion.go, internal/apis/acme/v1beta1/zz_generated.deepcopy.go, internal/apis/acme/zz_generated.deepcopy.go, pkg/apis/acme/v1/types_issuer.go, pkg/apis/acme/v1/zz_generated.deepcopy.go, pkg/issuer/acme/http/pod.go, pkg/issuer/acme/http/pod_test.go
We are able to specify service account name in acme http solver pod spec to pull solver image from private repo but there are use cases when users managing cert-manager don't have access to create service accounts in other namespaces where solver pod is running. This PR allows to specify `imagePullSecrets` in solver pod spec.
Related to #3853, #3817, #3913
feature
```release-note
Adds `acme.solvers.http01.ingress.podTemplate.spec.imagePullSecrets` field to issuer spec to allow to specify image pull secrets for the ACME HTTP01 solver pod.
```
=> Add imagePullSecrets for AMCE http01 solver pod

test/e2e/framework/addon/chart/addon.go
Same as https://github.com/cert-manager/cert-manager/pull/5795, but for the branch release-1.10.
/kind flake
```release-note
NONE
```
=> [release-1.10] e2e flakiness: vault addon incorrectly using StdoutPipe

test/e2e/framework/addon/chart/addon.go
I'd like to backport the commit https://github.com/cert-manager/cert-manager/pull/5502/commits/ba0bb5d5030a06a00f38779fbc9feb609c41dfee that was merged to master. This commit fixes a flake that appears quite often. 
Example: https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/logs/ci-cert-manager-release-1.11-e2e-v1-21/1623293794206093312
<details>
<summary>Links to the test failures, including the retried ones</summary>
- https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/logs/ci-cert-manager-master-e2e-v1-22-feature-gates-disabled/1605910679389212672
- https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/logs/ci-cert-manager-master-e2e-v1-22-feature-gates-disabled/1611711112418430976
- https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/logs/ci-cert-manage …
=> [release-1.11] e2e flakiness: vault addon incorrectly using StdoutPipe

make/tools.mk
On linux/arm64 `uname -m` [gives](https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1676652687723599?thread_ts=1676643017.223269&cid=CDEQJ0Q8M) `aarch64`, not `arm64`.
We don't have many people doing development on linux/arm64 so this wasn't spotted, because in macOS `uname -m` gives `arm64`.
/kind bug
```release-note
Fix development environment and go vendoring on Linux ARM64.
```
=> Handle uname on linux/arm64

LICENSES, go.mod, go.sum
In case we send a new valid CSR to TPP after a TPP error occurred, we get the following error message: `This certificate cannot be processed while it is in an error state. Fix any errors, and then click Retry.`
In https://github.com/cert-manager/cert-manager/pull/5674 we introduced the https://github.com/Venafi/vcert/pull/269 fix for this issue. However, we found out that this fix does often fail due in a race condition (see https://github.com/jetstack/vcert/pull/3). The race condition causes the requested CSR to get lost when calling reset too soon after requesting, resulting in the old Certificate being returned instead in a non-failure mode.
In order to fix the original issue, without having a race condition, we created https://github.com/jetstack/vcert/pull/3 which unconditionally …
=> Use jetstack vcert fork to properly reset on TPP error

LICENSES, go.mod, go.sum
/kind bug
```release-note
The auto-retry mechanism added in VCert 4.23.0 and part of cert-manager 1.11.0 (#5674) has been found to be faulty. Until this issue is fixed upstream, we now use a patched version of VCert. This patch will slowdown the issuance of certificates by 9% in case of heavy load on TPP. We aim to release at an ulterior date a patch release of cert-manager to fix this slowdown.
```
=> [release-1.11] use jetstack vcert fork to properly reset on error for TPP

make/e2e-setup.mk, make/tools.mk
Signed-off-by: yulng <wei.yang@daocloud.io>
https://github.com/kubernetes-sigs/gateway-api/releases
Upgrade gateway-api version to 0.6.0
```release-note
Upgraded Gateway API to v0.6.0.
```
=> Bump gateway-api version to 0.6.0

pkg/issuer/acme/dns/digitalocean/digitalocean.go, pkg/issuer/acme/dns/digitalocean/digitalocean_test.go, pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/util_test.go
This PR sets a custom user agent string when initializing the godo client for the DigitalOcean issuer. It's a general best practice for clients to identify themselves. As one of the maintainers of godo, it helps us to better understand how it is being used. It should help enable DigitalOcean to better support their customers using cert-manager.
```release-note
The DigitalOcean issuer now sets a cert-manager user agent string.
```
=> digitalocean: Pass user agent string to godo client.

deploy/manifests/README.md
Clean up obsolete documentation. Bazel is no longer used.
cleanup
```release-note
NONE
```
=> Remove obsolete bazel documentation

design/20190708.certificate-request-crd.md, pkg/controller/certificaterequests/sync.go, pkg/controller/certificaterequests/sync_test.go, pkg/controller/certificates/issuing/issuing_controller.go, pkg/controller/certificates/issuing/issuing_controller_test.go
Fixes #5847 
See #5847 for context - this PR fixes a race condition where issuance that results in denied CRs would sometimes result in failed and retried issuances and sometimes be 'stuck'
This PR:
- makes all Denied CRs fail issuance and be retried with exponential backoff
- makes all Invalid CRs fail issuance and be retried with exponential backoff
In case of denied CRs it could be considered a breaking change, however due to the race condition it seems to have already been the case (at least in all my local testing)
In case of invalid CRs, I am not aware of any issuers that set this CR condition, however the commit description appears to suggest that the intention that this condition should result in failed and retried issuance …
=> Fixes a race condition in retrying denied/invalid issuances

cmd/ctl/pkg/renew/renew.go, cmd/ctl/pkg/renew/renew_test.go
The aim of this PR is to fix the bug reported [here](https://github.com/cert-manager/cert-manager/issues/5886). Currently, there is no validation for the scenario where the namespace is informed without a certificate list. Therefore, this PR adds a validation for this scenario:
- Error:
`cmctl renew -n application-team-1 -> Error`
- Ok
`cmctl renew -n application-team-1 service-1 -> ok`
```release-note
cmctl renew now prints an error message unless Certificate name(s) or --all are supplied
```
Fixes: https://github.com/cert-manager/cert-manager/issues/5886
=> Error if the resource name is omitted, unless --all is also used.

LICENSES, go.mod
This should have been removed in https://github.com/cert-manager/cert-manager/pull/4958 however looks like I forgot to do that
It was added in https://github.com/cert-manager/cert-manager/pull/4942/commits/587e02cee9fba54b1b7580e06ee2b8351072842f to keep supporting HMACMD5 algorithm for RFC2136 DNS solver's [TSIG algorithm](https://cert-manager.io/docs/configuration/acme/dns01/rfc2136/#transaction-signatures--tsig) - to avoid a breaking change. In #4958 we implemented a shim over the upstream `TSIGProvider` interface so now we can use the latest version of that module without breaking anyone.
```release-note
NONE
```
/kind cleanup
=> Removes leftover replace statement

test/integration/ctl/migrate/ctl_upgrade_migrate_test.go
The issue #5899 reports a flaky test. I investigated a bit and it looks like we could lower the number of false-positives by slightly adjusting the timeout period.
Below are a few builds in which the test timed out.
Test `TestCtlUpgradeMigrate`:
| Build                                                                                                                                                                                                                 | Time   |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------ |
| [5248/pull-cert-manager-make-test](https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/pr- …
=> Migrate tests: higher timeout to lower the number of false-positives

make/git.mk, make/test.mk
Currently on master, upstream-tags.txt will use whatever ordering git uses by default, which at least on my system is lexicographic and not version aware. There's a `git ls-remote` argument to sort by version, which is what we actually want.
I'd seen this weirdness for a while and I finally dug into it.
I also added a version to upstream-tags so we can force a new invocation of `git ls-remote` on every checkout when we make a change like this. I can't imagine we'll have to change this file often but it seems good to force a new version this time.
The `--sort` flag is available at least as far back as [April 2019](https://git-scm.com/docs/git-ls-remote/2.24.0) (and probably older but I don't see a reason to dig any deeper).
`upstream-tags.txt`:
```text
v1.0.0
v1.0.0-alpha.0
v1.0.0-alpha.1 …
```
=> Fix upstream-tags sort order

design/20230302.gomod.md
Adds a design document for `go.mod` proliferation to help with longer-term maintenance tasks. A decent chunk of the code for this is already written  (albeit needing polish) - this PR and design doc is to seek consensus and look to how we might merge.
/kind design
```release-note
NONE
```
=> Design: Go Module Proliferation

deploy/crds/crd-certificates.yaml, pkg/apis/certmanager/v1/types_certificate.go
Updates `cert.status.lastFailureTime` description as it was out of date in regards to changes made in #4772 
```release-note
NONE
```
/kind cleanup
=> Updates cert.status.lastFailureTime description

pkg/acme/client/interfaces.go, pkg/controller/acmeorders/sync.go, pkg/controller/acmeorders/sync_test.go, pkg/controller/acmeorders/util.go, pkg/controller/acmeorders/util_test.go, test/unit/gen/challenge.go
This PR reduces the amount of calls made to ACME server during issuance.
**Problem**:
See #5867 for context.
Currently we have some redundant calls made to ACME server during issuance:
- orders controller retrieves the key for an HTTP-01/DNS-01 challenge (`HTTP01ChallengeResponse`/`DNS01ChallengeResponse` ACME call) every time when it calculates what Challenge resources should be created although in most cases it only needs the names of the Challenges [here](https://github.com/cert-manager/cert-manager/blob/v1.11.0/pkg/controller/acmeorders/sync.go#L124)
- orders controller in some cases GETs the ACME order (`GetOrder` ACME call) when it's actually not needed [here](https://github.com/cert-manager/cert-manager/blob/v1.11.0/pkg/controller/acmeorders/sync.go#L168)
**Changes in this PR**:
- …
=> Reduce the amount of ACME calls during issuance

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/_helpers.tpl, deploy/charts/cert-manager/templates/cainjector-poddisruptionbudget.yaml, deploy/charts/cert-manager/templates/poddisruptionbudget.yaml, deploy/charts/cert-manager/templates/webhook-poddisruptionbudget.yaml, deploy/charts/cert-manager/values.yaml
Added PodDisruptionBudgets to helm chart. It is configurable via the values.yaml.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3898
```release-note
Added PodDisruptionBudgets for cert-manager components to the Helm chart (disabled by default).
```
=> Added PodDisruptionBudgets to helm chart

make/ci.mk
The make target now removes all the LICENSES files before generating them, ensuring us they are all regenerated
In https://github.com/cert-manager/cert-manager/pull/5880, we made some major changes to our go.mod setup. We also changed the LICENSES generation logic. The `update-licenses` is causing problems now however, because it does not always update all the LICENSES files. The verify-licenses returns an error in CI, but the `update-licenses` target does not fix the issue as would be expected.
see https://github.com/cert-manager/cert-manager/pull/5931 and https://github.com/cert-manager/cert-manager/pull/5828 as examples of the target not working.
/kind bug
```release-note
NONE
```
=> Fix update-licenses make target

make/e2e-setup.mk, make/e2e.sh, make/test.mk, test/e2e/framework/addon/base/base.go, test/e2e/framework/framework.go, test/e2e/suite/certificaterequests/approval/approval.go, test/e2e/suite/certificaterequests/approval/userinfo.go
Reduces the e2e test duration from 30min to 16min.
```release-note
NONE
```
/kind cleanup
=> Use high QPS, Burst, ConcurrentWorkers, ginkgo nodes values for faster e2e tests

gcb/build_cert_manager.yaml
This PR, along with a GCB trigger to be configured later, should enable the automatic build of cert-manager releases by simply pushing tags. This should in turn remove a step from the release process, enabling easier maintenance (and hopefully, easier LTS support)
/kind feature
```release-note
NONE
```
=> Add GCB configuration file for building cert-manager on tag push

.gitignore, gcb/build_cert_manager.yaml
https://github.com/cert-manager/cert-manager/pull/5940 backported to release-1.10 as discussed.
Also includes a QoL gitignore fix when switching between branches with workspaces on.
NOTE: This PR also implies a change in the build image used for releases of 1.10. We originally used [this image](https://github.com/cert-manager/release/blob/c35ba39e591f1e5150525ca0fef222beb719de8c/gcb/makestage/cloudbuild.yaml#L16) and we change it here.
This is intentional. eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220629-ee75d11-4.2.1 has many vulnerabilities including critical severity vulns. Someone attacking the release process using those vulns doesn't seem particularly likely, but it does seem worth updating here. Since make-dind is much more slim than bazelbuild, it seems worth using that …
=> [release-1.10] Autobuild on tag push

test/e2e/framework/addon/vault/proxy.go, test/e2e/framework/addon/vault/setup.go, test/e2e/framework/addon/vault/vault.go, test/e2e/suite/conformance/certificatesigningrequests/vault/kubernetes.go, test/e2e/suite/issuers/vault/issuer.go, test/unit/gen/issuer.go
- inlined some functions that were used only once
- fixed some linting errors (eg. error messages should start with lowercase letter)
- I tried to make the vault test code a bit more understandable by not re-using role names as the name of the SA, secret, ...
/kind cleanup
```release-note
NONE
```
=> Vault test code cleanliness improvements

pkg/acme/accounts/registry.go, pkg/acme/accounts/registry_test.go, pkg/acme/accounts/test/registry.go, pkg/issuer/acme/setup.go, pkg/issuer/acme/setup_test.go
Fixes bug #5948 related to status change on privateKey update on acme issuer.
/kind bug
```release-note
ACME account registration is now re-verified if account key is manually changed.
```
=> Fixes status change on privateKey update on acme issuer

make/tools.mk
[ko v0.13.0 has many fixes](https://github.com/ko-build/ko/releases/tag/v0.13.0), including one for publishing the images to your local Docker daemon.
This now works properly:
```
make ko-images-push KO_REGISTRY=ko.local
```
```
$ docker images | egrep 'ko.local/cert-manager-(ctl|webhook|acmesolver|cainjector)\s+v'
ko.local/cert-manager-acmesolver                         v1.12.0-alpha.2-63-gece30e655f2c1d
2f41e9250269   16 hours ago    40.8MB
ko.local/cert-manager-cainjector                         v1.12.0-alpha.2-63-gece30e655f2c1d
2b1c44d24c98   16 hours ago    55.8MB
ko.local/cert-manager-webhook                            v1.12.0-alpha.2-63-gece30e655f2c1d
0991f36d7f25   16 hours ago    66.7MB
ko.local/cert-manager-ctl                                v1.12.0-alpha.2-63-gece30e655f2c1d …
```
=> Upgrade to ko 0.13

make/e2e-setup.mk
I created a multi-arch Docker image and a new alpha release in:
* https://github.com/cert-manager/sample-external-issuer/pull/39
Testing it out in this PR as follows:
```
$ make e2e-setup-certmanager e2e-setup-sampleexternalissuer
...
$ make e2e GINKGO_FOCUS='.*External (Cluster)?Issuer.*'
...
Ran 36 of 839 Specs in 23.921 seconds
SUCCESS! -- 36 Passed | 0 Failed | 0 Pending | 803 Skipped
--- PASS: TestE2E (23.96s)
PASS
Ginkgo ran 1 suite in 26.501944379s
Test Suite Passed
```
```release-note
NONE
```
=> Upgrade to sample-external-issuer v0.3.0

internal/informers/core_filteredsecrets.go, internal/informers/transfomers.go
This PR uses [client-go transform functions mechanism](https://github.com/cert-manager/cert-manager/blob/master/design/20221205-memory-management.md#transform-functions) to clean up labels, annotations and managed fields from partial metadata `Secret`s. This is okay as partial metadata `Secret`s are only cached to pre-determine if a `Secret` identified by name and namespace exists.
When we start using server-side apply in GA, we should also be able to remove the last applied annotation from cached typed `Secret`s without risking to delete it from the cluster object when cert-manager re-applies the `Secret` (i.e a `Certificate` `Secret` that was originally applied by user)
A rough measurement of performance changes in a cluster with 200 cert-manager unrelated `Secret`s and …
=> Clean up cached Secret resources

make/licenses.mk, make/tools.mk
Without a go.work file, `go-licenses` is unable to discover the LICENSE file and dependencies of github.com/cert-manager/cert-manager when it is pointed at `./cmd/controller`, for example.
It does not follow the replace statements in the `go.mod` file of each of the binaries.
Adding a `go.work` file allows it to work,  and presumably a `go.work` file was present when the current LICENSES files were generated and committed to the repository...or they were generated and committed before the introduction of the per-binary go.mod files.
~~The `make verify-licenses` target has been succeeding in CI thus far because the `_bin/scratch/LATEST-LICENSES*` files -- against which it compares the checked in LICENSES files -- are also cached in CI and are only updated when the respective `go.mod` or …
=> Use a temporary go.work file when running go-licenses

cmd/acmesolver/go.mod, cmd/cainjector/go.mod, cmd/controller/go.mod, cmd/ctl/go.mod, cmd/webhook/go.mod, go.mod, make/tools.mk, test/e2e/go.mod, test/integration/go.mod
Upgrading to Go 1.20 as a way of testing #5968 which will be triggered here by the changes to all the `go.mod` files.
/kind cleanup
```release-note
Upgrade to Go 1.20
```
=> Upgrade to Go 1.20

internal/apis/certmanager/validation/certificate.go, internal/apis/certmanager/validation/certificate_test.go
- Added validation for certificate.spec.secretName checking for valid k8s [secret name](https://kubernetes.io/docs/concepts/configuration/secret/#restriction-names-data), which should be a [DNS subdomain name](https://kubernetes.io/docs/concepts/overview/working-with-objects/names#dns-subdomain-names)
- Updated test cases
Fixes #5963 
kind/cleanup
```release-note
Validates that `certificate.spec.secretName` is a valid `Secret` name
```
=> Validate certificate.spec.secretName is a valid k8s resource name

make/tools.mk
Kubebuilder tools were re-pushed for kube 1.26.1 https://github.com/kubernetes-sigs/kubebuilder/commit/88c7833774d1659bbcc8e858e015ad81ed4369c8 so the SHAs changed and our tests are failing.
This PR updates the SHAs and adds a comment that these SHAs can change.
Some time ago I asked a question about the SHAs changing and was told that this can happen also not often https://kubernetes.slack.com/archives/CAR30FCJZ/p1665057082715119
```release-note
NONE
```
/kind cleanup
=> Update kubebuilder tools

hack/latest-kind-images.sh, make/cluster.sh, make/kind_images.sh
cert-manager v1.11 will be supported for a couple more months so it makes sense for 1.11 to support Kubernetes 1.27.
This PR adds Kuberentes 1.27 kind image. The 1.27 tests were already added to cert-manager 1.11 periodics in https://github.com/jetstack/testing/pull/883
```release-note
NONE
```
/kind cleanup
=> Adds kube 1.27 kind image

make/ko.mk
ko make targets do not work without go workspaces set up- this PR adds a comment that explains that.
In theory we could do something smart to detect if they are set up, but in practice that is probably an overkill.
```release-note
NONE
```
/kind cleanup
=> Add a comment that go workspaces are required to use ko make targets

cmd/controller/app/controller.go, internal/informers/core.go, internal/informers/core_basic.go, internal/informers/core_filteredsecrets.go, pkg/controller/acmechallenges/controller.go, pkg/controller/context.go, pkg/controller/test/context_builder.go, pkg/issuer/acme/http/http.go, pkg/issuer/acme/http/pod.go, pkg/issuer/acme/http/pod_test.go, pkg/issuer/acme/http/service.go, pkg/issuer/acme/http/service_test.go
This PR ensures that cert-manager retrieves and caches metadata only Pods and Services for http-01 challenge and applies a filter to only cache relevant resources.
Currently cert-manager watches [all Pods and Services in the cluster](https://github.com/cert-manager/cert-manager/blob/master/pkg/controller/acmechallenges/controller.go#L95-L98) which causes unnecessary memory/CPU consumption when any events occur for any Pods/Services in cluster.
This PR introduces metadata only informer factory with a filter for http-01 challenge resource filters. Pods and Services' informers get created from this factory.
- We start a new metadata informer factory rather than using the [the one that's created for Secrets](https://github.com/cert-manager/cert-manager/blob/master/internal/informers/core_filte …
=> Cache metadata only for pods and services

make/licenses.mk
`make update-licenses` fails if `_bin/scratch` does not exist.
This PR ensurse that `_bin/scratch` is created if it does not exist like we do in all other make targets
```release-note
NONE
```
/kind cleanup
=> Ensure _bin/scratch exists before attempting to update licenses

cmd/controller/app/controller.go, cmd/controller/app/options/options.go, cmd/controller/go.mod, deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/values.yaml, pkg/healthz/doc.go, pkg/healthz/healthz.go, pkg/healthz/healthz_test.go
Added a  /livez endpoint which reports the leaderElection status and fails if leader election record has not been observed for `leader-election-lease-timeout + leader-election-healthz-adaptor-timeout`.
A livenessProbe has been added to the controller container of the controller Pod,
which is disabled by default, because we do not actually know of any bugs in the controller which would cause it hang.
A failure in the renewal of the leader election should always result in the controller process exiting.
But in case such a bug does occur in the field, the user now has the ability to turn on the liveness probe.
They can also configure the durations and thresholds, using Helm chart values, because the default values were arbitrarily based on those used in the Kubernetes controller-manager.
The …
=> Report controller-manager as unhealthy if leader election has failed to renew the lease but process is wedged

pkg/util/pki/match.go
If a LiteralSubject is set, the IPs, URIs, DNSNames, ... should still be compared.
/kind bug
```release-note
Adds missing comparisons for certain fields which were incorrectly skipped if a LiteralSubject was set
```
=> BUGFIX: if a LiteralSubject is set, the RequestMatchesSpec function does skip too many checks

LICENSES, cmd/controller/LICENSES, hack/latest-kubebuilder-shas.sh, make/tools.mk
Some `make` commands do not function on Mac M1 / Arm64 Architecture e.g. due to naming conflicts of variables used for checksum validation.
Bug
```release-note
NONE
```
=> Add initial support for linux/arm64 as a dev platform

deploy/crds/crd-certificates.yaml, internal/controller/certificates/policies/checks.go, pkg/apis/certmanager/v1/types_certificate.go
The current policy check for keystores in Secrets creates a loop because
the truststore.jks or truststore.p12 will never exist when the issuer didn't
provide the CA certificate. This behaviour was introduced by #5597
The JKS and PKCS12 truststores are only added to the Secret
if the CA is provided by the issuer. The CertificateRequest API
reference states:
> The PEM encoded x509 certificate of the signer, also known
> as the CA (Certificate Authority). This is set on a best-effort basis by
> different issuers. If not set, the CA is assumed to be unknown/not available.
This change will only check the PKCS12/JKS truststores if the CA cert from the
issuer exists in the secret.
Fixes #5755
/kind bug
```release-note
Check JKS/PKCS12 truststore in Secrets only if issuer provides the CA
```
=> Check JKS/PKCS12 truststore in Secrets only if issuer provides the CA 

cmd/controller/app/options/options.go
In https://github.com/cert-manager/cert-manager/pull/5962 we added a new healthz server, 
but we are unsure about the implementation of the healthz server as a separate HTTP server and we may need to change it in a future release, so we want to avoid users overriding these flags, for now.
* https://github.com/cert-manager/cert-manager/pull/5962
/kind cleanup
```release-note
NONE
```
=> Hide the new healthz server flags

cmd/cainjector/app/start.go, deploy/charts/cert-manager/templates/cainjector-rbac.yaml, design/20220118.server-side-apply.md, internal/cainjector/feature/features.go, make/e2e-setup.mk, pkg/controller/cainjector/injectables.go, pkg/controller/cainjector/reconciler.go, pkg/controller/cainjector/setup.go, test/e2e/suite/serving/cainjector.go
based on #4810
This PR implements Server Side Apply for the ca-injector controller when the `SeverSideApply` Feature Gate (default `disabled`) is enabled.
---
This PR adds the `--feature-gates` flag to the `ca-injector` component. A `featureGates` field has been added to the ca-injector section in the helm chart. This field gets piped down to the `ca-injector` Deployment.
The `/devel/addons/cert-manager/install.sh` script has been updated to interpret the `FEATURE_GATES_CA_INJECTOR` environment variable, which gets piped down to the `cainjector.featureGates` helm chart value. We should update the testing config to include the same feature gate options we assign for the controller component. …
=> Server Side Apply: Adds support for CA Injector controller

pkg/healthz/healthz_test.go
Simulate a remote leader that always updates its lease
Fixes test flakes caused by the local node taking over leadership, because it did not observe any change in the leader election record held by the remote node.
The test flakes only became apparent during the upgrade of k8s.io/client-go in #5961. 
Which includes the following bug fix: [client-go: fix the wait time for trying to acquire the leader lease](https://github.com/kubernetes/kubernetes/pull/114872#top)
To demonstrate that this will indeed fix the flakes, I created a PR where this change is rebased on #5961
* https://github.com/cert-manager/cert-manager/pull/6020
/kind bug
```release-note
NONE
```
=> Fix flaky leader election healthz tests

cmd/ctl/pkg/check/api/api.go, cmd/webhook/app/testing/testwebhook.go, pkg/webhook/authority/authority.go, pkg/webhook/server/tls/dynamic_source.go, test/integration/acme/orders_controller_test.go, test/integration/certificates/issuing_controller_test.go, test/integration/certificates/metrics_controller_test.go, test/integration/certificates/revisionmanager_controller_test.go, test/integration/certificates/trigger_controller_test.go, test/integration/ctl/ctl_create_cr_test.go, test/integration/framework/helpers.go, test/integration/webhook/dynamic_authority_test.go, test/integration/webhook/dynamic_source_test.go
see https://pkg.go.dev/k8s.io/apimachinery/pkg/util/wait#PollImmediateUntil
I plan to replace each wait function one at a time.
NOTE: `wait.ErrWaitTimeout` is now deprecated and the Poll functions directly return `context.Canceled` or `context.DeadlineExceeded`.
/kind cleanup
```release-note
NONE
```
=> Replace deprecated wait.PollImmediateUntil

test/e2e/suite/issuers/venafi/tpp/certificate.go, test/e2e/suite/issuers/venafi/tpp/setup.go
Resolves panic on cleanup that is caused by a issuer that equals nil.
This issuer equals nil because the test is being skipped.
/kind cleanup
```release-note
NONE
```
=> Fix cleanup panic

make/tools.mk
Kubebuilder tools have been updated for v1.27.1 https://github.com/kubernetes-sigs/kubebuilder/commits/tools-releases
so our tests are failing https://testgrid.k8s.io/cert-manager-periodics-release-1.12#ci-cert-manager-release-1.12-make-test
This PR contains the SHAs produced by running `./hack/latest-kubebuilder-shas.sh v1.27.1`
```release-note
NONE
```
/kind cleanup
=> Update kubebuilder tools SHAs

cmd/ctl/go.mod, cmd/ctl/go.sum, make/ci.mk, make/tools.mk, test/integration/go.mod
Related to #6047 and #6041
This PR depended on https://github.com/cert-manager/release/pull/127 , which has now merged.
We want to preserve the ability for other projects to import cmctl as a module. This implies that we can't have a local filesystem replacement for the core cert-manager module in cmctl, and that cmctl must depend on an explicitly specified version of cert-manager.
Eventually we'd like cmctl to be moved to its own repo, but that's too much work right now.
Since the integration tests depend on cmctl, they also pick up an actual version of cert-manager in their go.mod file from this change. That shouldn't matter, since they still have a replace statement for cert-manager.
/kind feature
```release-note
Enable cmctl to be imported by third parties
```
=> Directly import cert-manager in cmctl

cmd/ctl/pkg/create/certificaterequest/certificaterequest.go, cmd/ctl/pkg/create/certificatesigningrequest/certificatesigningrequest.go, pkg/controller/certificates/requestmanager/requestmanager_controller.go, pkg/webhook/server/tls/dynamic_source.go, test/acme/suite.go, test/acme/util.go, test/e2e/suite/issuers/acme/issuer.go, test/integration/certificates/generates_new_private_key_per_request_test.go, test/integration/ctl/ctl_create_cr_test.go
see https://pkg.go.dev/k8s.io/apimachinery/pkg/util/wait#PollImmediateUntil
I plan to replace each wait function one at a time.
/kind cleanup
```release-note
NONE
```
=> Replace deprecated wait.PollUntil and wait.Poll

cmd/ctl/LICENSES, cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/LICENSES, test/integration/go.mod, test/integration/go.sum
fixes some docker CVEs
/kind cleanup
```release-note
NONE
```
=> Upgrade github.com/docker/distribution v2.8.2+incompatible

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
/kind cleanup
```release-note
NONE
```
=> Upgrade the cert-manager dependency to the 1.12-relaese HEAD commit

make/tools.mk
kubebuilder tools have been rebuilt for kube 1.27.1 with an updated alpine image, so the SHAs have changed and our tests are failing
https://github.com/kubernetes-sigs/kubebuilder/commits/tools-releases
https://testgrid.k8s.io/cert-manager-periodics-release-1.12#ci-cert-manager-release-1.12-make-test
https://testgrid.k8s.io/cert-manager-periodics-master#ci-cert-manager-master-make-test
Probably at some point we'll need to look into identifying the tools differently than by kube tag as they get repushed for the same tag quite a bit, so this is becoming a toil.
```release-note
NONE
```
=> Kubebuilder shas

pkg/apis/acme/v1/types_issuer.go
The `PreferredChain` field is marked optional in the API docs, but is required when serializing JSON. Make it optional to match.
bug
Probably don't need one, but:
```release-note
Make apis/acme/v1/ACMEIssuer.PreferredChain optional in JSON serialization.
```
=> apis/acme/v1: ACMEIssuer: set omitempty on optional field

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
This PR bumps cert-manager version in cmctl's `go.mod` file to v1.12.0. This should have been done _before_ releasing, however should not be a major issue as I cannot think of any changes that went in in cert-manager before v1.12.0-beta.1 and v1.12.0 that would have affected cmctl.
I've updated the release process notes so we don't forget it in the future https://github.com/cert-manager/website/pull/1225
```release-note
NONE
```
/kind cleanup
=> Updates cmctl to point at latest cert-manager

pkg/acme/webhook/cmd/server/start.go
This was meant to be a cherry-pick of #6085 , but that had a merge conflict, so I had to create a separate PR against release-1.11 https://github.com/cert-manager/cert-manager/pull/6085#issuecomment-1557408517
I have checked that the APF gets disabled as expected using samplewebhook (`make e2e-setup-samplewebhook`)
I will cut actual patch releases for 1.11 and 1.12 with this change once we get c/r 0.15 so I can put that into 1.12 patch.
```release-note
API Priority and Fairness controller is now disabled in extension apiserver for DNS webhook implementation.
```
/kind cleanup
=> [release-1.11] cherry-pick of disabling APF controller in webhook

deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/values.yaml, internal/cainjector/feature/features.go, internal/controller/feature/features.go, internal/webhook/feature/features.go, make/e2e-setup.mk, pkg/controller/certificates/requestmanager/requestmanager_controller.go, pkg/util/pki/csr.go, pkg/util/pki/csr_test.go
See #6011 for context- a shared library was pulling in some code from controller's feature gate setup, which was causing the webhook's feature gates being overwritten by the controller ones because webhook was also importing the shared library.
Additionally in https://github.com/cert-manager/cert-manager/pull/5584 we started relying on this bug by passing the feature flag values previously meant for controller into webhook.
Also our docs currently list the controller feature gates for webhook (I think I will edit this by hand no matter whether this PR gets cherry-picked or not) https://cert-manager.io/docs/cli/webhook/
This PR:
- removes the references to controller feature gates in the shared PKI library that was causing the controller feature gates to overwrite the webhook feature gates …
=> Fix webhook feature gate

deploy/charts/cert-manager/values.yaml
cherry-picker seems kaput https://github.com/cert-manager/cert-manager/pull/6100#issuecomment-1561169612
```release-note
NONE
```
/kind cleanup
=> Adds a note about usage of featureGates value in Helm chart to release-1.11

internal/controller/certificates/secrets_test.go, pkg/controller/certificaterequests/acme/acme_test.go, pkg/controller/certificaterequests/ca/ca_test.go, pkg/controller/certificaterequests/venafi/venafi_test.go, pkg/controller/certificatesigningrequests/ca/ca_test.go, pkg/util/pki/certificatetemplate.go, pkg/util/pki/csr_test.go, pkg/util/pki/generate_test.go, pkg/util/pki/kube_test.go, pkg/webhook/authority/authority.go, pkg/webhook/server/tls/dynamic_source.go, pkg/webhook/server/tls/file_source_test.go, test/e2e/util/util.go, test/framework/addon/vault/vault.go, test/unit/gen/csr.go
see https://github.com/cert-manager/cert-manager/blob/master/pkg/util/pki/certificatetemplate.go#L78-L81 for context
We incorrectly assumed that the golang *x509.Certificate Version field is the encoded version (which would be 2).
Based on the comment here https://cs.opensource.google/go/go/+/master:src/crypto/x509/x509.go;l=823-827, it is clear that the Version field in *x509.Certificate is the actual version value (which should be 3).
In some places, we were setting the Version of CertificateRequest to 3 too, which is incorrect and should be kept at 0 instead.
/kind bug
```release-note
NONE
```
=> Use Version 3 for *x509.Certificate

pkg/issuer/acme/http/pod.go, pkg/issuer/acme/http/pod_test.go
The PR disables the automatic service link injection and fixes https://github.com/cert-manager/cert-manager/issues/6142.
The service link injection is not recommended by k8s and the solver does not need them anyway.
bug
```release-note
Fixes a bug that caused the http solver pod to be in crash loop in a cluster with lot of services.
```
=> Remove service links from http solver pod

deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/startupapicheck-job.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml
Disables all not needed [`enableServiceLinks`](https://kubernetes.io/docs/tutorials/services/connect-applications-service/) in the helm chart.
The service env vars are not needed and just add overhead.
Requested here: https://github.com/cert-manager/cert-manager/pull/6143#issuecomment-1586812347
cleanup
```release-note
All service links in helm chart deployments have been disabled.
```
=> Disable service link in helm chart deployments

design/20230302.gomod.md
It became clear recently that the module proliferation design document had failed to serve the purpose of being clear about the reasons _for_ the change and.
This PR is an attempt to add a clarification using short and snappy bullet points of why the change was proposed, and the motivations and benefits of doing it.
```release-note
NONE
```
=> Attempt to clarify in short the modules proliferation design

pkg/controller/certificates/requestmanager/requestmanager_controller.go
I forgot to update this line in https://github.com/cert-manager/cert-manager/pull/6019.
/kind bug
```release-note
NONE
```
=> BUGFIX: I incidentally removed the feature gate check that enables the UseCertificateRequestBasicConstraints feature

hack/check-crds.sh
Remove the "--tmpdir" flag from mktemp in the check-crds.sh script. 
- The OS X version of mktemp doesn't support the --tmpdir flag.
- According to the doc for mktemp on OSX: "If no arguments are passed or if only the -d flag is passed mktemp behaves as if -t tmp was supplied."
- This will continue to work for Linux based versions of mktemp.
`make verify-crds` was failing on OS X. This commit resolves the issue. Below is the output of the failure: 
```
❯ make verify-crds
cd _bin/tools/ && ln -f -s ../downloaded/tools/yq@v4.27.5_darwin_amd64 yq
./hack/check-crds.sh go ........./_bin/tools/controller-gen ........../_bin/tools/yq
+++ verifying that generated CRDs are up-to-date...
/Library/Developer/CommandLineTools/usr/bin/make: unrecognized option `--tmpdir'
```
bug 
```release-note
NONE …
```
=> Remove the "--tmpdir" flag from mktemp

make/test.mk
I wasn't able to use the CGO compiled e2e.test binary on RedHat Enterprise Linux in 
* https://github.com/cert-manager/cert-manager-olm/pull/94
This compiles the `e2e.test` binary statically and also reduces the size of the binary by stripping debugging symbols.
```
$ ./_bin/test/e2e.test --repo-root=/dev/null --ginkgo.focus="CA\ Issuer" --ginkgo.skip="Gateway"
Running Suite: cert-manager e2e suite - /home/richard/projects/cert-manager/cert-manager
========================================================================================
Random Seed: 1687867131
Will run 44 of 777 specs
"hashicorp" already exists with the same configuration, skipping
Release "chart-vault-vault" does not exist. Installing it now.
NAME: chart-vault-vault
LAST DEPLOYED: Tue Jun 27 12:58:53 2023
NAMESPACE: …
```
=> Static e2e test build

make/cluster.sh, make/e2e-setup.mk
Before this commit, regardless of what was put for KIND_CLUSTER_NAME, the name of the cluster was always "kind". Furthermore, when running make clean, only clusters named "kind" were cleaned up. With a few minor fixes, this commit solves the problem so that kind clusters with different names can be used when running tests.
Before the changes proposed in this MR, when running `make KIND_CLUSTER_NAME=<name> e2e-setup-kind` the `KIND_CLUSTER_NAME` variable had no effect on the cluster name. The cluster that was stood up was always named "kind." Furthermore, if attempting to clean up the cluster `make clean` always deleted the "kind" cluster. From the [comments here](https://github.com/malovme/cert-manager/blob/master/make/e2e-setup.mk#L72-L74), we assume that the intent was to have the name …
=> Honor KIND_CLUSTER_NAME for e2e-setup & clean

pkg/issuer/acme/dns/cloudflare/cloudflare.go
The current implementation of the Cloudflare DNS01 challenge provider does not function as expected when validating multiple Let's Encrypt certificates simultaneously. The [Present](https://github.com/cert-manager/cert-manager/blob/master/pkg/issuer/acme/dns/cloudflare/cloudflare.go#L143) function deletes any existing TXT record under the FQDN; therefore, if there is another ongoing challenge under the same FQDN (e.g., by [following CNAME](https://cert-manager.io/docs/configuration/acme/dns01/#delegated-domains-for-dns01)), the newest challenge overwrites the previous challenge while it is still being validated by Let's Encrypt.
This MR removes the Cloudflare delete record API call from the [Present](https://github.com/cert-manager/cert-manager/blob/master/pkg/issuer/acme/dns/cloudflare/cl …
=> Handle multiple Cloudflare DNS01 challenges for the same FQDN

internal/apis/certmanager/validation/certificaterequest.go, internal/webhook/feature/features.go, pkg/api/util/kube.go, pkg/api/util/usages.go, test/integration/validation/certificaterequest_test.go
While creating https://github.com/cert-manager/cert-manager/pull/6056, we realised that the current CertificateRequest CSR webhook validation logic is too permissive:
If CertificateRequest.Usages is empty and the KeyUsages are only set as an extension in the CSR blob, the validation webhook allows this CertificateRequest to be created. However, some solutions (like approver-policy) depend on the Usages always being defined in the Usages array.
This is a quick summary of the current webhook behavior vs the new behavior:
| situation                    | before                      | after                                      |
|------------------------------|-----------------------------|--------------------------------------------|
| usages in CertReq & CSR blob | error if != …
=> BUGFIX: Stricter CertificateRequest CSR webhook validation

internal/controller/certificates/policies/checks.go, internal/controller/certificates/policies/checks_test.go, internal/controller/certificates/policies/constants.go, internal/controller/certificates/policies/policies.go, pkg/controller/certificates/issuing/secret_manager_test.go
Previously, the `cert-manager.io` annotations were just being ignored while checking the annotations in the template.
This PR adds checks that make sure the correct `cert-manager.io` annotations are present and that they have the correct value.
Same goes for the `controller.cert-manager.io/fao` label.
eg. Previously, you could remove or overwrite a `cert-manager.io/common-name` annotation on a Secret. Now, this annotation will be automatically updated to match its expected value after a change is detected.
/kind cleanup
```release-note
The SecretPostIssuancePolicyChain now also makes sure that the `cert-manager.io/common-name`, `cert-manager.io/alt-names`, ... annotations on Secrets are kept at their correct value.
```
=> Reconcile when managed annotations/ labels are out-of-sync

LICENSES, cmd/controller/LICENSES, cmd/controller/go.mod, cmd/controller/go.sum, cmd/ctl/LICENSES, cmd/webhook/LICENSES, cmd/webhook/go.mod, cmd/webhook/go.sum, go.mod, go.sum, internal/controller/feature/features.go, pkg/controller/certificaterequests/acme/acme_test.go, pkg/controller/certificaterequests/ca/ca.go, pkg/controller/certificaterequests/selfsigned/selfsigned.go, pkg/controller/certificatesigningrequests/venafi/venafi_test.go, pkg/issuer/venafi/client/request.go, pkg/util/pki/certificatetemplate.go, test/e2e/LICENSES, test/e2e/go.mod, test/e2e/go.sum, test/e2e/suite/certificatesigningrequests/selfsigned/selfsigned.go, test/integration/LICENSES, test/integration/go.mod, test/integration/go.sum
If the CertificateRequest or CertificateSigningRequest is not valid, the pki CertificateTemplate functions functions should return an error. This prevents us from signing a certificate with the wrong "privileges" (= wrong IsCA value or wrong (Extended)KeyUsages) in case the IsCA or (Extended)KeyUsages values don't match what is encoded in the CSR blob.
/kind cleanup
/kind feature
```release-note
The pki CertificateTemplate functions now perform validation of the CSR blob, making sure we sign a Certificate that matches the IsCA and (Extended)KeyUsages that are defined in the CertificateRequest resource.
```
=> Add validation to pki CertificateTemplate functions

LICENSES, cmd/controller/LICENSES, cmd/controller/go.mod, cmd/controller/go.sum, go.mod, go.sum, pkg/issuer/venafi/client/request.go, test/e2e/go.mod
Thanks to https://github.com/Venafi/vcert/pull/295, we do not longer need the fork.
/kind cleanup
```release-note
NONE
```
=> Remove VCert fork dependency replace statement

LICENSES, cmd/controller/LICENSES, cmd/controller/go.mod, cmd/controller/go.sum, go.mod, go.sum, pkg/issuer/venafi/client/request.go, test/e2e/go.mod
manual backport of https://github.com/cert-manager/cert-manager/pull/6206
/kind cleanup
```release-note
NONE
```
=> [release-1.12] remove VCert fork dependency replace statement

deploy/charts/cert-manager/templates/serviceaccount.yaml
Enabling workload identity requires the addition of a label to the service account. Unfortunately the current implementation adds a white line on top of the provided extra label
```yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
name: cert-manager
namespace: cert-manager
labels:
app: cert-manager
app.kubernetes.io/name: cert-manager
app.kubernetes.io/instance: cert-manager
app.kubernetes.io/component: "controller"
app.kubernetes.io/version: "v1.12.2"
app.kubernetes.io/managed-by: Helm
helm.sh/chart: cert-manager-v1.12.2
azure.workload.identity/use: true
```
bug
```release-note
NONE
```
=> service account labels introduce a white line issue

deploy/charts/cert-manager/templates/cainjector-poddisruptionbudget.yaml, deploy/charts/cert-manager/templates/poddisruptionbudget.yaml, deploy/charts/cert-manager/templates/webhook-poddisruptionbudget.yaml, deploy/charts/cert-manager/values.yaml
The new certmanager chart managed PDBs use `{{ with .minAvailable }}` and `{{ with .maxUnavailable }}` but due to the default value of `.minAvailable` you can't use `.maxUnavailable` without setting `.minAvailable` to `null`.
Because we use certmanager as a helm dependency we can't set `.minAvailable` to `null`. This is due to the helm bug where null values are not passed to dependent charts.
Because `.minAvailable: 1` is the default value I think it makes the most sense to skip setting `minAvailable` when `.maxUnavailable` is set, and not the other way around. Any other configuration is bad configuration supplied by the user which they can simply remove from the values to fix any deployment errors.
bug 
```release-note
Allow overriding default pdb .minAvailable with .maxUnavailable …
```
=> fix: maxUnavailable pdb configuration cannot be used due to default set minAvailable

pkg/controller/cainjector/indexers.go
This was discovered as part of the investigation into #6104
/kind bug
```release-note
NONE
```
=> Use supplied context where possible

pkg/controller/cainjector/indexers.go
Instead of creating a new local log variable, we were updating the cross-invocation log variable and were adding more Values to the log variable, causing high memory usage and incorrect log messages.
fixes #6217
fixes #6104
This bug affects all clusters and can be accelerated by creating and/ or updating lots of Secret resources.
/kind bug
```release-note
BUGFIX: 1-character bug was causing invalid log messages and a memory leak
```
=> [BUGFIX] Incorrect re-assignment of cross-invocation variable

pkg/controller/cainjector/indexers.go
This was discovered as part of the investigation into #6104
Manual backport.
/kind bug
```release-note
NONE
```
=> [release-1.12] Use supplied context where possible

deploy/charts/cert-manager/templates/webhook-deployment.yaml
Conforming to the recommended rules.
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
> For Pods running with hostNetwork, you should explicitly set its DNS policy to "ClusterFirstWithHostNet".
feature
```release-note
chore: When hostNetwork is enabled, dnsPolicy is now set to ClusterFirstWithHostNet.
```
=> chore: When hostNetwork is enabled, dnsPolicy is now set to ClusterFirstWithHostNet.

internal/cmd/util/exit.go, pkg/logs/logs.go, pkg/util/cmapichecker/cmapichecker.go, pkg/util/cmapichecker/cmapichecker_test.go, pkg/util/versionchecker/versionchecker.go
Continuation of what we started in https://github.com/cert-manager/cert-manager/pull/5828.
Changes cmctl to use the logging library used in all our other components.
**NOTE**: I had to split this PR into 2 parts: [part 1](https://github.com/cert-manager/cert-manager/pull/6108) and [part 2](https://github.com/cert-manager/cert-manager/pull/6119) because cmctl uses a pinned cert-manager version. This PR contains all the changes to cert-manager/cert-manager.
/kind cleanup
I added the release note in [part 2](https://github.com/cert-manager/cert-manager/pull/6119).
```release-note
NONE
```
=> Use logging library with json support in cmctl (part 1)

internal/cmd/util/exit.go, pkg/util/cmapichecker/cmapichecker.go
Continuation of what we started in https://github.com/cert-manager/cert-manager/pull/5828.
Changes cmctl to use the logging library used in all our other components.
**NOTE**: I had to split this PR into 3 parts: [part 1](https://github.com/cert-manager/cert-manager/pull/6108), [part 2](https://github.com/cert-manager/cert-manager/pull/6119) and [part 3](https://github.com/cert-manager/cert-manager/pull/6247) because cmctl uses a pinned cert-manager version. This PR contains some remaining changes to cert-manager/cert-manager.
/kind cleanup
You can find the release notes in https://github.com/cert-manager/cert-manager/pull/6119
```release-note
NONE
```
=> Use logging library with json support in cmctl (part 2)

pkg/issuer/acme/dns/util/wait_test.go
In the long term I don't think this test should be run as a unit test because it can randomly break due to changes in DNS config we don't control, which is a pretty poor user experience for someone trying to change unrelated code.
If we're going to run this kind of check, we should probably run it as a periodic rather than a presubmit, perhaps with the test being run on presubmit when the DNS util code is changed.
But that's all more work than I can really do now. Instead, I'll copy what the upstream go-lego is doing, which should unblock us for now:
https://github.com/go-acme/lego/blob/07c4daeff3c5d5e228b2490e002295716083a5fa/challenge/dns01/nameserver_test.go
For more context / info, see [this slack thread](https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1691139262485849).
For an …
=> Update nameserver lookup test to use upstream targets

internal/apis/config/webhook/fuzzer/fuzzer.go, internal/apis/config/webhook/types.go, internal/apis/config/webhook/v1alpha1/defaults.go, internal/apis/config/webhook/v1alpha1/zz_generated.conversion.go, internal/apis/config/webhook/validation/validation.go, internal/apis/config/webhook/zz_generated.deepcopy.go, internal/webhook/webhook.go, pkg/apis/config/webhook/v1alpha1/types.go, pkg/apis/config/webhook/v1alpha1/zz_generated.deepcopy.go, pkg/webhook/options/options.go, test/webhook/testwebhook.go
public: *int -> *int32
> All public integer fields MUST use the Go int32 or Go int64 types, not int (which is ambiguously sized, depending on target platform). Internal types may use int.
see https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md
internal: *int -> int32
Since the value is always being defaulted, it makes no sense to have a pointer value here. Also, I changed the type to int32 to match the public API.
/kind cleanup
```release-note
NONE
```
=> WebhookConfiguration: change the types of ports from *int to *int32

cmd/webhook/app/webhook.go, internal/apis/config/controller/types.go, internal/apis/config/webhook/fuzzer/fuzzer.go, internal/apis/config/webhook/types.go, internal/apis/config/webhook/v1alpha1/defaults.go, internal/apis/config/webhook/v1alpha1/zz_generated.conversion.go, internal/apis/config/webhook/zz_generated.deepcopy.go, pkg/apis/config/webhook/v1alpha1/types.go, pkg/apis/config/webhook/v1alpha1/zz_generated.deepcopy.go, pkg/logs/logs.go, pkg/webhook/options/options.go
The webhook config file is missing the logging options.
In https://github.com/cert-manager/cert-manager/pull/5337, I learned that we can include the logging options in our config file.
While writing this PR, I noticed the current controller config file still has a defaulting bug wrt. the logging options.
This PR fixes that bug and adds the logging options in the webhook config file.
/kind feature
```release-note
Add support for logging options to webhook config file.
```
=> Move logging options to webhook config file

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/startupapicheck-job.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/values.yaml
PR https://github.com/cert-manager/cert-manager/pull/6144 changed the `spec.enableServiceLinks` of all Deployments and the `startupapicheck` Job to `false`. 
In the controller Deployment, we're relying on these service links environment variables to use the cluster internal CoreDNS as value for the `dns01RecursiveNameservers`.
/kind feature
```release-note
Make `enableServiceLinks` configurable for all Deployments and `startupapicheck` Job in Helm chart.
```
=> Make enableServiceLinks configurable for DeploymentLikes

cmd/controller/app/start.go, cmd/controller/app/start_test.go, cmd/webhook/app/webhook.go, cmd/webhook/app/webhook_test.go, cmd/webhook/go.mod, pkg/logs/logs.go
In preparation for the 1.28 upgrade (https://github.com/cert-manager/cert-manager/pull/6287), we have to fix an issue with loading the logging options from flags & configfile.
Currently, we set the logging options based on the config in the flags & re-set the options after we parsed the configfile. This is done so we can use the logging settings from the flags while parsing the config file.
In 1.28 however, the logging library has become a bit more strict & does no longer allow re-setting the logging options.
/kind cleanup
```release-note
NONE
```
=> Only set logging settings once

pkg/util/pki/certificatetemplate.go
Since there is no way to configure what the MaxPathLen should be outside of the CSR blob, we cannot validate that the CSR blob matches that expected value.
Instead, we only override the MaxPathLen value that was set in the CSR blob.
/kind cleanup
```release-note
NONE
```
=> Remove MaxPathLen CSR blob validation logic

cmd/cainjector/go.mod, cmd/cainjector/go.sum, pkg/util/pki/csr.go, pkg/util/pki/match.go, pkg/util/util.go, pkg/util/util_test.go
Prompted by #6265 which included an example allowing for reproduction of the bug ❤️ 
This fix was discovered in two parts:
1. I discovered we weren't using a more correct IP comparison function we already had in our util package
2. I discovered that the function we already had was inefficient and poorly tested
The underlying issue is also twofold here:
1. IPv6 addresses often have multiple printed representations which are different strings but which represent the same IP address, meaning that comparing strings is incorrect for IP addresses. Consider `2a0e:2345:6789:1:1:2::6` and `2a0e:2345:6789:0001:0001:0002:0000:0006` which are the same. The same is true for IPv4 addresses but much less commonly seen, e.g. `001.001.001.001` and `1.1.1.1`.
2. IPv4 addresses have multiple representations …
=> Fix invalid handling of ip addresses in comparisons

cmd/cainjector/go.mod, cmd/cainjector/go.sum, pkg/util/pki/csr.go, pkg/util/pki/match.go, pkg/util/util.go, pkg/util/util_test.go
This manual backport of #6293 was to avoid adding a new [dependency](https://pkg.go.dev/golang.org/x/exp/slices) to the 1.12 branch of cert-manager. It uses sort.Slice instead of the slices package.
We first tried an automatic backport via #6295 but realised a manual backport would be needed
/kind bug
```release-note
Fixes an issue where cert-manager would incorrectly reject two IP addresses as being unequal when they should have compared equal. This would be most noticeable when using an IPv6 address which doesn't match how Go's `net.IP.String()` function would have printed that address.
```
=> [release-1.12] fix invalid handling of ip addresses in comparisons

pkg/logs/logs.go
Many klog flags have been marked as deprecated in Kubernetes 1.23 (as per [KEP-2845](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/README.md)) and will go away in Kubernetes 1.26. I propose that we follow the same path for the same reasons.
**Plan:**
- **cert-manager 1.12** (end of April 2023): start of the deprecation period for the flags `--log_dir`, `--log_file`, `--log_flush_frequency`, `--logtostderr`, `--alsologtostderr`, `--one_output`, `--stderrthreshold`, `--log_file_max_size`, `--skip_log_headers`, `--add_dir_header`, `--skip_headers`, `--log_backtrace_at`.
- ~~**cert-manager 1.15** (approx 6 month afterwards, Nov 2023): removal of the flags.~~ We do not have a planned version in which we will …
=> Deprecate klog flags and add a deprecation message

internal/apis/certmanager/validation/certificaterequest.go, internal/controller/feature/features.go, internal/webhook/feature/features.go, pkg/controller/certificaterequests/ca/ca.go, pkg/controller/certificaterequests/selfsigned/selfsigned.go, test/integration/validation/certificaterequest_test.go
This flag was introduced in https://github.com/cert-manager/cert-manager/pull/6182 and https://github.com/cert-manager/cert-manager/pull/6199 (not yet released).
I incorrectly made the flag a GA flag, while it should be Beta flag (see https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-stages).
This PR renames the `DontAllowInsecureCSRUsageDefinition` feature flag to `DisallowInsecureCSRUsageDefinition` and makes it a Beta flag.
fixes https://github.com/cert-manager/cert-manager/issues/6203
/kind cleanup
```release-note
NONE
```
=> Rename DontAllowInsecureCSRUsageDefinition feature flag and make it a Beta flag

internal/controller/feature/features.go, pkg/controller/certificates/requestmanager/requestmanager_controller_test.go, pkg/controller/certificates/requestmanager/util_test.go, test/integration/certificates/generates_new_private_key_per_request_test.go
Based on our CI testing, we can be reasonably comfortable with enabling StableCertificateRequestName and SecretsFilteredCaching by default & promoting them to Beta (see "A Beta feature means:" https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-stages).
I had to update some of our tests so they work with the new defaults.
/kind feature
```release-note
Promoted the StableCertificateRequestName and SecretsFilteredCaching featureflags to Beta (enabled by default).
```
=> Feature gates: promote StableCertificateRequestName and SecretsFilteredCaching to Beta

make/tools.mk
Go 1.20.6, which we used to build the cert-manager 1.20.3 binaries, are affected by a security bug in `crypto/tls`.
You can learn more at https://github.com/golang/go/issues/61460.
```release-note
Use Go 1.20.7 to fix a security issue in Go's `crypto/tls` library.
```
xref: https://github.com/cert-manager/cert-manager/pull/6317
=> [release-1.12] Bump to Go 1.20.7

make/tools.mk
Go 1.19.9, which we used to build the 1.11.4 binaries, are affected by a security bug in `crypto/tls`.
```release-note
Use Go 1.19.9 to fix a security issue in Go's `crypto/tls` library.
```
=> [release-1.11] Bump to Go 1.19.12

cmd/ctl/LICENSES, cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/LICENSES, test/integration/go.mod, test/integration/go.sum
Fixes the failing trivy alert: https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/logs/ci-cert-manager-master-trivy-test-ctl/1697263245615697920
/kind cleanup
```release-note
NONE
```
=> Upgrade docker dependencies

deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml
Relating to the [certificate-preset](https://hackmd.io/@hawksight/r1CVOU9i3) investigations we have been exploring ideas on how provide users of the `Certificate` resource without baking a new feature into cert-manager code. (See #2239 for back story).
As suggested by @wallrj in [a slack thread](https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1692950767141859?thread_ts=1692898220.457779&cid=CDEQJ0Q8M), it seems that cert-manager only uses this mutating webhook for `CertificateRequest` resources, and not for actual certificates. (**NOTE** this may not be true and we should absolutely validate this). 
The impact of this webhook was that it applied to `Certificate` resources when cert-manager does nothing useful with them at admission time. In fact as @erikgb has pointed out [in …
=> cleanup: Scope mutating webhook to only certificaterequest resources

cmd/ctl/LICENSES, cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/LICENSES, test/integration/go.mod, test/integration/go.sum
Fixes a trivy CVE alert (see https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/logs/ci-cert-manager-master-trivy-test-ctl/1701250736081342464)
/kind cleanup
```release-note
NONE
```
=> Fix trivy CVE alert for cyphar/filepath-securejoin

pkg/issuer/acme/http/pod.go, pkg/issuer/acme/http/pod_test.go
This should make cert-manager installs on GKE friendlier to node autoscaling.
fixes #5267
bug
```release-note
acme-challenge-solver-http01 will get a default annotation of `"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"`. You can provide an annotation of `"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"` in your `podTemplate` if you don't like this.
```
=> Add cluster-autoscaler.kubernetes.io/safe-to-evict

pkg/api/util/names.go, pkg/api/util/names_test.go, pkg/controller/certificates/requestmanager/requestmanager_controller.go, pkg/controller/certificates/requestmanager/requestmanager_controller_test.go
Fixes https://github.com/cert-manager/cert-manager/issues/6342
The new mechanism is explained here: https://github.com/cert-manager/cert-manager/blob/860df2294b53ee512bfde186ed8478e6a43dd204/pkg/controller/certificates/requestmanager/requestmanager_controller.go#L401-L411
/kind cleanup
```release-note
BUGFIX: fix CertificateRequest name collision bug in StableCertificateRequestName feature.
```
=> BUGFIX: CertificateRequest short names must be unique.

deploy/charts/cert-manager/templates/controller-config.yaml
This PR resolves the issue https://github.com/cert-manager/cert-manager/issues/6343. The controller ConfigMap is created even if `.Values.config` isn't set. It doesn't create any issue with cert-manager, but after discussion it was decided to refactor the Helm Chart to create the ConfigMap only if `.Values.config` is set, along with other changes.
cleanup
```release-note
Controller ConfigMap if now created only if .Values.config is set.
```
=> improvement(helm): fixed empty controller configmap + refactored

LICENSES, cmd/cainjector/LICENSES, cmd/cainjector/go.mod, cmd/cainjector/go.sum, cmd/controller/LICENSES, cmd/controller/go.mod, cmd/controller/go.sum, cmd/ctl/LICENSES, cmd/ctl/go.mod, cmd/ctl/go.sum, cmd/webhook/LICENSES, cmd/webhook/go.mod, cmd/webhook/go.sum, go.mod, go.sum, test/e2e/LICENSES, test/e2e/go.mod, test/e2e/go.sum, test/integration/LICENSES, test/integration/go.mod, test/integration/go.sum
In https://github.com/cert-manager/cert-manager/pull/6332, I upgraded the go-restful dependency, but missed that the version is labeled "do not use" in its `CHANGES.md` file (https://github.com/emicklei/go-restful/blob/v3/CHANGES.md#v3102---2023-03-09---do-not-use).
/kind cleanup
```release-note
Upgrade `github.com/emicklei/go-restful/v3` to `v3.11.0` because `v3.10.2` is labeled as "DO NOT USE".
```
=> Fix go-restful dependency "do not use" version

make/tools.mk
Upgrading the go patch version to fix some CVE alerts.
/kind cleanup
```release-note
Upgrade Go from 1.20.7 to 1.20.8.
```
=> Upgrade Go from 1.20.7 to 1.20.8

deploy/charts/cert-manager/values.yaml, pkg/healthz/clock_health.go, pkg/healthz/healthz.go
This PR adds a new LivenessProbe that makes sure the clock skew is not more than 5 minutes.
If we detect that the monotonic duration since the start of the controller differs more than 5 minutes from the system clock duration since the start of the project, we return HTTP error code 500 and force a restart.
This check will fix the following issues:
- if the controller was started at time A & a timer for time B is created, hibernating for duration h will cause the timer to trigger at time B + h
- if the controller was started at time A & a timer for time B is created, changing the system clock (eg. fixing a wrong delta using ntp) will still result in the timer triggering at the original time
See https://github.com/golang/go/issues/35012 for the background on this issue in upstream Go. …
=> Add health probe that detects skew between system clock and monotonic go process clock

deploy/charts/cert-manager/templates/webhook-deployment.yaml
This PR closes #6346. (Webhook feature gates only set if controller feature gates are )
/kind bug
```release-note
BUGFIX[helm]: Fix issue where webhook feature gates were only set if controller feature gates are set.
```
=> BUGFIX[helm]: Fix issue where webhook feature gates were only set if controller feature gates are set (closes #6346)

pkg/util/pki/basicconstraints.go, pkg/util/pki/csr_test.go, pkg/util/pki/keyusage.go
Based on upstream x509, these extensions should be critical.
https://cs.opensource.google/go/go/+/refs/tags/go1.20.4:src/crypto/x509/x509.go;l=1351
https://cs.opensource.google/go/go/+/refs/tags/go1.20.4:src/crypto/x509/x509.go;l=1314
https://cs.opensource.google/go/go/+/refs/tags/go1.20.4:src/crypto/x509/x509.go;l=1332
This change is not a major change, it will only change what the CSRs look like.
For the certificate itself, we set the KeyUsage field on the *x509.Certificate struct and use golang to encode these extensions. Golang does always encode KeyUsage and BasicConstraints as Critical extensions in Certificates.
/kind bug
```release-note
⚠️ potentially breaking ⚠️: The KeyUsage and BasicConstraints extensions will now be encoded as critical in the CertificateRequest's CSR blob.
```
=> Make KeyUsage and BasicConstraints Critical extensions in the CSR blob

make/e2e-setup.mk, make/test.mk, test/e2e/framework/addon/vault/vault.go
Following up on https://github.com/cert-manager/cert-manager/pull/6387 I've made some further changes to allow me to run the compiled e2e.test binary against an OpenShift cluster.
* The Vault helm chart is now installed with `--set global.openshift=true` if you supply the environment variable `E2E_OPENSHIFT=true, which is the [recommended way to install the Vault Helm chart on OpenShift](https://developer.hashicorp.com/vault/tutorials/kubernetes/kubernetes-openshift) and alters various deployment settings to work on OpenShift.
* I upgraded the [Vault helm chart to the latest version 0.25](https://github.com/hashicorp/vault-helm/releases/tag/v0.25.0)
(The [docker images  used by that chart](https://github.com/hashicorp/vault-helm/blob/v0.25.0/values.yaml#L375-L379) are the same) 
* Use the …
=> Openshift E2E test compatibility

pkg/issuer/venafi/client/request.go
In https://github.com/cert-manager/cert-manager/issues/6397, I showed that cert-manager 1.11, 1.12, and 1.13 still get stuck when retrying renewing a certificate after the error "This certificate has encountered errors. Fix any errors, and then click Retry". I used `dlv` and pin-pointed where the issue originated from:
The line in question is the following:
```go
tppConnector, isTPP := v.vcertClient.(*tpp.Connector)
```
The variable `isTPP` is always false since the concrete value is actually an instrumentedConnector. This problem appeared because we aren’t testing this code path.
I have tested the fix locally with both a TPP Venafi issuer and with a Venafi Cloud issuer. All seems well.
**Release note:**
```release-note
The Venafi issuer now properly resets the certificate and should no …
```
=> Venafi issuer: ResetCertificate wasn't working

make/licenses.mk
In https://github.com/cert-manager/cert-manager/pull/6427, @SgtCoDFish noticed that the go-licenses command produces a different result than CI.
The difference originates from the difference between the dependencies for the linux and darwin targets.
To make the scripts work both on linux and macos, I updated the make files to specifically specify what target we are generating the licenses for.
/kind cleanup
```release-note
NONE
```
=> Fix the 'make update-licenses' command on macos

deploy/charts/cert-manager/templates/cainjector-config.yaml, deploy/charts/cert-manager/templates/controller-config.yaml, deploy/charts/cert-manager/templates/webhook-config.yaml
A couple of weeks ago I made two PRs (https://github.com/cert-manager/cert-manager/pull/6360 and https://github.com/cert-manager/cert-manager/pull/6357) that improved the behavior of the Helm Chart. The goal was to disable the creation of the Controller and Webhook ConfigMaps resp. if the ```.Values.config``` and the ```.Values.webhook.config``` sections were not defined.
In this PRs, I also changed the way we check that some required values in these sections are defined, but I actually introduced a bug. The current code is :
```{{- required ".Values.xyz must be set !" .Values.xyz -}}```
With this code, the values that are checked are actually templated at the top of the ConfigMap which can result in some issues.
The goal of this PR is to fix this bug by doing this :
```{{- $_ := …
```
=> fix(helm): templating of required value in controller and webhook configmaps

make/e2e-setup.mk
Upgrading to v0.4.0 of sample-external-issuer. This new minor version fixes some CVE vulnerabilities:
* https://github.com/cert-manager/sample-external-issuer/pull/44
* https://github.com/cert-manager/sample-external-issuer/releases/tag/v0.4.0
The digest comparison in the Makefile didn't work for me, so I checked the digests manually as follows:
```bash
$ crane digest --platform=linux/amd64 ghcr.io/cert-manager/sample-external-issuer/controller:v0.4.0
sha256:964b378fe0dda7fc38ce3f211c3b24c780e44cef13c39d3206de985bad67f294
$ crane digest --platform=linux/arm64 ghcr.io/cert-manager/sample-external-issuer/controller:v0.4.0
sha256:bdff00089ec7581c0d12414ce5ad1c6ccf5b6cacbfb0b0804fefe5043a1cb849
```
/kind cleanup
```release-note
NONE
```
=> Use sample-external-issuer v0.4.0

make/e2e-setup.mk
The checksum validation for Docker images is broken because we use `crane manifest repo:tag@sha256:digest` which gets the file by checksum (the checksum from the makefile) rather than by tag....so the checksum always matches.
But the image is then pulled by reference to its tag, so although the local image on the filesystem will be the right version,
we won't detect if someone has pushed a different image to the registry using the same tag.
The problem is demonstrated in this PR follows:
1. [Updated only the semver **tag** of the ingress-nginx image and Helm chart](https://github.com/cert-manager/cert-manager/pull/6440/commits/ecada9c30f8612614793fa81e3f27b1546bb3bbb). **Did not** update the sha256 sum of the images.
2. Expected the build to fail because of a checksum validation. [But it …
=> Fix image checksum validation and upgrade ingress NGINX to demonstrate the problem

hack/latest-kind-images.sh, make/e2e-setup.mk, make/kind_images.sh
In https://github.com/cert-manager/cert-manager/pull/6440 I fixed a problem with the remote image tag to digest check
when downloading single-arch images for the components that we install in our e2e cluster.
But I made the mistake of assuming that the kind node images were also pinned using the digest of the single-arch image,
and removed the special case Make rule which we had previously used for those.
Here I've fixed the multi-arch digest for the 1.28 kind node image, to match the digest in the Kind 0.20.0 release notes:
* https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0
And i've resurrected the special case Make rule for downloading that image, albeit without the digest check.
(I've tried to explain why the digest check is not appropriate in the comments above the rule) …
=> Fix kindest image digests

LICENSES, cmd/controller/LICENSES, cmd/controller/go.mod, cmd/controller/go.sum, cmd/ctl/LICENSES, cmd/ctl/go.mod, cmd/ctl/go.sum, cmd/webhook/LICENSES, cmd/webhook/go.mod, cmd/webhook/go.sum, go.mod, go.sum, test/integration/LICENSES, test/integration/go.mod, test/integration/go.sum
Bump gRPC library version to fix CVE alert
/kind cleanup
```release-note
NONE
```
=> Bump gRPC library version to fix CVE alert

make/e2e-setup.mk
Run the [periodic best-practice tests](https://github.com/cert-manager/testing/blob/01d89492c1525be852e59ad726010c8f96f6a579/config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml#L606) using the latest content from: 
* https://cert-manager.io/docs/installation/best-practice/#best-practice-helm-chart-values
The changes are are listed here:
* https://github.com/cert-manager/website/commits/master/public/docs/installation/best-practice/values.best-practice.yaml
I ran the best practice E2E tests and all seems ok:
* https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/pr-logs/pull/cert-manager_cert-manager/6452/pull-cert-manager-master-e2e-v1-28-bestpractice-install/1717898613478133760
/kind cleanup
```release-note
NONE
```
=> Use latest version of the best-practice Helm values

deploy/charts/cert-manager/values.yaml, make/config/kyverno/kustomization.yaml, make/config/kyverno/policy.yaml
I wanted to verify whether any of the components log to the /tmp filesystem, as reported in:
* https://github.com/cert-manager/cert-manager/issues/5580
...all the E2E tests pass when readOnlyRootFilesystem is enabled, so I assume that the problem reported in that issue was due to a bug or legacy behaviour of an older version of the logging libraries, which is now fixed.
xref: https://github.com/cert-manager/cert-manager/issues/5580
1. 9dfb7c3ecf578aac02373d1ec24616b2c58211de: Added the [Kyverno Require Read-Only Root Filesystem policy](https://kyverno.io/policies/best-practices/require-ro-rootfs/require-ro-rootfs/)
2. best practice E2E tests fail: https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/pr-logs/pull/cert-manager_cert-manager/6453/pull-cert-manager-master-e2e-v1-28-bestp …
=> Enable readOnlyRootFilesystem by default

deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/values.yaml
I want to enable the SSA feature gate for cainjector, ref. https://cert-manager.io/docs/cli/cainjector/. And while cert-manager controller and webhook allow feature gates to be configured in the Helm chart, this seems to be missing from cainjector.
feature
```release-note
NONE
```
=> feat(helm): allow configuration of cainjector feature gates

deploy/charts/cert-manager/values.yaml
In https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1698746453367439 @hawksight and I both mis-interpreted the presence of a commented out `runAsNonRoot: true` in the values.yaml, to mean that this was not already the default.
But `runAsNonRoot` is already set to true in the *Pod*SecurityContext, so there isn't really any reason to set it at the Container SecurityContext too.
Having it in the example values.yaml file gives the misleading impression that runAsNonRoot is not the default.
* https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#podsecuritycontext-v1-core
We already verify this using Kyverno, in 
https://github.com/cert-manager/cert-manager/blob/32418051c3595de90e36ac1ed0413158d275f62a/make/config/kyverno/policy.yaml#L564-L617
/kind cleanup
```release-note
NONE …
```
=> Remove redundant / misleading runAsNonRoot examples from values.yaml

cmd/cainjector/LICENSES, cmd/cainjector/app/controller.go, cmd/cainjector/go.mod, cmd/cainjector/go.sum
Instead of adding a new errgroup, we should just let controller-runtime manage all goroutines for the cainjector.
/kind cleanup
```release-note
NONE
```
=> cainjector: Use controller-runtime manager to manage goroutine instead of errorgroup.

test/e2e/suite/issuers/ca/fixtures.go
Fixes #6476
Changes from the original:
1. Simplified subjects a bit
2. Changed to P-256
3. Made the root last 100 years, the first intermediate 99 years, and the second intermediate 98 years
4. Added instructions on regenerating and the dumped version of each cert for review purposes
/kind bug
```release-note
NONE
```
=> Regenerate hardcoded certs

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/values.yaml
@maelvls I'm sure that I saw you suggest this change on Slack or in a GitHub issue, but I can't find the reference now.
Was it you and is this what you meant?
> Users sometimes report that the connection between the K8S API server and the cert-manager webhook server times out.
> 
> But the error message is often only "context deadline exceeded", which doesn't help the user know what phase of the HTTPS connection timed out.
> 
> It could be during DNS resolution, TCP connection, TLS negotiation, HTTP channel negotiation, or slow HTTP response from the webhook server.
> 
> So this change increases the context timeout to its maximum value so that the underlying timeout error message has more chance of being returned to the end user.
```release-note
Increase the default webhook timeout to its …
```
=> Increase the default webhook timeout to its maximum value of 30 seconds

deploy/charts/cert-manager/templates/podmonitor.yaml, deploy/charts/cert-manager/templates/service.yaml, deploy/charts/cert-manager/values.yaml
**Pull Request Motivation**
In the current chart, users are limited to using ServiceMonitor for metric scraping,
This PR aims to add support for PodMonitor, providing an alternative to ServiceMonitor and conserving ClusterIP services.
Kind
feature
**Changes**
Added support for configuring PodMonitor in the Helm Chart.
Implemented conditional logic to ensure PodMonitor and ServiceMonitor are mutually exclusive to avoid configuration errors.
**Testing**
Deployed the Helm chart with PodMonitor enabled and verified metrics scraping.
Deployed the Helm chart with ServiceMonitor enabled to ensure no regressions.
Deployed the Helm chart with both enabled to confirm that a configuration error is correctly thrown.
**Release Note**
feat(helm): Added support for PodMonitor to conserve ClusterIP …
=> feat(helm) Add support for PodMonitor

deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, internal/apis/certmanager/types_issuer.go, internal/apis/certmanager/v1/zz_generated.conversion.go, internal/apis/certmanager/v1alpha2/types_issuer.go, internal/apis/certmanager/v1alpha2/zz_generated.conversion.go, internal/apis/certmanager/v1alpha2/zz_generated.deepcopy.go, internal/apis/certmanager/v1alpha3/types_issuer.go, internal/apis/certmanager/v1alpha3/zz_generated.conversion.go, internal/apis/certmanager/v1alpha3/zz_generated.deepcopy.go, internal/apis/certmanager/v1beta1/types_issuer.go, internal/apis/certmanager/v1beta1/zz_generated.conversion.go, internal/apis/certmanager/v1beta1/zz_generated.deepcopy.go, internal/apis/certmanager/validation/issuer.go, internal/apis/certmanager/validation/issuer_test.go, internal/apis/certmanager/zz_generated.deepcopy.go, pkg/apis/certmanager/v1/types_issuer.go, pkg/apis/certmanager/v1/zz_generated.deepcopy.go, pkg/controller/certificaterequests/ca/ca.go, pkg/controller/certificaterequests/ca/ca_test.go, pkg/controller/certificatesigningrequests/ca/ca.go, pkg/controller/certificatesigningrequests/ca/ca_test.go
Adds option to specify x509v3 Authority Information Accessors extension CA Issuers URLs on the CA issuer.
Resolves #6485 
feature
```release-note
Added the option to specify the  x509v3 Authority Information Accessors extension CA Issuers URLs for certificates issued by the CA issuer.
```
=> Add x509 v3 CA Issuers Extension

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/values.yaml
So that if it fails, users can know exactly what caused the failure.
Fixes: https://github.com/cert-manager/cert-manager/issues/6482
* https://github.com/cert-manager/cert-manager/issues/6482
/kind cleanup
```release-note
Enabled verbose logging in startupapicheck by default, so that if it fails, users can know exactly what caused the failure.
```
The difference is clear if you run `cmctl check api` from the command line after scaling the cert-manager webhook to 0.
```sh
$ cmctl check api --wait=5m
Not ready: the cert-manager webhook deployment is not ready yet
Not ready: the cert-manager webhook deployment is not ready yet
Not ready: the cert-manager webhook deployment is not ready yet
Not ready: the cert-manager webhook deployment is not ready yet
```
vs
```sh
$ cmctl check api …
```
=> Enable verbose logging in startupapicheck by default

README.md
I filled out the form on the CII site and they gave us a badge!
This is part of the work towards graduation - this is a required step listed in:
https://github.com/cncf/toc/blob/main/process/graduation_criteria.md
/kind feature
```release-note
Adds cert-manager's new core infrastructure initiative badge! See more details on https://www.bestpractices.dev/projects/8079
```
=> Add Core Infrastructure Initiative Best Practices badge

pkg/controller/certificate-shim/sync.go, pkg/controller/certificate-shim/sync_test.go
If listeners that do not support TLS are processed, they will raise warnings in the next steps (e.g. about empty TLS blocks, which are not supported for HTTP listeners).
See #6197
/kind bug
```release-note
Listeners that do not support TLS on Gateway resources will now not raise `BadConfig` warnings anymore
```
=> Do not process Gateway listeners that do not support TLS

LICENSES, cmd/controller/LICENSES, cmd/controller/go.mod, cmd/controller/go.sum, go.mod, go.sum, test/e2e/LICENSES, test/e2e/go.mod, test/e2e/go.sum
Fixes a CVE.
/kind cleanup
```release-note
NONE
```
=> Bump the go-jose dependency

cmd/cainjector/app/controller.go, cmd/controller/app/controller.go, pkg/issuer/acme/http/solver/solver.go, pkg/webhook/server/server.go
A recent security audit has shown that there are some http servers in cert-manager where the ReadHeaderTimeout setting is not set. 
The risk is low but if we add sensible default ReadHeaderTimeout values it will mitigate the risk of "slowloris" style DDOS attacks.
I have used the same `32s` values as are used in the Kubernetes api-server and which were then adopted by controller-runtime. 
Kyverno uses slightly lower `30s` values but I can't find any documentation explaining how that value was chosen.
```sh
$ time telnet 127.0.0.1 6060
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Connection closed by foreign host.
real    0m32.013s
user    0m0.005s
sys     0m0.000s
$ time telnet 127.0.0.1 9402
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'. …
```
=> Mitigate potential Slowloris attacks by setting ReadHeaderTimeout in all http.Server instances

cmd/cainjector/app/start.go, cmd/controller/app/controller.go, pkg/issuer/acme/http/solver/solver.go, pkg/webhook/server/server.go
This is a **manual** cherry-pick of https://github.com/cert-manager/cert-manager/pull/6534
The automated cherry-pick failed:
* https://github.com/cert-manager/cert-manager/pull/6534#issuecomment-1845259559
You can kind of see the manual changes I had to make by using `git range-diff`:
> git range-diff 8bed16685845428af3989753bf16780f43e5829c^- d080ceca9426e1df9471b4a062f186a4b57553a2^-
To verify that this version of the patch fixes all the same problems you can run  the following commands:
```
make go-workspace
golangci-lint run --exclude 'G(101|107|204|306|402|404|501|505|601)' --tests=false --disable-all --enable gosec -- $(find . -type f -name 'go.mod' -printf '%h/... ')
```
```release-note
Mitigate potential Slowloris attacks by setting ReadHeaderTimeout in all http.Server instances …
```
=> [release-1.13] Mitigate potential Slowloris attacks by setting ReadHeaderTimeout in all http.Server instances

cmd/cainjector/app/start.go, cmd/controller/app/controller.go, pkg/issuer/acme/http/solver/solver.go, pkg/webhook/server/server.go
This is a **manual** cherry-pick of #6538 because the automated cherry-pick failed:
* https://github.com/cert-manager/cert-manager/pull/6538#issuecomment-1845843247
You can see that the patch is the same but the context is different using `git range-diff`:
> git range-diff d080ceca9426e1df9471b4a062f186a4b57553a2^- cad118954291c041c1f601ef198cfcce0d7c3784^-
```release-note
Mitigate potential Slowloris attacks by setting ReadHeaderTimeout in all http.Server instances
```
/kind bug
=> [release-1.12] Mitigate potential Slowloris attacks by setting ReadHeaderTimeout in all http.Server instances

make/tools.mk
See https://go.dev/doc/devel/release#go1.20
- go1.20.11 (released 2023-11-07) includes security fixes to the path/filepath package, as well as bug fixes to the linker and the net/http package.
- go1.20.12 (released 2023-12-05) includes security fixes to the go command, and the net/http and path/filepath packages, as well as bug fixes to the compiler and the go command.
```release-note
cert-manager is now built with Go 1.20.12
```
/kind feature
Before:
```sh
$ make vendor-go
cd _bin/tools/ && ln -f -s ../downloaded/tools/_go-1.20.10-linux-amd64/goroot .
cd _bin/tools/ && ln -f -s ../downloaded/tools/_go-1.20.10-linux-amd64/goroot/bin/go .
$ go version
go version go1.20.10 linux/amd64
$ govulncheck --version
Go: go1.20.10
Scanner: govulncheck@v1.0.1
DB: https://vuln.go.dev
DB updated: …
```
=> [release-1.13] Bump to go 1.20.12

make/tools.mk
See https://go.dev/doc/devel/release#go1.20
- go1.20.11 (released 2023-11-07) includes security fixes to the path/filepath package, as well as bug fixes to the linker and the net/http package.
- go1.20.12 (released 2023-12-05) includes security fixes to the go command, and the net/http and path/filepath packages, as well as bug fixes to the compiler and the go command.
```release-note
cert-manager is now built with Go 1.20.12
```
/kind feature
Before:
```sh
$ make vendor-go
curl --silent --show-error --fail --location --retry 10 --retry-connrefused https://go.dev/dl/go1.20.10.linux-amd64.tar.gz -o _bin/downloaded/tools/go-1.20.10-linux-amd64.tar.gz
rm -rf _bin/downloaded/tools/_go-1.20.10-linux-amd64/goroot
tar xzf _bin/downloaded/tools/go-1.20.10-linux-amd64.tar.gz -C …
```
=> [release-1.12] Bump to go 1.20.12

.github/workflows/golangci-lint.yml, .golangci.ci.yaml
Run golangci-lint as a GitHub action, to provide fast feedback to a PR author about various common mistakes that are found in their code.
Initially we enable only on linter and check only G112.
The idea is that other checks and linters can be enabled one-by-one in separate PRs.
Each PR will enable only one new check and fix any offending code.
This way, the PRs are easy to review 
and easy to cherry-pick into previous release branches if the fixes are deemed important enough.
Eventually, when all standard linters and checks have been enabled, the non-standard file `.golangci-lint.*ci*.yaml` can be renamed to `.golangci-lint.yaml` so that it developers can simply run `golangci-lint run .` locally (or via their editor / lsp-server) and get feedback before even creating a PR>
The advantages …
=> Add the golangci-lint GitHub action

make/ci.mk, make/tools.mk
This lets users locally run the same commands that are run in CI without needing to open a browser to find out how to install golangci-lint.
It also removes the need (when running locally) to install `gh` or copy+paste the actual command from the github actions definition.
My personal preference would be to replace the github action entirely with a prow job for many reasons, but this PR doesn't do that. It also intentionally doesn't add this to `ci-presubmit` since golangci-lint really needs a cache configured.
I've not made any efforts towards changing how we run this job in CI in this PR because that's a bigger change. In this PR, I just want to be able to run the tool locally to debug what went wrong, without having to install other tools globally.
/kind cleanup
```release-note
NONE …
```
=> Add target + installation for golangci-lint

.golangci.ci.yaml, cmd/ctl/pkg/renew/renew.go, cmd/ctl/pkg/status/certificate/certificate.go, cmd/ctl/pkg/upgrade/migrateapiversion/migrator.go, internal/apis/certmanager/validation/certificate_test.go, internal/apis/certmanager/validation/issuer.go, pkg/controller/acmeorders/util.go, pkg/controller/certificate-shim/helper_test.go, pkg/issuer/vault/setup_test.go, pkg/util/useragent_test.go, pkg/webhook/handlers/conversion_test.go, test/e2e/suite/certificates/duplicatesecretname.go, test/e2e/suite/issuers/acme/certificate/webhook.go, test/integration/certificates/generates_new_private_key_per_request_test.go, test/integration/ctl/ctl_status_certificate_test.go
* Enables the Gosec G601 check in golangci-lint
* Reconfigures golangci-lint to show all issues in all files (rather than limiting the results)
* Reconfigures golangci-lint to also check `_test.go` files
* Makes a local copy of the loop var where necessary.
* Annotates the failed code where the failure is a false positive.
G601 is described in https://github.com/securego/gosec#available-rules as follows:
> G601: Implicit memory aliasing of items from a range statement
This gosec check was proposed in https://github.com/securego/gosec/issues/438 and implemented in https://github.com/securego/gosec/pull/443.
* https://github.com/securego/gosec/issues/438
* https://github.com/securego/gosec/pull/443
It is intended to identify instances of the problem described in [The Go Common Mistakes …
=> Fix gosec G601: Implicit memory aliasing of items from a range statement

internal/apis/certmanager/validation/certificate.go, internal/apis/certmanager/validation/certificate_test.go
Fixes an error message when an invalid key algorithm is provided. Also adds a unit test to Ed25519.
Fix https://github.com/cert-manager/cert-manager/issues/6474
bug
```release-note
Fixed a webhook validation error message when the key algorithm was invalid.
```
=> Fix validation webhook error message

pkg/logs/logs.go
These flags were deprecated as part of the 1.13 release.
Now, I would like to hide them so the `--help` output is a lot cleaner.
/kind cleanup
```release-note
NONE
```
=> Hide deprecated CLI flags

deploy/charts/cert-manager/README.template.md
Noticed this today while trying to install cert manager on an old cluster
flux message:
cheers
documentation
```release-note
NONE
```
=> docs: declare updated kube version in artifact hub doc

.golangci.ci.yaml, pkg/issuer/acme/dns/rfc2136/tsig.go, pkg/issuer/acme/dns/rfc2136/tsig_test.go
* Enabled the G505 check
```sh
$ golangci-lint run --config .golangci.ci.yaml -- $(find . -type f -name 'go.mod' -not -path './_bin/*' -printf '%h/... ')
pkg/issuer/acme/dns/rfc2136/tsig.go:25:2: G505: Blocklisted import crypto/sha1: weak cryptographic primitive (gosec)
"crypto/sha1"
^
pkg/issuer/acme/dns/rfc2136/tsig_test.go:25:2: G505: Blocklisted import crypto/sha1: weak cryptographic primitive (gosec)
"crypto/sha1"
^
```
-- https://github.com/cert-manager/cert-manager/actions/runs/7384493583?pr=6579
* Those two imports are in TSIG code which we [copied from github.com/miekg/dns](https://github.com/cert-manager/cert-manager/pull/4958) and which is used as part of the  [DNS01 DNS UPDATE mechanism in the ACME issuer](https://cert-manager.io/docs/configuration/acme/dns01/rfc2136/). 
* …
=> Enable gosec G505

.golangci.ci.yaml, pkg/issuer/acme/dns/rfc2136/tsig.go, pkg/issuer/acme/dns/rfc2136/tsig_test.go
```sh
$ make verify-golangci-lint
...
pkg/issuer/acme/dns/rfc2136/tsig.go:24:2: G501: Blocklisted import crypto/md5: weak cryptographic primitive (gosec)
"crypto/md5"
^
pkg/issuer/acme/dns/rfc2136/tsig_test.go:24:2: G501: Blocklisted import crypto/md5: weak cryptographic primitive (gosec)
"crypto/md5"
^
```
-- https://github.com/cert-manager/cert-manager/actions/runs/7385074055?pr=6581
* Those two imports are in TSIG code which we [copied from github.com/miekg/dns](https://github.com/cert-manager/cert-manager/pull/4958) and which is used as part of the  [DNS01 DNS UPDATE mechanism in the ACME issuer](https://cert-manager.io/docs/configuration/acme/dns01/rfc2136/). 
https://github.com/cert-manager/cert-manager/blob/833311d278af13e222e55f2507297f37d4e902b2/internal/apis/certmanager/validatio …
=> Enable gosec G501: Blocklisted import crypto/md5

.golangci.ci.yaml, pkg/controller/test/util.go, pkg/util/util.go
```sh
$ make verify-golangci-lint
...
pkg/util/util.go:171:22: G404: Use of weak random number generator (math/rand instead of crypto/rand) (gosec)
b[i] = letterRunes[rand.Intn(len(letterRunes))]
^
pkg/controller/test/util.go:36:22: G404: Use of weak random number generator (math/rand instead of crypto/rand) (gosec)
b[i] = letterBytes[rand.Intn(len(letterBytes))]
```
-- https://github.com/cert-manager/cert-manager/actions/runs/7385479927?pr=6582
* [`pkg/util.RandStringRunes`](https://github.com/cert-manager/cert-manager/blob/47d720be3960ecd50a77c9d50af5b39406d0c56d/pkg/util/util.go#L168C11-L174) was introduced in 7d8683bd169bdf2bc8a521fc9bdf6fb556213007 to generate a suffix for the HTTP01 solver Pod. But the solver Pod now uses GenerateName instead. …
=> Enable gosec 404: Use of weak random number generator

pkg/api/util/names_test.go, pkg/controller/acmechallenges/scheduler/scheduler_test.go, pkg/controller/test/context_builder.go, pkg/controller/test/util.go, pkg/util/util.go, test/e2e/framework/addon/vault/setup.go, test/e2e/suite/conformance/certificates/tests.go, test/e2e/suite/conformance/certificatesigningrequests/tests.go, test/e2e/suite/conformance/certificatesigningrequests/vault/kubernetes.go, test/e2e/suite/conformance/certificatesigningrequests/venafi/tpp.go, test/e2e/suite/issuers/ca/clusterissuer.go, test/e2e/suite/issuers/vault/issuer.go, test/e2e/suite/issuers/venafi/tpp/certificate.go, test/e2e/suite/issuers/venafi/tpp/certificaterequest.go, test/e2e/util/domains.go, test/integration/versionchecker/getpodfromtemplate_test.go
In https://github.com/cert-manager/cert-manager/pull/6582 @inteon  and I discussed consolidating the two near identical functions: `RandStringBytes` and `RandStringRunes`.
I found a function with the same intent and signature in https://pkg.go.dev/k8s.io/apimachinery@v0.29.0/pkg/util/rand#String so I have decided to deprecate those two functions and replace all their uses with https://pkg.go.dev/k8s.io/apimachinery@v0.29.0/pkg/util/rand#String instead.
The https://pkg.go.dev/k8s.io/apimachinery@v0.29.0/pkg/util/rand#String version is better tested and benchmarked and also avoids any embarrassing strings by omitting vowels.
It also avoids using the deprecated `math/rand.Seed` function.
In a followup PR #6586 I will enable checks to ensure that we do not call deprecated functions in our …
=> Deprecate RandStringBytes and RandStringRunes

.golangci.ci.yaml, cmd/controller/app/controller.go, cmd/controller/app/options/options.go, cmd/controller/app/options/options_test.go, cmd/ctl/pkg/upgrade/migrateapiversion/migrator.go, internal/plugin/plugins.go, internal/webhook/webhook.go, pkg/controller/acmeorders/sync.go, pkg/util/pki/match.go, pkg/webhook/admission/handler.go
> SA1019: sets.String is deprecated: use generic Set instead. new ways: 
> s1 := Set[string]{} 
> s2 := New[string]() 
-- https://github.com/cert-manager/cert-manager/actions/runs/7388630928?pr=6586
I considered using https://github.com/kubernetes/utils/blob/master/set/set.go instead, but decided not, because I wanted to keep the changeset small and  I didn't want to introduce a new dependency. 
There is some discussion about whether it will eventually replace the apimachinery sets package:
* https://github.com/kubernetes/kubernetes/issues/117673#issuecomment-1533488546
* https://github.com/kubernetes/utils/pull/294
/kind cleanup
```release-note
Use the new generic `sets.Set` type in place of the deprecated `sets.String`.
```
=> Replace calls to deprecated sets.String functions

deploy/crds/crd-certificates.yaml, internal/apis/certmanager/types_certificate.go, internal/apis/certmanager/v1/zz_generated.conversion.go, internal/apis/certmanager/v1alpha2/types_certificate.go, internal/apis/certmanager/v1alpha2/zz_generated.conversion.go, internal/apis/certmanager/v1alpha3/types_certificate.go, internal/apis/certmanager/v1alpha3/zz_generated.conversion.go, internal/apis/certmanager/v1beta1/types_certificate.go, internal/apis/certmanager/v1beta1/zz_generated.conversion.go, pkg/apis/certmanager/v1/types_certificate.go, pkg/controller/certificates/issuing/internal/keystore.go, pkg/controller/certificates/issuing/internal/keystore_test.go, pkg/controller/certificates/issuing/internal/secret.go
(resolves #5957, #6523)
This PR adds a new field .spec.keystores.pkcs12.algorithm to allow specifying encryption and MAC algorithms for PKCS#12 keystores, enhancing compatibility with OpenSSL 3 and keep maintaining support for legacy systems.
/kind feature 
```release-note
New option .spec.keystores.pkcs12.algorithms to specify encryption and MAC algorithms for PKCS#12 keystores. Fixes issues #5957 and #6523.
```
=> New option to specify encryption and MAC algorithms for PKCS#12 keystores.

deploy/crds/crd-certificates.yaml, internal/apis/certmanager/types_certificate.go, internal/apis/certmanager/v1alpha2/types_certificate.go, internal/apis/certmanager/v1alpha3/types_certificate.go, internal/apis/certmanager/v1beta1/types_certificate.go, internal/apis/certmanager/validation/certificate.go, internal/apis/certmanager/validation/certificate_test.go, internal/controller/feature/features.go, internal/webhook/feature/features.go, make/e2e-setup.mk, pkg/apis/certmanager/v1/types_certificate.go, pkg/controller/certificates/requestmanager/requestmanager_controller.go, pkg/util/pki/csr.go, pkg/util/pki/csr_test.go
We called the feature gate that we introduced in https://github.com/cert-manager/cert-manager/pull/6542 "UseCertificateRequestNameConstraints" to match the name we used for the `UseCertificateRequestBasicConstraints` feature gate.
However, on second thought, we realised that those two feature gates differ quite substantially in scope.
`UseCertificateRequestBasicConstraints` only enables/ disables encoding the Basic Constraints in the CSR, while "UseCertificateRequestNameConstraints" fully disables the Name Constraints (even defining a Certificate with such an option is disallowed by the webhook).
For that reason, I propose to change the name of the feature gate to NameConstraints.
We can still do this because we haven't released a version with this feature gate yet.
/kind cleanup …
=> Rename UseCertificateRequestNameConstraints to NameConstraints

cmd/cainjector/LICENSES, cmd/controller/LICENSES, cmd/controller/go.mod, cmd/controller/go.sum, cmd/ctl/LICENSES, go.mod, pkg/controller/certificaterequests/acme/acme.go, pkg/controller/certificaterequests/util/reporter_test.go, pkg/controller/certificatesigningrequests/acme/acme.go, pkg/issuer/acme/setup_test.go, pkg/issuer/venafi/setup_test.go, pkg/util/pki/certificatetemplate.go, pkg/util/util.go, test/e2e/LICENSES, test/e2e/framework/helper/certificaterequests.go, test/e2e/framework/helper/validation/certificates/certificates.go, test/e2e/framework/helper/validation/certificatesigningrequests/certificatesigningrequests.go, test/e2e/go.mod
This PR replaces a lot of our util functions with functions provided by the new upstream slices go library.
/kind cleanup
```release-note
NONE
```
=> Use slices go library

.golangci.ci.yaml, pkg/healthz/healthz_test.go, pkg/issuer/acme/dns/util/wait.go
> SA1019: "io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided by package [io] or package [os], and those implementations should be preferred in new code. See the specific function documentation for details.
-- https://go.dev/doc/go1.16#ioutil
- https://github.com/cert-manager/cert-manager/actions/runs/7411458268?pr=6598
/kind cleanup
```release-note
NONE
```
=> Use io instead of deprecated ioutil package

.golangci.ci.yaml, internal/apis/certmanager/validation/issuer.go
- The KubeCtl deprecation warning that I hid in an earlier PR seems to have gone away, perhaps after we updated the dependencies.
- The eab.KeyAlgorithm deprecation warning is a false positive so I have ignored it.
/kind cleanup
```release-note
NONE
```
=> Ignore warnings about deprecated eab.KeyAlgorithm field

test/e2e/framework/helper/validation/certificates/certificates.go
Replaces a custom utils function with `slices.Contains`.
/kind cleanup
```release-note
NONE
```
=> Replace util contains function with slices.Contains

pkg/util/pki/csr.go
Adds a deprecation warning because the function is currently only used by other deprecated functions.
/kind cleanup
```release-note
NONE
```
=> Deprecate URLsFromStrings which is only used in other deprecated functions

pkg/issuer/acme/dns/cloudflare/cloudflare.go, pkg/issuer/acme/http/http.go
Limit the size of the response body read from http requests performed by cert-manager. 
```release-note
NONE
```
=> feat: limit the size of the body read back from http requests

make/release.mk
If you open the "staged" cert-manager-server archive (bundle), it doesn't contain the startupapicheck.
That's at least part of the reason why that image didn't get published to quay.io.
* https://console.cloud.google.com/storage/browser/_details/cert-manager-release/stage/gcb/release/v1.14.0-alpha.0/cert-manager-server-linux-amd64.tar.gz;tab=live_object?project=cert-manager-release
I've added the image to the server bundle in this PR, so that when we do the next release, it will be automatically extracted and pushed by cmrel:
https://github.com/cert-manager/release/blob/e778ffcf93a9660a0679b269f6a240f002e5a2bd/cmd/cmrel/cmd/gcb_publish.go#L487-L497
https://github.com/cert-manager/release/blob/e778ffcf93a9660a0679b269f6a240f002e5a2bd/pkg/release/unpacker.go#L115-L122 …
=> Add startupapicheck image to the server bundle of `make release`

deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/values.yaml
I want to clean up old replica sets so that these don't appear in metrics, OPA violations, ArgoCD UI and so on.
Therefore I want to overwrite the Kubernetes default revision history limit. 
See [Kubernetes Clean up Policy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy).
feature
```release-note
Helm Chart: allow changing the default deployment revisionHistoryLimit
```
=> feat: allow changing the default Deployment revisionHistoryLimit

.golangci.ci.yaml, test/acme/fixture.go, test/acme/util.go
> test/acme/util.go:65:16: SA1019: f.environment.ControlPlane.KubeCtl is deprecated: use AddUser & AuthenticatedUser.Kubectl instead. (staticcheck)
The deprecation was introduced in:
* https://github.com/kubernetes-sigs/controller-runtime/pull/1486
---
- Unhide the KubeCtl deprecation warning
- See the golangci-lint warning here: https://github.com/cert-manager/cert-manager/actions/runs/7490910752
- Use a dedicated Authenticated envtest user instead of the deprecated default user
```release-note
NONE
```
=> Stop using deprecated f.environment.ControlPlane.KubeCtl function 

make/tools.mk
/kind cleanup
```release-note
cert-manager is now built with Go 1.20.13
```
=> [release-1.12] bump go to latest patch version

make/tools.mk
/kind cleanup
```release-note
cert-manager is now built with Go 1.20.13
```
=> [release-1.13] bump go to latest patch version

make/tools.mk
No reason to not use the latest for a new release!
/kind cleanup
```release-note
cert-manager is now built with Go 1.21.6
```
=> Bump go to latest version

.golangci.ci.yaml, cmd/ctl/pkg/inspect/secret/util.go
> cmd/ctl/pkg/inspect/secret/util.go:111:14: SA1019: x509.ParseCRL has been deprecated since Go 1.19: Use ParseRevocationList instead. (staticcheck)
Deprecated in:
* https://github.com/golang/go/issues/50674
--- 
- Unhide the warning
- https://github.com/cert-manager/cert-manager/actions/runs/7491727797?pr=6631
- Use ParseRevocationList instead of deprecated x509.ParseCRL
/kind cleanup
```release-note
NONE
```
=> Use ParseRevocationList instead of deprecated x509.ParseCRL 

test/e2e/suite/certificates/othernamesan.go
Ensures that otherName Certificate e2e test only runs when the feature flag is turned on!
Fixes test running in periodics where we don't use feature flags
https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/logs/ci-cert-manager-master-e2e-v1-23-feature-gates-disabled/1745556152202039296
```release-note
NONE
```
=> Require feature gate in otherName SAN cert e2e

cmd/controller/go.mod, cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
This PR cmd/cmctl's go.mod to v1.14.0-alpha.1 as part of the release process.
```release-note
NONE
```
=> [Release v1.14.0-alpha.1] Update cmd/cmctl's go.mod to v1.14.0-alpha.1

deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml, deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml, deploy/charts/cert-manager/values.yaml
We have to run multiple independent namespace level cert-manager in our cluster. While this works fine in general, we are not able to restrict webhooks to certain namespaces. Currently all webhooks are proceeded, if multiple cert-managers are installed.
Expose the `spec.namespaceSelector` settings for validating and mutating webhooks, resolves the issue.
feature
```release-note
Support custom spec.namespaceSelector for webhooks
```
=> [helm] Support custom spec.namespaceSelector for webhooks

README.md
https://prow.build-infra.jetstack.net/badge.svg?jobs=ci-cert-manager-master-make-test
> :bookmark: Read more about [Badges in Prow](https://docs.prow.k8s.io/docs/jobs/#badges)
Fixes the grey "build: no results" build status badge in the README file
* https://github.com/cert-manager/cert-manager/blob/master/README.md
---
A trivial PR to try out the 1.29 E2E tests
* https://github.com/cert-manager/cert-manager/pull/6641
* https://github.com/cert-manager/testing/pull/957
---
/kind cleanup
```release-note
NONE
```
=> Fix broken build-status badge in README.md

test/e2e/suite/conformance/certificates/venaficloud/cloud.go
Skip the OtherNames conformance tests on Venafi  Cloud
Until such time as we configure the servers to allow us to use those fields.
And I reconfigured the Venafi TPP server to allow UPN SANS.
You can see how the conformance tests have been failing since the OtherName feature landed in master:
* https://github.com/cert-manager/cert-manager/pull/6404
* https://testgrid.k8s.io/cert-manager-periodics-master#ci-cert-manager-master-e2e-v1-28-issuers-venafi
And here in the original commit (e2bfa14) I deliberately commented out the fix, to show the errors:
* https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/pr-logs/pull/cert-manager_cert-manager/6648/pull-cert-manager-master-e2e-v1-28-issuers-venafi-cloud/1747622034134798336
```
request venafi certificate: vcert error: server error: …
```
=> Skip the OtherNames conformance tests on Venafi Cloud

Makefile, make/tools.mk
This will enable easy testing of different GOEXPERIMENT variables, such as `loopvar` to test the upcoming changes there.
Note that I've confirmed that this change is a no-op. The binaries we build are identical after this change.
I used the following patch to allow me to hardcode versions:
```patch
diff --git a/make/git.mk b/make/git.mk
index 27a523880..18a266b78 100644
--- a/make/git.mk
+++ b/make/git.mk
@@ -12,9 +12,9 @@
-RELEASE_VERSION := $(shell git describe --tags --match='v*' --abbrev=14)
+RELEASE_VERSION ?= $(shell git describe --tags --match='v*' --abbrev=14)
-GITCOMMIT := $(shell git rev-parse HEAD)
+GITCOMMIT ?= $(shell git rev-parse HEAD)
IS_TAGGED_RELEASE := $(shell git describe --exact-match HEAD >/dev/null 2>&1 && echo "true" || echo "false")
```
Then I ran the following on …
=> no-op: add GOEXPERIMENT var

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
This PR cmd/cmctl's go.mod to v1.14.0-beta.0 as part of the release process.
```release-note
NONE
```
=> [Release v1.14.0-beta.0] Update cmd/cmctl's go.mod to v1.14.0-beta.0

.golangci.ci.yaml, pkg/issuer/acme/dns/rfc2136/rfc2136.go
> pkg/issuer/acme/dns/rfc2136/rfc2136.go:130:2: SA1019: c.SingleInflight is deprecated: This is a no-op. Callers should implement their own in flight query caching if needed. See github.com/miekg/dns/issues/1449. (staticcheck)
>         c.SingleInflight = true
>         ^
* https://github.com/miekg/dns/issues/1449
* https://github.com/cert-manager/cert-manager/actions/runs/7671543590?pr=6669
@splashx set this field to true in https://github.com/cert-manager/cert-manager/pull/661:
* https://github.com/cert-manager/cert-manager/pull/661/files#diff-5d460d422bf99472fcf52c0d56acc002758aa3fdf3089d5e164ce6b41f931611R207
https://github.com/cert-manager/cert-manager/blob/f340d9afeb779cf4ed434f39a48c3316d1b15550/pkg/issuer/acme/dns/rfc2136/rfc2136.go#L130
And that PR was based on an earlier PR …
=> Stop using the deprecated SingleInflight field of miekg/dns

pkg/issuer/acme/dns/azuredns/azuredns.go, pkg/issuer/acme/dns/azuredns/azuredns_test.go
Similar to https://github.com/cert-manager/cert-manager/pull/5663, but for the new Azure SDK.
Fixes https://github.com/cert-manager/cert-manager/pull/5452#issuecomment-1914793219
/kind bug
```release-note
Make sure the Azure SDK error messages are stable.
```
=> Replace the azcore.ResponseError error message to make it stable across retries

pkg/issuer/acme/dns/azuredns/azuredns.go, pkg/issuer/acme/dns/azuredns/azuredns_test.go
In https://github.com/cert-manager/cert-manager/pull/5452#issuecomment-1914793219 @weisdd wrote:
> * Earlier, you asked whether "DisableInstanceDiscovery" should be set to `true` or `false`. - I think it's better to not use `DisableInstanceDiscovery: true` (like in the code now), better to stick to defaults. I haven't seen it being disabled in other projects.
So I've removed it.
The field is documented as follows: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#ClientAssertionCredentialOptions
> 	// DisableInstanceDiscovery should be set true only by applications authenticating in disconnected clouds, or
> 	// private clouds such as Azure Stack. It determines whether the credential requests Microsoft Entra instance metadata
> 	// from https://login.microsoft.com before …
=> Remove unnecessary Azure workload identity setting: DisableInstanceDiscovery: true

make/scan.mk
This trivy scan Makefile target was missing.
/kind cleanup
```release-note
NONE
```
=> Add Make target for trivy startupapicheck image scan

make/scan.mk
This is a **manual** cherry-pick of #6685.
(cherry picked from commit 3d406a087b5dae842f2bef5fbf64351d3c2575a0)
The automated cherry pick failed, due to a merge conflict:
* https://github.com/cert-manager/cert-manager/pull/6685#issuecomment-1918882775
```sh
$ make trivy-scan-startupapicheck
...
$ echo $?
0
$ make trivy-scan-ctl
...
$ echo $?
0
$ make trivy-scan-all
...
$ echo $?
0
```
/kind cleanup
```release-note
NONE
```
=> [release-1.14] Add Make target for trivy startupapicheck image scan

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
This PR cmd/cmctl's go.mod to v1.14.0 as part of the release process.
```release-note
NONE
```
=> [Release v1.14.0] Update cmd/cmctl's go.mod to v1.14.0

deploy/charts/cert-manager/values.yaml
Introduced in https://github.com/cert-manager/cert-manager/pull/6639
This was discovered during the release of cert-manager v1.14.0. See the summary [on Slack](https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1706723744656039?thread_ts=1706713005.073879&cid=CDEQJ0Q8M)
/kind bug
```release-note
Fix broken cainjector image value in Helm chart
```
=> Fix mistakenly changed cainjector image value

deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/values.yaml
Clarifies the prometheus.enabled = true, prometheus.servicemonitor.enabled = false prometheus.podmonitor.enabled = false option using a comment.
Also makes the logic for adding the annotations aware of the podmonitor option (we missed this in https://github.com/cert-manager/cert-manager/pull/6459).
/kind bug
```release-note
NONE
```
=> Clearify prometheus options and fix error in Helm chart

deploy/charts/cert-manager/README.template.md
Manual backport of #6695
/kind bug
```release-note
NONE
```
=> [release-1.14] fix helm readme

deploy/charts/cert-manager/templates/service.yaml, deploy/charts/cert-manager/values.yaml
In https://github.com/cert-manager/cert-manager/pull/6459 the prometheus service was made conditional both on `.Values.prometheus.enabled` and `.Values.prometheus.servicemonitor.enabled`. This however conflicts with the original intentions of the author of this Service: https://github.com/cert-manager/cert-manager/pull/1942#discussion_r309007374.
For that reason, we decided to still include the service when only `.Values.prometheus.enabled` is set.
We do however remove the service when `.Values.prometheus.podmonitor.enabled` is true and aim to add an extra option in the future to disable this service.
/kind bug
```release-note
NONE
```
=> Fix backwards incompatible change: include a prometheus service by default

cmd/ctl/pkg/factory/factory.go, cmd/ctl/pkg/install/helm/settings.go
Manual backport of https://github.com/cert-manager/cmctl/pull/14 and https://github.com/cert-manager/cmctl/pull/13.
Fixes two issues introduced in https://github.com/cert-manager/cert-manager/pull/6562:
1. We were mixing PreRun and PreRunE functions. However, cobra will not execute PreRun when PreRunE is set. (see https://github.com/cert-manager/cmctl/pull/14/files#r1467623809)
2. Flags were parsed and set on a global variable, which was shared across all sub-commands. This caused the namespace default overwrite for the install subcommand to apply to all commands. (see https://github.com/cert-manager/cert-manager/pull/6706/files#diff-6afa2ae6fa2d57e759177e96b60d01f7cc307f1ac5a197466476314b79524343L34-L37 and https://github.com/cert-manager/cert-manager/blob/241e64fd3019c23e7d087b732f4ebd40 …
=> [release-1.14] CLI flags parsing bugfix

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
This PR cmd/cmctl's go.mod to v1.14.1 as part of the release process.
```release-note
NONE
```
=> [Release v1.14.1] Update cmd/cmctl's go.mod to v1.14.1

deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml
Closes https://github.com/cert-manager/cert-manager/issues/6712
This trick was introduced in https://github.com/cert-manager/cert-manager/pull/5860 and https://github.com/cert-manager/cert-manager/pull/6248.
The root issue is that `{{ if "" }}` and `{{ if 0 }}` both return `false`. The trick was introduced to fix this issue.
The trick uses the `quote` function to differentiate between a empty string and 0 or "0".
The result from `quote` can be compared with `(quote "")` to detect empty strings.
However, the fix is not complete. In case the value is empty/ null, the result from quote is an empty string not `(quote "")`.
The final solution that fixes the original and the new problem is to:
1. use `(quote value)`: yields these strings `"0"`, `""` and an empty string
3. compare the strings …
=> Fix the Helm trick that we use to differentiate between 0 and an empty value

make/tools.mk
#6732 but for release-1.12
We'll have to make a plan about how to handle the go version here since 1.20 is EOL now that 1.22 is released, but that's a discussion for another place!
```release-note
Bump go to 1.20.14
```
=> [release-1.12] bump go to latest 1.20.x version

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
This PR cmd/cmctl's go.mod to v1.14.2 as part of the release process.
```release-note
NONE
```
=> [Release v1.14.2] Update cmd/cmctl's go.mod to v1.14.2

Makefile, make/README.md, make/ci.mk, make/containers.mk, make/e2e-setup.mk, make/git.mk, make/ko.mk, make/licenses.mk, make/manifests.mk, make/release.mk, make/scan.mk, make/server.mk, make/test.mk, make/tools.mk, make/util.mk
This change will make it easier to start using makefile modules in the future: https://github.com/cert-manager/makefile-modules/blob/main/modules/repository-base/base/Makefile#L80
/kind cleanup
```release-note
NONE
```
=> Rename `$(BINDIR)` to `$(bin_dir)` in preparation for makefile modules

design/20240122.scarf.md, design/template.md
A proposal to use Scarf as a gateway for binary and container image downloads.
=> Scarf Proposal

deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, internal/apis/certmanager/types_issuer.go, internal/apis/certmanager/v1/zz_generated.conversion.go, internal/apis/certmanager/v1alpha2/types_issuer.go, internal/apis/certmanager/v1alpha2/zz_generated.conversion.go, internal/apis/certmanager/v1alpha2/zz_generated.deepcopy.go, internal/apis/certmanager/v1alpha3/types_issuer.go, internal/apis/certmanager/v1alpha3/zz_generated.conversion.go, internal/apis/certmanager/v1alpha3/zz_generated.deepcopy.go, internal/apis/certmanager/v1beta1/types_issuer.go, internal/apis/certmanager/v1beta1/zz_generated.conversion.go, internal/apis/certmanager/v1beta1/zz_generated.deepcopy.go, internal/apis/certmanager/validation/issuer.go, internal/apis/certmanager/validation/issuer_test.go, internal/apis/certmanager/zz_generated.deepcopy.go, internal/vault/vault.go, internal/vault/vault_test.go, pkg/apis/certmanager/v1/types_issuer.go, pkg/apis/certmanager/v1/zz_generated.deepcopy.go, test/e2e/framework/addon/globals.go, test/e2e/framework/addon/vault/setup.go, test/e2e/framework/addon/vault/vault.go, test/e2e/suite/issuers/vault/mtls.go, test/unit/gen/issuer.go
Vault server can be configured to strictly enforce clients to present client certificates while connecting to the server in the HTTPs transport layer.
It is possible to configure Vault to use a client certificate to secure the transport layer ([tcp listener documentation](https://www.vaultproject.io/docs/configuration/listener/tcp#tcp-listener-examples)):
```
listener "tcp" {
tls_disable = false
tls_cert_file = "/vault/tls/server.crt"
tls_key_file = "/vault/tls/server.key"
tls_client_ca_file = "/vault/tls/ca.crt"
tls_require_and_verify_client_cert = true
}
```
When Vault is configured in the way above, there is no possibility to properly configure Vault Issuer/ClusterIssuer by using existing CRDs.
Fixes #6613
feature
```release-note
Add the ability to communicate with Vault via mTLS when …
```
=> feat: Add the ability to communicate with Vault via mTLS

internal/apis/certmanager/validation/certificate.go, internal/apis/certmanager/validation/certificate_test.go, pkg/util/pki/csr.go
Fixes https://github.com/cert-manager/cert-manager/issues/6504
Changes:
- Updated misleading error messages, and related test cases.
- Used unified commonName variable value.
/kind bug
```release-note
When using the literalSubject on a Certificate, the webhook validation for the common name now also points to the literalSubject.
```
=> Fix webhook validation bug for cert subjects

pkg/util/pki/parse_test.go, pkg/util/pki/subject.go
Quick fix for memory issues caused by github.com/go-asn1-ber/asn1-ber library.
Similar to https://github.com/notaryproject/notation-go/pull/275.
Will be superseded by #6761, the goal of this PR is to backport this quick fix to older cert-manager versions.
/kind bug
```release-note
Bugfix: LiteralSubjects with a #= value can result in memory issues due to faulty DER parser (github.com/go-asn1-ber/asn1-ber).
```
=> Fix a memory bug in ldap's ParseDN function by disabling part of the functionality

.golangci.ci.yaml, internal/vault/vault_test.go, pkg/controller/certificates/issuing/internal/secret_test.go, pkg/controller/certificates/issuing/issuing_controller_test.go, test/e2e/suite/issuers/acme/certificate/http01.go, test/e2e/suite/issuers/acme/certificate/notafter.go, test/e2e/suite/issuers/ca/certificate.go, test/e2e/suite/issuers/selfsigned/certificate.go, test/e2e/suite/issuers/venafi/tpp/certificate.go, test/e2e/suite/serving/cainjector.go, test/e2e/util/util.go, test/unit/gen/certificate.go
- `pki.GenerateTemplate` was already no longer used
- `testCA.Subjects`, `RootCAs.Subjects`: I replaced these with `clientCA.Equal(testCA)`
- `util.NewCertManagerBasicCertificate(`: I replaced this function with `gen.Certificate` (as described in the deprecation notice)
/kind cleanup
```release-note
NONE
```
=> Replace deprecated functions

deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, pkg/apis/acme/v1/types_issuer.go, pkg/controller/acmeorders/sync.go, pkg/controller/acmeorders/sync_test.go, test/unit/gen/issuer.go
Due to [recent change of Let's Encrypt Chain of Trust](https://letsencrypt.org/2023/07/10/cross-sign-expiration), the short certificate chain (having ISRG Root X1 as root certificate) became the default certificate provided for `/acme/certificate` API endpoint. Old long certificate chain, which is cross-signed with DST Root CA X3, is now served as an alternate certificate chain.
Caused by this change, if `preferredChain` is configured as `ISRG Root X1` in Issuer or ClusterIssuer, cert-manager now returns a long-chain certificate, cross-signed by DST Root CA, since the current implementation does not include default certificate chain while looking for preferred chain.
Going worse, this does not fall back to the default chain but returns the cross-signed chain since that chain also includes …
=> bugfix: wrong certificate chain is used if preferredChain is configured

make/config/kyverno/kustomization.yaml, make/config/kyverno/policy.yaml
The [ci-cert-manager-master-e2e-v1-28-bestpractice-install](https://testgrid.k8s.io/cert-manager-periodics-master#ci-cert-manager-master-e2e-v1-28-bestpractice-install) tests have been failing since we merged https://github.com/cert-manager/cert-manager/pull/6614 
The problem is that that Kyverno is blocking the installation of the additional vault server, configured for mTLS, which was introduced in that PR.
```sh
$ make E2E_SETUP_OPTION_BESTPRACTICE=true e2e-setup
...
$ make e2e GINKGO_FOCUS='Vault Issuer [mtls]'
...
resource StatefulSet/e2e-vault-mtls/chart-vault-vault-mtls was blocked due to the following policies
disallow-capabilities-strict:
autogen-require-drop-all: 'validation failure: Containers must drop `ALL` capabilities.'
require-ro-rootfs: …
```
=> Fix broken best-practice e2e tests

pkg/logs/logs.go
Fixes https://github.com/cert-manager/cert-manager/issues/6768
In https://github.com/cert-manager/cert-manager/pull/6587 (https://github.com/cert-manager/cert-manager/pull/6587/files#diff-8f2f7b96261d29c4991c0025fde03c2edb0411a9aa7afaa834b5cf19837b5b2eL41), I updated the global `Log` definition in `log.go`.
I based the updated code on the deprecation message of the `klogr.NewWithOptions()` command that we were using.
It seems like the proposed replacement `textlogger.NewLogger(textlogger.NewConfig())` does not get updated when we parse & set the logging flags.
This PR fixes this bug by using `klog.Background()` instead.
Before:
```console
$ k -n cert-manager logs cert-manager-78dd8d6947-br2h8 
{"ts":1708504242845.5793,"caller":"clientcmd/client_config.go:618","msg":"Neither --kubeconfig …
```
=> Fix broken json logging

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
This PR cmd/cmctl's go.mod to v1.13.4 as part of the release process.
**To the reviewer:** the version changes in \`go.mod\` must be reviewed.
/kind cleanup
```release-note
NONE
```
=> [release-1.13] Update cmd/ctl's go.mod to v1.13.4

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
This PR cmd/cmctl's go.mod to v1.12.8 as part of the release process.
**To the reviewer:** the version changes in \`go.mod\` must be reviewed.
/kind cleanup
```release-note
NONE
```
=> [release-1.12] Update cmd/ctl's go.mod to v1.12.8

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
This PR cmd/cmctl's go.mod to v1.14.3 as part of the release process.
**To the reviewer:** the version changes in \`go.mod\` must be reviewed.
/kind cleanup
```release-note
NONE
```
=> [release-1.14] Update cmd/ctl's go.mod to v1.14.3

cmd/controller/LICENSES, cmd/controller/go.mod, go.mod, pkg/controller/acmechallenges/update.go, pkg/issuer/acme/dns/akamai/akamai.go, pkg/issuer/acme/dns/dns.go
One of the outcomes of our security audit is that we want to improve the quality of our direct dependencies.
Since `github.com/pkg/errors` is archived, it got a very low score.
For that reason, it was advised to remove this library as a direct dependency.
/kind cleanup
```release-note
NONE
```
=> Remove github.com/pkg/errors as a direct dependency

deploy/charts/cert-manager/templates/networkpolicy-egress.yaml, deploy/charts/cert-manager/templates/networkpolicy-webhooks.yaml
The NetworkPolicy `podSelector.matchLabels` contains too many labels, which makes it more brittle.
Ideally, we specify a minimum subset of labels that uniquely identifies the resources it should select.
This is a safe change, matchLabels on a NetworkPolicy is much less of a beast than matchLabels on a Deployment.
/kind cleanup
```release-note
NONE
```
=> Helm: fix matchLabels selector - select on minimum subset of labels that uniquely identifies the resources

internal/apis/certmanager/validation/certificate.go, internal/apis/certmanager/validation/certificate_test.go
https://github.com/cert-manager/cert-manager/issues/6340#issuecomment-1734962965
Fixes #6361
feature
```release-note
Allow `cert-manager.io/allow-direct-injection` in annotations
```
=> Allow `cert-manager.io/allow-direct-injection` in annotations

pkg/controller/certificates/issuing/internal/keystore.go, pkg/controller/certificates/issuing/internal/keystore_test.go, pkg/util/pki/parse.go
Fixes #6803. When either a JKS or PKCS12 keystore is requested, the contents of the generated truststores should match the contents of the `ca.crt` field in the rendered secret. Previously if an issuer returned multiple concatenated CAs when signing a CertificateRequest only the first CA would be included in the truststores, despite the full set appearing in the `ca.crt` field.
/kind bug
```release-note
BUGFIX: JKS and PKCS12 stores now contain the full set of CAs specified by an issuer
```
=> bugfix: include all CA certificates in encoded pkcs12/jks stores

internal/apis/config/cainjector/fuzzer/fuzzer.go, internal/apis/config/cainjector/v1alpha1/defaults.go, internal/apis/config/cainjector/v1alpha1/zz_generated.defaults.go
In https://github.com/cert-manager/cert-manager/pull/6345, I forgot to add the defaults for the cainjector leaderelection options.
The original defaults can be found here: https://github.com/cert-manager/cert-manager/blob/ba6268135d0f2ebea5f8eb29a57934f1acae15e2/internal/cmd/util/defaults.go.
Fixes https://github.com/cert-manager/cert-manager/issues/6808
```
$ _bin/server/cainjector-linux-amd64 --help
...
--leader-elect                                        If true, cainjector will perform leader election between instances to ensure no more than one instance of cainjector operates at a time (default true)
--leader-election-lease-duration duration             The duration that non-leader candidates will wait after observing a leadership renewal until attempting to acquire leadership of a …
```
=> BUGFIX: cainjector leaderelection defaults are missing

make/tools.mk
fixes CVE-2024-24783 (https://go.dev/doc/devel/release#go1.21.0)
/kind cleanup
```release-note
Upgrade go to 1.21.8: fixes CVE-2024-24783
```
=> Bump go to 1.21.8

pkg/controller/certificates/issuing/internal/keystore.go, pkg/controller/certificates/issuing/internal/keystore_test.go, pkg/util/pki/parse.go
Manual backport of https://github.com/cert-manager/cert-manager/pull/6806
/kind bug
```release-note
BUGFIX: JKS and PKCS12 stores now contain the full set of CAs specified by an issuer
```
=> [release-1.12] bugfix: include all CA certificates in encoded pkcs12/jks stores

LICENSES, cmd/acmesolver/LICENSES, cmd/acmesolver/go.mod, cmd/acmesolver/go.sum, cmd/cainjector/LICENSES, cmd/cainjector/go.mod, cmd/cainjector/go.sum, cmd/controller/LICENSES, cmd/controller/go.mod, cmd/controller/go.sum, cmd/ctl/LICENSES, cmd/ctl/go.mod, cmd/ctl/go.sum, cmd/webhook/LICENSES, cmd/webhook/go.mod, cmd/webhook/go.sum, go.mod, go.sum, test/e2e/LICENSES, test/e2e/go.mod, test/e2e/go.sum, test/integration/LICENSES, test/integration/go.mod, test/integration/go.sum
Manual backport of https://github.com/cert-manager/cert-manager/pull/6827
```
$ GOTOOLCHAIN=go1.21.8 govulncheck ./...
Scanning your code and 1505 packages across 160 dependent modules for known vulnerabilities...                                                                                                                                                                                                  === Symbol Results ===                                                                                                                                                                                                                                                                          Vulnerability #1: GO-2024-2611
Infinite loop in JSON unmarshaling in google.golang.org/protobuf
More …
```
=> [release-1.12] upgrade google.golang.org/protobuf fixing GO-2024-2611

make/tools.mk
Bump go to the latest version (1.22.1).
/kind cleanup
```release-note
Upgrade go to latest version 1.22.1
```
=> Bump to latest go version (1.22.1)

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
This PR cmd/cmctl's go.mod to v1.14.4 as part of the release process.
```release-note
NONE
```
=> [release-1.14] Update cmd/ctl's go.mod to v1.14.4

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
This PR cmd/cmctl's go.mod to v1.13.5 as part of the release process.
```release-note
NONE
```
=> [release-1.13] Update cmd/ctl's go.mod to v1.13.5

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
This PR cmd/cmctl's go.mod to v1.12.9 as part of the release process.
```release-note
NONE
```
=> [release-1.12] Update cmd/ctl's go.mod to v1.12.9

pkg/server/tls/authority/authority.go, pkg/server/tls/dynamic_source.go, pkg/server/tls/dynamic_source_test.go, test/integration/webhook/dynamic_source_test.go
- Adds unit tests to increase our confidence in the dynamic source logic.
- Simplifies the source by replacing a lot of the channels with an errgroup
/kind cleanup
```release-note
NONE
```
=> Refactor the webhook dynamic source and add unit tests

pkg/apis/certmanager/v1/types.go, pkg/controller/certificate-shim/helper.go, pkg/controller/certificate-shim/sync_test.go
These are the changes for implementing https://github.com/cert-manager/cert-manager/issues/6838.
This allows ingress-shim users to set the `secretTemplate` field on generated `Certificate` resources. This makes using [secret sync tools](https://cert-manager.io/docs/devops-tips/syncing-secrets-across-namespaces/) (e.g. [kubernetes-reflector](https://github.com/emberstack/kubernetes-reflector)) much simpler for ingress-shim users.
Added a new Ingress annotation `cert-manager.io/secret-template` whose value is a JSON representation of `secretTemplate`.
feature
```release-note
Added a new Ingress annotation for copying specific Ingress annotations to Certificate's secretTemplate
```
=> Add secretTemplate to Certificate resources created by ingress-shim

.trivyignore
These were causing the trivy tests to fail.
/kind bug
```release-note
NONE
```
=> [release-1.14] ignore two false positive vulns

internal/apis/config/controller/fuzzer/fuzzer.go
The round-tripper test fails in case defaults are applied.
That is why we always set the fields to a non-empty value (after the fuzzer sets it to an empty value).
Currently we just set a lot of fields to a non-empty value, which sort of defeats the purpose of the fuzzer.
Instead, we should just set the field to a non-empty value when we see the fuzzer generated an object with that field set to an empty value (which would trigger the default to be applied).
/kind cleanup
```release-note
NONE
```
=> ControllerConfiguration fuzzer, only set the value in case the random value is empty

internal/cmd/util/exit_test.go, internal/cmd/util/signal.go, internal/cmd/util/signal_test.go
Same bugfix as https://github.com/cert-manager/cmctl/pull/40.
The bug itself was introduced in https://github.com/cert-manager/cert-manager/pull/6771
/kind bug
```release-note
NONE
```
=> BUGFIX: exit with correct exit codes

pkg/controller/certificaterequests/venafi/venafi.go, pkg/controller/certificaterequests/venafi/venafi_test.go, pkg/controller/certificatesigningrequests/venafi/venafi.go, pkg/controller/certificatesigningrequests/venafi/venafi_test.go, pkg/issuer/venafi/client/venaficlient.go, pkg/issuer/venafi/client/venaficlient_test.go, pkg/issuer/venafi/setup.go, pkg/issuer/venafi/setup_test.go, pkg/issuer/venafi/venafi.go, pkg/util/useragent.go
- **Purpose**: Improve Venafi API interactions by adding a custom `User-Agent` header to requests from cert-manager.
- **Issue Addressed**: Allows Venafi TPP server administrators to identify cert-manager as the source of API requests, aiding in troubleshooting and bug reporting.
- **Implementation**: The `User-Agent` string mirrors that used for the ACME issuer and includes cert-manager version details.
- **Testing**: Local and E2E tests conducted, including verification of `User-Agent` header presence in TPP server logs.
As an administrator of a Venafi TPP server or of Venafi Cloud , I want to know which software is being used to connect to the REST API.
Right now the vcert SDK will use the [default Go HTTP client User-Agent header](https://github.com/golang/go/blob/db423dde85ad4923c2c4a …
=> Add user-agent header in requests to Venafi API

OWNERS
I have been a reviewer for some time and reviewed more than the requirement for appover status, some examples:
- https://github.com/cert-manager/cert-manager/pull/6784
- https://github.com/cert-manager/cert-manager/pull/6751
- https://github.com/cert-manager/cert-manager/pull/6672
- https://github.com/cert-manager/cert-manager/pull/6631
- https://github.com/cert-manager/cert-manager/pull/6607
- https://github.com/cert-manager/cert-manager/pull/6606
- https://github.com/cert-manager/cert-manager/pull/6586
- @sgtcodfish
```release-note
NONE
```
=> Add @ThatsMrTalbot as approver

make/ci.mk
Running `$(MAKE)` in the make target with concurrency >1 can cause multiple make instances to download the same tools/ dependencies at the same time. This results in faulty files and broken tests.
Long-term solution is to change the entry points called by prow.
These `$(MAKE)` calls were introduced in https://github.com/cert-manager/cert-manager/pull/6749.
Example CI failure: https://storage.googleapis.com/cert-manager-prow-artifacts/logs/ci-cert-manager-master-make-test/1781225581912788992/build-log.txt
/kind bug
```release-note
NONE
```
=> Makefile bugfix

internal/apis/certmanager/validation/certificate.go, internal/apis/certmanager/validation/certificate_test.go
In https://github.com/cert-manager/csi-driver/issues/197 we see a question where the error message when using an external issuer is a little confusing for the users because it's not clear they're missing the "group".
This PR changes the error message (in the event that the group is completely missing) and suggests the fix.
/kind feature
```release-note
Add hint to validation error message to help users of external issuers more easily fix the issue if they specify a Kind but forget the Group
```
=> Better error issuerref

make/release.mk
fixes https://github.com/cert-manager/infrastructure/issues/33
@maelvls discovered that rclone does not work with GCS buckets that have "uniform bucket level access" enabled instead of ACL (see https://github.com/cert-manager/infrastructure/issues/33).
This PR aims to change our rclone command so it works with "uniform bucket level access" GCS buckets.
I'll also backport this PR to 1.14, 1.13 and 1.12.
/kind cleanup
```release-note
NONE
```
=> Disable rclone gcs bucket ACL

make/cluster.sh
In https://github.com/cert-manager/testing/pull/1011, the docker networking hack that was lives in cert-manager/cert-manager was added to the testing runner script.
However, I did not expect that this would cause the cert-manager tests to fail due to the hack in this repo conflicting with the fix in the runner script (see https://storage.googleapis.com/cert-manager-prow-artifacts/pr-logs/pull/batch/pull-cert-manager-master-e2e-v1-28/1782439419886702592/build-log.txt).
This PR removes the docker network hack from cert-manager/cert-manager since it is already present in the runner script and both hacks are not compatible.
/kind cleanup
```release-note
NONE
```
=> Remove docker custom network hack which has been moved to the test runner

make/release.mk
Manual backport of https://github.com/cert-manager/cert-manager/pull/6906
/kind cleanup
```release-note
NONE
```
=> [release-1.14] Disable rclone gcs bucket ACL

internal/webhook/feature/features.go, pkg/controller/certificaterequests/ca/ca.go, pkg/controller/certificaterequests/selfsigned/selfsigned.go
This feature gate was introduced in https://github.com/cert-manager/cert-manager/pull/6300 (released in v1.13).
This PR graduates this feature to GA, so the deprecated code can be removed.
/kind cleanup
```release-note
Graduate the 'DisallowInsecureCSRUsageDefinition' feature gate to GA.
```
=> Graduate 'DisallowInsecureCSRUsageDefinition' to GA

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
This PR cmd/cmctl's go.mod to v1.14.5 as part of the release process.
```release-note
NONE
```
=> [Release v1.14.5] Update cmd/cmctl's go.mod to v1.14.5

.trivyignore
See comment in trivyignore file
/kind cleanup
```release-note
NONE
```
=> ignore CVE-2020-8559 in trivy scans

cmd/controller/app/controller.go, cmd/controller/app/options/options.go, internal/apis/config/controller/types.go, internal/apis/config/controller/v1alpha1/defaults.go, internal/apis/config/controller/v1alpha1/testdata/defaults.json, internal/apis/config/controller/v1alpha1/zz_generated.conversion.go, internal/controller/feature/features.go, make/e2e-setup.mk, pkg/apis/config/controller/v1alpha1/types.go, pkg/apis/config/controller/v1alpha1/zz_generated.deepcopy.go, pkg/controller/context.go
This PR graduates the GatewayAPI support to *BETA*:
- The ExperimentalGatewayAPISupport feature flag is now enabled by default
- An `--enable-gateway-api` flag / config file option has been added, this is disabled by default.
Fixes #6882
```release-note
GatewayAPI support has graduated to Beta. Add the `--enable-gateway-api` flag to enable the integration.
```
=> feat: graduate gateway-api to beta and enable by default

test/e2e/suite/certificates/additionaloutputformats.go, test/e2e/suite/issuers/ca/certificate.go
Revert removed required feature gates gating for e2e-tests in https://github.com/cert-manager/cert-manager/pull/6970, ref. https://github.com/cert-manager/cert-manager/pull/6970#issuecomment-2089953422
/kind cleanup
```release-note
NONE
```
=> Revert removal of required feature gate gating e2e-tests

pkg/util/pki/parse_test.go, pkg/util/pki/subject.go, pkg/util/pki/subject_test.go
There were still some tests that were using this function, I updated the tests to test the underlying function instead.
These tests were also moved to a test file that matches the file in which the functions are defined.
**Migration guide:**
Use the underlying `UnmarshalSubjectStringToRDNSequence(subject)` and `MarshalRDNSequenceToRawDERBytes(rdnSequence)` functions instead.
branched from https://github.com/cert-manager/cert-manager/pull/6775
/kind cleanup
```release-note
Remove deprecated `pkg/util/pki/ParseSubjectStringToRawDERBytes` function.
```
=> Remove deprecated ParseSubjectStringToRawDERBytes function

make/tools.mk
Fixes GO-2024-2824 (https://github.com/advisories/GHSA-2jwv-jmq4-4j3r).
/kind cleanup
```release-note
Upgrade Go to 1.21.10, fixing GO-2024-2824 (https://github.com/advisories/GHSA-2jwv-jmq4-4j3r).
```
=> [release-1.14] Bump go to 1.21.10

pkg/util/pki/subject.go, pkg/util/pki/subject_test.go
This PR adds a missing feature to the UnmarshalSubjectStringToRDNSequence function: the ability to specify numeric OIDs as subject attribute type. Right now, an attribute type has to be chosen by name and only a small set of names is supported: https://github.com/cert-manager/cert-manager/blob/8d15b5e6a8d92803c286a3b55a0108ece4f3aee8/pkg/util/pki/subject.go#L55-L66
/kind feature
```release-note
Add support for numeric OID types in LiteralSubject. Eg. "1.2.3.4=String Value"
```
=> LiteralSubject: Add support for numeric OID subject attribute type

make/e2e-ci.sh
We saw the following error in our logs "make/e2e-ci.sh: line 27: K8S_VERSION: command not found".
This is caused by a typo in the `make/e2e-ci.sh` script, where we tried to use Makefile syntax instead of bash syntax.
/kind bug
```release-note
NONE
```
=> Fix script error: "make/e2e-ci.sh: line 27: K8S_VERSION: command not found"

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/values.yaml
As a mitigation for https://github.com/cert-manager/cert-manager/issues/1292 it may be desired to hardcode DNS entries on pod level to allow the self-check to pass, e.g. in the scenario where the network does not allow traffic to an internal IP by calling its external IP (which happens in the case of a public DNS). 
feature
```release-note
[Helm] Add optional hostAliases to cert-manager pod to allow the DNS self-check to pass in custom scenarios.
```
=> Add optional hostAliases to cert-manager pod

deploy/crds/crd-certificates.yaml, internal/apis/certmanager/types_certificate.go, internal/apis/certmanager/v1alpha2/types_certificate.go, internal/apis/certmanager/v1alpha3/types_certificate.go, internal/apis/certmanager/v1beta1/types_certificate.go, internal/controller/feature/features.go, internal/webhook/feature/features.go, pkg/apis/certmanager/v1/types_certificate.go
We improved this feature a lot in this release:
- https://github.com/cert-manager/cert-manager/pull/6761
- https://github.com/cert-manager/cert-manager/pull/6775
- https://github.com/cert-manager/cert-manager/pull/6995
- https://github.com/go-ldap/ldap/pull/504
- https://github.com/go-ldap/ldap/pull/505
- https://github.com/go-ldap/ldap/pull/497
- https://github.com/go-asn1-ber/asn1-ber/pull/42
/kind feature
```release-note
Promote the `LiteralCertificateSubject` feature to Beta.
```
=> Promote the LiteralCertificateSubject feature to Beta

test/e2e/suite/certificaterequests/approval/userinfo.go
Manual backport of https://github.com/cert-manager/cert-manager/pull/6647
/kind cleanup
```release-note
NONE
```
=> [release-1.12] Read admin groups from the client certificate instead of hard coding them

hack/util/hash.sh
In https://github.com/cert-manager/cert-manager/pull/6749, we removed/ moved the `hash.sh` script.
However, I did not notice that the script is also used during the release process:
- https://github.com/cert-manager/cert-manager/blob/a26a0a856f17db768224adfdd3e56bdaef45a991/make/release.mk#L110
- https://github.com/cert-manager/cert-manager/blob/a26a0a856f17db768224adfdd3e56bdaef45a991/make/manifests.mk#L80
This PR re-adds the script with a notice that it is still used by those Make targets.
This should fix the release process.
/kind bug
```release-note
NONE
```
=> Re-add hash.sh, which was also used by the release Make target

cmd/controller/app/options/options.go, cmd/controller/app/options/options_test.go, deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/rbac.yaml, deploy/charts/cert-manager/values.yaml
This PR adds Helm options to simplify configuring the build-in cert-manager auto-approver.
1. It adds the option to approve external issuers (including an "approve all external issuers" options)
2. It adds the option to easily disable the auto-approver
This will simplify installing cert-manager combined with an external issuer or in combination with approver-policy (https://cert-manager.io/docs/policy/approval/approver-policy/installation/).
Fixes https://github.com/cert-manager/cert-manager/issues/6521
NOTE: We will keep the default "only approve cert-manager.io Issuer and ClusterIssuer" rule. In approver-policy and csi-driver-spiffe, we removed this constraint. The reason we keep the constraint here is because cert-manager's auto-approver will automatically approve all …
=> Add Helm options to extend auto-approval or disable it

deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml
We were not yet mounting the cainjector ConfigMap in the cainjector deployment.
fixes #7046
/kind bug
```release-note
Helm BUGFIX: the cainjector ConfigMap was not mounted in the cainjector deployment.
```
=> BUGFIX: correctly mount config files for components

design/20240518.push-to-multiple-registries.md
Proposal for pushing to an additional, non "jetstack" branded container registry.
proposal
```release-note
NONE
```
=> proposal: push to multiple registries

make/tools.mk
go1.21.11 (released 2024-06-04) includes security fixes to the archive/zip and net/netip packages, as well as bug fixes to the compiler, the go command, the runtime, and the os package.
```release-note
Updated Go to 1.21.11 bringing in security fixes for archive/zip and net/netip.
```
=> chore: update golang to 1.21.11

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/_helpers.tpl, deploy/charts/cert-manager/templates/podmonitor.yaml, deploy/charts/cert-manager/values.linter.exceptions, deploy/charts/cert-manager/values.schema.json, deploy/charts/cert-manager/values.yaml, make/ci.mk, make/manifests.mk
Adds a `values.schema.json` file generated using [helm-tool](https://github.com/cert-manager/helm-tool).
Also adds the `verify-helm-values` target which checks that the options defined in the template and the values.yaml file match.
/kind feature
```release-note
Helm: adds jsonschema validation for the Helm values.
```
=> Enable Helm values.yaml jsonschema validation

internal/vault/vault.go, pkg/controller/certificaterequests/vault/vault.go, pkg/controller/certificaterequests/vault/vault_test.go
Manual backport of https://github.com/cert-manager/cert-manager/pull/7105
/kind bug
```release-note
BUGFIX: fix issue that caused Vault issuer to not retry signing when an error was encountered.
```
=> [release-1.15] BUGFIX: retry signing when encountering transient error (Vault issuer)

test/e2e/framework/helper/validation/certificatesigningrequests/certificatesigningrequests.go, test/e2e/framework/util.go, test/e2e/suite/certificates/additionaloutputformats.go, test/e2e/suite/certificates/literalsubjectrdns.go, test/e2e/suite/certificates/othernamesan.go, test/e2e/suite/certificatesigningrequests/selfsigned/selfsigned.go, test/e2e/suite/conformance/certificates/tests.go, test/e2e/suite/conformance/certificatesigningrequests/acme/acme.go, test/e2e/suite/conformance/certificatesigningrequests/suite.go, test/e2e/suite/conformance/certificatesigningrequests/tests.go, test/e2e/suite/conformance/certificatesigningrequests/vault/approle.go, test/e2e/suite/conformance/certificatesigningrequests/vault/kubernetes.go, test/e2e/suite/issuers/ca/certificate.go
Simplifies the definitions of the CertificateSigningRequest conformance tests and adds additional tests, matching tests that exist for the Certificate resources.
/kind cleanup
```release-note
NONE
```
=> Simplify CertificateSigningRequest conformance tests and add missing tests

pkg/metrics/metrics.go, test/integration/certificates/metrics_controller_test.go
These metrics are default when using Prometheus go client's pre-defined registry, but were missing as the controller creates it's own registry.
Useful many debug scenarios
feature 
```release-note
Add process and go runtime metrics for controller
```
=> Add process and go runtime metrics for controller

test/e2e/suite/conformance/certificatesigningrequests/tests.go
Follow-up PR for https://github.com/cert-manager/cert-manager/pull/7110, adding missing required `OnlySAN` feature.
Fixes periodic CI job: https://prow.infra.cert-manager.io/view/gs/cert-manager-prow-artifacts/logs/ci-cert-manager-master-e2e-v1-30-issuers-venafi/1805033541822582784
/kind bug
```release-note
NONE
```
=> Fix Venafi conformance test

test/e2e/framework/helper/validation/certificates/certificates.go, test/e2e/suite/conformance/certificates/suite.go, test/e2e/suite/conformance/certificates/tests.go, test/unit/gen/certificate.go
This PR migrates the Certificate conformance tests to use a similar tabular definition style.
NOTE FOR REVIEWER: I split the PR in separate commits, so each individual test can be followed. I advise to review the PR commit-by-commit.
/kind cleanup
```release-note
NONE
```
=> Refactor Certificate conformance to tabular tests

make/e2e-setup.mk
Richard reported this issue in #7048. He found that the command:
```bash
E2E_EXISTING_CHART=true E2E_CERT_MANAGER_VERSION=1.14.2 make e2e-setup-certmanager
```
fails with the error:
```
Error: unknown flag: --version1.14.2
```
It looks like this comes from a change in https://github.com/cert-manager/cert-manager/pull/6795. In the Makefile:
```make
$(addprefix --version=,$(E2E_CERT_MANAGER_VERSION))
```
expanded to an empty string most of the time (when `E2E_CERT_MANAGER_VERSION` is left empty), which was OK. But when setting `E2E_CERT_MANAGER_VERSION`, `addprefix` would prepend `--version` without a space, causing the problem.
Closes #7048
```release-note
NONE
```
=> make e2e-setup-certmanager: E2E_CERT_MANAGER_VERSION now works

cmd/controller/go.mod, cmd/controller/go.sum, go.mod, go.sum
Fixes trivy-reported vuln  CVE-2024-6104. Nothing reported by govulncheck.
/kind bug
```release-note
Bump the go-retryablehttp dependency to fix CVE-2024-6104
```
=> Bump go-retryablehttp to address CVE-2024-6104

LICENSES, cmd/controller/LICENSES, cmd/controller/go.mod, cmd/controller/go.sum, go.mod, go.sum, test/e2e/LICENSES, test/e2e/go.mod, test/e2e/go.sum
Manual backport of #7125 
/kind bug
```release-note
Bump the go-retryablehttp dependency to fix CVE-2024-6104
```
=> [release-1.15] Bump go-retryablehttp to address CVE-2024-6104

pkg/controller/clusterissuers/checks.go, pkg/controller/issuers/checks.go
Introduced in https://github.com/cert-manager/cert-manager/pull/7036 (did not run the Venafi tests on the last commit).
Adds a missing nilpointer check that is causing panics for Venafi issuers.
/kind bug
```release-note
NONE
```
=> BUGFIX: Venafi issuer and clusterissuer checks were failing due to nilpointer exception

make/config/bind/configmap.yaml, make/config/bind/deployment.yaml
Following the best practices described here: https://home.robusta.dev/blog/stop-using-cpu-limits
Sets a CPU request and a MEM request and limit.
Experimentally found that 256Mi works as memory limit.
/kind cleanup
```release-note
NONE
```
=> Tests: add bind resource request to improve availability during tests

make/config/bind/configmap.yaml, make/config/bind/deployment.yaml, make/config/bind/service.yaml, make/e2e-setup.mk
Use the supported docker.io/ubuntu/bind9 image and run it as non-root.
/kind cleanup
```release-note
NONE
```
=> Tests: use supported bind9 image and run as non-root

deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, internal/apis/certmanager/types_issuer.go, pkg/apis/certmanager/v1/types_issuer.go
Fixes https://github.com/cert-manager/cert-manager/issues/7145
Trying to rephrase the outdated description according to the doc https://cert-manager.io/docs/configuration/venafi/#creating-a-venafi-trust-protection-platform-issuer
I have executed `make generate-crds` `generate-codegen` `ci-presubmit`.
/kind bug
```release-note
NONE
```
=> Fix API fields description for Venafi TPP credentialsRef

internal/controller/certificates/policies/checks.go, pkg/controller/certificates/issuing/issuing_controller.go, pkg/controller/certificates/keymanager/keymanager_controller.go, pkg/util/pki/match.go, pkg/util/pki/match_test.go
Simplifies the usage of pki match functions by removing the return values that are always nil.
/kind cleanup
```release-note
NONE
```
=> pki match: remove return values that are always nil

cmd/cainjector/app/controller.go, cmd/cainjector/go.mod, design/20221205-memory-management.md, pkg/controller/cainjector/indexers.go, pkg/controller/cainjector/reconciler.go, pkg/controller/cainjector/setup.go, pkg/controller/cainjector/sources.go
Update cainjector to use metadata-only caching for Secret resources:
1. To reduce memory use of cainjector, by only caching metadata of Secret resources in-memory.
2. To reduce the load on the K8S API server when cainjector starts up, caused by the initial listing of full Secret resources in the cluster.
With 100M of Secrets in the cluster, this reduces the maximum memory usage from ~290M to ~46M:
- Before:   "rss_max_kilobytes": 289268
- After: "rss_max_kilobytes": 45652
Behind the scenes the reflector is asking the server for a `PartialObjectMetadataList` projection instead of the full data `SecretList`.
You can see the reduction in the response size using curl as follows:
```sh
dd if=/dev/zero bs=1048576 count=1 of=f1
echo -n {0..99} | xargs -d ' ' -P5 -I{} kubectl create secret …
```
=> Reduce memory usage by only caching the metadata of Secret resources

pkg/issuer/acme/dns/route53/route53.go, pkg/issuer/acme/dns/route53/route53_test.go
fixes https://github.com/cert-manager/cert-manager/issues/7102
I think this issue was introduced in https://github.com/cert-manager/cert-manager/pull/6671, the v2 version of the aws sdk does now require a region to be provided for the sts client. We now have to explicitly provide the "aws-global" value to be used by the sts client (see https://github.com/go-acme/lego/issues/2067#issuecomment-1845666491).
@pchang388 could you verify this solves your issue?
/kind bug
```release-note
BUGFIX route53: explicitly set the "aws-global" sts region which is now required by the github.com/aws/aws-sdk-go-v2 library.
```
=> BUGFIX: AWS route53: Set global region for sts

pkg/issuer/acme/http/http.go, pkg/issuer/acme/http/httproute.go, pkg/issuer/acme/http/httproute_test.go
Fixes #7176 
/kind bug
```release-note
Fixes ACME HTTP01 challenge behaviour when using Gateway API to prevent unbounded creation of HTTPRoute resources
```
=> fix: HTTP01 challenge HTTPRoute creation for GatewayAPI

pkg/issuer/acme/dns/azuredns/azuredns.go, pkg/issuer/acme/dns/azuredns/azuredns_test.go
When checking for a HTTP status code returned by Azure client, we did not consider the case of authentication error - which happens to be a completely different type in some cases.
This PR fixes this issue by making sure the error extraction actually succeeded and we got a valid non-nil error.
Fixes #7136 
/kind bug
```release-note
Fix Azure DNS causing panics whenever authentication error happens
```
=> fix: Handle case of Azure returning auth error

deploy/charts/cert-manager/templates/podmonitor.yaml
In https://github.com/cert-manager/cert-manager/pull/6459 @shlomitubul introduced a PodMonitor resource. 
There was a bug in the PodMonitor template where the servicemonitor.endpointAdditionalProperties were being added instead of podmonitor.endpointAdditionalProperties and that bug has been recently fixed by @inteon in https://github.com/cert-manager/cert-manager/pull/7069#pullrequestreview-2099180596
But there is an additional mistake in the indentation of those values which is only now apparent.
Here's how to recreate the issue:
```yaml
#value.yaml
prometheus:
enabled: true
podmonitor:
enabled: true
endpointAdditionalProperties:
scheme: https
tlsConfig:
serverName: cert-manager-metrics
ca:
secret:
name: cert-manager-metrics-ca
key: "tls.crt"
```
```sh
git fetch origin master
git …
```
=> Fix incorrect indentation of the PodMonitor template in the Helm chart

deploy/charts/cert-manager/templates/podmonitor.yaml
Manual backport of https://github.com/cert-manager/cert-manager/pull/7069#pullrequestreview-2099180596 and https://github.com/cert-manager/cert-manager/pull/7190.
/kind bug
```release-note
Fix incorrect value and indentation of `endpointAdditionalProperties` in the `PodMonitor` template of the Helm chart
```
=> [release-1.15] Fix incorrect value and indentation of the PodMonitor endpointAdditionalProperties 

test/e2e/suite/conformance/certificates/tests.go
There is logic in a BeforeEach block to skip GatewayAPI tests if the feature is disabled. However there was a bug so this only skipped the first test of each process.
This does not impact 1.14 because GatewayAPI was disabled by default and does not impact master because the tests have been refactored
```release-note
NONE
```
=> [release-1.15] fix: e2e feature flags disabled test failing

gcb/build_cert_manager.yaml
While trying to [release cert-manager v1.15.2-alpha.0](https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1721810574344189), the [cloudbuild failed](https://console.cloud.google.com/cloud-build/builds;region=global/fd32d59d-8757-4a16-87c5-9d2061ebcf7f;step=1?project=cert-manager-release) after I [pushed the tag](https://github.com/cert-manager/cert-manager/releases/tag/v1.15.2-alpha.0):
> Pulling image: eu.gcr.io/jetstack-build-infra-images/make-dind:20230406-0ef4440-bullseye
Error response from daemon: pull access denied for eu.gcr.io/jetstack-build-infra-images/make-dind, repository does not exist or may require 'docker login': denied: Permission denied for "20230406-0ef4440-bullseye" from request "/v2/jetstack-build-infra-images/make-dind/manifests/20230406-0ef4440-bullseye".
/kind bug …
=> Update the Google CloudBuild job image

deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, internal/apis/acme/types_issuer.go, internal/apis/acme/v1/zz_generated.conversion.go, internal/apis/acme/v1alpha2/types_issuer.go, internal/apis/acme/v1alpha2/zz_generated.conversion.go, internal/apis/acme/v1alpha2/zz_generated.deepcopy.go, internal/apis/acme/v1alpha3/types_issuer.go, internal/apis/acme/v1alpha3/zz_generated.conversion.go, internal/apis/acme/v1alpha3/zz_generated.deepcopy.go, internal/apis/acme/v1beta1/types_issuer.go, internal/apis/acme/v1beta1/zz_generated.conversion.go, internal/apis/acme/v1beta1/zz_generated.deepcopy.go, internal/apis/acme/zz_generated.deepcopy.go, pkg/apis/acme/v1/types_issuer.go, pkg/apis/acme/v1/zz_generated.deepcopy.go, pkg/issuer/acme/http/pod.go, pkg/issuer/acme/http/pod_test.go
Currently when using ingress for ACME HTTP validation you can provide a pod template to configure various aspects of the pod like tolerations and affinity. This PR adds the same capability for GatewayAPI
resolves #7210 
/kind feature
```release-note
Allow the user to specify a Pod template when using GatewayAPI HTTP01 solver, this mirrors the behaviour when using the Ingress HTTP01 solver.
```
=> feat: allow pod template to be specified when using gateway-api

make/tools.mk
Updates the version of Go to 1.21.13 to resolve CVE-2024-24791
/kind bug
```release-note
Updates Go to 1.21.13 to resolve CVE-2024-24791
```
=> [release-1.12] chore: update go to 1.21.13

make/e2e-setup.mk
E2E setup is currently broken because the bind9 image we are using got pushed over, changing its shasum
/kind bug
```release-note
NONE
```
=> fix: update shasum for docker.io/ubuntu/bind9

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
This PR cmd/cmctl's go.mod to v1.12.13 as part of the release process.
```release-note
NONE
```
=> [release-1.12] Update cmd/cmctl's go.mod to v1.12.13

pkg/server/tls/authority/authority.go, pkg/server/tls/authority/authority_test.go
Fixes a bug in the `caRequiresRegeneration` function and adds a unit test that fully tests this function.
This bug was introduced in https://github.com/cert-manager/cert-manager/pull/6784, when I tried to fix another issue that could occur when the CADuration value is changed. It went unnoticed due to the lack of tests (something we also made progress towards in #6784).
/kind bug
```release-note
BUGFIX: the dynamic certificate source used by the webhook TLS server failed to detect a root CA approaching expiration, due to a calculation error. This may cause the webhook TLS server to fail renewing it's CA certificate. Please upgrade before the expiration of this CA certificate is reached.
```
=> BUGFIX: fix incorrect tls server renewal time check and add unit tests

pkg/controller/acmechallenges/sync.go, pkg/controller/acmechallenges/sync_test.go
I encountered several ACME challenges that were stuck in bad state, with no associated DNS01 TXT record.
Specifically, in the logs, I saw the error: "challenge was not present in authorization", from pkg/controller/acmechallenges/sync.go:syncChallengeStatus()
Since this error is not of type acmeapi.error, handleError was returning immediately:
```
if acmeErr, ok = err.(*acmeapi.Error); !ok {
return err
}
```
When I tried deleting the challenge manually, the challenge was still not presented to the ACME server, and the code that `Present`'s the challenge is never reached because when `ch.status.State` is empty and `syncChallengeState` returns an error, the Sync method exits immediately. I also looked at the ACME server's console and did not see pending verifications for the domain in …
=> error out ACME Challenges when encountering non-ACME errors

internal/controller/certificates/policies/checks.go, internal/controller/certificates/policies/checks_test.go
This PR:
- sorts the map keys before matching to make sure the returned message is consistent
- separates checking the label/annot. values vs checking the label/annot. keys
This will make sure that the issuance/ ready condition message is consistent for a specific situation (not random due to ordering of map keys).
/kind cleanup
```release-note
NONE
```
=> Improve ordering consistency of policy chain results (issuance, ready ...)

deploy/charts/cert-manager/templates/rbac.yaml
When creating the cert-manager serviceaccount we should include the RBAC permissions to create serviceaccount tokens, which are required when using the incuded serviceaccount for authenticating against AWS IRSA when configuring Route53.
This aligns with the documentation on Route53, where these permissions are only to be created manually when using a different serviceaccount.
Other usecases may apply as well.
Fixes https://github.com/cert-manager/cert-manager/issues/7212
Align with documentation on Route53 & simpify RBAC setup.
```release-note
Create tokenrequest RBAC for the cert-manager serviceaccount by default
```
=> Add RBAC for the serviceaccount to create tokens

pkg/server/tls/authority/authority.go, pkg/server/tls/authority/authority_test.go, pkg/server/tls/dynamic_source_test.go
Adds unit tests and intruces a few minor changes to improve logging and make the test work as expected. Should make the logs a lot more insightful.
/kind cleanup
```release-note
NONE
```
=> Add unit tests for tls authority logic

pkg/issuer/acme/dns/route53/route53.go, pkg/issuer/acme/dns/route53/route53_test.go
The problem we are trying to fix is described in #5486 by @pquerna, as follows:
> When using the Route53 Solver for ACME, I am attempting to use an IRSA (IAM Role for Service Accounts). However, I have a permissions error, causing sts:AssumeRoleWithWebIdentity to fail.
> When this happens, cert-manager goes into an aggressive loop, retrying to delete the challenge.
The reason for the aggressive retry loop is that the errors returned by the AWS SDK contain a unique "request ID",
which cert-manager saves to the `Challenge.Status`, triggering a re-reconcile, and so on:
> error instantiating route53 challenge solver: unable to assume role: WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, 
> …
=> Prevent aggressive Route53 retries caused by STS authentication failures by removing the Amazon Request ID from STS errors

pkg/controller/certificaterequests/vault/fuzz_test.go
Adds a fuzz test that tests certificate requests with the Vault issuer.
The fuzzer randomizes selected fields in the request and the issuer. Sometimes it will choose correct values and sometimes it will choose incorrect ones.
The fuzzer could be expanded by e.g. adding more objects or randomizing more fields, but it would be good to see how this runs on OSS-Fuzz first.
/kind feature
```release-note
NONE
```
=> add fuzz test for cert requests with vault issuer

pkg/util/pki/csr.go
fixes https://github.com/cert-manager/cert-manager/issues/6541
/kind bug
```release-note
We no longer add the KeyUsages x509 extension when there are no key usages set in accordance to RFC 5280 - Section 4.2.1.3.
```
=> BUGFIX: adhere to RFC 5280 - Section 4.2.1.3 and don't include empty KeyUsages extensions

deploy/charts/cert-manager/templates/rbac.yaml, deploy/charts/cert-manager/templates/webhook-rbac.yaml
Fixes #6851
Currently, there are four resources in the Helm chart that use an empty `apiGroup` in their `subjects.ServiceAccount` references. This PR aims to remove these redundant lines.
/kind cleanup
```release-note
NONE
```
=> Helm: Remove empty apiGroup from 'subjects.ServiceAccount' refs

make/licenses.mk
As suggested by @jsoref  on slack: https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1726175654671509
/kind cleanup
```release-note
NONE
```
=> Add further text explaining why we use an old license year

.github/PULL_REQUEST_TEMPLATE.md
Many PRs were left without `kind-` labels. The instructions clearly didn't work for many contributors.
```release-note
NONE
```
=> Clarify how to use the Kind section of the PR template

pkg/issuer/venafi/client/venaficlient.go
- API Keys are deprecated, so providing a user/pass will result in an error
- Previously cert-manager would use these to return an API Key
- Do the same here except instead use the OAuth endpoint to get access_token
- Change Authentication to happen when VerifyCredentials called, not at client creation
feature
TBC - "breaking" in some ways so needs to be clearly documented. Will come back to this.
Potentially resolves: #4653
```release-note
Venafi TPP issuer can now be used with a username & password combination with OAuth. Fixes #4653.
Breaking: cert-manager will no longer use the API Key authentication method which was deprecated in 20.2 and since removed in 24.1 of TPP.
```
To test, I both ran locally against the kind cluster, and build the image and ran it in my cluster.
Here are my …
=> feat: Use OAuth endpoint for Venafi Issuer when user/pass provided

pkg/controller/certificaterequests/venafi/venafi.go, pkg/controller/certificaterequests/venafi/venafi_test.go, pkg/controller/certificatesigningrequests/venafi/venafi.go, pkg/controller/certificatesigningrequests/venafi/venafi_test.go, pkg/issuer/venafi/client/fake/venafi.go, pkg/issuer/venafi/client/request.go, pkg/issuer/venafi/client/request_test.go, pkg/issuer/venafi/client/venaficlient.go
When using Venafi as issuer the specified Duration on the certificate resource does not get passed to Venafi. Therefor only the CA default expire time will be used and it's not possible to override it.
feature
solves https://github.com/cert-manager/cert-manager/issues/6898
```release-note
Now passes down specified duration to venafi client instead of using the CA default only.
```
=> 6898: Add validity duration to Venafi certificates

internal/apis/config/controller/v1alpha1/defaults_test.go, internal/apis/config/webhook/v1alpha1/defaults_test.go, internal/cainjector/feature/features.go, internal/controller/feature/features.go, internal/webhook/feature/features.go, pkg/apis/acme/v1/const.go, pkg/controller/acmechallenges/finalizer.go, pkg/controller/acmechallenges/finalizer_test.go, pkg/controller/acmechallenges/sync.go, pkg/controller/acmechallenges/sync_test.go
#7266
/kind bug
```release-note
Adds support (behind a flag) to use a domain qualified finalizer. If the feature is enabled (which is not by default), it should prevent Kubernetes from reporting:
> metadata.finalizers: "finalizer.acme.cert-manager.io": prefer a domain-qualified finalizer name to avoid accidental conflicts with other finalizer writers
```
=> Support a domain qualified finalizer instead of one that triggers a warning from kubernetes

design/20240625.push-charts-to-oci.md
This design is for us to agree on a path towards pushing cert-manager charts to an OCI registry. Subprojects will follow later.
Related to #5566  and #7117
/kind design
```release-note
NONE
```
=> Add design for pushing charts to OCI registry

pkg/controller/acmechallenges/sync.go, pkg/controller/acmechallenges/sync_test.go, pkg/controller/helper.go, pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/dns_test.go, pkg/issuer/acme/dns/util_test.go, pkg/issuer/acme/http/http.go
At the time of deleting the Challenge resource, the issuer might no longer exist.
We actually do not depend on the configuration of the issuer, we only use the issuer reference that is in the Challenge object.
/kind cleanup
```release-note
NONE
```
=> Remove issuer argument from CleanUp function

.golangci.yaml, pkg/acme/webhook/registry/challengepayload/challenge_payload.go, pkg/controller/acmeorders/sync.go, pkg/controller/certificate-shim/sync_test.go, pkg/controller/test/context_builder.go, pkg/issuer/acme/setup.go, pkg/util/pki/generate_test.go, test/e2e/suite/certificaterequests/approval/userinfo.go, test/e2e/suite/certificates/secrettemplate.go, test/e2e/suite/issuers/acme/certificate/webhook.go
depends on #7242
Fixes remaining linter violations and enables the linters in `.golangci.yaml`.
/kind cleanup
```release-note
NONE
```
=> Enable and fix usestdlibvars, misspell and staticcheck linters

deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, internal/apis/certmanager/validation/issuer.go, internal/apis/certmanager/validation/issuer_test.go, pkg/apis/acme/v1/types_issuer.go, test/integration/validation/files/issuers.valid.yaml, test/integration/validation/issuer_test.go
When you install cert-manager on EKS and use IAM Roles for Service Accounts or Pod Identity,
an AWS mutating webhook will add `AWS_REGION` and `AWS_DEFAULT_REGION` environment variables to the controller Pod. There's no need to specify the region in the Issuer config so it should not be a required field.
> 📖 Read [Grant Kubernetes workloads access to AWS using Kubernetes Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/service-accounts.html) to learn more about these two mechanisms.
AWS Route53 is a [global service](https://docs.aws.amazon.com/whitepapers/latest/aws-fault-isolation-boundaries/global-services.html) and does not have regional endpoints.
The AWS SDK for Go V2 uses the region (whether supplied or detected from environment variables) as a hint,
with which to …
=> Optional AWS Route53 region

pkg/server/tls/authority/authority.go
When tracking down unowned secrets in a cluster, I noticed `secret/cert-manager-webhook-ca` does not specify `app.kubernetes.io/managed-by`.
This label is useful when filtering out managed Secrets in a multi-tenant cluster to generate reports or alerts.
Helm applies this label to resources it manages.
Set the string to "cert-manager" since it is responsible for generating and regenerating the CA.
https://kubernetes.io/docs/reference/labels-annotations-taints/#app-kubernetes-io-managed-by
feature
```release-note
Added app.kubernetes.io/managed-by: "cert-manager" to cert-manager-webhook-ca
```
=> Add managed-by label to webhook CA

pkg/issuer/acme/dns/route53/route53.go
Allows you to see which API endpoints are being used and which region is being used in the request signature.
To help debug AWS Route53 problems in the field.
Here's how it looks at `-v 4` with JSON logging enabled and using `jl` to parse the logs:
```
[2024-09-20 14:31:37] preparing to create Route53 provider [caller=dns/dns.go:296 dnsName=75b2296e-65a9-4c25-954b-d0b283c6bfd2.com domain=75b2296e-65a9-4c25-954b-d0b283c6bfd2.com logger=cert-manager.controller.Present.solverForChallenge resource_kind=Challenge resource_name=www-1-2762490819-1292702510 resource_namespace=default resource_version=v1 type=DNS-01]
[2024-09-20 14:31:37] using ambient credentials [caller=route53/route53.go:99 logger=cert-manager.route53-session-provider]
[2024-09-20 14:31:37] presenting DNS01 challenge for domain …
```
=> Log AWS SDK warnings and API requests at cert-manager debug level

deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, pkg/apis/acme/v1/types_issuer.go, pkg/issuer/acme/dns/route53/route53.go, pkg/issuer/acme/dns/route53/route53_test.go
The code was conflating "ambient credentials" with "ambient region".
On a multi tenant cluster, you should not allow tenants to use the "ambient credentials". For example, the instance role (and associated temporary access key) provided by the EC2 instance metadata service.
Especially if that instance role has been attached to a Policy that grants Route53 permissions.
But there is no risk in allowing cert-manager to use the "ambient region" from AWS_REGION and AWS_DEFAULT_REGION environment variables. Both Issuer and ClusterIssuer linked challenges should be able to use those variables because it saves the application teams from having to know the AWS region of the node where cert-manager is scheduled.
But they can still override the region by adding it to the Issuer, if their Route53 …
=> Route53 DNS01 Solver: Always fall back on the ambient region

gcb/build_cert_manager.yaml
Fixes: https://github.com/cert-manager/cert-manager/issues/7307
* https://github.com/cert-manager/cert-manager/issues/7307
I tested this change by making the same changes to the cloudbuild.yaml in the release repo.
See the "Testing" section in the description of https://github.com/cert-manager/release/pull/189
* https://github.com/cert-manager/release/pull/189
/kind cleanup
```release-note
NONE
```
=> Fix makestage OOM failures

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/startupapicheck-job.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/values.schema.json, deploy/charts/cert-manager/values.yaml
Fixes: #7316 
* #7316 
```release-note
Helm: New value `webhook.extraEnv`, allows you to set custom environment variables in the webhook Pod.
Helm: New value `cainjector.extraEnv`, allows you to set custom environment variables in the cainjector Pod.
Helm: New value `startupapicheck.extraEnv`, allows you to set custom environment variables in the startupapicheck Pod.
```
I tested this by installing cert-manager with the following Helm values, to enable the WatchListClient feature in all the components.
```yaml
global:
logLevel: 6
extraEnv:
- name: KUBE_FEATURE_WatchListClient
value: "true"
cainjector:
extraEnv:
- name: KUBE_FEATURE_WatchListClient
value: "true"
webhook:
extraEnv:
- name: KUBE_FEATURE_WatchListClient
value: "true"
startupapicheck:
extraEnv:
- name: …
```
=> Allow extra environment variables to be added to  cainjector, webhook and startupapicheck

pkg/controller/helper.go, pkg/controller/test/context_builder.go, pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/dns_test.go
fixes https://github.com/cert-manager/cert-manager/issues/7331
see https://github.com/cert-manager/cert-manager/pull/7285#discussion_r1789623611
TODO: in a follow-up PR, we have to figure out why there is no e2e test that tests ACME cluster issuers with Secrets.
/kind bug
```release-note
❗BUGFIX: A change in v1.16.0 caused cert-manager's ACME ClusterIssuer to look in the wrong namespace for resources required for the issuance (eg. credential Secrets). This is now fixed in v1.16.1.
```
=> BUGFIX: use correct resource namespace for Cluster Issuers

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/values.schema.json, deploy/charts/cert-manager/values.yaml
Fixes https://github.com/cert-manager/cert-manager/issues/7340
For `podDisruptionBudget.minAvailable` and `podDisruptionBudget.maxAvailable`, we should accept both string and integer values.
Affected values:
- podDisruptionBudget.minAvailable
- cainjector.podDisruptionBudget.minAvailable
- webhook.podDisruptionBudget.minAvailable
- podDisruptionBudget.maxAvailable
- cainjector.podDisruptionBudget.maxAvailable
- webhook.podDisruptionBudget.maxAvailable
/kind bug
```release-note
BUGFIX: Helm will now accept percentages for the podDisruptionBudget.minAvailable and podDisruptionBudget.maxAvailable values.
```
=> BUGFIX: Update schema validation to accept both string and integer values

deploy/charts/cert-manager/values.linter.exceptions, deploy/charts/cert-manager/values.schema.json, deploy/charts/cert-manager/values.yaml
Fixes https://github.com/cert-manager/cert-manager/issues/7334#issuecomment-2396066624 and part 2 from https://github.com/cert-manager/cert-manager/issues/7334#issuecomment-2397034886
Similar to https://github.com/open-telemetry/opentelemetry-helm-charts/pull/262
/kind bug
```release-note
Helm: allow `enabled` to be set as a value to toggle cert-manager as a dependency.
```
=> Helm: add enabled to json schema

cmd/acmesolver/go.mod, cmd/cainjector/go.mod, cmd/controller/go.mod, cmd/startupapicheck/go.mod, cmd/webhook/go.mod, go.mod, pkg/util/pki/parse_certificate_chain_test.go, test/e2e/framework/addon/globals.go, test/e2e/framework/framework.go, test/e2e/go.mod, test/integration/go.mod
See go 1.23 release notes (https://go.dev/doc/go1.23) which describes the new feature.
This PR introduces some std-lib iterators where useful.
/kind cleanup
```release-note
NONE
```
=> Use new go 1.23 iterators

pkg/controller/certificates/issuing/issuing_controller.go, pkg/controller/certificates/requestmanager/requestmanager_controller.go, test/e2e/suite/certificates/foregrounddeletion.go, test/e2e/util/util.go
If you delete a Certificate resource with ["foreground" cascading deletion](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion), the child objects such as the Secret and the CertificateRequest objects will be deleted first. This causes the Certificate controllers to re-create these even though the Certificate resource is being deleted itself.
We can check if a Certificate is being deleted by testing the metadata.deletionTimestamp field is set, this PR adds this test to the controllers responsible for creating the CertificateRequest and Secret objects.
resolves #7358
/kind bug
```release-note
The Certificate object will no longer create CertificateRequest or Secret objects while being deleted
```
=> fix: don't create certificaterequests while being deleted

cmd/controller/app/options/options.go
Inspired by #5538
```release-note
Add example for ipv6 in --dns01-recursive-nameservers
```
=> add IPv6 example for recursive DNS arg

cmd/controller/app/options/options.go
Manual backport of #7367
```release-note
NONE
```
=> [release-1.16] add IPv6 example for recursive DNS arg

pkg/controller/certificaterequests/ca/ca.go, pkg/controller/certificaterequests/selfsigned/selfsigned.go, pkg/util/pki/csr.go, pkg/util/pki/csr_test.go
See also #7357
A [US DoD document](https://dl.dod.cyber.mil/wp-content/uploads/pki-pke/pdf/unclass-memo_dodcryptoalgorithms.pdf) states that:
> Effective immediately, all Public Key enabled commercial-off-the-shelf
> software and Public Key enabled Open-Source software integrations [...]
> must support at least RSA-3072 (4096 is preferred) and SHA-384.
cert-manager already supports large RSA keys - that's no problem. But we always use SHA256 with all RSA keys currently; this commit changes that so we use SHA512 for RSA keys 4096 bits and above, or else SHA384 for RSA keys 3072 bits and above, or else SHA256.
We discussed in standups / in the issue how to roll this out, and the consensus so far has been to roll this out unilaterally. Albeit we don't have data to support our assumption, we …
=> Use different hash algorithms for larger RSA keys

internal/apis/certmanager/validation/certificate.go, internal/apis/certmanager/validation/certificate_test.go, pkg/acme/util/util.go, pkg/controller/certificate-shim/helper.go, test/e2e/framework/addon/vault/setup.go, test/e2e/framework/addon/vault/vault.go
Spotted these while doing other work; these are simple cleanups and improvements which should have no observable impact.
Each commit is self-contained and can be reviewed individually.
Description of changes:
1) Use `math/rand/v2` for calculating acme jitter. We don't need cryptographically secure RNG there and the resulting code is much simpler.
2) Change hardcoded magic numbers to reference Min/Max RSA key size vars we already have.
3) Change calls (mostly in tests) to the stdlib key generation to use our functions instead.
4) Add error handling in vault e2e addon. Panicing is fine here - better IMO than not knowing if an error occurred in these functions
/kind cleanup
```release-note
NONE
```
=> Cleanup key gen / RSA key sizes

deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, internal/apis/acme/types_issuer.go, internal/apis/acme/v1/zz_generated.conversion.go, internal/apis/certmanager/validation/issuer.go, internal/apis/certmanager/validation/issuer_test.go, pkg/apis/acme/v1/types_issuer.go, pkg/issuer/acme/dns/azuredns/azuredns.go
With using managed identity for AzureDNS it's possible to use a service principal as a managed identity. For service principals it's possible to use it in multiple organization. [Example for multitenant service principal](https://learn.microsoft.com/en-us/azure/container-registry/authenticate-aks-cross-tenant)
You can use federated credentials for service principals in the same way as for[ managed identities](https://learn.microsoft.com/en-us/entra/workload-id/workload-identity-federation-create-trust?pivots=identity-wif-apps-methods-azp)
So if our DNS Zone is in a different tenant than cert-manager we can use this behavior but we have to specify a tenantID.
With this pull request a tenantID option will be added to the managedIdentity section for AzureDNS
/kind
```release-note
New …
```
=> add tenantID option to azureDNS managedIdentity

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
This PR cmd/cmctl's go.mod to v1.12.14 as part of the release process.
```release-note
NONE
```
=> [Release v1.12.14] Update cmd/cmctl's go.mod to v1.12.14

pkg/util/pki/renewaltime.go, pkg/util/pki/renewaltime_test.go
- Fixes https://github.com/cert-manager/cert-manager/issues/7420
Setting `renewBeforePercentage` to x now makes the certificate renew when there is x percent of its duration left *before* its expiry. For example, if the validity duration of a certificate is 180 minutes, and `renewBeforePercentage` is set to 25, the certificate will renew after 135 minutes, i.e. when there is 25% of its duration left.
This now means the behaviour is in accordance with the spec of `renewBeforePercentage`.
Before this patch, the behaviour was reversed, whereby the certificate would renew *after* x percent of its duration, not *before*. For example, for a certificate valid for 180 minutes, it would renew after 45 minutes.
/kind bug
```release-note
Fix the behaviour of `renewBeforePercentage` to comply with …
```
=> Fix renewBeforePercentage to comply with its spec

deploy/charts/cert-manager/templates/cainjector-service.yaml
When installing cert-manager using helm chart with `cainjector.enabled: false`, service for cainjector is still going to be created. This PR addresses this small issue.
/kind bug
```release-note
NONE
```
=> fix: don't install cainjector service when cainjector is disabled

test/e2e/framework/framework.go, test/e2e/framework/helper/validate.go, test/e2e/framework/helper/validation/certificaterequests/certificaterequests.go, test/e2e/framework/helper/validation/certificates/certificates.go, test/e2e/framework/helper/validation/validation.go, test/e2e/suite/issuers/ca/certificate.go, test/e2e/suite/issuers/ca/certificaterequest.go, test/e2e/suite/issuers/selfsigned/certificate.go, test/e2e/suite/issuers/selfsigned/certificaterequest.go, test/e2e/suite/issuers/vault/certificate/approle.go, test/e2e/suite/issuers/vault/certificate/cert_auth.go, test/e2e/suite/issuers/vault/certificaterequest/approle.go
Moves validation functions to helper. This groups them with the other existing validation functions.
/kind cleanup
```release-note
NONE
```
=> Move duration validation test functions to helper

pkg/controller/clusterissuers/controller.go, pkg/controller/issuers/controller.go
This will make the controller more responsive in case the issuer has accumulated a high back-off timeout and the Secret is updated to fix the problem.
AddRateLimited explained: https://github.com/kubernetes/client-go/blob/master/util/workqueue/rate_limiting_queue.go#L30-L31
/kind bug
```release-note
The issuer will now more quickly retry when its linked Secret is updated to fix an issue that caused a high back-off timeout.
```
=> Enqueue the (Cluster)Issuer using Add instead of AddRateLimited when linked Secret is updated

cmd/controller/app/controller.go, internal/informers/core.go, internal/informers/core_basic.go, internal/informers/core_filteredsecrets.go
Call the `Shutdown()` function on all informer factories before shutting down. See https://github.com/kubernetes/client-go/blob/v0.31.3/informers/factory.go#L263 for more info.
/kind cleanup
```release-note
NONE
```
=> Add Shutdown function to KubeInformerFactory interface and call Shutdown on shutdown

pkg/api/util/conditions.go, pkg/controller/acmechallenges/sync.go, pkg/controller/certificate-shim/sync.go, pkg/controller/certificatesigningrequests/util/conditions.go, pkg/issuer/acme/dns/akamai/akamai.go, pkg/issuer/acme/dns/rfc2136/rfc2136.go, pkg/issuer/acme/dns/util/wait.go, pkg/issuer/vault/setup.go, pkg/logs/logs.go
There were still a few remaining non-structured logging instructions in the source code (all using the `logs.V` function).
This PR replaces those log instructions with structured variants and uses contextual logging when possible.
This is the e2e log output showing the new log messages:
https://storage.googleapis.com/cert-manager-prow-artifacts/pr-logs/pull/cert-manager_cert-manager/7461/pull-cert-manager-master-e2e-v1-31/1867140272089993216/artifacts/cert-manager-e2e-logs/kind-control-plane/containers/cert-manager-7fbf57fd9f-tzfql_cert-manager_cert-manager-controller-c49323e77ad827f378b66ea45af91000cbb575e021f5c20b0f17c025da717d31.log
All keys are in [lowerCamelCase](https://en.wiktionary.org/wiki/lowerCamelCase) following these guidelines: …
=> Replace all remaining non-structured logging (logs.V function)

deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml
#7137
```yaml
serviceAccount:
create: false
name: user-created-sa
global:
imagePullSecrets:
- name: image-pull-secret
image:
repository: private-repo.jfrog.io/jetstack/cert-manager-controller
```
In the event we don't create a service account, the deployments don't have the context of image pull secrets unless the user knows to add it to the service account they created.
This adds the global image pull secrets to all deployments if its respective service account is disabled.
/kind
```release-note
Added image pull secrets to deployments when service accounts aren't created
```
=> Add imagePullSecrets to deployments if the service account is not created

internal/pem/decode.go, internal/pem/decode_test.go, pkg/controller/acmeorders/sync_test.go, pkg/util/pki/parse.go
Follow up to #7400
A [slack discussion](https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1733440158060159) reported that the size limit for `SafeDecodeMultipleCertificates` was too small in the case that a user was trying to decode a trust store (such as a publicly trusted cert bundle).
That use case wasn't really captured before because cert-manager (the repo) doesn't really concern itself with trust stores. The issue is that other projects import cert-manager as a library and can use `DecodeX509CertificateSetBytes` to parse a trust bundle. For example, [istio-csr uses `DecodeX509CertificateChainBytes` to decode trust bundles](https://github.com/cert-manager/istio-csr/blob/a8b288583b61e3ce6df5c29ecee24515441186d0/pkg/tls/rootca/rootca.go#L139-L166).
There's an important distinction …
=> Add specialised PEM decoder for trust bundles

.trivyignore
The trivy scanner is reporting a vulnerability in the Debian 11 distroless base image used in cert-manager 1.12.
[Debian 11 is no longer supported by the distroless project](https://github.com/GoogleContainerTools/distroless/pull/1656) so we have no easy way to fix this without upgrading to Debian 12.
which would be too big a change for a cert-manager 1.12 patch release.
So we have decided to ignore that warning, for the sake of stopping the daily testgrid failures.
The next version of cert-manager 1.12 may still be flagged as having a vulnerability of unknown rating by scanners [such as used by ArtifactHub](https://artifacthub.io/packages/helm/cert-manager/cert-manager/1.12.14?modal=security-report):
cert-manager 1.15 and 1.16 use Debian 12 base images which have an up to date tzdata …
=> [release-1.12] Ignore the Trivy vulnerability warning for DLA-3972-1

cmd/controller/app/options/options.go
`ValidateCAA` hasn't progressed for ages, it doesn't have test coverage or a champion.
/kind cleanup
```release-note
Deprecated: `ValidateCAA` with removal scheduled for 1.18.
```
=> Deprecate ValidateCAA

pkg/issuer/venafi/client/venaficlient.go, pkg/issuer/venafi/client/venaficlient_test.go
- The goal of the PR is to remove statically defined `clientID` for the venafi client and make it customizable by the user 
- Add the ability to add `client-id` in the TPP secret defined by the user 
/kind feature
related topics: 
- https://github.com/cert-manager/cert-manager/pull/7084#discussion_r1644641090
- https://github.com/cert-manager/cert-manager/issues/4653#issuecomment-2566570151
```release-note
Added the ability to customize client ID when using username/password authentification for venafi client
```
- https://github.com/cert-manager/website/pull/1618
=> add ability to inject client-id in tpp secret venafi

internal/kube/config.go, internal/webhook/webhook.go, pkg/controller/context.go
https://github.com/cert-manager/cert-manager/issues/7251
Remove unnecessary warnings coming from kubeclient.
/cleanup
```release-note
Remove `Neither --kubeconfig nor --master was specified` warning message when the controller and the webhook services boot
```
=> remove unnecessary warning when booting the controller and the webhook service

internal/cainjector/bundle/bundle.go, internal/cainjector/bundle/bundle_test.go, internal/cainjector/feature/features.go, make/e2e-setup.mk, pkg/controller/cainjector/injectables.go, test/e2e/suite/serving/cainjector.go
Currently the ca-injector replaces the bundle in the webhook configuration whenever the cert is renewed, however if the pod backing the webhook is slow to pick up the change then it may still be presenting the old cert.
This adds a feature to the ca-injector to instead merge the new ca into the bundle. It also removes expired certificates from the bundle to ensure it does not just continue to grow in size each rotation.
/kind feature
```release-note
Add CAInjectorMerging feature gate to the ca-injector, enabling this will change the behaviour of the ca-injector to merge in new CA certificates instead of outright replacing the existing one.
```
=> feat: gated feature to have ca-injector merge in and not replace the ca bundle

hack/build/version.sh
While responding to [this email](https://groups.google.com/g/cert-manager-dev/c/rn7OwGLweyE/m/f0_DnjaMCQAJ) on the mailing list, I noted that the logs [2] were indicating that the upgrade test was always upgrading from 1.9.2 to 1.16.2. 1.9.2 has long been deprecated, and I found that there is a bug in the "finding out the latest cert-manager tag" logic that force `make test-upgrade` to use 1.9.2 instead of the actual latest tag.
[1]: https://github.com/cert-manager/testing/blob/3abe3250b30370c700f4226e79ad4b3e99e89087/config/jobs/cert-manager/cert-manager/release-1.16/cert-manager-release-1.16.yaml#L913C17-L913C24
[2]: https://prow.infra.cert-manager.io/view/gs/cert-manager-prow-artifacts/logs/ci-cert-manager-release-1.16-e2e-v1-31-upgrade/1875263680220762112
/kind cleanup
```release-note …
```
=> make test-upgrade was stuck using 1.9.2 as a starting point

cmd/acmesolver/app/app.go
acmesolver exits with an error "http: Server closed" and the `--help` output on success. Ignore `http.ErrServerClosed` to fix this.
/kind cleanup
```release-note
NONE
```
=> acmesolver: Fix error message on successful exit

make/_shared/tools/00_mod.mk
Bump go to 1.23.6 to address CVE-2025-22866 reported by Trivy
/kind bug
```release-note
Bump go to 1.23.6 to address CVE-2025-22866 reported by Trivy
```
=> [release-1.16] bump go to v1.23.6

make/_shared/klone/01_mod.mk, make/_shared/tools/00_mod.mk
Bump go to 1.23.6 to address CVE-2025-22866 reported by Trivy
See also #7562
/kind bug
```release-note
Bump go to 1.23.6 to address CVE-2025-22866 reported by Trivy
```
=> [release-1.17] Bump go to v1.23.6

pkg/issuer/acme/dns/cloudflare/cloudflare.go
Cloudflare have stopped including zone IDs in their record responses now, 2 months after they said they did and with their trademark zero effort in outreach to consumers of their API. Ensure that findTxtRecord returns a record struct with the zone ID set regardless.
Fixes #7540
Make issuing certificates using DNS01 challenges work on Cloudflare again.
/kind bug
```release-note
Fix issuing of certificates via DNS01 challenges on Cloudflare
```
=> chore(issuer/cloudflare): ensure we set ZoneID

pkg/issuer/acme/dns/cloudflare/cloudflare.go
Cloudflare have stopped including zone IDs in their record responses now, 2 months after they said they did and with their trademark zero effort in outreach to consumers of their API. Ensure that findTxtRecord returns a record struct with the zone ID set regardless.
Fixes #7540
(Manual cherry pick of #7549 fixed up to apply cleanly)
NB: Since release-1.12 doesn't include #6191 (it wasn't ever backported), users issuing with Cloudflare on cert-manager v1.12.x are strongly encouraged to upgrade to a newer version. We'll have to mention that in the release notes for v1.12.16
/kind bug
```release-note
Fix issuing of certificates via DNS01 challenges on Cloudflare after a breaking change to the Cloudflare API
```
=> [release-1.12] chore(issuer/cloudflare): ensure we set ZoneID

deploy/crds/crd-certificaterequests.yaml, deploy/crds/crd-certificates.yaml, deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, deploy/crds/crd-orders.yaml, make/tools.mk, pkg/webhook/handlers/testdata/apis/testgroup/crds/testgroup.testing.cert-manager.io_testtypes.yaml
The version of Go used for release-1.12 hasn't been supported for a while now, and right now the next supported version is go1.23.x which will be supported past the remaining lifetime of 1.12.x LTS
This commit bumps to a supported version of Go to address several reported vulnerabilties present in the image for cert-manager v1.12.15 including:
- CVE-2024-34156
- CVE-2024-34155
- CVE-2024-34158
- CVE-2024-45336
- CVE-2024-45341
- CVE-2025-22866
The old version of controller-gen panics when used with a newer version of Go, for reasons I don't have time to investigate. This requires an update to controller-gen to fix, and that in turn changes the formatting of descriptions in the CRDs we generate.
Supersedes #7567 
/kind bug
```release-note
Bump go to 1.23.6, fixing several CVEs:
- …
```
=> [release-1.12] bump go to supported version

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
This PR cmd/cmctl's go.mod to v1.12.16 as part of the release process.
```release-note
NONE
```
=> [Release v1.12.16] Update cmd/cmctl's go.mod to v1.12.16

pkg/controller/certificate-shim/sync.go, pkg/controller/certificate-shim/sync_test.go
I've tried to fix #6985 combining HTTPS listeners with TLS-termination and TLS listeners with TLS-passthrough that I reported earlier.
I'm unsure if this change will introduce unwanted behaviour, though all the tests are passing.
bug
```release-note
Skip Gateway TLS-listeners in passthrough mode
```
=> Skip gateway TLS listener in passthrough mode

pkg/metrics/certificates_test.go, pkg/metrics/metrics.go, test/integration/certificates/metrics_controller_test.go
As indicated by its name, the `certmanager_certificate_renewal_timestamp_seconds` metric reports the timestamp where cert-manager will begin to attempt renewal of a certificate. The current description states:
> The number of seconds before expiration time the certificate should renew.
The description current states that the value is relative to the expiration time (`certmanager_certificate_expiration_timestamp_seconds`), rather than absolute with respect to Unix epoch time.
[This line](https://github.com/cert-manager/cert-manager/blob/ee6a12d57a8947e37368ac6ffeaed4868a744e00/pkg/metrics/certificates.go#L52) shows that this metric is populated via `Status.RenewalTime.Unix()`, and does not take into account the expiration time.
The expiration metric …
=> Fix `certmanager_certificate_renewal_*_seconds` incorrect descriptions

deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, internal/apis/certmanager/types_issuer.go, pkg/apis/certmanager/v1/types_issuer.go
The default is set by VCert.
The main motivation for this change is to help users who're trying to set a different URL; they need to not include the `v1`.
```release-note
NONE
```
=> Fix incorrect default in venafi issuer docs

pkg/issuer/acme/dns/util/wait_test.go
I mistakenly thought we weren't running these any more, but we are and this change breaks all CI.
We should remove these tests, but that's not for now. For now, just fix the test
/kind bug
```release-note
NONE
```
=> fix DNS test broken by upstream change

pkg/issuer/acme/setup.go
I've noticed that the secrets created by the ACME account setup do not specify the label "app.kubernetes.io/managed-by". This allows attributing secrets without a controller owner reference to the system response for them.
This label is already used by cert-manager for the CA secret created for the API webhook.
/kind feature
```release-note
Added `app.kubernetes.io/managed-by: cert-manager` label to the created Let's Encrypt account keys
```
=> add managed-by label to ACME account key

pkg/metrics/certificates.go, pkg/metrics/certificates_test.go, pkg/metrics/metrics.go, test/integration/certificates/metrics_controller_test.go
Currently, there are no metrics exposed for certificates that show information about when a certificate was issued. This makes it difficult to determine how long it will be until a certificate expires, relative to how long it was issued for. This is important for monitoring of renewals, as alerts and dashboards based around absolute threshold (e.g. an alert when a certificate is 2 weeks from expiring) are largely useless when using a mix of short lived and long lived certificates. This mix of short and long lived certificates is somewhat common, where root CAs may be issued for years, intermediary CAs issued for months, and leaf certs issued for days or hours.
To address this, this PR adds a `certmanager_certificate_not_before_timestamp_seconds` metric, who's value is the timestamp before …
=> feat: Add certificate issuance time and duration metrics

make/e2e-setup.mk, pkg/issuer/acme/dns/util/wait_test.go
This is because of consistently breaking tags upstream
See also #7631
We also need to fix the DNS tests which we want to remove, because of a changed record upstream.
/kind bug
```release-note
NONE
```
=> [release-1.17] Use cert-manager mirrored version of bind + fix dns test

cmd/controller/app/controller.go, cmd/controller/app/options/options.go, cmd/controller/app/start_test.go, internal/apis/config/controller/types.go, internal/apis/config/controller/v1alpha1/defaults.go, internal/apis/config/controller/v1alpha1/zz_generated.conversion.go, internal/apis/config/controller/zz_generated.deepcopy.go, pkg/apis/config/controller/v1alpha1/types.go, pkg/apis/config/controller/v1alpha1/zz_generated.deepcopy.go, pkg/controller/certificate-shim/sync.go, pkg/controller/certificate-shim/sync_test.go, pkg/controller/context.go
Some setups have a requirement to have custom-field annotation set on Certificate object.
This commit introduces an ingress-shim option:
* --extra-certificate-annotations which sets list of annotation keys to be copied from Ingress-like to resulting Certificate object
feautre
```release-note
Added ingress-shim option:
* --extra-certificate-annotations which sets list of annotation keys to be copied from Ingress-like to resulting Certificate object
```
=> ingress-shim: optionally copy specific annotation

deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, internal/apis/certmanager/types_issuer.go, internal/apis/certmanager/v1/zz_generated.conversion.go, internal/vault/vault.go, internal/vault/vault_test.go, pkg/apis/certmanager/v1/types_issuer.go
Allows the server name used to validate Vault certificates to be configured. This is for the use case where Vault is hosted in cluster, has a public certificate, but you want to access it over the *.cluster.local address to avoid going out and back into the cluster.
resolves #7661
/kind feature
```release-note
Add config to the Vault issuer to allow the server-name to be specified when validating the certificates the Vault server presents.
```
=> feat: allow server name to be set on the vault client

pkg/issuer/acme/dns/route53/route53_test.go
Hi,
The unit test for Route53 in `pkg/issuer/acme/dns/route53/` loads any existing AWS configuration which invalid the test.
This PR sets a dummy AWS configuration file by setting `AWS_CONFIG_FILE` to a non-existing file to ensure the AWS SDK loads without configuration.
Thanks for the Contribfest event in Kubecon London.
=> Fix Route53 unit test

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/rbac.yaml, deploy/charts/cert-manager/values.schema.json, deploy/charts/cert-manager/values.yaml
This open [issue](https://github.com/cert-manager/cert-manager/issues/7598) highlights that the ClusterRole `...-controller-challenges` would be able to create arbitrary pods in any namespace which means that an attacker who compromised the cert-manager controller could probably escalate their privileges to cluster-admin level. For this reason some people deploy their own roles to prevent this from happening and turning off the deployment of rbac via `global.rbac.create` means they have to deploy all the roles on their own. This PR provides a more fine-grained way of turning off the challenger role only.
/kind feature
```release-note
Adds the `global.rbac.disableHTTPChallengesRole` helm value to disable HTTP-01 ACME challenges. This allows cert-manager to drop its permission to create …
```
=> More fine-grained control over powerful RBAC permission granted via Helm chart

pkg/issuer/acme/dns/cloudflare/cloudflare.go
Cloudflare have stopped including zone IDs in their record responses now. Ensure that findTxtRecord returns a record struct with the zone ID set. 
Fixes [7540](https://github.com/cert-manager/cert-manager/issues/7540)
/kind bug
```release-note
Fix issuing of certificates via DNS01 challenges on Cloudflare after a breaking change to the Cloudflare API
```
=> [release-1.15] chore(issuer/cloudflare): ensure we set ZoneID

internal/controller/certificates/policies/gatherer_test.go, pkg/controller/certificates/revisionmanager/revisionmanager_controller_test.go, pkg/controller/certificates/trigger/trigger_controller_test.go, pkg/metrics/certificates_test.go, pkg/metrics/metrics_test.go, pkg/server/tls/authority/authority_test.go, pkg/server/tls/file_source_test.go, test/integration/rfc2136_dns01/provider_test.go, test/integration/rfc2136_dns01/rfc2136_test.go, test/integration/webhook/dynamic_authority_test.go, test/integration/webhook/dynamic_source_test.go, test/webhook/testwebhook.go
While looking at some code I want to work with, I noticed that the [logr testing package](https://pkg.go.dev/github.com/go-logr/logr@v1.4.2/testing) is deprecated. This PR migrates all usage to the replacement [testr package](https://pkg.go.dev/github.com/go-logr/logr@v1.4.2/testr).
/kind cleanup
```release-note
NONE
```
=> Migrate usage of deprecated logr testing package

go.mod, pkg/controller/acmechallenges/scheduler/scheduler_test.go, pkg/issuer/acme/http/ingress_test.go, pkg/issuer/acme/http/service.go, pkg/issuer/acme/http/service_test.go, test/e2e/framework/addon/vault/setup.go, test/e2e/suite/issuers/acme/certificate/http01.go, test/e2e/util/util.go
I noticed the use of deprecated code that was simple to migrate. It's mainly changing test code, but please let me know if I should split this up.
/kind cleanup
```release-note
NONE
```
=> Migrate use of deprecated functions/fields

cmd/cainjector/app/controller.go, cmd/controller/app/controller.go, internal/webhook/webhook.go, pkg/server/tls/authority/authority.go, pkg/server/tls/authority/authority_test.go
Mainly motivated by the ability to address https://github.com/cert-manager/approver-policy/issues/505, but also to clean up the somehow misleading CA secret labels and CA subject CN.
In this PR, I suggest setting more exact managed-by labels based on the workload using the dynamic authority. But it could also make sense to set `app.kubernetes.io/managed-by: cert-manager` for all use in this project. It depends on whether we consider cert-manager the app here or the components in cert-manager as dedicated apps.
I am tempted to change the CA subject CN, as it appears a bit misleading for all the currentuse of the DynamicAuthority, but I am unsure of the consequences. Please advice!
/kind cleanup
```release-note
NONE
```
=> Make DynamicAuthority CN and secret labels configurable

deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml
As suggested in #7268 this adds short names for these resources.
/kind feature
```release-note
Added the `iss` short name for the cert-manager `Issuer` resource
Added the `ciss` short name for the cert-manager `ClusterIssuer` resource
```
=> Add short names for Issuer and ClusterIssuer

make/config/kind/cluster.yaml
Adds a comment that explains how to trust a corporate CA that is trusted by the host machine already.
```release-note
NONE
```
=> Add note to kind configuration explaining how to configure it to trust a MITM corporate VPN CA

.github/workflows/scorecards.yml
My forks often have a different default branch than upstreams. cert-manager's scorecard workflow ❌ when i pull in upstream master which is annoying.
https://github.com/check-spelling-sandbox/cert-manager/actions/runs/13138950431
/kind bug
```release-note
NONE
```
=> skip score cards for forks with other default branches

test/e2e/suite/issuers/acme/certificaterequest/dns01.go, test/e2e/suite/issuers/acme/certificaterequest/http01.go, test/e2e/suite/issuers/ca/certificaterequest.go, test/e2e/suite/issuers/vault/certificaterequest/approle.go, test/e2e/suite/issuers/venafi/tpp/certificaterequest.go
I noticed the deprecated test helper `NewCertManagerBasicCertificateRequest` was currently in use. This removes all usage of the helper in this project, but I've kept the function as others might still be using it.
/kind cleanup
```release-note
NONE
```
=> Remove remaining usage of deprecated CertificateRequest test helper

cmd/controller/app/controller.go, cmd/controller/app/options/options.go, internal/apis/config/controller/v1alpha1/defaults.go, pkg/controller/certificaterequests/selfsigned/selfsigned.go
The controller [CLI reference](https://cert-manager.io/docs/cli/controller/) documents parameter `--namespace string`
> If set, this limits the scope of cert-manager to a single namespace and ClusterIssuers are disabled. If not specified, all namespaces will be watched
Currently, even if providing the parameter cert-manager still attempts to access cluster-scoped resources. As a result, it fails to operate correctly if deployed without cluster-wide RBAC permissions. Following error gets repreatedly printed:
```
W0411 17:31:32.444733       1 reflector.go:569] k8s.io/client-go@v0.32.0/tools/cache/reflector.go:251: failed to list *v1.ClusterIssuer: clusterissuers.cert-manager.io is forbidden: User "system:serviceaccount:cert-manager:cert-manager" cannot list resource "clusterissuers" in API …
```
=> Fix behavior when running with --namespace=<namespace>

pkg/controller/acmechallenges/controller.go, pkg/controller/acmeorders/controller.go, pkg/controller/certificate-shim/gateways/controller.go, pkg/controller/certificate-shim/ingresses/controller.go, pkg/controller/certificaterequests/controller.go, pkg/controller/certificates/issuing/issuing_controller.go, pkg/controller/certificates/keymanager/keymanager_controller.go, pkg/controller/certificates/readiness/readiness_controller.go, pkg/controller/certificates/requestmanager/requestmanager_controller.go, pkg/controller/certificates/revisionmanager/revisionmanager_controller.go, pkg/controller/certificates/trigger/trigger_controller.go, pkg/controller/certificatesigningrequests/controller.go, pkg/controller/clusterissuers/controller.go, pkg/controller/issuers/controller.go
Continuation of the work started in https://github.com/cert-manager/cert-manager/pull/7361.
Should additionally make the logs less noisy.
/kind cleanup
```release-note
NONE
```
=> Don't unnecessarily reconcile resources marked for deletion and don't log that a resource no longer exist

pkg/issuer/acme/dns/route53/fixtures_test.go, pkg/issuer/acme/dns/route53/route53.go, pkg/issuer/acme/dns/route53/route53_test.go
In https://github.com/cert-manager/cert-manager/pull/6671#discussion_r1470884367 @wallrj made a careless code review remark which resulted in a bug in the cleaning up the Route53 challenge txt record.
> nit: invalidChangeBatchErr seems to be unused. Consider using errors.Is instead.
But `route53types.InvalidChangeBatch` is not a sentinel error and can't be used with `errors.Is`.
@alex-berger wrote the fix for this in #7548 using a generic smithy error, and I have now adjusted that change to use `*route53types.InvalidChangeBatch` instead and added some unit tests.
I originally tried pushing my changes to his branch but was unable to force-push after I'd made some unnecessary changes,
so I've moved everything to this branch on my fork.
Fixes: …
=> Fix AWS Route53 error detection for not-found errors during deletion

cmd/acmesolver/go.mod, cmd/cainjector/go.mod, cmd/controller/go.mod, cmd/startupapicheck/go.mod, cmd/webhook/go.mod, go.mod, make/_shared/tools/00_mod.mk, test/e2e/go.mod, test/integration/go.mod
Updates the Go binary and the stdlib to 1.23.8.
> go1.23.8 (released 2025-04-01) includes security fixes to the net/http
package, as well as bug fixes to the runtime and the go command. See the Go
1.23.8 milestone on our issue tracker for details.
-- https://go.dev/doc/devel/release#go1.23.0
This will partially fix the failures that we're seeing in our periodic trivy tests and and ArtifactHub:
* https://testgrid.k8s.io/cert-manager-periodics-release-1.16
I bumped the Go version to 1.23.8 and then ran the following commands, in subsequent commits:
```
_bin/tools/go get go@1.23.8
make go-tidy
```
See:
* https://go.dev/doc/toolchain#get
/kind bug
```release-note
Bump Go to v1.23.8 to fix CVE-2025-22871
```
=> [release-1.16] Bump Go to v1.23.8 to fix CVE-2025-22871

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
This PR cmd/cmctl's go.mod to v1.12.17 as part of the release process.
```release-note
NONE
```
=> [Release v1.12.17] Update cmd/cmctl's go.mod to v1.12.17

deploy/charts/cert-manager/templates/NOTES.txt, deploy/crds/crd-certificates.yaml, internal/apis/certmanager/v1/defaults.go, internal/apis/certmanager/v1/defaults_test.go, internal/apis/certmanager/validation/certificate.go, internal/apis/certmanager/validation/certificate_test.go, internal/apis/certmanager/validation/warnings.go, internal/controller/feature/features.go, pkg/apis/certmanager/v1/types_certificate.go, pkg/controller/certificates/keymanager/keymanager_controller.go, test/e2e/suite/conformance/certificates/tests.go, test/integration/certificates/generates_new_private_key_per_request_test.go
The motivation for this change is described by @SgtCoDFish  in #7601:
> Security; if a private key is exposed, users may (reasonably) assume that re-issuing a certificate (e.g. using cmctl renew) will generate a new private key. Flynn's point is that unless a user has already deeply read the cert-manager docs (which most won't have, it's pretty simple to get cert-manager working for most) this is highly surprising and will mean that cert-manager isn't protecting the user from something they expect.
> 
> Users who need to not change the private key on rotation (e.g. if they want to preserve it and just change the cert, which is less common but still happens) would need to explicitly set the rotation policy to never to avoid losing the key.
There were two proposed strategies and the team …
=> [VC-39805] Change the default `privateKey.rotationPolicy` to `Always`

internal/apis/certmanager/v1/defaults.go, pkg/controller/certificates/keymanager/keymanager_controller.go
See  https://github.com/cert-manager/cert-manager/pull/7723#discussion_r2080108272 for context.
/kind bug
```release-note
NONE
```
=> Avoid mutating the client-go informer cache

deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/startupapicheck-job.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml, make/config/samplewebhook/chart/templates/deployment.yaml
This pr updates the Helm Chart to add quotes to values for _nodeSelector_ entries. This is needed if the value is a _boolean_. An example is using [Spot VMs](https://cloud.google.com/kubernetes-engine/docs/concepts/spot-vms) on _GCP_:
````
apiVersion: v1
kind: Pod
spec:
nodeSelector:
cloud.google.com/gke-spot: "true"
````
Currently, the Helm Chart uses the _toYaml_ function when adding the _nodeSelector_ values, however, _toYaml_ does not quote the values as discussed [here](https://github.com/helm/helm/issues/4262).
/kind bug
```release-note
Quote nodeSelector values in Helm Chart
```
=> Quote node selector values

deploy/crds/crd-certificates.yaml, internal/apis/certmanager/types_certificate.go, pkg/apis/certmanager/v1/types_certificate.go, pkg/controller/certificates/revisionmanager/revisionmanager_controller.go, pkg/controller/certificates/revisionmanager/revisionmanager_controller_test.go
As highlighted in this [issue](https://github.com/cert-manager/cert-manager/issues/3958), the default value for the revisionHistoryLimit should not be nil as if the user doesn't set it then no revisions will be garbage collected. Most users do want the revisions garbage collected so it would be good to provide it right out of the box.
/kind feature
```release-note
⚠️ might be breaking: Set the default revisionHistoryLimit to 1 for the CertificateRequest revisions
```
=> Set the default RevisionHistoryLimit to 1 for CertificateRequest revisions

third_party/forked/acme/acme.go, third_party/forked/acme/rfc8555.go, third_party/forked/acme/rfc8555_test.go, third_party/forked/acme/types.go, third_party/klone.yaml
This PR patches the `third_party/forked/acme` package to add support for ACME profiles via new options, error variables, and tests. Key changes include:
- Updating the vendor reference and documentation in third_party/klone.yaml.
- Adding new error definitions, functions, and options in types.go to support profiles.
- Introducing new tests and updates in rfc8555_test.go and rfc8555.go along with JSON decoding changes in acme.go to validate profile support.
Stack:
1.  [ ] #7752
2.  [x] #7776
3.  [ ] #7777
- https://github.com/cert-manager/crypto/commit/20ccc126e2ac0b2d9da2e78f84f5bb7649d8100a
```release-note
Patch the `third_party/forked/acme` package with support for the ACME profiles extension.
```
=> [VC-39414] Patch the third_party/forked/acme package with support for ACME profiles

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/values.schema.json, deploy/charts/cert-manager/values.yaml
Fixes: #7720 
Use port names rather than numbers to map connections
/kind feature
```release-note
Switched service/servicemon definitions to use port names instead of numbers.
```
=> helm: use port names rather than numbers

deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, deploy/crds/crd-orders.yaml, internal/apis/acme/types_issuer.go, internal/apis/acme/types_order.go, internal/apis/acme/v1/zz_generated.conversion.go, make/config/pebble/chart/templates/configmap.yaml, pkg/apis/acme/v1/types_issuer.go, pkg/apis/acme/v1/types_order.go, pkg/controller/acmeorders/sync.go, pkg/controller/acmeorders/sync_test.go, pkg/controller/certificaterequests/acme/acme.go, pkg/controller/certificaterequests/acme/acme_test.go, test/e2e/framework/helper/certificaterequests.go, test/e2e/framework/helper/validation/certificaterequests/certificaterequests.go, test/e2e/suite/issuers/acme/certificaterequest/profiles.go, test/unit/gen/issuer.go
Adds support for the ACME Profiles extension by propagating a new Profile field through the controller, API types, client sync logic, and CRDs.
- Extends buildOrder to accept and set a certificate profile
- Updates ACME controller (Sign and createOrder) to pass and handle Profile
- Adds Profile to API types, CRDs, tests, and conversion logic
Stack:
1.  [x] #7752
2.  [x] #7776
3.  [ ] #7777
/kind feature
```release-note
Feature: Add support for [ACME profiles extension](https://datatracker.ietf.org/doc/draft-aaron-acme-profiles/).
```
=> [VC-39414] Add support for ACME profiles

deploy/crds/crd-certificates.yaml, pkg/apis/certmanager/v1/types_certificate.go
Discovered by copilot in another PR:
* https://github.com/cert-manager/website/pull/1710#discussion_r2137296005
/type cleanup
```release-note
NONE
```
=> Fix typo in Certificate.Spec.SignatureAlgorithm documentation

pkg/issuer/acme/http/ingress.go
This change introduced a breaking change for users of the `ingress-nginx` ingress controller. `cert-manager` will in an upcoming release introduce this breaking change alongside with an option to make the pathType configurable.
This reverts commit 0af46c43653518063a57e3771fc4df10bf6e290b.
```release-note
Reverting to ImplementationSpecific Ingress pathType for until an upcoming breaking change release.
```
=> fix(acme):  Use ImplementationSpecific pathType until next breaking-change release

cmd/acmesolver/go.mod, cmd/cainjector/go.mod, cmd/controller/go.mod, cmd/startupapicheck/go.mod, cmd/webhook/go.mod, go.mod, make/_shared/tools/00_mod.mk, test/e2e/go.mod, test/integration/go.mod
govulncheck and trivy are reporting three vulnerabilities in the release-1.17 branch:
- https://testgrid.k8s.io/cert-manager-periodics-release-1.17
- https://github.com/cert-manager/cert-manager/actions/runs/15633164071/job/44041966423
The vulnerabilities are:
- https://pkg.go.dev/vuln/GO-2025-3749
```
Vulnerability #3: GO-2025-3749
Usage of ExtKeyUsageAny disables policy validation in crypto/x[50](https://github.com/cert-manager/cert-manager/actions/runs/15633164071/job/44041966423#step:5:51)9
More info: https://pkg.go.dev/vuln/GO-2025-3749
Standard library
Found in: crypto/x509@go1.23.8
Fixed in: crypto/x509@go1.23.10
Example traces found:
Error:       #1: pkg/check/api/api.go:130:14: api.Options.Run calls fmt.Fprintln, which eventually calls x509.Certificate.Verify
```
* …
=> [release-1.17] Bump Go to 1.23.10 to fix GO-2025-3749, GO-2025-3750, and GO-2025-3751

internal/controller/feature/features.go, make/e2e-setup.mk, pkg/issuer/acme/http/ingress.go, pkg/issuer/acme/http/ingress_test.go
With the release of cert-manager version `1.18.1` the pathType changes from `ImplementationSpecific` to `Exact`. This PR implements the feature gate `ACMEHTTP01IngressPathTypeExact`.
`ACMEHTTP01IngressPathTypeExact` changes the default `pathType` for ACME HTTP01 Ingress based challenges to `Exact`. This security feature ensures that the challenge path (which is an exact path) is not misinterpreted as a regular expression or some other Ingress specific (ImplementationSpecific) parsing. This allows HTTP01 challenges to be solved when using standards compliant Ingress controllers such as Cilium. The old default `ImplementationSpecific` can be reinstated by disabling this feature gate. You may need to disable the feature for compatibility with `ingress-nginx`. See [version 1.18 release …
=> feat(acme): Add default feature gate for ACME HTTP01 Ingress pathType Exact

internal/controller/feature/features.go
This new featuregate was supposed to be introduced at maturity level Beta, exactly like the DefaultPrivateKeyRotationPolicyAlways feature. Instead it has been set to GA.
The consequence of setting it to GA, is that when you disable it, you get a warning in the cert-manager logs:
```
$ kubectl  -n cert-manager logs deployments/cert-manager --follow
W0617 15:42:25.514056       1 feature_gate.go:354] Setting GA feature gate ACMEHTTP01IngressPathTypeExact=false. It will be removed in a future release.
```
I overlooked this when reviewing https://github.com/cert-manager/cert-manager/pull/7795
* https://github.com/cert-manager/cert-manager/pull/7795
/kind cleanup
```release-note
NONE
```
```
make e2e-setup FEATURE_GATES=AllAlpha=false,AllBeta=false
```
=> Change ACMEHTTP01IngressPathTypeExact feature to beta

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/startupapicheck-job.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/values.schema.json, deploy/charts/cert-manager/values.yaml
Adds a `global.nodeSelector` option to be able to set `nodeSelector` for all services in a single location. This is overridable at an individual service level as before.
Resolves issue #7817 
/kind feature
```release-note
Add `global.nodeSelector` to helm chart to allow for a single `nodeSelector` to be set across all services.
```
=> Add global.nodeSelector to helm chart

cmd/controller/app/controller.go, internal/collectors/acme_collector.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, test/integration/certificates/metrics_controller_test.go
Fixes https://github.com/cert-manager/cert-manager/issues/7700. This PR adds the new challenge status metric with a controller which monitors the challenges.
/kind
```release-note
Added `certmanager_certificate_challenge_status` prometheus metric.
```
=> feat(metrics): adding `certmanager_certificate_challenge_status` metric

internal/cainjector/bundle/bundle_test.go, internal/controller/certificates/secrets_test.go, pkg/controller/certificaterequests/acme/acme_test.go, pkg/controller/certificaterequests/ca/ca_test.go, pkg/controller/certificaterequests/venafi/venafi_test.go, pkg/controller/certificatesigningrequests/ca/ca_test.go, pkg/server/tls/authority/authority.go, pkg/server/tls/authority/authority_test.go, pkg/server/tls/dynamic_source.go, pkg/server/tls/dynamic_source_test.go, pkg/server/tls/file_source_test.go, pkg/util/pki/csr_test.go, pkg/util/pki/generate_test.go, pkg/util/pki/parse_certificate_chain_test.go, test/e2e/framework/addon/vault/vault.go, test/e2e/suite/conformance/certificatesigningrequests/ca/ca.go, test/webhook/testwebhook.go
While working on another cert-manager project, I noticed that the `x509.CreateCertificate` function hard-codes the version to 2 (v3), as ref. https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.2.1. Thus, ignoring our `Version: 3` set in templates in a lot of places. I am also questioning the value 3 used, as I think it should be 2 (v3), but this needs to be investigated more. 
The `x509.CreateCertificate` function also contains code for generating a proper serial number, if one is not set in the template. So instead of maintaining code to generate a serial number ourselves, I propose to make the Go stdlib generate a serial number when the template is only used to create a certificate.
I left the hardcoded `Version: 3` and custom serial number generation in …
=> Let x509.CreateCertificate set Version and SerialNumber

cmd/controller/app/controller.go, cmd/controller/go.mod, make/02_mod.mk, pkg/acme/accounts/client.go, pkg/acme/accounts/registry.go, pkg/acme/accounts/registry_test.go, pkg/acme/accounts/test/registry.go, pkg/controller/acmechallenges/controller.go, pkg/controller/acmeorders/controller.go, pkg/controller/context.go, pkg/issuer/acme/acme.go, pkg/issuer/acme/setup.go, pkg/issuer/acme/setup_test.go, test/integration/acme/orders_controller_test.go, test/integration/certificates/generates_new_private_key_per_request_test.go, test/integration/certificates/issuing_controller_test.go, test/integration/certificates/metrics_controller_test.go, test/integration/certificates/trigger_controller_test.go
Refactored the `Registry interface`, such that its `AddClient` function takes a `NewClientOptions` object that we can check against in the `GetClient` calls (future PR).
/kind cleanup
```release-note
NONE
```
=> Refactor ACME client registry (part 1)

pkg/util/pki/certificatetemplate.go, pkg/util/pki/certificatetemplate_test.go, pkg/util/pki/csr.go, pkg/util/pki/kube_test.go
This is a follow-up to https://github.com/cert-manager/cert-manager/pull/7844, removing the last traces of setting `x509.Certificate` Version and SerialNumber in production code. Since this PR also changes the unit test, I wanted this cleanup to go in a separate PR.
/kind cleanup
```release-note
NONE
```
=> Don't set x509.CreateCertificate Version and SerialNumber

pkg/controller/acmechallenges/scheduler/scheduler_test.go, pkg/controller/acmechallenges/update_test.go, pkg/controller/certificates/requestmanager/requestmanager_controller_test.go, pkg/controller/test/actions.go, pkg/controller/test/context_builder.go, pkg/issuer/acme/http/ingress_test.go, pkg/issuer/vault/setup_test.go, pkg/metrics/metrics_test.go, pkg/server/tls/authority/authority_test.go
This is a follow-up after https://github.com/cert-manager/cert-manager/pull/7866. Using deprecated APIs is something we should avoid when we can.
It seems like the generated `fake.NewClientSet` func in Gateway API isn't usable, so I have left it for now, as this must be fixed upstream.
/kind cleanup
```release-note
NONE
```
=> Migrate away from deprecated fake NewSimpleClientset func

hack/k8s-codegen.sh
While working on bootstrapping Renovate, we detected some issues related to running `make generate`. Maybe `GOBIN` is set in the Renovate environment? Which will make the current script fail. Anyway this appears like a simplification to me. Kudos to @ThatsMrTalbot!
/kind cleanup
```release-note
NONE
```
=> Improve script generating applyconfigurations

.github/workflows/renovate.yml
Renovate just created a lot of PRs which didn't have the expected form. Until we figure out how to fix this, after testing this in another project, we should disable the scheduled job.
/kind cleanup
```release-note
NONE
```
=> ci(renovate): disable scheduled job

internal/pem/decode.go, internal/pem/decode_test.go, pkg/util/pki/parse_certificate_chain_test.go
This commit manually checks out the internal/pem/decode* files from b8ade82a7997148c570e2181b6ae863b78070cb4 as merged to master in #7961
I chose to just check out the files (rather than cherry-picking) because these files are security-relevant and I want the review to be as simple as possible.
The diff on this PR is pretty much irrelevant, since this files are now identical to those on master which have already been reviewed.
/kind bug
```release-note
Increase maximum sizes of PEM certificates and chains which can be parsed in cert-manager, to handle leaf certificates with large numbers of DNS names or other identities
```
=> [release-1.17] increase maximum PEM sizes for leaf certificates and chains

deploy/charts/cert-manager/templates/rbac.yaml
cert-manager controller tokenrequest RoleBinding name is rendered as `cert-manager-cert-manager-tokenrequest`, which is less consistent than its corresponding Role name `cert-manager-tokenrequest`. Meanwhile it would be more accurate to use `{{ template "cert-manager.fullname" . }}` instead of `{{ template "cert-manager.serviceAccountName" . }}`
Follow-up #7213
The renamed RoleBinding `cert-manager-tokenrequest` was created successfully, meanwhile the orphan RoleBinding `cert-manager-cert-manager-tokenrequest` was cleaned up automatically.
```
$ k get role,rolebinding -n cert-manager
NAME                                                                  CREATED AT
role.rbac.authorization.k8s.io/cert-manager-tokenrequest              2025-08-17T07:20:30Z …
```
=> Helm: Fix naming format of tokenrequest RBAC resources

internal/apis/certmanager/validation/issuer.go, internal/apis/certmanager/validation/issuer_test.go
to reject configurations when multiple ingress options (class, ingressClassName, name) are specified simultaneously. This would help us catch errors at admission time rather than runtime.
Addresses https://github.com/cert-manager/cert-manager/pull/5849#discussion_r2297621682
Invalid configurations that should be rejected by the webhook:
- Both `http01.ingress.class` and `http01.ingress.ingressClassName`
- Both `http01.ingress.class` and `http01.ingress.name`
- Both `http01.ingress.ingressClassName` and `http01.ingress.name`
- All three fields
Error message:
```
Error from server (Forbidden): error when creating "STDIN": admission webhook "webhook.cert-manager.io" denied the request: spec.acme.solvers[0].http01.ingress: Forbidden: only one of 'ingressClassName', 'name' or 'class' should be …
```
=> fix: Enforce strict mutual exclusion for HTTP-01 ingress configuration fields

internal/controller/certificates/policies/constants.go
fix typo comments form `SecretTemplateMisMatch` to `SecretTemplateMismatch`
/kind cleanup
```release-note
NONE
```
=> fix: typo in SecretTemplateMismatch's comment

pkg/util/pki/asn1_util.go
As mentioned in https://github.com/cert-manager/cert-manager/pull/8079#discussion_r2352377413, I found it hard to read due to the two imbricated switch statements. I propose that we flatten them.
```release-note
NONE
```
=> asn1_util: flatten the MarshalUniversalValue func

cmd/cainjector/app/cainjector.go, cmd/controller/app/controller.go, cmd/controller/app/start.go, cmd/webhook/app/webhook.go
Print `util.AppVersion` and `util.AppGitCommit` when the controller, webhook and ca-injector starts.  
Previously, these values were present in `Short`, which never gets printed for the root command removed since they are standalone root commands with no subcommands.
resolves https://github.com/cert-manager/cert-manager/issues/8067
/kind feature
```release-note
The controller, webhook and ca-injector now logs its version and git commit on startup for easier debugging and support.
```
=> feat: log version information when starting the cert-manager controller, webhook and ca-injector

.github/renovate.json5
This reverts commit 9307cdb1494f602adeab423ff7b4ed546a27d23b.
It seems like the attempt to renovate our release branches is not working. I will look more into this, as I think it's useful, but let's revert it for now.
/kind cleanup
```release-note
NONE
```
=> Revert "Start renovating release branches"

pkg/acme/client/http.go, pkg/acme/client/http_test.go, pkg/acme/client/middleware/logger.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, test/integration/certificates/metrics_controller_test.go, third_party/forked/acme/acme.go
This PR addresses issue https://github.com/cert-manager/cert-manager/issues/7883 where the ACME client's Prometheus metrics could grow with unbounded cardinality, leading to performance degradation and high memory usage in Prometheus.
The existing instrumentation for ACME client metrics used the request's URL `path` as a label. A `pathProcessor` function attempted to normalize this by taking the first two URL segments. While this heuristic worked for ACME CAs like Let's Encrypt (e.g., `/acme/orders/<id>`), it failed for others like Google Public CA, whose URL structures are different (e.g., `/orders/<id>`).
This divergence meant that for some CAs, unique order/challenge identifiers were still included in the `path` label, creating a new time series for nearly every step of the certificate …
=> [7883] - Fix uncontrolled cardinality for Prometheus metrics
