.gitlab-ci.yml, Dockerfile.acmesolver, Dockerfile.controller, Makefile
@munnerz I still went with one stage for gitlab, I think it's easier for now (the golang binaries are quite big in size and I rather not having them stored on the gitlab server for every build)
The master will always assing a unique one and update the `canary` tag
Git tags translate into docker image tags and will update the latest reference
=> Adds .gitlab-ci.yml

pkg/issuer/acme/http/http.go
This is a quick workaround for #92 
Really, crtName could be up to 63 characters, so we need to make sure to truncate it in order to guarantee the length of the resource is then <63 chars.
=> Use shorter names for http solver resources

pkg/issuer/acme/http/http.go
Fixes a race in the ACME HTTP solver when using multiple domains.
Closes #153 
```release-note
Fix race condition in ACME HTTP01 solver when validating multiple domains
```
=> Ensure Present and CleanUp run in serial

pkg/issuer/acme/http/http.go, pkg/issuer/acme/http/http_test.go
See #154 for details. Sometimes HTTP routes have not propagated yet when using a controller such as GCLB. This forces us to wait for 5 consecutive passes of the HTTP01 self-check before proceeding.
Closes #154 
* This adds an extra 10s delay onto *any* HTTP01 validation
* The '5 tries' number is hardcoded into the HTTP01 solver
```release-note
Ensure 5 consecutive HTTP01 self-checks to pass before issuing ACME certificate
```
=> Ensure ACME HTTP01 reachability test passes 5 times before issuing certificate

pkg/issuer/acme/http/http.go
A type in the HTTP01 solver caused it to not return an error if the key presented by the ingress and the expected key do not match.
Fixes #163 
```release-note
Fix bug in ACME HTTP01 solver causing self-check to return true before paths have propagated
```
=> Error if existing presented key and expected key do not match

pkg/controller/certificates/sync.go
Set the Kubernetes secret type to TLS
Fixes #133 
```release-note
Set the Kubernetes secret type to TLS.
Action required: this will cause renewals of existing certificates to fail. You **must** delete certificates that have been previously produced by cert-manager else cert-manager may enter a renewal loop when saving the new certificates. Alternatively, you may specify a new secret to store your certificate in and manually update your ingress resource/applications reference the secret.
```
=> Set TLS certificate secret type to TLS type

pkg/issuer/acme/dns/dns_test.go, pkg/issuer/acme/dns/util/testdata/resolv.conf.1, pkg/issuer/acme/dns/util/wait_test.go
Adds some unit tests for ACME dns solver
```release-note
NONE
```
=> Add solverFor and wait.go unit tests for acme dns solver

Makefile
Don't run tests for generated files
```release-note
NONE
```
=> Don't test pkg/client/ and third_party/ packages

pkg/controller/certificates/sync.go, pkg/issuer/acme/prepare.go, pkg/issuer/ca/issue.go, pkg/util/filter.go, pkg/util/filter_test.go, pkg/util/pki/csr.go, pkg/util/pki/csr_test.go
Improves the validation of dnsNames and commonNames on certificate resources.
Fixes a bug in checking certificate validity.
Fixes #176, fixes #175
```release-note
Fix a bug in checking certificate validity and improve validation of dnsNames and commonName
```
=> Improve validation of certificates. Fix bug in checking certificate validity

Makefile
Cherry pick of #186 on release-0.2.
#186: Don't test pkg/client/ and third_party/ packages
```release-note
NONE
```
=> Automated cherry pick of #186

pkg/issuer/acme/dns/dns_test.go, pkg/issuer/acme/dns/util/testdata/resolv.conf.1, pkg/issuer/acme/dns/util/wait_test.go
Cherry pick of #185 on release-0.2.
#185: Add solverFor and wait.go unit tests for acme dns solver
```release-note
NONE
```
=> Automated cherry pick of #185

.gitlab-ci.yml, .travis.yml
1.10 isn't too far off, at which point 1.8 will no longer receive security updates. It seems simple enough to bump sooner rather than wait until the last second.
```release-note
NONE
```
=> Update to go 1.9

Makefile, cmd/ingress-shim/README.md, cmd/ingress-shim/app.go, cmd/ingress-shim/controller/checks.go, cmd/ingress-shim/controller/controller.go, cmd/ingress-shim/controller/sync.go, cmd/ingress-shim/controller/sync_test.go, cmd/ingress-shim/main.go, cmd/ingress-shim/options/options.go, cmd/ingress-shim/start.go, contrib/charts/cert-manager/templates/deployment.yaml, contrib/charts/cert-manager/values.yaml, hack/build/dockerfiles/ingress-shim/Dockerfile, hack/test/setup-boulder.sh, pkg/util/kube/config.go, test/e2e/certificate/certificate_acme.go, test/e2e/e2e.go, test/e2e/framework/framework.go, test/e2e/ingress/certificate_acme.go, test/util/util.go
Adds a new controller, ingress-shim, that will automatically create Certificate resources for ingress resources with annotations on them.
By setting defaults on the ingress-shim CLI, it's possible to re-implement the `kubernetes.io/tls-acme` behavior of kube-lego.
There also needs to be some documentation written about this, as well as a user guide. This can be our migration story for users coming from kube-lego as well. It'd be interesting to know how easily it'd be to support a seamless migration from [kube-cert-manager](https://github.com/PalmStoneGames/kube-cert-manager) through this tool too. …
=>  Add ingress-shim controller to create Certificates based on annotations on ingress resources

contrib/charts/cert-manager/templates/deployment.yaml, contrib/charts/cert-manager/values.yaml
Fixes ingress-shim image name in helm chart
Allow specifying extraArgs to ingress-shim in helm chart
```release-note
NONE
```
/assign
=> Ingress shim fixes

contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/values.yaml, docs/examples/cert-manager.yaml
Version bump for 0.2.2
```release-note
NONE
```
=> Update for v0.2.2

Makefile, pkg/scheduler/scheduler.go
Fixes a race condition in the scheduler package and enables the race detector in tests
```release-note
Fix a race condition in the package responsible for scheduling renewals
```
=> Enable go race detector and fix race in scheduler

pkg/issuer/acme/setup.go
Fixes a panic when an error other than HTTP Conflict is returned from the ACME server during registration.
Fixes #236 
```release-note
Fix panic when ACME server returns an error other than HTTP Status Conflict during registration
```
/assign
=> Fix panic when ACME server returns a genuine error

docs/README.md, docs/user-guides/README.md, docs/user-guides/deploying.md, docs/user-guides/helm.md, docs/user-guides/ingress-shim.md, docs/user-guides/migrating-from-kube-lego.md
Improves our documentation to further explain how Helm deployment works (including RBAC and extraArgs).
It also adds a doc on ingress-shim - what it does, how it works, how to configure it and how to use it.
Fixes #256, fixes #257, fixes #136 
```release-note
Improve deployment documentation
```
/cc @ahmetb
=> Expand deployment docs, including docs on ingress-shim

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/templates/deployment.yaml
We changed this in the most recent release, which caused upgrades from prior versions to fail. This removes the strategy from the chart in a backwards compatible way for those that have started on v0.2.3.
Fixes #268 
```release-note
Revert change to Helm chart deployment update strategy that'd cause upgrades from previous versions to fail
```
=> Remove .spec.strategy.type: Recreate

Makefile, test/e2e/e2e.go, test/e2e/framework/test_context.go
Output junit reports during e2e tests for gubernator to display test details more clearly.
/release-note-none
/assign
=> Optionally write junit reports into artifacts during e2e tests

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/templates/NOTES.txt, contrib/charts/cert-manager/values.yaml, docs/deploy/rbac/certificate-crd.yaml, docs/deploy/rbac/clusterissuer-crd.yaml, docs/deploy/rbac/deployment.yaml, docs/deploy/rbac/issuer-crd.yaml, docs/deploy/rbac/rbac.yaml, docs/deploy/rbac/serviceaccount.yaml, docs/deploy/without-rbac/certificate-crd.yaml, docs/deploy/without-rbac/clusterissuer-crd.yaml, docs/deploy/without-rbac/deployment.yaml, docs/deploy/without-rbac/issuer-crd.yaml, hack/deploy/rbac-values.yaml, hack/deploy/without-rbac-values.yaml
This PR brings the helm chart in line with what is found in kubernetes/charts (changes contained here: https://github.com/kubernetes/charts/pull/3416/commits/008d52cbc4c2b7d2b4981f53214e15779e085fb7).
It also addresses some feedback (https://github.com/kubernetes/charts/issues/3513) in order to improve our post-installation documentation by providing links to how to configure issuers/ingress-shim.
```release-note
Remove default resource requests in Helm chart. Improve post-deployment informational messages.
```
=> Update helm chart to align with k/charts feedback

test/e2e/certificate/certificate_acme.go, test/e2e/certificate/certificate_ca.go, test/e2e/framework/certificate.go
Updates our e2e tests to ensure the certificate being tested is valid for the domains requested on the certificate under test
```release-note
NONE
```
=> Ensure certificate is valid for given domains during e2e tests

pkg/issuer/ca/issue.go
If the CA used is only an intermediate CA, and the root CA is trusted by the client, the client needs help verifying the certificate chain.
This also makes the CA present in the certificate even if it's the root CA.
Trusting certs issued by intermediate CAs used by cert-manager.
I have tested this locally with my own intermediate CA used by cert-manager, issued by my own root CA trusted by my macOS client. The whole certificate chain is now presented in the browser.
The idea to just append the certificates is based on cfssl's mkbundle:
https://github.com/cloudflare/cfssl/blob/1.3.0/cmd/mkbundle/mkbundle.go#L97
```release-note
CA Issuer: bundle CA certificate with …
```
=> Bundle the CA public key in issued certificate

.gitlab-ci.yml
Install Helm during .gitlab-ci.yml script
(in future, this file will go away altogether once we have set up a 'trusted' build cluster to push releases)
```release-note
NONE
```
/assign
=> Install Helm during .gitlab-ci.yml release build

cmd/ingress-shim/controller/sync.go, cmd/ingress-shim/controller/sync_test.go
**What this PR does / why we need it**: Previously the ingress-shim would sync an Ingress resource if it simply contained the `kubernetes.io/tls-acme` annotation, regardless of the value; now it will only do so if the annotation value is truthy (e.g., "true", "t", "1", so forth).
**Special notes for your reviewer**: This could probably be done in a way that doesn't disrupt the function's aesthetics so much. Open to all suggestions.
```release-note
ingress-shim will only sync Ingress resources with `kubernetes.io/tls-acme` annotation if the value of that annotation is true.
```
=> Check the value of the tls-acme annotation, not just its existence

cmd/controller/app/controller.go, cmd/ingress-shim/app.go, contrib/charts/cert-manager/templates/rbac.yaml, docs/deploy/rbac/rbac.yaml
Use ConfigMaps for leader election. Improves scalability by not modifying Endpoints, which are watched by kube-proxy.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #293
```release-note
action required: Before upgrading, scale the cert-manager Deployment to 0, to avoid two controllers attempting to operate on the same resources
```
=> fix: Use ConfigMaps for leaderelection

contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/templates/certificate-crd.yaml, contrib/charts/cert-manager/values.yaml, docs/deploy/rbac/certificate-crd.yaml, docs/deploy/without-rbac/certificate-crd.yaml
Defaults to `[cert, certs]` and is configurable with `certificateCRDShortNames` parameter.
Simplifies manual certificate management with kubectl.
Fixes #311
<div name="review-notes" />
Instead of a boolean switch do/dont include the shortNames, the value defines the aliases. This may be handy if anybody prefers `[crt, crts]` instead.
I'm not too keen on the `certificateCRDShortNames` variable name. It might be better to use `Resource` instead of `CRD` to be consistent with the `createCustomResource` var.
Other CRDs are probably ok without an alias, but other people workflows may differ. Should these also be configurable? In that case, the variables could be `shortNames: {certificates: [], …}`. …
=> Add default shortNames to certificates CRD

pkg/controller/certificates/sync.go
Previously, when requesting a certificate for the first time, the following events are logged:
```
Warning  ErrorCheckCertificate  1m                 cert-manager-controller  Error checking existing TLS certificate: secret "httpbin" not found
Normal   PrepareCertificate     1m                 cert-manager-controller  Preparing certificate with issuer
```
This has caused confusion for users when they see a Warning/Error being logged. This PR changes that to be:
```
Normal   ErrorCheckCertificate  1m                 cert-manager-controller  Error checking existing TLS certificate, will re-issue: secret "httpbin" not found
Normal   PrepareCertificate     1m                 cert-manager-controller  Preparing certificate with issuer
``` …
=> Make existing TLS certificate check emit a Normal event instead of Warning when the existing certificate is invalid

contrib/charts/cert-manager/templates/deployment.yaml, contrib/charts/cert-manager/templates/serviceaccount.yaml, docs/deploy/rbac/deployment.yaml, docs/deploy/rbac/rbac.yaml, docs/deploy/rbac/serviceaccount.yaml, docs/deploy/without-rbac/deployment.yaml, hack/update-deploy-gen.sh
Previously, our deployment manifests deployed into the 'default' namespace. This changes them to deploy into 'cert-manager' instead.
```release-note
The static deployment manifests now automatically deploy into the 'cert-manager' namespace by default
```
=> Update default deployment namespace to be 'cert-manager'

contrib/charts/cert-manager/templates/00-namespace.yaml, contrib/charts/cert-manager/values.yaml, docs/deploy/rbac/00-namespace.yaml, docs/deploy/without-rbac/00-namespace.yaml, hack/update-deploy-gen.sh
Create a Namespace resource as part of the static deployment manifests bundle, to make it easier for users to deploy cert-manager without a Helm chart
```release-note
NONE
```
/cc @davecheney @wallrj
=> Create a Namespace resource as part of the static manifest bundle

contrib/charts/cert-manager/templates/deployment.yaml, docs/deploy/rbac/deployment.yaml, docs/deploy/without-rbac/deployment.yaml, test/e2e/clusterissuer/clusterissuer_ca.go, test/e2e/e2e.go
Changes the default cluster resource namespace from kube-system to the current namespace of the cert-manager deployment.
**Which issue this PR fixes**: fixes #103 
```release-note
Supporting resources for ClusterIssuer's (e.g. signing CA certificates, or ACME account private keys) will now be stored in the same namespace as cert-manager, instead of kube-system in previous versions. Action required: you will need to ensure to properly manually migrate these referenced resources across into the deployment namespace of cert-manager, else cert-manager may not be able to find account private keys or signing CA certificates.
```
/cc @mikebryant
=> Set default cluster resource namespace to current pod namespace

contrib/charts/cert-manager/templates/rbac.yaml, docs/deploy/rbac/rbac.yaml
Adds permission to CRUD Endpoints resources back into the cert-manager RBAC role. This is to prevent deployments using the 'master' version of the Helm chart failing when deploying a pre-0.3 (unreleased) release of cert-manager.
We will remove this in 0.4. This is in order to reduce friction for new users if they forget/decide not to use a tagged release of the Helm chart.
```release-note
NONE
```
/cc @davecheney @mikebryant
=> Add Endpoints back into the cert-manager RBAC policy

docs/user-guides/deploying.md
Proper documentation for deploying cert-manager for k8s clusters without rbac enabled (happens to be the default for cdk on localhost).
No issue per se, a follow-up on #256.
=> docs: fix value name that disables rbac

docs/user-guides/deploying.md, docs/user-guides/migrating-from-kube-lego.md
Updates docs to use Chart from kubernetes/charts in the installation/migration guides. This makes it less confusing which Chart to use. There was a short discussion about this with @ahmetb and @munnerz on Slack https://kubernetes.slack.com/archives/C4NV3DWUC/p1519675336000598
No issue filed.
None.
```release-note
NONE
```
=> Update guides to use official Charts repository

pkg/issuer/acme/dns/util/wait.go
If /etc/resolv.conf does not have any entries, then its unlikely
that the domain name representation of google's DNS would get
resolved too. Hence using IP address directly makes sense.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #360
```release-note
NONE
```
=> Use Google's DNS IPs instead of domain

Makefile, hack/verify-chart-version.sh
Verifies that the Helm chart version is bumped when a file in the chart is changed.
```release-note
NONE
```
=> Verify helm chart version is bumped when a chart is changed

.gitlab-ci.yml
Since #372 merged, builds of master (which lead to releases) have been failing.
Technically, the PULL_BASE_SHA should be set to the SHA value of the branch this PR is being *merged into*. Because we don't actually test these on GitLab, this workaround is okay (setting it to the value of the current commit).
```release-note
NONE
```
=> Fix .gitlab-ci.yml build

docs/devel/README.md, docs/examples/acme-cert.yaml
I felt that the steps to deploy/run/test cert-manager in minikube were non-trivial enough that it was worth documenting.
Let me know if this should live somewhere else in the repo or if you have suggestions for how to better document this.
```release-note
NONE
```
=>  docs/devel: add 'deploy to minikube' docs 

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/values.yaml, docs/deploy/rbac/certificate-crd.yaml, docs/deploy/rbac/clusterissuer-crd.yaml, docs/deploy/rbac/deployment.yaml, docs/deploy/rbac/issuer-crd.yaml, docs/deploy/rbac/rbac.yaml, docs/deploy/rbac/serviceaccount.yaml, docs/deploy/without-rbac/certificate-crd.yaml, docs/deploy/without-rbac/clusterissuer-crd.yaml, docs/deploy/without-rbac/deployment.yaml, docs/deploy/without-rbac/issuer-crd.yaml
Lots of new users don't realize:
(a) They need to create a Issuer/ClusterIssuer themselves
(b) They need to tell `ingress-shim` the name via `extra-args`
This PR adds a comment to the helm chart `values.yaml` to address these issues.
(Ideally the `helm` would create an ClusterIssuer for you by default, and set these options, if you specify and email address to use with LE.)
Release note:
```release-note
NONE
```
=> Document common ingressShim.extraArgs use case in chart

docs/user-guides/migrating-from-kube-lego.md
Clarify ClusterIssuer resource namespace in the migrating from kube lego guide
```release-note
NONE
```
=> Clarify ClusterIssuer resource namespace

pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/dns_test.go
AWS credentials don't contain whitespace, and it's very easy to
accidentally include spaces or newlines at the end of secrets.
I am hoping that this fixes #320 and #208 
Based on comments there, it would have clearly fixed some cases in there at least.
```release-note
The ACME dns01 solver now trims excess whitespace from AWS credentials 
```
=> Trim aws credentials for acme dns route53 provider

cmd/ingress-shim/controller/sync.go, cmd/ingress-shim/controller/sync_test.go
**What this PR does / why we need it**: Previously ingress-shim did not reconfigure certificates when the ingress config changed.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #288 
```release-note
ingress-shim now reconfigures certificates
```
=> Reconfigure certs when ingress config changes

hack/verify-chart-version.sh
Previously when the verify-chart-version script was run more than once, it would fail.
```release-note
NONE
```
=> Fix verify-chart-version script when running more than once

.travis.yml, Makefile, hack/verify-chart-version.sh
This is a followup/fixup for #372 
The changes in 372 broke break running `make verify` locally, which I think is a somewhat useful developer command.
While I was at it, I also changed the default target to build since I think that's more likely what someone wants. I don't think that breaks anything since I think other places have explicitly been calling out which targets to call.
This also requires https://github.com/jetstack/test-infra/pull/158 to not lose that new coverage
=> make: split 'verify_pr' out 

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/templates/deployment.yaml, contrib/charts/cert-manager/values.yaml, docs/deploy/rbac/certificate-crd.yaml, docs/deploy/rbac/clusterissuer-crd.yaml, docs/deploy/rbac/deployment.yaml, docs/deploy/rbac/issuer-crd.yaml, docs/deploy/rbac/rbac.yaml, docs/deploy/rbac/serviceaccount.yaml, docs/deploy/without-rbac/certificate-crd.yaml, docs/deploy/without-rbac/clusterissuer-crd.yaml, docs/deploy/without-rbac/deployment.yaml, docs/deploy/without-rbac/issuer-crd.yaml
This PR add podAnnotations value to the deployment resource.
This is useful if you want to use the Route53 provider together with Kube2Iam to allocate AWS role to a pod.
```
annotations:
"iam.amazonaws.com/role":"arn:aws:iam::<project id>:role/CertManagerRole"
```
https://github.com/jetstack/cert-manager/issues/195
```release-note
Add podAnnotations to Helm chart
```
=> Add podAnnotations

pkg/issuer/acme/http/http.go, test/e2e/framework/util.go
**What this PR does / why we need it**: Add limits to http validation pod so it's able to be created in namespaces with quota enforcement enabled
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #233 
```release-note
Add limits to http validation pod 
```
=> Add limits to http validation pod 

pkg/issuer/acme/acme.go
Related to #407.
```release-note
Add a meaningful user agent to the ACME client to help diagnosing abusive traffic patterns
```
=> Add a meaningful User-Agent.

Makefile
This is a follow up to #397 where we also switched the Prow scenario spec to run 'verify_pr' as part of the quick-verify test process
This is required to fix builds on release-0.2
```release-note
NONE
```
=> release-0.2: Add empty 'verify_pr' target

pkg/apis/certmanager/v1alpha1/types.go, pkg/controller/certificates/sync.go
**What this PR does / why we need it**: Previously, it was hard to inspect why a secret was created. This adds additional information in the form of annotations which should help keep track of created secrets.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #262 
```release-note
TLS secrets are now annotated with information about the certificate
```
=> Annotate created secrets with cert information

pkg/issuer/acme/acme.go, pkg/issuer/acme/dns/akamai/akamai.go, pkg/issuer/acme/dns/cloudflare/cloudflare.go, pkg/issuer/acme/dns/route53/route53.go, pkg/util/kube/config.go, pkg/util/useragent_roundtripper.go, pkg/util/version.go
This is a followup to #422 
The most useful thing out of this is the kubeconfig one which should make it easier for cluster operators to look at apiserver logs and find cert-manager's calls.
The others are all just to try and be a good citizen, but probably don't matter much.
I have not tested this other than verifying it compiles.
```release-note
NONE
```
=> Plumb a user-agent through pretty much everywhere

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/templates/deployment.yaml, docs/deploy/rbac/certificate-crd.yaml, docs/deploy/rbac/clusterissuer-crd.yaml, docs/deploy/rbac/deployment.yaml, docs/deploy/rbac/issuer-crd.yaml, docs/deploy/rbac/rbac.yaml, docs/deploy/rbac/serviceaccount.yaml, docs/deploy/without-rbac/certificate-crd.yaml, docs/deploy/without-rbac/clusterissuer-crd.yaml, docs/deploy/without-rbac/deployment.yaml, docs/deploy/without-rbac/issuer-crd.yaml
add `selector` to deployment as otherwise it fails on GKE k8s v1.9.x
```release-note
NONE
```
=> add selector, as otherwise it fails on GKE k8s v1.9.x

hack/build/dockerfiles/controller/Dockerfile, hack/build/dockerfiles/ingress-shim/Dockerfile
I've added a user to the controller and ingress-shim Dockerfiles. The processes don't need root access so I figured I might as well limit it.
```release-note
Run cert-manager container as a non root user
```
=> Running docker containers as non-root user

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/templates/NOTES.txt, contrib/charts/cert-manager/values.yaml, docs/deploy/rbac/certificate-crd.yaml, docs/deploy/rbac/clusterissuer-crd.yaml, docs/deploy/rbac/deployment.yaml, docs/deploy/rbac/issuer-crd.yaml, docs/deploy/rbac/rbac.yaml, docs/deploy/rbac/serviceaccount.yaml, docs/deploy/without-rbac/certificate-crd.yaml, docs/deploy/without-rbac/clusterissuer-crd.yaml, docs/deploy/without-rbac/deployment.yaml, docs/deploy/without-rbac/issuer-crd.yaml, docs/examples/cert-manager.yaml
Bumps the chart version for 0.2.4
This PR should then be cherry picked into release-0.2 and the conflicts resolved.
```release-note
NONE
```
=> Bump chart version

hack/ci.sh
Helm sometimes takes 5-10m to timeout on commands. This adds our own timeout to the Helm version command to save builds hanging.
```release-note
NONE
```
=> Set 5s timeout on helm version command

pkg/issuer/acme/http/http.go
As an alternative to #458, this change absorbs HTTP client errors in the ACME http self check.
Previously we would fail if connection to the server failed, which caused Prepare to not be called. This absorbs all errors, returning 'false' for the self check.
```release-note
NONE
```
/assign
=> Absorb HTTP client errors in acme http self check

third_party/crypto/acme/acme.go, third_party/crypto/acme/acme_test.go
This PR cherry picks [acme: stop polling authz on 4xx client errors](https://github.com/golang/crypto/commit/91a49db82a88618983a78a06c1cbd4e00ab749ab) and resolves conflicts when applied to v2 (just comments).
The original commit body:
```
acme: stop polling authz on 4xx client errors
"At Let's Encrypt, we are seeing clients in the wild that continue
polling their challenges long after those challenges have expired and
started serving 404."
The 4xx response code errors are client errors and should not be
retried.
Fixes golang/go#24145
Change-Id: I012c584fc4defd3a0d64a653860c35705c5c6653
Reviewed-on: https://go-review.googlesource.com/97695
Run-TryBot: Alex Vaghin <ddos@google.com>
TryBot-Result: Gobot Gobot <gobot@golang.org>
Reviewed-by: Brad Fitzpatrick <bradfitz@golang.org>
``` …
=> acme: stop polling authz on 4xx client errors

docs/reference/issuers.rst, docs/reference/issuers/acme/dns01.rst, docs/reference/issuers/acme/http01.rst, docs/tutorials/acme/dns-validation.rst, docs/tutorials/acme/http-validation.rst, docs/tutorials/acme/migrating-from-kube-lego.rst
This blindly replaces all v1 letsencrypt endpoints with v2 in our docs.
As this change is merging into master, the public facing documentation won't be updated until we roll out the release-0.3 branch.
I may enable building the master branch of the docs too, for those wanting to try out the :canary release.
More docs updates to follow.
```release-note
NONE
```
=> String replace ACMEv1 endpoints with v2 in docs

pkg/issuer/acme/prepare.go
Fixes the string formatting of the error that's printed when the self check fails
```release-note
NONE
```
=> Fix up self check failure error message

Makefile
It looks like it was accidentally removed in commit
8c7eaa1db8e4143254b14711f3fa3fdcaa53e22c
Adds back the commit sha label for the docker images
None 
N/A
=> Add back the commit sha in the `org.label-schema.vcs-ref` label.

pkg/issuer/ca/issue.go
Google Chrome rejects the certificate for SSL connections if the Key Usage extension does not include the keyEncipherment purpose. This adds the missing Key Encipherment bit to the createCertificateTemplate function.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #481
```release-note
Add the Key Encipherment purpose to CA Issuer generated certificates
```
=> Add Key Encipherment bit to Key Usage extension

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/manifests/cert-manager/rbac/certificate-crd.yaml, contrib/manifests/cert-manager/rbac/clusterissuer-crd.yaml, contrib/manifests/cert-manager/rbac/deployment.yaml, contrib/manifests/cert-manager/rbac/issuer-crd.yaml, contrib/manifests/cert-manager/rbac/rbac.yaml, contrib/manifests/cert-manager/rbac/serviceaccount.yaml, contrib/manifests/cert-manager/without-rbac/certificate-crd.yaml, contrib/manifests/cert-manager/without-rbac/clusterissuer-crd.yaml, contrib/manifests/cert-manager/without-rbac/deployment.yaml, contrib/manifests/cert-manager/without-rbac/issuer-crd.yaml
Includes a typo fix from @AdamDang.
```release-note
none
```
=> Sync cert-manager chart with kubernetes/charts

pkg/controller/certificates/controller.go, pkg/controller/clusterissuers/controller.go, pkg/controller/issuers/controller.go, pkg/controller/util.go
This PR switches all uses of the workqueue to use AddRateLimited, to save excessive retries.
It also adjust the exponential backoff to have a base of 2s and a max of 1m (this is for overall processing of Certificates, not necessarily the rate at which we will re-attempt authorisations)
ref #407 #413
```release-note
Fix bug that could cause excessive validation/issuance attempts for failing Certificate resources
```
=> release-0.2: Always use AddRateLimited. Adjust exponential backoff base/max.

.gitlab-ci.yml
Removes the 'latest' image tag from the push_release step. This tag doesn't currently behave properly, and isn't referenced anywhere.
We have :canary which tracks master as well as release tags, I don't think we need anything more for now.
```release-note
NONE
```
/assign
=> Remove 'latest' docker image tag

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/OWNERS, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/templates/NOTES.txt, contrib/charts/cert-manager/templates/_helpers.tpl, contrib/charts/cert-manager/templates/certificate-crd.yaml, contrib/charts/cert-manager/templates/clusterissuer-crd.yaml, contrib/charts/cert-manager/templates/deployment.yaml, contrib/charts/cert-manager/templates/issuer-crd.yaml, contrib/charts/cert-manager/templates/rbac.yaml, contrib/charts/cert-manager/templates/serviceaccount.yaml, contrib/charts/cert-manager/values.yaml
As per https://github.com/jetstack/cert-manager/issues/489#issue-315504968, this PR syncs the chart in kubernetes/charts back to the release-0.2 branch.
From now on, we will publish changes to the chart from the latest stable release branch to kubernetes/charts periodically.
In future, we may set up a bot to automate this process, or at least remind us to do it ourselves.
**Which issue this PR fixes**: fixes #489
```release-note
NONE
```
=> Sync helm chart from kubernetes/charts back to release-0.2

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/values.yaml, contrib/manifests/cert-manager/rbac/certificate-crd.yaml, contrib/manifests/cert-manager/rbac/clusterissuer-crd.yaml, contrib/manifests/cert-manager/rbac/deployment.yaml, contrib/manifests/cert-manager/rbac/issuer-crd.yaml, contrib/manifests/cert-manager/rbac/rbac.yaml, contrib/manifests/cert-manager/rbac/serviceaccount.yaml, contrib/manifests/cert-manager/without-rbac/certificate-crd.yaml, contrib/manifests/cert-manager/without-rbac/clusterissuer-crd.yaml, contrib/manifests/cert-manager/without-rbac/deployment.yaml, contrib/manifests/cert-manager/without-rbac/issuer-crd.yaml
Bumps the chart and app version on the master branch to the latest tagged prerelease. This PR will also be on the release-0.3 branch after it's fast-forwarded to the head of master.
Part of #489 
```release-note
NONE
```
/cc @kragniz 
ref #503
=>  Bump chart and appVersion on master branch

test/e2e/certificate/certificate_acme_dns01.go, test/util/generate/certificate.go
Previously dns DNS01 provider tests actually used HTTP01 validation, and did not test wildcards.
This fixes that, and adds a test for both regular and wildcard domains. I have also switched it to use the Let's Encrypt staging server instead of Pebble, due to a bug in Pebble: https://github.com/letsencrypt/pebble/issues/118
```release-note
NONE
```
=> Fix and extend DNS01 provider e2e tests

pkg/issuer/acme/prepare.go, pkg/issuer/acme/prepare_test.go, test/e2e/certificate/certificate_acme_dns01.go, third_party/crypto/acme/types.go
Previously, in order to obtain validations for a wildcard certificate, a user must specify `certificate.spec.{dnsNames,commonName}=*.domain.com` and `certificate.spec.acme.config.domains=domain.com`.
This changes the behaviour, so that `certificate.spec.acme.config.domains=*.domain.com` is now required.
This also makes ingress-shim compatible with wildcard certs.
**Which issue this PR fixes**: fixes #501
This is based on #513 and should not be merged until after that.
It incorporates parts of #510.
```release-note
Fixed bug requiring users to specify the apex domain (e.g. example.com) when attempting to obtain a wildcard certificate from an ACME server
```
/hold
/assign
=>  Require asterisk denoted wildcard in acme solver config for wildcard certificates

pkg/apis/certmanager/v1alpha1/types.go, pkg/issuer/acme/prepare.go, test/e2e/certificate/certificate_acme_dns01.go
Previously, if a user requested a certificate for *.domain.com and domain.com at the same time, cert-manager would constantly update the DNS record with both challenge keys, causing neither to succeed.
This PR changes cert-manager to serialise validations for the same identifier (i.e. domain).
The only caveat, is if a user were to set a dns01 challenge for *.domain.com, and a http01 challenge for domain.com, the validations would still be serialised despite the fact they don't need to be.
I think this is a minor drawback however, and is an edge case.
This shouldn't be merged until after #512 
**Which issue this PR fixes**: fixes #505 
```release-note
Fix a bug causing certificates for domain.com as well as *.domain.com to fail …
```
=> Only perform one validation per identifier for a single order at a time

test/e2e/certificate/certificate_acme_dns01.go, test/e2e/framework/certificate.go
This test has been flakey as validation for both domains can take >5 minutes quite often.
This increases the timeout to 10m.
```release-note
NONE
```
=> Increase timeout for wildcard and apex domain e2e test

cmd/ingress-shim/controller/sync.go, cmd/ingress-shim/controller/sync_test.go, docs/reference/ingress-shim.rst
This is a follow up to #454, adding some unit test cases and cleaning up the commit history.
```release-note
ACTION REQUIRED: Add `certmanager.k8s.io/acme-http01-edit-in-place` annotation and change ingress-shim to set 'ingressClass' on ACME Certificate resources by default. This is a potentially breaking change for users of ingress controllers that map a single IP address to a single Ingress resource, such as the GCE ingress controller. These users will need to add the following annotation to their ingress: `certmanager.k8s.io/acme-http01-edit-in-place: "true"`.
```
cc @HeWhoWas
=> Allow ingressClass to be specified using ingress-shim

pkg/controller/certificates/controller.go
This is a follow up to #496 to increase the amount of time between attempts.
```release-note
More aggressively backoff when retry failing certificate requests
```
=> Update exponential backoff base to 5s and max to 5m

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/templates/deployment.yaml, contrib/manifests/cert-manager/rbac/certificate-crd.yaml, contrib/manifests/cert-manager/rbac/clusterissuer-crd.yaml, contrib/manifests/cert-manager/rbac/deployment.yaml, contrib/manifests/cert-manager/rbac/issuer-crd.yaml, contrib/manifests/cert-manager/rbac/rbac.yaml, contrib/manifests/cert-manager/rbac/serviceaccount.yaml, contrib/manifests/cert-manager/without-rbac/certificate-crd.yaml, contrib/manifests/cert-manager/without-rbac/clusterissuer-crd.yaml, contrib/manifests/cert-manager/without-rbac/deployment.yaml, contrib/manifests/cert-manager/without-rbac/issuer-crd.yaml
#502 changed the Helm chart to add the ingress shim flags to the main controller.
The chart was however updated incorrectly, and the previous flag values are invalid.
```release-note
NONE
```
=> Fix ingress-shim cli flags

pkg/issuer/acme/prepare.go
Check if order.Error != nil before accessing .Error() on it
**Which issue this PR fixes**: fixes #531
```release-note
NONE
```
=> Fix panic in shouldAttemptValidation

pkg/issuer/acme/setup.go, pkg/issuer/acme/util.go
When users upgrade from cert-manager v0.2 to v0.3, any existing Let's Encrypt Issuers they have will break with strange errors (see #491).
This PR causes cert-manager to set the Issuer Ready condition to false with a helpful informational message to advise users how to fix their Issuer resources.
**Which issue this PR fixes**: fixes #491
```release-note
NONE
```
=> Set Issuer ready condition to false if ACMEv1 endpoints are used

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/templates/deployment.yaml, contrib/charts/cert-manager/values.yaml, contrib/manifests/cert-manager/rbac/certificate-crd.yaml, contrib/manifests/cert-manager/rbac/clusterissuer-crd.yaml, contrib/manifests/cert-manager/rbac/deployment.yaml, contrib/manifests/cert-manager/rbac/issuer-crd.yaml, contrib/manifests/cert-manager/rbac/rbac.yaml, contrib/manifests/cert-manager/rbac/serviceaccount.yaml, contrib/manifests/cert-manager/without-rbac/certificate-crd.yaml, contrib/manifests/cert-manager/without-rbac/clusterissuer-crd.yaml, contrib/manifests/cert-manager/without-rbac/deployment.yaml, contrib/manifests/cert-manager/without-rbac/issuer-crd.yaml
Adds a way to override the cluster resource namespace when deploying with the Helm chart.
```release-note
Add clusterResourceNamespace option to Helm chart
```
=> Add clusterResourceNamespace option to Helm chart

docs/reference/issuers/acme/dns01.rst
Readme Issue:
The GCP CloudDNS example is missing a required parameter in the configuration: `project`
=> Update Readme: dns01.rst

docs/tutorials/acme/dns-validation.rst
Updates the ACME DNS01 tutorial with a mention and use of wildcard certificates.
**Which issue this PR fixes**: fixes #456 
```release-note
NONE
```
=> Update acme dns01 tutorial with reference to wildcard domains

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/templates/deployment.yaml, contrib/charts/cert-manager/values.yaml, contrib/manifests/cert-manager/rbac/certificate-crd.yaml, contrib/manifests/cert-manager/rbac/clusterissuer-crd.yaml, contrib/manifests/cert-manager/rbac/deployment.yaml, contrib/manifests/cert-manager/rbac/issuer-crd.yaml, contrib/manifests/cert-manager/rbac/rbac.yaml, contrib/manifests/cert-manager/rbac/serviceaccount.yaml, contrib/manifests/cert-manager/without-rbac/certificate-crd.yaml, contrib/manifests/cert-manager/without-rbac/clusterissuer-crd.yaml, contrib/manifests/cert-manager/without-rbac/deployment.yaml, contrib/manifests/cert-manager/without-rbac/issuer-crd.yaml
Previously, a ConfigMap in the kube-system namespace was used to perform leader election. This updates the chart to use the same namespace as cert-manager is deployed into for leader election.
```release-note
Use cert-manager deployment namespace by default for leader election
```
=> Add leaderElection.namespace option to helm chart

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/values.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac.yaml
Bumps strings for the v0.3.0 release
Merge after #574 
```release-note
NONE
```
=> Bump chart and manifests for v0.3.0 release

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/templates/NOTES.txt, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac.yaml
When syncing changes page from the k/charts repo in the past, this was switched to plain http.
```release-note
NONE
```
=> Use https docs URL in chart NOTES.txt

pkg/issuer/vault/setup.go
Fix panic when Vault server is not initialized or is sealed.
```release-note
vault: fix panic when vault is sealed or uninitialized
```
=> vault: fix panic when vault is sealed or uninitialized

hack/build/dockerfiles/acmesolver/Dockerfile
acmesolver won't run in a namespace with a restrictive PSP
(Pod Security Policy)[1] without this change.
Note: A numeric user id is required due to [1]
[1] https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups
[2] https://github.com/kubernetes/kubernetes/pull/56503
```release-note
Run acmesolver container as non-root user
```
=> acmesolver: Run as non-root

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/templates/deployment.yaml, contrib/charts/cert-manager/values.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac.yaml
Add support for custom DNS settings for the cert-manager pod 
This allows HTTP / DNS challenges to be self checked in AWS setups in which both a public and private DNS zone are present for the same domains. Without this the pod will never see the challenge that is going to be presented to LE because they'll be added to public ingresses / DNS zones, failing with something along these lines:
```
I0427 13:23:33.027444       1 sync.go:241] Error preparing issuer for certificate frehm/testing: http-01 self check failed for domain "testing.dev.k8s.cafe
```
I remember seeing some comments / issues related to this but haven't had a chance to look around again.
**Special notes for your reviewer**: 
This is my first ever …
=> Support for custom dns settings

pkg/issuer/acme/dns/dns.go
Improve logging for Google CloudSQL configuration errors around misconfigured ServiceAccounts.
In my case, there happened to be two Secrets with the same name and different keys, and it was impossible to determine which Secret the cert-manager was trying to load.
/fixes 539
=>  Improve logs for CloudDNS service account errors

pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/http/http_test.go, pkg/issuer/acme/http/ingress.go, pkg/issuer/acme/http/pod.go, pkg/issuer/acme/http/service.go
It's useful to know what namespace is being operated on, so log
namespaces all over the place!
Specifically, I think this would have helped in #540
```release-note
NONE
```
=>  issuer/acme/*: log namespaces for resources 

docs/tutorials/vault/creating-vault-issuers.rst
Update the documentation to avoid errors using vault issuer
```NONE
```
=> Vault issuer MUST USE the vault 'sign' endpoint

pkg/issuer/acme/dns/util/wait.go, pkg/issuer/acme/dns/util/wait_test.go
Fixes eTLD and CNAME issues with FindZoneByFqdn
See https://github.com/jetstack/cert-manager/issues/581
```release-note
Fix bugs affecting eTLD and CNAMEs during DNS zone resolution
```
=> FindZoneByFqdn fixes from lego

test/e2e/certificate/certificate_acme.go
Let's encrypt no longer allow use of @example.com emails for ACME accounts.
This PR switches us to use a @cert-manager.io email for the ACME account used during e2e tests, as currently the dns01 e2e tests are performed against the let's encrypt staging endpoint due to issues described in https://github.com/letsencrypt/pebble/issues/118
```release-note
NONE
```
=> Update e2e test ACME email

pkg/issuer/acme/prepare.go
The ACME issuer will check that a given challenge type is configured on the issuer being used.
fixes #607
```release-note
action required: ACME http01 validation is no longer attempted using an
Issuer/ClusterIssuer with no ACME http01 config.  Note that the minimal
`http01: {}` config IS sufficient.
If you rely on ACME http01 validation, you should check your issuers to make
sure http01 validation is explicitly enabled.
```
=> Check the acme issuer has the challenge type configured.

pkg/issuer/acme/dns/route53/OWNERS
cc @munnerz; I'd like to volunteer to help maintain the route53 provider more formally.
I believe the bot favors owners in deeper OWNERS files even though everyone in the root OWNERS is still able to review/approve/etc, so I included you for the sake of trying to distribute review load a little bit :smile:
=> issuer/dns/route53: add myself as owner

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/templates/_helpers.tpl, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac.yaml
The newer 'fullname' helper function automatically avoids name duplication. This change updates the template in cert-manager to include that functionality.
Given there is generally only one cert-manager per cluster, if you install cert-manager and call it `cert-manager`:
```
helm upgrade --install cert-manager stable/cert-manager
```
You get deployments and pods called `cert-manager-cert-manager` 
With the update  version (taken from the `helm create` template for helm 2.8.2) you instead get deployments and pods called simply `cert-manager`.
There is a workaround possible at the moment, but the automatic behavior is more intuitive for new users.
```
helm upgrade --install cert-manager stable/cert-manager --set=fullnameOverride=cert-manager
``` …
=> Update the 'fullname' template to match helm 2.8.2

Makefile
This PR add an environement variable to the docker build command.
This environment variable can be use to add some flags to the docker
build command.
For example it allow the build of docker images when the developper is
behind a http proxy by using the '--build-arg http_proxy --build-arg
https_proxy' flags.
```release-note
NONE
```
=> Add DOCKER_BUILD_FLAGS environment variable

pkg/controller/clusterissuers/sync.go, pkg/controller/issuers/sync.go
This fixes a bug that could cause ACME issuers to spin, re-checking their account validation status every few seconds.
```release-note
Fix a bug that could cause ACME Issuers to re-check Account validation status every few seconds
```
=> issuers: Skip triggering API update if status has not changed

pkg/issuer/acme/prepare.go
When an ACME renewal is due, the previous Order's status will be set to 'invalid'.
This *should* trigger cert-manager to automatically create a new order (after the appropriate rate limit/back off is applied).
However, in `shouldAttemptValidation`, we return the *invalid* order, which consequently fails to validate (as it is invalid!).
This was a bug from the re-implementation of ACME in v0.3, and the method comment on this function does state that only valid orders (or orders that *can* be attempted) will be returned.
This patch fixes the bug, and should resolve issues users see with renewal in v0.3. This PR will be cherry picked into v0.3, to become v0.3.1.
```release-note
Fix bug that could cause ACME Certificates to not be …
```
=> Don't return invalid/expired orders in shouldAttemptValidation

docs/tutorials/vault/creating-vault-issuers.rst, pkg/controller/clusterissuers/sync.go, pkg/controller/issuers/sync.go, pkg/issuer/acme/prepare.go, test/e2e/certificate/certificate_acme.go
Cherry pick of #628 #655 #662 #674 on release-0.3.
#628: Vault issuer MUST USE the vault 'sign' endpoint
#655: Update e2e test ACME email
#662: issuers: Skip triggering API update if status has not changed
#674: Don't return invalid/expired orders in shouldAttemptValidation
=> Automated cherry pick of #628 #655 #662 #674

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/templates/deployment.yaml, contrib/charts/cert-manager/values.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac.yaml
This allows configuring environment variables for the `cert-manager`.
For example it enables configuring `Vault` client to accept connections with kubernetes Certificate Authority:
```yaml
extraEnv:
- name: VAULT_CAPATH
value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
```
```release-note
added option to set additional environment variable values to the helm chart
```
=> charts/cert-manager: add extraEnv

Gopkg.lock, pkg/apis/certmanager/validation/certificate.go, pkg/apis/certmanager/validation/certificate_test.go, pkg/apis/certmanager/validation/clusterissuer.go, pkg/apis/certmanager/validation/issuer.go, pkg/apis/certmanager/validation/issuer_test.go, pkg/controller/certificates/sync.go, pkg/controller/clusterissuers/sync.go, pkg/controller/clusterissuers/sync_test.go, pkg/controller/issuers/sync.go, pkg/controller/issuers/sync_test.go
Adds resource validation functions, and executes them at the start of sync loops.
This is a precursor to #478 whilst we wait for PRs to merge into Helm (and for Helm 2.10 to be released). These functions can be directly re-used as part of the new webhook in that PR.
**Which issue this PR fixes**: part of #132
```release-note
Add resource validation at start of sync loops, and mark resources as not Ready when invalid
```
/cc @kragniz
=> Resource validation as part of controller sync loops

pkg/controller/ingress-shim/sync.go, pkg/controller/ingress-shim/sync_test.go
Fixes #619.
```release-note
Fix bug that could cause changes to Ingress resources when using ingress-shim to not be properly propagated to their respective Certificate resources
```
=> Update spec.acme.config field when ingress changes

.gitlab-ci.yml
Since we started verifying dep in CI, and since we *still* use GitLab for release builds, we need to install dep in our GitLab CI environment too. In future we can hopefully get rid of this duplication!
```release-note
NONE
```
=> Install dep during gitlab-ci build

pkg/issuer/acme/prepare.go, third_party/crypto/acme/types.go
There's a new status value for orders: "ready".
Addresses #692 
```release-note
ACME: Handle the new Let's Encrypt 'Ready' state for orders
```
=> Support the new ACMEv2 "ready" order status

docs/reference/clusterissuers.rst, pkg/controller/ingress-shim/sync.go, pkg/controller/ingress-shim/sync_test.go, pkg/issuer/acme/prepare.go, third_party/crypto/acme/types.go
Cherry pick of #686 #695 #698 on release-0.3.
#686: Update spec.acme.config field when ingress changes
#695: Add doc on secret references for cluster issuers
#698: Support the new "ready" order status
=> Automated cherry pick of #686 #695 #698

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/values.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac.yaml
Version bump for v0.3.2
```release-note
NONE
```
=> Bump Helm chart for v0.3.2

pkg/apis/certmanager/v1alpha1/helpers.go
This is a simple way to prevent panics if a Certificate specifies a DNS01 provider that is not present on the Issuer resource.
We should be able to bail out earlier in the process in this case once we have 'runtime validation' in place (i.e. we validate Certificate resources at the start of the issuer's sync loop/present function).
Usually we could implement this in the API validation function (which will eventually become a webhook), however as the webhook would need to check the specified issuer in order to validate the resource, we cannot as it would introduce ordering requirements for users creating resources (which goes against Kubernetes API conventions). Instead, we must perform this kind of validation whilst *syncing* the Certificate instead …
=> Prevent panics in v1alpha1 helpers.go

pkg/apis/certmanager/v1alpha1/helpers.go
Prevent panics in v1alpha1 helpers.go (#708)
```release-note
NONE
```
=> Automated cherry pick of #708 upstream release 0.3

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/templates/deployment.yaml, contrib/charts/cert-manager/values.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac.yaml
**What this PR does / why we need it**: Solves #310 Allow setting http_proxy environment variables
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #310
```release-note
Added configuration variables to set http_proxy, https_proxy and no_proxy environment variables in Helm chart.
```
=> Allow setting http_proxy and https_proxy in cert-manager deployment

docs/reference/issuers/acme/dns01.rst
After testing the suggested policy both with the AWS policy simulator and by using it with cert-manager I have found that the ARN prefixes for the resources included in the statement cause the provider to fail with an access denied error. This new policy is equivalent as the resource types are already specified by the actions and it is valid according to the AWS policy simulator.
```release-note
NONE
```
=> Fix AWS DNS policy example

cmd/controller/start.go
This adds a log entry showing the version and revision of cert-manager being run. Example:
```
g/s/g/j/cert-manager {version-in-logs} $ ./hack/build/dockerfiles/cert-manager-controller_linux_amd64
I0706 17:28:15.437043   23804 start.go:63] starting cert-manager canary (revision 2ef08e2b3c9ef93c89b3e264b05ef8514e8b4fea)
I0706 17:28:15.437546   23804 server.go:68] Listening on http://0.0.0.0:9402
...
```
```release-note
none
```
=> Add log message showing git tag and commit during startup

pkg/apis/certmanager/v1alpha1/types.go, pkg/controller/certificates/sync.go, test/e2e/framework/certificate.go
**What this PR does / why we need it**: this applies a `certmanager.k8s.io/certificate-name` label to secrets created by cert-manager.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #566
```release-note
Add `certmanager.k8s.io/certificate-name` label to secrets.
```
=> Add certificate-name label to created secrets

pkg/issuer/acme/dns/route53/route53.go
I got confused when I saw that we had records "Managed by Lego", when we're not running Lego. Updated to say "Managed by cert-manager" instead which I think makes more sense.
=> route53: update managed by DNS record comment

pkg/issuer/acme/http/pod.go, pkg/issuer/acme/http/service.go
This should help alleviate issues described [here](https://medium.com/@prune998/istio-envoy-cert-manager-lets-encrypt-for-tls-14b6a098f289) when using cert-manager with Istio.
It simply adds the `auth.istio.io` annotation to all services created to solve HTTP01 challenge validations.
One question I have (hopefully @ldemailly can shed some light?): will this not break if a user has sidecar injection enabled on the namespace containing the acmesolver pods? If yes, we need some way to trigger this on/off, or somehow support custom annotations (#447).
**Which issue this PR fixes**: fixes #238, fixes #231
```release-note
Support for ACME HTTP01 validations when using istio-ingress with a mTLS enabled mesh
```
=> Add auth.istio.io annotation to ACME HTTP01 service

docs/generated/reference/output/reference/api-docs/index.html, docs/tutorials/vault/creating-vault-issuers.rst, pkg/apis/certmanager/v1alpha1/types.go, pkg/issuer/vault/issue.go, pkg/issuer/vault/setup.go, test/e2e/certificate/certificate_vault.go, test/e2e/issuer/issuer_vault.go, test/util/util.go, test/util/vault/util.go
Configurable appRole authentication path in Vault.
fixes #560 
```release-note
Configurable Vault appRole authentication path using the attribute is spec.vault.auth.authPath in the issuer.
```
=> Vault: configurable appRole authentication path

cmd/controller/app/controller.go, cmd/controller/app/options/options.go, pkg/util/util.go, pkg/util/util_test.go
This adds a new flag, which can be used to disable running the
ingress-shim controller (and any of the other controllers):
--controllers=issuers,clusterissuers,certificates
Fixes #567.
```release-note
To disable ingress-shim, you can now set this flag: `--controllers=issuers,clusterissuers,certificates`
```
=> Add --controllers flag to set which controllers are run

docs/reference/issuers.rst
Adds a missing link to the selfsigned issuer docs
```release-note
NONE
```
=> Add link to selfsigned issuer docs

docs/generated/reference/output/reference/api-docs/index.html, pkg/apis/certmanager/v1alpha1/types.go, pkg/apis/certmanager/validation/certificate.go, pkg/apis/certmanager/validation/certificate_test.go, pkg/issuer/acme/acme.go, pkg/issuer/acme/issue.go, pkg/issuer/acme/setup.go, pkg/issuer/ca/issue.go, pkg/issuer/ca/renew.go, pkg/issuer/selfsigned/issue.go, pkg/issuer/selfsigned/renew.go, pkg/issuer/vault/issue.go, pkg/util/kube/pki.go, pkg/util/pki/csr.go, pkg/util/pki/csr_test.go, pkg/util/pki/generate.go, pkg/util/pki/generate_test.go, pkg/util/pki/parse.go, pkg/util/pki/parse_test.go
- Adds two fields to CertificateSpec:
- `keyAlgorithm`, denotes which algorithm to use when generating
a private key. Can be either `rsa` or `ecdsa`. When not set, the
default algorithm used `rsa`.
- `keySize`, denotes the key size of the private key being generated.
For `rsa`, minimum key size is 2048 and maximum is 8192.
For `ecdsa`, sizes 224, 256, 384 & 521 are supported.
See https://golang.org/pkg/crypto/elliptic
If both fields are not populated, `rsa` with key size `2048` is used
- Adds `pki.GeneratePrivateKeyForCertificate` function that takes in a `Certificate` and generates a private key based on the `keyAlgorithm` & `keySize` fields in the `CertificateSpec`
- Adds helper functions to the `pki` package to generate/parse `rsa` and `ecdsa` …
=> Add keyAlgorithm and keySize fields to Certificates, and support ECDSA keys

hack/verify-deps.sh
If "dep status" fails on CI, it's useful to know what version of dep is
being used to locally reproduce and examine the issue.
This is motivated by a verify error encountered on #746 which I can't reproduce with my version of dep locally.
```release-note
NONE
```
=> hack/verify: also include 'dep version' output

pkg/issuer/acme/dns/clouddns/clouddns.go
Previously this would fail if you use a CNAME for the _acme-challenge
record.
```release-note
none
```
=> clouddns: find hosted zone for challenge record

Gopkg.lock, pkg/issuer/acme/dns/route53/route53.go
Fixes #736.
Prior to this change, it was quite possible to end up with a queue of
cleanup tasks that would never succeed.
```release-note
Fixed Route53 cleanup errors for already deleted records.
```
=> issuer/route53: fix delete for 'NotExist' errors

pkg/issuer/acme/dns/util/dns.go, pkg/issuer/acme/dns/util/wait.go
Domain for which certificate is asked for can have a `CNAME`, so we should check it.
If domain has a `CNAME`, create the challenge `TXT` record in the alias domain.
This is useful in the scenario where a company like us is using some DNS provider
which is not supported dynamically. We can then create a CNAME for records like
`_acme-challenge.example.com -> example.aws.hosted.com`
So this will allow us getting cert for `*.example.com` with creating a `TXT` record in route53 hosted zone for above example.
```release-note
Add support for …
```
=> add support CNAME for dns-01 challenge

pkg/issuer/acme/dns/clouddns/clouddns.go
Cherry pick of #754 on release-0.4.
#754: clouddns: use fqdn for challenge cleanup
=> Automated cherry pick of #754

pkg/issuer/acme/dns/clouddns/clouddns.go
This is the same as the problem fixed in #750, but for cleanup.
```release-note
Fix cleanup of Google Cloud DNS hosted zone for dns-01 challenge records
```
=> clouddns: use fqdn for challenge cleanup

contrib/charts/pebble/Chart.yaml, contrib/charts/pebble/values.yaml, pkg/issuer/acme/issue.go, test/chart/.testenv
When the new 'ready' state for orders was added, we did not add code into the obtainCertificate function to gate finalising orders with the ACME server until they are in a 'ready' state.
This PR adds a gate to ensure that the order is in a valid state for finalisation.
It may also require us to bump the version of Pebble used in our e2e tests, as the older versions will never set the `status` to 'ready'
**Which issue this PR fixes**: fixes #758
```release-note
Fix a race that could cause ACME orders to fail despite them being in a 'valid' state
```
/cc @kragniz
@tlycken @damienwebdev
=> Wait for ACME Orders to be in 'ready' state before attempting finalization

pkg/apis/certmanager/validation/certificate_for_issuer.go, pkg/apis/certmanager/validation/certificate_for_issuer_test.go, pkg/controller/certificates/sync.go, pkg/issuer/const.go, pkg/issuer/factory.go
Fixes #735
```release-note
Add base issuer-specific validation to certificates at runtime
```
=> Add base of issuer-specific validation to certificates at runtime

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/templates/rbac.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac.yaml
As version `0.4` is used now, it should be safe to remove `endpoints` from the ClusterRole resources. See old `TODO` in code.
Release Note
```release-note
NONE
```
=> helm chart: remove endpoints from rbac resources

cmd/controller/app/options/options.go
The previous defaults were overly chatty and causing calls to the ConfigMap update endpoint every ~2s.
This PR changes it to make a call every 15s. Instances of the controller will also hold the leader election lease for up to 60s.
Fixes #723 
```release-note
Reduce rate of leader election ConfigMap updates
```
=> Change leader election duration defaults to be less chatty

cmd/controller/app/controller.go, cmd/controller/app/options/options.go, pkg/controller/certificates/sync.go, pkg/controller/context.go, pkg/controller/helper.go
This helps break out the changes in #800
It adds a new RenewBeforeExpiryDuration option to help resolve the issues described there.
This option can in future become the default global option when we support this as a field on the issuer spec.
~QUESTION: should this field be called `renew-before-expiry-duration`?~ yes (cc @zuzzas)
```release-note
Add renew-before-expiry-duration option to configure how long before expiration a certificate should be attempted to be renewed
```
/cc @kragniz
=> Add RenewBeforeExpiryDuration option to controller context

cmd/controller/app/controller.go, cmd/controller/app/options/options.go, pkg/acme/client/fake.go, pkg/acme/client/interfaces.go, pkg/acme/client/middleware/logger.go, pkg/controller/certificates/sync.go, pkg/controller/context.go, pkg/controller/helper.go, pkg/issuer/acme/issue.go, pkg/util/pki/generate.go, pkg/util/pki/generate_test.go, third_party/crypto/acme/acme.go
Recent changes to Let's Encrypt have meant that they now use the 'ready' ACME status condition to indicate an order is ready to be finalized.
Order's that have already been finalized will have a state 'valid'.
If an order is ready, we must finalize it (i.e. submit a CSR to the ACME server)
If an order is valid, all we can do is retrieve the existing Certificate (as signed by the server in response to the CSR initially submitted when the order was 'ready').
This PR adapts our Issue function to handle these cases properly.
It is slightly more complex due to case (2) (where the order is already valid). If we have lost the certificate's private key, we need to detect this and trigger a new order to be created so we can re-finalize with the new private …
=> Add logic to handle ready vs valid ACME orders properly

pkg/issuer/acme/issue.go, pkg/util/pki/csr.go
Cherry pick of #807 #811 on release-0.4.
#807: Catch edge case where the CN and DNSNames on a Certificate
#811: Don't bundle the CA certificate when selfsigned
=> Automated cherry pick of #807 #811

pkg/util/pki/csr.go
Don't bundle the CA certificate when that certificate is selfsigned.
**Which issue this PR fixes**: fixes #779
```release-note
Don't bundle the CA certificate when using the self signed issuer
```
=> Don't bundle the CA certificate when selfsigned

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/values.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac.yaml
Bumps the image version for v0.4.1
```release-note
NONE
```
=> Bump image version for v0.4.1

CONTRIBUTING.md, docs/devel/dco-sign-off.rst, docs/devel/index.rst
Adds details on DCO sign-off to our documentation and root of the repo.
Wording here has been borrowed from the `heptio/ark` repository: https://github.com/heptio/ark/blob/master/CONTRIBUTING.md
=> Add details on DCO sign-off

pkg/issuer/acme/dns/akamai/akamai.go, pkg/issuer/acme/dns/akamai/akamai_test.go, pkg/issuer/acme/dns/azuredns/azuredns.go, pkg/issuer/acme/dns/azuredns/azuredns_test.go, pkg/issuer/acme/dns/clouddns/clouddns.go, pkg/issuer/acme/dns/clouddns/clouddns_test.go, pkg/issuer/acme/dns/cloudflare/cloudflare.go, pkg/issuer/acme/dns/cloudflare/cloudflare_test.go, pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/dns_test.go, pkg/issuer/acme/dns/route53/route53.go, pkg/issuer/acme/dns/route53/route53_test.go, pkg/issuer/acme/dns/util/dns.go, pkg/issuer/acme/dns/util/wait.go, pkg/issuer/acme/dns/util/wait_test.go, pkg/issuer/acme/dns/util_test.go
Plumb the configured dns servers into more areas of the codebase allowing split horizon dns setups to work again. Previously there was a lot of use of the default `RecursiveNameservers`.
fixes: #820
```release-note
NONE
```
=> fix: plumb dns servers into more areas

pkg/issuer/acme/http/ingress.go, pkg/issuer/acme/http/ingress_test.go
Previously, if an ingress resource did not specify an existing `rule` containing the domain name we need to solve for (e.g. if only the default backend is configured), we would leave an empty `rule` (one with any path configuration) which would consequently fail validation when submitting back to the apiserver.
This patch fixes this so we remove empty rules after cleaning up. It also adds a unit test to verify the behaviour. The newly added unit test fails without the second commit applied 😄
The actual ingress test fixture for this was taken from #828.
**Which issue this PR fixes**: fixes #828 
```release-note
Fix issue causing existing Ingresses to not be cleaned up properly after HTTP01 challenges in some cases
```
=> Fix issue causing existing ingresses to not be cleaned up properly

docs/generated/reference/output/reference/api-docs/index.html, pkg/apis/certmanager/v1alpha1/types_certificate.go, pkg/apis/certmanager/validation/certificate_for_issuer.go, pkg/util/pki/csr.go
Adds an 'isCA' field to the Certificate spec.
This is required for resource validation (see #657). Once we have resource validation merged, we can add all sorts of checks to make sure this is not set on ACME certs 😄 
```release-note
Add isCA field to Certificates
```
=> Add 'isCA' field to Certificate spec

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/templates/certificate-crd.yaml, contrib/charts/cert-manager/templates/clusterissuer-crd.yaml, contrib/charts/cert-manager/templates/issuer-crd.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac.yaml
It annotates all CRDs with "crd-install" hook.
This fix is required in order to make helm properly verify the CRDs
when cert-manager chart is referenced as a dependency of another chart.
@munnerz Do I have to send this patch also to `stable/cert-manager` chart, or are you going to sync that chart from this repo? 
```release-note
```
=> chart: annotate all CRDs with "crd-install" hook

contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac.yaml
#823 was merged before the quick-verify job bumped its Helm version to 2.10.
This means that future jobs are now failing, as these values are not set on the CRDs generated as part of update-deploy-gen.
This unblocks the merge queue and fixes issues in #849  😄 
```release-note
NONE
```
=> Run hack/update-deploy-gen.sh

pkg/issuer/acme/dns/cloudflare/cloudflare.go
It's possible for cert-manager to get in a bad state where it thinks there's something to cleanup, but repeatedly fails to clean it up.
Not finding the record should not be an error when we're trying to delete the record anyway.
**Which issue this PR fixes**: fixes #654
```release-note
Fix cloudflare provider failing on cleanup if no record is found
```
=> Fix cloudflare provider failing on cleanup if no record is found

.gitlab-ci.yml
We still use a completely different set of tooling versions when building the master branch on GitLab 😢 
This PR bumps Helm to 2.10.
#844 should help resolve these issues in future.
```release-note
NONE
```
=> Bump helm version on Gitlab CI

pkg/issuer/acme/dns/acmedns/acmedns.go, pkg/issuer/acme/dns/acmedns/acmedns_test.go, pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/dns_test.go
Fixes cert-manager panic.
**Which issue this PR fixes** : #857 
FYI tested on my live install, instead of panic-ing now properly getting `error instantiating acmedns challenge solver: invalid character '{'` from logs.
The key fix is that last `err != nil` check in `acme/dns/dns.go` switch/case entry
for `AcmeDNS`, to avoid following thru and wrongly returning `impl, nil` (with a `nil` impl pointer).
**Release note**: 
```
fix panic from acmedns.go constructor failure
```
=> [jjo] fix panic from acmedns.go constructor failure

.gitlab-ci.yml
Bump the version of go and dep used for GitLab builds.
In future we'll switch to using the same base image as our GitHub builds. After that, we will switch to using Prow for pushing docker images.
This fixes pushes of the master branch and tags.
```release-note
NONE
```
/assign
=> Bump golang and dep version on gitlab

Makefile
Standardise our makefile's verify targets to have a `verify_` prefix.
We can then create a presubmit per verify target in our CI
```release-note
NONE
```
/assign
=> Standardise verify make targets

pkg/apis/certmanager/validation/issuer.go, pkg/apis/certmanager/validation/issuer_test.go
The validation message was invalid. This PR fixes it to match the JSON tag for the field.
```release-note
NONE
```
/assign
=> Fix acme.privateKeySecretRef validation message

pkg/issuer/acme/dns/clouddns/clouddns.go, pkg/issuer/acme/dns/clouddns/clouddns_test.go, pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/util_test.go
this PR enables gcloud authentication via meta authentication api
fixes #241
```release-note
enable metadata server authentication for cloudDNS
```
=> enable clouddns meta auth

pkg/issuer/acme/dns/dns.go
Also adds documentation comments for public methods (caught by 'go lint').
Fixes a non-propagated `error` type in `dns.go`.
```release-note
NONE
```
=> Add an error check for AzureDNS failure to create a solver.

docs/reference/issuers/acme/dns01.rst
Heyo, loving the cert-manager, but found a small error in the docs.
=> Documentation fix for `hostedZoneID` field

pkg/apis/certmanager/validation/issuer.go, pkg/apis/certmanager/validation/issuer_test.go
#664 added support for resource validation using the CloudDNS metadata server.
As a result, we need to relax the validation rules around the serviceAccount field to allow omitting a secret ref, as per https://github.com/jetstack/cert-manager/issues/241#issuecomment-420097826
```release-note
NONE
```
=> Relax resource validation for CloudDNS service account credentials

Makefile
This adds a new target that can be used to regenerate all generated files.
This should make it easier for users developing new features, by providing a single command that can be run in order to update *all* generated files.
cc @Queuecumber 
```release-note
NONE
```
=> Add 'make generate' target to run all hack generators

docs/reference/ingress-shim.rst
There were some issues with the rendering of code blocks in the ingress-shim doc, also remove an outdated note.
```release-note
NONE
```
=> Fix issues with ingress-shim doc rendering and remove warning

.gitlab-ci.yml, Makefile
Bazel's rules_docker pushes v2.2 manifests to the image registry.
Quay.io *still* does not support manifest lists, so this step is currently failing in our GitLab CI release environment.
This PR switches us to using standard docker to *push images only*.
```release-note
NONE
```
/cc @kragniz
=> Workaround quay.io not support v2.2 docker image manifests

pkg/controller/certificates/sync.go, pkg/issuer/acme/issue.go, pkg/issuer/acme/renew.go, pkg/issuer/ca/issue.go, pkg/issuer/ca/renew.go, pkg/issuer/issuer.go, pkg/issuer/selfsigned/issue.go, pkg/issuer/selfsigned/renew.go, pkg/issuer/vault/issue.go, pkg/issuer/vault/renew.go, pkg/util/pki/csr.go, test/util/util.go
This PR includes the CA cert as a field in the issued TLS secret as `ca.crt`. 
Although the TLS secret specification does not explicitly support this field, some projects (like nginx-ingress for example) check the existence of the `ca.crt` field and use it's value to provide special handling for the certificate. For example, if nginx-ingress is aware that a certificate is (or has) a ca, it will allow that field to be used to validate tls mutual authentication. In general it can be useful to know the CA certificate and to be able to get at it without parsing a PEM chain. 
Right now this works for vault, ca, and self-signed issuers, ACME support is more complex since it requires retrieving the CA certificate from the ACME server. Support for this is …
=> Include CA Certificate In Secrets

cmd/controller/app/BUILD.bazel, cmd/controller/app/controller.go, cmd/controller/app/options/options.go, pkg/controller/BUILD.bazel, pkg/controller/context.go, pkg/issuer/acme/http/BUILD.bazel, pkg/issuer/acme/http/pod.go
Makes the values configurable that have been hardcoded/introduced via #408 
It refs  #892 but doesn't necessarily fixes it.
```release-note
Make http01 solver pod resource request/limits configurable
```
=> make http01 solver pod resource request/limits configurable, refs #892

docs/generated/reference/openapi/openapi_generated.go, docs/generated/reference/output/reference/api-docs/index.html, docs/reference/issuers/acme/http01.rst, pkg/apis/certmanager/v1alpha1/BUILD.bazel, pkg/apis/certmanager/v1alpha1/types_issuer.go, pkg/apis/certmanager/validation/BUILD.bazel, pkg/apis/certmanager/validation/issuer.go, pkg/apis/certmanager/validation/issuer_test.go, pkg/issuer/acme/http/http.go, pkg/issuer/acme/http/service.go, pkg/issuer/acme/http/service_test.go
I have a scenario where services with type=NodePort can't be deployed (disabled by quota). This PR simply switches it back to type=ClusterIP (default) since I have no indication why NodePort should make sense for our http01 implementation.
```release-note
Make http01 solver serviceType configurable, so one can use ClusterIP instead of the previously hardcoded type NodePort. NodePort still remains as default but may be changed in future.
```
=> Make http01 solver serviceType configurable

pkg/issuer/acme/BUILD.bazel, pkg/issuer/acme/issue.go
This PR separates the ACME Issuer out into different functions, and generally tidies up and documents things better.
The only functionality change here:
- when a TLS certificate is read from the ACME server, if that certificate fails to parse then the order is retried (whereas previously we continuously attempted to retrieve & parse that certificate)
```release-note
NONE
```
=> Cleanup ACME Issue function, separate into different functions

pkg/util/pki/csr.go, pkg/util/pki/csr_test.go
This allows the GenerateCSR & GenerateTemplate functions to set the PublicKeyAlgorithm field on the resources it creates, useful for issuers that may require the field to be set.
```release-note
NONE
```
=> Update SignatureAlgorithm function to also return PublicKey type

test/e2e/framework/addon/chart/addon.go
Previously during end-to-end tests we still relied on a system provided helm and did not honour the --helm-binary-path flag.
This changes fixes that to require a path to helm be provided at e2e invocation time.
This is all handled by the Makefile `make e2e_test` target (and consequently through `./hack/ci/run-e2e-kind.sh`) so should not really effect development workflow.
```release-note
NONE
```
=> Fix using Bazel built helm during e2e tests

pkg/controller/clusterissuers/controller.go, pkg/controller/ingress-shim/controller.go, pkg/controller/issuers/controller.go
This PR adjusts the issuer, clusterissuer and ingress-shim controllers to use an exponential back-off when an issuer or clusterissuer has failed to process.
I thought this was already done when we adjusted the values on the Certificate controller in response to #407, but @jsha has reported that we are hitting their acme registration endpoint as well as /directory aggressively.
In cases where updating the Kubernetes API is failing, or any other failure in `Sync` or `Setup`, we could enter a tight loop retrying this verification.
The previous ratelimiter in use was the default one defined in `workqueue`:
```
return NewMaxOfRateLimiter(
NewItemExponentialFailureRateLimiter(5*time.Millisecond, 1000*time.Second),
// 10 qps, 100 bucket size.  This is only for retry speed and its only the …
```
=> Update workqueue rate limiters on issuers and ingress-shim controllers

test/e2e/framework/addon/chart/addon.go
Previously the --wait flag was causing issues as helm was not returning.
Since we have merged #983, I want to re-try this as we're using a newer version of Helm which should hopefully have resolved the issue!
```release-note
NONE
```
=> Use --wait flag when installing e2e charts

pkg/issuer/acme/http/http.go, pkg/issuer/acme/http/http_test.go
* A context was created with `WithTimeout` of `HTTP01Timeout`, but not used in the HTTP requests in `testReachability`
* `testReachability` completely absorbed HTTP client errors which makes it very hard in some situations to debug issues where the challenge does not succeed (in 0.5.0 it only logs a "... self check failed for domain ..."
=> Respect HTTP01Timeout, improve logging

Makefile, test/e2e/framework/BUILD.bazel, test/e2e/framework/config/suite.go, test/e2e/framework/framework.go, test/e2e/framework/util/BUILD.bazel, test/e2e/framework/util/errors/BUILD.bazel, test/e2e/framework/util/errors/errors.go, test/e2e/suite/issuers/acme/dnsproviders/BUILD.bazel, test/e2e/suite/issuers/acme/dnsproviders/cloudflare.go
Since the change to e2e's, we now fail tests instead of skipping them if DNS01 credentials are not provided.
This patch reverts us to the previous behaviour, skipping the tests if credentials are not provided.
It also adjusts the way we provide details to the e2e's, removing usage of CLI args from the Makefile.
```release-note
NONE
```
=> Don't fail e2e's if cloudflare dns01 credentials are not provided

Makefile, hack/ci/run-e2e-minikube.sh
Our periodic minikube CI jobs have been failing since we added the RBAC 'conformance' checks, as well as with the refactor of the e2e suite.
This PR fixes that environment by:
1) skipping RBAC checks (as they fail on Kubernetes before 1.9)
2) skip setting up cluster-wide tiller and nginx-ingress (this is now handled as part of the e2e suite)
```release-note
NONE
```
=> Fix up minikube e2e tests

cmd/webhook/main.go
**What this PR does / why we need it**: Fixes the `ERROR: logging before flag.Parse` errors that occur when running webhook
**Which issue this PR fixes**: fixes #932 
```release-note
NONE
```
=> webhook: Fix "logging before flag.Parse" errors

.gitlab-ci.yml
Since we now require Bazel >=0.17.1, we need to use an updated test image on GitLab.
```release-note
NONE
```
=> Bump e2e image used on gitlab

docs/reference/ingress-shim.rst, pkg/controller/ingress-shim/sync.go, pkg/controller/ingress-shim/sync_test.go
**What this PR does / why we need it**: to get letsencrypt's certificates for internal services.
Allow ingress-shim to use certificate ingress class other then original ingress class. Part of #942.
```release-note
Added certmanager.k8s.io/acme-http01-ingress-class annotation
```
=> Add certmanager.k8s.io/acme-http01-ingress-class annotation

test/e2e/framework/addon/tiller/addon.go
Removes an old and no longer correct notice on the tiller addon
```release-note
NONE
```
=> e2e: remove old notice about Tiller addon

docs/tutorials/acme/migrating-from-kube-lego.rst
Related to #773 - the previous instructions guide the user to look for events on the certificate related to when renewals are scheduled. This change directs them to view the logs to see the renewal schedule messages.
Documentation update to better reflect where to look to see renewal schedule information.
**Which issue this PR fixes**: fixes #773
=> Update kube-lego migration guide towards logs

pkg/util/BUILD.bazel, pkg/util/version.go, pkg/util/version_test.go
This PR removes the Git commit hash from the version string unless `github.com/JetStack/cert-manager/pkg/util.AppVersion` is set to `canary`.
**Which issue this PR fixes**: fixes #997
Open question on issue #997.
```release-note
Removed the Git commit hash from the version string in non `canary` builds (#997)
```
=> Remove commit hash from Version string

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/templates/challenge-crd.yaml, contrib/charts/cert-manager/templates/order-crd.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac.yaml
The Helm crd-install annotation is not applied during upgrades, and has numerous issues with how it is handled during installation, upgrade and even uninstall (ref https://github.com/helm/helm/issues/4863)
Whilst a fix for this should hopefully be coming, for the time being we should work to mitigate these problems.
The new Order and Challenge resource types are not required during the helm chart installation phase, and as such, this PR removes the crd-install annotation from these CRDs to attempt to avoid issues in future.
The only two resource types that *are* required during installation are Certificates and Issuers. I have avoided removing the annotation from *ClusterIssuer* resources for now, as I am unsure exactly how this will behave when …
=> Remove crd-install annotation from Challenges and Orders

cmd/controller/BUILD.bazel, cmd/controller/app/BUILD.bazel, cmd/controller/app/controller.go, cmd/controller/app/options/BUILD.bazel, cmd/controller/app/options/options.go, cmd/controller/start.go, docs/generated/reference/output/reference/api-docs/index.html, pkg/apis/certmanager/v1alpha1/types_challenge.go, pkg/controller/acmechallenges/scheduler/BUILD.bazel, pkg/controller/acmechallenges/scheduler/controller.go, pkg/controller/acmechallenges/scheduler/sync.go, pkg/controller/acmechallenges/scheduler/sync_test.go, pkg/controller/acmechallenges/scheduler/util_test.go, pkg/controller/acmechallenges/sync.go, pkg/controller/acmechallenges/sync_test.go, test/e2e/suite/issuers/acme/certificate/dns01.go, test/unit/gen/challenge.go
Adds a basic ACME challenge scheduler.
As discussed with @kragniz, this does not perform particularly well in clusters with a large number of certificate resources.
We will implement some scale tests on this as a follow up, that verifies the performance so we have something to benchmark against for improvements.
**Which issue this PR fixes**: fixes #951, fixes #541 
Depends on #955 
```release-note
NONE
```
=> Add ACME challenge scheduler

docs/tutorials/acme/migrating-from-kube-lego.rst, pkg/controller/clusterissuers/controller.go, pkg/controller/ingress-shim/controller.go, pkg/controller/issuers/controller.go
Cherry pick of #981 #1017 on release-0.5.
#981: Update workqueue rate limiters on issuers and ingress-shim
#1017: Update kube-lego migration guide towards logs
=> Automated cherry pick of #981 #1017

cmd/controller/app/controller.go, cmd/controller/app/options/options.go, pkg/controller/context.go, pkg/controller/ingress-shim/controller.go, pkg/controller/ingress-shim/sync.go, pkg/controller/ingress-shim/sync_test.go
- adds a option command line (default to the current behavour) which allows the user to control the acme annotation used by the shim controller
- a current migration requires us to run multiple providers at the same
=> Configurable ACME Annotation

cmd/acmesolver/BUILD.bazel, cmd/controller/BUILD.bazel, cmd/webhook/BUILD.bazel, hack/def.bzl
fixes #1022
```release-note
NONE
```
=> Stamp docker images with current timestamp using Bazel

WORKSPACE, hack/BUILD.bazel, hack/bin/BUILD.bazel, hack/update-gofmt.sh, hack/verify-gofmt.sh, pkg/controller/acmeorders/sync_test.go, pkg/controller/ingress-shim/sync_test.go, pkg/util/version_test.go
This ensures we are using the correct code format for the Golang version we are using, instead of relying on goimports for this.
```release-note
NONE
```
=> Use go_sdk gofmt instead of goimports

pkg/controller/certificates/sync.go
Fixes a bug that caused an infinite loop when the Certificate and its target secret name are not named identically.
This bug only exists on the master branch of the project, so does not need to be backported.
**Which issue this PR fixes**: fixes #1038
```release-note
NONE
```
=> Fix invalid secret name used in certificates controller

test/unit/gen/BUILD.bazel, test/unit/gen/certificate.go, test/unit/gen/issuer.go
This is to support various other PRs when writing tests that use Certificate and Issuer resources.
```release-note
NONE
```
=> Add Certificate and Issuer unit gen functions

.gitlab-ci.yml
Brings the image used in-line with CI
```release-note
NONE
```
=> Bump CI image used on GitLab

cmd/webhook/BUILD.bazel, cmd/webhook/main.go, test/e2e/framework/helper/pod_start.go, test/fixtures/cert-manager-values.yaml
The webhook was disabled during e2e's when the new framework came in, as we needed to add an explicit wait for pods to become ready before continuing after provisioning an addon.
We now do this as part of the `chart` base addon, so this *should* pass.
This PR also fixes a panic on webhook startup.
```release-note
NONE
```
=> Re-enable webhook during e2e tests and fix panic on start

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/requirements.lock, contrib/charts/cert-manager/requirements.yaml, contrib/charts/cert-manager/values.yaml, contrib/charts/cert-manager/webhook/Chart.yaml, contrib/charts/cert-manager/webhook/values.yaml, contrib/manifests/cert-manager/with-rbac-webhook.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac-webhook.yaml, contrib/manifests/cert-manager/without-rbac.yaml
This PR bumps the Helm chart to use the canary image tags on the master branch.
We should have done this after release-0.5 was cut, but did not 😬 
```release-note
NONE
```
=> Bump Helm chart version to canary on master

.gitlab-ci.yml
Fixes building/pushing images on GitLab
```release-note
NONE
```
=> Fix GitLab build use of APP_VERSION

pkg/controller/acmechallenges/sync.go
Adds some extra event logging when a Challenge succeeds or fails
```release-note
NONE
```
=> Fire Events when challenges succeed or fail

pkg/acme/acme.go, pkg/issuer/acme/setup.go
This PR updates the ACME setup function to only verify the ACME account when the Ready condition is not currently True, or the Host part of the acme server URL does not match the registered acme account URL.
In future, we can look at storing a hash of either the private key or something else in order to re-check more frequently.
cc @jsha 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1013
```release-note
NONE
```
=> Skip re-checking ACME account status if Issuer is ready and URL hosts match

pkg/issuer/acme/setup.go
Following up #1032, this marks the issuer as invalid when parsing either of the URLs fails.
```release-note
NONE
```
=> Mark issuer as invalid when parsing URLs fails

pkg/acme/acme.go, pkg/issuer/acme/setup.go
Cherry pick of #1032 #1073 on release-0.5.
#1032: Skip re-checking ACME account status if Issuer is ready and
#1073: Mark issuer as invalid when parsing URLs fails
=> Automated cherry pick of #1032 #1073

pkg/controller/acmeorders/controller.go
We added a fake clock for testing, but never actually instantiated it in our constructor! 🤦‍♂️ 
```release-note
NONE
```
=> acmeorders: instantiate real clock

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/values.yaml, contrib/charts/cert-manager/webhook/Chart.yaml, contrib/charts/cert-manager/webhook/values.yaml, contrib/manifests/cert-manager/with-rbac-webhook.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac-webhook.yaml, contrib/manifests/cert-manager/without-rbac.yaml
Bump deployment manifests for v0.5.1.
```release-note
NONE
```
=> Bump manifests for v0.5.1

pkg/issuer/acme/http/ingress.go, pkg/issuer/acme/http/ingress_test.go
Previously, cert-manager could clean up paths that it is not meant to clean up during the ACME HTTP01 validation process.
This PR adds a unit test to verify how cert-manager behaves (which previously failed), and changes the cleanupIngress function to make this test pass 🎉 
**Which issue this PR fixes**: fixes #974
This may require backporting
```release-note
Fix bug when cleaning up ingress resources after performing ACME HTTP01 validation
```
=> Fix bug with ingress path cleanup

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/requirements.lock, contrib/charts/cert-manager/requirements.yaml, contrib/charts/cert-manager/templates/deployment.yaml, contrib/charts/cert-manager/values.yaml, contrib/charts/cert-manager/webhook/Chart.yaml, contrib/charts/cert-manager/webhook/templates/deployment.yaml, contrib/charts/cert-manager/webhook/values.yaml, contrib/manifests/cert-manager/with-rbac-webhook.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac-webhook.yaml, contrib/manifests/cert-manager/without-rbac.yaml
This PR modifies cert-manager chart to allow customization of deployment strategy. This way one can modify maxSurge and maxUnavailable values.
This could be needed when deploying cert-manager on each master node and setting affinities to forbid two pods on the same node. In this situation, default values of maxSurge (25% round up to next integer = 1) and maxUnavailable (25% round down to next integer = 0) block cert-manager update as the new surge pod can't be scheduled on a master node due to the anti affinities. Setting maxSurge to 0 and maxUnavailable to 1 would solve the problem.
=> chart: allow deployment strategy customization

pkg/controller/certificates/sync.go
#788 changed the certificate sync function in a way that meant we wouldn't always schedule a renewal for a certificate if cert-manager has been restarted since the first time the certificate was issued.
This PR updates the Certificate controller to always schedule a renewal if a certificate has been validated as up to date and valid.
ref #893 
```release-note
NONE
```
=> Schedule certificate renewal at the end of Certificate Sync function

pkg/controller/acmechallenges/controller.go, pkg/controller/acmechallenges/scheduler/controller.go, pkg/controller/acmechallenges/sync.go, pkg/controller/acmechallenges/sync_test.go, pkg/controller/acmeorders/controller.go, pkg/controller/certificates/controller.go, pkg/controller/clusterissuers/controller.go, pkg/controller/ingress-shim/controller.go, pkg/controller/issuers/controller.go, pkg/controller/util.go
Instead of returning an error and relying on the rate limiter to cause acmechallenges to be retries, this PR switches us to retry a fixed every 5s and not returns errors.
This also switches us to use the same rate limiter for all controllers (i.e. with the same base and max duration), and increases them all as well.
We may need to look into changing how we enqueue parent objects when 'owned' resources are enqueued, as currently we call AddRateLimited instead of Add, which will cause the back-off to be applied when it shouldn't be.
**Which issue this PR fixes**: fixes #1078
```release-note
NONE
```
=> Retry after a fixed 5s if self check is failing & adjust all controllers to use same rate limiter

cmd/controller/app/controller.go, cmd/controller/app/options/options.go, pkg/apis/certmanager/v1alpha1/types.go, pkg/controller/certificates/sync.go, pkg/controller/context.go
Sets the certificate as an owner of the secret
In this way, the secret will be garbage collected when a certificate is deleted.
```release-note
Add a flag which controls whether the certificate resource is configured as an owner of the secret where the effective TLS certificate is stored. This flag is set by default to 'on'. When this flag is enabled, the secret will be automatically removed when the certificate resource is deleted.
```
=> Set the certificate as an owner of the secret

docs/tutorials/quick-start/index.rst
Signed-off-by: Joe Heck <heckj@mac.com>
- fixes broken/scattered numbering in the new quick-start tutorial
```NONE
```
=> fix numbering of steps in quickstart

pkg/acme/util.go, pkg/apis/certmanager/v1alpha1/types_order.go, pkg/controller/acmeorders/sync.go
This updates the orders controller to handle 4xx errors by erroring and marking the order as failed.
This will trigger our back-off handling logic, as it will count as a failed order from cert-manager's point-of-view.
The new 'Errored' value is *not* a real ACME status, but is used internally to convey something has gone wrong with that particular order.
```release-note
NONE
```
=> Add Errored type and mark orders as errored when creating fails

pkg/controller/ingress-shim/BUILD.bazel, pkg/controller/ingress-shim/sync.go, pkg/controller/ingress-shim/sync_test.go, test/unit/gen/issuer.go
Reworks ingress-shim so we can print validation errors as Events instead of just logging to stdout.
This also stops us infinitely retrying processing on resources that are invalid.
```release-note
Validate ingresses marked for processing and report errors using the Events API on Ingress resources
```
=> Use Events API to report validation errors with ingress-shim

test/e2e/suite/issuers/ca/certificate.go, test/e2e/suite/issuers/selfsigned/certificate.go, test/e2e/suite/issuers/vault/certificate/approle.go
In e2e tests, check the certificate duration **after** verifying the certificate is issued
This should help cut down on some test flakes with the CA issuer I think.
```release-note
NONE
```
=> Fix potential race in e2e duration checking

pkg/apis/certmanager/v1alpha1/types_certificate.go, pkg/controller/acmeorders/checks.go, pkg/controller/acmeorders/controller.go, pkg/controller/acmeorders/sync.go, pkg/controller/certificates/checks.go, pkg/controller/certificates/controller.go, pkg/controller/certificates/sync.go, pkg/issuer/acme/issue.go, pkg/issuer/ca/issue.go, pkg/issuer/selfsigned/BUILD.bazel, pkg/issuer/selfsigned/issue.go, pkg/issuer/vault/BUILD.bazel, pkg/issuer/vault/issue.go, pkg/util/kube/pki.go, pkg/util/pki/csr.go
Updates how we use the Ready condition on certificates to be stricter, as well as uniform across all different issuer types.
This has required changing where most issuers log information about failed issuance to use Events instead of overloading the Ready condition
**Which issue this PR fixes**: fixes #742
I imagine a number of e2e tests are going to need updating to make this mergeable 😄 
```release-note
Use the Ready status condition in a consistent manner between issuer types
```
/cc @mikebryant @kragniz
=> Make Certificate Ready condition behaviour consistent between all issuer types

pkg/controller/acmechallenges/controller.go, pkg/controller/acmeorders/controller.go, pkg/controller/certificates/controller.go, pkg/controller/certificates/sync.go, pkg/controller/clusterissuers/controller.go, pkg/controller/clusterissuers/sync.go, pkg/controller/ingress-shim/controller.go, pkg/controller/issuers/controller.go, pkg/controller/issuers/sync.go, pkg/issuer/acme/issue_test.go, pkg/issuer/acme/setup.go, pkg/issuer/ca/issue_test.go, pkg/issuer/ca/setup.go, pkg/issuer/issuer.go, pkg/issuer/selfsigned/setup.go, pkg/issuer/vault/setup.go
We don't actually ever utilise the Requeue option, so I've removed it altogether.
This also updates the way items in the workqueue have Done and Forget called on them to avoid a potential race.
```release-note
NONE
```
=> Remove requeue option and fix small race in controllers

pkg/apis/certmanager/v1alpha1/const.go, pkg/controller/acmechallenges/sync.go, pkg/controller/acmechallenges/sync_test.go, pkg/controller/acmeorders/sync.go
Previously, we only cleaned up challenge resources if they succeeded. Any challenges that are deleted whilst they are failing/pending, will not be cleaned up.
This PR adds a finalizer to the challenge resources, and cleans them up upon deletion if they have not already been cleaned up.
```release-note
Add Challenge resource finalizer to handle cleanup
```
=> CleanUp ACME challenges after issuing and on delete using finalizer

pkg/controller/certificates/sync.go
We've recently changed what the Ready condition means to be a reflection of the actual x509 certificate status.
This should have been removed as part of that PR, as we now use events to log this kind of 'event' occurring.
```release-note
NONE
```
=> Don't update Certificate status condition upon issuance

pkg/controller/certificates/sync.go, pkg/issuer/acme/issue.go, pkg/issuer/acme/issue_test.go, pkg/issuer/ca/issue.go, pkg/issuer/ca/issue_test.go, pkg/issuer/issuer.go, pkg/issuer/selfsigned/issue.go, pkg/issuer/vault/issue.go
Replaces #962
Now, if the Issuer returns a non-nil IssueResponse, we will update the secret resource to contain the fields that were returned.
It also tidies up how we set metadata, and makes the metadata be set based on the contents of the certificate.
```release-note
NONE
```
=> Switch issuer.Issue to return a pointer and fix up setting secret fields

pkg/issuer/acme/dns/util/wait.go
This retries dns lookups using TCP if the UDP method times out.
fixes #896 
```release-note
Retry dns queries with TCP if UDP has an i/o timeout.
```
=> Retry dns queries with TCP if UDP has an i/o timeout

Gopkg.lock, Gopkg.toml
Bitbucket keeps failing/giving i/o timeouts, so this PR pins us to use a mirror of this one package that is hosted on Bitbucket.
This also means that you no longer need `hg` installed to verify/update dependencies 😄 
```release-note
NONE
```
=> Use github.com/munnerz/goautoneg mirror to resolve bitbucket issues

docs/generated/reference/output/reference/api-docs/index.html, pkg/apis/certmanager/v1alpha1/types_issuer.go, pkg/apis/certmanager/validation/issuer.go, pkg/controller/acmechallenges/sync.go, pkg/controller/acmechallenges/sync_test.go, pkg/issuer/acme/dns/acmedns/BUILD.bazel, pkg/issuer/acme/dns/acmedns/acmedns.go, pkg/issuer/acme/dns/akamai/akamai.go, pkg/issuer/acme/dns/akamai/akamai_test.go, pkg/issuer/acme/dns/azuredns/BUILD.bazel, pkg/issuer/acme/dns/azuredns/azuredns.go, pkg/issuer/acme/dns/azuredns/azuredns_test.go, pkg/issuer/acme/dns/clouddns/clouddns.go, pkg/issuer/acme/dns/clouddns/clouddns_test.go, pkg/issuer/acme/dns/cloudflare/cloudflare.go, pkg/issuer/acme/dns/cloudflare/cloudflare_test.go, pkg/issuer/acme/dns/digitalocean/digitalocean.go, pkg/issuer/acme/dns/digitalocean/digitalocean_test.go, pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/dns_test.go, pkg/issuer/acme/dns/rfc2136/rfc2136.go, pkg/issuer/acme/dns/rfc2136/rfc2136_test.go, pkg/issuer/acme/dns/route53/route53.go, pkg/issuer/acme/dns/route53/route53_test.go, pkg/issuer/acme/dns/util/dns.go, pkg/issuer/acme/http/http.go, pkg/issuer/acme/http/http_test.go
When the 'follow DNS CNAMES' functionality was added in v0.5, it broke DNS01 configurations for users who have a CNAME record configured for *.example.com as this CNAME matched `_acme-challenge.example.com` causing cert-manager to attempt to update the zone that this CNAME points to.
This PR adds a `followCNAME` option to the DNS01 provider's config to allow users to toggle this behaviour on a per DNS provider basis.
It also changes the default behaviour to *not* follow CNAMEs, which should fix issues that existing users have been seeing.
**Which issue this PR fixes**: fixes #1035, fixes #837
We *can* improve how this is handled in future to automatically detect which zone to update based on user's configuration. …
=> Add cnameStrategy field to configure how CNAME records should be handled during DNS01

hack/def.bzl
This fixes an issue where clusters with Pod Security Policy feature
enabled cannot start the containers.
Signed-off-by: Vasilis Remmas <vasremm@gmail.com>
Using the [restricted](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#example-policies) Pod Security Policy from the official Kubernetes documents, there is an error which prevents the pods from starting.
```
$ kubectl get events -n cert-manager
LAST SEEN   FIRST SEEN   COUNT   NAME                                             KIND         SUBOBJECT                       TYPE      REASON                  SOURCE                  MESSAGE
12s         12s          1       cert-manager-5c8649bb9d-r5lbh.156ef9c98a92b8f9   Pod                                          Normal    Scheduled …
```
=> Build images using user with id 1000

deploy/chart/Chart.yaml, deploy/chart/README.md, deploy/chart/requirements.lock, deploy/chart/requirements.yaml, deploy/chart/values.yaml, deploy/chart/webhook/Chart.yaml, deploy/chart/webhook/values.yaml, deploy/manifests/cert-manager.yaml, docs/getting-started/2-installing.rst
Bumps versions everywhere for pending v0.6.0-alpha.0 release
```release-note
NONE
```
=> Bump versions for 0.6.0-alpha.0

.gitlab-ci.yml
Our internal GitLab builders switched to use the Kubernetes executor instead of the Docker based executor, meaning we need to update the DOCKER_HOST env var to use tcp instead of a unix socket.
This should fix builds, and may also need cherry-picking to release-0.5 😄 
```release-note
NONE
```
/cc @kragniz
=> Add DOCKER_HOST env var to gitlab build

test/e2e/framework/addon/base/base.go, test/e2e/framework/addon/chart/BUILD.bazel, test/e2e/framework/addon/chart/addon.go, test/e2e/framework/helper/pod_start.go, test/e2e/framework/log/log.go
Previously Helm install output was always logged - this changes the e2e framework to only print helm output if the test case fails.
```release-note
NONE
```
=> Use GinkgoWriter to print Helm install output

pkg/issuer/acme/dns/util/wait_test.go
The nameservers for this host have changed to be `ns4.`, `ns5.` and `ns6.` - I have opted to remove the case altogether, as they may switch back in future (perhaps this is due to maintenance?) and we already check 2 other DNS names as part of this set of tests.
This resolves current issues when building/releasing v0.6.0-alpha.0 (and master)
Fixes `bazel test //pkg/issuer/acme/dns/util:go_default_test`
```release-note
NONE
```
=> Remove flakey unit test in dns utils package

test/e2e/charts/pebble/templates/deployment.yaml
liveness checks are a feature in kubernetes meant to restart hung
workloads. Since pebble stores account information in-memory, failing
a liveness check means that any running test will fail.
Because we're using pebble as part of a testsuite, we're protected
against hangs by the test just timing out.
On resource constrained environments (like my laptop), I've seen
the liveness check fail during startup, causing reboot loops and
timeouts. Since rebooting pebble mid-test will cause tests to fail
anyhow, we should probably disable this check.
Signed-off-by: Daniel Morsing <dmo@jetstack.io>
```
NONE
```
=> remove liveness checks on pebble deployments in e2e tests

pkg/controller/acmechallenges/sync.go, pkg/controller/acmeorders/sync.go
When an ACME server tells us that a challenge or an order is invalid, it's helpful to get some information on why that's the case. Populate the reason field with the error information so that these issues can be more easily debugged.
```
NONE
```
=> Add reason when an order/challenge gets marked invalid

deploy/manifests/00-crds.yaml, deploy/manifests/01-namespace.yaml, deploy/manifests/cert-manager.yaml, docs/getting-started/2-installing.rst, hack/update-deploy-gen.sh
Switches us to include the CRD & Namespace resources as part of the single all-in-one deployment manifest.
This simplifies installation for users that don't use Helm to a single command.
**Which issue this PR fixes**: fixes #1171
```release-note
NONE
```
=> Include CRD and Namespace resources in static deployment manifest file

deploy/manifests/00-crds.yaml, deploy/manifests/cert-manager.yaml
This gives far more useful kubectl output when running `kubectl get certificate,order,challenge` 😄 
~We can't currently make use of the Ready condition that we publish on the Certificate resource due to https://github.com/kubernetes/kubernetes/issues/67268 - once that merges, I think we should propagate the 'readiness' as a column too 😄~
```release-note
Print more useful information about Certificate, Order and Challenge resources when running `kubectl get`
```
=> Add additionalPrinterColumns fields to CustomResourceDefintions

pkg/controller/acmechallenges/controller.go, pkg/controller/acmechallenges/sync.go, pkg/controller/acmeorders/controller.go, pkg/issuer/acme/issue.go
1. Increases our maximum back-off time to 30m for both Order and Challenge resource types, when the control loop returns an error (e.g. an http client error)
2. Decreases the self-check frequency from every 5s to every 10s
3. Increases the amount of time between Order attempts if an order fails from 5m to 1h
In future I'd like to make (3) also exponentially back-off as-per the Let's Encrypt client guidelines. This will require us to record more information about how many failures have passed, so I am deferring this for now.
(1) should also help reduce the number of times we re-attempt calls to the ACME server. With a base of 5s and a max of 30m, we will quickly only be re-attempting client calls every 30 minutes in the event they are persistently …
=> Increase ACME control loop & order creation back-off

Makefile, WORKSPACE, hack/ci/lib/build_images.sh, test/e2e/charts/BUILD.bazel, test/e2e/charts/pebble/BUILD.bazel, test/e2e/charts/pebble/templates/configmap.yaml, test/e2e/charts/pebble/templates/deployment.yaml, test/e2e/charts/pebble/values.yaml, test/e2e/charts/vault/templates/vault-deployment.yaml, test/e2e/charts/vault/values.yaml, test/e2e/framework/addon/nginxingress/nginx.go, test/e2e/framework/config/tiller.go
This PR moves us away from using a custom built pebble image (built/pushed by hand) to instead use a copy of pebble that is built during the e2e test suite.
This should also make it easier for us to keep up to date with new pebble revisions.
This PR also bumps the version of pebble we use during e2e tests to the current latest.
I've also moved image pulling for all e2e test dependencies into Bazel, which helps reduce flakes & timeouts when running the tests on slow connections.
```release-note
NONE
```
=> Use pebble built by bazel & pre-pull images during e2e tests

test/fixtures/cert-manager-values.yaml
We are occasionally seeing test failures with the CA Issuer, and whilst inspecting the logs to determine the problem, I've noticed that the certificates controller can take a long time during the 'issuance' phase.
I have a hunch this *could* be caused simply by lack of CPU resources to complete this in a timely manner, based on the log messages I can see (it's taking ~30-45s to run the `issue` function and in that time, the test has already timed out)
```release-note
NONE
```
=> Increase resource requests and limits for cert-manager during e2e tests

pkg/controller/acmeorders/sync.go
Previously we deleted all Challenge resources for an Order once the Order enters any 'final' state (including failed).
This makes it harder for users to debug order failures once the order transitions to the invalid state.
@goblain brought this up on slack: https://kubernetes.slack.com/archives/C4NV3DWUC/p1547213252391000
> any idea how can I force cert-manager to keep challenge response open for debugging access to it ?
```release-note
Retain Challenge resources when an Order has entered a failed state to make debugging easier
```
/area provider-acme
=> Retain Challenge resources for debugging if an Order enters an invalid state

deploy/chart/Chart.yaml, deploy/chart/README.md, deploy/chart/templates/serviceaccount.yaml, deploy/chart/values.yaml, deploy/manifests/cert-manager.yaml
**What this PR does / why we need it:**
Allows specifying a imagePullSecrets when the image is stored in private registry
Inspiration from: https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml#L30-L34
```release-note
NONE
```
=> [chart] Adding imagePullSecrets to Service Account

deploy/chart/Chart.yaml, deploy/chart/README.md, deploy/chart/requirements.lock, deploy/chart/requirements.yaml, deploy/chart/templates/deployment.yaml, deploy/chart/values.yaml, deploy/chart/webhook/Chart.yaml, deploy/chart/webhook/templates/deployment.yaml, deploy/manifests/cert-manager.yaml
Signed-off-by: Artem Kajalainen <artem.kajalainen@gofore.com>
this PR adds priorityClassName option to helm chart, allowing user to specify priorityClassName for cert-manager pod.
```release-note
Add global.priorityClassName option to Helm chart
```
=> feat(helm chart): add priorityClassName option

test/e2e/framework/addon/globals.go
This fixes the issue of global addons not being cleaned up after tests
```
NONE
```
=> only init globals data once

pkg/util/kube/pki.go
Previously, if the `secretName` specified on a Certificate references a secret that already exists but does not have the `tls.key` field set, we would refuse to attempt to issue a certificate.
By wrapping the error we return here with InvalidData, the ACME issuer will generate a new private key and 'insert' values into the existing Secret resource.
This issue was reported by @swade1987 😄
```release-note
Fix issuing a certificate into a pre-existing secret resource
```
=> Fix issuing a certificate into a pre-existing secret

docs/reference/challenges.rst, docs/reference/index.rst, docs/reference/orders.rst
Adds reference docs section for both order and challenge resource types.
**Which issue this PR fixes**: fixes #952
```release-note
NONE
```
/area provider-acme
=> Add reference docs for Order and Challenge resources

pkg/issuer/acme/http/http.go
Disable TLS verification when self-checking
Fixes #949
There's no test for this right now, since pebble doesn't implement the right redirect behavior and any E2E test would fail.
```
Fix self-check behavior with HTTP->HTTPS redirects
```
=> Disable TLS verification when self-checking

docs/tutorials/quick-start/index.rst
Updates the nginx acme quickstart guide with details on the new Order and Challenge resource types, which can be used to track the progress of a certificate being issued.
```release-note
NONE
```
/cc @heckj
=> Update nginx acme quickstart guide with details on Orders and Challenges

pkg/acme/acme.go, third_party/crypto/acme/acme.go
Whilst implementing #1226, I noticed that we are making multiple calls to the `new-acct` endpoint whenever a call is made to the ACME server and the account URI is not cached.
Because we construct a new ACME client on each invocation of a 'sync' loop, we will be querying the `new-acct` endpoint each time a 'sync' begins of an Order or Challenge resource.
This is not intended, and is a consequence of this code in the ACME client being called on every HTTP request: https://github.com/jetstack/cert-manager/blob/3767a6df23fc38a4a1c4fceba672e35cdd667044/third_party/crypto/acme/acme.go#L613
In order to get around this, this PR does two things:
1) Create a `SetAccountURL` method on the ACME client which allows us to set the internally cached account URL. …
=> Use cached ACME account URL when constructing ACME client

deploy/chart/Chart.yaml, deploy/chart/README.md, deploy/chart/requirements.lock, deploy/chart/requirements.yaml, deploy/chart/values.yaml, deploy/chart/webhook/Chart.yaml, deploy/chart/webhook/values.yaml, deploy/manifests/cert-manager.yaml
Bump the manifest/chart/doc versions for a new v0.6.0 beta release. This should hopefully be the last change in this release!
Once this has merged and release-0.6 has been fast forwarded, we can begin accepting patches for v0.7 into master.
Any new changes will need to be cherry picked into release-0.6.
```release-note
NONE
```
=> Bump Helm chart version for beta.0

pkg/controller/certificates/sync.go
Check to make sure the map is non-nil before writing data into it
**Which issue this PR fixes**: fixes #1236
```release-note
NONE
```
/kind bug
=> Fix nil map panic when writing to an empty existing Secret

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/values.yaml, deploy/manifests/cert-manager.yaml
Adds the ability to run cert-manager deployment pods with a non-root user which enables cert manager to work with PodSecurityPolicy defaults.
```release-note
Added securityContext to cert-manager deployment pods in helm chart
```
=> Added securityContext to cert-manager deployment pods in helm chart

test/chart/.testenv
Since moving the chart around a few times, our chart bump check has not been running properly. This should fix it 😄 
```release-note
NONE
```
=> Fix testenv for chart testing

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/requirements.yaml, deploy/charts/cert-manager/values.yaml, deploy/charts/cert-manager/webhook/Chart.yaml, deploy/charts/cert-manager/webhook/templates/ca-sync.yaml, deploy/manifests/cert-manager.yaml, docs/getting-started/2-installing.rst, docs/getting-started/3-configuring-first-issuer.rst, test/chart/lib/chartlib.sh
The default value for this field is 6. In some cases, this job can fail due to e.g. missing the 'disable-validation' annotation on the cert-manager Namespace.
Increasing this limit should help these cases, and this PR also adds some extra notes informing users to 'verify' their installations.
```release-note
NONE
```
=> Set CA sync backoff limit & add verifying installation docs

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/requirements.yaml, deploy/charts/cert-manager/values.yaml, deploy/charts/cert-manager/webhook/Chart.yaml, deploy/charts/cert-manager/webhook/values.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml
Bump version strings for the v0.6.0 release! 🎉 😄
This will be the final PR for v0.6 - after this is merged and `release-0.6` has been fast forwarded, master will be re-opened for PRs for the v0.7 release!
```release-note
NONE
```
=> Bump version strings for v0.6.0

WORKSPACE
More information on the contents of the 2 patch releases: https://golang.org/doc/devel/release.html
```release-note
Build using go 1.11.4
```
=> Bump go to 1.11.4

deploy/charts/cert-manager/webhook/Chart.yaml
Upstream helm/charts now requires additional fields be set on *all* Helm charts.
```release-note
NONE
```
=> Update Chart.yaml in webhook

pkg/controller/acmechallenges/sync.go, pkg/controller/acmechallenges/sync_test.go, pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/http/http.go, pkg/issuer/acme/http/http_test.go
This PR surfaces self-check errors in the challenge resource, making it more obvious what is holding up issuance of a certificate.
fixes #1208
This PR works by changing the `Check` method on the `solver` interface. Instead of having a (retry, error) tuple, we eliminate errors from the various checkers, making it so that the only type of error returned is a retryable one. Because of this change, the PR looks like it changes a lot more things than it actually does. If a change seems weird, I suggest looking through the commits one-by-one
```
More observable errors when waiting for self-checks to propagate
```
=> Surface self-check errors in challenge resource

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/README.md, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml
Helps users when deploying into a namespace that already exists
**Which issue this PR fixes**: fixes https://github.com/helm/charts/issues/10856
```release-note
NONE
```
=> Add note about disabling validation on existing namespaces to Helm chart

pkg/issuer/acme/dns/akamai/akamai.go, pkg/issuer/acme/dns/akamai/akamai_test.go, pkg/issuer/acme/dns/azuredns/azuredns.go, pkg/issuer/acme/dns/clouddns/clouddns.go, pkg/issuer/acme/dns/cloudflare/cloudflare.go, pkg/issuer/acme/dns/route53/route53.go
This fixes issues with split horizon configurations where cert-manager would not respect the `--dns01-recursive-nameservers` flag when determining which zone to update for a given fqdn.
This could cause errors like:
```
Failed to determine Route 53 hosted zone ID: Zone something.example.com. not found in Route 53 for domain _acme-challenge.abc.something.com.
```
```release-note
Fix bug where --dns01-recursive-nameservers flag was not respected when looking up the zone to update for a DNS01 challenge
```
/kind bug
=> Respect recursive nameservers flag when finding zone for fqdn

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/requirements.yaml, deploy/charts/cert-manager/webhook/Chart.yaml, deploy/charts/cert-manager/webhook/templates/pki.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml
In v0.6.0, the webhook component was installed using certificates that don't explicitly set a `duration`. This means that the new default of `90d` will be used.
We haven't currently tested auto-rotation of certificates in the webhook component, and we may need to signal with a SIGHUP or similar to make it reload the cert (or just watch the file on disk).
This PR increases the lifetime of these component certificates, which should at least help mitigate the issue until v0.7 is released when we have a more complete patch ready.
```release-note
Increase x509 certificate duration from 90d to 1y for webhook component certificates
```
/kind bug
/cc @DanielMorsing 
/shrug
=> Use long-lived certificates for the webhook component

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/templates/rbac.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml
For the cert-manager to be able to set ownerReferences, the RBAC rules
for finalizers need to be in place.
Fixes #1257
Signed-off-by: Simon Rüegg <simon.ruegg@vshn.ch>
Fixes #1257
Fixes #1257
```release-note
NONE
```
=> Add RBAC rules for finalizers

pkg/util/pki/generate.go, pkg/util/pki/parse.go, pkg/util/pki/parse_test.go
This PR enables the key parser for the ca issuer to use PKCS#8 encoded private keys.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: No Issue created
The changes in the file `generate.go` is only required for the tests.
```release-note
Allow to use PKCS#8 encoded private keys in CA issuers.
```
=> Adds key parser for PKCS#8 encoded private keys.

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/requirements.yaml, deploy/charts/cert-manager/webhook/Chart.yaml, deploy/charts/cert-manager/webhook/templates/pki.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml
Cherry pick of #1294 on release-0.6.
#1294: Fix 'selfsigned' key on webhook issuer
=> Automated cherry pick of #1294

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/requirements.yaml, deploy/charts/cert-manager/webhook/Chart.yaml, deploy/charts/cert-manager/webhook/templates/pki.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml
This was a typo in the webhook deployment manifests that was accepted by kubernetes <1.13.
Discovered whilst working on #1268 
```release-note
Fix typo in SelfSigned Issuer in webhook deployment manifests
```
/kind bug
/area deploy
=> Fix 'selfsigned' key on webhook issuer

WORKSPACE
Bumps golang version to 1.11.5
```release-note
Bump Go version to 1.11.5
```
=> Build using Go 1.11.5

pkg/controller/certificates/sync.go
This should avoid weird conditions that could allow a certificate to be issued multiple times.
```release-note
Use secretLister in updateSecret
```
=> Use secretLister in updateSecret

.gitlab-ci.yml, hack/release.sh
Adds a script `hack/release.sh` that can be used to push tagged images for cert-manager releases.
This allows us to move our release process over to Prow from the internal-only gitlab setup we have now.
I've only enabled this for the canary releases for now, although the script also supports pushing tags too.
I've also changed our release process so instead of pushing `master-{pipeline-id}` tags (where pipeline-id is only visible on gitlab), we now use the git short ref of the commit being pushed.
```release-note
NONE
```
Requires https://github.com/jetstack/testing/pull/160
/hold
/area deploy
/kind cleanup
=> Add hack/release.sh script for publishing releases

docs/redirects
Signed-off-by: Mike Eves <meves23@gmail.com>
**What this PR does / why we need it**: Fixes broken redirect of https://docs.cert-manager.io/en/latest/reference/ingress-shim.html (Link appears in search results of `shim`)
```release-note
NONE
```
=> Fix redirect of ingress-shim.html page

docs/tasks/acme/configuring-dns01/index.rst, docs/tasks/acme/configuring-dns01/rfc2136.rst
Signed-off-by: Mike Eves <meves23@gmail.com>
Re-adds missing RFC2136 DNS provider docs
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1251
```release-note
```
=> Recover missing RFC2136 docs

cmd/controller/app/options/options.go
Increase default acmesolver cpu resource limit to 100m to prevent an issue that could cause certain docker versions to hang when creating pods.
**Which issue this PR fixes**: fixes #1324
```release-note
Increase acmesolver default cpu resource limit to 100m
```
=> Increase acmesolver default cpu resource limit to 100m

README.md, deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/templates/NOTES.txt, deploy/manifests/README.md, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml, docs/generated/reference/generate/static_includes/_certmanager.md, docs/generated/reference/output/reference/api-docs/index.html, docs/tasks/acme/configuring-http01.rst, docs/tasks/issuing-certificates/index.rst, docs/tutorials/acme/quick-start/index.rst
Now that we can get free TLS certs with readthedocs, this is now easy to do... (yes, I appreciate the irony that cert-manager isn't used for its own docs...)
```release-note
NONE
```
=> Update docs links to docs.cert-manager.io

docs/devel/develop-with-minikube.rst
minikube enables RBAC by default as of v0.26.0; hence,
it is not needed to add the extra-config override
See https://github.com/kubernetes-incubator/service-catalog/pull/2365/files/9b5f7c1ebd632b040482013a42c662bd245802e1
Signed-off-by: Shawn Zhou <shawnzhou00@yahoo.com>
It helps users getting minikube running correctly for testing cert-manager builds.
```release-note
NONE
```
=> update minikube startup instruction

docs/getting-started/install.rst
**What this PR does / why we need it**: updates docs to remove suggestion to apply `00-crds.yaml` before applying `cert-manager.yaml`, as the latter now includes the CRDs (since #1193).
```release-note
NONE
```
=> docs: no need to apply 00-crds.yaml when installing with regular manifests

pkg/acme/acme.go, pkg/acme/client/fake.go, pkg/acme/client/interfaces.go, pkg/acme/client/middleware/logger.go, pkg/controller/acmechallenges/BUILD.bazel, pkg/controller/acmechallenges/sync.go, pkg/issuer/acme/dns/util/wait.go, pkg/issuer/acme/dns/util/wait_test.go, third_party/crypto/acme/acme.go
This PR implements a rudimentary CAA check for ACME clients, making sure that users don't run into LE rate limits with improperly set up DNS
fixes #211
```
Check for CAA records during ACME issuance
```
=> Extend ACME self check to check CAA records

Gopkg.lock, test/e2e/framework/BUILD.bazel, test/e2e/framework/matcher/BUILD.bazel, test/e2e/framework/matcher/have_condition_matcher.go, test/e2e/suite/issuers/acme/certificate/BUILD.bazel, test/e2e/suite/issuers/acme/certificate/http01.go
Tests out creating a custom Gomega matcher for checking for conditions on resources during e2e tests.
Depending on how this goes, we can look at creating more custom matchers to test different functionality & cleanup the e2e test framework codebase.
```release-note
NONE
```
=> Create HaveCondition gomega matcher and use it in e2e test

BUILD.bazel, Makefile, WORKSPACE, cmd/acmesolver/BUILD.bazel, cmd/controller/BUILD.bazel, cmd/webhook/BUILD.bazel, hack/ci/lib/build_images.sh, hack/ci/lib/lib.sh, hack/def.bzl, hack/release.sh, test/e2e/BUILD.bazel, test/e2e/charts/pebble/BUILD.bazel
This PR adds support for building arm32 and arm64 images for cert-manager.
We'll need to set up the new quay.io repositories for the new architectures. In future, when quay.io supports manifest list 2.2, we'll be able to push proper multiarch images.
**Which issue this PR fixes**: fixes #608 
```release-note
Publish arm32 and arm64 images for all cert-manager components
```
=> Add arm32 and arm64 bazel image targets

test/e2e/charts/BUILD.bazel
Adds a manual tag to e2e image targets to reduce the number of things that need pulling when running `bazel build //...`
```release-note
NONE
```
=> Add manual tag to charts image targets

pkg/controller/BUILD.bazel, pkg/controller/certificates/controller.go, pkg/controller/certificates/sync.go, pkg/controller/helper_test.go, pkg/controller/ingress-shim/BUILD.bazel, pkg/controller/ingress-shim/controller.go, pkg/controller/ingress-shim/sync.go, pkg/controller/ingress-shim/sync_test.go
This removes all bespoke implementations of GetGenericIssuer aside from the new one that's attached to the controller context's Helper. This should make refactors in future easier, and avoid any weird behaviour as a result of differing implementations 😄 
I had to refactor the unit test to not use the `test.Builder` structure, as it introduced a circular dependency.
```release-note
NONE
```
=> Use Helper structure to call GetGenericIssuer everywhere

WORKSPACE, deploy/manifests/00-crds.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml, docs/generated/reference/output/reference/api-docs/index.html, hack/BUILD.bazel, hack/bin/BUILD.bazel, hack/update-crds.sh, hack/verify-crds.sh, pkg/apis/certmanager/v1alpha1/types.go, pkg/apis/certmanager/v1alpha1/types_certificate.go, pkg/apis/certmanager/v1alpha1/types_challenge.go, pkg/apis/certmanager/v1alpha1/types_issuer.go, pkg/apis/certmanager/v1alpha1/types_order.go
The CRD generator from kubebuilder has been extracted out into its own distinct tool, meaning we can easily re-use it in our own non-kubebuilder project.
This PR means that our CRD resources are now generated directly from our API types, including an openapi validation schema 😄 
**Which issue this PR fixes**: fixes #
~This is WIP as there are likely going to be some test fails due to misuse of field annotations such as `// + optional`~
```release-note
Add validation schema to CRD resources
```
=> Generate CRDs using controller-tools, including validation schema

cmd/webhook/BUILD.bazel, cmd/webhook/main.go
This watches the certificate file on the webhook, restarting whenever a certificate has changed. This makes sure that we're always going to have a valid certificate
fixes #1340
```
NONE
```
=> watch TLS cert file

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/requirements.yaml, deploy/charts/cert-manager/templates/rbac.yaml, deploy/charts/cert-manager/values.yaml, deploy/charts/cert-manager/webhook/Chart.yaml, deploy/charts/cert-manager/webhook/templates/ca-sync.yaml, deploy/charts/cert-manager/webhook/templates/rbac.yaml, deploy/charts/cert-manager/webhook/values.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml
Webhook sub-chart does not currently allow for turning off rbac creation like the parent chart.
fixes #1283
Breaking change that requires the user to switch to `global.rbac.create: false` if they wish to disable rbac resource creation.
rbac.create: false
webhook.rbac.create: false
```release-note
Breaking Change: Added global.rbac.create to main chart and webhook.  Replaces old rbac.create.
```
=> [chart] Adding rbac creation flag to webhook

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/requirements.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/webhook/Chart.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml
Since v0.6.0 cert-manager can expose metrics, this PR permits to use these with helm chart.
fixes #1301 
```release-note
NONE
```
=> [chart] Add possibility to scrape metrics with prometheus

pkg/issuer/acme/http/http.go, pkg/issuer/acme/http/pod.go, test/e2e/suite/issuers/acme/certificate/BUILD.bazel, test/e2e/suite/issuers/acme/certificate/http01.go
While solver pods are fairly simple and shouldn't die, they can be terminated for a variety of reasons, like draining nodes or overzealous sysadmins. Recreate the solver pod if it goes away while we're waiting for the self-check to pass.
fixes #1311 
```
More robust handling of solver pods
```
=> Recreate dead solver pods during self-check

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/requirements.yaml, deploy/charts/cert-manager/values.yaml, deploy/charts/cert-manager/webhook/Chart.yaml, deploy/charts/cert-manager/webhook/values.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml, docs/getting-started/install.rst, docs/getting-started/webhook.rst, docs/tasks/issuing-certificates/index.rst, docs/tasks/upgrading/index.rst, docs/tasks/upgrading/upgrading-0.5-0.6.rst, docs/tutorials/acme/quick-start/index.rst
Bumps all our manifests and files for the upcoming release-0.7. This should have probably been done nearer the cycle, but we now know for next time :smile: 
```release-note
NONE
```
=> Bump files for v0.7.0-alpha.0

hack/release.sh
Fixes the release.sh script 🤦‍♂️ 
```release-note
NONE
```
=> Negate SKIP_CHART in comparison

WORKSPACE
This fixes an issue that caused the `//:images.push` target to not work.
```release-note
NONE
```
=> Bump rules_docker version

hack/release.sh
This fixes an issue with the release script on environments that haven't run `helm init` before.
```release-note
NONE
```
=> Run helm init -c in release.sh

test/e2e/framework/addon/chart/addon.go
When cert-manager is deploying and the controller is in a crash loop, the webhook sometimes does not start which means errors get returned when retrieving the pod logs so the log messages don't get printed.
This PR ignores errors when retrieving pod logs, in favour of returning as many logs as can be retrieved.
```release-note
NONE
```
=> Don't return errors if retrieving pod logs fails

docs/getting-started/install.rst
Added BKPR (https://github.com/bitnami/kube-prod-runtime/) as an alternative way to deploy cert-manager to the documentation.
BKPR is a curated set of the services you would need to deploy on top of your Kubernetes cluster to enable logging, monitoring, certificate management, automatic discovery of Kubernetes resources via public DNS servers and other common infrastructure needs.
BKPR can be easily deployed with the `kubeprod install` command, and that will deploy `cert-manager` for certificate management. 
Fixes #1401 
```release-note
Added kubeprod as an alternative way to deploy cert-manager to the documentation
```
=> Added kubeprod as an alternative way to deploy cert-manager to the documentation

test/e2e/suite/serving/cainjector.go
These were previously set to 2s (the default), which is a bit too low when we run ~20 tests at once I think.
```release-note
NONE
```
=> Increase timeouts for cainjector e2e tests

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/README.md, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml, docs/getting-started/install.rst, docs/tasks/upgrading/index.rst
Update the installation instructions to refer to the new charts.jetstack.io repo
```release-note
NONE
```
/milestone v0.7
=> Update references to Helm chart repo with charts.jetstack.io

docs/devel/dns01-providers.rst
Since we're changing how we're handling DNS01 providers, update the docs to refer to our plans
```
NONE
```
=> update DNS01 contrib docs

WORKSPACE
Newer versions of bazel error out of our node dependencies. Update them to fix this build issue
```
NONE
```
=> update bazel node deps

pkg/issuer/acme/dns/azuredns/azuredns.go
Signed-off-by: Aditya Sundaramurthy <aditya.sundaramurthy@gmail.com>
**What this PR does / why we need it**: Fixes https://github.com/jetstack/cert-manager/issues/1459 . Uses inferred zone name from the Azure DNS API over the configured `hostedZoneName` param in the ClusterIssuer
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1459 
**Special notes for your reviewer**: Overrides `hostedZoneName` config param.
```release-note
Removes need for `hostedZoneName` to be specified. Uses discovered DNS zone name instead.
```
=> [Azure DNS] Fixes trimming of zone inferred via zone discovery 

docs/tutorials/acme/quick-start/index.rst
Updated the quickstart documentation to use the new jetstack helm repo.
To fix the documentation so people don't end up pulling out their hair wondering why the stable/cert-manager chart is only pulling version 0.6.2 of the code but the CRD's are from version 0.7.0.
```release-note
fixing the quickstart documentation to use the new helm chart repo charts.jetstack.io
```
=> fix(docs): updated quickstart docs

cmd/controller/app/controller.go
This makes sure all cert-manager instances have a metrics endpoint.
Fixes #1352.
```release-note
Run metrics server on cert-manager instances that have not been elected as leader
```
=> Expose metrics server on non-leader instances

pkg/issuer/acme/http/BUILD.bazel, pkg/issuer/acme/http/http.go, pkg/issuer/acme/http/ingress.go, pkg/issuer/acme/http/ingress_test.go, pkg/issuer/acme/http/pod.go, pkg/issuer/acme/http/pod_test.go, pkg/issuer/acme/http/service.go, pkg/issuer/acme/http/service_test.go
Adds additional debug logging and switches the HTTP01 solver to use the logr interface
```release-note
Improve logging in ACME HTTP01 solver
```
=> Use logr in ACME HTTP01 solver

cmd/controller/app/options/options.go
Signed-off-by: Lennart Jern <lennart.jern@gmail.com>
**What this PR does / why we need it**: This detects the architecture and sets the acmesolver container image based on that.
**Which issue this PR fixes**: fixes #1470
I'm not sure if it's OK to use `quay.io/jetstack/cert-manager-acmesolver-amd64` instead of `quay.io/jetstack/cert-manager-acmesolver` (the case now) for the normal `amd64` arch. It makes sense in the way that all archs are treated equally but it may need changes in other places that I'm not aware of (build and push jobs?).
Please bear with me, this is my first pull request to cert-manager :smile: 
```release-note
Set default acmesolver image based on arch
```
=> Set default acmesolver image based on arch

pkg/issuer/acme/http/ingress.go
Whitelisting 0.0.0.0/0 means people who use whitelisting won't have problems when using acme over ipv4, but guarantees that people will have problems when using acme over ipv6 (see nginx rule below). I've added ::0/0 to the whitelist, which seems to solve the problem I've been having today.
```
geo $the_real_ip $deny_QevWrNHVjGFiQYHjfMrOsfzrjRZiYJTr {
default 1;
0.0.0.0/0 0;
::/0 0;
}
```
Without ::0/0 in this filter, IPv6 acme requests are blocked with error 403.
```
if ($deny_QevWrNHVjGFiQYHjfMrOsfzrjRZiYJTr) {
return 403;
}
```
You can tell this is happening when the nginx logs show the pattern of returning 200 for a challenge requests coming from one of your cluster nodes, followed by a 403 response to a request with the Let's Encrypt user agent …
=> also whitelist ipv6

pkg/issuer/acme/dns/util/wait.go
This fixes a typo (conflation of "it's/its") in a log message.
```release-note
NONE
```
=> Fix "it's" typo in log message

hack/def.bzl
**What this PR does / why we need it**: Updates bazel syntax to work with newest version.
In bazel 0.24.0 the flag `--incompatible_disallow_dict_plus` is enabled by default, which means that cert-manager won't build without this change.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: I could not find an issue for this.
You can find the flag mentioned above in the [release notes](https://github.com/bazelbuild/bazel/releases). I'm not sure if the "dict plus" is used some place else, but with this change I was able to `make build` successfully.
```release-note
NONE
```
=> bazel: use update instead of + for dict

pkg/controller/certificates/sync.go, pkg/controller/certificates/sync_test.go, pkg/controller/ingress-shim/sync.go
**What this PR does / why we need it**: This makes cert-manager re-issue certificates if the issuer changes.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #813 
I noted a todo [here](https://github.com/jetstack/cert-manager/blob/master/pkg/controller/certificates/sync.go#L387) that is a bit related and may affect how this should be done.
```release-note
Update certificate if issuer changes
```
=> Update certificate if issuer changes

pkg/issuer/acme/dns/util/wait.go
For certain setups, DNS servers would return SERVFAIL on CAA queries. Normally, this would be a validation error for Let's Encrypt, but we might be talking to an internal DNS server. Go to the authoritative server to make sure.
fixes #1518
```
More robust CAA checks
```
=> use authoritative nameservers for CAA checks

WORKSPACE
Fixes issues building with Bazel 0.24.1
```release-note
NONE
```
=> Bump repo-infra dependency

docs/tasks/issuers/setup-venafi.rst
**What this PR does / why we need it**: username field in credentials secret is 'username' not 'user'
```release-note
None
```
=> Fixing username field in credentials secret

WORKSPACE, hack/update-bazel.sh
Bump workspace dependencies in prep for newer go version & remove unneeded nodejs dependency
```release-note
NONE
```
=> Bump WORKSPACE dependencies

WORKSPACE
Bump to use Go 1.12
```release-note
Bump to use Go 1.12
```
/area deploy
=> Bump to Go 1.12

cmd/controller/app/controller.go, pkg/controller/BUILD.bazel, pkg/controller/acmechallenges/controller.go, pkg/controller/acmechallenges/util_test.go, pkg/controller/acmeorders/controller.go, pkg/controller/certificates/controller.go, pkg/controller/clusterissuers/controller.go, pkg/controller/context.go, pkg/controller/ingress-shim/controller.go, pkg/controller/issuers/controller.go, pkg/controller/register.go
Part of #1443.
This updates the controller initialisation code to allow it to return errors.
I've also updated the controller context to contain a reference to the RESTClient, as this will be used as part of the existing DNS01 webhook types in future.
```release-note
NONE
```
=> Allow controller constructor to return errors and pass RESTClient on context

pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/util/dns.go, pkg/issuer/acme/dns/util/wait.go
We need to export dnsQuery so that it can be used as part of the soon-to-come DNS01 test suite.
I've also refactored the DNS01Record method to be DNS01LookupFQDN, which better reflects what it does. In the process I also removed some redundant arguments and returned fields.
```release-note
NONE
```
/cc @kragniz
=> Export dnsQuery function & refactor DNS01Record function

pkg/issuer/acme/dns/rfc2136/BUILD.bazel, pkg/issuer/acme/dns/rfc2136/rfc2136_test.go
Improves the RFC2136 DNS provider's test dns server to actually track the values of records.
This will make it possible for the RFC2136 provider to pass the conformance test suite in a follow-on PR 😄 
```release-note
NONE
```
/cc @kragniz
=> Improve RFC2136 test DNS server

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/cainjector/Chart.yaml, deploy/charts/cert-manager/cainjector/values.yaml, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/requirements.yaml, deploy/charts/cert-manager/values.yaml, deploy/charts/cert-manager/webhook/Chart.yaml, deploy/charts/cert-manager/webhook/values.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml, docs/getting-started/install.rst
Bump manifest versions for v0.7.1
```release-note
NONE
```
/cc @Evesy
=> Bump manifests for v0.7.1

deploy/manifests/00-crds.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml, pkg/apis/certmanager/v1alpha1/types_certificate.go, pkg/apis/certmanager/v1alpha1/types_issuer.go
This is the standard in upstream k8s, and prevents errors
when malformed 'condition' stanzas are included in resources.
**Which issue this PR fixes**: fixes #1509 
I'm also intending to cherry pick this into v0.7
```release-note
Fix upgrade bug where lastTransitionTime may be set to nil, rendering cert-manager inoperable without manual intervention
```
=> Add omitempty to fields on conditions

pkg/issuer/acme/http/http.go, pkg/issuer/acme/http/pod.go
Signed-off-by: Christian Hüning <christian.huening@figo.io>
Adds labels to the solver pod in order to allow for customer service manifests to pick it up
fixes #1529 
```release-note
- add static label for solver identification to allow usage of custom service
```
=> Added static label for solver identification. Solves #1529

pkg/issuer/acme/dns/rfc2136/BUILD.bazel, pkg/issuer/acme/dns/rfc2136/provider_test.go, pkg/issuer/acme/dns/rfc2136/rfc2136_test.go, test/acme/dns/BUILD.bazel, test/acme/dns/server/BUILD.bazel, test/acme/dns/server/doc.go, test/acme/dns/server/rfc2136.go, test/acme/dns/server/server.go
Refactors the test DNS server code into a standalone library which can be used during e2e tests
```release-note
NONE
```
/cc @kragniz
=> Refactor test DNS server into separate package

pkg/acme/webhook/apiserver/BUILD.bazel, pkg/acme/webhook/apiserver/apiserver.go
This area of the codebase is currently awaiting tests, and this issue is only caught at runtime.
The ChallengePayload API type is now part of a dedicated API group, but the apiserver scheme was not updated to reflect this.
```release-note
NONE
```
=> Update webhook apiserver Scheme to add webhook API types

pkg/acme/webhook/apiserver/apiserver.go, pkg/acme/webhook/cmd/server/BUILD.bazel, pkg/acme/webhook/cmd/server/start.go
More runtime errors with the webhook apiserver... We should have e2e tests for this though soon 😄 
```release-note
NONE
```
=> Fix runtime errors with webhook apiserver library

pkg/controller/acmechallenges/sync.go
Previously the error that causes a challenge to fail to present or clean up was not clearly surfaced to users.
This PR changes that to store the error as the `status.reason` field, as well as log it as an Event. Because an error is actually being returned, we should not enter a 'tight loop' so we should not flood the apiserver with Events 😄 
```release-note
Improve error handling when ACME challenges fail to Present or CleanUp
```
=> Set Reason field on ACME challenges during Present/CleanUp

Makefile, test/e2e/e2e.go, test/e2e/framework/config/addons.go, test/e2e/framework/framework.go, test/e2e/framework/helper/certificates.go
Exposes more e2e test framework variables via the Makefile. This is useful for local development.
```release-note
NONE
```
=> Expose ginkgo.focus and skip-globals flags in e2e_test

hack/ci/lib/build_images.sh, test/e2e/BUILD.bazel, test/e2e/framework/addon/BUILD.bazel, test/e2e/framework/addon/certmanager/addon.go, test/e2e/framework/addon/samplewebhook/BUILD.bazel, test/e2e/framework/addon/samplewebhook/addon.go, test/e2e/framework/addon/samplewebhook/sample/BUILD.bazel, test/e2e/framework/addon/samplewebhook/sample/chart/example-webhook/.helmignore, test/e2e/framework/addon/samplewebhook/sample/chart/example-webhook/Chart.yaml, test/e2e/framework/addon/samplewebhook/sample/chart/example-webhook/templates/_helpers.tpl, test/e2e/framework/addon/samplewebhook/sample/chart/example-webhook/templates/apiservice.yaml, test/e2e/framework/addon/samplewebhook/sample/chart/example-webhook/templates/deployment.yaml, test/e2e/framework/addon/samplewebhook/sample/chart/example-webhook/templates/pki.yaml, test/e2e/framework/addon/samplewebhook/sample/chart/example-webhook/templates/rbac.yaml, test/e2e/framework/addon/samplewebhook/sample/chart/example-webhook/templates/service.yaml, test/e2e/framework/addon/samplewebhook/sample/chart/example-webhook/values.yaml, test/e2e/framework/addon/samplewebhook/sample/main.go, test/e2e/suite/issuers/acme/certificate/BUILD.bazel, test/e2e/suite/issuers/acme/certificate/webhook.go, test/fixtures/example-webhook-values.yaml
Adds a DNS test that creates a certificate and waits to ensure that cert-manager marks the certificate as presented, by calling the provisioned 'dummy' DNS01 webhook (this webhook will *always* return success, so long as it can decode the ChallengePayload).
This is currently using a copy of the helm chart taken from the [example repo](https://github.com/munnerz/cert-manager-webhook-example).
```release-note
NONE
```
=> Add acme dns01 webhook provider e2e test case

Makefile, docs/devel/develop-with-minikube.rst
Signed-off-by: Michael FIG <michael@liveblockauctions.com>
Updates the build instructions and Makefile rule to allow cross-platform builds of Docker images from a MacOS host.  It probably works for Windows, too, but it is not tested.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: n/a
The `--platforms` flag enables Bazel rules for the Go Linux cross-compiler.
```
Update build instructions and enable building under MacOS.
```
=> Build under MacOS.

test/fixtures/cert-manager-values.yaml
This should make reading logs easier 😄 
```release-note
NONE
```
=> Set global.logLevel to 4 during e2e tests

pkg/controller/certificates/BUILD.bazel, pkg/controller/certificates/sync.go
It seems that the metav1.Time that we read from the x509 certificate changes between calls to read the certificate.
This PR updates the acmechallenges controller to first encode to json before comparing the encoded bytes, which should resolve the issue.
There's probably a cleaner way to handle this comparison, but for now this fixes a known bug 🙈 
**Which issue this PR fixes**: fixes #TODO
```release-note
Fix update loop in certificates controller and add additional debug logging 
```
=> Fix update loop due to changing notAfter struct

pkg/controller/ingress-shim/sync.go
When testing out migrating my certificates & issuers to use the new format (managed by ingress-shim), it would not clear the `certificate.spec.acme` block on existing Certificate resources without me manually deleting them first, because the `setIssuerSpecificConfig` method does not actually clear the field if it is already set.
```release-note
NONE
```
=> Fix issue when migrating ingress-shim managed certificates from old to new format

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/templates/rbac.yaml, deploy/charts/cert-manager/values.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml
This PR relaxes some right in order to enable this Chart to be deployed flawlessly on Openshift.
This helm chart have some trouble launching the webhook, after investigation, it sounded like it had some trouble creating or editing some of the needed secrets. 
Also, cert-manager needs to edit ingress. This cannot be done with the actual rights of this chart. 
```release-note
Allow Openshift to install cert-manager chart
```
=> Fix RBAC for openshift and add openshift compatibility

deploy/charts/cert-manager/Chart.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml
The patch version here was accidentally bumped instead of the revision number.
This PR will require manual overriding of the chart job to merge 😄 
```release-note
NONE
```
=> Fix chart version accidentally being ahead

docs/tutorials/acme/migrating-from-kube-lego.rst
**What this PR does / why we need it**: The migration docs reference `stable/cert-manager` whcih when applied installs the wrong version of cert-manager which leads to a whole bunch of problems.
=> Fix wrong helm repo reference in "Migrating from kube-lego"

hack/ci/lib/build_images.sh, hack/def.bzl, hack/release/pkg/build/images/plugin.go
Sets the correct image suffix when exporting docker images.
**Which issue this PR fixes**: fixes #1637 
```release-note
NONE
```
=> Correctly suffix image names with architecture & fix authentication

hack/release/pkg/build/images/plugin.go
Docker fails if `--config` is specified *after* `push` 🤦‍♂ 
```release-note
NONE
```
=> Fix use of --config flag when calling docker

deploy/manifests/00-crds.yaml, pkg/apis/certmanager/v1alpha1/types_issuer.go, pkg/apis/certmanager/validation/issuer.go, pkg/apis/certmanager/validation/issuer_test.go, pkg/issuer/acme/setup.go
Email addresses aren't required by the acme standard. Bring the configuration into line with the spec
fixes #1428
```
Make ACME email addresses optional
```
=> make email address an optional field in ACME issuers

hack/release/pkg/build/manifests/github.go
Read the github token used to publish static manifests from a file instead of passed on the CLI to avoid potentially leaking secrets during release runs.
```release-note
NONE
```
=> release: read github token from file

docs/index.rst
Fixes the Venafi link on https://docs.cert-manager.io/en/latest/
=> [docs] Fix Venafi link

pkg/issuer/acme/http/ingress.go
Prepends new paths to an ingress rule, to fix an issue with `alb-ingress-controller` choosing a less specific path.
fixes #1417 
```release-note
New paths added to ingress are prepended to the associated rule, instead of appended
```
=> Prepend when adding paths to ingress

cmd/controller/app/controller.go, cmd/controller/app/options/options.go, pkg/controller/acmechallenges/controller.go, pkg/controller/acmechallenges/scheduler/scheduler.go, pkg/controller/acmechallenges/scheduler/scheduler_test.go, pkg/controller/context.go
Makes `MaxConcurrentChallenges` (the maximum number of challenges which can be scheduled as 'processing' at any time) a configurable parameter via the flag `--max-concurrent-challenges <int>`, with default value of `60`.
**Which issue this PR fixes**: fixes #1540 
```release-note
Add `MaxConcurrentChallenges` as a configurable parameter via the flag `--max-concurrent-challenges <int>`
```
=> Make MaxConcurrentChallenges a configurable parameter

pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/webhook/webhook.go
The creation of the `ChallengeRequest` resource for the webhook issuer is incorrect. The `DNSName` field is always empty (it is never set) and the `Config` field contains the wrong object (the `ACMEIssuerDNS01ProviderWebhook` containing the config).
This PR fills the `DNSName` field with the DNS name and makes `Config` contain the correct object.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/jetstack/cert-manager/issues/1674
I didn't want to dive into how to build this project, so the changes are not tested.
```release-note
The `DNSName` field in the …
```
=> fix ChallengeRequest resource creation

pkg/controller/ingress-shim/sync.go, pkg/controller/ingress-shim/sync_test.go, pkg/controller/test/context_builder.go
Updates ingress-shim to copy labels across from Ingress resources to Certificates.
This *may* causing 'fighting' between controllers as it is, however it depends if other controllers utilise labels on resources to track things.
We should probably revisit this soon to see if there's a more optimal way we can co-exist with other controllers.
This is needed to make the new ACME solver selector code work well with ingress-shim.
```release-note
Copy labels from Ingress resources to Certificates
```
=> Copy labels from Ingress to Certificate resource in ingress-shim

test/e2e/framework/addon/chart/addon.go
Fixes issue with `ChartVersion` not being set as a flag when calling `helm install` in the e2e tests, preventing the correct setup of kind pods and therefore testing.
```release-note
NONE
```
=> Add ChartVersion to helm install when running tests

test/e2e/framework/cleanup.go
The license header got overwritten as part of this commit 51195e4c
This change rolls it back with additional directive to skip license
check in favor of hack/verify_boilerplate.py
`test/e2e/framework/cleanup.go`), which is copied from other project (kubernetes/kubernetes), has the original copyright line overwritten as part of https://github.com/jetstack/cert-manager/commit/51195e4c5f75d200738a8378a2a1d08a59afcb82 which should not happen
```release-note
```
=> Correct test/e2e/framework/cleanup.go license header

pkg/controller/acmeorders/sync.go
These variables seem like they should be updated when updating the thing they are supposed to be derived from.
https://github.com/jetstack/cert-manager/issues/1714
```release-note
Fix a the logic to select the most specific solver from an issuer if multiple matched
```
=> Fix logic to select the solver that has the most labels

docs/tasks/issuers/setup-acme/dns01/google.rst
I propose to stay in the context of this example and either use `example-issuer` or `letsencrypt-staging` in both of th examples in this context.
=> Change name of issuer to issuer from contextual example

docs/tutorials/acme/migrating-from-kube-lego.rst
Adds the `solvers` field in the kube-lego migration guide doc.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1611 
Just copies code blocks from https://docs.cert-manager.io/en/latest/tasks/issuers/setup-acme/index.html
```release-note
NONE
```
=> Add solvers field in kube-lego migration guide

WORKSPACE, hack/def.bzl, test/e2e/charts/pebble/BUILD.bazel, test/e2e/framework/addon/samplewebhook/sample/BUILD.bazel
This PR switches all cert-manager images to use 'gcr.io/distroless/static' as a base.
This image contains pretty much just ca-certificates, which makes it perfect for what we need.
distroless/static does not include any binaries at all, meaning the base image is by default multi-arch 😄 
Users wanting to debug from within the cert-manager pod will need to attach an additional container with their debug utilities to the pod's namespaces.
```release-note
Switch to using distroless for base images
```
=> Switch to gcr.io/distroless/static base image

deploy/charts/cert-manager/cainjector/templates/rbac.yaml, deploy/charts/cert-manager/templates/rbac.yaml
This will be a true test of our test suite's coverage...
I've only updated the main chart for now. Still need to work on cainjector and webhook.
```release-note
Reduce cert-manager's RBAC permissions
```
=> Split up RBAC permissions and make them more granular

test/e2e/charts/pebble/templates/deployment.yaml, test/e2e/charts/pebble/values.yaml, test/e2e/framework/addon/pebble/pebble.go, test/e2e/framework/config/pebble.go, third_party/crypto/acme/acme.go, third_party/crypto/acme/acme_test.go, third_party/crypto/acme/jws.go
Add support for ACME POST-as-GET to the ACME client.
Thanks to @bluecmd for this patch.
**Which issue this PR fixes**: fixes #1341 
I'm holding this patch until v0.9, as this probably shouldn't be included this late in v0.8.
```release-note
Add support for ACMEv2 POST-as-GET
```
/hold
/milestone v0.9
=> Add support for ACMEv2 POST-as-GET

docs/getting-started/install/openshift.rst
The beta link was still in the docs. Fixed that.
=> Fixed manifest file link for openshift

pkg/controller/acmeorders/sync.go
The address of a for loop created variable does not change between loops - the variable is over-written with each new variable.  This fixes the code so that `d` references the array element instead of the local variable, which means that when `d` is assigned to `matchAll` or `specificMatch` it will work as intended.
Fixes https://github.com/jetstack/cert-manager/issues/1716 and prevents the underlying cause of https://github.com/jetstack/cert-manager/issues/1713
```release-note
Fix a bug where the logic to select a solver would always return the last solver and may return the wrong kind of solver for the challenge that it returned.
```
=> Fix solver selection logic to return the selected solver rather than always returning the last one

pkg/issuer/acme/http/http.go
If a user has not specified anything under the `issuer.spec.acme.solvers[].http01.ingress` field, but *has* set `issuer.spec.acme.solvers[].http01` to some non-nil value, we would panic when calling `buildService` in the HTTP01 challenge solver as a `http01` structure would be returned with a nil `ingress` field.
**Which issue this PR fixes**: fixes #1739
```release-note
Fix a panic when a misconfigured Issuer is used for HTTP01 challenge solving
```
/milestone v0.8
=> Fix panic in HTTP01 solver if ingress field is not specified

go.mod, go.sum, pkg/issuer/venafi/BUILD.bazel, pkg/issuer/venafi/connector_test.go, pkg/issuer/venafi/issue.go, pkg/issuer/venafi/issue_test.go, pkg/issuer/venafi/venafi.go, vendor/github.com/Venafi/vcert/client.go, vendor/github.com/Venafi/vcert/config.go, vendor/github.com/Venafi/vcert/pkg/certificate/certificate.go, vendor/github.com/Venafi/vcert/pkg/certificate/certificateCollection.go, vendor/github.com/Venafi/vcert/pkg/endpoint/endpoint.go, vendor/github.com/Venafi/vcert/pkg/venafi/cloud/certificatePolicies.go, vendor/github.com/Venafi/vcert/pkg/venafi/cloud/cloud.go, vendor/github.com/Venafi/vcert/pkg/venafi/cloud/company.go, vendor/github.com/Venafi/vcert/pkg/venafi/cloud/connector.go, vendor/github.com/Venafi/vcert/pkg/venafi/cloud/search.go, vendor/github.com/Venafi/vcert/pkg/venafi/fake/connector.go, vendor/github.com/Venafi/vcert/pkg/venafi/fake/fake.go, vendor/github.com/Venafi/vcert/pkg/venafi/tpp/connector.go, vendor/github.com/Venafi/vcert/pkg/venafi/tpp/search.go, vendor/github.com/Venafi/vcert/pkg/venafi/tpp/tpp.go, vendor/github.com/Venafi/vcert/vcert.go, vendor/modules.txt
This resolves issues when talking to the latest iteration of the Venafi Cloud API, which appears to have removed the `ping/` endpoint (causing previous versions of this library to fail).
```release-note
Bump Venafi vcert dependency to latest version
```
/cc @alljames @mattbates
=> Bump vcert to latest version

docs/tutorials/acme/quick-start/index.rst
I ran into a couple of problems using this document as a guide to
deploying cert-manager in my own cluster. This is the most comprehensive
document on getting the latest cert-manager up and running, so I
think using it this way will be common. These suggestions are
intended to improve the clarify of the doc in a way that I think
would have helped me get running more quickly.
N/A
Summary of changes:
1. Previous version referenced the `cert-manager` namespace already
existing, but don't instruct you to create it at any point. Changed
these instructions to …
=> Quick-Start example clarity suggestions

pkg/controller/ingress-shim/BUILD.bazel, pkg/controller/ingress-shim/sync.go, pkg/controller/ingress-shim/sync_test.go
If two ingresses are setup with the same Certificate resource, then only the first will be the owner and be allowed to modify it. Any attempts from the second ingress to modify the resource will be skipped, preventing 'flap' updates when misconfigured.
Tests are also changed to conform with this new strategy, and additional tests have been added to test the strategy.
**Which issue this PR fixes**: fixes #1520 
```release-note
Ingress skips updating Certificate resource if already exists and not owned
```
=> Ensure only the sole owner of a certificate can modify it

pkg/issuer/acme/issue.go, test/e2e/suite/issuers/acme/certificate/BUILD.bazel, test/e2e/suite/issuers/acme/certificate/http01_new.go
We previously always generated a 2048 bit RSA private key in the ACME issuer even if an ECDSA key was requested. This also meant we'd have an RSA private key with an ECDSA certificate in issued certificates.
**Which issue this PR fixes**: fixes #1741
```release-note
Fix bug causing ECDSA certificates to be issued using 2048-bit RSA private keys
```
/milestone v0.8
=> Fix ECDSA certificate issuance with ACME issuer

docs/tasks/issuing-certificates/index.rst, pkg/controller/helper_test.go
Some issuers set the `notBefore` field of their issued X.509 certificates to be before the time of issuance to handle clock-skew issues, for example Let's Encrypt sets it to be one hour before.
In the case of LE, this means that the working duration is actually `89d23h`, while the full duration (`notAfter - notBefore`) remains `90d`.
This can cause issues if the `renewBefore` field of Certificate resources is set to be very close to the full duration, e.g. `89d23h50m`, since it will **always** be in the renewal period and so the controllers will **always** try to renew it.
I have added a test to demonstrate what happens in this case, and added documentation describing what is happening and to …
=> Add documentation on taking care when setting `renewBefore` to be close to `duration`

docs/tasks/issuers/setup-acme/index.rst
The `selector` field needs to be on the same level as the solver type (either `dns01` or `http01`).
Fixes invalid example config in the docs.
```release-note
Fix indentation on ACME setup examples
```
=> Fix indentation on ACME setup examples

docs/getting-started/troubleshooting.rst
The secret should exist in the `cert-manager` namespace, otherwise we would be checking `default` namespace.
- N/A
```release-note
cert-manager-webhook secret exists in cert-manager ns
```
=> cert-manager-webhook secret exists in cert-manager ns

pkg/controller/BUILD.bazel, pkg/controller/acmechallenges/BUILD.bazel, pkg/controller/acmechallenges/controller.go, pkg/controller/acmechallenges/sync.go, pkg/controller/acmeorders/BUILD.bazel, pkg/controller/acmeorders/checks.go, pkg/controller/acmeorders/controller.go, pkg/controller/base_controller.go, pkg/controller/certificates/BUILD.bazel, pkg/controller/certificates/checks.go, pkg/controller/certificates/controller.go, pkg/controller/clusterissuers/BUILD.bazel, pkg/controller/clusterissuers/controller.go, pkg/controller/ingress-shim/BUILD.bazel, pkg/controller/ingress-shim/controller.go, pkg/controller/issuers/BUILD.bazel, pkg/controller/issuers/controller.go, vendor/modules.txt
Adds a `BaseController` struct as a collection of common fields in the Controllers, along with the common functions `Run()` and `worker()`.
The Controllers have been modified to use this struct.
**Which issue this PR fixes**: fixes #1003 
I'm not sure how well these changes align with Go best practices, particularly with regards to accessing the fields of the `BaseController` from the Controller - I am very open to any reviews of this PR.
```release-note
NONE
```
=> Add BaseController as a refactoring of common controller code

deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/servicemonitor.yaml, deploy/charts/cert-manager/values.yaml
Add support for new ServiceMonitor API in Prometheus Operator
**Which issue this PR fixes**: fixes #1682
```release-note
Add support for Prometheus Operator ServiceMonitor object in Helm Chart
```
=> Add support for Prometheus Operator ServiceMonitor object in Helm Chart

pkg/controller/certificates/sync.go, pkg/controller/certificates/sync_test.go, test/unit/gen/certificate.go
Validates that only one Certificate is using a specific `secretName` per namespace checking that is unique before issuing, preventing multiple Certificates from updating the Secret.
**Which issue this PR fixes**: fixes #1558 
```release-note
Validate that Certificates in a namespace have unique `secretName`
```
=> Validate that only one Certificate is using a secretName per namespace

pkg/issuer/acme/dns/clouddns/BUILD.bazel, pkg/issuer/acme/dns/clouddns/clouddns.go
Fixes issue with managed zone picked being the first from the array, with may be private.
**Which issue this PR fixes**: fixes #1383 
```release-note
Fix issue with private managed-zone being picked in CloudDNS
```
=> Ensure managed zone picked for CloudDNS is public

pkg/issuer/acme/issue.go
Truncates Certificate name when forming Order name to 52 characters, to allow space for hash - fixing issue with name being longer than 63 characters.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1552 
```release-note
Fix bug with auto-generated Order names being longer than 63 characters
```
=> Add truncation of certificate name when forming order name

docs/tutorials/acme/quick-start/index.rst
Fix code rendering in ACME quick start guide
Replaces #1376 
```release-note
NONE
```
/cherrypick release-0.8
=> Fix code rendering in docs

pkg/controller/ingress-shim/sync.go, pkg/controller/ingress-shim/sync_test.go
When the `SecretName` of a TLS entry in an ingress is changed/modified, the previous certificate is deleted.
This fixes issues with work queues being filled with unrequired certificates.
**Which issue this PR fixes**: fixes #912 
The change to `sync_test.go` will need to be modified for simplicity to follow the changes in pull request #1670 (w.r.t. owner references).
```release-note
Add the removal of certificates when no longer required by the owner ingress
```
=> Add the removal of unrequired certificates

pkg/controller/certificates/controller.go, pkg/metrics/BUILD.bazel, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
Prometheus metrics for Certificates will be cleaned up by deleting entries for deleted Certificates, and keeping track of which Certificates are currently registered by Prometheus.
This prevents metrics for deleted Certificates from being exposed past their use.
**Which issue this PR fixes**: fixes #1332 
The metrics are currently cleaned up every minute via a goroutine in the certificate controller - I would be happy to discuss a more refined garbage collection scheme to implement.
```release-note
Prometheus metrics for deleted Certificates are cleaned up
```
=> Clean up Prometheus metrics for deleted Certificates

test/e2e/framework/framework.go
This will fix printing pod logs when tests fail during e2e
```release-note
NONE
```
=> Fix loggableAddon interface in test framework

deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/cainjector/values.yaml, deploy/charts/cert-manager/webhook/values.yaml
Documents how to set the `nodeSelector` to the webhook and cainjector, to disambiguate the current single `nodeSelector` parameter. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1673 
```release-note
NONE
```
=> Document configuring nodeSelector for webhook and cainjector

hack/update-crds.sh
When adding new resources we found inconsistencies in how bash expanded and for looped over `dir/*`.
This should keep things consistent and passing CI. 
```release-note
NONE
```
=> Use find + sort to ensure we list CRD files consistently across multiple dev environments

docs/getting-started/troubleshooting.rst
_--show-all_ has been deprecated in kubernetes v1.15, docs are stale.
fixes #1814
As there is no alternative for _--show-all_ I went with a less-is-more approach and deleted both the flag and the comment.
None needed, this only updated the docs. No code changes.
=> Removing use of kubectl --show-all in docs

pkg/controller/BUILD.bazel, pkg/controller/acmechallenges/controller.go, pkg/controller/acmechallenges/scheduler/BUILD.bazel, pkg/controller/acmechallenges/scheduler/scheduler.go, pkg/controller/acmechallenges/scheduler/scheduler_test.go, pkg/controller/acmeorders/BUILD.bazel, pkg/controller/acmeorders/sync.go, pkg/controller/certificates/controller.go, pkg/controller/certificates/sync.go, pkg/controller/helper.go, pkg/controller/helper_test.go, pkg/controller/ingress-shim/BUILD.bazel, pkg/controller/ingress-shim/sync.go, pkg/issuer/acme/dns/BUILD.bazel, pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/dns_test.go, pkg/issuer/acme/issue.go
This continues work to remove references to klog from our codebase. There are now no direct references in the whole of `pkg/controller` 😄 🎉
```release-note
NONE
```
=> Remove use of klog from more places

pkg/issuer/acme/BUILD.bazel, pkg/issuer/acme/sign.go, pkg/issuer/ca/BUILD.bazel, pkg/issuer/ca/sign.go, pkg/issuer/fake/fake.go, pkg/issuer/issuer.go, pkg/issuer/selfsigned/BUILD.bazel, pkg/issuer/selfsigned/sign.go, pkg/issuer/vault/BUILD.bazel, pkg/issuer/vault/sign.go, pkg/issuer/venafi/BUILD.bazel, pkg/issuer/venafi/sign.go
Adds sign interface to interfaces `	Sign(context.Context, *v1alpha1.CertificateRequest) (*IssueResponse, error)`
This is a requirement for moving over to using CertificateRequests to issue certificates using x509 certificate requests instead of exposing keys.
Rebased on top of #1789 
```release-note
Adds Sign interface to Issuers
```
=> Adds sign interfaces for Issuers

pkg/issuer/ca/BUILD.bazel, pkg/issuer/ca/issue.go, pkg/issuer/ca/issue_test.go, pkg/issuer/ca/sign.go, pkg/issuer/ca/sign_test.go, pkg/issuer/ca/util_test.go, pkg/util/pki/BUILD.bazel, pkg/util/pki/csr.go, test/unit/gen/BUILD.bazel, test/unit/gen/certificaterequest.go
Signed-off-by: JoshVanL <vleeuwenjoshua@gmail.com>
Adds `sign` functionality to the CA issuer.
Enables signing of CSRs using custom CA without generation or exposing of keys.
```release-note
Adds CSR signing to CA issuer
```
=> Adds Sign function to CA issuer

BUILD.bazel, Makefile, cmd/acmesolver/BUILD.bazel, cmd/cainjector/BUILD.bazel, cmd/controller/BUILD.bazel, cmd/webhook/BUILD.bazel, hack/def.bzl, hack/release/pkg/bazel/flags.go, hack/release/pkg/build/images/plugin.go, test/e2e/charts/pebble/BUILD.bazel, test/e2e/framework/addon/samplewebhook/sample/BUILD.bazel
This changes how we perform a crossbuild for multiple platforms to only ever make use of the `--platform` flag, and never to explicitly set goos or goarch on go_image rules.
Also modifies the release tool to handle this change.
Due to complexities in the way bazel exposes the current architecture being built for, this means we can no longer suffix image names with their architecture when building them. Instead, i've moved this logic into the `//hack/release` tool, which now handles automatically tagging built docker images with appropriate tags.
To build for different architectures, you can run:
```
bazel run --platforms=@io_bazel_rules_go//go/toolchain:linux_arm64 //cmd/acmesolver:image.export
bazel run …
```
=> Change bazel build to only build for current --platform

deploy/charts/cert-manager/cainjector/templates/rbac.yaml, pkg/api/BUILD.bazel, pkg/api/scheme.go, pkg/controller/cainjector/BUILD.bazel, pkg/controller/cainjector/controller.go, pkg/controller/cainjector/injectors.go, pkg/controller/cainjector/setup.go, test/e2e/framework/BUILD.bazel, test/e2e/framework/framework.go, test/e2e/suite/serving/BUILD.bazel, test/e2e/suite/serving/cainjector.go
This adds support for the CRD conversion webhook configuration to the CA
injector controller.  This allows you to configure injection conversion webhooks much the same way that you can for validating/mutating webhooks and API services.
```release-note
Support CRD conversion webhooks in the CA injector controller.
```
=> Add support for CRDs to the CA injector

pkg/issuer/acme/http/solver/solver.go
Adding cache control in the response header
fixes: https://github.com/jetstack/cert-manager/issues/597
=> [GH-597] add cache-control header

deploy/manifests/00-crds.yaml, pkg/acme/client/fake.go, pkg/acme/client/interfaces.go, pkg/acme/client/middleware/logger.go, pkg/apis/certmanager/v1alpha1/types_issuer.go, pkg/issuer/acme/setup.go, test/e2e/suite/issuers/acme/issuer.go
When the `email` in the `spec.acme` field of an Issuer changes, compares this with the newly added field `lastRegisteredEmail` in `status.acme`.
If they are different then the registering process is begun, otherwise nothing.
On success the field is updated to the spec value, otherwise on failure or no difference it is kept the same.
As the `status` has changed then `updateIssuerStatus` will be called, and changes should be made to the actual Issuer.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1667 
```release-note
Adds the handling of updates to the …
```
=> Add handling of updates to ACME email field in Issuers

cmd/controller/app/controller.go, pkg/controller/acmechallenges/BUILD.bazel, pkg/controller/acmechallenges/sync_test.go, pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/rfc2136/provider.go
When we moved the rfc2136 solver to implement the webhook interface internally, we forgot to handle setting a namespace filter on the constructed informer factory.
This PR passes the option through to the solver so it can be properly filtered, thus resolving RBAC issues 😄 
**Which issue this PR fixes**: fixes #1838 
```release-note
Fix issue causing challenge controller to attempt to list Secrets across all namespaces even when --namespace is specified
```
=> Respect --namespace flag in rfc2136 provider

deploy/manifests/00-crds.yaml, docs/generated/reference/output/reference/api-docs/index.html, pkg/apis/certmanager/v1alpha1/types_issuer.go, pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go, pkg/controller/acmeorders/BUILD.bazel, pkg/controller/acmeorders/selectors/BUILD.bazel, pkg/controller/acmeorders/selectors/dns_names.go, pkg/controller/acmeorders/selectors/dns_zones.go, pkg/controller/acmeorders/selectors/labels.go, pkg/controller/acmeorders/selectors/selector.go, pkg/controller/acmeorders/sync.go, pkg/controller/acmeorders/sync_test.go
Add support for `dnsZones` field in solver selectors for the ACME issuer.
This PR is split into 4 parts:
* Adding unit tests that pass for the existing implementation, covering dnsNames and labels
* Refactor the function to be written in an easier to extend way
* Add support for dnsZones selectors
* Add unit tests for dnsZones selectors
Fixes #1783 
```release-note
Add support for selecting ACME challenge solver to use by specifying 'dnsZones' in the selector
```
=> Add support for dnsZones in ACME solver selectors & rewrite selection logic

pkg/issuer/acme/http/http.go
**What this PR does / why we need it**: allows to use proxy environment variables in self-check request
**Special notes for your reviewer**: [default transport uses proxy environment variables](https://golang.org/pkg/net/http/#RoundTripper), but since [0.6](https://github.com/jetstack/cert-manager/blob/v0.6.0/pkg/issuer/acme/http/http.go#L159) custom transport is used and it is impossible to send self-check request through proxy. This is needed to get certificates for internal services (see https://github.com/jetstack/cert-manager/pull/942#issuecomment-433112965)
```release-note
Use proxy environment variables in self-check request
```
=> Use proxy from env in self check request

pkg/issuer/acme/dns/util/BUILD.bazel, pkg/issuer/acme/dns/util/wait.go, pkg/issuer/acme/dns/util/wait_test.go
Fixes incorrect handling of the `issuewild` tag in `matchCAA`, so that `issuewild` entries will take priority on any wildcard certificate verifications, but `issue` entries can also permit these in the absence of entries of the former.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1587  
I have added a test to verify that wildcard certificates are possible with `www.google.com`'s CAA record, but this could be quite fragile since it is dependent on Google not adding an `issuewild` entry in the future.
I would like to add a test for verifying that …
=> Fix incorrect `issuewild` handling in matchCAA

deploy/manifests/00-crds.yaml, docs/generated/reference/output/reference/api-docs/index.html, pkg/apis/certmanager/v1alpha1/types_certificate.go, pkg/apis/certmanager/validation/certificate.go, pkg/apis/certmanager/validation/certificate_test.go, test/e2e/suite/issuers/acme/certificate/http01.go, test/e2e/suite/issuers/acme/certificate/http01_new.go
Adds checks to the validation webhook to ensure that CommonName length is below 64 bytes, or that the first entry in DNSNames (if CommonName is empty) is below 64 bytes.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1812 
```release-note
Limit length for CommonName to 63 bytes
```
=> Add validation for CommonName and DNSNames length

pkg/controller/acmeorders/sync.go
This should make it obvious to users why their Order is not progressing if no solver type can be chosen.
This has exposed some issues with the way we handle this case too, which I'll open a separate issue to track improving.
**Which issue this PR fixes**: fixes #1718
```release-note
Fire informational Event if an ACME solver cannot be chosen for a domain on an Order
```
=> Fire an Event when no acme solver matches an identifier being validated

deploy/charts/cert-manager/values.yaml
Includes commented-out arg reference for enabling certificate-owner feature flag... Pretty boring PR, I know. Little bit of inline "documentation" that will save some time for people trying to enable this
See also:
https://github.com/jetstack/cert-manager/issues/296
https://github.com/jetstack/cert-manager/pull/819
https://github.com/jetstack/cert-manager/issues/912
https://github.com/jetstack/cert-manager/pull/1705
https://github.com/jetstack/cert-manager/issues/296
```release-note
commented-out extraArg for enable-certificate-owner-ref
```
=> enable-certificate-owner-ref chart placeholder

test/e2e/suite/issuers/venafi/tpp/certificate.go
There are currently issues with our test instance, so skip the tests for now until they are resolved 😄 
```release-note
NONE
```
=> Skip Venafi issuer e2e tests

pkg/issuer/acme/setup.go
The first commit in this PR fixes an issue where the new email address would not be persisted to the Kubernetes API on the Issuer resources `status` field after the email has been updated. It also fixes a logging error.
The second commit refactors the logic for updating the email address into its own function, which should make it easier for us to unit tests this in future 😄
```release-note
NONE
```
=> Fix issues with updating ACME account email

hack/release/pkg/bazel/flags.go, hack/release/pkg/log/log.go
Fixes issue where the app-version and git commit info wasn't properly set when building release targets.
Before:
```
$ docker run "quay.io/jetstack/cert-manager-controller:v0.9.0-alpha.0"
I0708 14:02:38.361114       1 start.go:76] cert-manager "level"=0 "msg"="starting controller"  "git-commit"="{STABLE_APP_GIT_COMMIT}" "version"="{STABLE_APP_VERSION}"
```
After:
```
$ docker run "quay.io/jetstack/cert-manager-controller:v0.9.0-alpha.0"
I0708 14:42:16.619575       1 start.go:76] cert-manager "level"=0 "msg"="starting controller"  "git-commit"="458c7193d" "version"="v0.9.0-alpha.0"
```
```release-note
NONE
```
=> hack/release: add --stamp=true when running 'bazel run'

deploy/charts/cert-manager/README.md, docs/getting-started/install/kubernetes.rst, docs/getting-started/install/openshift.rst, docs/getting-started/webhook.rst, docs/tasks/issuing-certificates/index.rst, docs/tasks/upgrading/index.rst, docs/tasks/upgrading/upgrading-0.5-0.6.rst, docs/tutorials/acme/quick-start/index.rst
Bumps version strings across the docs website 😄 
```release-note
NONE
```
=> Bump version strings for v0.9 alpha

design/20190708.certificate-request-crd.md
/hold
```release-note
Adds CertificateRequest proposal
```
=> CertificateRequest "KEP"

design/20190708.certificate-request-crd.md
Adds the option earlier in graduation to get the Certificates controller using `CertificateRequets`.
Try things sooner and catch more bugs.
```release-note
NONE
```
=> CR KEP: Updates the beta strategy for Certificates controller

deploy/manifests/00-crds.yaml, docs/generated/reference/output/reference/api-docs/index.html, pkg/apis/certmanager/v1alpha1/types.go, pkg/apis/certmanager/v1alpha1/types_certificaterequest.go, pkg/controller/certificaterequests/BUILD.bazel, pkg/controller/certificaterequests/sync.go, pkg/controller/certificaterequests/sync_test.go, pkg/controller/certificates/BUILD.bazel, pkg/controller/certificates/sync.go, pkg/controller/certificates/sync_test.go
Adds a string `Group` to object reference. This is used by the CertificateRequest controllers to distinguish ownership of CertificateRequest resources. This therefore allows external controllers to have the same kind issuer reference but will be namespaces by the group.
The certmanager.k8s.io CertificateRequest controllers will watch for groups `""` and `"certmanager.k8s.io"`.
TODO:
Add a mutating webhook to inject the `certmanager.k8s.io` group name into issuer references when the field is empty.
Rebased on #1836 
/hold
/assign
```release-note
Adds `group` to `issuerRef` in `CertificateRequest` resources to distinguish resource ownership of incoming CertificateRequests so enabling full external issuer support. 
```
=> Include Group name in IssuerRef for CertificateRequest controller ownership distinction

docs/design/index.rst, docs/index.rst
Adds a page to the website with a link to the design documents from the repo `./design`. This makes the documents a bit more discoverable by people.
```release-note
Adds Design and Proposals page to website docs
```
=> Adds design and proposals to docs website

pkg/controller/acmeorders/sync.go, pkg/controller/acmeorders/sync_test.go
Previously when the `selectedSolver` has been set, and the current solver has no selector, a nil pointer panic would occur as it would try to retrieve data from the selector - we now just skip if the `selectedSolver` has already been set since it must be just as or more specific than the current.
```release-note
NONE
```
=> Fix bug where solver with no selector causes nil pointer

pkg/controller/acmeorders/sync.go, pkg/issuer/acme/issue.go, pkg/issuer/acme/issue_test.go
Previously the Order resource's CSR field was set to a DER encoded CSR instead of the expected format, PEM.
This PR does two things:
1) changes the ACME Issuer to create Orders with PEM encoded CSRs
2) changes the `acmeorders` controller to be able to handle both PEM and DER encoded CSRs, to prevent users upgrading from a release without this patch having broken in-flight orders.
In future, we should also extend our validation to validate that the CSR is PEM encoded. We will need to wait until after all users have moved off problematic versions before we can do so however, as otherwise we'd block updates to existing Order resources containing DER encoded CSRs.
Due to the way we check if the Order is up to date for a Certificate already, existing …
=> Encode CSR on Order into PEM format and properly handle decoding

pkg/controller/certificates/sync.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
Adds metrics to track the ready status of certificates.
Built over/modified from @seleznev's patch.
Also refactors the clean up to use a cleanUpFunctions slice.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1679 
```release-note
Add Prometheus metrics for tracking Certificate readiness
```
=> Add Prometheus metrics for Certificate ready status

docs/reference/certificaterequests.rst, docs/reference/index.rst
Adds documentation on the CertificateRequest resource.
```release-note
NONE
```
/assign
/hold
=> Adds CertificateRequest docs

pkg/controller/certificaterequests/sync.go, pkg/controller/certificaterequests/sync_test.go
This condenses the condition status reasons for the CertificateRequest to `Pending`, `Failed` and `Issued`
This simplifies how a controller will handle states of this resource.
```release-note
NONE
```
=> Changes CertificateRequest conditions to only Pending/Failed/Issued

cmd/controller/app/BUILD.bazel, cmd/controller/app/controller.go, pkg/controller/certificates/BUILD.bazel, pkg/controller/certificates/certificate_request.go, pkg/controller/certificates/certificate_request_test.go, pkg/controller/certificates/checks.go, pkg/controller/certificates/controller.go, pkg/controller/certificates/sync.go, pkg/issuer/acme/issue.go, pkg/issuer/vault/issue.go, pkg/util/pki/csr.go, test/unit/gen/certificate.go, test/unit/gen/certificaterequest.go
This PR implements an initial implementation of the new Certificate controller implementation which manages CertificateRequest resources to issue certificates as described in [the proposal](https://github.com/jetstack/cert-manager/blob/master/design/20190708.certificate-request-crd.md).
The remaining parts to implement:
Opening this now for visibility 😄 
All this new functionality is kept behind the existing CertificateRequestControllers feature gate, so this should have a net-zero effect for most users.
~There are some key pieces missing still, and I've not actually run this on a real cluster yet (just lots of unit testing! 😅)~ Has now been run on a real cluster and confirmed working 😄  …
=> Implement new Certificate controller that manages CertificateRequest resources

design/release-notes/release-0.8/draft-release-notes.md, design/release-notes/release-0.9/draft-release-notes.md
Cert-manager release notes are now going to be kept in tree and then copied over at the time of a release. Ideally, 0.9 release notes should be completed and merged before the release is cut.
rebased on #1890 
```release-note
NONE
```
=> 0.9 Release Notes

docs/tasks/issuers/setup-venafi.rst, docs/tutorials/venafi/securing-ingress.rst
Updates a couple of typos in the new Venafi tutorial & includes details on configuring a TPP server as well as Venafi Cloud.
```release-note
NONE
```
=> Fix two typos in Venafi tutorial & add TPP details

deploy/charts/cert-manager/cainjector/templates/deployment.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/webhook/templates/deployment.yaml, test/e2e/framework/addon/samplewebhook/sample/chart/example-webhook/templates/deployment.yaml
I'd like to get this in for v0.9 to ensure our deployment manifests are compatible with k8s 1.16 😄
This should work all the way back to v1.9 😄 
more info: https://groups.google.com/forum/#!topic/kubernetes-dev/je0rjyfTVyc
```release-note
Bump Deployments in manifests to use apps/v1 API group, available since Kubernetes 1.9
```
/area deploy
/milestone v0.9
=> Update Deployment manifests to use apps/v1

WORKSPACE
Bumps rules_go & gazelle + bumps us to use Go 1.12.7
```release-note
Build using Go 1.12.7
```
=> Bump rules_go and gazelle

pkg/apis/certmanager/validation/certificate.go
This is needed in order to allow issuerRef's that specify `kind` fields other than Issuer/ClusterIssuer to be accepted by the validation webhook.
With this patch, we only validate the kind field if the group name field is empty.
This may need to be backported to v0.9 to support the on-going out-of-tree issuer efforts.
```release-note
Don't validate issuerRef.kind field if issuerRef.group is set in order to support out-of-tree Issuer types
```
=> Do not validate issuerRef's Kind field if group is not recognised

design/20190708.certificate-request-crd.md
Signed-off-by: JoshVanL <vleeuwenjoshua@gmail.com>
Adds the annotations section to the `CerticiateRequest` enhancement proposal.
Also includes the private key annotation that is required by the self signing issuer.
```release-note
NONE
```
=> Adds the CertificateRequest annotations section to JEP

deploy/manifests/00-crds.yaml, pkg/apis/certmanager/v1alpha1/types.go, pkg/apis/certmanager/v1alpha1/types_certificate.go, pkg/apis/certmanager/v1alpha1/types_certificaterequest.go, pkg/apis/certmanager/v1alpha1/types_challenge.go, pkg/apis/certmanager/v1alpha1/types_issuer.go, pkg/apis/certmanager/v1alpha1/types_order.go, pkg/apis/certmanager/validation/issuer.go, pkg/apis/certmanager/validation/issuer_test.go, pkg/issuer/acme/dns/dns.go
controller-tools requires the enum validation definitions to be set on the types themselves, and not fields of that type.
This PR adjusts our CRD schema validation to include these enum types.
```release-note
NONE
```
=> Fix enum type validation schema in API

deploy/charts/cert-manager/templates/service.yaml, deploy/charts/cert-manager/templates/servicemonitor.yaml
This fixes two errors with monitoring using the [Prometheus Operator ServiceMonitor](https://github.com/coreos/prometheus-operator/blob/3288dbd9cf9a9b667d16e48d7c113753635654ef/Documentation/design.md#servicemonitor) that was introducted in #1761 in order to make monitoring with Prometheus easier.
1. The ServiceMonitor object had incorrect match labels
1. The SerivceMonitor needs a Service in order to monitor 
```release-note
helm: fix lables and add Service for Prometheus ServiceMonitor
```
Signed-off-by: Hans Kristian Flaatten …
=> helm: fix lables and add Service for Prometheus ServiceMonitor

deploy/manifests/00-crds.yaml, pkg/apis/certmanager/v1alpha1/types_challenge.go, pkg/apis/certmanager/v1alpha1/types_order.go
Pulled out of #1922 so it can be cherry-picked back to v0.9.
```release-note
Mark 'spec' and 'status' as non-required fields in CRDs
```
=> Add omitempty to spec and status fields

pkg/controller/acmeorders/controller.go
In the Order controller we never instantiated the 'clock' var, meaning that if an Order fails a panic can occur.
This is already fixed in master, however needs cherrypicking back into release-0.9.
**Which issue this PR fixes**: fixes #1962
```release-note
Fix panic when an ACME Order fails
```
/milestone v0.9
=> Backport fix for panic in orders controller

deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/templates/servicemonitor.yaml, deploy/charts/cert-manager/values.yaml
This PR adds the possibility to specify the namespace where the serviceMonitor resource is going to be deployed. Sometimes we have prometheus monitoring from another namespace and we consolidate serviceMonitor resources there.
Also, it adds the possibility to specify custom labels for ServiceMonitor, some people (like us) use different labels so different prometheus can scan against this labels. 
**Which issue this PR fixes**: None
**Release notes**:
```release-note
Added variable to specify custom namespace where to deploy ServiceMonitor resource
```
**Special notes for your reviewer**: None
=> Improve ServiceMonitor resource by adding custom namespace and custom labels

pkg/controller/certificates/sync.go
Previously we did not DeepCopy Secret resources before updating them in the apiserver, despite fetching them from a shared cache.
This is simply using the lister improperly, so it's clear it needs to be fixed.
I think this manifested itself in #1951, as the lister and our own controller both modify the labels/annotations list simultaneously in certain cases.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1951
```release-note
Fix concurrent map write panic in certificates controller
```
/cc @JoshVanL
=> Fix concurrent map write panic

deploy/manifests/00-crds.yaml, pkg/api/util/conditions.go, pkg/apis/certmanager/v1alpha1/types_certificaterequest.go, pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go, pkg/controller/certificaterequests/BUILD.bazel, pkg/controller/certificaterequests/ca/BUILD.bazel, pkg/controller/certificaterequests/ca/ca.go, pkg/controller/certificaterequests/controller.go, pkg/controller/certificaterequests/selfsigned/BUILD.bazel, pkg/controller/certificaterequests/selfsigned/selfsigned.go, pkg/controller/certificaterequests/sync.go, pkg/controller/certificaterequests/sync_test.go, pkg/controller/certificaterequests/util/BUILD.bazel, pkg/controller/certificaterequests/util/reporter.go, pkg/controller/certificaterequests/util/reporter_test.go, pkg/controller/certificates/certificate_request.go, pkg/controller/certificates/certificate_request_test.go, test/unit/gen/certificaterequest.go
Adds FailureTime to CertificateRequet Status.
Time set to now on the CertificateRequest if failed and the FailureTime is not currently set.
The Certificate controller will re-try CertificateRequests that have failed and have a FailureTime of at least one hour in the past. If the FailureTime is less than one hour, the Certificate is rescheduled for syncing in one hour.
```release-note
Adds CertificateRequest FailureTime. The Certificate controller will re-try failed CertificateRequests at least one hour after this failed time.
```
=> Adds CertificateRequest FailureTime

pkg/apis/certmanager/v1alpha1/types.go, pkg/controller/cainjector/BUILD.bazel, pkg/controller/cainjector/controller.go, pkg/controller/certificates/certificate_request.go, pkg/controller/certificates/certificate_request_test.go, pkg/controller/certificates/sync.go, pkg/controller/certificates/sync_test.go
This key is essentially part of our API, and should be represented as such.
This is part of the effort to implement conversion webhooks (#1984)
```release-note
NONE
```
=> Move TLSCAKey to v1alpha1 package

cmd/cainjector/start.go, pkg/controller/cainjector/BUILD.bazel, pkg/controller/cainjector/controller.go, pkg/controller/cainjector/indexers.go, pkg/controller/cainjector/setup.go, pkg/controller/cainjector/sources.go, test/e2e/suite/serving/cainjector.go
As part of #1984, we need to be able to inject directly from secrets as we are unable to create Certificate resources during cert-manager's installation phase.
This PR extends the cainjector to support injecting from secrets with the new `inject-ca-from-secret` annotation, similar to the existing `inject-ca-from` one.
```release-note
cainjector: allow injecting CAs directly from Secret resources
```
=> Extend cainjector to support injecting from secrets

docs/tasks/upgrading/index.rst
Addresses question from user about inability to find cert-manager helm package.
It's a minor doc update to the upgrade procedure that could potentially save some headaches.
fixes #1931
=> #1931 clarify you have to manually add the jetstack helm repo

pkg/controller/acmechallenges/sync_test.go, pkg/controller/acmeorders/sync_test.go, pkg/controller/certificaterequests/acme/acme_test.go, pkg/controller/certificaterequests/ca/ca_test.go, pkg/controller/certificaterequests/selfsigned/selfsigned_test.go, pkg/controller/certificaterequests/sync_test.go, pkg/controller/certificaterequests/vault/vault_test.go, pkg/controller/certificaterequests/venafi/venafi_test.go, pkg/controller/certificates/certificate_request_test.go, pkg/controller/certificates/sync_test.go, pkg/controller/clusterissuers/sync_test.go, pkg/controller/ingress-shim/sync_test.go, pkg/controller/issuers/sync_test.go, pkg/controller/test/BUILD.bazel, pkg/controller/test/context_builder.go, pkg/controller/webhookbootstrap/BUILD.bazel, pkg/controller/webhookbootstrap/controller.go, pkg/controller/webhookbootstrap/controller_test.go, pkg/issuer/acme/dns/util_test.go, pkg/issuer/acme/http/util_test.go, pkg/issuer/acme/setup_test.go, pkg/issuer/acme/util_test.go, pkg/issuer/ca/util_test.go, pkg/issuer/helper_test.go, vendor/modules.txt
Without this change, the webhookboostrap controller will run for *every* Secret in the cluster, causing a tonne of log churn that is never useful.
Use a filtered informer that watches only a single namespace to fix this 😄 
```release-note
NONE
```
=> Watch only the webhookboostrap namespace in bootstrap controller

docs/tutorials/acme/quick-start/index.rst
Hi community,
When I learn `cert-manager` I find `kubectl get certificate` output is outdated.
Best,
Alpha
=> Update kubectl output result with kubectl 12+

test/acme/dns/fixture.go, test/acme/dns/options.go, test/acme/dns/suite.go, test/acme/dns/util.go
This makes the DNS conformance test's poll interval and propagation limit configurable on the fixture object by test authors. 
Until now the poll interval was fixed to be 3 seconds and the propagation limit to be 2 minutes. Especially the latter value may be too short e.g. when waiting for the deletion of the created TXT record, leading to a test failure that can't really be fixed if the propagation limit can't be increased.
```release-note
```
=> test/acme/dns: poll interval and propagation limit configurable

deploy/manifests/00-crds.yaml, docs/generated/reference/output/reference/api-docs/index.html, pkg/api/util/BUILD.bazel, pkg/api/util/usages.go, pkg/apis/certmanager/v1alpha1/types.go, pkg/apis/certmanager/v1alpha1/types_certificate.go, pkg/apis/certmanager/v1alpha1/types_certificaterequest.go, pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go, pkg/internal/apis/certmanager/types.go, pkg/internal/apis/certmanager/types_certificate.go, pkg/internal/apis/certmanager/types_certificaterequest.go, pkg/internal/apis/certmanager/v1alpha1/zz_generated.conversion.go, pkg/internal/apis/certmanager/validation/certificate.go, pkg/internal/apis/certmanager/validation/certificate_test.go, pkg/internal/apis/certmanager/zz_generated.deepcopy.go, pkg/util/pki/csr.go, pkg/util/pki/csr_test.go, test/e2e/framework/helper/certificaterequests.go, test/e2e/framework/helper/certificates.go, test/e2e/suite/issuers/ca/BUILD.bazel, test/e2e/suite/issuers/ca/certificate.go, test/e2e/suite/issuers/ca/certificaterequest.go, test/e2e/util/util.go, test/unit/gen/BUILD.bazel, test/unit/gen/certificate.go, test/unit/gen/certificaterequest.go, test/unit/gen/csr.go
Signed-off-by: stuart.warren <stuart.warren@ocado.com>
Enable users to request x509 key usages and extended key usages when defining a certificate or certificate signing request
fixes: #301
Happy to move things around, not sure if the apis/certmanager/v1alpha1/key_usages.go should be there, or contents better added to another file?
```release-note
Add ability to specify key usages and extended key usages in certificates
```
=> feat: enable crt/csr keyusages and extended keyusages

deploy/charts/cert-manager/templates/_helpers.tpl, deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml, docs/tasks/upgrading/upgrading-0.9-0.10.rst, pkg/controller/acmeorders/selectors/BUILD.bazel, pkg/controller/acmeorders/selectors/dns_zones_test.go, pkg/controller/certificaterequests/acme/acme.go, pkg/controller/certificates/certificate_request.go
Whilst going through the upgrade process myself, I encountered a couple of issues:
1) The name of the webhook chart has changed, meaning the label selector has changed again. I've simply switched this back to the old value for now to save extra pain for users upgrading.
2) If using the static manifest based install, there are a number of resources that need to be cleaned up else the old and new implementations will 'fight'.
```release-note
NONE
```
/milestone v0.10
=> Fix-up manifests and upgrade guide for v0.10

pkg/controller/certificates/sync.go, pkg/controller/certificates/sync_test.go, test/e2e/framework/helper/certificates.go, test/e2e/suite/conformance/BUILD.bazel, test/e2e/suite/conformance/certificates/BUILD.bazel, test/e2e/suite/conformance/certificates/acme/BUILD.bazel, test/e2e/suite/conformance/certificates/acme/acme.go, test/e2e/suite/conformance/certificates/ca/BUILD.bazel, test/e2e/suite/conformance/certificates/ca/ca.go, test/e2e/suite/conformance/certificates/featureset.go, test/e2e/suite/conformance/certificates/selfsigned/BUILD.bazel, test/e2e/suite/conformance/certificates/selfsigned/selfsigned.go, test/e2e/suite/conformance/certificates/suite.go, test/e2e/suite/conformance/doc.go
Adds a very simple set of conformance tests that can be run against any Issuer implementation.
Initially this covers a *very* basic set of functionality, but we can expand this suite and eventually move all issuer types to share a common set of tests 😄 
I'm still iterating on this, and opening it now to get some feedback from the e2e test job
```release-note
NONE
```
=> Add very basic Certificates based conformance suite

.bazelrc
See discussion in slack: https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1567723028023900
> Hi, I'm trying to run ./hack/ci/run-e2e-kind.sh and getting the error below.  Any clues on how to fix it best? (I tried editing Makefiles to add the --host_force_python=PY2 flag that the error suggests on every bazel build I see, but I can't manage to get it to run. (Not familiar with Bazel)
See following issues for details
* https://github.com/bazelbuild/rules_docker/issues/842
* https://github.com/bazelbuild/rules_docker/issues/580
* https://github.com/bazelbuild/bazel/issues/7899
```release-note
NONE
```
=> feat: permit running e2etests for py3 users

docs/tasks/issuers/setup-acme/dns01/google.rst
The error from gcloud is very misleading when trying to create a key for non-existing account (it tells you that you do not have the right permissions, which is actually incorrect). This documentation should inform the user to make sure the account is created first.
```release-note
```
=> Add gcloud service-account create

test/e2e/images.bzl
fixes #2077 
```release-note
NONE
```
=> Upgrade e2e test vault images to 1.2.3

deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/templates/serviceaccount.yaml, deploy/charts/cert-manager/values.yaml
Signed-off-by: Brian Hong <sungjinhong@devsisters.com>
Add service account annotation support to helm chart. In order to use AWS EKS IAM Roles for Service Accounts feature, one must annotate the service account to specify what IAM role admin wants to grant to that service account.
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
annotations:
eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME
```
This PR is a QoL patch to enable helm created service accounts to have the annotation required above.
Relates to #2048 
I've successfully …
=> Add service account annotations to helm chart

WORKSPACE, go.mod, hack/BUILD.bazel, hack/verify-codegen.sh, pkg/apis/certmanager/v1alpha2/zz_generated.deepcopy.go, pkg/internal/apis/certmanager/zz_generated.deepcopy.go, repos.bzl
Use Golang 1.13.1.
We should also make a corresponding change to bump release-0.10 to go 1.12.10 separately 😄 
```release-note
Build using Go 1.13.1
```
=> Update to use go 1.13.1

WORKSPACE
Bumps release-0.10 to use the latest Go 1.12 patch version
**Which issue this PR fixes**: fixes #2091
```release-note
Build using go 1.12.10
```
=> Bump release-0.10 to use go 1.12.10

docs/tasks/issuers/setup-vault.rst
After adding the Vault k8s auth stuff, some of the documentation examples still referenced the old API group/version.
```release-note
NONE
```
=> Correct API group on Vault setup guide

deploy/charts/cert-manager/README.md, docs/getting-started/install/kubernetes.rst, docs/getting-started/install/openshift.rst, docs/getting-started/webhook.rst, docs/tasks/issuing-certificates/index.rst, docs/tasks/upgrading/index.rst, docs/tasks/upgrading/upgrading-0.10-0.11.rst, docs/tutorials/acme/quick-start/index.rst
Adds provisional/first draft of upgrade notes for v0.11 as well as bumping version strings for alpha.0
```release-note
NONE
```
=> Add provisional upgrade notes for v0.11 & bump version strings

hack/build/BUILD.bazel
Not too sure why, but running the follow fails to govet check due to a panic in the atomicalign plugin:
```
$ bazel build --platforms=@io_bazel_rules_go//go/toolchain:linux_arm @io_k8s_apiserver//pkg/server:go_default_library
INFO: Analyzed target @io_k8s_apiserver//pkg/server:go_default_library (0 packages loaded, 10000 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_james/7efc976e92b56f94fd5066e3c9f5d356/external/io_k8s_apiserver/pkg/server/BUILD.bazel:3:1: GoCompilePkg external/io_k8s_apiserver/pkg/server/linux_arm_pure_stripped/go_default_library%/k8s.io/apiserver/pkg/server.a failed (Exit 1) builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk …
```
=> Disable atomicalign vet check due to panic on linux/arm

Makefile, hack/update-all.sh
Tidies up the Makefile in preparation to eventually remove it altogether maybe 😄 also adds an update-all.sh script which wraps up all the `hack/update-*.sh` scripts.
```release-note
NONE
```
=> Update Makefile and add update-all.sh script

docs/tasks/issuers/setup-acme/dns01/index.rst
Signed-off-by: Dan Farrell <dfarrell@doctorondemand.com>
it took me a few hours to dig out the way to set recursive nameservers in helm. This makes the process of specifying dns servers for dns validation obvious for helm users. I don't think many folks are running cert manager without helm? So the doc as written isn't very useful .
fixes #1163
I know this isn't the most obvious place to get into the helm deploy specifics but it's the obvious place to put the doc, so I hope you'll agree this is better than nothing
```release-note
NONE
```
=> how to set  --dns01-recursive-nameservers in helm

pkg/controller/cainjector/indexers.go
Signed-off-by: Ingo Gottwald <in.gottwald@gmail.com>
**What this PR does / why we need it**: Removes the use of a deprecated function.
```release-note
```
=> Remove use of deprecated client.MatchingField

deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/cainjector/values.yaml, deploy/charts/cert-manager/values.yaml
Some values were miscategorised in README.md (`global.priorityClassName`, `global.leaderElection.namespace`) while others were missing (`webhook.affinity`, etc.). `resources` was missing documented default values.
**What this PR does / why we need it**: Maintaining an accurate README helps users configure cert-manager properly.
```release-note
```
=> Fix values and README for helm chart

LICENSES, deploy/manifests/00-crds.yaml, go.mod, go.sum, hack/build/repos.bzl
Bumps our controller-tools dependency to correctly set the type/extensions for the 'raw JSON' field we have as part of the DNS01 webhook provider config.
```release-note
NONE
```
=> Update controller-tools to correctly set x-kubernetes-preserve-unknown-fields

pkg/controller/ingress-shim/sync.go, pkg/controller/ingress-shim/sync_test.go
```release-note
NONE
```
fixes #2152 
If a common name is manually added to a certificate that is managed by the ingress shim then this will ensure the certificate is updated and it is removed.
=> The ingress shim checks certificate common names and ensures they are empty

docs/tasks/upgrading/upgrading-0.10-0.11.rst
Add a bash command to help users discover Ingress resources that still have old annotations.
```release-note
NONE
```
=> Add jq bash magic to find Ingress resources with old annotations

deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/cainjector/templates/deployment.yaml, deploy/charts/cert-manager/cainjector/templates/rbac.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/rbac.yaml, deploy/charts/cert-manager/values.yaml
This changes the default leader election namespace to no longer be the same namespace as cert-manager is running within.
In practice, this has caused issues such as #2150, and potential #1948 too.
Setting this to always be kube-system unless manually overridden will mean that unless a user *explicitly* tries to run multiple copies per cluster, leader election will be performed properly.
**Which issue this PR fixes**: fixes # (potentially 1948)
We *may* want to consider backporting this to v0.10, even though it is a more substantial change that we'd normally backport. On the other hand, we should be encouraging users to upgrade regularly anyway (and v0.11 contains *further* changes to the ACME flow which should …
=> Update default leader election namespace to be kube-system

pkg/controller/certificates/BUILD.bazel, pkg/controller/certificates/controller.go, pkg/controller/certificates/sync.go, pkg/controller/certificates/sync_test.go, pkg/controller/context.go
Properly implements and tests the setting owner reference functionality on secret resources.
Thanks to @jcassee for spotting this in the beta ahead of release 🎉 
**Which issue this PR fixes**: fixes #2172 
```release-note
NONE
```
/cc @jcassee
=> Fix regression in certificates controller setting owner references

docs/getting-started/install/kubernetes.rst, docs/tasks/upgrading/index.rst
This is to avoid errors like:
```
error: error validating "https://raw.githubusercontent.com/jetstack/cert-manager/release-0.11/deploy/manifests/00-crds.yaml": error validating data: ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.solver.properties.dns01.properties.webhook.properties.config): unknown field "x-kubernetes-preserve-unknown-fields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps; if you choose to ignore these errors, turn validation off with --validate=false
```
When installing our CRD resources against a Kubernetes apiserver running 1.14 or below.
```release-note
NONE
```
=> Advise users to set --validate=false when installing with kubectl

test/e2e/framework/addon/certmanager/addon.go
As per our own installation instructions, older k8s versions require disabling kubectl validation.
```release-note
NONE
```
=> Fix e2e jobs on Kubernetes 1.14 and below

deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/values.yaml
The controller arguments `--default-acme-issuer-challenge-type` and `--default-acme-issuer-dns01-provider-name` are not available in version 0.11.
This causes the deployment pod to fail in a CrashLoopBackOff when a value was defined.
This PR removes the ability to define these deprecated arguments. 
```NONE
```
=> Remove deprecated arguments from helm chart deployment

docs/reference/issuers.rst, docs/tasks/upgrading/upgrading-0.10-0.11.rst, docs/tutorials/acme/http-validation.rst
With the 0.11 release, the deprecated `spec.http01`/`spec.dns01` syntax was removed from the `Issuer`/`ClusterIssuer` CRDs.
Update some references to the old syntax and add a note to the 0.11 upgrade doc about an error one might see if they were still using the old syntax, as was still being provided in the `Issuers` docs until this PR...
**What this PR does / why we need it**: The current examples with deprecated do not work on 0.11 at all, because the deprecated fields had been removed since 0.10.
```release-note
Fix outdated documentation for solver configuration in Issuers …
```
=> Fix documentation relating to issuer solvers

deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml
This is for supporting `kubectl --server-dry-run` feature.
It fixes #2186.
```release-note
[Kubernetes APIServer dry-run](https://kubernetes.io/docs/reference/using-api/api-concepts/#dry-run) is supported.  
```
=> Add sideEffects: None to MutatingWebhookConfiguration

deploy/charts/cert-manager/templates/rbac.yaml
This is done to give preference to the new leaderelection RoleBinding in 'kube-system'
Related to issue
Depending on which of these 2 (cluster)rolebindings are picked up by cert-manager deployment:
1. `cert-manager:leaderelection` in RoleBindings - kube-system namespace
1. `cert-manager-leaderelection` in ClusterRoleBindings
'Cert-manager' deployment either works or crashes. If 'cert-manager' deployment picks `cert-manager-leaderelection` it crashes.
My suspicion is that helm based charts are working fine because of the order of resource application in deployment.
Affects v0.11.0 release.
Related to: kubeflow/manifests#369
/cc @munnerz 
```release-note
NONE
```
=> Removes leaderelection ClusterRoleBinding

pkg/acme/BUILD.bazel, pkg/acme/helper.go, pkg/controller/acmechallenges/sync.go, pkg/controller/acmeorders/sync.go
Add additional error code checking to points where we interact with the ACME server. If at any point the server returns *any* 4xx errors, we'll mark the Order/Challenge as errored, which will in turn trigger our 'global' backoff/cooldown, which is currently a fairly naive "wait 1h before trying again" (although this *will* prevent us making requests in the order of seconds, so this is definitely a preferable patch to have 😄)
**Which issue this PR fixes**: fixes #2194
```release-note
NONE
```
=> Mark Order & Challenge resources as Errored if 4xx error is received

test/e2e/framework/addon/certmanager/BUILD.bazel, test/e2e/framework/addon/certmanager/addon.go
This should help us debug persistent Kubernetes 1.11 e2e test failures: https://testgrid.k8s.io/jetstack-cert-manager-master#cert-manager-master-e2e-v1-11&sort-by-flakiness=
```release-note
NONE
```
=> Print 'kubectl apply' output during e2e tests

pkg/issuer/acme/dns/clouddns/BUILD.bazel, pkg/issuer/acme/dns/clouddns/clouddns.go, pkg/issuer/acme/dns/clouddns/clouddns_test.go
- Replace deprecated dns.New function with dns.NewService
- Remove deprecated oauth2.NoContext
- Fix unused err value in test
Signed-off-by: Ingo Gottwald <in.gottwald@gmail.com>
**What this PR does / why we need it**: Code maintenance in the clouddns package (see above)
```release-note
NONE
```
=> Cleanup clouddns package

docs/tutorials/venafi/securing-ingress.rst
Fixes the URL for Venafi Cloud enrollment linked to in the documentation. Without this PR, users signing up for Venafi Cloud are not properly enabled for the Venafi Cloud for DevOps feature set.
```release-note
```
=> Fix the enrollment URL for Venafi Cloud.

Makefile, hack/ci/run-e2e-kind.sh
We can enable running specs twice during presubmits to help avoid disruption from flakey tests. The periodic jobs that we expose on testgrid.k8s.io will continue to run with this set to `1`, the default, so we can identify and resolve flakey test cases.
```release-note
NONE
```
=> Allow setting flakeAttempts when running e2e suite

cmd/controller/app/options/options.go
Now that we publish multi-arch manifest lists, this hackery (that could cause issues for users running homogenous clusters) can be removed :tada:
```release-note
No longer use architecture specific acmesolver images
```
=> No longer use arch-specific acmesolver image

cmd/webhook/BUILD.bazel, cmd/webhook/main.go, deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml, pkg/apis/acme/v1alpha2/types.go, pkg/internal/apis/acme/BUILD.bazel, pkg/internal/apis/acme/validation/BUILD.bazel, pkg/internal/apis/acme/validation/challenge.go, pkg/internal/apis/acme/validation/challenge_test.go, pkg/internal/apis/acme/validation/order.go, pkg/internal/apis/acme/validation/order_test.go, pkg/webhook/BUILD.bazel, pkg/webhook/certmanager.go, pkg/webhook/handlers/BUILD.bazel, pkg/webhook/handlers/interfaces.go, pkg/webhook/handlers/mutation.go, pkg/webhook/handlers/mutation_test.go, pkg/webhook/handlers/testdata/apis/testgroup/BUILD.bazel, pkg/webhook/handlers/testdata/apis/testgroup/types.go, pkg/webhook/handlers/testdata/apis/testgroup/v1/types.go, pkg/webhook/handlers/testdata/apis/testgroup/v1/zz_generated.conversion.go, pkg/webhook/handlers/testdata/apis/testgroup/validation/BUILD.bazel, pkg/webhook/handlers/testdata/apis/testgroup/validation/validation.go, pkg/webhook/handlers/testdata/apis/testgroup/validation/validation_test.go, pkg/webhook/handlers/validation.go, pkg/webhook/handlers/validation_test.go, pkg/webhook/server/server.go
Makes the following fields on Order resources immutable:
* `spec.csr`
* `status.url`
* `status.finalizeURL`
* `status.certificate`
* `status.authorizations`
* `status.authorizations[].url`
* `status.authorizations[].identifier`
* `status.authorizations[].wildcard`
* `status.authorizations[].challenges`
* `status.authorizations[].challenges[].url`
* `status.authorizations[].challenges[].type`
* `status.authorizations[].challenges[].token`
Also make the entirety of `challenge.spec` immutable after creation
This should help reduce 'fighting' between resources when users run multiple instances of cert-manager, as well as enforces an 'unwritten rule' (currently the behaviour if you change these fields after creation is ~undefined).
**Special notes for …
=> Make Order resource status & Challenge spec fields immutable

test/e2e/framework/addon/BUILD.bazel, test/e2e/framework/addon/globals.go, test/e2e/suite/conformance/certificates/acme/BUILD.bazel, test/e2e/suite/conformance/certificates/acme/acme.go, test/e2e/suite/issuers/acme/certificate/BUILD.bazel, test/e2e/suite/issuers/acme/certificate/http01.go, test/e2e/suite/issuers/acme/certificate/webhook.go, test/e2e/suite/issuers/acme/certificaterequest/BUILD.bazel, test/e2e/suite/issuers/acme/certificaterequest/http01.go
This should _hopefully_ reduce test flakes and reduce load on the e2e test cluster by not running ~60 instances of Tiller and Pebble...
```release-note
NONE
```
=> Run a single instance of Pebble during the e2e suite

deploy/charts/cert-manager/README.md
Different Documentation between Helm Chart and CertManager Documentation. Within Helm Chart Documentation the command misses the disabled validation.
fixes #2208 
```release-note
NONE
```
```
Signed-off-by: Thomas Grünert <thomas@gruenert.de>
```
=> add '--validate=false' for deploy instruction with 00-crds.yaml #2208

deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml, deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml
As per the [matching requests](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-rules) documentation, we need to opt-in to having the status subresource matched by our validating/mutating webhooks.
```release-note
Perform API resource validation of the 'status' subresource on cert-manager resources
```
/area api
=> Enable validation and mutation for subresources

hack/bin/deps.bzl, test/e2e/images.bzl
Bumps the version of Helm and Tiller used to 2.15.1, the last feature release before 3.0!
```release-note
Bump Helm & Tiller version used during end-to-end tests to 2.15.1
```
=> Bump Helm and Tiller to 2.15.1

deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/templates/webhook-service.yaml, deploy/charts/cert-manager/values.yaml
Add a `webhook.securePort` option to the Helm chart and default it to 10250 for better out of the box compatibility with GKE private clusters.
**Which issue this PR fixes**: fixes #1883 
Related #2107 
```release-note
Change the default webhook listen address to 10250 for better compatibility with GKE private clusters
```
=> Default webhook port to 10250 for better compatibility with GKE

deploy/charts/cert-manager/Chart.yaml
Add missing `apiVersion` to `Chart.yaml`.
fixes #2269
https://helm.sh/docs/developing_charts/#the-chart-yaml-file
```release-note
Add missing apiVersion to Chart.yaml
```
=> Chart.yaml: add missing apiVersion

test/e2e/framework/addon/vault/BUILD.bazel, test/e2e/framework/addon/vault/proxy.go, test/e2e/framework/addon/vault/setup.go, test/e2e/framework/addon/vault/vault.go, test/e2e/suite/conformance/certificates/vault/vault_approle.go, test/e2e/suite/issuers/vault/certificate/approle.go, test/e2e/suite/issuers/vault/certificate/approle_custom_mount.go, test/e2e/suite/issuers/vault/certificaterequest/approle.go, test/e2e/suite/issuers/vault/certificaterequest/approle_custom_mount.go, test/e2e/suite/issuers/vault/issuer.go
fixed #2226
```release-note
NONE
```
Creates a proper wrapper for the port forward for vault connections in e2e tests. This ideally eliminate flakes occurring during to relying on time.Sleep
=> Creates a proper wrapper for vault port-forwarding to keep it alive and healthy

pkg/controller/clusterissuers/checks.go
```release-note
NONE
```
fixes #2316 
=> Ensure we check all the secrets that vault cluster issuers may be

deploy/charts/cert-manager/templates/rbac.yaml, pkg/controller/acmeorders/util.go
fixes #2308
Signed-off-by: Nils Cant <nils.cant@vargen.io>
```release-note
Fix setting ownerReference on Challenge resources created by Orders controller
```
=> Correct order api group owner reference when creating challenges

deploy/charts/cert-manager/crds/clusterissuers.yaml, deploy/charts/cert-manager/crds/issuers.yaml, deploy/manifests/00-crds.yaml, docs/generated/reference/output/reference/api-docs/index.html, pkg/apis/certmanager/v1alpha2/const.go, pkg/apis/certmanager/v1alpha2/types_issuer.go, pkg/internal/vault/vault.go, test/e2e/suite/issuers/vault/issuer.go
```release-note
ACTION REQUIRED
Users who have previously set the Kubernetes Auth Mount Path will need to update their manifests to include the entire mount path. The `/login` endpoint is added for you.
Changes the Vault Kubernetes Auth Path to require the entire mount path. `/login` is added to all mount paths when authenticating.
The default auth path has now changed from `kubernetes` to `/v1/auth/kubernetes`
```
fixes #2205
=> Changes the vault issuer Kubernetes auth path to require the full *mount* path

pkg/controller/certificaterequests/vault/vault.go, test/e2e/framework/addon/vault/setup.go, test/e2e/suite/conformance/certificates/acme/acme.go, test/e2e/suite/conformance/certificates/ca/BUILD.bazel, test/e2e/suite/conformance/certificates/ca/ca.go, test/e2e/suite/conformance/certificates/selfsigned/selfsigned.go, test/e2e/suite/conformance/certificates/vault/BUILD.bazel, test/e2e/suite/conformance/certificates/vault/vault_approle.go, test/e2e/suite/conformance/certificates/venafi/BUILD.bazel, test/e2e/suite/conformance/certificates/venafi/venafi.go, test/e2e/suite/issuers/vault/certificate/BUILD.bazel, test/e2e/suite/issuers/vault/certificate/approle.go, test/e2e/suite/issuers/vault/certificate/approle_custom_mount.go, test/e2e/suite/issuers/vault/certificaterequest/BUILD.bazel, test/e2e/suite/issuers/vault/certificaterequest/approle.go, test/e2e/suite/issuers/vault/certificaterequest/approle_custom_mount.go, test/e2e/suite/issuers/vault/issuer.go, test/e2e/suite/issuers/venafi/addon/tpp.go, test/e2e/util/util.go
fixes #2231 
Points the vault client to the correct secret when using a cluster issuer. Previously it used the same namespace as the CertificateRequest which has now been changed to the cluster resource namespace (kube-system)
```release-note
NONE
```
=> Make vault issuer to point to resource namespace over certificaterequest

Makefile, cmd/acmesolver/BUILD.bazel, cmd/cainjector/BUILD.bazel, cmd/controller/BUILD.bazel, cmd/controller/app/controller.go, cmd/controller/main.go, cmd/webhook/BUILD.bazel, hack/build/docker.bzl, pkg/util/BUILD.bazel, pkg/util/coverage/BUILD.bazel, pkg/util/coverage/coverage.go, pkg/util/coverage/faketestdeps.go
This allows us to build binaries that can be used for gathering coverage data during end-to-end tests.
A later PR will actually wire up the e2e framework to use these images and gather the coverage results from pods.
**Which issue this PR fixes**: fixes #
You can build a binary to test this using:
```shell
bazel run //cmd/controller:image.covered --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 --collect_code_coverage --instrumentation_filter='^//'
```
Then running with something like:
```shell
docker run -v $(pwd)/coverprofiles:/cover -e COVERPROFILE=/cover/cm.cover -v $HOME/.kube:/.kube bazel/cmd/controller:image.covered
```
```release-note
Fix bug causing SIGTERM and SIGINT signals to …
```
=>  Add Bazel image targets with coverage enabled

deploy/charts/cert-manager/templates/rbac.yaml
fixes: #2305
Signed-off-by: Nils Cant <nils.cant@vargen.io>
```release-note
Fix issue causing certificates not to be issued when running with `OwnerReferencesPermissionEnforcement` admission controller enabled
```
=> Add update permission to certificaterequests/finalizers to the cert-manager-controller-certificates clusterrole.

deploy/charts/cert-manager/crds/certificaterequests.yaml, deploy/manifests/00-crds.yaml, design/20190708.certificate-request-crd.md, pkg/apis/certmanager/v1alpha2/types_certificaterequest.go, pkg/internal/apis/certmanager/types_certificaterequest.go
This field is currently marked as required by our validating webhook, but not by our CRD schema.
This should be safe to do, as:
1) it was required anyway
2) very few users manually create CertificateRequest resources
```release-note
Mark `certificaterequest.spec.csr` field as required in OpenAPI schema
```
=> Mark 'csr' field as required in CertificateRequest

deploy/charts/cert-manager/templates/webhook-psp-clusterrole.yaml, deploy/charts/cert-manager/templates/webhook-psp-clusterrolebinding.yaml, deploy/charts/cert-manager/templates/webhook-psp.yaml
Fixes issues with Pod Security Policies that prevent the cert-manager and cert-manager-webhook containers from running if Pod Security Policies are enabled
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2221 
```
Fixes issues with Pod Security Policies that prevented pods from running when Pod Security Policy is enabled in Kubernetes
```
=> Fixes for PSP Issues

pkg/apis/meta/v1/doc.go
This _should_ allow us to generate reference docs using this patch in `gen-crd-api-reference-docs`: https://github.com/munnerz/gen-crd-api-reference-docs/commit/60e15c17c527d79dbb88deb8e4e39a37cc517154
```release-note
NONE
```
=> Add '// +gencrdrefdocs:force' to meta/v1 package

pkg/apis/acme/v1alpha2/doc.go, pkg/apis/certmanager/v1alpha2/doc.go, pkg/apis/meta/v1/doc.go
Follows up on #2372 
```release-note
NONE
```
=> Fix up whitespace around doc.go in apis package

deploy/charts/cert-manager/templates/webhook-psp.yaml
It fixes the typo that prevents helm chart to be used with psp enabled.
This kind of issue might be detected early in the future by enabling psp
in e2e tests (https://github.com/jetstack/cert-manager/pull/2280).
A similar bug was already fixed in
be0b865522e9d876b81155790996a2ea1e37a893.
**Which issue this PR fixes** : fixes #2386
```release-note
NONE
```
=> deploy/charts/cert-manager: Fixes typo in webhook-psp definition

pkg/apis/certmanager/v1alpha2/types.go, pkg/controller/certificates/sync.go, pkg/controller/certificates/util.go, pkg/controller/certificates/util_test.go, test/unit/gen/BUILD.bazel, test/unit/gen/secret.go
This PR allows the certificate controller to accept a secret matches its spec if the secret is using legacy issuer annotations.
This is to ensure that during the upgrade process to 0.11, not all certificates are reissued due to the current Secret resources having the old annotations.
```release-note
Allow permissive acceptance for matching Certificates with Secrets that are using legacy annotations to reduce non-required certificate reissue. 
```
/cherry-pick release-0.11
=> Allow secrets with legacy annotations for issuer name and kind to match

pkg/apis/certmanager/v1alpha2/types.go, pkg/controller/certificates/sync.go, pkg/controller/certificates/util.go, pkg/controller/certificates/util_test.go, test/unit/gen/BUILD.bazel, test/unit/gen/secret.go
```release-note
Ensure secrets using deprecated secret annotations does not cause unneeded re-issuance 
```
=> Release 0.11 secret annotation deprecated

deploy/charts/cert-manager/templates/deployment.yaml
I added an explicit definition of the ContainerPort protocol in the helm chart.
The server-side apply beta currently complains when the cert-manager manifest is applied as-is, because it needs a ContainerPort protocol to resolve conflicts:
```
$ kubectl apply -f cert-manager.yml --server-side
failed to create typed patch object: .spec.template.spec.containers[name="cert-manager"].ports: element 0: associative list with keys has an element that omits key field "protocol"
```
This resolves it by adding that field.
```release-note
Explicitly define ContainerPort protocol in helm chart
```
=> deploy/charts/cert-manager: explicitly define ContainerPort protocol

docs/tasks/upgrading/upgrading-0.10-0.11.rst
Signed-off-by: Luke Reed <luke@lreed.net>
The documentation for 0.11 upgrade includes a link that 404s. I adjusted the link to point to the 11.0 release artifact for api-migration
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: I could not find an issue or PR already opened for this. Happy to open one if necessary.
```release-note
NONE
```
=> correcting upgrade docs as the 11.1 release does not include an api-migration artifact

test/e2e/images.bzl
Upgrades to the latest version of Pebble, including letsencrypt/pebble#294 in order to fix issues with redirect tests.
```release-note
NONE
```
=> Upgrade to Pebble containing letsencrypt/pebble#294

pkg/controller/certificates/sync.go, pkg/controller/certificates/util.go
In v0.11, we accidentally removed the line of code that recorded the expiry time metric for certificate resources due to the switch over to the new certificate request based implementation. This PR adds it back in.
**Which issue this PR fixes**: fixes #2266 
```release-note
Fix `certmanager_certificate_expiration_timestamp_seconds` metric recording
```
/kind bug
/area monitoring
=> Fix certificate controller expiry metrics

cmd/webhook/main.go, pkg/util/BUILD.bazel, pkg/util/profiling/BUILD.bazel, pkg/util/profiling/profiling.go, pkg/webhook/server/BUILD.bazel, pkg/webhook/server/server.go
Register HTTP pprof handlers to make it easier to debug issues such as #2445 by grabbing running `go tool pprof`.
```release-note
webhook: register http handlers for pprof debug endpoints
```
=> webhook: register http handlers for pprof debug endpoints

deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/values.yaml
**What this PR does / why we need it**: Adds support for cert-manager deployments annotations in the chart
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2443
```release-note
Adds support for chart configurable parameters  `deploymentAnnotations`, `webhook.deploymentAnnotations` and `cainjector.deploymentAnnotations`
```
=> issue 2443 - annotations for cert-manager deployments

deploy/charts/cert-manager/README.md
I think the default value of `image.tag` is now `v0.12.0`, corrected `README.md`
none
Just a small change in `README.md`
not needed
=> Bump default 'image.tag' value in helm chart README.md

cmd/controller/app/options/options.go
Remove the requirement that the `--dns01-recursive-nameservers` option must be specified as IP address.
We're issuing a certificate to be used on a cluster running in a VPC with a private DNS zone in AWS. There's also a public zone for the domain, and we write the DNS01 challenge records to that zone so that Let's Encrypt can see them. However, inside the VPC, the records in the public zone don't resolve using the default nameserver, because AWS has intercepted the request and attempted to resolve them in the private zone. cert-manager then spins waiting for them to resolve.
We fixed this by specifying the nameservers of the public zone, i.e. `--dns01-recursive-nameservers=ns-1234.awsdns-56.co.uk:53,ns-789.awsdns-10.org:53,ns-11.awsdns-12.com:53,ns-1 …
=> Remove IP address validation on dns01-recursive-nameservers to allow domain names

pkg/webhook/server/tls_file_source.go
As per the comment on the Golang `time.Tick` function:
```
// Tick is a convenience wrapper for NewTicker providing access to the ticking
// channel only. While Tick is useful for clients that have no need to shut down
// the Ticker, be aware that without a way to shut it down the underlying
// Ticker cannot be recovered by the garbage collector; it "leaks".
```
We were previously calling this function in a `for` loop that by default, ticked every 10s. This means that over time, this resource 'leaks' thus causing an increase in CPU usage.
I was specifically tipped off that this may be the case through [this](https://stackoverflow.com/a/59242611) stackoverflow comment!
**Which issue this PR fixes**: fixes #2445  …
=> webhook: don't use time.Tick to prevent leaks

pkg/util/kube/BUILD.bazel, pkg/util/kube/pki.go
These functions are re-used in many places across the codebase and all handle their own logging - in a lot of instances, the error messages are suppressed by 'IsInvalidData' and 'IsNotFound' matches, as these types of errors are 'expected' and handled appropriately (i.e. by then attempting to issue the certificate).
Right now they are unconditionally logged, even if they are then later handled by the call-site.
```release-note
Remove misleading 'error decoding x509 certificate' message
```
=> Don't log misleading error messages

deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/templates/cainjector-psp.yaml, deploy/charts/cert-manager/templates/psp.yaml, deploy/charts/cert-manager/templates/webhook-psp.yaml, deploy/charts/cert-manager/values.yaml
Fixes #2293
It fixes #2293 
The helm chart now allows to configure whether Apparmor should be used or not.
It is done in the same way, as it is implemented for grafana:
https://github.com/helm/charts/blob/master/stable/grafana/templates/podsecuritypolicy.yaml#L15
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2293 
```
It is now possible to disable Apparmor when PSPs are used.
```
=> Add configuration switch for use of apparmor in PSP

deploy/charts/cert-manager/templates/rbac.yaml
Similar to the other `ClusterRoleBinding` serviceAccount references this PR aims to set the serviceAccount for the `RoleBinding` for the leaderelection role to use the `{{ template "cert-manager.serviceAccountName" . }}` reference instead of `{{ include "cert-manager.fullname" . }}`. This way if a user is referencing an existing `serviceAccount` for their helm deployment like so:
```yaml
...
serviceAccount:
create: false
name: my-custom-name
...
```
the rolebinding will correctly bind to the right `serviceAccount`.
If this is not done and a user sets the above config for their `values.yaml` then the `RoleBinding` will refer to an unknown `serviceAccount`.
```release-note
Fix invalid service …
```
=> updating serviceAccount reference in leaderelection rolebinding

pkg/api/util/BUILD.bazel, pkg/api/util/names.go, pkg/api/util/names_test.go
This strips any symbols at the end of a shortened domain name in ComputeCertificateRequestName.
It also adds tests for the specific util function.
This strips non allowed characters from the end of the certificate name that may be there when a string gets shortened to 52 characters to fit the allowed character limit.
fixes #2505
I added tests to this package, they weren't any not sure if there is a decision for that that I missed..
```release-note
Fixes generation if invalid certificate name the the 52nd character in a domain name is a …
```
=> Fix issue in ComputeCertificateRequestName when 52nd is a dot

deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/values.yaml
Signed-off-by: Joshua Stern <joshua.stern@appian.com>
The purpose of this PR is to add support for volumes and volume mounts in the cert-manager chart by adding the appropriate fields to the helm chart values file. This will allow for the use of AWS IAM roles for cert-manager service accounts (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)
```
Add volume and volume mounts field to cert-manager helm chart
```
=> Add support for volumes and volume mounts to cert-manager chart

pkg/controller/certificaterequests/venafi/venafi.go
This resolves venafi sign requests not being able to use clusterissuers by only looking in the 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2457
```release-note
Fixes ClusterIssuers not finding the secret when the secret is in a different namespace than the certificate request
```
=> Fix clusterissuer not being able to provision certs

LICENSES, go.mod, go.sum, hack/build/repos.bzl
removes the need of Bazaar by updating github.com/digitalocean/godo to v1.29.0
- Updates github.com/digitalocean/godo to v1.29.0.
- Reduces unnecessary dependencies.
- Evaporates bzr from installation process.
**Which issue this PR fixes** : 
fixes #2432 
It is one of my first PRs, so please let me know if I can improve something.
```
fix: removes the need of Bazaar by updating github.com/digitalocean/godo to v1.29.0 Fixes issue #2432
```
=> fix: removes the need of Bazaar by updating github.com/digitalocean/godo to v1.29.0 Fixes issue #2432

pkg/controller/certificaterequests/acme/BUILD.bazel, pkg/controller/certificaterequests/acme/acme.go, pkg/controller/certificates/sync.go
Due to the way the ACME CertificateRequest controller fetches the Order it creates by hashing the input parameters on the CertificateRequest resource ([here](https://github.com/jetstack/cert-manager/blob/6d9200f9d32aa158fe600ff4d0883763840b1e71/pkg/controller/certificaterequests/acme/acme.go#L119)), in certain edge cases the CR controller can fetch an Order that has been created by a different private/public key to that of the CSR stored in the CertificateRequest.
This is because the `hashOrder` function does not account for the public key or any other parameters on the Order, instead relying on the Order's `spec`.
We should investigate a refactor to avoid this kind of hashing and resource naming in future so we can properly avoid cases of it …
=> Ensure fetched certificate is valid for CSRs public key before issuing

deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/cainjector-psp-clusterrole.yaml, deploy/charts/cert-manager/templates/cainjector-psp-clusterrolebinding.yaml, deploy/charts/cert-manager/templates/cainjector-psp.yaml, deploy/charts/cert-manager/templates/cainjector-rbac.yaml, deploy/charts/cert-manager/templates/cainjector-serviceaccount.yaml, deploy/charts/cert-manager/values.yaml
cainjector previously disregarded the cainjector.enabled
value when passed in.  This commit leaves it defaulted to
enabled (per the docs) but causes cainjector to not be
deployed when cainjector.enabled = false.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2503 
It looks like there might be some magic in play for Chart version number incrementing. I'm not sure whether I need to do anything further!
```release-note
Fix cainjector.enabled=False override being ignored by the Helm Chart
```
=> Fix Helm chart cainjector.enabled

pkg/issuer/acme/http/http.go
Corrects the GVK of the OwnerReference set on resources created by the HTTP01 challenge solver.
Since moving the Challenge resource to a new API group, this bug went unnoticed.
**Which issue this PR fixes**: fixes #2475
```release-note
Fix GroupVersionKind set on OwnerReference of resources created by HTTP01 challenge solver, causing HTTP01 validations to fail on OpenShift 4.x
```
/cherrypick release-0.13
=> Fix ownerReference GVK used during HTTP01 challenge solving

cmd/webhook/main.go, devel/BUILD.bazel, pkg/webhook/server/BUILD.bazel, pkg/webhook/server/server.go
Add a --tls-cipher-suites command line flag and set to sensible
defaults.
fixes #2559
```release-note
Added --tls-cipher-suites command line flag to the webhook binary with sensible defaults
```
=> Add cipher suites configuration and defaults

pkg/internal/apis/acme/types_challenge.go, pkg/internal/apis/acme/types_issuer.go, pkg/internal/apis/acme/types_order.go, pkg/internal/apis/certmanager/types.go, pkg/internal/apis/certmanager/types_certificate.go, pkg/internal/apis/certmanager/types_certificaterequest.go, pkg/internal/apis/certmanager/types_issuer.go, pkg/internal/apis/meta/types.go
These structures are never serialised or deserialised and are only used as the basis for conversion and certain types of validation.
The struct tags should be present on the internal types to reflect this, and the kubebuilder annotations are misleading as they are ignored here 😄 
```release-note
NONE
```
/kind cleanup
/area api
=> Remove json field tags from internal API structs

deploy/charts/cert-manager/crds/clusterissuers.yaml, deploy/charts/cert-manager/crds/issuers.yaml, deploy/manifests/00-crds.yaml, pkg/apis/certmanager/v1alpha2/types_issuer.go, pkg/apis/certmanager/v1alpha3/types_issuer.go, pkg/internal/apis/certmanager/types_issuer.go
This value is defaulted by the Venafi client as-per https://github.com/Venafi/vcert/blob/d4d4df569eec07f98bda84e99f8813a51d7f4650/config.go#L35-L36
I've avoided defaulting this value in order to prevent leaking implementation details of the Venafi client up to the API surface (i.e. if the default URL changes)
```release-note
Fix Venafi Cloud URL field being marked required
```
=> Make the Venafi Cloud URL field optional

devel/ci-run-e2e.sh, devel/cluster/export-logs.sh
This PR adds back exporting cert-manager logs to artifacts or CI runs but also included logs of all other components.
```release-note
NONE
```
=> Exports cluster logs to artifacts after CI run

pkg/controller/builder.go, pkg/controller/controller.go, pkg/controller/webhookbootstrap/BUILD.bazel, pkg/controller/webhookbootstrap/controller.go, pkg/controller/webhookbootstrap/controller_test.go
In the current implementation of the webhook boot strap controller, it relies on creating empty secrets in order to reconcile over those secrets in the main loop. Creating empty Secrets causes issues further upstream where mounting fails on the webhook pod and therefore can significantly increase the start time.
This PR changes this behavior by manually adding the target secrets at boot time, even though they do not yet exist. The controller is able to either create or update the target Secret, depending on whether it exists. The controller will also only atomically create/update the secret with the private key _and_ signed certificate.
This PR adds a `First` func to controllers which are able to register functions that will be run after the …
=> Webhook cert bootsrap single reconcile

deploy/manifests/BUILD.bazel
As part of the new release tooling changes, we forgot to include a copy of the CRDs in the generated 'static manifests'.
This updates the files we generate to include the `00-crds.yaml` file.
This PR currently enables the conversion webhook for CRDs even in the `no-webhook` variant, which won't work. @meyskens upcoming PR to move the CRDs into a Helm chart so we can template out these areas should fix this 😄 
```release-note
NONE
```
=> Fix including CRDs as part of static manifests

devel/ci-run-e2e.sh
```release-note
NONE
```
This will ensure that logs are exported, regardless whether tests succeeded.
=> Export cluster logs during e2e even if test succeed

deploy/charts/cert-manager/crds/certificates.yaml, deploy/manifests/00-crds.yaml, pkg/apis/certmanager/v1alpha2/types_certificate.go, pkg/apis/certmanager/v1alpha3/types_certificate.go, pkg/internal/apis/certmanager/validation/certificate.go, pkg/internal/apis/certmanager/validation/certificate_test.go
Adds open API validation for maximum and minimum values for KeySize
```release-note
NONE
```
=> Certificate KeySize encode openapi validation

pkg/controller/ingress-shim/sync.go, pkg/controller/ingress-shim/sync_test.go
If a user creates an Ingress resource that has multiple `tls` entries that point to the same secret name but with a different set of domains, the controller will fight with itself and continuously update the Certificate resource it manages, causing Orders etc. to be recreated rapidly.
This can cause API quotas to be quickly used up, general cluster instability through excessive API calls, and will result in the Certificate issuance never completing.
fixes #2342
```release-note
Fix bug in ingress-shim causing Certificate resources to be rapidly updated if multiple `spec.tls[].hosts` entries refer to the same Secret name but a different set of hosts
```
/kind bug
/area ingress-shim
/milestone v0.13
=> Only allow a single TLS entry per secret name in an Ingress resource

deploy/manifests/BUILD.bazel
When building with the `--platforms` flag, it's important we correctly categorise `src` vs `tool` dependencies as it indicates to Bazel where this will be run. *tool* dependencies will be built for the *host architecture*, whereas `src` dependencies will be built for the *target architecture*.
Without this change, building the release-tars target for a different arch to the host results in:
```/bin/bash: bazel-out/k8-fastbuild/bin/hack/filter-crd/linux_arm_pure_stripped/filter-crd: cannot execute binary file: Exec format error```
```release-note
NONE
```
=> Mark filter-crd target as a tool dependency instead of src

deploy/charts/cert-manager/crds/certificates.yaml, deploy/manifests/00-crds.yaml, pkg/apis/certmanager/v1alpha2/types_certificate.go, pkg/apis/certmanager/v1alpha2/zz_generated.deepcopy.go, pkg/apis/certmanager/v1alpha3/types_certificate.go, pkg/apis/certmanager/v1alpha3/zz_generated.deepcopy.go, pkg/controller/webhookbootstrap/controller.go, pkg/internal/apis/certmanager/types_certificate.go, pkg/internal/apis/certmanager/v1alpha2/zz_generated.conversion.go, pkg/internal/apis/certmanager/v1alpha3/zz_generated.conversion.go, pkg/internal/apis/certmanager/validation/certificate.go, pkg/internal/apis/certmanager/validation/certificate_test.go, pkg/internal/apis/certmanager/zz_generated.deepcopy.go, pkg/util/pki/csr.go, test/e2e/framework/helper/certificates.go, test/e2e/suite/conformance/certificates/acme/acme.go, test/e2e/suite/conformance/certificates/featureset.go, test/e2e/suite/conformance/certificates/suite.go
This adds the Email SAN option to the Certificate resource.
Fixes #1356
This needs more tests
```release-note
Add emailSANs field to Certificate resource
```
=> Add Email SANs

LICENSES, cmd/controller/app/options/options.go, go.mod, go.sum, pkg/controller/certificates/BUILD.bazel, pkg/controller/certificates/controller.go, pkg/controller/certificates/keystore.go, pkg/controller/certificates/sync.go, pkg/controller/context.go
This PR adds a new experimental flag to enable generating PKCS12 bundles in 'target secrets'.
This flag will be replaced with native support for PKCS12 bundles in future, once #2402 has been implemented.
**Which issue this PR fixes**: part of #586 
```release-note
Add `--experimental-issue-pkcs12` flag to enable PKCS12 bundle generation in generated Secret resources. This flag will be replaced with native support for PKCS12 bundles in future and is currently an experimental feature. If enabled, the `--experimental-pkcs12-keystore-password` flag must also be set to the password used to encrypt PKCS12 bundles.
```
/cc @JoshVanL
=> Add --experimental-issue-pkcs12 flag to enable PKCS12 bundle generation

deploy/charts/cert-manager/templates/rbac.yaml, deploy/charts/cert-manager/values.yaml, deploy/manifests/BUILD.bazel
This removes the `isOpenShift` from the Helm Chart, this enables all manifests to have a copy of the OpenShift specific RBACs so OpenShift 4 users can use the main version.
Phase 1 of #2639 
```release-note
Remove `isOpenShift` from Helm chart
```
=> Put OpenShift specific RBAC in all manifests

deploy/manifests/BUILD.bazel, hack/filter-crd/main.go
This releases a new manifest type "legacy" to support Kubernetes <1.15 and OpenShift 3.
This version uses the webhook but disables the conversions as they are not supported.
For this reason only the v1alpha2 API is added in these manifests.
All newer APIs are filtered by the filter-crd tool.
Fixes #2639 
```release-note
Replace openshift/no-webhook manifest variants with a "legacy" variant
```
=> Replace openshift/no-webhook manifests with legacy

deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml, deploy/charts/cert-manager/templates/webhook-rbac.yaml, deploy/charts/cert-manager/templates/webhook-service.yaml, deploy/charts/cert-manager/templates/webhook-serviceaccount.yaml, deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml, deploy/charts/cert-manager/values.yaml
This removes the Webhook.enabled option from the Helm chart as we no longer ship a no-webhook version.
This is kind of up for debate if we want to keep it in the chart or not as we removed it from the manifest releases.
```release-note
Remove `webhook.enabled` variable in Helm chart as the webhook now is a required component
```
=> Remove webhook.enabled from Helm chart

pkg/webhook/handlers/BUILD.bazel, pkg/webhook/handlers/conversion.go, pkg/webhook/handlers/mutation.go
This prevents log messages being generated during normal operation of the webhook. If we want to see this information, we can increase our `--v` level temporarily 😄 
```release-note
NONE
```
=> webhook: don't log messages during normal operation

build/BUILD.bazel, build/container.bzl, build/release-tars/BUILD.bazel
This fixes running `bazel build //...` on macOS.
```release-note
NONE
```
=> Mark all build/ targets as manual

deploy/charts/cert-manager/BUILD.bazel, deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml, deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml, devel/addon/certmanager/install.sh, devel/cluster/create.sh, devel/lib/lib.sh, hack/filter-crd/main.go
Our periodic end-to-end jobs have been failing against Kubernetes 1.14 and below for a little while now since we introduced the `preserveUnknownFields` flag.
This PR attempts to fix these test failures. It may need reworking to make use of the newly introduced "legacy" installation manifests, but seeing if this is sufficient for now.
```release-note
NONE
```
=> Fix end-to-end tests running against Kubernetes 1.14 and below

deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml, deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml
Adds a condition in the chart that avoids setting the 'sideEffects' field on Validating and Mutating webhooks if the Kubernetes version is less than 1.12.
We don't officially support Kubernetes 1.11, but given it's quite easy for us to include this gate I think we should, and it means users installing with Helm onto older k8s versions will have it 'just work'.
The `legacy` variant of the static manifests *will* include the `sideEffects` field still, as it is a field that *is* useful for users of 1.12-1.14, and these users can avoid warnings by setting `--validate=false` on the `kubectl create` command.
```release-note
NONE
```
/kind cleanup
/area deploy
=> Only include the 'sideEffects' field on webhooks in Kubernetes 1.12+

deploy/manifests/BUILD.bazel
Includes the generated CRD manifest file as part of the artifacts published to GitHub in releases.
This can be used in favour of the `00-crds.yaml` file linked in the repository, and we should look at removing the `00-crds.yaml` file in future 😄
**Which issue this PR fixes**: fixes #2660 
```release-note
Replace `00-crds.yaml` file with a manifest file published as part of the release
```
=> Include CRDs as part of release assets published to GitHub

test/e2e/suite/issuers/acme/certificate/webhook.go
Increases the timeout for the DNS01 sample webhook tests. I suspect that the fixed 60s `ttl` value in the DNS01 challenge provider is causing the challenges controller to be blocked for up to 60s at a time, meaning that the Challenge resource is not being processed in time in some cases. Repeated testing locally shows that this test consistently passes when run in isolation.
**Which issue this PR fixes**: fixes #2671
We should also investigate ways to make this 60s ttl asynchronous, or otherwise remodel it in a way that does not allow a DoS through creating many challenges at once.
```release-note
NONE
```
/kind flake
/area testing
=> Increase timeout for sample DNS01 webhook e2e tests

build/helm.bzl
Gets rid of all this unhelpful output when building the Helm package via Bazel:
```
walk.go:74: found symbolic link in path: /private/var/tmp/_bazel_james/7efc976e92b56f94fd5066e3c9f5d356/sandbox/darwin-sandbox/3642/execroot/com_github_jetstack_cert_manager/deploy/charts/cert-manager/.helmignore resolves to /Users/james/go/src/github.com/jetstack/cert-manager/deploy/charts/cert-manager/.helmignore
walk.go:74: found symbolic link in path: /private/var/tmp/_bazel_james/7efc976e92b56f94fd5066e3c9f5d356/sandbox/darwin-sandbox/3642/execroot/com_github_jetstack_cert_manager/deploy/charts/cert-manager/Chart.yaml resolves to /Users/james/go/src/github.com/jetstack/cert-manager/deploy/charts/cert-manager/Chart.yaml
walk.go:74: found symbolic link in path: …
```
=> Silence helm package output when building chart

go.mod, go.sum, hack/build/repos.bzl
We need to bump our dependency on vcert in order to support custom fields in TPP 19.2.
I'm not actually certain that this revision includes this patch as I can't find a PR that *looks* relevant/related, so for the time being and for safeties sake, I have bumped us now in the hopes it is just hidden in some recent PRs 😅 
```release-note
Bump Venafi/vcert dependency to support custom fields in Venafi TPP 19.2
```
/kind cleanup
=> Bump vcert to v4.9.3

test/e2e/framework/framework.go, test/e2e/suite/issuers/ca/certificaterequest.go, test/e2e/suite/issuers/selfsigned/certificaterequest.go, test/e2e/suite/issuers/vault/certificaterequest/approle.go
fixes #2672 
This PR adds a duration fuzz to the CertificateRequest Vault AppRole e2e test. This is because Vault can sometimes issue certificates that are off by a second or so for the duration. This PR should reduce the flakes we are seeing :crossed_fingers: 
```release-note
NONE
```
=> Adds a duration gap for the app role Vault e2e issuer test

build/licensing.bzl, deploy/manifests/BUILD.bazel, hack/boilerplate/BUILD.bazel
Includes the license boilerplate header inside the release manifests we publish alongside a GitHub release.
**Which issue this PR fixes**: fixes #2645, fixes #2677
```release-note
Include license header in manifests attached to GitHub releases
```
/area deploy
/kind cleanup
=> Automatically prepend license boilerplate header to release manifests

BUILD.bazel, cmd/webhook/BUILD.bazel, cmd/webhook/app/BUILD.bazel, cmd/webhook/app/options/BUILD.bazel, cmd/webhook/app/options/options.go, cmd/webhook/app/testing/BUILD.bazel, cmd/webhook/app/testing/testwebhook.go, cmd/webhook/app/webhook.go, cmd/webhook/main.go, deploy/charts/cert-manager/BUILD.bazel, deploy/charts/cert-manager/crds/BUILD.bazel, hack/bin/BUILD.bazel, hack/bin/deps.bzl, hack/update-crds.sh, test/integration/BUILD.bazel, test/integration/conversion/BUILD.bazel, test/integration/conversion/conversion_test.go, test/integration/framework/BUILD.bazel, test/integration/framework/apiserver.go, test/integration/framework/paths.go
This PR adds an integration testing framework to make it easier for us to test functionality implemented either via our CRD resource's OpenAPI schemas or implemented as part of the webhook component.
It brings up a Kubernetes API server and an instance of etcd using controller-runtime's `envtest` package, as well as running the webhook component in-memory and configuring the CRDs to use the webhook for conversion.
In a future PR, we should also configure a Validating & Mutating webhook here too, to allow us to test functionality implemented there.
Integration tests won't be a replacement for unit tests by any means, but they provide a valuables means to test isolated but composed together bits of the system (i.e. API related things, or even certain …
=> Add integration testing framework with a basic conversion test

BUILD.bazel, build/container.bzl, devel/addon/certmanager/BUILD.bazel, test/e2e/BUILD.bazel
Fixes up after #2708 merged accidentally due to the issue fixed by https://github.com/jetstack/testing/pull/358
```release-note
NONE
```
/kind cleanup
/area deploy
=> Fixup bazel build

pkg/acme/client/middleware/logger.go
/area acme
Set acme client context deadline to 10 seconds as well as wraps the controller context to be more cleaner.
```release-note
NONE
```
=> Sets ACME client context to 10s and wraps controller ctx

deploy/charts/cert-manager/crds/challenges.yaml, deploy/charts/cert-manager/crds/clusterissuers.yaml, deploy/charts/cert-manager/crds/issuers.yaml, deploy/manifests/00-crds.yaml, pkg/apis/acme/v1alpha2/types_issuer.go, pkg/apis/acme/v1alpha3/types_issuer.go, pkg/internal/apis/acme/types_issuer.go, pkg/internal/apis/certmanager/validation/issuer.go, pkg/internal/apis/certmanager/validation/issuer_test.go, pkg/internal/apis/certmanager/validation/util/nameserver.go, pkg/issuer/acme/dns/rfc2136/rfc2136_test.go
Add support for FQDN, “hostname” and IPv6 address in Issuer's and ClusterIssuer's `spec.acme.solvers[].dns01.rfc2136.nameserver`
Fixes #2440 
The `ValidNameserver` doesn’t check for a valid IP anymore, it now accepts any arbitrary string.
```release-note
`nameserver` field in RFC2136 providers now supports hostname, FQDN, and IPv6 address in addition to IPv4 address.
```
=> Allow setting FQDN, hostname or IPv6 address in RFC2136 nameserver

WORKSPACE
Bumps Go version to 1.14.1: https://groups.google.com/forum/#!msg/golang-announce/Ix2U_8WWmXo/a2nJkNW5AAAJ
```release-note
Bump Go version to 1.14.1
```
/kind cleanup
=> Bump Go version to 1.14.1

cmd/controller/app/controller.go, pkg/controller/certificaterequests/sync_test.go, pkg/controller/certificates/BUILD.bazel, pkg/controller/certificates/controller.go, pkg/controller/certificates/keystore.go, pkg/controller/certificates/keystore_test.go, pkg/util/pki/parse.go
The JKS library uses a `map[string]interface{}` for the `KeyStore` type and we incorrectly used non-pointer structures as that `interface{}`, which caused the underlying JKS library to fail to encode the JKS bundles.
This PR fixes that, and adds tests to catch it.
I've also updated the controller instantiation code to correctly pass the values for the flags down to this area of the code, which is what caused the `keystore.p12` file to not be created either (as reported in #2702)
**Which issue this PR fixes**: fixes #2702
```release-note
Fix bug causing the experimental PKCS12 and JKS keystore feature to not work
```
/kind bug
/cherrypick release-0.14
=> Fix JKS keystore functionality and add additional tests

pkg/acme/client/middleware/logger.go
Cherrypick of #2713 and #2714 - this updates our ACME client to have a fixed 10s context deadline, which should avoid situations where we can block forever due to long `retry-after` responses returned from the ACME server.
```release-note
Fix issue that could cause the ACME client to block for extended periods when the server responds with a long `retry-after` header, causing cert-manager to not process new orders or challenges.
```
/kind bug
/area acme
=> cherrypick: set context deadline on ACME client calls

deploy/charts/cert-manager/templates/deployment.yaml
We were using the incorrect service name as part of the `--webhook-dns-names` flag. This means that if a user customised the `--name` of the Helm release, the webhook certificate will be signed with an incorrect DNS name.
This results in errors such as:
```
failed to create resource: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.sre.svc:443/mutate?timeout=30s: x509: certificate is valid for acme-cert-manager-webhook, acme-cert-manager-webhook.sre, acme-cert-manager-webhook.sre.svc, not cert-manager-webhook.sre.svc
```
**Which issue this PR fixes**: fixes #2732
```release-note
Fix incorrect service name being used in the --webhook-dns-names flag
``` …
=> Use correct service name in the --webhook-dns-names flag

README.md, deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/templates/NOTES.txt, deploy/manifests/README.md
This tidies up the Helm chart's README (which is displayed on the Helm Hub) to include proper information on the legacy manifests (in-line with the installation guide).
At the same time, I updated the URLs to point to the correct ones on the new website (there are redirects in place for these URLs anyway, but this is good to do 😄).
```release-note
Update Helm chart README to properly explain legacy manifests
```
/area deploy
/cherrypick release-0.14
=> Update Helm chart & other docs with new URLs and info

pkg/controller/webhookbootstrap/controller.go, pkg/controller/webhookbootstrap/controller_test.go
Previously we'd always run a Create, and if this responds with `IsAlreadyExists`, we'd attempt an Update instead. This does not work in some cases, as an error "resourceVersion must not be set on Create calls" can be returned.
This changes the way we detect if something should be created to instead inspect the `resourceVersion` field, which will *always* be non-empty if an Update is to be performed.
```release-note
Fix bug that could cause the `webhookbootstrap` controller to fail to Update webhook TLS resources in certain cases
```
/kind bug
=> webhookbootstrap: fix updating Secret resources

deploy/charts/cert-manager/BUILD.bazel, deploy/charts/cert-manager/README.template.md
This updates our build tooling to automatically add the release version into the Helm chart README to avoid us having to manually bump this for each release 😄 
As part of this change, I've also renamed `README.md` to be `README.template.md`. This has the side-effect of making it not appear on GitHub when a user browses to `deploy/charts/cert-manager`, however, users shouldn't be viewing the chart at this location anyway (and instead should look at the Helm Hub: https://hub.helm.sh/charts/jetstack/cert-manager, where it will be fully templated & the chart properly assembled).
```release-note
NONE
```
/area deploy
/kind cleanup
=> Use Bazel to automatically add version numbers to the Helm chart README

devel/cluster/create.sh, hack/bin/BUILD.bazel, hack/bin/deps.bzl
Adds support for `K8S_VERSION=1.18` to the `devel/cluster/create.sh` script, to allow us to enable testing against Kubernetes 1.18.
```release-note
NONE
```
/area testing
/kind feature
=> devel: add k8s 1.18 support

cmd/controller/app/controller.go, pkg/controller/acmechallenges/controller.go, pkg/controller/acmeorders/controller.go, pkg/controller/builder.go, pkg/controller/certificaterequests/controller.go, pkg/controller/certificates/controller.go, pkg/controller/clusterissuers/controller.go, pkg/controller/controller.go, pkg/controller/ingress-shim/controller.go, pkg/controller/issuers/controller.go, pkg/controller/register.go, pkg/controller/test/context_builder.go
This is no longer required as there is a `With` function on the `pkg/controller.Builder` structure that can be used to trigger additional things that should be run alongside a controller (which is used in the `acmechallenges` controller to run the challenge scheduler, and the `webhookbootstrap` controller to continuously ensure the webhook TLS assets are up to date).
Removing this option to a) simplify things a bit and b) make it easier/cleaner to start controllers during integration tests.
```release-note
NONE
```
/kind cleanup
=> Remove AdditionalRunFuncs from base controller

WORKSPACE, build/BUILD.bazel, build/images.bzl, build/platforms.bzl, build/release-tars/BUILD.bazel
Adds UBI base image targets to the build/release targets. This will require an additional change to the github.com/cert-manager/release `cmrel` tool in order to:
1) understand the new 'ubi' variant images
2) understand the new `s390x` and `ppc64le` architectures
I've opted to keep these variants of these images within the same image repository but under a suffixed tag, e.g. `v0.14.1-ubi` or `v0.14.1-alpha.0-ubi` etc.
This PR does *not* setup end-to-end test jobs that actually use these new base images - we might want to consider creating a periodic job for this, in case anything weird with permissions etc. comes up when running in the UBI environment.
```release-note
Add Red Hat Universal Base Image based image release targets
``` …
=> Add build targets for UBI based docker images

build/container.bzl
As per @r0bj's comment here: https://github.com/jetstack/cert-manager/pull/2708#issuecomment-605393658 it seems like the recent changes in https://github.com/jetstack/cert-manager/pull/2708 did not correctly fix the user ID used for our release docker images.
The 'stamped' version of these images (which contains the build timestamp in it) did *not* set the `user` attribute. Because of this, it get reset back to zero in this target, meaning that in *releases* specifically, the UID is still zero.
**Which issue this PR fixes**: fixes https://github.com/jetstack/cert-manager/pull/2708#issuecomment-605393658
This needs cherrypicking back into v0.14 and will mean we need to release v0.14.2. …
=> helm.bzl: correctly set 'user' attribute on all image targets

deploy/manifests/BUILD.bazel
This should have been set to `false` as we already prepend the CRD resources using Bazel, which we have to do because `helm template` no longer has a `--kube-version` command.
```release-note
Fix issuing causing CRDs to added to the static manifests twice
```
/kind bug
=> Avoid duplicate CRDs in static manifests

deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/serviceaccount.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/templates/webhook-rbac.yaml, deploy/charts/cert-manager/values.yaml
Some improvements for the Helm chart to remove `annotations` fields when none are specified, as well as correctly setting `metadata.namespace` on namespaced resources (so the 'static manifests' have to correct namespace by default).
```release-note
NONE
```
/kind cleanup
/area deploy
=> Remove empty 'annotations' blocks from resources and add missing 'metata.namespace' field

deploy/charts/cert-manager/templates/webhook-deployment.yaml
Without this I am unable to reach the port inside the cluster from another pod. cert-manager itself complains about being unable to reach the webhook:
```
E0414 23:20:49.230665       1 controller.go:140] cert-manager/controller/clusterissuers "msg"="re-queuing item  due to error processing" "error"="Internal error occurred: failed calling webhook \"webhook.cert-manager.io\": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=4s: context deadline exceeded" "key"="letsencrypt-prod"
```
Testing it from another random pod results in similar failure:
```
% keti -n pihole pihole-776dd9464b-9gmfd bash
root@pihole-776dd9464b-9gmfd:/# nc -v cert-manager-webhook.cert-manager.svc 443
nc: connect to cert-manager-webhook.cert-manager.svc port …
```
=> Expose webhook deployment container port

pkg/api/util/conditions.go, pkg/apis/certmanager/v1alpha2/types.go, pkg/apis/certmanager/v1alpha3/types.go, pkg/controller/expcertificates/BUILD.bazel, pkg/controller/expcertificates/issuing/BUILD.bazel, pkg/controller/expcertificates/issuing/issuing_controller.go, pkg/controller/expcertificates/issuing/issuing_controller_test.go, pkg/controller/expcertificates/issuing/keystore.go, pkg/controller/expcertificates/issuing/keystore_test.go, pkg/controller/expcertificates/issuing/secret.go, pkg/controller/expcertificates/issuing/secret_test.go, pkg/controller/expcertificates/issuing/util_test.go, pkg/controller/expcertificates/trigger/BUILD.bazel, pkg/controller/expcertificates/trigger/trigger_controller.go, pkg/controller/expcertificates/trigger/trigger_controller_test.go, pkg/controller/expcertificates/util.go, pkg/internal/apis/certmanager/types.go, pkg/util/kube/pki.go, test/integration/certificates/BUILD.bazel, test/integration/certificates/issuing_controller_test.go, test/unit/gen/certificate.go, test/unit/gen/certificaterequest.go
/cc @munnerz 
This controller is used to implement the issuing controller, as described in the extensible certificates controller proposal here #2753. This controller is responsible for writing the resulting certificate, ca, and private key to the target certificate resource, in the correct fromat.
```release-note
Adds new extensible issuing certificate
```
=> Extensible Certificate Issuing Controller

pkg/controller/expcertificates/BUILD.bazel, pkg/controller/expcertificates/informers.go, pkg/controller/expcertificates/internal/predicate/BUILD.bazel, pkg/controller/expcertificates/internal/predicate/certificate.go, pkg/controller/expcertificates/internal/predicate/certificate_test.go, pkg/controller/expcertificates/internal/predicate/certificaterequest.go, pkg/controller/expcertificates/internal/predicate/certificaterequest_test.go, pkg/controller/expcertificates/internal/predicate/generic.go, pkg/controller/expcertificates/internal/predicate/generic_test.go, pkg/controller/expcertificates/internal/predicate/predicate.go, pkg/controller/expcertificates/internal/predicate/predicate_test.go, pkg/controller/expcertificates/issuing/BUILD.bazel, pkg/controller/expcertificates/issuing/issuing_controller.go, pkg/controller/expcertificates/listers.go, pkg/controller/expcertificates/trigger/BUILD.bazel, pkg/controller/expcertificates/trigger/trigger_controller.go, pkg/controller/expcertificates/util.go
Refactors the way we configure and apply predicates that are applied during Enqueue functions (for informers) and listers. This means we can share predicate functions between the two, which should hopefully simplify all the ad-hoc selection/filtering logic we're starting to create.
Part of the on-going 'experimental certificates' work 😄
```release-note
NONE
```
/kind cleanup
=> expcertificates: create 'predicate' package and standardise list and enqueue predicates

deploy/charts/cert-manager/templates/cainjector-rbac.yaml, deploy/charts/cert-manager/templates/rbac.yaml
This PR limits the Role created for the leadership election to the 3 specific configmaps that are used for this election. This will in turn limit the security impact of deploying these roles into for example the kube-system namespace as access is limited to these 3 configmaps.
This change was made because I found this TODO line in the installation yaml(lines 6064 and 6084 of https://github.com/jetstack/cert-manager/releases/download/v0.14.1/cert-manager.yaml) and i really do not like to broad of access to anything.
So after deploying cert-manager, retrieved the configmap names, added them to the respective RBAC yaml files and tried the deployment again and it is still functioning.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, …
=> Limit the scope of leadership configmap role to specific configmaps

build/container.bzl
This adds our licence files to `/licences` in the Docker images, this is a requirement for some certifications like the RedHat Operator hub.
```release-note
Add license files to /licences/ in Docker images
```
=> Add licences to Docker images

deploy/charts/cert-manager/templates/cainjector-rbac.yaml, pkg/api/BUILD.bazel, pkg/api/scheme.go, pkg/controller/cainjector/BUILD.bazel, pkg/controller/cainjector/controller.go, pkg/controller/cainjector/injectors.go, pkg/controller/cainjector/setup.go
This adds support for the `AuditSink` in `auditregistration.k8s.io/v1alpha1` to be a ca injector target. 
```release-note
Support the `AuditSink` kind in `auditregistration.k8s.io/v1alpha1` to be a ca injector target. 
```
=> Add auditsinks in auditregistration.k8s.io/v1alpha1 to the supported injector targets

cmd/controller/app/BUILD.bazel, cmd/controller/app/controller.go, pkg/apis/certmanager/v1alpha2/types.go, pkg/controller/expcertificates/BUILD.bazel, pkg/controller/expcertificates/issuing/issuing_controller.go, pkg/controller/expcertificates/keymanager/BUILD.bazel, pkg/controller/expcertificates/keymanager/keymanager_controller.go, pkg/controller/expcertificates/keymanager/keymanager_controller_test.go, pkg/controller/expcertificates/listers.go, pkg/controller/expcertificates/util.go, pkg/controller/expcertificates/util_test.go, pkg/internal/apis/certmanager/validation/certificate.go
Adds the keymanager controller which handles generating and managing 'next private keys' with the new 'experimental' certificates controller design.
With this PR, the controller currently *always* generates a new private key upon re-issuance, a departure from what we do today. It needs extending to default to the current behaviour with an option to enable rotation.
```release-note
NONE
```
=> expcertificates: add keymanager controller

pkg/internal/venafi/sign.go, pkg/internal/venafi/sign_test.go
Add an origin tag on Venafi certificate sign requests. This allows the Venafi software to recognize that the certificates are requested by cert-manager
```release-note
Venafi issuer: add origin tag to requests
```
=> Add cert-manager origin tag in Venafi

build/container.bzl
Licence vs. license was very confusing but the correct one for the Docker container should be licenses 
```release-note
NONE
```
/kind cleanup
=> Make directory name the correct "licenses"

deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml, deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml
* Use the correct URL path for validation
* Also validate v1alpha3 API objects
Fixes: #2754
Fixes: #2822
Signed-off-by: Richard Wall <richard.wall@jetstack.io>
```release-note
Fix validatingwebhookconfiguration to use correct URL path and to suport v1alpha3 API objects.
```
=> Fixes for the validating and mutating webhook configuration

pkg/controller/ingress-shim/sync.go
When the default issuer kind is overwritten to ClusterIssuer but 
Fixes https://github.com/jetstack/cert-manager/issues/2533
```release-note
Fix case where cert-manager.io/issuer doesn't set `Issuer` kind
```
=> Set Issuer kind specific to Issuer if /issuer is specified

pkg/issuer/acme/dns/cloudflare/cloudflare.go
It changes the `per_page` used to query Cloudfare 
**Which issue this PR fixes** *
fixes: #2857
NA
```release-note
Limit `per_page` to 100 in Cloudfare API calls
```
=> cloudfare: update per_page max to 100

build/BUILD.bazel, build/platforms.bzl, build/release-tars/BUILD.bazel
This PR adds the ctl binaries to the release tars for the release tool to use
This is a very early WIP to allow the cmrel tool to pick up this branch 
```release-note
Release cert-manager ctl binaries
```
=> Build ctl binaries

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/_helpers.tpl, deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/cainjector-psp-clusterrolebinding.yaml, deploy/charts/cert-manager/templates/cainjector-rbac.yaml, deploy/charts/cert-manager/templates/cainjector-serviceaccount.yaml, deploy/charts/cert-manager/templates/psp-clusterrolebinding.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/templates/webhook-psp-clusterrolebinding.yaml, deploy/charts/cert-manager/templates/webhook-rbac.yaml, deploy/charts/cert-manager/templates/webhook-serviceaccount.yaml, deploy/charts/cert-manager/values.yaml
The psp cluste role binding was not using the serviceAccountName template so it would have binded to the wrong service account if a name was given.
Add the ability to disable and set the name of the service accounts for the webhook and cainjector.
```release-note
* Add webhook service account customization
* Add cainjector service account customization
```
=> chart service account improvments

pkg/apis/certmanager/v1alpha2/types.go, pkg/apis/certmanager/v1alpha3/types.go, pkg/internal/apis/certmanager/types.go, pkg/util/pki/csr_test.go
Removes the `serverAuth` usage by default to avoid issues when creating certificates with the `isCA` option set to true.
**Which issue this PR fixes**: fixes #2407
```release-note
ACTION REQUIRED: Remove `serverAuth` key usage from set of defaults. If your configured issuer does not automatically set this usage and you do require it, you will need to manually update your Certificate & CertificateRequest resources to contain the `serverAuth` usage
```
=> Remove serverAuth default usage & remove unused DefaultKeyUsage functions

cmd/ctl/BUILD.bazel
Uses the correct `go_binary` (our own one that wraps the go_binary and sets x_defs correctly).
```release-note
NONE
```
/kind bug
/area ctl
=> Ensure version x_defs are set on built ctl binary

deploy/crds/crd-orders.yaml, pkg/apis/acme/v1alpha2/types_order.go, pkg/apis/acme/v1alpha3/types_order.go, pkg/controller/acmeorders/sync.go, pkg/controller/acmeorders/sync_test.go, pkg/controller/acmeorders/util.go, pkg/internal/apis/acme/types_order.go, pkg/internal/apis/acme/v1alpha2/zz_generated.conversion.go, pkg/internal/apis/acme/v1alpha3/zz_generated.conversion.go, pkg/internal/apis/acme/validation/order.go
If an ACME Order object contains authorizations that are already 'valid', we will still attempt to create Challenge resources for them (which would usually immediately be marked valid). [Because Let's Encrypt recently changed Boulder to not return already-valid Challenges within Authorization objects](https://github.com/jetstack/cert-manager/issues/2494#issuecomment-618503293), this would mean we'd not be able to find a valid 'solving configuration' and so we'd fail to create the Challenge resource, thus never observing that the Authorization is already valid.
This extends the `fetchMetadata` method, which fetches the initial Authorization objects from the ACME server, to record the initial state of the Authorization, thus allowing the …
=> Handle ACME orders with already valid authorizations upon first fetch through new 'initialState' field

cmd/ctl/cmd/cmd.go, cmd/ctl/pkg/version/version.go, tools/cobra/main_test.go
Renames the CLI tool to the public name
```release-note
NONE
```
=> Rename the CLI to kubectl cert-manager

cmd/ctl/cmd/cmd.go, cmd/ctl/pkg/renew/renew.go, tools/cobra/main_test.go
Updates references to the command name to be consistently `kubectl cert-manager`. For the usage text, this was slightly more difficult due to the fact Cobra strips everything after the first space character in the `Use` field, so I've duplicated the default Usage template here and modified it to include `kubectl` at the start 😅 
**Which issue this PR fixes**: fixes #2886
```release-note
NONE
```
/kind bug
/area ctl
/cc @meyskens 
=> Update references to ctl binary name

Makefile, build/BUILD.bazel
The name of the target generated by `build/container.bzl` has changed, causing the error described in the linked issue!
**Which issue this PR fixes**: fixes #2881
```release-note
NONE
```
/kind bug
=> Fix 'make images'

hack/filter-crd/main.go
https://github.com/jetstack/cert-manager/commit/393ee0cd47e560e674c39564dff4695bb13bf7d0 removed `x-kubernetes-preserve-unknown-fields` from Issuer and ClusterIssuer CRDs but this field is once again present in these CRDs (don't know since when though). This PR removes the `x-kubernetes-preserve-unknown-fields` field again from these CRDs.
```release-note
NONE
```
=> Remove x-kubernetes-preserve-unknown-fields from Issuer and ClusterIssuer CRDs

deploy/charts/cert-manager/.helmignore, deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/values.yaml
Adds the ability to set the container securityContext for each deployment in the helm chart.
fixes #2849
```release-note
Added the ability to set the container securityContext for each deployment in the helm chart
```
=> Fix #2849 Add container security context to helm chart deployments

go.mod, go.sum, hack/build/repos.bzl
Updates AWS Go SDK to 1.31.3 to support Route53 in AWS China Region.
See: https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-route-53-is-now-available-in-AWS-china-region/
```release-note
Updates AWS Go SDK to 1.31.3 to support Route53 in AWS China Region
```
=> Update AWS Go SDK to 1.31.3

pkg/internal/venafi/sign.go
Venafi TPP errors on trying to sign a CSR with an empty DN. In 0.15 we stopped adding `cert-manager` as default org to all certs, making the DN empty by default (if no CN is set).
This adds the default behavior back for the Venafi issuer to not break compatibility.
fixes #2905
```release-note
Default to `O = cert-manager` in the Venafi issuer if DN is empty
```
/kind bug
/cherry-pick release-0.15
=> Add default DN back in Venafi issuer

pkg/controller/certificates/sync.go, pkg/controller/certificates/sync_test.go, pkg/controller/expcertificates/internal/secretsmanager/secret.go, pkg/controller/expcertificates/issuing/issuing_controller_test.go
**What this PR does / why we need it**: Currently cert-manager creates TLS secrets with three keys: tls.key, tls.crt and ca.crt.
ca.crt can be empty, and user suggested that we change the behaviour to: ca.crt either exists and contains a valid CA, or it does not exist.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1975 
```release-note
An empty ca.crt will no longer be added into the secret resource
```
=> Do not add empty ca.crt

deploy/charts/cert-manager/values.yaml
Adds a new line in values.yaml to clairify podLabels does not belong to the comment below
fixes  #2970 
```release-note
NONE
```
=> Add new line to clairify podLabels <-> podDNS

pkg/issuer/acme/dns/route53/BUILD.bazel, pkg/issuer/acme/dns/route53/route53.go
Signed-off-by: Ilya Shaisultanov <ilya.shaisultanov@gmail.com>
ACME challenges controller already handles retry logic. This
avoid an issue where cert-manager can spam Route53 under certain
conditions, leading to throttling.
**Which issue this PR fixes** : fixes #2159.
I used `make verify` to test this, unsure if that's the best way.
```release-note
Remove custom retry logic from Route53 DNS01
```
=> Remove custom retry logic from route53 package

WORKSPACE, build/container.bzl, devel/addon/ingressnginx/BUILD.bazel, devel/addon/ingressnginx/install.sh, test/e2e/images.bzl
This tags the Docker images correct when building multiarch images
fixes #2987
I had to update the Bazel Docker helper to support setting this. This also deprecated v1 manifests which is why the Nginx ingress is updated also. 
Related: https://github.com/cert-manager/release/pull/17
```release-note
Tag the Docker image with the correct `architecture` attribute
```
=> Fix Docker architecture tag set by bazel

pkg/controller/expcertificates/issuing/issuing_controller.go, pkg/controller/expcertificates/issuing/temporary.go, pkg/util/pki/generate.go
Currently when a user uses experminetal certificates controller only, the private keys are always encoded in PKCS8. This PR is to correctly handle the Spec.keyEncoding field to encode private keys to PKCS1 or PKCS8 as requested by the user.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2863
```
Experimental certificate controllers encode private keys according to specification of user.
```
=> Encode private keys to PKCS1/PKCS8 as requested by user

test/integration/certificates/issuing_controller_test.go
Adds a test case for #3017 - ensuring that we correctly convert private keys into the requested output key format
```release-note
NONE
```
/kind cleanup
/milestone v0.16
=> expcertificates: add integration test for PKCS#8 keyFormat

deploy/crds/crd-certificates.yaml, pkg/apis/certmanager/v1alpha2/types_certificate.go, pkg/apis/certmanager/v1alpha2/zz_generated.deepcopy.go, pkg/apis/certmanager/v1alpha3/types_certificate.go, pkg/apis/certmanager/v1alpha3/zz_generated.deepcopy.go, pkg/controller/certificates/controller.go, pkg/controller/expcertificates/readiness/readiness_controller.go, pkg/controller/expcertificates/trigger/BUILD.bazel, pkg/controller/expcertificates/trigger/policies/BUILD.bazel, pkg/controller/expcertificates/trigger/policies/policies.go, pkg/controller/expcertificates/trigger/policies/policies_test.go, pkg/controller/expcertificates/trigger/trigger_controller.go, pkg/controller/expcertificates/util.go, pkg/internal/apis/certmanager/types_certificate.go, pkg/internal/apis/certmanager/v1alpha2/zz_generated.conversion.go, pkg/internal/apis/certmanager/v1alpha3/zz_generated.conversion.go, pkg/internal/apis/certmanager/zz_generated.deepcopy.go, pkg/scheduler/BUILD.bazel, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go, test/integration/certificates/BUILD.bazel, test/integration/certificates/trigger_controller_test.go, test/integration/framework/apiserver.go
This PR fixes certificate renewal near expiry when running with the new 'experimental' certificate controllers introduced in v0.15.
The 'scheduled work queue' concept has been modified to use a passed-in 'clock' which we can easily manipulate during integration tests.
I've then also added an integration test to exercise this case so we can be sure it's working.
**Which issue this PR fixes**: fixes #2978
This is best reviewed commit-by-commit.
I've aimed to keep things nice and separated to make it clear at each stage along the way what's going on.
I also opted to add two new fields to the Certificate resource's `status`: `status.notAfter` and `status.renewalTime`. These are computed and set/managed by the …
=> expcertificates: fix bug renewing certificates automatically near expiry

deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, pkg/apis/acme/v1alpha2/types_issuer.go, pkg/apis/acme/v1alpha3/types_issuer.go, pkg/internal/apis/certmanager/validation/issuer.go, pkg/issuer/acme/dns/cloudflare/cloudflare.go
Cloudflare does not require an email to be sent when using token based auth. 
We should make the field optional if tokens are used.
fixes  #2972 
```release-note
DNS01: make Cloudflare email optional if a token is used
```
=> Make Cloudflare email an optional field

cmd/ctl/pkg/create/certificaterequest/BUILD.bazel, cmd/ctl/pkg/create/certificaterequest/certificaterequest.go
Signed-off-by: Haoxiang Zhou <haoxiang.zhou@jetstack.io>
Change `create cr` ctl command to use ctl.Scheme that was created recently instead of webhook.Scheme.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3029 
```
Use ctl.Scheme in create cr ctl command
```
/kind cleanup
=> Use ctl.Scheme in create cr ctl command

devel/addon/ingressnginx/install.sh
this sets `controller.admissionWebhooks.enabled=false` for the Nginx ingress deployed for e2e tests as we do not use this.
This being true failed older Kubernetes versions as their webhook configuration was not backwards compatible with Kubernetes 1.11 and 1.12.
```release-note
NONE
```
/kind cleanup
=> Disable controller admission webhook in ingress nginx for e2e

pkg/internal/venafi/sign.go, pkg/internal/venafi/sign_test.go
In #2946 we made a mistake that the DN is taken from the  CSR and not the vCert request.
Since there is no way to modify the CSR right now for 1 specific issuer we should add a check instead to tell the user the certificate will be refused by the Venafi system instead of showing the unclear error the API gives back and keep retrying. 
```release-note
Error on venafi CertificateRequest when DN is empty
```
=> Error on venafi CertificateRequest when DN is empty

pkg/controller/cainjector/BUILD.bazel, pkg/controller/cainjector/injectors.go, pkg/controller/cainjector/setup.go
The AuditSink resource type (previously in alpha) has been removed
as per https://groups.google.com/g/kubernetes-sig-auth/c/aV_nXpa5uWU.
Remove all support for it from our cainjector so we are able to
continue to upgrade dependencies, and to avoid more users coming
to rely on this functionality ahead of it being removed from
Kubernetes.
The AuditSink resource type (previously in alpha) has been removed
as per https://groups.google.com/g/kubernetes-sig-auth/c/aV_nXpa5uWU.
Remove all support for it from our cainjector so we are able to
continue to upgrade dependencies, and to avoid more users coming
to rely on this functionality ahead of it being removed from
Kubernetes.
```release-note
ACTION REQUIRED: Support for AuditSink …
```
=> Remove AuditSink support from cainjector

WORKSPACE
Upgrade Go to 1.14.4 ahead of the 0.16 release
```release-note
Build using Go version 1.14.4
```
/kind cleanup
/milestone v0.16
=> Bump Go version to 1.14.4

pkg/internal/apis/certmanager/validation/util/BUILD.bazel, pkg/internal/apis/certmanager/validation/util/nameserver_test.go
While looking into a potential bug i found this validation function not to have any tests while it is quite critical. I added some basic unit tests to it.
```release-note
NONE
```
/kind cleanup
=> Add unit tests for nameserver validation

LICENSES, go.mod, go.sum, hack/build/repos.bzl, hack/update-deps-licenses.sh
Upgrades cobra dependency to v1.0.0. This required a fair bit of work due to the issues described in https://github.com/kubernetes/kubernetes/pull/92735 ...
Requires #3057 
```release-note
NONE
```
=> Upgrade cobra dependency to v1.0.0

pkg/issuer/acme/http/BUILD.bazel, pkg/issuer/acme/http/http.go
A lot of places (Kubernetes probes specifically) already use the default Go HTTP User Agent.
it would be nice for SREs to be able to more specifically pinpoint cert-manager self checks traffic inside their logs, by filtering the cert-manager user agent.
```release-note
Add cert-manager specific User-Agent to HTTP01 self-checks
```
=> Add a user-agent on HTTP self-checks

cmd/acmesolver/BUILD.bazel, cmd/acmesolver/app/BUILD.bazel, cmd/acmesolver/app/app.go, cmd/acmesolver/main.go, cmd/controller/app/start.go, cmd/webhook/BUILD.bazel, cmd/webhook/app/BUILD.bazel, cmd/webhook/app/options/options.go, cmd/webhook/app/testing/testwebhook.go, cmd/webhook/app/webhook.go, cmd/webhook/main.go, pkg/issuer/acme/http/solver/BUILD.bazel, pkg/issuer/acme/http/solver/solver.go, tools/cobra/BUILD.bazel, tools/cobra/main.go
This move the acmesolver and webhook commands into the cobra package for consistency and to allow documentation generation for their command line arguments.
This also fixes a small bug in the controller where it would not exit on an options validation error.
This also includes the two new cobra commands into the docs generation code.
```release-note
NONE
```
fixes #2852
=> Move all commands into cobra

deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml, deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml
In #3038 we added a new API version, but forgot to add it to our webhook configuration 🙈 
Switch this to a wildcard to avoid this issue in future.
```release-note
NONE
```
/kind cleanup
/area deploy
/milestone v0.16
=> Use wildcard for apiVersions in webhook configurations

pkg/controller/certificaterequests/acme/acme.go, pkg/controller/certificaterequests/acme/acme_test.go, test/unit/gen/order.go
Updates the `acme` certificate request controller to surface the Order's `reason` field if an Order has failed for whatever reason.
This should make it easier to debug issues as they'll be immediately obvious via `kubectl describe certificate` and `kubectl describe certificaterequest` instead of the user having to go all the way down to the Order level.
```release-note
acme: surface the 'reason' for Order's failing on Certificate & CertificateRequest resources for easier debugging of failures
```
/area acme
/kind feature
/milestone v0.16
=> Include Order failure reason as part of CertificateRequest failure message

deploy/charts/cert-manager/README.template.md
Add chart docs for `ingressShim.defaultIssuerGroup` 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: -
```release-note
NONE
```
=> Add defaultIssuergroup option to chart docs

cmd/ctl/BUILD.bazel, cmd/ctl/pkg/create/certificaterequest/BUILD.bazel, cmd/ctl/pkg/create/certificaterequest/certificaterequest.go, cmd/ctl/pkg/util/BUILD.bazel, cmd/ctl/pkg/util/util.go, test/integration/ctl/BUILD.bazel, test/integration/ctl/ctl_create_cr_test.go
This PR enables the user to specify `--fetch-certificate` and `--output-cert-file` flags to wait for the CertificateRequest that was created to be ready and store the certificate in a file.
```
kubectl cert-manager: Added flags to wait for the CertificateRequest to be ready and store the certificate in a file.
```
/kind feature
/area ctl
=> Enable create cr ctl command to fetch certificate

hack/filter-crd/main.go
With adding v1beta1 the filter-crd broke causing invalid legacy CRDs. This adds the new field paths to remove in a multi version validation.
```release-note
NONE
```
/kind bug
=> Fix multi version removal of x-kubernetes-preserve-unknown-field 

deploy/charts/cert-manager/templates/webhook-deployment.yaml
Inject `POD_NAMESPACE` env variable to `dynamic-serving-ca-secret-namespace` argument in `cert-manager-webhook` deployment template. So user installing cert-manager static manifests with `kustomize` and `namePrefix` or `nameSuffix`, will not have to modify manually `cert-manager-webhook` deployment `dynamic-serving-ca-secret-namespace` argument (more details in the related issue).
**Which issue this PR fixes**: fixes #3099
```release-note
NONE
```
=> Inject POD_NAMESPACE env variable in cert-manager-webhook deployment template

pkg/issuer/acme/dns/cloudflare/cloudflare.go
Cloudfare's API errors can be quite obscure to the reason why exactly the request is failing, it will for example give you an API permission error when trying to list zones for a domain name not in an account.
This adds the HTTP verb and path to the error to have more context to the user where we got the error.
new output in `kubectl describe`:
```
Status:
Presented:   false
Processing:  true
Reason:      Cloudflare API Error for GET "/zones?name=unauthorized-domain-name" 
Error: 0: Actor 'com.cloudflare.api.token.somecode' requires permission 'com.cloudflare.api.account.zone.list' to list zones
State:       pending
Events:
Type     Reason        Age              From          Message
----     ------        ----             ----          ------- …
```
=> Improve error output for Cloudflare

pkg/controller/certificates/trigger/trigger_controller.go, pkg/controller/certificates/trigger/trigger_controller_test.go
Previously, if a certificate had failed due to the underlying CertificateRequest failing, the Certificate would only be scheduled to be 'resynced' by the trigger controller *if* the `status.RenewalTime` is in the *future*.
This is really non-obvious, and is effectively because this assumption (in `scheduleRecheckOfCertificateIfRequired`):
```go
// don't schedule a re-queue if the time is in the past.
// if it is in the past, the resource will be triggered during the
// current call to the ProcessItem method. If we added the item to the
// queue with a duration of <=0, we would otherwise continually re-queue
// in a tight loop whilst we wait for the caching listers to observe
// the 'Triggered' status condition changing to 'True'.
```
Does *not* hold …
=> Schedule a 'resync' of Certificates that have been marked as failed and are to be retried later

hack/sha256-of-plugin-tar.sh
Signed-off-by: Haoxiang Zhou <haoxiang.zhou@jetstack.io>
This script make it easier to manually update the our plugin manifest in krew-index. It downloads the .tar files for different platforms and outputs the SHA256.
```
NONE
```
=> Add script for computing SHA256 of tars of our kubectl plugin

design/20200326.extensible-certificate-controller.md
Adds a design document for the 'extensible certificates controller' design. This is still work in progress, but I'm putting it out there now as the general ideas behind it are there and I'd like to get feedback 😄 
**Which issue this PR fixes**: fixes #2692 
```release-note
NONE
```
/kind design
=> add extensible certificate controller design doc

cmd/ctl/pkg/status/certificate/certificate.go
Signed-off-by: Haoxiang Zhou <haoxiang.zhou@jetstack.io>
When iterating through the list of CRs, I just took the pointer, which always gets overwritten by the next request. This is the fix.
```
Fix bug of status certificate command where the matching CR gets overwritten
```
/kind bug
/area ctl
=> Fix bug of using overwritten pointer when searching for CR

deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, pkg/apis/certmanager/v1alpha2/types_issuer.go, pkg/apis/certmanager/v1alpha3/types_issuer.go, pkg/apis/certmanager/v1beta1/types_issuer.go, pkg/internal/apis/certmanager/types_issuer.go, pkg/internal/apis/certmanager/v1alpha2/zz_generated.conversion.go, pkg/internal/apis/certmanager/v1alpha3/zz_generated.conversion.go, pkg/internal/apis/certmanager/v1beta1/zz_generated.conversion.go, pkg/internal/vault/vault.go, pkg/internal/vault/vault_test.go
fixes #2917
This requires a change in the documentation, please let me know the repo where the documentations for the CRDs are kept so that I can add it there as well. 
```release-note
Added Namespace to VaultIssuer to support vault roles from a different vault namespaces
```
=> Add Vault Namespace in Vault Issuer

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/values.yaml
When using AWS EKS with a third party CNI (such as Weave or Calico), cert-manager cannot reach the webhook. Running the webhook on the host network solves this issue.
Used the comment from https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml#L1294 in the `values.yaml`.
Fixes some occurrences of issue https://github.com/jetstack/cert-manager/issues/2109, such as https://github.com/jetstack/cert-manager/issues/2109#issuecomment-546954893.
```
Add `webhook.hostNetwork` option to the Helm Chart to run the webhook in hostNetwork mode
```
/kind feature
=> Chart: Add option to run webhook in hostNetwork

cmd/ctl/pkg/status/certificate/certificate.go, test/integration/ctl/ctl_status_certificate_test.go, test/unit/gen/issuer.go
This PR adds output about the Issuer/ClusterIssuer of the Certificate resource.
Also adds the creation time of the Certificate.
```
Add output about the Issuer/ClusterIssuer of the Certificate resource and about creation time of the Certificate.
```
/kind feature
/area ctl
=> Ctl status certificate command: Add issuer output and creation time

USERS.md
We hear a lot of good cert-manager user stories but we never had a proper list for them. This file allows cert-manager users who would like to promote their use of our project to list themselves on our repo.
```release-note
NONE
```
=> Add a USERS.md file to list cert-manager users

deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, pkg/apis/acme/v1alpha2/types_issuer.go, pkg/apis/acme/v1alpha3/types_issuer.go, pkg/apis/acme/v1beta1/types_issuer.go, pkg/internal/apis/acme/types_issuer.go, pkg/internal/apis/acme/v1alpha2/zz_generated.conversion.go, pkg/internal/apis/acme/v1alpha3/zz_generated.conversion.go, pkg/internal/apis/acme/v1beta1/zz_generated.conversion.go, pkg/issuer/acme/http/pod.go, pkg/issuer/acme/http/pod_test.go
This adds support for the `priorityClassName` field for HTTP01 solvers.
fixes:  #3108
```release-note
Add `priorityClassName` field to `podTemplate` for ACME HTTP01 issuers
```
/kind feature
=> Add support for the pod PriorityClass field in HTTP01 podTemplate

pkg/controller/ingress-shim/sync.go, pkg/controller/ingress-shim/sync_test.go
Some issuers/consumers need a common name set. This allows ingress-shim users to set one using the CN annotation on ingress resources. ~~It also implements a defaulting for a CN which only applies on ingress-shim created resources.~~
Fixes https://github.com/jetstack/cert-manager/issues/2237
Fixes https://github.com/jetstack/cert-manager/issues/3087
Several things to have a think about:
~~1. is setting the CN by default a good idea?~~
~~1. Will there be issues by the sync controller updating older certs setting a CN?~~
~~1. The more i am writing i feel like only using the annotation might be a better idea...~~
```release-note
Allow cert-manager.io/common-name …
```
=> Set a CN on ingress-shim + allow common-name annotation on ingress

.bazelrc, WORKSPACE
- this PR updates the docker rule version
- removed the PY2 flag from .bazelrc
- this allows the project to use a hosts python3 installation
- python3 must be installed on the host system and link /usr/bin/python is required
- on debian sudo apt-get install python3-distutil as well as possible
other packages
**What this PR does / why we need it**: updating the docker rules in order to run on a system with python3
Allows for the use of bazel and python3. python2 is no longer viable.  I can open an issue, but there is one closed that talks about this problem. Here:
https://github.com/jetstack/cert-manager/issues/1498
**Special notes for your reviewer**: 
I do not know what your testing image has installed so this may not pass CI/CD if your testing host is …
=> Updating docker-rules and allowing for Python3

deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, pkg/apis/acme/v1alpha2/types_issuer.go, pkg/apis/acme/v1alpha3/types_issuer.go, pkg/apis/acme/v1beta1/types_issuer.go, pkg/internal/apis/acme/types_issuer.go, pkg/internal/apis/acme/v1alpha2/zz_generated.conversion.go, pkg/internal/apis/acme/v1alpha3/zz_generated.conversion.go, pkg/internal/apis/acme/v1beta1/zz_generated.conversion.go, pkg/issuer/acme/http/pod.go, pkg/issuer/acme/http/pod_test.go
**What this PR does / why we need it:**
This adds support for the serviceAccountName field for HTTP01 solvers.
**Which issue this PR fixes:**
fixes: #2770 
**Release note:**
```release-note
Add `serviceAccountName` field to `podTemplate` for ACME HTTP01 issuers
```
/kind feature
=> Add serviceAccountName to issuers CRDs for http01 solvers

test/unit/gen/order.go
Signed-off-by: Haoxiang Zhou <haoxiang.zhou@jetstack.io>
Variables of type `Order` were called `crt`, cleaning that up in a small PR.
```
NONE
```
/kind cleanup
=> User order as variable name in gen/order.go

test/e2e/suite/issuers/acme/issuer.go
This fixes a dropped error in `test/e2e/suite/issuers/acme`.
```release-note
NONE
```
=> test/e2e/suite/issuers/acme: fix dropped error

LICENSES, go.mod, go.sum, hack/build/repos.bzl, pkg/controller/certificates/internal/secretsmanager/keystore_test.go
This new version includes a
[pkcs12.DecodeChain](https://godoc.org/software.sslmate.com/src/go-pkcs12#DecodeChain)
which will help in testing https://github.com/jetstack/cert-manager/pull/3146
```release-note
NONE
```
=> Update to latest version of https://github.com/SSLMate/go-pkcs12

pkg/controller/certificates/internal/secretsmanager/BUILD.bazel, pkg/controller/certificates/internal/secretsmanager/keystore.go, pkg/controller/certificates/internal/secretsmanager/keystore_test.go
If ACME (or any other that has no CA.crt) issues an intermediate certificate it is dropped from our pkcs12 keystore.
This was due to the logic being inside an if statement that checked the CA.crt secret.
Fixes #3039
Supplants: https://github.com/jetstack/cert-manager/pull/3146
```
Fix issue where intermediate certificates are not in the pkcs12 keystore
```
=> Add intermediate cert to P12 chain if ca.crt is empty

deploy/charts/cert-manager/templates/cainjector-rbac.yaml, deploy/charts/cert-manager/templates/rbac.yaml, deploy/charts/cert-manager/templates/webhook-rbac.yaml, devel/addon/samplewebhook/chart/templates/rbac.yaml
Updates our chart to use `rbac.authorization.k8s.io/v1`, this is supported in all versions of Kubernetes we support
fixes #3158 
```release-note
Use rbac.authorization.k8s.io/v1
```
=> Use rbac.authorization.k8s.io/v1

cmd/ctl/pkg/status/certificate/BUILD.bazel, cmd/ctl/pkg/status/certificate/certificate.go, cmd/ctl/pkg/status/certificate/types.go, test/integration/ctl/BUILD.bazel, test/integration/ctl/ctl_status_certificate_test.go, test/unit/gen/order.go
Adds output about the Order resource for `status certificate` command if ACME Issuer is used.
```
Add output about Order resource for `status certificate` command if ACME Issuer is used.
```
/kind feature
/area ctl
=> Ctl command `status certificate`: Add order output

deploy/manifests/BUILD.bazel, hack/filter-crd/main.go
We always shipped "managed-by:helm" and other chart/tiller references in our static manifests, this is incorrect and can cause confusion.
This PR repurposed our `filter-crd` tool (which might be up to be renamed filter-yaml?) to remove those labels from the static CRDs and static deployment manifests.
fixed #2477 
I start to like Bazel, i'm sorry
```release-note
Remove Helm specific labels from static manifests
```
/kind cleanup
=> Remove managed by Helm labels from static manifests and CRDs

deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/values.yaml
Add digest option for images.
Also add "registry/repository" option.
Impossible to use a digest reference for a docker image.
It's needed for some security purpose.
```release-note
Helm chart: add image digest option
```
=> chart: add image digest option

USERS.md
Per @meyskens [request in the Kubernetes Slack workspace](https://kubernetes.slack.com/archives/C4NV3DWUC/p1596180147499000), add Atomist as user, along with link to a blog post describing the usage.
It seems the intent in the user table was to have the users in alphabetical order, so I did the same for the organization table. If you prefer to have them in a different order, let me know.
=> Add Atomist to users

cmd/ctl/pkg/status/certificate/certificate.go, cmd/ctl/pkg/status/certificate/certificate_test.go, cmd/ctl/pkg/status/certificate/types.go, test/integration/ctl/ctl_status_certificate_test.go, test/unit/gen/challenge.go
Adds info about Challenges related to a Certificate resource to the output of `status certificate` command.
Hold until previous [PR 3171](https://github.com/jetstack/cert-manager/pull/3171) is merged
```
Add info about Challenges related to a Certificate resource to the output of `status certificate` command.
```
/area ctl
/kind feature
=> Ctl command status certificate: Add challenge output

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/values.yaml
- This PR makes the Probes for the Webhook-Deployment configurable in the Helm-Chart
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3184
```release-note
Helm chart: make webhook-probes configurable 
```
=> Make webhook-probes configurable in helm-chart

cmd/ctl/pkg/create/certificaterequest/certificaterequest_test.go, deploy/charts/cert-manager/README.template.md, pkg/api/scheme.go, pkg/controller/ingress-shim/controller.go
Fixes some lingering references to v1alpha2 in our tests and in some of the import aliases.
Followup to https://github.com/jetstack/cert-manager/pull/3196
Part of https://github.com/jetstack/cert-manager/issues/3156
```release-note
NONE
```
/kind feature
=> Tidy up some remaining references to v1alpha2

deploy/crds/crd-clusterissuers.v1beta1.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.v1beta1.yaml, deploy/crds/crd-issuers.yaml, pkg/apis/acme/v1/types_issuer.go, pkg/apis/acme/v1alpha2/types_issuer.go, pkg/apis/acme/v1alpha3/types_issuer.go, pkg/apis/acme/v1beta1/types_issuer.go, pkg/internal/apis/acme/types_issuer.go, pkg/internal/apis/acme/v1/zz_generated.conversion.go, pkg/internal/apis/acme/v1alpha2/zz_generated.conversion.go, pkg/internal/apis/acme/v1alpha3/zz_generated.conversion.go, pkg/internal/apis/acme/v1beta1/zz_generated.conversion.go, pkg/issuer/acme/setup.go
Currently users cannot use a single ACME account ID across multiple clusters as cert-manager generates a new ACME account ID in each instance. This PR adds a new field to the ACMEIssuer API called `onlyUseExistingAccountKey` which, when set to true, disables generating a new private key on the Issuer resource. This would allow users to create a Issuer resource without creating the Secret resource, instead reusing an existing one (e.g. copied from another cluster)
Default behaviour is still the same.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2990 
Not sure about the correctness of the comments I …
=> Ability to disable generating new ACME account key for ACME issuers

pkg/controller/certificates/internal/secretsmanager/keystore_test.go
This fixes two dropped test error variables.
```release-note
NONE
```
=> pkg/controller/certificates/internal: fix dropped test errors

pkg/apis/acme/v1/types.go, pkg/issuer/acme/http/http.go, pkg/issuer/acme/http/ingress_test.go, pkg/issuer/acme/http/pod.go, pkg/issuer/acme/http/pod_test.go
Fixes https://github.com/jetstack/cert-manager/issues/3159
```release-note
NONE
```
=> Move ACME label keys to the external API package

deploy/crds/crd-clusterissuers.v1beta1.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.v1beta1.yaml, deploy/crds/crd-issuers.yaml, go.mod, go.sum, hack/build/repos.bzl, pkg/acme/client/fake.go, pkg/acme/client/interfaces.go, pkg/acme/client/middleware/logger.go, pkg/apis/acme/v1/types_issuer.go, pkg/apis/acme/v1alpha2/types_issuer.go, pkg/apis/acme/v1alpha3/types_issuer.go, pkg/apis/acme/v1beta1/types_issuer.go, pkg/controller/acmeorders/sync.go, pkg/controller/acmeorders/sync_test.go, pkg/internal/apis/acme/types_issuer.go, pkg/internal/apis/acme/v1/zz_generated.conversion.go, pkg/internal/apis/acme/v1alpha2/zz_generated.conversion.go, pkg/internal/apis/acme/v1alpha3/zz_generated.conversion.go, pkg/internal/apis/acme/v1beta1/zz_generated.conversion.go
The ACME API now allows for alternate certificates being fetched signed by different CAs. Let's Encrypt does this by serving both their cross signed and own CA root certificates. We currently do not support specifying a preference for one. 
certbot recently added support for this with the upcoming switch to the ISRG CA, they added:
```
--preferred-chain PREFERRED_CHAIN
If the CA offers multiple certificate chains, prefer
the chain with an issuer matching this Subject Common
Name. If no match, the default offered chain will be
```
This PR adds similar behavior to cert-manager, while I didn't look at the exact checks it does and error handling it seems I wrote the exact dame thing :smiley_cat: 
Fixes …
=> Add support for alternate certs with PrefferedChain in ACME

WORKSPACE, go.mod
```release-note
Build using Go version 1.15
```
This seems significant in the Go 1.15 release notes: https://golang.org/doc/go1.15#commonname
> The deprecated, legacy behavior of treating the CommonName field on X.509 certificates as a host name when no Subject Alternative Names are present is now disabled by default. It can be temporarily re-enabled by adding the value x509ignoreCN=0 to the GODEBUG environment variable.
> 
> Note that if the CommonName is an invalid host name, it's always ignored, regardless of GODEBUG settings. Invalid names include those with any characters other than letters, digits, hyphens and underscores, and those with empty labels or trailing dots. 
/kind cleanup
/milestone v1.0
=> Bump Go version to 1.15

deploy/crds/crd-certificaterequests.v1beta1.yaml, deploy/crds/crd-certificaterequests.yaml, pkg/apis/certmanager/v1/types_certificaterequest.go, pkg/internal/apis/certmanager/validation/BUILD.bazel, pkg/internal/apis/certmanager/validation/certificate.go, pkg/internal/apis/certmanager/validation/certificaterequest.go, pkg/internal/apis/certmanager/validation/clusterissuer.go, pkg/internal/apis/certmanager/validation/issuer.go, pkg/internal/apis/certmanager/validation/register.go, pkg/util/pki/BUILD.bazel, pkg/util/pki/csr.go, pkg/util/pki/csr_test.go, pkg/util/pki/generate_test.go, pkg/util/pki/keyusage.go, pkg/webhook/handlers/validation.go, pkg/webhook/handlers/validation_test.go, test/integration/BUILD.bazel, test/integration/validation/BUILD.bazel, test/integration/validation/certificaterequest_test.go
This encodes the ExtKeyUsages into the CSR so supported issuers can pick those up and assign them.
Fixes https://github.com/jetstack/cert-manager/issues/3136 
~~From my research is isn't possible to define the "old" key usages into the CSR. Prove me wrong is your mission ;)~~
I read more code in the evening, it works :D 
```release-note
Add key usages into the CSR body
```
=> Extended key usages into CSR

README.md
Remove the warning from the README around API stability 🎉
```release-note
Remove stability warning from README for v1.0
```
/milestone v1.0
=> Remove pre-1.0 stability warning

pkg/webhook/server/server.go
Do internal version conversion in the conversion webhook
fixes https://kubernetes.slack.com/archives/C4NV3DWUC/p1599054237050400
This will patch the CI issue in #3241 also
```release-note
Fix conversion webhook when given v1beta1 requests
```
=> Cast conversion request in the correct API group

cmd/cainjector/app/start.go
Reverts jetstack/cert-manager#3187
Fixes: https://github.com/jetstack/cert-manager/issues/3251
```release-note
Revert de-duplication of cainjector leader-election to fix scenario where it crashes at startup due to broken webhook.
```
=> Revert "Refactor the cainjector to only have 1 leader election"

pkg/util/pki/csr.go, pkg/util/pki/csr_test.go
This fixes two dropped `err` variables in `pkg/util/pki`.
```release-note
NONE
```
=> pkg/util/pki: fix dropped errors

pkg/webhook/handlers/BUILD.bazel, pkg/webhook/handlers/conversion.go, pkg/webhook/handlers/conversion_test.go, pkg/webhook/handlers/interfaces.go, pkg/webhook/server/BUILD.bazel, pkg/webhook/server/server.go, pkg/webhook/server/server_test.go
We had assumed that there were conversions for the ConversionReview types, 
but there are not.
The unit tests revealed that.
So instead I've refactored the schema based conversion webhook dependency to have ConversionReview version specific methods which dispatch to a common method that performs the conversion of the object list.
Fixes: https://github.com/jetstack/cert-manager/issues/3244
```release-note
NONE
```
=> Use separate methods for each ConversionReview type

pkg/util/pki/csr.go, pkg/util/pki/csr_test.go
This fixes an ASN `0.` which got added it no extended key usages got requested in the certificate
Fixes https://github.com/jetstack/cert-manager/issues/3260
```release-note
Do not encode EextendedKeyUsage in the CSR is none is needed
```
=> Only encode EKUs if there are EKUs to be encoded

pkg/internal/apis/certmanager/validation/BUILD.bazel, pkg/internal/apis/certmanager/validation/certificaterequest.go, pkg/internal/apis/certmanager/validation/certificaterequest_test.go, pkg/util/pki/csr_test.go
Fixes the case where the CSR is invalid when both "signing" and "digital signature" are set. They are the same in x509.
This also adds some unit tests to test this validation.
fixes https://github.com/jetstack/cert-manager/issues/3274
```release-note
Fixes incorrect CSR validation when both "signing" and "digital signature" are set
```
=> Fix double "signing" KU validation

.gitignore
Because I keep messing up
This is added by the e2e tests and should be ignored
```release-note
NONE
```
=> Add _artifacts/ to the .gitignore

pkg/acme/BUILD.bazel, pkg/acme/accounts/BUILD.bazel, pkg/acme/accounts/client.go, pkg/acme/client/BUILD.bazel, pkg/acme/client/interfaces.go, pkg/acme/util.go, pkg/acme/util/BUILD.bazel, pkg/acme/util/util.go
This improves the logic added in #3215 to:
* be used in the correct place (insert facepalm)
* stop the Go retry logic after 10 attempts, some calls ended up with an infinite retry
fixes #3267
Let's backport this to v1.0 as many hit this bug
```release-note
Improve ACME backoff logic + prevent infinity retry without surfacing errors
```
=> Implement ACME backoff in the correct place + improve logic

devel/ci-run-e2e.sh, test/e2e/suite/conformance/certificates/featureset.go, test/e2e/suite/conformance/certificates/suite.go, test/e2e/suite/conformance/certificates/venafi/BUILD.bazel, test/e2e/suite/conformance/certificates/venafi/venafi.go, test/e2e/suite/issuers/venafi/tpp/certificate.go
Set up new credentials inside the CI cluster. Tests are passing again!
FIxes https://github.com/jetstack/cert-manager/issues/2175
```release-note
Run e2e tests against Venafi TPP
```
/kind cleanup
=> Remove the Venafi e2e skip

CONTRIBUTING.md
Looking at contributing.md the conference I realized a link to the actual contributing docs was missing.
```release-note
NONE
```
=> Link to contributing site in contributing.md

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml, deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml, deploy/charts/cert-manager/values.yaml
Because webhooks add to API request latency, they should evaluate as
quickly as possible. `timeoutSeconds` allows configuring how long the
API server should wait for a webhook to respond before treating the call
as a failure.
The default values from Kubernetes are, however, too large. For
`admissionregistration.k8s.io/v1` the default value is 10 seconds while
for `admissionregistration.k8s.io/v1beta1` is 30 seconds!
This custom/default value of 10 seconds should be more than enough for
standard installs.
```release-note
Helm: Allow custom timeout value for webhook calls
```
=> Allow custom timeout value for webhook calls

cmd/controller/app/controller.go, cmd/controller/app/options/options.go, pkg/controller/acmechallenges/controller.go, pkg/controller/acmechallenges/sync.go, pkg/controller/context.go
This PR makes it possible to configure the time cert-manager should wait between checking if a ACME dns entry exists instead of the static 10 seconds.
Why we need this:
At our org new dns entries are only synced every 2 hours from the internal DNS servers with the external dns server (do not ask why). With the default time the controller logs will be filled up with a lot of error messages.
I messed up the old PR when i rebased the old branch. Sorry for the inconvenience
```release-note
make ACME dns01 propagation check period configurable 
```
/kind feature
=> make ACME dns01 propagation check period configurable 

.gitignore
Fix a typo made in #3320 
```release-note
NONE
```
/kind cleanup
=> Fix typo in _artifacts

pkg/internal/apis/certmanager/validation/certificaterequest.go, pkg/internal/apis/certmanager/validation/certificaterequest_test.go
Patch mistake made in patchDuplicateKeyUsage and write tests for it for the case of a double signing key usage.
fixes https://github.com/jetstack/cert-manager/issues/3274
Was made before some error in the logic made it not fully functional.
/cherry-pick v1.0
```release-note
Fix logic in patchDuplicateKeyUsage when signing and digital signature were set
```
=> Patch mistake made in patchDuplicateKeyUsage

test/e2e/suite/conformance/certificates/venaficloud/cloud.go
Due to Venafi Cloud being a quite old PR a v1alpha2 API call got into the e2e codebase on delete. This caused the legacy version to fail to run tests as v1alpha2 was not installed. Causing the tests to fail on k8s <1.16.
This PR fixes that mistake.
```release-note
NONE
```
=> Fix delete call for Venafi Cloud e2e

pkg/issuer/acme/dns/route53/fixtures_test.go, pkg/issuer/acme/dns/route53/route53.go, pkg/issuer/acme/dns/route53/route53_test.go, pkg/issuer/acme/dns/util/BUILD.bazel, pkg/issuer/acme/dns/util/dns.go, pkg/issuer/acme/dns/util/dns_test.go
Changes:
1. When there are multiple route53 hosted top zone and delegated
zones within the same account, cert-manager incorrectly uses
the top level domain as auth zone for which it doesn't have perms.
This DOSes AWS's IAM API.
2. This change adds the best match in determining auth zone while
looking up hosted zone IDs.
3. Defines a GetBestMatch util function to perform longest domain
matches.
4. Adds test cases
```release-note
Fix bug in AWS route53 zone lookup that caused too many IAM requests
```
Fixes https://github.com/jetstack/cert-manager/issues/3353
Signed-off-by: Supriya Premkumar <supriyapremkumar1@gmail.com>
=> Fix auth zone hostedZoneID lookups.

test/e2e/e2e_test.go
I added some new validation checks to the TPP addon configuration, 
but the tests still ran, despite my deliberate mistakes in the supplied TPP config.
This makes the e2e tests fail fast if the validation fails.
```release-note
NONE
```
=> Fail early when e2e flag validation fails

pkg/issuer/venafi/setup.go, pkg/issuer/venafi/setup_test.go
And always set a meaningful error message on the condition when the issuer setup
has failed.
Previously it would only set the Ready condition: false if there was a Ping failure.
Not if there was an error during the client setup, which implicitly connects to the API and performs authentication steps.
This makes it much easier to debug TPP e2e test failures because the issuer Ready condition will now correctly be added to the test failure output when the venafi addon fails to wait for the issuer to become ready. E.g.
```
• Failure in Spec Setup (BeforeEach) [60.109 seconds]                                                                                                                                                                                     
[cert-manager] [Venafi] [TPP] …
```
=> Always set the ready condition on Venafi issuer

pkg/issuer/venafi/client/venaficlient.go, pkg/issuer/venafi/client/venaficlient_test.go, test/e2e/framework/config/venafi.go, test/e2e/suite/issuers/venafi/addon/tpp.go
Add support for access-token credentials. This is for users who have configured TPP with refresh tokens disabled and / or with a long lived access token which they prefer to refresh using an external process.
The access-token is generated using `vcert getcred`, as described in the [draft documentation](https://github.com/cert-manager/website/pull/346).
This PR does not add any validation of the supplied credentials. I assumed that vcert library would do that, but it does not, for example validate that you only supply one credential mechanism. 
I've added support for access-token credentials to the E2E tests, and I've run them locally.
Part of: #3140 
See draft documentation at: https://github.com/cert-manager/website/pull/346/files
```release-note
TPP issuer now supports …
```
=> Add support for long lived TPP access-token credentials

deploy/crds/crd-certificates.v1beta1.yaml, deploy/crds/crd-certificates.yaml, pkg/apis/certmanager/v1/types_certificate.go, pkg/apis/certmanager/v1/zz_generated.deepcopy.go, pkg/apis/certmanager/v1alpha2/types_certificate.go, pkg/apis/certmanager/v1alpha2/zz_generated.deepcopy.go, pkg/apis/certmanager/v1alpha3/types_certificate.go, pkg/apis/certmanager/v1alpha3/zz_generated.deepcopy.go, pkg/apis/certmanager/v1beta1/types_certificate.go, pkg/apis/certmanager/v1beta1/zz_generated.deepcopy.go, pkg/internal/apis/certmanager/types_certificate.go, pkg/internal/apis/certmanager/v1/zz_generated.conversion.go, pkg/internal/apis/certmanager/v1alpha2/zz_generated.conversion.go, pkg/internal/apis/certmanager/v1alpha3/zz_generated.conversion.go, pkg/internal/apis/certmanager/v1beta1/zz_generated.conversion.go, pkg/internal/apis/certmanager/zz_generated.deepcopy.go, pkg/util/pki/csr.go, pkg/util/pki/csr_test.go
This PR intends to fix #3301 by adding a new `encode_usages_in_request` option to certificates.
```release-note
Add encodeUsagesInRequest to Certificate spec to disable encoding usages in the CSR
```
=> Add encodeUsagesInRequest to Certificate spec (fix #3301)

build/BUILD.bazel, build/licensing.bzl, hack/boilerplate/BUILD.bazel, hack/build/print-workspace-status.sh
This adds a timestamped license boilerplate option used in static manifests.
fixes https://github.com/jetstack/cert-manager/issues/3263
```release-note
Put current year into manifest license
```
=> Timestamp the static manifest's licences

cmd/controller/app/controller.go, cmd/controller/app/options/options.go
With the new controllers independently checking and setting state we caused more requests to be made to the API.
In large deployments this will cause a lot of throttling errors. Setting it much higher for all users would not be a good idea.
So I decided to make it a config flag on the controller.
```release-note
Make Kubernetes API QPS throttling configurable
```
=> Make Kubernetes API QPS throtteling configurable

hack/build/print-workspace-status.sh
With git log signatures enabled, in my `.gitconfig` file:
``` 
[log]
showSignature = true
```
...the build script would fail...
```
./devel/addon/certmanager/install.sh
...
Target //devel/addon/certmanager:bundle up-to-date (nothing to build)
INFO: Elapsed time: 4.904s, Critical Path: 4.40s
INFO: 25 processes: 1 internal, 24 linux-sandbox.
INFO: Build completed successfully, 25 total actions
INFO: Build completed successfully, 25 total actions
/tmp/tmp.1romCJipzn: line 9: export: `gpg:=         There is no indication that the signature belongs to the owner.': not a valid identifier
```
This patch disables the printing of signatures in the command which gets the copyright YEAR of the last revision,
introduced in https://github.com/jetstack/cert-manager/pull/3357
/kind cleanup …
=> Suppress GPG signatures when getting the git last revision year

cmd/controller/app/controller.go
This is a version of https://github.com/jetstack/cert-manager/pull/3398 that sets the resync period to 10 hours without making it configurable as there is not much use into having it as a flag.
```release-note
Set the resync periods of informers to 10 hours instead of 30 seconds
```
=> Set the resync period to 10 hours

pkg/internal/apis/certmanager/validation/issuer.go, pkg/internal/apis/certmanager/validation/issuer_test.go, pkg/issuer/venafi/client/venaficlient.go
This makes the API validation a little stricter, 
* checks that a Zone is always supplied.
* checks one  (and only) of Issuer.Spec.Venafi.[TPP,Cloud] is set.
* checks that a TPP URL is supplied if TPP is configured
I considered whether this is backwards compatible and decided that it kind of is, 
since these broken configurations would previously have resulted in failures in the Issuer and CertificateRequest controllers anyway.
Part of: #3148
```release-note
Improved API validation for Venafi Issuer configuration
```
=> Add API validation for Venafi Issuer config

pkg/controller/acmechallenges/scheduler/scheduler.go, pkg/controller/acmechallenges/scheduler/scheduler_test.go
Found this one in testing, when you change the max-concurrent-challenges value to a lower one that challenges currently in progress you end up with a negative number for a slice index,
This fixes this preventing a panic() from stopping cert-manager
```release-note
Fix a panic when changing the max concurrent challenges to a lower value
```
/kind bug
=> Fix a panic when changing the max concurrent challenges

pkg/issuer/acme/dns/clouddns/clouddns.go
Fixes a missing log value in the struct
Was an oversight from the improved logging
Fixes #3393 (nil pointer)
/cherry-pick release-1.0
```release-note
Fix nil pointer error in Cloud DNS when specific config was used.
```
=> Fix missing log in struct

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/values.yaml
Signed-off-by: Michael Hill <mhill@betterview.net>
This PR adds the ability to specify `podLabels` for the `webhook` and `cainjector` deployments when installing cert-manager using Helm. Specifying labels on these pods is sometimes necessary (e.g. to support some network policy configurations).
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: N/A
N/A
```release-note
Adds ability to Helm chart to set podLabels for the webhook and cainjector deployments
```
=> Adds ability to Helm chart to set podLabels for the webhook and cainjector deployments

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature-request.md
When going through issues I often spend a lot of time cleaning up the text in there to be more readable using code blocks or removing boilerplate. By looking at the most made mistakes I tried to improve our templates this way.
Suggestions welcome!
```release-note
NONE
```
/kind cleanup
=> Change issue templates to use HTML comments + tip about code blocks

pkg/acme/util/BUILD.bazel, pkg/acme/util/util.go, pkg/acme/util/util_test.go
If an error is thrown the system now retries for 10 times often being ~15 seconds, for a blocking function this is quite long.
On creating a lot of ACME resources this might be limiting the controllers from functioning correctly.
Fixes https://github.com/jetstack/cert-manager/issues/3218
This replaces the built in logic with a custom one that will do a few checks. Totally disabling it causes too many errors to be surfaced as invalid tokens often happen (especially in Pebble by design) and should be retried immediately. We cannot read the body of the error thus it looks at the HTTP status code to see if it is the one matching the token issues, if so it retries only less and faster than before. Any other status …
=> Disable Go's ACME retry logic

deploy/crds/crd-clusterissuers.v1beta1.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.v1beta1.yaml, deploy/crds/crd-issuers.yaml, deploy/crds/crd-orders.v1beta1.yaml, deploy/crds/crd-orders.yaml, pkg/apis/acme/v1/types_issuer.go, pkg/apis/acme/v1/types_order.go, pkg/apis/acme/v1/zz_generated.deepcopy.go, pkg/apis/acme/v1alpha2/types_issuer.go, pkg/apis/acme/v1alpha2/types_order.go, pkg/apis/acme/v1alpha2/zz_generated.deepcopy.go, pkg/apis/acme/v1alpha3/types_issuer.go, pkg/apis/acme/v1alpha3/types_order.go, pkg/apis/acme/v1alpha3/zz_generated.deepcopy.go, pkg/apis/acme/v1beta1/types_issuer.go, pkg/apis/acme/v1beta1/types_order.go, pkg/apis/acme/v1beta1/zz_generated.deepcopy.go, pkg/controller/acmeorders/sync.go, pkg/controller/certificaterequests/acme/acme.go, pkg/controller/certificaterequests/acme/acme_test.go, pkg/internal/apis/acme/types_issuer.go, pkg/internal/apis/acme/types_order.go, pkg/internal/apis/acme/v1/zz_generated.conversion.go, pkg/internal/apis/acme/v1alpha2/zz_generated.conversion.go, pkg/internal/apis/acme/v1alpha3/zz_generated.conversion.go, pkg/internal/apis/acme/v1beta1/zz_generated.conversion.go, pkg/internal/apis/acme/zz_generated.deepcopy.go, test/e2e/suite/issuers/acme/certificate/BUILD.bazel, test/e2e/suite/issuers/acme/certificate/notafter.go
Add a Not After date request to ACME, currently not supported by let's encrypt but it is by Step CA and allows it to be used once a CA adopts it.
fixes https://github.com/jetstack/cert-manager/issues/3092
Would love some thoughts on how to enable/disable this as it is is allowed per ACME spec to error if it is set but not supported
```release-note
Add option to pass the Certificate duration to ACME (not supported by Let's Encrypt yet)
```
=> Add duration into ACME

pkg/issuer/acme/dns/route53/BUILD.bazel, pkg/issuer/acme/dns/route53/fixtures_test.go, pkg/issuer/acme/dns/route53/route53.go, pkg/issuer/acme/dns/route53/route53_test.go, pkg/issuer/acme/dns/route53/testutil_test.go
**Goal**: in #3222, we realized that some errors returned by aws-sdk-go would contain a request id. And since the Challenge controller updates the status using this error and that the request id changes for every request, the Challenge would get resynced over and over.
Here is an example of two errors (stringified) returned by [Present](https://github.com/maelvls/cert-manager/blob/d63b12f0334593c84608e9ea6b097959db6da631/pkg/issuer/acme/dns/route53/route53.go#L182-L185) would look like this; the only difference is the request id:
```
Failed to change Route 53 record set: AccessDenied: [...]\n\tstatus code: 403, request id: 5de26eaf-ae10-47fa-ac63-78d5d661f471
Failed to change Route 53 record set: AccessDenied: [...]\n\tstatus code: 403, request id: e40a0163-0055-4331-acff-cf0add32d971
``` …
=> Strip X-Amzn-RequestId to avoid spurious challenge updates

pkg/internal/vault/vault.go, pkg/internal/vault/vault_test.go
This patch changes certificate data (`CertificateRequest`, `Secret`, ...) issued with Vault issuer as follows:
- `ca.crt` (ca): a root certificate, returned in `ca_chain` from Vault.
i.e. `ca.crt` should be a single certificate represents a root of certificate chain, which can be included into clients' trust store.
- `tls.crt` (certificate): a leaf certificate, plus intermediate certificates if available in `ca_chain`
i.e. `tls.crt` should not include a root certificate
This is a breaking change; Vault issuer had included an issuing CA as a chain in `tls.crt`, but after this change it will no longer include a root certificate when the issuing CA is not an intermediate. For `ca.crt`, it had included a issuing CA only, which can be an intermediate. …
=> Handle Vault issuer working as intermediate correctly

pkg/controller/certificates/internal/test/test.go, pkg/controller/certificates/issuing/issuing_controller.go, pkg/controller/certificates/issuing/issuing_controller_test.go
| This PR is part of the work on PR https://github.com/jetstack/cert-manager/pull/3444 |
| ---- |
**Goal**: after hours and hours of reading logs, I [discovered](https://github.com/jetstack/cert-manager/pull/3444#issuecomment-727598771) an unexpected behavior of the issuing controller: it would update the certificate's status when the certificate request has a failure ("Reason = Failed"), but the controller might have picked up an out-of-date certificate request. The consequence is that the issuing controller would set the certificate to "Issuing = False". This bug happens when a re-issuance is triggered with an old failing certificate request still around.
This PR adds a unit test that reproduces the issue; I'll then propose a fix to it, which is just moving a block of lines 13 lines …
=> Bug: the issuing controller does not wait until the request matches the certificate before setting the certificate to "Issuing = False"

deploy/crds/crd-certificates.v1beta1.yaml, deploy/crds/crd-certificates.yaml, pkg/apis/certmanager/v1/types_certificate.go, pkg/apis/certmanager/v1alpha3/types_certificate.go, pkg/controller/certificates/internal/secretsmanager/keystore.go, pkg/controller/certificates/internal/secretsmanager/keystore_test.go, pkg/controller/certificates/internal/secretsmanager/secret.go
Add support for creation of PKCS12 truststore.p12 using Certificate Authority.  This implementations follows the same pattern as the creation of truststore.jks and leverages the go-pkcs12 EncodeTrustStore function to produce a PKCS12 trust store that is compatible with Java 8 and greater.
fixes #3373
```release-note
Add creation of PKCS12 truststore.p12 using Certificate Authority
```
Signed-off-by: David Handermann <exceptionfactory@gmail.com>
=> Add creation of truststore.p12 from CA

devel/cluster/create-kind.sh
Adds Kubernetes 1.20 to the scripts so we can start running e2e tests against it
```release-note
NONE
```
=> Add Kubernetes 1.20 to the kind setup script

pkg/issuer/venafi/client/request.go, pkg/util/useragent.go
Remove Jetstaqck from the User Agent now it's under the CNCF
fixes https://github.com/jetstack/cert-manager/issues/3480
```release-note
Remove Jetstack from user-agent fields
```
=> Rename the User Agent fields

pkg/apis/certmanager/v1/types.go, pkg/controller/ingress-shim/BUILD.bazel, pkg/controller/ingress-shim/helper.go, pkg/controller/ingress-shim/helper_test.go, pkg/controller/ingress-shim/sync.go, pkg/controller/ingress-shim/sync_test.go, test/e2e/suite/conformance/certificates/tests.go
Part of: #3396
```release-note
The ingress-shim now checks for `cert-manager.io/duration` and `cert-manager.io/renew-before` annotations and uses those values to set the Certificate.Spec.Duration and Certificate.Spec.RenewBefore fields.
```
=> Add duration and renew-before Ingress annotations to set those fields on the Certificate

pkg/controller/certificaterequests/acme/BUILD.bazel, pkg/controller/certificaterequests/acme/acme.go, pkg/controller/certificaterequests/acme/acme_test.go
Added a check for the length of Order.Status.Certificate before attempting to decode it and copy it to the CertificateRequest.
I also considered adding a Ready condition to the Order which would only be set to true once all the ACME operations had been completed by the order controller.
That might be a cleaner way for the certificaterequest-controller to know when it should examine the Order.
Fixes: #2667
```release-note
NONE
```
=> Wait for order-controller to add certificate data to the Order

deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml, deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml
We now can use admissionregistration.k8s.io/v1 in all cases, removing the ugly helm hack which we put into place
Part of #3413
https://github.com/jetstack/cert-manager/pull/3507 went a bit too far, this is a lite version
```release-note
Always install using admissionregistration.k8s.io/v1
```
=> Remove Helm hack for webhook API versions

deploy/manifests/BUILD.bazel
When releasing v1.2.0-alpha.0 we found a few file names had a bad name. This PR fixes the output for the static manifests which was caused in the cleanup of the legacy release.
```release-note
NONE
```
=> Fix release tar content of manifests

hack/verify-codegen.sh
Added a regex to the diff to ignore Copyright lines for changes to avoid a new year making our testing go red. 
fixes https://github.com/jetstack/cert-manager/issues/3554
Happy 2021
```release-note
NONE
```
/kind cleanup
=> Fix verify-codegen.sh to ignore Copyright lines

pkg/controller/cainjector/sources.go
Supplying just a name, rather than a namespace/name, for a cainjector
source reference, results in the generic error message "invalid
certificate name". This condition is detected on its own branch so we
can be more specific.
```release-note
NONE
```
=> Minor log message clarification

cmd/ctl/BUILD.bazel, cmd/ctl/cmd/cmd.go, cmd/ctl/pkg/inspect/BUILD.bazel, cmd/ctl/pkg/inspect/inspect.go, cmd/ctl/pkg/inspect/secret/BUILD.bazel, cmd/ctl/pkg/inspect/secret/secret.go, cmd/ctl/pkg/inspect/secret/secret_test.go, cmd/ctl/pkg/inspect/secret/util.go, cmd/ctl/pkg/inspect/secret/util_test.go, pkg/api/util/usages.go, pkg/controller/acmeorders/controller.go
How many times have you done `echo ... | base64 -d | openssl x509 --noout --text`? Yup that's right!
This PR aims to print info about a cert in a Kubernetes secret
example output (WIP)
```
user@penguin ~/g/s/g/j/cert-manager> go run ./cmd/ctl/ inspect secret --namespace dispatch princess-tls
Valid for:
DNS Names: 
- princess.maartje.dev
URIs: <none>
IP Addresses: <none>
Email Addresses: 
- maartje@eyskens.me
- maartje@jetstack.io
Usages: 
- signing
- key encipherment
- server auth
- client auth
- netscape sgc
Validity period:
Not Before: Wed, 25 Nov 2020 15:50:07 UTC
Not After: Wed, 25 Nov 2020 16:50:07 UTC
Issued By:
Common Name             Jetstack Royal CA
Organization            <none>
OrganizationalUnit      <none>
Country: …
```
=> Add `inspect secret` command

deploy/crds/crd-certificaterequests.yaml, deploy/crds/crd-certificates.yaml, deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, deploy/crds/crd-orders.yaml
**What this PR does / why we need it**:go
This 1dda category names to our CRDs to they appear in `kubectl get all` and `kubectl get cert-manager` which is quite easy for debugging issues!
```
user@mect-l001 ~/g/s/g/m/c/acme> k get cert-manager
NAME                                                      STATE     AGE
order.acme.cert-manager.io/local-test2-896bh-2961499243   errored   3s
NAME                            READY   AGE
issuer.cert-manager.io/pebble   True    3s
NAME                                                   READY   AGE
certificaterequest.cert-manager.io/local-test2-896bh   False   6s
NAME                                      READY   SECRET      AGE
certificate.cert-manager.io/local-test2   False   localtls2   6s
user@mect-l001 ~/g/s/g/m/c/acme> k get acme
NAME …
```
=> Add CRD categories

pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/util/dns.go, pkg/issuer/acme/dns/util/wait.go, pkg/issuer/acme/dns/util/wait_test.go
We always resolved 1 level of CNAME follows,. this changes that logic to keep looking for CNAMEs. If there is a potential recursive it will error out.
fixes https://github.com/jetstack/cert-manager/issues/3098
Needs some testing to be written as the functionality is sensitive to infinite loops.
```release-note
Make CNAME Follow recursive in DNS01 checker
```
=> Make CNAME resolver recursive

pkg/controller/ingress-shim/sync.go, pkg/controller/ingress-shim/sync_test.go
Allows for certificates to be created/updated for valid `Ingress.spec.tls` entries even if there are some invalid ones (missing a secret name of hosts array) in the same spec.
fixes #2009 
There would now be a `BadConfig` Ingress event for each invalid TLS entry rather than once for the whole Ingress and the TLS block validation happens [separately for each entry](https://github.com/irbekrm/cert-manager/blob/2009_skip_invalid_ingress_tls_entries/pkg/controller/ingress-shim/sync.go#L144)
I have manually tested (with nginx ingress) that if either a new Ingress resource with some invalid TLS entries is created or an existing one is updated …
=> Skips invalid Ingress tls entries instead of invalidating the Ingress

deploy/crds/crd-certificaterequests.yaml, deploy/crds/crd-certificates.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, pkg/apis/certmanager/v1/types_certificate.go, pkg/apis/certmanager/v1/types_certificaterequest.go, pkg/apis/certmanager/v1/types_issuer.go, pkg/apis/certmanager/v1alpha2/types_certificate.go, pkg/apis/certmanager/v1alpha2/types_certificaterequest.go, pkg/apis/certmanager/v1alpha2/types_issuer.go, pkg/apis/certmanager/v1alpha3/types_certificate.go, pkg/apis/certmanager/v1alpha3/types_certificaterequest.go, pkg/apis/certmanager/v1alpha3/types_issuer.go, pkg/apis/certmanager/v1beta1/types_certificate.go, pkg/apis/certmanager/v1beta1/types_certificaterequest.go, pkg/apis/certmanager/v1beta1/types_issuer.go, pkg/internal/apis/certmanager/types_certificate.go, pkg/internal/apis/certmanager/types_certificaterequest.go, pkg/internal/apis/certmanager/types_issuer.go
**What this PR does / why we need it**: fix the doc
- Use backticks, not single/double quotes for enum values
- Fix allowed values for encoding and key algorithm
At https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificatePrivateKey
> algorithm: Algorithm is the private key algorithm of the corresponding private key for this certificate. If provided, allowed values are either “rsa” or “ecdsa” If algorithm is specified and size is not provided, key size of 256 will be used for “ecdsa” key algorithm and key size of 2048 will be used for “rsa” key algorithm.
> size: Size is the key bit size of the corresponding private key for this certificate. If algorithm is set to RSA, valid values are 2048, 4096 or 8192, and will default to 2048 if not specified. If algorithm is set …
=> Fix comments for docs on types_certificate.go

deploy/charts/cert-manager/templates/BUILD.bazel, deploy/manifests/BUILD.bazel
We had inadvertently broken [the `installCRDs` mechanism ](https://cert-manager.io/next-docs/installation/kubernetes/#installing-with-helm), which works by  wrapping the whole `crds.yaml` content in an `{{ if }}` statement.
The `{{ if }}` block is added using a bazel `modify_file` rule.
This oversight was probably due to that `modify_file` rule also adding an  `{{ if }}` clause to test for legacy versions of Kubernetes.
I've re-instated it, without the test for Kubernetes versions.
Fixes: https://github.com/jetstack/cert-manager/issues/3627
```release-note
NONE
```
=> Fix duplication of the CRD definitions in cert-manager.yaml

deploy/crds/crd-certificates.yaml, pkg/apis/certmanager/v1/types_certificate.go, pkg/apis/certmanager/v1alpha2/types_certificate.go, pkg/apis/certmanager/v1alpha3/types_certificate.go, pkg/apis/certmanager/v1beta1/types_certificate.go
See #3644 for more context- we observed an issue when upgrading `cert-manager` using Helm due to [failed type conversion of the `minimum` and `maximum` fields in CRDs](https://github.com/helm/helm/issues/5806).
I have removed `minimum` and `maximum` validation fields from `Certificate.spec.privateKey.size` (for all four api versions that we have). As I understand, those fields were redundant as we are performing the actual validation using the [validation webhook](https://github.com/jetstack/cert-manager/blob/master/pkg/internal/apis/certmanager/validation/certificate.go#L64)- also they don't represent the correct values (a valid key size is not in range (0, 8192)).
fixes #3644
I have tested this manually, by …
=> Fix Helm chart type conversion bug 

test/e2e/e2e_test.go, test/e2e/suite/conformance/certificates/venafi/venafi.go, test/e2e/suite/issuers/venafi/tpp/doc.go
We're having some flaky test issues with the TPP test server and we have disabled the TPP E2E tests so that we can get PRs merged:
* https://github.com/jetstack/cert-manager/issues/3555
But it would be useful to be able to run the tests on an ad-hoc basis, especially to check whether the TPP server issue may have been fixed, 
and to attempt to run the tests for PRs that specifically affect the TPP Issuer.
More generally, it will be useful to be able to mark tests or groups of Flaky tests, without having to make changes to the testing infra repo.
For that reason, I have simply copied the mechanism from Kubernetes:
* https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/flaky-tests.md
I'll make a separate PR to add a non-blocking prow job targeting …
=> Label all the Venafi TPP tests so that they can be run in a separate, non-merge-blocking, prow job

cmd/controller/app/controller.go, cmd/controller/app/options/BUILD.bazel, cmd/controller/app/options/options.go, pkg/controller/certificates/readiness/readiness_controller.go, pkg/controller/context.go
Removes the `--renew-before-expiry` flag that was [deprecated](https://github.com/jetstack/cert-manager/blob/master/cmd/controller/app/options/options.go#L256) in v1.2.0
Users can specify how long before the real expiry a certificate should be renewed using `Certificate.spec.renewBefore` field and if they haven't set that, we use a [default value](https://github.com/jetstack/cert-manager/blob/master/pkg/apis/certmanager/v1/const.go#L32) at the time of [calculating renewal](https://github.com/jetstack/cert-manager/blob/master/pkg/controller/certificates/readiness/readiness_controller.go#L167)- this is already the current behaviour, I have only removed the part that would overrwrite the default value with the one from the flag.
I think the calculation …
=> Removes the deprecated renew-before-expiry flag

pkg/controller/certificaterequests/acme/acme_test.go
This fixes a dropped test error in `pkg/controller/certificaterequests/acme`.
```release-note
NONE
```
=> pkg/controller/certificaterequests/acme: fix dropped test error

cmd/ctl/pkg/inspect/secret/secret_test.go, cmd/ctl/pkg/inspect/secret/util_test.go
Fixes a broken test caused by a hardcoded certificate that has expired.
This isn't a good fix. What we should actually do is use one of our existing utility functions to generate a cert on the fly. However, as this failing test blocks all PRs the quick fix is to regenerate the cert and fix it properly later.
```release-note
NONE
```
=> Fix expired certificate test in kubectl plugin

pkg/util/coverage/faketestdeps.go
Signed-off-by: Mitsuo Heijo <mitsuo.heijo@gmail.com>
Since go1.16, `SetPanicOnExit0` has been added to `testdeps`.
https://github.com/golang/go/commit/4f76fe86756841befb6574ce4bf04113d14389d4
```release-note
NONE
```
=> Fix build on go1.16

deploy/charts/cert-manager/templates/service.yaml
The chart has a config value to specify service monitor port, but doesn't use this value for the service manifest.
```release-note
use port from helm values for service targetPort
```
=> use port from helm value for service targetPort

pkg/util/pki/BUILD.bazel, pkg/util/pki/csr_test.go
While working on https://github.com/jetstack/cert-manager/pull/3475, I found out that `IPAddressesForCertificate` was left alone untested. So I figured I would test it! 😅
```release-note
NONE
```
Still 10 untested functions that contain non-obvious logic in the [pki](https://github.com/jetstack/cert-manager/blob/33a9cbfd36acda31e9117d9879973b7f951c7ee4/pkg/util/pki/csr.go) package (❌ = untested):
- ✅ `IPAddressesForCertificate` (in #3737)
- ~~`URIsForCertificate`~~ (no logic)
- ~~`DNSNamesForCertificate`~~ (no logic)
- ✅ `buildCertificate`
- ❌ `URLsFromStrings`
- ~~IPAddressesToString~~ (no logic)
- ❌ `URLsToString`
- ✅ `removeDuplicates`
- ~~`OrganizationForCertificate`~~ (no logic)
- ~~`SubjectForCertificate`~~ (no logic)
- ✅ `BuildKeyUsages`
- ~~`BuildCertManagerKeyUsages`~~ (not much …
=> Add unit tests around IPAddressesForCertificate

deploy/charts/cert-manager/templates/rbac.yaml
The edit aggregate cluster role gave read only permission on challenges and orders resources. This permission is already given by the read aggregate cluster role. This PR replaces the read only permission with a write permission (which was the author’s original intention I guess).
```release-note
Correct permissions on edit aggregate role
```
=> fix: correct permissions on edit aggregate role

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/cainjector-serviceaccount.yaml, deploy/charts/cert-manager/templates/serviceaccount.yaml, deploy/charts/cert-manager/templates/webhook-serviceaccount.yaml, deploy/charts/cert-manager/values.yaml
Adds ability to specify the `automountServiceAccountToken` field on the cert-manager service accounts.
```
Add automountServiceAccountToken field to service accounts in helm chart
```
=> Add automountServiceAccountToken field to ca service accounts

cmd/ctl/pkg/renew/renew.go, deploy/crds/crd-certificates.yaml, pkg/api/util/conditions.go, pkg/apis/certmanager/v1/types_certificate.go, pkg/apis/certmanager/v1alpha2/types_certificate.go, pkg/apis/certmanager/v1alpha3/types_certificate.go, pkg/apis/certmanager/v1beta1/types_certificate.go, pkg/controller/certificates/issuing/issuing_controller.go, pkg/controller/certificates/issuing/issuing_controller_test.go, pkg/controller/certificates/readiness/readiness_controller.go, pkg/controller/certificates/trigger/trigger_controller.go, pkg/controller/certificates/trigger/trigger_controller_test.go, pkg/internal/apis/certmanager/types_certificate.go, pkg/internal/apis/certmanager/v1/zz_generated.conversion.go, pkg/internal/apis/certmanager/v1alpha2/zz_generated.conversion.go, pkg/internal/apis/certmanager/v1alpha3/zz_generated.conversion.go, pkg/internal/apis/certmanager/v1beta1/zz_generated.conversion.go, test/e2e/framework/helper/certificates.go, test/e2e/framework/helper/validate.go, test/e2e/framework/helper/validations/BUILD.bazel, test/e2e/framework/helper/validations/certificates.go, test/integration/certificates/issuing_controller_test.go, test/integration/ctl/ctl_status_certificate_test.go, test/unit/gen/certificate.go
fixes #3585 #1551
This PR adds the field `observedGeneration` to Certificate conditions. 
This does not make any functional changes to any of the Certificate controllers, but instead, exposes the Generation of the Certificate when adding/updating a condition. When adding a condition where one with the same type already exists, but the observed generation is different, that condition will be overwritten with the newer generation.
The e2e Certificate is valid func is updated to ensure we get an observed generation we are expecting.
```release-note
Adds an observedGeneration field to all Certificate conditions. This is set to the generation of that Certificate at the time of updating.
```
=> Certificate condition observed generation

pkg/issuer/acme/dns/clouddns/clouddns_test.go
If gcloud hasn't been installed, or if it has but the default application credential file
at `.config/gcloud/application_default_credentials.json` hasn't been configured, this test
would segfault since the assertion at the start fails but doesn't stop the test later
attempting to use `testProvider` which is `nil`.
instead, we treat failure at the start as a sign that cloud DNS cannot be tested, and skip
the test while providing an informational error to explain how the test can be run
This makes it easier to get started developing / hacking on cert-manager, as it removes a
step to getting the test suite running for people who've not used google cloud before
/kind bug
```release-note
Skip Google Cloud DNS test when gcloud hasn't been configured
```
=> Skip Google Cloud DNS test when gcloud isn't initialized

deploy/charts/cert-manager/templates/webhook-psp.yaml
It fixes bug with hostNetwork: false in webhook psp
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3324
```release-note
Allow the usage of hostNetwork in the webhook PSP
```
=> fix bug with hostNetwork false in webhook psp

pkg/controller/certificates/trigger/policies/BUILD.bazel, pkg/controller/certificates/trigger/policies/policies.go, pkg/controller/certificates/trigger/policies/policies_test.go, pkg/controller/certificates/trigger/trigger_controller.go, test/integration/certificates/trigger_controller_test.go
See #3603 for context.
When a `Certificate` is being renewed, after a `CertificateRequest` succeeds, `CertificateIssuing` controller updates the `Certficate` including [removing `status.Issuing` condition](https://github.com/jetstack/cert-manager/blob/master/pkg/controller/certificates/issuing/issuing_controller.go#L338). After this, there are 2 possible paths:
1. `CertificateReadiness` controller syncs the updated `Certificate`, updates it including [setting new `status.RenewalTime` value](https://github.com/jetstack/cert-manager/blob/master/pkg/controller/certificates/readiness/readiness_controller.go#L169), then `CertificateTrigger` controller syncs the updated `Certificate` and requeues the `Certificate` to be re-synced at renewal time.
2. …
=> Fix multiple Certificate Requests issue

Makefile
Signed-off-by: Arsh Sharma <arshsharma461@gmail.com>
**What this PR does / why we need it**: Fixes the reference to the non-existent `DOCKER_REPO` env var in the makefile
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes (partly) #3648 
Verified manually by running:
```
make images DOCKER_REGISTRY=something.com/arsh
```
Got this in the final lines of the output:
```
Tagging 130518c203ce75a73173ed8238730033154a508d7f39edbe071d3b76f42db857 as something.com/arsh/cert-manager-acmesolver-amd64:v1.2.0-89-e1e8392d50d1e1
Tagging a41f59e78513c83f51d3d76e6c1bcb9b6e5524686b98b985816e2251dfab6b0b as …
```
=> fix(makefile): updated the docker_repo env var

deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, pkg/api/util/conditions.go, pkg/apis/certmanager/v1/types_issuer.go, pkg/apis/certmanager/v1alpha2/types_issuer.go, pkg/apis/certmanager/v1alpha3/types_issuer.go, pkg/apis/certmanager/v1beta1/types_issuer.go, pkg/internal/apis/certmanager/types_issuer.go, pkg/internal/apis/certmanager/v1/zz_generated.conversion.go, pkg/internal/apis/certmanager/v1alpha2/zz_generated.conversion.go, pkg/internal/apis/certmanager/v1alpha3/zz_generated.conversion.go, pkg/internal/apis/certmanager/v1beta1/zz_generated.conversion.go, pkg/issuer/acme/setup.go, pkg/issuer/ca/setup.go, pkg/issuer/selfsigned/setup.go, pkg/issuer/vault/setup.go, pkg/issuer/venafi/setup.go
fixes #1551 
I haven't added this field to ACME resources since they don't follow the same condition pattern.
I also haven't added this field to the CertificateRequest since it the spec _shouldn't_, and soon _can't_ ever change once created.
```release-note
Adds ObservedGeneration field to all Issuer conditions
```
=> Issuer observed generation

test/acme/dns/fixture.go, test/acme/dns/options.go, test/acme/dns/util.go
[Custom webhooks](https://github.com/cert-manager/webhook-example) provide a relatively easy approach to extend cert-manager acme-challenge to other DNS providers. Some in-house developed DNS providers/integrations may have restrictions, allowing just a few domains to be validated, and often example.com is not one of them.
This PR allows the base DNS name to be set using the new `SetDNSName()` and `SetDNSChallangeKey()` methods **in tests only**. If not set, the default value _"example.com"_ will be used, without changing the original behavior. 
```release-note
NONE
```
=> tests: allow setting DNSName and ChallengeKey for webhook integration tests

design/20210203.certificate-request-identity.md
Signed-off-by: joshvanl <vleeuwenjoshua@gmail.com>
This PR contains a design document for the first iteration of implementing identity to certificate requests in cert-manager.
/cc @meyskens @jakexks @munnerz @maelvls @wallrj @irbekrm 
related: https://github.com/jetstack/cert-manager/issues/3473
```release-note
NONE
```
=> DESIGN: CertificateRequest UserInfo fields

deploy/crds/crd-certificaterequests.yaml
This PR changes the behaviour of `kubectl get cr` to now include the username of the requestor, and outputs the issuer name by default without `-o wide`. This makes the output more inline with upstream certificates.k8s.io, and looks better to me :)
```bash
$ kubectl get csr
NAME   AGE   SIGNERNAME                            REQUESTOR          CONDITION
john   24m   kubernetes.io/kube-apiserver-client   kubernetes-admin   Pending
```
```bash
$ kubectl get cr
NAME           READY   ISSUER              REQUESTOR                                         AGE
osm-ca-2fvdl   True    selfsigned-issuer   system:serviceaccount:cert-manager:cert-manager   13m
``` 
```bash
$ kubectl get cr -o wide
NAME           READY   ISSUER              REQUESTOR                                         STATUS …
```
=> Add Requestor to kubectl output, moves Issuer name from wide to default outpt

Makefile
Signed-off-by: Arsh Sharma <arshsharma461@gmail.com>
**What this PR does / why we need it**: Added a target in the Makefile to push images 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes (partly) #3648 
Verified by running:
```
make images_push DOCKER_REGISTRY=something.com/arsh
```
got the following output:
```
Makefile:103: warning: overriding recipe for target 'ctl'
Makefile:84: warning: ignoring old recipe for target 'ctl'
APP_VERSION= \
DOCKER_REGISTRY=something.com/arsh \
bazel run \
--stamp \
--platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 \
//:images.push
INFO: Analyzed target //:images.push (883 packages loaded, 12506 targets …
```
=> feat: added images_push target in Makefile

cmd/controller/app/options/BUILD.bazel, cmd/controller/app/options/options.go, deploy/crds/crd-certificaterequests.yaml, pkg/api/util/conditions.go, pkg/apis/certmanager/v1/types_certificaterequest.go, pkg/apis/certmanager/v1alpha2/types_certificaterequest.go, pkg/apis/certmanager/v1alpha3/types_certificaterequest.go, pkg/apis/certmanager/v1beta1/types_certificaterequest.go, pkg/controller/certificaterequests/BUILD.bazel, pkg/controller/certificaterequests/acme/acme_test.go, pkg/controller/certificaterequests/approver/BUILD.bazel, pkg/controller/certificaterequests/approver/approver.go, pkg/controller/certificaterequests/approver/approver_test.go, pkg/controller/certificaterequests/approver/sync.go, pkg/controller/certificaterequests/ca/ca_test.go, pkg/controller/certificaterequests/selfsigned/selfsigned_test.go, pkg/controller/certificaterequests/sync.go, pkg/controller/certificaterequests/sync_test.go, pkg/controller/certificaterequests/vault/vault_test.go, pkg/controller/certificaterequests/venafi/venafi_test.go, pkg/internal/apis/certmanager/types_certificaterequest.go, pkg/internal/apis/certmanager/validation/certificaterequest.go, pkg/internal/apis/certmanager/validation/certificaterequest_test.go, test/e2e/framework/helper/certificaterequests.go, test/unit/gen/certificaterequest.go
This PR adds the `Approved`, and `Denied` condition type to CertificateRequests. These conditions are managed by a new CertificateRequest controller "approver". Today, this controller will _always_ set the Approved condition to _true_ for all newly created CRs, though in future this will change with the inclusion of automated policy, [see](https://github.com/jetstack/cert-manager/pull/3727).
```bash
NAME             APPROVED   READY   AGE
istio-ca-cz88l   True       True    44m
```
The base CertificateRequest controller will ensure that the Approved condition is present and it is set to _True_, and that the Denied condition is not present. If Approval is not present or it is Denied, it will exit processing this resource. In future, this will mean CRs which fail approval will not be signed …
=> Certificate request approved condition

test/e2e/suite/conformance/certificates/tests.go
Signed-off-by: Lars Lehtonen <lars.lehtonen@gmail.com>
This fixes a dropped error in `test/e2e/suite/conformance/certificates`.
```release-note
NONE
```
=> test/e2e/suite/conformance/certificates: fix dropped error

pkg/controller/certificates/issuing/issuing_controller.go, pkg/controller/certificates/keymanager/keymanager_controller.go, pkg/controller/certificates/metrics/controller.go, pkg/controller/certificates/readiness/readiness_controller.go, pkg/controller/certificates/requestmanager/requestmanager_controller.go, pkg/controller/certificates/trigger/trigger_controller.go
/kind cleanup
/assign @irbekrm @jakexks 
This is a small PR to change the names of the Certificate controllers so that they are consistent with the naming elsewhere in the project.
```release-note
Standardise controller names across the project
```
=> Standardise the name of controllers so there is consistency across the project

deploy/crds/crd-certificates.yaml, pkg/apis/certmanager/v1/types_certificate.go
**What this PR does / why we need it**: 
As requested in the [#cert-manager slack channel](https://kubernetes.slack.com/archives/C4NV3DWUC/p1614862186217000), add documentation for the default renewBefore field to the API docs
Fixes #3734 
```release-note
NONE
```
/area api
=> Clarify the default values for the renewBefore and duration fields

build/images.bzl
Update the distroless/static base image to fix DLA-2542-1, DLA-2509-1, DLA-2424-1
**Which issue this PR fixes**: fixes #3740
```release-note
Update distroless/static base image
```
=> fix bump distroless/static

pkg/controller/certificates/readiness/BUILD.bazel, pkg/controller/certificates/readiness/readiness_controller.go, pkg/controller/certificates/readiness/readiness_controller_test.go
Signed-off-by: OmairK <omairkhan064@gmail.com>
Certificate readiness controller was updating the the status of the certificate even if there was no change. This PR will reduce the unnecessary Certificate updates.
Fixes #3663
```
None
```
=> Certificate Readiness controller only updates certificate's status if there is a change

cmd/ctl/BUILD.bazel, cmd/ctl/cmd/BUILD.bazel, cmd/ctl/cmd/cmd.go, cmd/ctl/pkg/approve/BUILD.bazel, cmd/ctl/pkg/approve/approve.go, cmd/ctl/pkg/approve/approve_test.go, cmd/ctl/pkg/deny/BUILD.bazel, cmd/ctl/pkg/deny/deny.go, cmd/ctl/pkg/deny/deny_test.go
/kind feature
/assign @jakexks @irbekrm @maelvls 
```release-note
Adds `kubectl cert-manager [approve|deny] CLI commands to manually approve or deny CertificateRequests
```
=> Adds kubectl cert-manager [approve|deny] CLI commands

cmd/controller/app/options/BUILD.bazel, cmd/controller/app/options/options.go, deploy/crds/crd-certificates.yaml, pkg/apis/certmanager/v1/types_certificate.go, pkg/apis/certmanager/v1/zz_generated.deepcopy.go, pkg/apis/certmanager/v1alpha2/types_certificate.go, pkg/apis/certmanager/v1alpha2/zz_generated.deepcopy.go, pkg/apis/certmanager/v1alpha3/types_certificate.go, pkg/apis/certmanager/v1alpha3/zz_generated.deepcopy.go, pkg/apis/certmanager/v1beta1/types_certificate.go, pkg/apis/certmanager/v1beta1/zz_generated.deepcopy.go, pkg/controller/certificates/BUILD.bazel, pkg/controller/certificates/revisionmanager/BUILD.bazel, pkg/controller/certificates/revisionmanager/revisionmanager_controller.go, pkg/controller/certificates/revisionmanager/revisionmanager_controller_test.go, pkg/internal/apis/certmanager/types_certificate.go, pkg/internal/apis/certmanager/v1/zz_generated.conversion.go, pkg/internal/apis/certmanager/v1alpha2/zz_generated.conversion.go, pkg/internal/apis/certmanager/v1alpha3/zz_generated.conversion.go, pkg/internal/apis/certmanager/v1beta1/zz_generated.conversion.go, pkg/internal/apis/certmanager/validation/certificate.go, pkg/internal/apis/certmanager/validation/certificate_test.go, pkg/internal/apis/certmanager/zz_generated.deepcopy.go, test/integration/certificates/BUILD.bazel, test/integration/certificates/revisionmanager_controller_test.go, test/unit/gen/certificate.go, test/unit/gen/certificaterequest.go
fixes  #3458
/assign @jakexks 
/kind feature
This PR adds a new Certificate controller that is responsible for cleaning up old CertificateRequests using a new `RevisionHistoryLimit` field.
This optional field will ensure that only x number of old request revisions for a Certificate exist. The field is set to `nil` by default, which won't clean up any CRs. The controller will delete CRs from oldest first, and will ignore CRs if they don't have the annotation or have an invalid value (which shouldn't normally happen). The controller won't trigger if the Certificate isn't in a Ready state so as to not conflict with other processing. The value must be set to 1 or greater- this is to ensure we keep _some_ kind of visibility and doesn't cause potential issues for other controllers.
I'm not 100% …
=> Certificate revision history limit

pkg/controller/certificaterequests/selfsigned/BUILD.bazel, pkg/controller/certificaterequests/selfsigned/selfsigned.go, pkg/controller/certificaterequests/selfsigned/selfsigned_test.go, pkg/controller/ingress-shim/sync.go, pkg/util/pki/csr.go, pkg/util/pki/generate.go
**What this PR does / why we need it**: RFC 5280 states that the issuer field cannot be empty, but this is effectively the default for selfsigned certs where the user doesn't specify any part of the subject DN (and with selfsigned certs, the subject becomes the issuer).
There are also some smaller tweaks to comments I discovered as part of this work.
/kind bug
**Which issue this PR fixes**: fixes #3634 (sort of)
```release-note
selfsigned issuer: warn when certs have empty issuer DNs, in violation of TLS RFC 5280
```
=> selfsigned: warn when certs are issued with empty issuer DNs 

pkg/internal/vault/fake/vault.go, pkg/internal/vault/vault.go, pkg/internal/vault/vault_test.go, pkg/issuer/vault/setup.go
This PR fixes two issues: 
1. Approle login for HashiCorp vault is failing when namespaces were used in vault.  
2. The health check would mark the vault as sealed/un-initialised when the vault token did not have enough access to call the /sys endpoints. 
In order to fix the first issue, I added the `X-VAULT-NAMESPACE` header to the login API call. 
To fix the second issue, I had to move from making use of vault client's `client.Sys().Health()` to making direct API calls like we do for login etc. This is because when token passed to the vault does not have sufficient permissions to call the /sys/* endpoints, vault returns the correct HTTP status code, but an empty JSON response. In vault client's `client.Sys().Health()`, the team is replying purely …
=> Vault health check and namespace fix

pkg/controller/acmechallenges/BUILD.bazel, pkg/controller/acmechallenges/sync.go, pkg/controller/acmeorders/BUILD.bazel, pkg/controller/acmeorders/sync.go, pkg/controller/certificaterequests/BUILD.bazel, pkg/controller/certificaterequests/sync.go, pkg/controller/clusterissuers/BUILD.bazel, pkg/controller/clusterissuers/sync.go, pkg/controller/issuers/BUILD.bazel, pkg/controller/issuers/sync.go
Signed-off-by: salmanahmed404 <salmanahmed404@gmail.com>
**What this PR does / why we need it**
`reflect.DeepEqual` can be replaced with semantic equality checks in few places in controller packages. This PR makes the necessary replacements wherever a related TODO comment was found in the code
Fixes #3809 
**Release Note**
```release-note
None
```
=> Replace reflect.DeepEqual with semantic equality check

WORKSPACE, hack/build/repos.bzl, hack/update-bazel.sh, hack/update-deps.sh, hack/verify-bazel.sh, pkg/internal/api/mutation/BUILD.bazel, pkg/internal/api/validation/BUILD.bazel, test/e2e/BUILD.bazel, test/e2e/images.bzl
Bumps versions of Gazelle, go_rules, Kazel, protobuf.
It should help with #3804.
- Gazelle v0.22.0 [changed default naming convention for generated rules](https://github.com/bazelbuild/bazel-gazelle/releases/tag/v0.22.0). Although the new names seem nicer it would have changed names of our targets, some of which have [public visibility](https://github.com/jetstack/cert-manager/blob/master/pkg/controller/BUILD.bazel#L14), so I set it to [keep the old naming](https://github.com/irbekrm/cert-manager/blob/update_bazel/hack/update-bazel.sh#L46) instead of the new default.
- Gazelle v0.22.0 has [a dependency of `golang.org/x/crypto`](https://github.com/bazelbuild/bazel-gazelle/blob/master/go.sum#L24), so I had to move …
=> Bump versions of Gazelle, go_rules, Kazel, protobuf

pkg/internal/apis/certmanager/validation/plugins/approval.go, pkg/internal/apis/certmanager/validation/plugins/approval_test.go, pkg/internal/apis/certmanager/validation/plugins/plugins.go, pkg/webhook/handlers/interfaces.go, pkg/webhook/handlers/mutation.go, pkg/webhook/handlers/mutation_test.go, pkg/webhook/handlers/validation.go, pkg/webhook/server/server.go, pkg/webhook/server/server_test.go
/kind cleanup
/hold
This PR is rebased on #3785
This PR passes through the request context of the webhook server to admission functions. This is primarily for the approval plugin.
```release-note
NONE
```
=> Webhook validation request context passthrough

pkg/controller/certificates/issuing/issuing_controller.go, pkg/controller/certificates/issuing/issuing_controller_test.go
This PR will mark the issuance of a certificate as failed if the CertificateRequest was denied. This means that denied requests will be retried after a period of time (1 hour), as if it had failed. We only check for the denied condition, if the Ready condition is also not present. This is because some issuers will ignore the Denied condition, and so we should still complete issuance for these issuers.
/kind feature
/assign @munnerz @jakexks @irbekrm @maelvls @wallrj 
/milestone v1.3
```release-note
Retry issuance of Denied CertificateRequests after 1 hour.
```
=> Adds Denied check to CertificateRequests in issuing controller to retry denied requests

.gitignore, pkg/util/pki/csr.go
This patch fixes the CA issuer in case it is working as intermediate, and _the root CA certificate is available_ (best effort).
The current behavior is to assume that the CA issuer is the root CA, and return the issuing CA certificate as CA certificate to clients. This is not optimal when the CA issuer is an intermediate CA.
The wanted behavior in intermediate CA case is described in https://github.com/jetstack/cert-manager/issues/3619#issuecomment-808159467. Fix suggested in this PR uses the last certificate in the CA chain when signing as CA certificate supplied to clients. This should handle the intermediate case more correctly if the CA issuer is configured with the full CA certificate chain: starting with the issuing/signing CA certificate, any …
=> Handle CA issuer working as intermediate correctly 

.gitignore, pkg/util/pki/csr.go
This PR reverts jetstack/cert-manager#3847. As discussed in https://github.com/jetstack/cert-manager/pull/3847#issuecomment-814702622, I went too fast and `/lgtm` from my bed, which led to merging code that could potentially break people's cert-manager deployments.
Our plan is to have the same PR re-opened so that we can have it released for v1.4 (due on Friday 11 June 2021 as per [our timeline](https://docs.google.com/document/d/1Tc5t6ylY9dhXAan1OjOoldeaoys1Yh4Ir710ATfBa5U/edit#bookmark=kix.8a98ch6d7b)).
/cc @munnerz 
/kind cleanup
/area acme/http01
```release-note
NONE
```
=> Revert "Handle CA issuer working as intermediate correctly"

README.md, SECURITY.md, SECURITY_CONTACTS.md
Ideally, `SECURITY.md` will be the central source of truth to answer the
question "How do I report a security vulnerability in a cert-manager project?"
See also #3761 
```release-note
Add a vulnerability reporting process in SECURITY.md
```
=> Add SECURITY.md documenting vuln report process

pkg/issuer/acme/dns/rfc2136/rfc2136.go
Allowes to create Letsencrypt certificates using RFC2136 with multiple dnsNames. Currently the `TXT` records are cleared when adding a new one.
Since `Present` is called for each dnsName it removes the existing `TXT` records for other dnsNames. The new behavior removes the records on `CleanUp` like the DigitalOcean provider does it.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes  #3621
I wasn't able to run the bazel build on NixOS, so this is not tested. Sorry for that, seems like NixOS, podman and bazel don't go along that well...
```release-note
Fix RFC2136 DNS-01 challenges with multiple DNS names
```
=> Fix letsencrypt with rfc2136 and multiple dnsNames

test/e2e/suite/conformance/certificates/venafi/venafi.go, test/e2e/suite/conformance/certificates/venaficloud/cloud.go, test/e2e/suite/issuers/venafi/tpp/doc.go
@simplyzee has now installed a dedicated TPP testing machine and updated our Venafi Cloud account for OutagePREDICT, so we should be able to run the E2E tests reliably for each PR.
I also had to assign the role `OP PKI Administrator` to the `Jetstack Cert-Manager-E2E` user in Venafi Cloud.
```release-note
NONE
```
=> Re-enable E2E tests for the Venafi Issuer

test/e2e/suite/issuers/acme/BUILD.bazel, test/e2e/suite/issuers/acme/certificate/http01.go, test/e2e/suite/issuers/acme/certificate/notafter.go, test/e2e/suite/issuers/acme/certificaterequest/http01.go, test/e2e/suite/issuers/acme/issuer.go, test/e2e/suite/issuers/ca/certificate.go, test/e2e/suite/issuers/ca/certificaterequest.go, test/e2e/suite/issuers/ca/clusterissuer.go, test/e2e/suite/issuers/ca/issuer.go, test/e2e/suite/issuers/selfsigned/certificate.go, test/e2e/suite/issuers/selfsigned/certificaterequest.go, test/e2e/suite/issuers/vault/BUILD.bazel, test/e2e/suite/issuers/vault/certificate/BUILD.bazel, test/e2e/suite/issuers/vault/certificate/approle.go, test/e2e/suite/issuers/vault/certificate/approle_custom_mount.go, test/e2e/suite/issuers/vault/certificaterequest/BUILD.bazel, test/e2e/suite/issuers/vault/certificaterequest/approle.go, test/e2e/suite/issuers/vault/certificaterequest/approle_custom_mount.go, test/e2e/suite/issuers/vault/issuer.go, test/e2e/suite/serving/BUILD.bazel, test/e2e/suite/serving/cainjector.go, test/e2e/util/BUILD.bazel, test/e2e/util/util.go, test/unit/gen/issuer.go
This PR removes a bunch of legacy functions for issuer generation from [`test/e2e/util/util.go`](https://github.com/jetstack/cert-manager/blob/master/test/e2e/util/util.go) as it partially duplicated the functionality in [`test/unit/gen/issuer.go`](https://github.com/jetstack/cert-manager/blob/master/test/unit/gen/issuer.go) and adds some more specific issuer generation functions to `test/unit/gen/issuer.go`.
I hope no-one has been importing these legacy functions - I did not find [external imports on `pkg.go.dev`](https://pkg.go.dev/github.com/jetstack/cert-manager/test/e2e/util?tab=importedby)
This PR was originally part of #3850 which is getting split into multiple PRs.
```release-note
Removes legacy util functions for issuer generation from test/e2e/util/util.go. Use functions in …
```
=> Remove legacy e2e util functions for Issuer creation

deploy/crds/crd-certificates.yaml, pkg/apis/certmanager/v1/types_certificate.go, pkg/apis/certmanager/v1alpha2/types_certificate.go, pkg/apis/certmanager/v1alpha3/types_certificate.go, pkg/apis/certmanager/v1beta1/types_certificate.go, pkg/internal/apis/certmanager/validation/certificate.go, pkg/internal/apis/certmanager/validation/certificate_test.go
This PR tries to fix an issue were `helm upgrade` command seems to not be able to convert the `minimum` value of our new `certificate.spec.revisionHistoryLimit` field, see #3880 
I have removed the `minimum` field and instead moved the validation to of the `revisionHistoryLimit` to the validating webhook, similarly to how we did it in #3647 
In [the related helm discussion](https://github.com/helm/helm/issues/5806#issuecomment-788116838) I see that this issue should have been fixed in Kubernetes `v1.20` and this _does_ seem to be the case. But I guess since we still support Kubernetes from `v1.16` onwards, we will need to fix it somehow. 
Perhaps we could try to backport a fix [in Helm](https://github.com/helm/helm/issues/5806#issuecomment-788146025) as an alternative to moving the …
=> Certificate's revision history limit validated by webhook

LICENSES, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, go.mod, go.sum, hack/build/repos.bzl, pkg/apis/acme/v1/types_issuer.go, pkg/apis/acme/v1alpha2/types_issuer.go, pkg/apis/acme/v1alpha3/types_issuer.go, pkg/apis/acme/v1beta1/types_issuer.go, pkg/internal/apis/acme/types_issuer.go, pkg/internal/apis/certmanager/validation/issuer.go, pkg/internal/apis/certmanager/validation/issuer_test.go, pkg/issuer/acme/setup.go, test/e2e/suite/conformance/certificates/acme/acme.go, test/e2e/suite/issuers/acme/BUILD.bazel, test/e2e/suite/issuers/acme/issuer.go
See #3220  for full context.
Up till now we used a fork of [`golang/crypto`](https://github.com/golang/crypto) with added support for ACME External Account Binding and fetching of ACME preferred certificate chains from @meyskens GitHub account.
This PR:
- uses upstream `golang/crypto` functionality for ACME External Account Binding instead of our own
- uses `golang/crypto` fork from `cert-manager` account instead of @meyskens  account
Notes:
- I have forked the latest `golang/crypto` [to `cert-manager` org](https://github.com/cert-manager/crypto) and cherry-picked @meyskens commit that implements fetching of alternative certificate chains on top of that. We can use this fork till the same functionality [gets implemented upstream](https://go-review.googlesource.com/c/crypto/+/277294/)
- …
=> Use upstream golang/crypto for ACME EAB + move crypto fork to cert-manager org

pkg/controller/acmechallenges/sync.go, pkg/controller/acmeorders/sync.go, pkg/controller/certificates/keymanager/keymanager_controller.go, pkg/controller/certificates/requestmanager/requestmanager_controller.go, pkg/controller/ingress-shim/sync.go
Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>
Uses constants for string literals which get repeated in as the `reason` argument in `k8s.io/client-go/tools/record.EventRecorder.Eventf` function calls.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3620
Should I do this even for arguments which do not get repeated and are only used once @irbekrm?
```release-note
NONE
```
=> chore: used constants for string literals when recording new events

pkg/api/util/conditions.go, pkg/apis/certmanager/v1/types_certificaterequest.go, pkg/apis/certmanager/v1alpha2/types_certificaterequest.go, pkg/apis/certmanager/v1alpha3/types_certificaterequest.go, pkg/apis/certmanager/v1beta1/types_certificaterequest.go, pkg/controller/certificaterequests/acme/acme_test.go, pkg/controller/certificaterequests/ca/ca_test.go, pkg/controller/certificaterequests/selfsigned/selfsigned_test.go, pkg/controller/certificaterequests/sync.go, pkg/controller/certificaterequests/sync_test.go, pkg/controller/certificaterequests/util/reporter.go, pkg/controller/certificaterequests/util/reporter_test.go, pkg/controller/certificaterequests/vault/vault_test.go, pkg/controller/certificaterequests/venafi/venafi_test.go
This PR changes all internal signers so that they set the Ready condition to False with the Reason "RequestDenied" when a CertificateRequest is Denied. This is to keep the same behavior where a terminal state of a CertificateRequest should have a Ready condition.
This should be backported to `release-1.3` and released in `v1.3.1`.
```release-note
Set the Ready condition to False when a CertificateRequest has been denied for all CertificateRequests that reference a cert-manager.io signer
```
=> Set the Ready condition to False when a CertificateRequest has been denied for all CertificateRequests that reference a cert-manager.io signer

test/e2e/suite/conformance/certificates/venaficloud/cloud.go
It looks like the Venafi Cloud e2e tests are failing again since Friday [almost all the periodics](https://testgrid.k8s.io/jetstack-cert-manager-master#ci-cert-manager-e2e-v1-20
) as well as all the presubmits - see for example [here](https://github.com/jetstack/cert-manager/pull/3724#issuecomment-821967538).
Would it make sense to disable these till we fix the flake, so folks can get their PR tests running normally?
I assume we might need to force merge this PR?
=> Temporarily revert "Enable the Venafi Cloud E2E tests"

pkg/util/pki/generate.go, pkg/util/pki/generate_test.go
Also adds/improves doc comments on related functions, and adds tests of
comparisons RSA keys and ECDSA keys. these tests failed as expected
before the function was changed, e.g.:
```text
Executing tests from //pkg/util/pki:go_default_test
---------------------------------------------------
--- FAIL: TestPublicKeysEqualECDSA (0.00s)
generate_test.go:492: got an incorrect match from different curves:
pub1 type: "P-256"
pub2 type: "P-521"
--- FAIL: TestPublicKeysEqualRSA (0.00s)
generate_test.go:560: got an incorrect match from different RSA keys:
pub1: &rsa.PublicKey{N:2293...<snip>...8869, E:65537}
pub2: &rsa.PublicKey{N:2293...<snip>...8869, E:3}
```
**Note for reviewer**: This also changes `PublicKeyMatchesCertificate`, which previously re-implemented the public key matching logic. It …
=> Fix incorrect comparison function for public keys

.gitignore, pkg/util/pki/BUILD.bazel, pkg/util/pki/csr.go, pkg/util/pki/csr_test.go, test/e2e/framework/helper/featureset/featureset.go, test/e2e/framework/helper/validate.go, test/e2e/framework/helper/validations/certificates.go, test/e2e/suite/conformance/certificates/vault/vault_approle.go, test/e2e/suite/issuers/vault/certificate/BUILD.bazel, test/e2e/suite/issuers/vault/certificate/approle.go, test/e2e/suite/issuers/vault/certificate/approle_custom_mount.go
This is a new PR to reapply the changes suggested in https://github.com/jetstack/cert-manager/pull/3847, that were reverted by https://github.com/jetstack/cert-manager/pull/3862. This time tests are added to test the wanted behavior - both unit tests and e2e-tests.
Copying in the PR description from https://github.com/jetstack/cert-manager/pull/3847.
This patch fixes the CA issuer in case it is working as intermediate, and _the root CA certificate is available_ (best effort).
The current behavior is to assume that the CA issuer is the root CA, and return the issuing CA certificate as CA certificate to clients. This is not optimal when the CA issuer is an intermediate CA.
The wanted behavior in intermediate CA case is described in …
=> Handle CA issuer working as intermediate correctly

devel/addon/sample-external-issuer/BUILD.bazel, devel/addon/sample-external-issuer/install.sh
When  https://github.com/cert-manager/sample-external-issuer/pull/15 merges, there will be a Docker image and an `install.yaml` file for the sample-external-issuer, allowing us to simplify the installation in cert-manager E2E tests.
No longer any need to `git clone` the repo.
Fixes: #3531
```release-note
NONE
```
=> Simplify the installation of sample-external-issuer

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml, deploy/charts/cert-manager/templates/webhook-service.yaml, deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml, deploy/charts/cert-manager/values.yaml
This PR adds support for configuring a way of reaching the webhook from "outside" of the cluster. This is useful if your control plane is configured in a way where it does not
know anything about the internal cluster network.
See discussion in Slack:
https://kubernetes.slack.com/archives/C4NV3DWUC/p1617873731232000
I wasn't sure if the Helm chart is tested somehow. If it is, please let me know and I'll look into test coverage.
I currently only tested this in my local `0.15` Cert-manager installation, by modifying the manifests after installing the Helm chart.
```release-note
The webhook can now be configured to be accessible from outside of the cluster.
```
=> Add support for accessing the webhook from outside of the cluster
