README.md
=> Updates to README after feedback

pkg/issuer/acme/dns/dns.go
Error message says clouddns when the provider is cloudflare.
=> Fix cloudflare error message

pkg/controller/certificates/controller.go, pkg/controller/context.go, pkg/controller/issuers/controller.go, pkg/controller/register.go, pkg/controller/util.go, pkg/issuer/acme/acme.go, pkg/issuer/const.go, pkg/issuer/context.go, pkg/issuer/factory.go, pkg/issuer/register.go
=> Add comments to top level packages

README.md, contrib/charts/cert-manager/templates/deployment.yaml, contrib/charts/cert-manager/templates/rbac.yaml, contrib/charts/cert-manager/templates/serviceaccount.yaml, contrib/charts/cert-manager/values.yaml, docs/rbac.yaml
I started with the `simonkey007/cert-manager` rules mentioned in the ticket, but it was not complete for my setup (http challenge). Here is a more complete list.
=> Create RBAC policy for cert-manager #34

pkg/issuer/acme/dns/clouddns/LICENSE, pkg/issuer/acme/dns/cloudflare/LICENSE, pkg/issuer/acme/dns/route53/LICENSE
=> Add LICENSE files for files from github.com/xenolf/lego library

.gitlab-ci.yml, Makefile, cmd/controller/app/controller.go, cmd/controller/app/options/options.go, cmd/controller/start.go, pkg/issuer/acme/acme.go, pkg/issuer/acme/http/http.go, pkg/issuer/context.go, pkg/util/version.go
=> Make acmesolver image configurable through CLI. Use tagged version as default

pkg/apis/certmanager/v1alpha1/types.go, pkg/issuer/acme/prepare.go
=> Check authorizations account URI before attempting to reuse authorization

contrib/charts/cert-manager/templates/rbac.yaml, pkg/controller/certificates/sync.go, pkg/issuer/acme/http/http.go, pkg/issuer/acme/issue.go, pkg/issuer/acme/prepare.go, pkg/issuer/acme/renew.go, pkg/issuer/ca/issue.go, pkg/issuer/ca/prepare.go, pkg/issuer/ca/renew.go, pkg/issuer/issuer.go, pkg/util/pki/csr.go
This PR also incidentally fixes a few bugs being experienced with the HTTP01 challenge provider.
=>  Only update certificate status in the controller package.

.travis.yml
=> Set travis go_import_path

labels.yaml
```release-note
NONE
```
/assign munnerz
/area admin
=> Add provider labels. Clean up old labels.

pkg/controller/certificates/controller.go, pkg/controller/clusterissuers/controller.go, pkg/controller/issuers/controller.go, pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/util/wait.go, pkg/issuer/acme/http/http.go
Cherry pick of #126 on release-0.1.
#126: Consistent use of glog
=> Automated cherry pick of #126

hack/cherry-pick-pull.sh
```release-note
NONE
```
/cc @simonswine 
/assign
=> Add cherry-pick-pull script to hack/

pkg/issuer/acme/http/http.go
Cherry pick of #155 on release-0.1.
#155: Ensure Present and CleanUp run in serial
=> Automated cherry pick of #155

pkg/issuer/acme/http/http.go, pkg/issuer/acme/http/http_test.go
Cherry pick of #156 on release-0.1.
#156: Ensure ACME HTTP01 reachability test passes 5 times before
=> Automated cherry pick of #156

contrib/charts/cert-manager/values.yaml
```release-note
NONE
```
/assign
=> Update default chart version to v0.1.1

pkg/issuer/acme/setup.go
Fix a panic in the ACME issuer registration flow
Closes #164 
```release-note
Fix panic if the secret named in an ACME issuer exists but contains invalid data (or no data)
```
=> Fix panic in ACME issuer setup

pkg/issuer/acme/setup.go
Cherry pick of #165 on release-0.1.
#165: Fix panic in ACME issuer setup
=> Automated cherry pick of #165

pkg/issuer/acme/issue.go, pkg/issuer/ca/issue.go, pkg/issuer/ca/setup.go
Fixes #169 
```release-note
Fix checking for invalid data in issuer secrets
```
/assign
=> Fix checking for invalid data in issuer secrets

pkg/issuer/acme/setup.go, test/e2e/issuer/issuer_acme.go
Overcome 'registration already exists for provider key' errors in ACME provider by auto-detecting lost ACME registration URIs
fixed #151, fixes #162 
This change causes us to *always* attempt to register an account, and upon failure will read the account ID from the `Location` header of the registration response and then verify *that* account.
```release-note
Overcome 'registration already exists for provider key' errors in ACME provider by auto-detecting lost ACME registration URIs
```
=> Allow rediscovering lost/not set ACME account URIs

pkg/issuer/acme/http/http.go
Previously the ensureService function was written to update a service if it already exists. There should never be a case where the http01 solver needs to update an existing *service*, so this PR simplifies this functionality into a simple `createService` function.
```release-note
NONE
```
=> Only ever create http01 solver service instead of also updating

pkg/issuer/acme/acme.go, pkg/util/kube/pki.go
Improves validation of existing certificate resources
```release-note
Fix bugs when checking validity of certificate resources
```
=> Add basic validation to ACME issuer

pkg/controller/certificates/sync.go, pkg/issuer/acme/prepare.go, pkg/issuer/ca/issue.go, pkg/util/filter.go, pkg/util/filter_test.go, pkg/util/pki/csr.go, pkg/util/pki/csr_test.go
Cherry pick of #183 on release-0.2.
#183: Improve validation of certificates. Fix bug in checking
=> Automated cherry pick of #183

pkg/issuer/acme/acme.go, pkg/util/kube/pki.go
Cherry pick of #184 on release-0.2.
#184: Add basic validation to ACME issuer
=> Automated cherry pick of #184

docs/user-guides/acme-http-validation.md
=> Fix doc link typo

pkg/issuer/acme/prepare.go
Fixes a panic in the authorize() method of the acme issuer
Fixes #206 
```release-note
Fix a bug in the ACME authorizer that would cause cert-manager to panic when certificate.spec.acme was not specified
```
=> Fix panic in acme authorize function

pkg/controller/certificates/sync.go
Previously we always overwrite the existing certificate if it already existed. Some users have requested a way to automatically create the target secrets using a helm chart, so that all artifacts can be cleaned up cleanly upon `helm delete`.
Fixes #192
```release-note
Update existing secrets instead of replacing in order to preserve annotations/labels
```
=> Update Secrets instead of replacing to preserve additional metadata

Makefile, pkg/issuer/acme/prepare.go, pkg/scheduler/scheduler.go
Cherry pick of #218 #219 on release-0.2.
#218: Enable go race detector and fix race
#219: Fix panic in acme authorize function
=> Automated cherry pick of #218 #219

docs/user-guides/acme-dns-validation.md
Documentation fix. For further information see #209.
fixes #209
```release-note
NONE
```
=> provider names in issuer.yml and certificate.yml must match

contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/values.yaml, docs/examples/cert-manager.yaml
=> Update version for 0.2.3

.gitlab-ci.yml
=> Fix GitLab CI config

.gitlab-ci.yml
Cherry pick of #251 on release-0.2.
#251: Update .gitlab-ci.yml for debian base
=> Automated cherry pick of #251

.gitignore, contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/templates/NOTES.txt, contrib/charts/cert-manager/templates/_helpers.tpl, contrib/charts/cert-manager/templates/certificate-crd.yaml, contrib/charts/cert-manager/templates/clusterissuer-crd.yaml, contrib/charts/cert-manager/templates/deployment.yaml, contrib/charts/cert-manager/templates/issuer-crd.yaml, contrib/charts/cert-manager/templates/rbac.yaml, contrib/charts/cert-manager/templates/serviceaccount.yaml, contrib/charts/cert-manager/values.yaml
* Update Chart.yaml
* Make templates namespaced
* Update config table in README.md
* Apply best practices for RBAC
(see
https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md)
* Add extra args for cert-manager container
* Make list indentation consistent
* Apply standard labels on all resources
* Add some content to NOTES.txt
```release-note
action required: Enhance Helm chart in-line with best practices. This may require a change to your values.yaml files/--set flags.
```
=> Enhance Helm chart and apply best practices

README.md, docs/README.md, docs/user-guides/README.md
After #264, this adds links to the new docs in our main README.
```release-note
NONE
```
=> Add links to new documentation content

.gitignore
=> Add ingress-shim to .gitignore

pkg/apis/certmanager/v1alpha1/annotations.go
Remove an old piece of code that is not used
```release-note
NONE
```
=> Remove unused file

docs/user-guides/migrating-from-kube-lego.md
=> fix multiline command

pkg/issuer/acme/dns/dns.go
This helps debugging, e.g. if there are network problems.
```release-note
```
=> Log potential errors while waiting for DNS record propagation

docs/api-types/issuer/spec.md
**What this PR does / why we need it**: Necessary permissions previously not documented.
```release-note
Document the minimum necessary permissions for using cert-manager with Route53
```
=> Document the minimum necessary permissions for using cert-manager with Route53

docs/api-types/issuer/README.md
This PR is in response to #379
```release-note
NONE
```
=> Add missing apiVersion to Issuer sample docs

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/templates/deployment.yaml, docs/deploy/rbac/certificate-crd.yaml, docs/deploy/rbac/clusterissuer-crd.yaml, docs/deploy/rbac/deployment.yaml, docs/deploy/rbac/issuer-crd.yaml, docs/deploy/rbac/rbac.yaml, docs/deploy/rbac/serviceaccount.yaml, docs/deploy/without-rbac/certificate-crd.yaml, docs/deploy/without-rbac/clusterissuer-crd.yaml, docs/deploy/without-rbac/deployment.yaml, docs/deploy/without-rbac/issuer-crd.yaml
Adds support for setting the node affinity and tolerations scheduling options
```release-note
Add support for node affinity and tolerations in Helm chart
```
=> Helm Chart: Add support for affinity and tolerations

pkg/issuer/acme/acme.go
Cherry pick of #422 on release-0.2.
#422: Add a meaningful User-Agent.
=> Automated cherry pick of #422

cmd/controller/app/controller.go, cmd/controller/app/options/options.go, cmd/ingress-shim/app.go, cmd/ingress-shim/options/options.go, pkg/controller/certificates/controller.go, pkg/controller/context.go, pkg/issuer/context.go
**What this PR does / why we need it**: removes the --namespace flag, which currently isn't tested.
**Which issue this PR fixes**: fixes #334 
```release-note
Removed --namespace flag
```
=> Remove --namespace flag

contrib/charts/cert-manager/values.yaml, docs/examples/cert-manager.yaml
Cherry pick of #441 on release-0.2.
#441: Bump for cert-manager v0.2.4
=> Automated cherry pick of #441

hack/ci.sh
Cherry pick of #451 on release-0.2.
#451: Set 5s timeout on helm version command
```release-note
NONE
```
=> Automated cherry pick of #451

docs/reference/ingress-shim.rst
Fix rst syntax error in ingress-shim.rst.
The code block syntax is missing a `:` so the code is not show in rendered doc.
=> Fix rst syntax error in ingress-shim.rst

docs/tutorials/acme/dns-validation.rst, docs/tutorials/acme/http-validation.rst, docs/tutorials/acme/migrating-from-kube-lego.rst
Updates some of the kubectl describe outputs for docs examples
ref #456 
```release-note
NONE
```
/assign
=> Update some docs examples for acmev2

docs/reference/ingress-shim.rst
Fixes the broken link reported in #471 
```release-note
NONE
```
=> Fix broken link

docs/reference/ingress-shim.rst
Cherry pick of #455 #473 on release-0.2.
#455: Fix rst syntax error in ingress-shim.rst
#473: Fix broken link
=> Automated cherry pick of #455 #473

docs/reference/ingress-shim.rst
Following up #473 
```release-note
NONE
```
/assign
=> Fix deployment guide link. Fix inline code block.

docs/reference/ingress-shim.rst
Cherry pick of #475 on release-0.2.
#475: Fix deployment guide link. Fix inline code block.
=> Automated cherry pick of #475

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/values.yaml, contrib/manifests/cert-manager/rbac/certificate-crd.yaml, contrib/manifests/cert-manager/rbac/clusterissuer-crd.yaml, contrib/manifests/cert-manager/rbac/deployment.yaml, contrib/manifests/cert-manager/rbac/issuer-crd.yaml, contrib/manifests/cert-manager/rbac/rbac.yaml, contrib/manifests/cert-manager/rbac/serviceaccount.yaml, contrib/manifests/cert-manager/without-rbac/certificate-crd.yaml, contrib/manifests/cert-manager/without-rbac/clusterissuer-crd.yaml, contrib/manifests/cert-manager/without-rbac/deployment.yaml, contrib/manifests/cert-manager/without-rbac/issuer-crd.yaml
Bumps Helm chart for v0.3.2-alpha.2
```release-note
NONE
```
=> Update chart for v0.3.2-alpha.2

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/values.yaml
Updates the chart values for the v0.2.5 release
```release-note
NONE
```
=> Update chart for v0.2.5 release

pkg/apis/certmanager/v1alpha1/types.go
Fix attribute names mismatch with Vault documentation.
```
Fix attribute names mismatch with Vault documentation.
```
=> rename fields in Vault appRole credentials

pkg/issuer/acme/dns/cloudflare/cloudflare.go
This changes the Cloudflare DNS01 provider to check if the record is already set before setting it, in order to avoid returning a "record already exists" error during validation.
**Which issue this PR fixes**: fixes #448 
```release-note
NONE
```
=> Update Cloudflare provider to be idempotent when calling Present

pkg/apis/certmanager/v1alpha1/types.go
Seen a typo while going through the code.
```release-note
NONE
```
=> IssuerConfig.Vault typo fix

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/templates/_helpers.tpl, contrib/charts/cert-manager/templates/deployment.yaml, contrib/charts/cert-manager/values.yaml, contrib/manifests/cert-manager/rbac/certificate-crd.yaml, contrib/manifests/cert-manager/rbac/clusterissuer-crd.yaml, contrib/manifests/cert-manager/rbac/deployment.yaml, contrib/manifests/cert-manager/rbac/issuer-crd.yaml, contrib/manifests/cert-manager/rbac/rbac.yaml, contrib/manifests/cert-manager/rbac/serviceaccount.yaml, contrib/manifests/cert-manager/without-rbac/certificate-crd.yaml, contrib/manifests/cert-manager/without-rbac/clusterissuer-crd.yaml, contrib/manifests/cert-manager/without-rbac/deployment.yaml, contrib/manifests/cert-manager/without-rbac/issuer-crd.yaml
=> add pod labels

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/templates/NOTES.txt, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac.yaml
Cherry pick of #577 on release-0.3.
#577: Use https docs url
=> Automated cherry pick of #577

pkg/issuer/vault/setup.go
Cherry pick of #587 on release-0.3.
#587: vault: fix panic when vault is sealed or uninitialized
=> Automated cherry pick of #587

docs/tutorials/acme/migrating-from-kube-lego.rst
=> Fix references to other documentation sections.

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/templates/deployment.yaml, contrib/charts/cert-manager/values.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac.yaml
Cherry pick of #522 on release-0.3.
#522: Add support for custom DNS settings for the cert-manager
=> Automated cherry pick of #522

.github/PULL_REQUEST_TEMPLATE.md
fixes #523
```release-note
NONE
```
=> Fix links in pull request template

README.md
Closes #590 
```release-note
NONE
```
=> Add note about Google Group to readme

docs/tutorials/acme/migrating-from-kube-lego.rst
Cherry pick of #609 on release-0.3.
#609: Fix references to other documentation sections.
=> Automated cherry pick of #609

OWNERS
=> Add Richard Wall to OWNERS file

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/values.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac.yaml
Bumps the Helm chart for upcoming v0.3.1.
```release-note
NONE
```
=> Version bump for v0.3.1

pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
While unlikely, it was possible before for the scheduler to race in such
a way that concurrent 'Add' calls would result in "leaking" a timer,
thus making an unstoppable invocation of that event.
This includes a test which fails without the small bugfix in
scheduler.go
This also updates the scheduler unit tests and shaves 12s off the test running time.
```release-note
NONE
```
=> pkg/scheduler: fix minor race; use mocks in scheduler tests

third_party/crypto/acme/acme.go, third_party/crypto/acme/integration_test.go, third_party/crypto/acme/types.go
This PR merges in the latest changes from the upstream crypto/acme CL here: https://go-review.googlesource.com/c/crypto/+/86635
```release-note
NONE
```
=> Merge latest changes from upstream crypto/acme library

docs/reference/issuers.rst
=> Automated cherry pick of #726 upstream release 0.4

pkg/issuer/acme/dns/clouddns/clouddns.go
Cherry pick of #750 on release-0.4.
#750: clouddns: find hosted zone for challenge record
```release-note
Fix discovery of Google Cloud DNS hosted zone for dns-01 challenge records
```
=> Automated cherry pick of #750

docs/reference/issuers/acme/dns01.rst
:wave:
/kind docs
```release-note
NONE
```
=> Document project field for Google CloudDNS provider

Gopkg.lock, pkg/issuer/acme/dns/route53/route53.go
Cherry pick of #746 on release-0.4.
#746: issuer/route53: fix delete for 'NotExist' errors
=> Automated cherry pick of #746

docs/reference/issuers.rst, docs/reference/issuers/acme/http01.rst
Fixes #757.
```release-note
none
```
=> Add note about http01 and wildcard certificates to docs

docs/reference/issuers.rst, docs/reference/issuers/acme/http01.rst
Cherry pick of #759 on release-0.4.
#759: Add note about http01 and wildcard certificates
=> Automated cherry pick of #759

contrib/charts/pebble/Chart.yaml, contrib/charts/pebble/values.yaml, pkg/issuer/acme/issue.go, test/chart/.testenv
Cherry pick of #764 on release-0.4.
#764: Wait for ACME Orders to be in 'ready' state before
=> Automated cherry pick of #764

labels.yaml
=> Add github label for DNS01 providers

docs/OWNERS, pkg/apis/OWNERS, pkg/issuer/acme/OWNERS, pkg/issuer/acme/dns/OWNERS, pkg/issuer/ca/OWNERS, pkg/issuer/selfsigned/OWNERS, pkg/issuer/vault/OWNERS
This PR also marks the apis directory as requiring a review by @munnerz.
```release-note
NONE
```
/cc @kragniz
=> Add OWNERS files to auto-label PRs. 

docs/devel/dns01-providers.rst, docs/devel/index.rst
Ref #766.
```release-note
none
```
=> Add documentation on creating DNS01 providers

README.md
This updates the README with extended information on where to get help and the current status of the project.
cc @rosskukulinski
```release-note
NONE
```
/cc @kragniz
=> Update 'troubleshooting' and 'current status' README sections

pkg/issuer/acme/issue.go
Catches an edge case picked up and reported by @damienwebdev when a user changes the common name specified on the certificate, but does not change the overall set of domains listed on the cert (i.e. the names on the cert are re-orded).
This should also be cherry-picked into release-0.4 along with #801 and #802
```release-note
NONE
```
=> Catch edge case where the CN and DNSNames on a Certificate have been reordered

pkg/issuer/acme/dns/akamai/akamai.go, pkg/issuer/acme/dns/azuredns/azuredns.go, pkg/issuer/acme/dns/clouddns/clouddns.go, pkg/issuer/acme/dns/cloudflare/cloudflare.go, pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/route53/route53.go, pkg/issuer/acme/dns/util/dns.go
=> Catch and return dns query error in DNS01Record

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/templates/deployment.yaml, contrib/charts/cert-manager/values.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac.yaml
=> added affinity and tolerations

docs/reference/ingress-shim.rst
#436
**What this PR does / why we need it**: This improves the ingress shim documentation by adding an example `Ingress` definition with comments.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #436
```
Add a minimal ingress-shim example with comments.
```
=> doc: add minimal ingress-shim example

Makefile
The recent move to decorated ProwJobs for testing has meant our junit output for e2e tests is broken.
This should fix it 😄 
```release-note
NONE
```
=> Fix JUnit e2e test output

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/requirements.lock, contrib/charts/cert-manager/requirements.yaml, contrib/charts/cert-manager/values.yaml, contrib/charts/cert-manager/webhook/Chart.yaml, contrib/charts/cert-manager/webhook/values.yaml, contrib/manifests/cert-manager/with-rbac-webhook.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac-webhook.yaml, contrib/manifests/cert-manager/without-rbac.yaml
Bumps version numbers for v0.5.0
```release-note
NONE
```
=> Update version numbers for v0.5.0

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/requirements.lock, contrib/charts/cert-manager/requirements.yaml, contrib/charts/cert-manager/values.yaml, contrib/charts/cert-manager/webhook/Chart.yaml, contrib/charts/cert-manager/webhook/templates/ca-sync.yaml, contrib/charts/cert-manager/webhook/values.yaml, contrib/manifests/cert-manager/with-rbac-webhook.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac-webhook.yaml, contrib/manifests/cert-manager/without-rbac.yaml
Bundles changes made to release-0.5
```release-note
NONE
```
/assign
=> Chart updates based on helm/charts feedback

docs/reference/ingress-shim.rst
```release-note
NONE
```
/cc @kragniz
=> Automated cherry pick of #917

pkg/apis/certmanager/validation/certificate_for_issuer.go, pkg/apis/certmanager/validation/certificate_for_issuer_test.go
**What this PR does / why we need it**: Allow ECDSA for ACME issuer
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: -
I already try on my k8s cluster and it works !
```release-note
Allow ECDSA for ACME issuer
```
=> Allow ECDSA for ACME

docs/generated/reference/openapi/openapi_generated.go, docs/generated/reference/output/reference/api-docs/index.html, pkg/apis/certmanager/v1alpha1/types_challenge.go, pkg/apis/certmanager/v1alpha1/types_order.go
This adds more comments to our API types for users to read in our reference documentation.
```release-note
NONE
```
/cc @kragniz
=> Add additional comments/descriptions to ACME API types

contrib/charts/vault/templates/vault-config.yaml, contrib/charts/vault/templates/vault-deployment.yaml, contrib/charts/vault/templates/vault-secret.yaml, contrib/charts/vault/values.yaml, docs/generated/reference/openapi/openapi_generated.go, docs/generated/reference/output/reference/api-docs/index.html, docs/tutorials/vault/creating-vault-issuers.rst, pkg/apis/certmanager/v1alpha1/types_issuer.go, pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go, pkg/apis/certmanager/validation/issuer.go, pkg/apis/certmanager/validation/issuer_test.go, pkg/issuer/vault/issue.go, pkg/issuer/vault/setup.go, test/e2e/BUILD.bazel, test/e2e/certificate/certificate_vault.go, test/e2e/e2e.go, test/e2e/issuer/issuer_vault.go, test/util/util.go, test/util/vault/util.go
Add a caBundle field to Vault Issuer. 
fixes #834
```release-note
A new field *caBundle* added to the Vault Issuer configures a CA certificate used to validate the connection to the Vault Server.
```
=> vault ca bundle support

pkg/controller/acmechallenges/sync.go, pkg/controller/acmechallenges/sync_test.go
The ACME client handles Invalid/failing authorizations by returning its own error type that wraps an Authorization.
This PR updates the acme challenges controller to properly handle this case and update the challenge status subresource accordingly.
```release-note
NONE
```
=> Handle WaitAuthorization failing properly

pkg/issuer/ca/issue.go
Tidies up the use of status conditions in the CA issuer.
This should make it clearer for those building against our APIs to understand the status of a Certificate.
```release-note
Update CA Issuer status condition usage
```
=> Tidy up CA Issuer's use of status conditions

docs/devel/end-to-end-tests.rst
This PR fixes a typo in the documentation that might potentially discourage some contributors.
```release-note
```
=> Fix typo in developer documentation.

hack/ci/run-e2e-kind.sh
This PR fixes issues with the new kind CLI design, preventing users that don't use minikube to run tests.
```release-note
```
=> Fix test-infra/kind testing sh script

pkg/issuer/acme/setup.go
This refactors the way we call createPrivateKey to make things clearer.
It also fixes a bug whereby we may ignore an error returned by `cl, err = acme.ClientWithKey(a.issuer, accountPrivKey)`.
Otherwise, this should be a no-op 😄 
```release-note
NONE
```
=> Refactor ACME account generation

pkg/controller/certificates/sync.go
Tidy up how we check for certificate validity.
Previously the code was confusing to read and understand what is going on.
This should ultimately not change any behaviour 😄 
```release-note
NONE
```
=> Simplify certificate controller cert validity checks

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/requirements.lock, contrib/charts/cert-manager/requirements.yaml, contrib/charts/cert-manager/webhook/Chart.yaml, contrib/charts/cert-manager/webhook/templates/ca-sync.yaml, contrib/charts/cert-manager/webhook/values.yaml, contrib/manifests/cert-manager/with-rbac-webhook.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac-webhook.yaml, contrib/manifests/cert-manager/without-rbac.yaml
Signed-off-by: Sébastien Prud'homme <sebastien.prudhomme@gmail.com>
Enable using a private registry for downloading quay.io/munnerz/apiextensions-ca-helper image
fixes #1039 
```release-note
NONE
```
=> Remove hardcoded image #1039

pkg/issuer/acme/setup.go
Cherry pick of #998 on release-0.5.
#998: Refactor ACME account generation
=> Automated cherry pick of #998

BUILD.bazel, cmd/acmesolver/BUILD.bazel, cmd/acmesolver/main.go, cmd/controller/BUILD.bazel, cmd/controller/main.go, cmd/webhook/BUILD.bazel, cmd/webhook/main.go, pkg/logs/BUILD.bazel, pkg/logs/logs.go, test/e2e/BUILD.bazel, test/e2e/e2e_test.go
This reverts commit b6f854f849db332e6cac80e513e544e442892101.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #987 
This also intercepts calls to `log.Infof` etc so they are funnelled through glog.
```release-note
NONE
```
=> Revert "Remove pkg/logs package"

pkg/issuer/acme/dns/util/wait.go
Cherry pick of #1033 on release-0.5.
#1033: Fix concurrent map writes in FindZoneByFqdn
=> Automated cherry pick of #1033

pkg/issuer/ca/BUILD.bazel, pkg/issuer/ca/issue.go, pkg/issuer/ca/issue_test.go, pkg/issuer/ca/util_test.go, pkg/util/pki/csr.go, test/e2e/suite/issuers/ca/certificate.go, test/unit/gen/certificate.go, test/util/util.go
fixes #1004 
fixes #938
```release-note
NONE
```
=> Add e2e test verifying we can obtain ECDSA keys from RSA CA issuers

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/requirements.lock, contrib/charts/cert-manager/requirements.yaml, contrib/charts/cert-manager/values.yaml, contrib/charts/cert-manager/webhook/Chart.yaml, contrib/charts/cert-manager/webhook/values.yaml, contrib/manifests/cert-manager/with-rbac-webhook.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac-webhook.yaml, contrib/manifests/cert-manager/without-rbac.yaml
=> Bump manifests for v0.6.0-alpha.0

docs/devel/dco-sign-off.rst, docs/devel/generate-docs.rst, docs/reference/issuers/acme/http01.rst
**What this PR does / why we need it**: 
- cleans up sphinx warnings and adds some detail about generating the docs
- a minor correction or two to grammar
- did this as cleanup work while working on a quick-start guide, then pulled it out for it's own inclusion as a separate PR
```release-note
NONE
```
=> Docs cleanup

docs/tutorials/quick-start/echoserver/deployment.yaml, docs/tutorials/quick-start/echoserver/ingress-tls.yaml, docs/tutorials/quick-start/echoserver/ingress.yaml, docs/tutorials/quick-start/echoserver/service.yaml
- I'm going to reference them, but the testing for this repo does
link validation up front, so the files need to exist in their final
locations before the other PR can pass its testing/validation.
```release-note
NONE
```
=> adding files for quickstart

pkg/issuer/acme/http/ingress.go, pkg/issuer/acme/http/ingress_test.go
Cherry pick of #1082 on release-0.5.
#1082: Add failing test to ensure non cert-manager controlled
=> Automated cherry pick of #1082

contrib/charts/cert-manager/Chart.yaml, contrib/charts/cert-manager/README.md, contrib/charts/cert-manager/requirements.lock, contrib/charts/cert-manager/requirements.yaml, contrib/charts/cert-manager/values.yaml, contrib/charts/cert-manager/webhook/Chart.yaml, contrib/charts/cert-manager/webhook/values.yaml, contrib/manifests/cert-manager/with-rbac-webhook.yaml, contrib/manifests/cert-manager/with-rbac.yaml, contrib/manifests/cert-manager/without-rbac-webhook.yaml, contrib/manifests/cert-manager/without-rbac.yaml
Bump deployment manifests for v0.5.2
```release-note
NONE
```
=> Bump manifests for v0.5.2

WORKSPACE
Signed-off-by: Zenara Daley <zenara.daley@shopify.com>
The `WORKSPACE` needs to be updated to use the new bazel rules otherwise errors will occur during `make ...` commands. 
```release-note
NONE
```
cc: @munnerz
=> Update bazel rules

cmd/controller/app/BUILD.bazel, cmd/controller/app/controller.go, cmd/controller/app/options/options.go, pkg/controller/acmechallenges/controller.go, pkg/controller/acmeorders/controller.go, pkg/controller/certificates/controller.go, pkg/controller/context.go, pkg/controller/ingress-shim/controller.go
Fixes #993.
```release-note
Add `--namespace` option to limit scope to a single namespace
```
=> Add --namespace flag

design/acme-orders-challenges-crd.md
This PR documents the work in #788.
It supersedes the document in #737 (omitting the parts of that document about custom challenge solvers).
It has been written with influence from the implementation in #788.
This is a **working document**, however, since we have a WIP implementation in #788 I imagine there won't be too significant changes to what is proposed here (barring feedback!)
```release-note
NONE
```
=> Add proposal for Order and Challenge resources

OWNERS, deploy/chart/OWNERS
After discussion with @wallrj and @simonswine, removing you so you don't get pinged for reviews!
Also adding @DanielMorsing - although be warned being a top level reviewer will mean you get auto-assigned to review PRs 😄 
```release-note
NONE
```
/cc @wallrj @simonswine @DanielMorsing 
/hold
=> Update OWNERS files

WORKSPACE
=> bump pebble version to get larger timeouts

docs/admin/upgrading/index.rst, docs/admin/upgrading/upgrading-0.5-0.6.rst, docs/getting-started/2-installing.rst
Adds the upgrading to v0.6 guide 😄 
fixes #1143 
```release-note
NONE
```
/cc @DanielMorsing @kragniz
=> Add upgrade notes for v0.6

pkg/controller/acmeorders/sync.go
This PR adds a check that handles the case where an existing ACME order is 'valid', but we've not recorded the state after calling FinalizeOrder meaning we've not recorded the signed certificate.
FinalizeOrder can only be called on 'ready' orders, and will return an error if an order is already 'valid'. In these instances, we can re-fetch the issued certificate using the CertificateURL.
Previously, in this instance the call to `syncOrderStatus` which happens irrespective of if FinalizeOrder returned a valid response would update the certificate's status from ready->valid, but because FinalizeOrder in these instances would return an error because the order is already valid, we would *not* record the actual certificate data on the order meaning the …
=> If an Order is already valid, attempt to retrieve existing certificate

docs/getting-started/2-installing.rst
Signed-off-by: Kévin Dunglas <dunglas@gmail.com>
Docs fix
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: n/a
Thanks for this project!
```release-note
NONE
```
=> docs: fix a bash snippet in 2-installing.rst

docs/getting-started/2-installing.rst
Cherry pick of #1261 on release-0.6.
#1261: docs: fix a bash snippet in 2-installing.rst
=> Automated cherry pick of #1261

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/templates/rbac.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml, pkg/issuer/acme/dns/akamai/akamai.go, pkg/issuer/acme/dns/akamai/akamai_test.go, pkg/issuer/acme/dns/azuredns/azuredns.go, pkg/issuer/acme/dns/clouddns/clouddns.go, pkg/issuer/acme/dns/cloudflare/cloudflare.go, pkg/issuer/acme/dns/route53/route53.go
Cherry pick of #1258 #1266 on release-0.6.
#1258: Add RBAC rules for finalizers
#1266: Respect recursive nameservers flag when finding zone for fqdn
=> Automated cherry pick of #1258 #1266

docs/getting-started/troubleshooting.rst, docs/getting-started/webhook.rst
Cherry pick of #1288 on release-0.6.
#1288: Add webhook troubleshooting guide
=> Automated cherry pick of #1288

.gitignore, docs/generated/reference/output/reference/api-docs/index.html, pkg/apis/certmanager/v1alpha1/types.go, pkg/apis/certmanager/v1alpha1/types_certificate.go, pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go, pkg/apis/certmanager/validation/certificate.go, pkg/apis/certmanager/validation/certificate_for_issuer.go, pkg/apis/certmanager/validation/certificate_for_issuer_test.go, pkg/apis/certmanager/validation/certificate_test.go, pkg/controller/certificates/sync.go, pkg/issuer/acme/issue_test.go, pkg/issuer/vault/issue.go, pkg/util/pki/csr.go, pkg/util/util.go
Signed-off-by: Laurent Rolaz <laurent.rolaz@gmail.com>
It allows to specify IP addresses in certificate request, it's useful for TLS connection on IP instead of DNS Names
```
Allow to specify IP addresses in Certificate Request
```
=> Add IP Address in CSR

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/requirements.yaml, deploy/charts/cert-manager/values.yaml, deploy/charts/cert-manager/webhook/Chart.yaml, deploy/charts/cert-manager/webhook/values.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml, docs/getting-started/install.rst, docs/tasks/upgrading/upgrading-0.5-0.6.rst
Cherry pick of #1314 on release-0.6.
#1314: Bump for v0.6.1
=> Automated cherry pick of #1314

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/requirements.yaml, deploy/charts/cert-manager/values.yaml, deploy/charts/cert-manager/webhook/Chart.yaml, deploy/charts/cert-manager/webhook/values.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml, docs/getting-started/install.rst, docs/tasks/upgrading/upgrading-0.5-0.6.rst
Bump manifests for v0.6.1
```release-note
NONE
```
=> Bump for v0.6.1

docs/getting-started/install.rst
Fixed a minor mistake in installation guide documentation
```release-note
```
=> Fixed a mistake in installation guide

docs/devel/develop-with-minikube.rst
- add run kubectl steps before running helm
- correct the path for helm chart
Signed-off-by: Shawn Zhou <shawnzhou00@yahoo.com>
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1349
```release-note
NONE
```
=> Update helm command for minikube installation

pkg/controller/acmechallenges/util_test.go, pkg/controller/acmeorders/util_test.go, pkg/controller/clusterissuers/util_test.go, pkg/controller/issuers/util_test.go, pkg/controller/test/context_builder.go, pkg/issuer/acme/dns/util_test.go, pkg/issuer/acme/http/util_test.go, pkg/issuer/ca/util_test.go
This improves logging within the unit test framework
```release-note
NONE
```
/area testing
/kind cleanup
=> Plumb testing.T through to test Builder

pkg/issuer/acme/issue.go
This should make it easier for users to debug failures coming out of the controller related to their own resource types without having to dig into log messages.
```release-note
Fire additional events when syncing ACME certificates fails
```
=> Fire more Events in ACME Issue function on failure

docs/devel/develop-with-minikube.rst
Signed-off-by: Shawn Zhou <shawnzhou00@yahoo.com>
this PR adds a blank line after the code-block:: shell in minikube instructions so that those commands in the code show up.
This fixes the regression with my earlier commit cf77fbef06a0d2e3ec6339d830d5b62042e63613
```release-note
NONE
```
=> add the missing new line to minikube shell block

docs/reference/certificates.rst
This is a little fix for the docs.
```release-note
NONE
```
=> Fix certificate example in docs

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/requirements.yaml, deploy/charts/cert-manager/values.yaml, deploy/charts/cert-manager/webhook/Chart.yaml, deploy/charts/cert-manager/webhook/values.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml, docs/getting-started/install.rst, docs/tasks/upgrading/upgrading-0.5-0.6.rst
Bump versions for v0.6.2
```release-note
NONE
```
=> Bump for v0.6.2

docs/tasks/acme/configuring-dns01/google.rst
**What this PR does / why we need it**: This PR adds more information to the Google CloudDNS guide
**Which issue this PR fixes**: N/A
```release-note
Add more information to Google CloudDNS guide
```
=> Add more information to Google CloudDNS guide

hack/release.sh
Adds automatic publishing of the Helm chart as part of the release.sh script.
This allows you to publish release .gz of charts to GCS, which can then be served by chart museum or something similar.
**Which issue this PR fixes**: fixes #1186
```release-note
Use charts.jetstack.io instead of the helm/charts repository to publish Helm chart
```
=> Publish Helm chart as part of release.sh script

pkg/controller/test/actions.go, pkg/controller/test/context_builder.go, pkg/issuer/acme/issue_test.go
This improves unit test failure log output, when an action is missing, e.g.:
```
--- FAIL: TestSync (7.39s)
--- FAIL: TestSync/should_update_an_existing_empty_secret_with_the_private_key (1.02s)
util_test.go:85: [unexpected difference between actions: [ObjectMeta.Annotations["certmanager.k8s.io/issuer-kind"]: (missing) != "Issuer" ObjectMeta.Annotations["certmanager.k8s.io/common-name"]: (missing) != "cert-manager.local" ObjectMeta.Annotations["certmanager.k8s.io/alt-names"]: (missing) != "" ObjectMeta.Annotations["certmanager.k8s.io/ip-sans"]: (missing) != "" ObjectMeta.Annotations["certmanager.k8s.io/issuer-name"]: (missing) != "test" Data["tls.crt"]: []uint8[1062] != []uint8[1127]], missing action: update {"" "v1" "secrets"} in namespace …
```
=> Print unit test failures in action matchers as part of failure message

WORKSPACE, hack/ci/lib/build_images.sh, test/e2e/BUILD.bazel, test/e2e/charts/BUILD.bazel, test/e2e/framework/addon/nginxingress/nginx.go, test/e2e/suite/issuers/acme/certificate/http01.go
Upstream dependencies fixed a bug that stopped us from enabling this test. Enable it.
```
NONE
```
=> Enable https redirect test

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/cainjector/Chart.yaml, deploy/charts/cert-manager/cainjector/values.yaml, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/requirements.yaml, deploy/charts/cert-manager/values.yaml, deploy/charts/cert-manager/webhook/Chart.yaml, deploy/charts/cert-manager/webhook/values.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml, docs/getting-started/install.rst, docs/tasks/upgrading/upgrading-0.5-0.6.rst
=> Update versions for v0.7.0-beta.0

pkg/issuer/acme/dns/util/wait.go
During some testing @munnerz found that the CAA check would error out when a domain is not found. This is not the right CAA check behavior
Additionally, improve error messages when we do get an unexpected code
```
NONE
```
=> treat domain not found as ok for CAA checks

docs/getting-started/webhook.rst
This is no longer the case 😄 
```release-note
NONE
```
/milestone v0.7
=> Remove old note about EKS

docs/getting-started/troubleshooting.rst, docs/getting-started/webhook.rst
Updates to the webhook & troubleshooting docs for the cainjector
```release-note
NONE
```
/milestone v0.7
=> Update webhook documentation for cainjector

docs/tutorials/venafi/creating-venafi-issuers.rst
Fixing typos in Venafi documentation and improving caBundle example
```release-note
None
```
=> Fixing typos in Venafi documentation and improving caBundle example

docs/tasks/acme/configuring-dns01/index.rst, docs/tasks/acme/configuring-http01.rst, docs/tasks/acme/issuing-certificates.rst
Adds some missing links
```release-note
NONE
```
/milestone v0.7
=> Update links to ACME docs

docs/tasks/issuing-certificates/index.rst
=> Add note on temporary self signed certificates to docs

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/cainjector/Chart.yaml, deploy/charts/cert-manager/cainjector/values.yaml, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/requirements.yaml, deploy/charts/cert-manager/values.yaml, deploy/charts/cert-manager/webhook/Chart.yaml, deploy/charts/cert-manager/webhook/values.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml, docs/getting-started/install.rst, docs/tasks/upgrading/upgrading-0.5-0.6.rst
=> Bump manifests for v0.7.0

docs/tutorials/acme/quick-start/index.rst
Following the current documentation leads to the bug referenced in this issue: https://github.com/jetstack/cert-manager/issues/1373
```release-note
```
=> Few corrections to the quickstart documentation

docs/tutorials/acme/quick-start/index.rst
Cherry pick of #1468 on release-0.7.
#1468: fix(docs): updated quickstart docs
=> Automated cherry pick of #1468

pkg/issuer/acme/dns/cloudflare/cloudflare.go
=> stop cloudflare auth key from being leaked into the logs

docs/tutorials/acme/quick-start/index.rst
This PR removes a duplicate step in the quickstart example doc.
```release-note
```
=> ref(quickstart): remove duplicate command

docs/devel/dns01-providers.rst
Signed-off-by: Sebastian Brandt 793580+sebbrandt87@users.noreply.github.com
```release-note
NONE
```
=> corrected example docs path

pkg/issuer/acme/dns/util/wait.go
Cherry pick of #1521 on release-0.7.
#1521: use authoritative nameservers for CAA checks
=> Automated cherry pick of #1521

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/templates/deployment.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml
fix typo
fixes https://github.com/jetstack/cert-manager/issues/1539
```release-note
- fix typo in the deployment template
```
=> fix typo in the deployment template for leader election

deploy/manifests/00-crds.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml, pkg/apis/certmanager/v1alpha1/types_certificate.go, pkg/apis/certmanager/v1alpha1/types_issuer.go
Cherry pick of #1576 on release-0.7.
#1576: Add omitempty to fields on conditions
=> Automated cherry pick of #1576

go.mod, go.sum, vendor/modules.txt, vendor/sigs.k8s.io/controller-runtime/doc.go, vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go, vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go, vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go, vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go, vendor/sigs.k8s.io/controller-runtime/pkg/source/BUILD.bazel, vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go
This fork will not remove this commit/ref, whereas the previous
one was part of a pull request that is being force pushed, causing
our builds to fail.
```release-note
NONE
```
=> Pin controller-runtime dependency to use munnerz/controller-runtime fork

pkg/api/BUILD.bazel, pkg/api/scheme.go, pkg/apis/certmanager/validation/issuer.go, pkg/issuer/acme/dns/webhook/webhook.go
Discovered whilst working on #1594 
```release-note
NONE
```
=> Fix webhook DNS provider bugs

pkg/controller/acmechallenges/sync.go
Updates the acmechallenges controller to handle 'challenge expired' responses from the acme server.
This will in turn trigger a retry of the order eventually.
**Which issue this PR fixes**: fixes #1232, fixes #1589 
```release-note
Automatically retry expired Challenge resources
```
=> Handle expired challenge responses in acmechallenges controller

deploy/manifests/00-crds.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml, pkg/apis/certmanager/v1alpha1/types_certificate.go
Replaces #1566 
**Which issue this PR fixes**: fixes #1473 
```release-note
Fixes additionalPrinterColumn formatting for Certificate resources
```
cc @snobu
=> Fix string escaping in CRD additionalPrinterColumns

deploy/manifests/00-crds.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml, pkg/apis/certmanager/v1alpha1/types_certificate.go
Cherry pick of #1616 on release-0.7.
#1616: Fix escape in resource def
=> Automated cherry pick of #1616

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/cainjector/Chart.yaml, deploy/charts/cert-manager/cainjector/values.yaml, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/requirements.yaml, deploy/charts/cert-manager/values.yaml, deploy/charts/cert-manager/webhook/Chart.yaml, deploy/charts/cert-manager/webhook/values.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml, docs/getting-started/install.rst, docs/getting-started/webhook.rst, docs/tasks/issuing-certificates/index.rst, docs/tasks/upgrading/index.rst, docs/tasks/upgrading/upgrading-0.5-0.6.rst, docs/tutorials/acme/quick-start/index.rst
Bumps resources for upcoming v0.8.0-alpha.0
```release-note
NONE
```
=> Bump manifests and docs for v0.8

deploy/charts/cert-manager/Chart.yaml, deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/cainjector/Chart.yaml, deploy/charts/cert-manager/cainjector/values.yaml, deploy/charts/cert-manager/requirements.lock, deploy/charts/cert-manager/requirements.yaml, deploy/charts/cert-manager/values.yaml, deploy/charts/cert-manager/webhook/Chart.yaml, deploy/charts/cert-manager/webhook/values.yaml, deploy/manifests/cert-manager-no-webhook.yaml, deploy/manifests/cert-manager.yaml, docs/getting-started/install.rst
=> Bump manifests for v0.7.2

hack/release.sh, hack/release/main.go, hack/release/pkg/build/chart/plugin.go, hack/release/pkg/build/images/plugin.go
Adds some missing options that weren't passed through
```release-note
NONE
```
=> Update release script to support more options

deploy/charts/cert-manager/templates/rbac.yaml, deploy/charts/cert-manager/templates/serviceaccount.yaml, deploy/charts/cert-manager/webhook/templates/rbac.yaml
Replaces #1538 
```release-note
NONE
```
=> Fix missing line-feeds in Helm chart

hack/release/pkg/build/images/plugin.go
=> Pass path to docker config directory instead of file

deploy/charts/cert-manager/README.md, docs/getting-started/install.rst
=> Bump version numbers for beta.0

hack/release/pkg/build/images/plugin.go
This image was missing in v0.8.0-beta.0 🙈 
**Which issue this PR fixes**: fixes #1652
```release-note
NONE
```
=> Add cainjector to list of images to build

docs/getting-started/install.rst, docs/getting-started/webhook.rst, docs/tasks/upgrading/index.rst
Update install instructions for new manifest location
```release-note
NONE
```
=> Update install guide for GitHub assets installation

docs/getting-started/index.rst, docs/getting-started/install/index.rst, docs/getting-started/install/kubernetes.rst, docs/getting-started/install/openshift.rst, docs/redirects, hack/release/pkg/build/manifests/plugin.go
Adds a page on installing on OpenShift to the documentation 😄 
**Which issue this PR fixes**: fixes #1348 
```release-note
Add installing on OpenShift guide
```
=> Add installing on OpenShift guide

docs/tasks/upgrading/upgrading-0.6-0.7.rst, docs/tasks/upgrading/upgrading-0.7-0.8.rst
**Which issue this PR fixes**: fixes #1665
```release-note
NONE
```
/milestone v0.8
=> Add v0.8 upgrade notes document

docs/getting-started/install/openshift.rst
=> Fixup oc login command in openshift guide

pkg/controller/ingress-shim/sync.go
```release-note
NONE
```
/milestone v0.8
=> Log warning Event if edit-in-place is enabled with new solver format

deploy/charts/cert-manager/Chart.yaml
=> Add logo to Helm chart

docs/tasks/upgrading/index.rst, docs/tasks/upgrading/upgrading-0.7-0.8.rst
=> Fix broken links in docs

docs/getting-started/install/kubernetes.rst
=> Fix-up version number in docs

docs/tutorials/acme/quick-start/example/ingress-tls-final.yaml, docs/tutorials/acme/quick-start/example/ingress-tls.yaml, docs/tutorials/acme/quick-start/example/ingress.yaml, docs/tutorials/acme/quick-start/example/production-issuer.yaml, docs/tutorials/acme/quick-start/example/staging-issuer.yaml, docs/tutorials/acme/quick-start/index.rst
Adds the `solvers` field in the related `issuer.yaml` files for the quick start guide doc. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1608 
Just copies code blocks from https://docs.cert-manager.io/en/latest/tasks/issuers/setup-acme/index.html
```release-note
NONE
```
=> Add solvers fields in Let's Encrypt/nginx quick start guide

pkg/issuer/acme/dns/dns.go
This PR for visibility, I found this typo when looking through the code for some issues I have been seeing.
Not sure what the impact is.
=> Typo. should tenantID ?

docs/tasks/issuers/setup-acme/dns01/index.rst
Adds documentation on using the `cnameStrategy` field for delegated domains.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1614 
```release-note
NONE
```
=> Add documentation on cnameStrategy

deploy/charts/cert-manager/README.md, docs/getting-started/install/kubernetes.rst, docs/getting-started/install/openshift.rst, docs/getting-started/webhook.rst, docs/tutorials/acme/quick-start/index.rst
=> Bump version numbers for v0.8.1

deploy/charts/cert-manager/README.md, docs/getting-started/install/kubernetes.rst, docs/getting-started/install/openshift.rst, docs/getting-started/webhook.rst, docs/tutorials/acme/quick-start/index.rst
=> Bump manifests for v0.8.1

go.mod, go.sum, vendor/github.com/Venafi/vcert/pkg/venafi/cloud/certificatePolicies.go, vendor/github.com/Venafi/vcert/pkg/venafi/cloud/cloud.go, vendor/github.com/Venafi/vcert/pkg/venafi/cloud/company.go, vendor/github.com/Venafi/vcert/pkg/venafi/cloud/connector.go, vendor/modules.txt
This resolves issues with Venafi Cloud & reading zone policy configuration 😄 
```release-note
Venafi: use vCert v4.1.0
```
/cc @alljames 
/area venafi
=> Bump to vcert v4.1.0

OWNERS
=> Remove myself from top-level reviewers list

deploy/charts/cert-manager/cainjector/templates/deployment.yaml, deploy/charts/cert-manager/cainjector/templates/rbac.yaml, deploy/charts/cert-manager/cainjector/templates/serviceaccount.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/rbac.yaml, deploy/charts/cert-manager/templates/serviceaccount.yaml, deploy/charts/cert-manager/webhook/templates/apiservice.yaml, deploy/charts/cert-manager/webhook/templates/deployment.yaml, deploy/charts/cert-manager/webhook/templates/pki.yaml, deploy/charts/cert-manager/webhook/templates/rbac.yaml, deploy/charts/cert-manager/webhook/templates/service.yaml, deploy/charts/cert-manager/webhook/templates/serviceaccount.yaml, deploy/charts/cert-manager/webhook/templates/validating-webhook.yaml
Updated the labels in the helm charts to use the newer ones.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/jetstack/cert-manager/issues/914
```release-note
Updated the labels in the helm charts to use the newer ones.
```
=> Replace labels to use the newer ones

docs/tasks/issuers/setup-venafi.rst
add more detail around username format for TPP credentials.
```release-note
```
=> Update Venafi Issuer doc

test/e2e/framework/addon/chart/addon.go
Since we updated the Helm chart to use the new style of labels, we've been unable to fetch logs when tests failing from cert-manager. This should fix that 😄
```release-note
NONE
```
=> Fix fetching logs in e2e test framework

design/release-notes/release-0.1/draft-release-notes.md, design/release-notes/release-0.2/draft-release-notes.md, design/release-notes/release-0.3/draft-release-notes.md, design/release-notes/release-0.4/draft-release-notes.md, design/release-notes/release-0.5/draft-release-notes.md, design/release-notes/release-0.6/draft-release-notes.md, design/release-notes/release-0.7/draft-release-notes.md, design/release-notes/release-0.8/draft-release-notes.md
/assign
```release-note
NONE
```
=> Adds release-notes to be in tree

docs/reference/certificaterequests.rst, docs/reference/index.rst
```release-note
NONE
```
rebased on #1875 
=> CertificateRequest conditions docs

docs/tasks/upgrading/index.rst, docs/tasks/upgrading/upgrading-0.8-0.9.rst
=> Adds release-0.9 upgrade guide

OWNERS
=> Adds joshvanl to OWNERS

deploy/charts/cert-manager/README.md, docs/getting-started/install/kubernetes.rst, docs/getting-started/install/openshift.rst, docs/getting-started/webhook.rst, docs/tutorials/acme/quick-start/index.rst
=> Bump version numbers for v0.9.0-alpha.0 to v0.9.0-beta.0

docs/devel/release-process.rst
=> Updates release process

design/20190708.certificate-request-crd.md
Signed-off-by: Michael Cristina <michael.cristina@optum.com>
This marks the code blocks as golang so it is colored and easier to read in github
```release-note
NONE
```
=> doc: mark MD code as golang for readability

deploy/charts/cert-manager/README.md, docs/getting-started/install/kubernetes.rst, docs/getting-started/install/openshift.rst, docs/getting-started/webhook.rst, docs/tutorials/acme/quick-start/index.rst
Bumps version numbers for v0.9.0
```release-note
NONE
```
=> Bump version strings for v0.9.0

design/release-notes/release-0.9/draft-release-notes.md
=> Add intro to 0.9 release notes

deploy/charts/cert-manager/README.md
Remove unintentional line break in values table in README.md that caused markdown rendering issue.
```release-note
chart: fix formatting of values table in README.md
```
=> chart: fix formatting of values table in README.md

docs/getting-started/install/kubernetes.rst
This pr is in response to @JoshVanL in https://github.com/jetstack/cert-manager/pull/1935
```release-note
NONE
```
=> include helmfile alternative installation

pkg/metrics/metrics.go
Signed-off-by: Vasilis Remmas <vasremm@gmail.com>
**What this PR does / why we need it**: fixes metrics cleanUp function
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1955
```release-note
NONE
```
=> Fix functionality of metrics cleanUp function

Makefile
This may hopefully reduce flakes 😬 
```release-note
NONE
```
=> Only run 10 e2e test cases in parallel

design/20190708.certificate-request-crd.md
=> Adds FailureTime and ACME behaviour to CertificateRequest JEP

deploy/charts/cert-manager/README.md, docs/getting-started/install/kubernetes.rst, docs/getting-started/install/openshift.rst, docs/getting-started/webhook.rst, docs/tutorials/acme/quick-start/index.rst
=> Bump version strings for v0.9.1

BUILD.bazel, cmd/webhook/BUILD.bazel, cmd/webhook/main.go, pkg/apis/certmanager/validation/BUILD.bazel, pkg/webhook/validation/BUILD.bazel, pkg/webhook/validation/certificate.go, pkg/webhook/validation/clusterissuer.go, pkg/webhook/validation/issuer.go, vendor/modules.txt
This is part of the effort to implement conversion webhooks (#1984)
```release-note
NONE
```
=> Move API webhook validation package

hack/BUILD.bazel, hack/update-codegen.sh, third_party/k8s.io/code-generator/BUILD.bazel, third_party/k8s.io/code-generator/generate-groups-internal.sh
This is part of the effort to implement conversion webhooks (#1984)
```release-note
NONE
```
=> Add generate-groups-internal.sh script from code-generator

deploy/charts/cert-manager/README.md, docs/getting-started/install/kubernetes.rst, docs/getting-started/install/openshift.rst, docs/getting-started/webhook.rst, docs/tasks/issuing-certificates/index.rst, docs/tasks/upgrading/index.rst, docs/tutorials/acme/quick-start/index.rst
=> Bump cert-manager version strings v0.9.0 -> v0.10.0

docs/tasks/upgrading/upgrading-0.8-0.9.rst
```release-note
NONE
```
/cherrypick
=> Adds documentation to describe how to perform 0.8->0.9 process

docs/devel/generate-docs.rst
**What this PR does / why we need it**: Documentation on how to generate documentation is not properly generated ;)
```release-note
NONE
```
=> Fix docs on how to generate docs

deploy/charts/cert-manager/README.md, design/release-notes/release-0.10/draft-release-notes.md, docs/getting-started/install/kubernetes.rst, docs/getting-started/install/openshift.rst, docs/getting-started/webhook.rst, docs/tasks/backup-restore-crds.rst, docs/tasks/upgrading/index.rst, docs/tasks/upgrading/upgrading-0.9-0.10.rst, docs/tutorials/acme/quick-start/index.rst
Add release notes for v0.10.0 and bump version strings
```release-note
NONE
```
/milestone v0.10
=> Add v0.10.0 release notes and bump versions

docs/tasks/issuers/setup-acme/dns01/google.rst
Context: https://github.com/jetstack/cert-manager/issues/650#issuecomment-441850385
Improve docs
#650
```release-note
NONE
```
=> Adds a note about the secret namespace error

docs/getting-started/install/kubernetes.rst, docs/getting-started/install/openshift.rst
=> Adds install warning on running multiple instances of cert-manager

deploy/charts/cert-manager/templates/rbac.yaml
If fixes the strange hidden characters related in the issue https://github.com/jetstack/cert-manager/issues/2055. 
**Which issue this PR fixes**: fixes #2055
I was trying to install v0.10
=> Fix for the issue https://github.com/jetstack/cert-manager/issues/2055

docs/getting-started/install/kubernetes.rst
=> Fixed double quotes to highlight cert-manager-webhook

deploy/charts/cert-manager/README.md, docs/getting-started/install/kubernetes.rst, docs/getting-started/install/openshift.rst, docs/getting-started/webhook.rst
Bumps version strings for v0.10.1
```release-note
NONE
```
=> Bump version strings for v0.10.1

docs/tutorials/acme/quick-start/example/deployment.yaml, hack/ci/lib/build_images.sh, test/e2e/BUILD.bazel, test/e2e/charts/BUILD.bazel, test/e2e/charts/pebble/templates/deployment.yaml, test/e2e/charts/vault/templates/vault-deployment.yaml, test/e2e/framework/addon/nginxingress/nginx.go, test/e2e/framework/config/nginx.go, test/e2e/images.bzl
This should fix the Kubernetes 1.16 periodic jobs too 🎉 
```release-note
NONE
```
=> Fix end-to-end test suite for Kubernetes 1.16

deploy/manifests/00-crds.yaml, docs/getting-started/install/kubernetes.rst, pkg/apis/acme/v1alpha2/types_challenge.go, pkg/apis/acme/v1alpha2/types_order.go, pkg/apis/certmanager/v1alpha2/types_certificate.go, pkg/apis/certmanager/v1alpha2/types_certificaterequest.go, pkg/apis/certmanager/v1alpha2/types_issuer.go, pkg/controller/acmechallenges/controller.go, pkg/controller/acmechallenges/sync.go, pkg/controller/acmechallenges/sync_test.go, pkg/controller/acmeorders/sync.go, pkg/controller/acmeorders/sync_test.go, pkg/controller/certificaterequests/acme/acme_test.go, pkg/controller/certificaterequests/ca/ca_test.go, pkg/controller/certificaterequests/selfsigned/selfsigned_test.go, pkg/controller/certificaterequests/sync.go, pkg/controller/certificaterequests/sync_test.go, pkg/controller/certificaterequests/vault/vault_test.go, pkg/controller/certificaterequests/venafi/venafi_test.go, pkg/controller/certificates/BUILD.bazel, pkg/controller/certificates/sync.go, pkg/controller/certificates/sync_test.go, pkg/controller/certificates/util.go, pkg/controller/clusterissuers/sync.go, pkg/controller/issuers/sync.go
```release-note
Move status to a CRD Subresource
```
/hold
=> Adds status sub resource and changes updates

deploy/charts/cert-manager/README.md, deploy/charts/cert-manager/cainjector/templates/psp-clusterrole.yaml, deploy/charts/cert-manager/cainjector/templates/psp-clusterrolebinding.yaml, deploy/charts/cert-manager/cainjector/templates/psp.yaml, deploy/charts/cert-manager/cainjector/values.yaml, deploy/charts/cert-manager/templates/psp-clusterrole.yaml, deploy/charts/cert-manager/templates/psp-clusterrolebinding.yaml, deploy/charts/cert-manager/templates/psp.yaml, deploy/charts/cert-manager/values.yaml, test/fixtures/cert-manager-values.yaml
This PR enable podsecuritypolicy with a permissive and privileged default.
fixes #1841
```release-note
NONE
```
=> chart: support podsecuritypolicy

deploy/charts/cert-manager/README.md, docs/getting-started/install/kubernetes.rst, docs/getting-started/install/openshift.rst, docs/getting-started/webhook.rst
=> Bump version strings for v0.11.0-beta.0

design/release-notes/release-0.11/draft-release-notes.md
Initial draft release notes for v0.11 - this is a *big* release 😄 looking forward to getting it out! 🎉 
```release-note
NONE
```
=> Add v0.11 draft release notes

docs/getting-started/index.rst, docs/getting-started/install/kubernetes.rst, docs/getting-started/install/openshift.rst, docs/tasks/index.rst, docs/tasks/uninstall/index.rst, docs/tasks/uninstall/kubernetes.rst, docs/tasks/uninstall/openshift.rst
```release-note
NONE
```
fixes #2138
=> Adds uninstallation documentation

design/release-notes/release-0.11/draft-release-notes.md
=> Adds some notable items to 0.11 release notes

deploy/charts/cert-manager/values.yaml
fixes #2158 
```release-note
NONE
```
=> Adds comment to helm chart with the verbosity levels

test/e2e/suite/conformance/certificates/suite.go
=> Fix name of a conformance test

pkg/internal/vault/vault.go
- Fix a trivial bug
- Modify error message according to https://github.com/golang/go/wiki/CodeReviewComments#error-strings
```release-note
NONE
```
=> Fix to handle error

deploy/charts/cert-manager/README.md, docs/getting-started/install/kubernetes.rst, docs/getting-started/install/openshift.rst, docs/getting-started/webhook.rst
=> Bump version strings for v0.11.0

design/release-notes/release-0.11/draft-release-notes.md
=> Add additional sections to release notes

docs/tasks/upgrading/upgrading-0.10-0.11.rst, hack/BUILD.bazel, hack/api-migration/BUILD.bazel, hack/api-migration/main.go
Adds CLI migration too to automatically migrate your ingress annotations.
fixes #2163 
```release-note
NONE
```
=> Adds CLI migration tool with docs on how to use it

docs/tasks/index.rst, docs/tasks/upgrading/upgrading-0.10-0.11.rst
=> Fix order of tasks and rst table in 0.10 upgrade

design/release-notes/release-0.11/draft-release-notes.md
=> Add changelog for v0.11.0

design/release-notes/release-0.11/draft-release-notes.md
=> Add contributor list to release notes

docs/tasks/upgrading/upgrading-0.10-0.11.rst
=> Fix uninstall link in upgrade guide 0.11

hack/update-deps.sh
Unset GOROOT during update-deps
```release-note
NONE
```
/milesone v0.12
=> Change update-deps to set GOROOT

docs/reference/cainjector.rst
Add cainjector usage documentation.
**Release note**
```release-note
NONE
```
=> Add cainjector usage documentation.

pkg/apis/acme/v1alpha2/types.go, pkg/apis/certmanager/v1alpha2/types.go, pkg/controller/ingress-shim/sync.go, pkg/controller/ingress-shim/sync_test.go
=> Move IngressEditInPlaceAnnotationKey into acme API

hack/release/pkg/build/images/plugin.go
First pass at attempting to get multi-architecture docker images published to `quay.io/jetstack`.
I've tested this locally and it has published a multi-arch image successfully (🎉).
**Which issue this PR fixes** fixes #1905
I am not certain, but I suspect our CI docker daemon's *won't* have the experimental flag enabled, and I think `docker manifest` requires it. We'll only find out after this PR merges, as this code runs *after* publishing, and we can't smoketest the *publish* stage (only the build stage).
```release-note
Publish multi-architecture docker manifest lists
```
=> Create multi-arch manifest lists when publish docker images

hack/update-bazel.sh, hack/update-codegen.sh, hack/update-crds.sh, hack/update-deps-licenses.sh, hack/update-deps.sh, hack/update-gofmt.sh, hack/update-reference-docs.sh, hack/verify-bazel.sh, hack/verify-errexit.sh, hack/verify-gofmt.sh, hack/verify-links.sh
ref https://github.com/kubernetes/test-infra/pull/13910 and https://github.com/kubernetes/test-infra/issues/13873
Fixes sporadic weird Bazel errors.
```release-note
NONE
```
=> Fix infinite symlink expansion errors

docs/tasks/issuers/setup-acme/dns01/index.rst, docs/tasks/issuers/setup-acme/dns01/webhook.rst
Add areference to the existing webhook solvers.
```release-note
Add documentation for the webhook
```
=> Add documentation for the webhook

pkg/controller/acmechallenges/sync.go, pkg/controller/acmechallenges/sync_test.go
Full details are in the referenced issue - this will make it a lot easier for users to debug why their certificates are not being issued 😄 
**Which issue this PR fixes**: fixes #2259
```release-note
Surface more information about ACME authorization failures on Challenge resources
```
/cc @Evesy
=> Surface ACME Challenge failure reason on Challenge resource if available

pkg/api/util/usages.go, pkg/controller/certificates/sync.go, pkg/util/pki/csr.go, pkg/util/pki/csr_test.go, test/e2e/framework/helper/certificaterequests.go, test/e2e/framework/helper/certificates.go, test/e2e/suite/conformance/certificates/acme/acme.go, test/e2e/suite/conformance/certificates/featureset.go, test/e2e/suite/conformance/certificates/suite.go, test/e2e/suite/conformance/certificates/vault/vault_approle.go
```release-note
NONE
```
fixes #2247
=> Ensure key usages are set on CertificateRequests created by the Certificate controller

deploy/charts/cert-manager/crds/clusterissuers.yaml, deploy/charts/cert-manager/crds/issuers.yaml, deploy/manifests/00-crds.yaml, pkg/apis/certmanager/v1alpha2/types_issuer.go
```release-note
NONE
```
Adds custom fields to issuer output for more informative output
=> Increases issuer CLI output

test/e2e/suite/serving/BUILD.bazel, test/e2e/suite/serving/cainjector.go
=> Disables API Service cainjector.go e2e test

deploy/charts/cert-manager/README.md
=> Bump Helm chart README for v0.12.0-beta.0

deploy/charts/cert-manager/crds/certificaterequests.yaml, deploy/charts/cert-manager/crds/certificates.yaml, deploy/manifests/00-crds.yaml, pkg/apis/certmanager/v1alpha2/types.go
=> Adds all key usage possible values to key usage comment

WORKSPACE
```release-note
Build using go 1.13.4
```
=> Build using go 1.13.4

deploy/charts/cert-manager/README.md
=> Update Helm chart README for v0.12.0-beta.1

pkg/controller/certificaterequests/BUILD.bazel, pkg/controller/certificaterequests/acme/acme_test.go, pkg/controller/certificaterequests/ca/ca_test.go, pkg/controller/certificaterequests/selfsigned/selfsigned_test.go, pkg/controller/certificaterequests/sync.go, pkg/controller/certificaterequests/sync_test.go, pkg/controller/certificaterequests/vault/vault_test.go, pkg/controller/certificaterequests/venafi/venafi_test.go
```release-note
NONE
```
/milesone v0.12
=> Check for Issuer readiness in CR controllers

deploy/charts/cert-manager/README.md, docs/getting-started/install/kubernetes.rst, docs/getting-started/install/openshift.rst, docs/getting-started/webhook.rst, docs/tasks/upgrading/upgrading-0.10-0.11.rst
Signed-off-by: James Munnelly <james@munnelly.eu>
```release-note
```
=> Bump version strings for v0.11.1

deploy/charts/cert-manager/templates/cainjector-rbac.yaml, deploy/charts/cert-manager/templates/deployment.yaml
Fixes falsey fields issue in helm chart 
fixes #2375 
```release-note
Fix falsey values in helm chart to mitigate kubernetes/issues/66450
```
=> Fixes false/null fields in the helm chart.

deploy/charts/cert-manager/README.md
This will be an initial alpha ahead of christmas, containing the newly merge 'ExternalAccountBinding' support along with a handful of other features.
```release-note
NONE
```
=> Bump Helm chart strings for v0.13.0-alpha.0

pkg/controller/certificates/sync.go, pkg/controller/certificates/sync_test.go
Changes the certificate controller to be more permissive about existing issued certificates when deciding whether to re-issue a 'temporary' certificate.
**Which issue this PR fixes**: fixes #2413
```release-note
Fix bug causing temporary certificates to overwrite previously issued certificates when adding a new dnsName to an existing Certificate resource
```
/kind bug
=> Don't overwrite existing certificates when issuing a temporary certificate

pkg/issuer/acme/http/ingress.go, pkg/issuer/acme/http/ingress_test.go
**What this PR does / why we need it:**
This PR addresses a bug where a service name change does not cause the previously created ingress's service name to update. 
**Which issue this PR fixes:** fixes #2442
**Release note:**
```release-note
fixed a bug that in certain cases could cause HTTP01 ingress 'serviceName' fields to be incorrectly set
```
/kind bug
=> ACME HTTP01 solver: clean up ingresses if the service name changes

deploy/charts/cert-manager/README.md
Signed-off-by: James Munnelly <james@munnelly.eu>
```release-note
```
=> Update version tags in Helm chart

deploy/charts/cert-manager/README.md
We shouldn't lie to our users 😇  the installation docs already make this clear, but our Helm chart should too.
```release-note
NONE
```
=> Update version numbers in Helm chart README

README.md
The documentation has moved, this updates the links in the readme as well as fixing some dead links in there.
Signed-off-by: Maartje Eyskens <maartje@eyskens.me>
Fixing links in the README.md
```release-note
NONE
```
=> Update README with new docs links

deploy/charts/cert-manager/crds/certificates.yaml, deploy/manifests/00-crds.yaml, pkg/apis/certmanager/v1alpha2/types_certificate.go, pkg/apis/certmanager/v1alpha3/types_certificate.go, pkg/internal/venafi/BUILD.bazel
Add a note about ignorance of common name
Fixes #2550
Related to https://github.com/cert-manager/website/pull/106
```release-note
NONE
```
=> Add note that CommonName is not looked at when any SAN is set

deploy/charts/cert-manager/README.md
:tada:
```release-note
NONE
```
=> Bump Helm chart README for v0.13.1

pkg/issuer/acme/http/http.go
This change presents us displaying the full HTML body of a page when a HTTP01 'self check' fails.
Previously, a whole bunch of text could be presented to the user in a very unhelpful way. Appending `(truncated)` should hopefully make it clear that the text is long.
```release-note
Truncate message display if HTTP01 self check fails
```
=> Truncate message displayed to user if fetched key does not match presented key

deploy/charts/cert-manager/templates/webhook-rbac.yaml
Resolved hard-coded namespace in helm chart.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2618
```release-note
Make the webhook `RoleBinding` the leader election namespace instead of hard-coded `kube-system`
```
=> dynamic namespace for webhook RoleBinding

deploy/charts/cert-manager/README.md
Prepaing for v0.14(alpha)
```release-note
NONE
```
=> Tag v0.14 in the Helm chart readme

OWNERS
Adding myself to the reviewers and approvers to be able to merge PRs.
```release-note
NONE
```
=> Add meyskens to reviewers and approvers

test/e2e/suite/conformance/certificates/suite.go
Previously, even if a test case was skipped, we'd run the BeforeEach and AfterEach functions which typically involve creating an Issuer resource and waiting for it to become ready. This is completely unnecessary and in the best case wastes time, and in the worst case causes flakes due to e.g. registering too many ACME accounts in a short period of time.
```release-note
NONE
```
/kind cleanup
/area testing
=> Skip test initialisation if test case utilises unsupported features

deploy/charts/cert-manager/README.md
v0.14.0-alpha.1 release
```release-note
NONE
```
=> Bump Helm version in docs to v0.14.0-alpha.1

pkg/acme/cache.go
This is part of a larger attempt to fix flakes that we're seeing, caused by the CreateAccount endpoint taking minutes to respond and blocking up the issuer/clusterissuer controller queue and causing tests to fail.
This is copying the configuration from the `DefaultTransport` in the `http` package.
```release-note
NONE
```
=> Re-use net.Dialer on repeat calls to DialContext

deploy/charts/cert-manager/README.md
v0.14.0 release
```release-note
NONE
```
=> Bump Helm version in readme to v0.14.0

pkg/acme/client/middleware/logger.go
This PR adds a 30 deadline timeout to acme client calls.
fixes #2711 
/kind bug
/area acme
```release-note
Adds acme client timeout of 30 seconds
```
=> Adds acme client timeout of 30 seconds

deploy/charts/cert-manager/README.md
Update the Helm chart README from v0.14.1 :)
```release-note
NONE
```
/area deploy
=> release-0.14: bump Helm chart README for v0.14.1

deploy/charts/cert-manager/README.md
As-per the title 😄 this is still required for the release-0.14 branch patch releases.
```release-note
NONE
```
=> Bump version strings for v0.14.2

pkg/webhook/handlers/validation.go, pkg/webhook/handlers/validation_test.go
Use the `admissionSpec.Kind` field instead of `RequestKind` if RequestKind is not set, avoiding a nil pointer dereference when working with apiservers older than 1.15 (which do not set the RequestKind field).
**Which issue this PR fixes**: fixes #2850
```release-note
Fix bug in webhook based validation on Kubernetes API servers older than 1.15
```
/area webhook
/kind bug
=> Support Kubernetes 1.15 and below properly in validating webhook

cmd/ctl/pkg/convert/convert.go
Fix the CLI convert example
```release-note
NONE
```
/kind cleanup
=> Fix the convert example

deploy/charts/cert-manager/README.template.md
Fixes the link to values.yaml on the Helm Hub
fixes  #2874
```release-note
NONE
```
=> Change link in the Helm Hub readme

WORKSPACE
Bump Go to the latest version
```release-note
NONE
```
=> Bump Go to 1.14.2

LICENSES, go.mod, go.sum, hack/build/repos.bzl, pkg/issuer/acme/dns/util/wait.go, test/acme/dns/server/server.go
Update to the latest miekg/dns which has several useful fixes
```release-note
Update the miekg/dns dependency
```
=> Update to the latest miekg/dns

go.mod, go.sum, hack/build/repos.bzl
This is #2984 with bazel updated, would be good to have this in in time for v0.16.
fixes #2983
```release-note
NONE
```
/kind cleanup
=> Bump goacmedns to v0.0.3

hack/update-deps-licenses.sh
Updates our LICENSES file generation with the latest changes from k/k.
This is in order to better handle issues we'll face in future around license generation (when we upgrade to k8s 1.19 dependencies)
```release-note
NONE
```
/kind cleanup
=> Update update-deps-licenses.sh with latest changes from kubernetes/kubernetes

cmd/ctl/pkg/status/certificate/BUILD.bazel, cmd/ctl/pkg/status/certificate/certificate.go, cmd/ctl/pkg/status/certificate/certificate_test.go, test/integration/ctl/ctl_status_certificate_test.go
Add information about the CertificateRequest resource owned by the Certificate and with the correct Revision to the output of the `status certificate` command.
```
Add information about the CertificateRequest resource related to the Certificate to the output of the `status certificate` command.
```
/kind feature
/area ctl
=> Ctl command status certificate: Add CR output

devel/addon/bind/install.sh, devel/addon/bind/manifests/configmap.yaml, devel/addon/bind/manifests/deployment.yaml, devel/addon/bind/manifests/service.yaml, devel/addon/certmanager/install.sh, devel/addon/ingressnginx/install.sh, devel/addon/samplewebhook/chart/templates/deployment.yaml, devel/ci-run-e2e.sh, devel/cluster/BUILD.bazel, devel/cluster/config/openshift-coredns.yaml, devel/cluster/create-kind.sh, devel/cluster/create-openshift3.sh, devel/cluster/create.sh, devel/cluster/export-logs.sh, devel/lib/lib.sh, devel/run-e2e.sh, devel/setup-e2e-deps.sh, hack/bin/BUILD.bazel, hack/bin/deps.bzl, test/e2e/framework/config/acme.go, test/e2e/suite/conformance/certificates/acme/acme.go, test/e2e/suite/issuers/acme/certificate/dns01.go, test/e2e/suite/issuers/acme/certificaterequest/dns01.go, test/e2e/suite/issuers/acme/dnsproviders/rfc2136.go
Add e2e tests for OpenShift 3.11
fixes #2698
```release-note
Add e2e tests for OpenShift 3.11
```
=> OpenShift 3.11 e2e tests

hack/filter-crd/main.go
=> Remove x-kubernetes-preserve-unknown-fields from Issuer and ClusterIssuer CRDs

devel/addon/bind/install.sh, devel/addon/ingressnginx/install.sh, devel/addon/pebble/install.sh, devel/addon/samplewebhook/install.sh, devel/addon/vault/install.sh
Fixes the IS_OPENSHIFT variable from being used before it is set inside lib.sh
```release-note
NONE
```
/cc @hzhou97
=> Fix individual devel addon installs

USERS.md
=> 📝 Add myself to users list

cmd/ctl/pkg/status/certificate/BUILD.bazel, cmd/ctl/pkg/status/certificate/certificate.go, cmd/ctl/pkg/status/certificate/certificate_test.go, cmd/ctl/pkg/status/certificate/types.go, cmd/ctl/pkg/status/util/BUILD.bazel, cmd/ctl/pkg/status/util/util.go, test/integration/ctl/ctl_status_certificate_test.go
Refactor the `status certificate` command to build a `CertificateStatus` struct, then call `String()` for output. This design is supposed to be more reusable, as we now also have a struct to pass around rather then just string being printed line by line. Should not change any visible behaviour.
```
NONE
```
/kind cleanup
/area ctl
=> Refactor status cmd

cmd/ctl/pkg/status/certificate/BUILD.bazel, cmd/ctl/pkg/status/certificate/certificate.go, cmd/ctl/pkg/status/certificate/certificate_test.go, cmd/ctl/pkg/status/certificate/types.go, test/unit/gen/certificate.go
Refactor the Run method of ctl command `status certificate` into smaller helpe functions for easier testing, and added unit tests.
Hold until PR [3154](https://github.com/jetstack/cert-manager/pull/3154) is merged in as it's based on it.
```
NONE
```
/kind cleanup
/area ctl
/area testing
=> Ctl command status certificate: Refactor Run method

cmd/cainjector/app/start.go
This combines the 2 managers that are setup in the cainjector to become 1, getting rid of the two leader elections being done.
fixes #2982
```release-note
Refactor the cainjector to only have 1 leader election
```
/kind cleanup
=> Refactor the cainjector to only have 1 leader election

USERS.md
Signed-off-by: rimas <rmocius@gmail.com>
```release-note
NONE
```
=> Add JFrog to users

pkg/acme/client/interfaces.go
This PR adds a special back-off function to the ACME client which will make sure the library returns an error to our code when it hits a Retry-After header.
fixes #2741 
replaces #3212 
```release-note
Let cert-manage handle ACME backoff when Retry-After is set on a rate limit error
```
=> Provide a backoff function to ACME

devel/cluster/create-kind.sh
```release-note
Updates kind cluster 1.19 SHA to use upstream kindest
```
=> Updates kind node 1.19 sha to use upstream

pkg/internal/apis/certmanager/validation/certificate.go, pkg/internal/apis/certmanager/validation/certificate_test.go
=> Update references to URISANs and EmailSANs in the validation

pkg/controller/certificates/util.go
=> Update some references to URISANs and EmailSANs in RequestMatchesSpec

pkg/controller/controller.go
=> Remove extra space

OWNERS
=> Grant Richard Wall (@wallrj) approver and reviewer permissions

cmd/ctl/pkg/renew/renew.go
Signed-off-by: Josh Soref <jsoref@users.noreply.github.com>
Add missing quote to help
```release-note
NONE
```
=> Add missing quote to help

README.md
I started by adding a link to the docs repo, then ended up doing more small fixes
```release-note
NONE
```
=> Keep README.md up to date

hack/bin/deps.bzl
Fix for the CRD bug in local testing
```release-note
NONE
```
=> Update Helm to 3.3.4

deploy/charts/cert-manager/values.yaml
=> typo of registry in values.yaml

deploy/charts/cert-manager/templates/rbac.yaml
- Added acme resources to cluster roles
Fixes #3286
Signed-off-by: Anshul Sharma <optimisticanshul@gmail.com>
```release-note
Include ACME resources aggregated ClusterRoles
```
=> Added acme resources to clusterroles

USERS.md
Add Acoss organisation to USER.md file
```release-note
NONE
```
=> Add Acoss to users

pkg/apis/certmanager/v1/types_issuer.go, pkg/apis/certmanager/v1alpha2/types_issuer.go, pkg/apis/certmanager/v1alpha3/types_issuer.go, pkg/apis/certmanager/v1beta1/types_issuer.go
An attempt to help to fix https://github.com/jetstack/cert-manager/issues/3149 
Not https://github.com/jetstack/cert-manager/issues/3149, to properly fix it needs an addition to controller-gen
/assign @wallrj 
```release-note
NONE
```
=> Document a bit more about the IssuerConfig

ROADMAP.md
This is based on discussions with a lot of people about
what they would like to see from the project and what fits
with the vision on the project.
There's no timeline at this point as different people may
contribute to different themes, so it's hard to make definite
plans.
```release-note
NONE
```
I don't think this requires a release note? Happy to be convinced otherwise.
=> Add a roadmap for the project

pkg/issuer/acme/dns/route53/route53_test.go
This replaces the deprecated `session.New()` with `session.NewSession()`.
`go doc github.com/aws/aws-sdk-go/aws/session New`
>  Deprecated: Use NewSession functions to create sessions instead. NewSession has the same functionality as New except an error can be returned when the func is called instead of waiting to receive an error until a request is made.
```release-note
NONE
```
=> pkg/issuer/acme/dns: replace deprecated AWS function

build/container.bzl, build/files.bzl, deploy/crds/BUILD.bazel, design/acme-orders-challenges-crd.md, devel/cluster/create-openshift3.sh, devel/lib/lib.sh, pkg/controller/acmeorders/sync.go, pkg/controller/certificates/issuing/issuing_controller.go, pkg/controller/ingress-shim/sync_test.go, pkg/internal/apis/certmanager/validation/certificate_test.go, pkg/internal/vault/vault_test.go, pkg/issuer/acme/dns/util/wait_test.go, pkg/util/pki/csr_test.go, pkg/webhook/authority/authority.go, pkg/webhook/server/util/convert.go, test/e2e/framework/helper/validate.go, test/e2e/framework/helper/validations/certificates.go, test/e2e/suite/conformance/certificates/venaficloud/cloud.go, test/e2e/suite/issuers/vault/certificate/approle.go, test/integration/certificates/metrics_controller_test.go, test/integration/framework/apiserver.go
This PR fixes various typos found in the codebase.
```release-note
NONE
```
=> Fix various typos found by codespell

devel/addon/pebble/chart/templates/configmap.yaml, test/e2e/images.bzl
This is for @maelvls's PR to simulate the blocked domain behaviour in Pebble. 
This still needs testing, having kind issues at the moment so there is some delay.
Currently using my fork of Pebble until I tested it, PRed it and is accepted
```release-note
NONE
```
=> Add a blocklist to Pebble

devel/addon/ingressnginx/BUILD.bazel, devel/addon/ingressnginx/install.sh, test/e2e/images.bzl
- Update ingress-nginx to the latest version.
- Remove the default backend image. This is not required since 0.32.0
```release-note
NONE
```
=> Update ingress-nginx addon

cmd/cainjector/app/start.go, deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/values.yaml
**What this PR does / why we need it**: Make leader-election settings customizable for cainjector, through `--leader-election-lease-duration`, `--leader-election-renew-deadline` and `--leader-election-retry-period` flags. Also add these in the Helm chart.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3517
```release-note
Allows customization of cainjector leader-election leases with new flags `--leader-election-lease-duration`, `--leader-election-renew-deadline` and `--leader-election-retry-period`
```
=> Make leader-election settings customizable for cainjector

README.md
The README is currently incorrect
```release-note
NONE
```
=> The development meetings are now hosted on Google Meet

devel/BUILD.bazel, devel/addon/sample-external-issuer/BUILD.bazel, devel/addon/sample-external-issuer/install.sh, devel/bin/kustomize, devel/lib/lib.sh, devel/setup-e2e-deps.sh, hack/bin/BUILD.bazel, hack/bin/deps.bzl, test/e2e/images.bzl, test/e2e/suite/conformance/BUILD.bazel, test/e2e/suite/conformance/certificates/BUILD.bazel, test/e2e/suite/conformance/certificates/external/BUILD.bazel, test/e2e/suite/conformance/certificates/external/external.go, test/e2e/suite/conformance/import.go
Fixes: https://github.com/jetstack/cert-manager/issues/3152
```release-note
NONE
```
=> E2e tests for external issuers

devel/cluster/create-kind.sh, hack/verify-codegen.sh
This is a manual cherry-pick of #3503 
/assign jakexks
```release-note
NONE
```
=> [release-1.1] Add Kubernetes 1.20 to the kind setup script

deploy/crds/crd-certificates.v1beta1.yaml, deploy/crds/crd-certificates.yaml, pkg/apis/certmanager/v1/types_certificate.go, pkg/apis/certmanager/v1alpha2/types_certificate.go, pkg/apis/certmanager/v1alpha3/types_certificate.go, pkg/apis/certmanager/v1beta1/types_certificate.go
This is a manual cherry-pick of #3647
/assign jakexks
```release-note
NONE
```
=> [release-1.1] Fix Helm chart type conversion bug

OWNERS
Let's add @irbekrm and @maelvls to the OWNERS! 😇
```release-note
```
=> Add Irbe and Mael to the OWNERS list

CONTRIBUTING.md, devel/addon/certmanager/install.sh, devel/addon/pebble/install.sh, devel/addon/samplewebhook/install.sh
Also fixes some copy-pasted comments in a few `devel/` scripts
Signed-off-by: Ashley Davis <ashley.davis@jetstack.io>
```release-note
NONE
```
=> Match CONTRIBUTING language to existing copyright notices

OWNERS
```release-note
NONE
```
/cc @SgtCoDFish
=> Adds sgtcodfish to root OWNERS

pkg/issuer/vault/setup.go
/kind bug
fixes #3762
/milestone v1.3
/assign @jakexks @RiichardCC @maelvls @irbekrm 
```release-note
Improve error messages when Vault Issuer has misconfigured auth method
```
=> Change vault auth misconfiguration to have more descriptive error messages

pkg/controller/certificaterequests/controller.go
/kind cleanup
/milestone v1.3
/assign @jakexks @maelvls @irbekrm @wallrj  
```release-note
NONE
```
=> Don't log from multiple controllers when a CertificateRequest is deleted

cmd/controller/app/controller.go, cmd/controller/app/options/BUILD.bazel, cmd/controller/app/options/options.go, cmd/controller/app/options/options_test.go, deploy/charts/cert-manager/values.yaml
/kind feature
/assign @jakexks @irbekrm 
```release-note
Allows disabling enabled cert-manager-controller controller, for example '--controllers=*,-foo'
```
=> Enables disabling enabled cert-manager-controller controllers

devel/setup-e2e-deps.sh
Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>
**What this PR does / why we need it**: Makes it easy to read the logs when the E2E tests fail sometimes during setup. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: xref #3796 
**Release Note:**
```release-note
NONE
```
=> feat: fix logs display for e2e test failures

pkg/controller/certificates/issuing/issuing_controller.go
In https://github.com/jetstack/cert-manager/pull/3795#discussion_r608113314, I proposed to tweak one comment that was meant to explain these 7 lines:
```go
cond := apiutil.GetCertificateRequestCondition(req, cmapi.CertificateRequestConditionReady)
if cond == nil {
if apiutil.CertificateRequestIsDenied(req) {
return c.failIssueCertificate(ctx, log, crt, apiutil.GetCertificateRequestCondition(req, cmapi.CertificateRequestConditionDenied))
}
return nil
}
```
The initial comment seems to focus too heavily on the "what", and too little on the "why". The "why" comes at the end:
```go
// If the certificate request has been denied, set the last failure time to
// now, and set the Issuing status condition to False with reason. We only
// perform this check if the request also doesn't have a Ready …
```
=> issuing-controller: explain why we do the Ready + Denied checks

test/integration/certificates/trigger_controller_test.go
Signed-off-by: Lars Lehtonen <lars.lehtonen@gmail.com>
```release-note
NONE
```
=> test/integration/certificates: fix dropped error

README.md
Also includes some minor changes to language and title casing
Signed-off-by: Ashley Davis <ashley.davis@jetstack.io>
```release-note
Add both style info and warnings about importing cert-manager as a module to README
```
=> Add note about module compat and code style

SECURITY_CONTACTS.md
/hold 
(Held until James is actually added to the group)
```release-note
add @munnerz to SECURITY_CONTACTS.md
```
=> Add @munnerz to SECURITY_CONTACTS.md

pkg/acme/client/interfaces.go, pkg/acme/webhook/apis/acme/v1alpha1/register.go, pkg/api/util/duration.go, pkg/controller/acmeorders/checks.go, pkg/controller/acmeorders/selectors/selector.go, pkg/controller/certificaterequests/acme/acme.go, pkg/controller/certificaterequests/ca/ca_test.go, pkg/controller/certificaterequests/util/reporter.go, pkg/controller/certificates/internal/secretsmanager/secret.go, pkg/controller/certificates/metrics/controller.go, pkg/controller/certificates/revisionmanager/revisionmanager_controller_test.go, pkg/controller/certificates/util.go, pkg/controller/helper.go, pkg/controller/register.go, pkg/controller/test/util.go, pkg/internal/api/mutation/registry_test.go, pkg/internal/apis/acme/validation/order.go, pkg/internal/apis/certmanager/validation/issuer_test.go, pkg/internal/vault/fake/vault.go, pkg/issuer/acme/dns/route53/route53.go, pkg/issuer/acme/dns/route53/route53_test.go, pkg/util/coverage/coverage.go, pkg/util/pki/csr_test.go, pkg/webhook/server/tls/BUILD.bazel, pkg/webhook/server/tls/file_source_test.go
To improve our code quality, fix various issues highlighted by static analysis tools. This is part of the work on https://github.com/cert-manager/website/issues/538
```release-note
NONE
```
/kind cleanup
=> Static Analysis fixes

pkg/controller/acmechallenges/scheduler/BUILD.bazel, pkg/controller/acmechallenges/scheduler/scheduler_test.go, pkg/controller/certificaterequests/venafi/venafi_test.go, pkg/controller/certificates/revisionmanager/revisionmanager_controller.go, pkg/controller/certificates/trigger/trigger_controller_test.go, pkg/controller/controller.go, pkg/controller/issuers/BUILD.bazel, pkg/controller/issuers/sync_test.go, pkg/internal/api/mutation/registry.go, pkg/internal/apis/certmanager/validation/certificaterequest_test.go, pkg/issuer/acme/dns/akamai/akamai.go, pkg/issuer/acme/dns/dns.go, pkg/issuer/acme/dns/rfc2136/BUILD.bazel, pkg/issuer/acme/dns/rfc2136/rfc2136_test.go, pkg/issuer/acme/http/pod.go, pkg/issuer/venafi/client/venaficlient_test.go, pkg/webhook/server/tls/file_source.go
Fix the non-documentation related errors highlighted by lint checking in https://github.com/cert-manager/website/issues/538#issuecomment-831923565
/kind cleanup
```release-note
NONE
```
=> Fix some linting errors 

pkg/controller/certificaterequests/venafi/BUILD.bazel, pkg/controller/certificaterequests/venafi/venafi.go, pkg/controller/certificaterequests/venafi/venafi_test.go, pkg/internal/vault/vault.go, pkg/internal/vault/vault_test.go, pkg/util/pki/parse.go, pkg/util/pki/parse_test.go
```release-note
Change Venafi Issuer to populate CertificateRequest.Status.CA with the root most certificate that was returned from signing. 
```
This PR is branched from #3982 and should be merged first. EDIT: This should say "and that PR should be merged first" instead of "and should be merged first"
/assign @maelvls @munnerz @SgtCoDFish @jakexks
=> Parse certificate chain venafi

Makefile
Signed-off-by: Kevin Grigorenko <kevin@myplaceonline.com>
**Which issue this PR fixes**: fixes #4042
=> Issue #4042: Support make clean target

deploy/crds/crd-certificates.yaml, pkg/apis/certmanager/v1/types_certificate.go, pkg/controller/certificates/util.go, pkg/controller/certificates/util_test.go, pkg/internal/apis/certmanager/types_certificate.go, pkg/internal/apis/certmanager/validation/certificate.go, pkg/util/pki/csr.go, pkg/util/pki/csr_test.go, pkg/util/pki/generate.go, pkg/util/pki/generate_test.go, test/e2e/framework/helper/certificaterequests.go, test/e2e/framework/helper/certificates.go, test/e2e/framework/helper/featureset/featureset.go, test/e2e/framework/helper/validations/certificates.go, test/e2e/suite/conformance/certificates/tests.go, test/e2e/suite/conformance/certificates/vault/vault_approle.go, test/e2e/suite/conformance/certificates/venafi/venafi.go, test/e2e/suite/conformance/certificates/venaficloud/cloud.go, test/e2e/suite/issuers/ca/certificate.go, test/e2e/suite/issuers/ca/certificaterequest.go, test/e2e/suite/issuers/selfsigned/certificaterequest.go, test/e2e/suite/issuers/selfsigned/fixtures.go, test/e2e/util/util.go, test/unit/gen/csr.go
Add support for Ed25519 
#2466
```release-note
Added support for Ed25519 algorithm for Certificates 
```
=> support-ed25519

build/images.bzl
Bumps base images.
I wonder if we should have some automation for this.
```release-note
NONE
```
/kind cleanup
=> Bumps base image versions

BUILD.bazel, cmd/acmesolver/BUILD.bazel, cmd/acmesolver/app/BUILD.bazel, cmd/acmesolver/app/app.go, cmd/acmesolver/main.go, cmd/cainjector/BUILD.bazel, cmd/cainjector/main.go, cmd/controller/BUILD.bazel, cmd/controller/app/BUILD.bazel, cmd/controller/app/controller.go, cmd/controller/main.go, cmd/ctl/BUILD.bazel, cmd/ctl/cmd/cmd.go, cmd/ctl/main.go, cmd/ctl/pkg/check/api/BUILD.bazel, cmd/ctl/pkg/check/api/api.go, cmd/util/BUILD.bazel, cmd/util/context.go, cmd/util/exit.go, cmd/util/signal.go, cmd/util/signal_posix.go, cmd/util/signal_windows.go, cmd/webhook/BUILD.bazel, cmd/webhook/app/BUILD.bazel, cmd/webhook/app/webhook.go, cmd/webhook/main.go, pkg/acme/webhook/cmd/BUILD.bazel, pkg/acme/webhook/cmd/cmd.go, pkg/util/BUILD.bazel
fixes #4222
```release-note
set correct exit codes on ctrl+c event & process defer calls on error
```
=> set correct exit codes

cmd/ctl/pkg/install/install.go, test/integration/ctl/BUILD.bazel, test/integration/ctl/ctl_install.go, test/integration/ctl/install_framework/BUILD.bazel, test/integration/ctl/install_framework/framework.go
first steps towards fixing #4180
```release-note
```
=> Add basic tests to kubectl cert-manager x install

pkg/controller/certificate-shim/sync.go, pkg/controller/certificate-shim/sync_test.go
In #4290, I discovered that using a Gateway with an empty `certificateRef` field would yield a nil pointer exception. I added a couple of unit tests along the way.
Fixes #4290.
```release-notes
Fixed a bug in the "gateway shim" controller that was causing the cert-manager controller to crash
with a nil pointer exception when using the annotation "cert-manager.io/issuer" on a Gateway that
had an empty `tls` block or with `certificateRef` left empty.
```
=> Nil pointer exception: certificateRef and TLS can now be left empty

deploy/charts/cert-manager/README.template.md
This is a manual cherry-pick of the commit in #4309 for release-1.5
/kind cleanup
```release-note
NONE
```
=> [release-1.5] Fix chart prerequisites Kubernetes version

hack/verify-upgrade.sh
This PR changes the upgrade tests to always install cert-manager with the default settings.
The upgrade test [had started failing](https://testgrid.k8s.io/jetstack-cert-manager-master#ci-cert-manager-upgrade-v1-21) because it was at one point installing cert-manager with [./devel/addon/certmanager/install.sh](https://github.com/jetstack/cert-manager/blob/master/devel/addon/certmanager/install.sh) which enables the Gateway feature gate, so the cert-manager controller was failing to start as it did not find the Gateway CRDs.
```release-note
NONE
```
/kind cleanup
=> Fix upgrade tests

deploy/charts/cert-manager/templates/rbac.yaml
**What this PR does / why we need it**: corrects misspelling in RBAC rules
**Which issue this PR fixes**: fixes #4346
```release-note
NONE
```
/kind bug
=> finalisers -> finalizers

pkg/internal/apis/certmanager/validation/certificate_test.go
Signed-off-by: jonathansp <jonathansimonprates@gmail.com>
Replaces reflect package by testify/assert.
**Which issue this PR fixes**: #4351
=> fix: flaky test when comparing unordered elements

pkg/issuer/acme/dns/cloudflare/cloudflare.go
Not a huge deal, fixes a small typo in the error message
```
NONE
```
=> Fix typo in error message

pkg/controller/acmechallenges/sync.go, pkg/controller/acmechallenges/sync_test.go
Fixes #3777
In the ACME challenge controller, we make a GetChallenge call as one of the first things we do.
https://github.com/jetstack/cert-manager/blob/5ec37819e85edbf37e1569c72d3f90f91eb3cf0e/pkg/controller/acmechallenges/sync.go#L303
The intention of this call is to pull in remote state form the ACME server since cert-manager is level based. This [call is made]((https://cs.opensource.google/go/x/crypto/+/32db7946:acme/acme.go;drc=9d1352758620574fd6fc23c31c59c4333b4b3fff;l=628)) as a [Post-as-Get request](https://datatracker.ietf.org/doc/html/rfc8555#section-6.3) to the ACME server.
The [ACME Spec](https://datatracker.ietf.org/doc/html/rfc8555#section-7.1) is a bit ambiguous as to whether making a POST-as-GET request to the challenge endpoint is a valid way to retrieve the current …
=> Replace GetChallenge call with GetAuthorization call in ACME challenge controller

cmd/ctl/pkg/check/check.go, internal/apis/certmanager/types_issuer.go, pkg/apis/acme/v1/types.go, pkg/apis/acme/v1/types_issuer.go, pkg/controller/certificaterequests/ca/ca.go, pkg/logs/logs.go, pkg/metrics/metrics.go, test/e2e/framework/testenv.go, test/e2e/suite/conformance/certificates/tests.go
Fixes some golint issues regarding comments to structs and methods.
Part of #4457 
```release-note
NONE
```
=> Fix some lint issues regarding comments

internal/apis/certmanager/types_issuer.go, internal/vault/fake/vault.go, pkg/api/util/names.go, pkg/controller/certificaterequests/fake/fake.go, pkg/issuer/acme/dns/akamai/akamai.go, pkg/issuer/acme/dns/akamai/akamai_test.go, pkg/issuer/ca/setup.go, pkg/issuer/helper.go, pkg/issuer/vault/setup.go, pkg/metrics/metrics.go
**What this PR does**:
Reduces Go Linter warnings.
**Why we need it**:
Makes the codebase more idiomatic.
[Fix golint errors](https://github.com/jetstack/cert-manager/issues/4457)
I am a non-native speaker / new to cert-manager. Feel free to help me better understand the codebase, in case my comments are wrong :smile:
=> add comments to satisfy linter

build/images.bzl
As prompted by #4033 
```release-note
NONE
```
=> Bump base images to latest versions

OWNERS
adds me to OWNERS
```release-note
NONE
```
=> add jahrlin to OWNERS

internal/apis/meta/v1/conversion.go, pkg/issuer/acme/http/ingress_test.go, test/e2e/framework/helper/describe.go
/kind cleanup
```release-note
NONE
```
=> Three small goimports fixes against current HEAD

devel/addon/certmanager/install.sh
Adds arm (M1) support for the cert-manager developer installation script 
```release-note
NONE
```
=> build cert-manager images for arm on arm

cmd/ctl/pkg/upgrade/migrateapiversion/migrator.go
Updates some of the wording/text messages in the `cmctl upgrade migrate-api-version` command that was added in #4711.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4718 
```release-note
NONE
```
/cc @jsoref
/kind cleanup
/area ctl
=> Reword log messages in the 'cmctl upgrade migrate-api-version' command

cmd/cainjector/app/start.go, cmd/ctl/pkg/create/create.go, cmd/ctl/pkg/factory/validargs.go, pkg/api/util/kube.go, pkg/apis/certmanager/v1/types.go, pkg/controller/certificatesigningrequests/selfsigned/selfsigned.go, pkg/issuer/acme/dns/clouddns/clouddns.go, pkg/issuer/vault/vault.go, pkg/util/pki/kube.go
This PR fixes golinter issues within the codebase
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4457 
This is ongoing and to check current work is appropriate
```release-note
NONE
```
=> add go linters fixes within codebase

make/tools.mk
Note that darwin/arm64 has to be special cased currently because of a lack of official support for that platform in upstream etcd and kube-apiserver. We instead install the amd64 versions, which is what we did [for bazel](https://github.com/jetstack/cert-manager/blob/42d358d69b59f52d6ebc539fa382bb16b5c34e56/hack/bin/BUILD.bazel#L17-L27).
Testers with M1 macs would be especially valuable for this PR!
/kind feature
```release-note
NONE
```
=> Add kubebuilder tools in make for integration tests

cmd/ctl/pkg/upgrade/migrateapiversion/migrator.go
Followup to https://github.com/jetstack/cert-manager/pull/4719#discussion_r780243456 
```release-note
NONE
```
=> Simplify successfully migrated message

README.md
Part of #4824
```release-note
NONE
```
=> Add note about import paths to README

test/integration/ctl/ctl_status_certificate_test.go
Two main changes:
1. Timezones
Because the tests were run in bazel or in CI environments, they always ran in UTC, but the behaviour of ctl is based on local time, not UTC. We show "not after" in the local timezone.
Now, we parse the "not after" time from the output so that its timezone is respected and should pass on any developer laptop even outside of bazel.
2. Created At
There was previously a pretty big regex for checking that "Created at" was a valid timestamp. Now, we simply parse the timestamp using the Go standard library to confirm that it's a valid RFC3339 timestamp.
/kind bug
```release-note
NONE
```
=> Change handling of time in ctl integration tests

deploy/charts/cert-manager/templates/servicemonitor.yaml
Additionally check that the prometheus-operator is installed and the chart will not drop during installation
```release-note
NONE
```
=> Add additional check for servicemonitor

cmd/ctl/pkg/install/helm/applycrd.go, pkg/issuer/acme/dns/cloudflare/cloudflare.go, pkg/issuer/factory.go
Signed-off-by: DiptoChakrabarty <diptochuck123@gmail.com>
This is continuation based on the feedback received in PR #4801 
/kind cleanup
```release-note
NONE
```
=> fix comments to reduce golint issues

design/20220118.server-side-apply.md
This PR contains a design document for implementing Server Side Apply for all cert-manager controllers. Discussion is very welcome :slightly_smiling_face: 
Some related issues/PRs:
https://github.com/jetstack/cert-manager/pull/4638
https://github.com/jetstack/cert-manager/pull/4598
https://github.com/jetstack/cert-manager/issues/4552
```release-note
NONE
```
=> Design Server Side Apply

deploy/charts/cert-manager/values.yaml, pkg/issuer/acme/http/pod.go
Signed-off-by: Ivan <ivans@vaskir.co>
Wanting to solve #4952
/kind feature
```release-note
* `allowPrivilegeEscalation` in container security context defaults to `false` when not set for acmesolver pod
* `allowPrivilegeEscalation` set to `false` by default for controller, cainjector, webhook pods and startupapicheck job
```
=> update: Setting allowPrivilegeEscalation to false

USERS.md
Joakim made a request in the k8s slack for PRs to add Orgs that are currently using cert-manager. We certainly are, so we're happy to fill one out. 
documentation
```release-note
NONE
```
=> Add APU to USERS.MD

USERS.md
Adding a blog about using cert manager using external dns provider in Users file under Individuals 
documentation 
```release-note
NONE
```
=> add cert manager blog details in Users

pkg/controller/acmechallenges/controller.go
Signed-off-by: lonelyCZ <531187475@qq.com>
Fixes #5023 
/kind bug
```release-note
NONE
```
=> Fix the error is reported to null when it happens

pkg/controller/acmechallenges/BUILD.bazel, pkg/controller/acmechallenges/controller_test.go, test/unit/gen/challenge.go
Signed-off-by: lonelyCZ <531187475@qq.com>
Fixes #5011 
/kind feature
```release-note
NONE
```
=> Add a unit test for challenges reScheduler

README.md
See https://github.com/cert-manager/csi-driver/pull/80 for change justification!
/kind cleanup
```release-note
NONE
```
=> Update logo dimensions + add note about logo location and name

README.md, logo/README.md
Rewrites some of the language, and also removes some duplicated stuff - we should have a single source of truth for things like meetings, and this PR will make the website the source of truth for that.
/kind cleanup
```release-note
NONE
```
=> Various README improvements for clarity and brevity

design/20220614-timeouts.md
Proposal to fix ACME timeout issues as in #5080 
/kind design
```release-note
NONE
```
=> Timeouts proposal

hack/build/repos.bzl
This PR updates gazelle imports (The result of running `./hack/update-deps.sh`)
```release-note
NONE
```
=> Updates Bazel deps

ROADMAP.md
This PR adds some initial items to the Roadmap and introduces some loose timeboxing.
Mainly I'd like this PR to serve as a starter for a discussion as to what should be in our Roadmap as well as what should be the process for updating it and what the Roadmap should be used for.
The previous version did correctly indicate the kind of things we are interested in, but in practice it was never used, so I think perhaps a more concrete Roadmap could work better.
Suggestions for ideas for process, structure and other items are very welcome- I expect that the actual contents will liikely be very different from the original commit.
For inspiration as to how other project do it @wallrj pointed us at Github's Roadmap https://github.com/orgs/github/projects/4247/views/1
```release-note
NONE
``` …
=> Updates Roadmap

test/e2e/suite/certificates/secrettemplate.go
/kind flake
This PR is part of the larger [flaky e2e test initiative](https://github.com/cert-manager/cert-manager/issues/4950).
Related: https://github.com/cert-manager/cert-manager/pull/5317
The `SecretTemplate` e2e tests are regularly featured in the periodic e2e testing as failing or flaky. [testgid](https://testgrid.k8s.io/jetstack-cert-manager-next#ci-cert-manager-next-e2e-v1-22).
Much like the [AdditionalOutputFormats e2e test flake PR](https://github.com/cert-manager/cert-manager/pull/5317), I was able to reproduce the test failures locally that we regularly see in our periodic tests. This time however I needed to run a fair few more terminals running ginkgo to make them surface.
Again, we use retry on conflict when updating Certificates during a test _setup_. We are not changing …
=> E2E test flakes: SecretTemplate

test/e2e/suite/approval/approval.go
/kind flake
This PR is part of the larger https://github.com/cert-manager/cert-manager/issues/4950.
The CertificateRequest Approval e2e tests are regularly featured in the periodic e2e testing as failing or flaky. [testgid](https://testgrid.k8s.io/jetstack-cert-manager-next#ci-cert-manager-next-e2e-v1-22).
The main reason for these test failures after testing locally are two fold:
1. (race): The CRD created to test permissions is not yet observable by the webhook by the time that the test attempts to approve or deny a request. This results in returning not found errors.
2. (throttle): Under load, the webhook will implement client throttling do check permissions of a requestor as well as GET requests on the CRD, and so a CertificateRequest Update may return with a context deadline …
=> E2E test flakes: CertificateRequest Approval

pkg/controller/certificates/issuing/internal/keystore_test.go
/kind flake
The fuzzing library we use in the `TestManyPasswordLengths` test cannot be used concurrently. If done, there is a high chance of a panic (and I think the fuzzing won't be totally correct anyway).
This panic can be reliably reproduced with:
```terminal
go test -v ./pkg/controller/certificates/issuing/internal --count 1000 -run 'TestManyPasswordLengths'
```
This PR pre-fuzzes the password test cases non-concurrently, which are then uniquely referenced during the concurrent tests. 
Fixes https://github.com/cert-manager/cert-manager/issues/5228
```release-note
NONE
```
=> Test Flake: TestManyPasswordLengths: pre-create password test cases outside of concurrent tests

OWNERS
Adds our newest team member `inteon` to OWNERS
```release-notes
NONE
```
=> add inteon to OWNERS

hack/prune-junit-xml/prunexml.go, hack/prune-junit-xml/prunexml_test.go, make/test.mk
Currently the junit xml output for gotestsum tests seems to be broken.
This PR fixes the bug & adds some logic to process gotestsum xml ouput before displaying in prow.
/kind feature
```release-note
NONE
```
=> Output junit xml using gotestsum

Makefile, make/README.md, make/ci.mk, make/cmctl.mk, make/e2e-setup.mk, make/licenses.mk, make/manifests.mk, make/release.mk, make/scan.mk, make/server.mk, make/test.mk, make/tools.mk, test/internal/apiserver/envs.go
This PR tries to simplify the `tools.mk` file, by generating some of the targets.
/kind cleanup
```release-note
NONE
```
=> Generate Makefile build targets dynamically for tools

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/values.yaml
Fixes #5149
feature
```release-note
NONE
```
=> Add topologySpreadConstraints to helm chart

deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/startupapicheck-job.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml, test/fixtures/upgrade/overlay/cainjector-ops.yaml, test/fixtures/upgrade/overlay/controller-ops.yaml, test/fixtures/upgrade/overlay/webhook-ops.yaml
Please see #5355
feature
```release-note
To help troubleshooting, make the container names unique.
BREAKING: this change will break scripts/ CI that depend on `cert-manager` being the container name.
```
=> to help troubleshooting make the helm chart container names unique

pkg/metrics/metrics.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
cleanup
```release-note
NONE
```
=> chore: remove duplicate word in comments

design/20220118.server-side-apply.md
=> Fixing the documentation typo

deploy/charts/cert-manager/Chart.template.yaml
Signed-off-by: Martin Schimandl <martin.schimandl@gmail.com>
fixes https://github.com/cert-manager/cert-manager/issues/5280
kind/cleanup
```release-note
NONE
```
=> Update Chart kubeVersion to >=1.20.0-0

pkg/issuer/acme/setup_test.go
Signed-off-by: Sathyanarayanan Saravanamuthu <sathya.chozhanaadan@gmail.com>
Increasing the code coverage for ACME issuer setup.go (84.4% to 97.5%)
test improvement
```release-note
NONE
```
=> Increasing unit test coverage for pkg/issuer/acme/setup.go

make/tools.mk
Backport of #5559 for release-1.10
/king bug
```release-note
Upgrade to latest go minor release
```
=> [release-1.10] Bump to latest go minor version to fix vulns

deploy/charts/cert-manager/templates/webhook-config.yaml
Add commonLabels on webhook configmap.
It was forgotten in this [PR](https://github.com/cert-manager/cert-manager/pull/5208).
Feature
NONE
=> feat: add commonLabels on webhook configmap

internal/controller/feature/features.go, pkg/util/pki/csr.go, pkg/util/pki/csr_test.go, pkg/util/pki/keyusage.go
Signed-off-by: Sathyanarayanan Saravanamuthu <sathyanarays@vmware.com>
Fixing #5539 , #4654
bug
```release-note
Introducing UseCertificateRequestBasicConstraints feature flag to enable Basic Constraints in the Certificate Signing Request
```
=> Fixing CA flag in basic constraints extension

internal/vault/vault_test.go, pkg/controller/certificaterequests/acme/acme_test.go, pkg/controller/certificaterequests/ca/ca_test.go, pkg/controller/certificaterequests/selfsigned/selfsigned_test.go, pkg/controller/certificaterequests/sync_test.go, pkg/controller/certificaterequests/vault/vault_test.go, pkg/controller/certificaterequests/venafi/venafi_test.go, pkg/controller/certificatesigningrequests/ca/ca_test.go, pkg/controller/certificatesigningrequests/selfsigned/selfsigned_test.go, pkg/issuer/venafi/client/request_test.go, test/e2e/suite/issuers/selfsigned/fixtures.go, test/integration/ctl/ctl_status_certificate_test.go, test/unit/gen/csr.go
This PR aims to simplify the code & make it more homogenized.
It improves the gen.CSR code and uses it in all the tests.
/kind cleanup
```release-note
NONE
```
=> Improve gen.CSR and use it in all tests

pkg/controller/certificate-shim/sync.go, pkg/controller/certificate-shim/sync_test.go
When a user creates a `Gateway` resource with a cross-namespace secret reference in the `listeners` block, a secret with invalid `ownerReferences` is attempted to be created:
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
name: example
namespace: default
annotations:
cert-manager.io/issuer: foo
spec:
gatewayClassName: acmesolver
listeners:
- name: https
hostname: foo.com
port: 443
protocol: HTTPS
allowedRoutes:
namespaces:
from: All
tls:
mode: Terminate
certificateRefs:
- name: foo
namespace: other-namespace # different than the namespace of the Gateway itself
```
```bash
$ kubectl apply -f example.yml
$ kubectl get certificate,secret -n sandbox
No resources found in sandbox namespace.
$ kubectl describe gateway example
...
Events:
Type    Reason …
```
=> Return error when Gateway has a cross-namespace secret ref

pkg/issuer/acme/dns/azuredns/azuredns.go
As it was mentioned #5652, a misconfigured Workload Identity-enabled setup (when there's no Federated Identity Credential linked to the controller's service account) leads to excessive logs in controller.
Further investigation showed that messages in token refresh errors in this case contain some unique data like timestamps and Trace IDs.
Whenever an error message is different compared to the previous one, cert-manager controller saves it in CR status of a related resource.
The status updates lead to early reconciliations due to events received over a WATCH session, effectively defeating rate-limiting (`queue.AddRateLimited`).
The PR is intended to fix the behavior by rewriting error message in `adal.RefreshTokenError` before returning it to the above layers of `adal`. To make it …
=> fix(AzureDNS): prevent early reconciliations for misconfigured Workload Identity

cmd/ctl/pkg/install/install.go
Fixes cmctl x install
```release-note
NONE
```
/kind bug
=> Use fake kube apiserver version when generating helm template in cmctl x install

cmd/webhook/app/testing/testwebhook.go, cmd/webhook/app/webhook.go, internal/webhook/webhook.go
This unused parameter causes an unnecessary package dependency.
/kind cleanup
```release-note
NONE
```
=> Removed unused NewCertManagerWebhookServer function argument

SECURITY_CONTACTS.md
Adds Tim to security contacts
```release-note
NONE
```
=> Adds Tim to security contacts

design/20221205-memory-management.md
/kind cleanup
```release-note
NONE
```
=> design: fix dead image links

pkg/webhook/configfile/configfile.go, test/integration/framework/apiserver.go
ioutil is deprecated
```release-note
NONE
```
=> Remove ioutil

internal/plugin/admission/certificaterequest/approval/certificaterequest_approval.go
Found these code improvements while trying to understand this part of the cert-manager code.
This PR only does some small refactors (without any changes to the functionality).
/kind cleanup
```release-note
NONE
```
=> Cleanup certificate request approval webhook

gcb/build_cert_manager.yaml
Add some more comments in the file that was added in #5940 
```release-note
NONE
```
=> Add a link to the full release process

test/e2e/framework/addon/chart/addon.go
Running Helm with the `--wait` flag already waits for pods to be ready (see https://helm.sh/docs/intro/using_helm/).
Additionally, waiting for all pods in the namespace != waiting for the pods deployed by the chart (which is what we actually want).
/kind cleanup
```release-note
NONE
```
=> Simplify e2e Helm

make/tools.mk
https://github.com/google/go-licenses/releases/tag/v1.6.0
/kind cleanup
```release-note
NONE
```
=> Upgrade to go-licenses v1.6.0

make/e2e-setup.mk
We are & want to cache the downloads folder. Therefore, we should not place images in that folder that don't have a version in their filename. To fix this issue, we moved these images to the `containers` folder instead.
/kind cleanup
```release-note
NONE
```
=> Don't place locally built unversioned images in the cached downloads folder

make/config/pebble/chart/templates/deployment.yaml, pkg/issuer/acme/http/http.go, pkg/issuer/acme/http/pod.go
/kind cleanup
```release-note
NONE
```
=> Fix small bugs and make small improvements in ACME code

pkg/acme/webhook/cmd/server/start.go
See #6035 for context- this PR disables [API Priority and Fairness controller](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/) in the [extension apiserver started by a cert-manager external webhook implementation](https://github.com/cert-manager/cert-manager/blob/v1.12.0/pkg/acme/webhook/apiserver/apiserver.go)
API Priority and Fairness is a new-ish mechanism for server-side rate limiting in kube apiserver.
Our external DNS webhook mechanism works by starting [an extension apiserver](https://kubernetes.io/docs/tasks/extend-kubernetes/setup-extension-api-server/) to which the user's normal kube apiserver will forward certain requests as specified in [an APIService deployed by the particular webhook implementation](https://github.com/cert-manager/webhook-example/blo …
=> Disable APF for webhook extension apiserver

deploy/charts/cert-manager/values.yaml
As discussed in https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1684924260330049
```release-note
NONE
```
=> Add a note that folks should not use top level helm featureGates value for webhook feature gates

cmd/ctl/pkg/check/api/api.go
I think this bug might have been introduced by switching to the new wait functions.
The idea is that the default value for `--wait`, which is `0s` should still result in a single check of the API.
/kind bug
```release-note
BUGFIX: `cmctl check api --wait 0` exited without output; we now make sure we perform the API check at least once
```
=> BUGFIX: `cmctl check api --wait 0` should still check the API once

pkg/issuer/acme/dns/clouddns/clouddns.go
If you are running multiple cert managers, like in different clusters, they can race against each other when using Google CloudDNS dns01 issuer.
This is because cert-manager removes any previous txt records under _acme-challenge for the FQDN it's trying to issue. This causes a state where cert-manager will have successfully done the Present() call, but then never complete the challenge. 
Log lines associated with this would be like:
> cert-manager/challenges "msg"="propagation check failed" "error"="DNS record for \"foo.example.com\" not yet propagated" "dnsName"="foo.example.com" "resource_kind"="Challenge" "resource_name"="foo.example.com-755w2-153119475-769035721" "resource_namespace"="istio-system" "resource_version"="v1" "type"="DNS-01"
To solve this, I have changed the behavior so …
=> issuer: acme: clouddns: Fix race condition

design/20221205-memory-management.md, pkg/apis/certmanager/v1/types.go
See https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1685704657807239
This PR just documents what FAO stands for in the `controller.cert-manager.io/fao` label
cleanup
```release-note
NONE
```
=> Document what fao stands for in the controller.cert-manager.io/fao label

internal/plugin/admission/certificaterequest/approval/certificaterequest_approval.go, pkg/controller/cainjector/indexers.go, pkg/controller/util.go, pkg/util/pki/certificatetemplate.go, pkg/util/predicate/certificate.go
=> fix function name in comments

USERS.md
We at Diagrid are using cert-manger a lot in our backend infrastructure.
/cc @maelvls 
```release-note
NONE
```
=> USERS.md: Adds Diagrid organisation

USERS.md
Adding Cluster API to users.
documentation
```release-note
NONE
```
=> Add Cluster API to users

pkg/util/pki/csr.go
/kind cleanup
```release-note
NONE
```
=> ip address is missing from error message

USERS.md
Support cert-manager's CNCF graduation process as [announced via mastodon](https://floss.social/@CertManager@infosec.exchange/110572096248323232). 
Thanks for all your hard work! 
documentation
```release-note
NONE
```
=> Add Cloudogu logo

USERS.md
Add Metal³ to users
```release-note
NONE
```
=> Add Metal3 to users

cmd/controller/go.mod
/kind cleanup
```release-note
NONE
```
=> Remove old miekg/dns replace statement

USERS.md
We've been using cert-manager for years both internally as well as in your clients' clusters to generate certificates and secure our Ingresses.
```release-note
NONE
```
=> Add SenseLabs to USERS.md

pkg/util/pki/parse.go
=> Improve documentation of pki.ParseSingleCertificateChain

LICENSES, go.mod, go.sum, pkg/issuer/venafi/client/request.go
manual backport of https://github.com/cert-manager/cert-manager/pull/6206
/kind cleanup
```release-note
NONE
```
=> [release-1.11] remove VCert fork dependency replace statement

deploy/charts/cert-manager/Chart.template.yaml
- helm: Update Chart.template.yaml - add apache 2.0 license annotaion
- show the license at artifacthub.io
/kind feature
```release-note
helm: Add apache 2.0 license annotation
```
=> helm: Update Chart.template.yaml - add apache 2.0 license

make/tools.mk
#6258 but for the master branch
/kind bug
```release-note
NONE
```
=> Fix kubebuilder shas

cmd/ctl/pkg/factory/validargs.go, internal/apis/config/controller/v1alpha1/conversion_test.go, pkg/controller/acmeorders/sync.go, pkg/controller/certificates/issuing/internal/keystore_test.go, pkg/issuer/acme/dns/rfc2136/tsig_test.go, pkg/issuer/acme/dns/util/wait_test.go, test/integration/acme/orders_controller_test.go
/kind cleanup
```release-note
NONE
```
=> cleanup: some redundant code clean up

pkg/controller/certificate-shim/sync.go, pkg/controller/certificate-shim/sync_test.go
when I use host ip in ingress.Spec.TLS.Hosts and self-signed ca, found that the ip address is not in Certificate IPAddress extensions. It will cause certificate verify failed.
/kind feature
```release-note
Certificate Shim: distinguish dns names and ip address in certificate
```
=> distinguish dns names and ip address

pkg/controller/certificate-shim/sync_test.go
Follow-on to #6267 
/kind cleanup
```release-note
NONE
```
=> add tests for ipv6 in ingress-shim

pkg/issuer/selfsigned/selfsigned.go, pkg/issuer/vault/setup.go, pkg/issuer/venafi/client/instrumentedvenaficlient.go
Fix messageAppRoleAuthKeyRequired error message for Vault.
/kind cleanup
```release-note
NONE
```
=> Fix messageAppRoleAuthKeyRequired error message

design/20230302.gomod.md
Addresses feedback from @james-w - thanks!
/kind design
```release-note
NONE
```
=> Further clarifications and updates to the proliferation design doc

internal/cainjector/feature/features.go, internal/controller/feature/features.go, internal/webhook/feature/features.go
Makes sure all comments use the same format/ template.
/kind cleanup
```release-note
NONE
```
=> Cleanup featuregate comments

deploy/crds/crd-certificaterequests.yaml, deploy/crds/crd-certificates.yaml, internal/apis/certmanager/types_certificate.go, internal/apis/certmanager/types_certificaterequest.go, pkg/apis/certmanager/v1/types_certificate.go, pkg/apis/certmanager/v1/types_certificaterequest.go
This PR improves a lot of the comments in the Certificate and CertificateRequest APIs.
/kind cleanup
```release-note
NONE
```
=> Review Certificate and CertificateRequest API comments

test/integration/go.mod
/kind cleanup
```release-note
NONE
```
=> Remove old github.com/miekg/dns replace statement

deploy/charts/cert-manager/templates/webhook-config.yaml
In the same way we changed the Controller ConfigMap creation behavior [here](https://github.com/cert-manager/cert-manager/pull/6357), we are doing it for the Webhook ConfigMap 
cleanup
```release-note
Webhook ConfigMap if now created only if .Values.webhook.config is set.
```
=> improvement(helm): fixed empty webhook configmap + refactored

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
Part of the release of 1.13.1
/kind cleanup
```release-note
NONE
```
=> [release-1.13] import latest release 1.13 commit in cmctl

test/e2e/framework/addon/vault/vault.go
In https://github.com/cert-manager/cert-manager-olm/pull/99 I attempted to test the cert-manager OLM packages by runing `make e2e-build` to create an `e2e.test` binary and I upload that to a virtual machine where I'm running an OpenShift test cluster with cert-manager installed via OperatorHub.
But the tests won't run because they first deploy a Vault server where the Deployment refers to a Docker image called `local/vault:local`. 
That image is normally pre-loaded into the cluster by the makefile, but in my case I'm running the tests on a cluster where the `make e2e-setup` script has not (and cannot) be run.
This PR changes the E2E test so  that it only uses the `local/vault` image if it detects that it is being executed by make.
This problem was caused by …
=> Allow the E2E tests to run on clusters that have not been prepared by the Makefile

deploy/charts/cert-manager/values.yaml
This PR fixes typo in `values.yml`.
> `Affinty` -> `Affinity`
```release-note
NONE
```
=> Fix typo in values.yml

pkg/controller/configfile/configfile_test.go
The name of the variable inside the test was misleading.
test refactor
```release-note
NONE
```
=> Rename `webhookConfig` to `controllerConfig`

internal/vault/vault.go, internal/vault/vault_test.go, pkg/controller/certificaterequests/vault/vault_test.go, pkg/controller/certificatesigningrequests/vault/vault_test.go, pkg/issuer/vault/setup.go, pkg/issuer/vault/setup_test.go
If the Vault server can not be properly parsed, or it can not be reached, provide a more useful error message
Fixes #5782 
/kind bug
```release-note
Fixed error messaging when setting up vault issuer
```
=> fix error message when setting up vault issuer

deploy/charts/cert-manager/values.yaml
Fix controller featuregates list to proper-case in helm values sample config. Also updated it with current featuregates.
Fixes #6496 
bug
```release-note
NONE
```
=> Fix controller feature gates config in helm

pkg/webhook/server/server.go
We want to prevent the webhook from consuming a LOT of memory due to extremely large requests.
Additionally, this PR improves handling empty bodies, crashes ...
fix is based on https://github.com/kubernetes/kubernetes/blob/c28c2009181fcc44c5f6b47e10e62dacf53e4da0/staging/src/k8s.io/pod-security-admission/cmd/webhook/server/server.go
/kind bug
```release-note
NONE
```
=> BUGFIX: Limit webhook admission input

cmd/cainjector/app/controller.go
in https://github.com/cert-manager/cert-manager/pull/6467, I replaced the errorgroup with a c/r runnable. However, I did not realise that the default for these runnables is to only run on the elected leader.
This PR fixes the runnable to also run on non-leaders.
/kind bug
```release-note
NONE
```
=> BUGFIX: run pprof server on non-leaderelected replicas

cmd/webhook/LICENSES
License verification started to fail due to an upstream package change.
/kind bug
```release-note
NONE
```
=> Fix licenses file

cmd/cainjector/app/cainjector.go, cmd/controller/app/start.go, cmd/webhook/app/webhook.go, internal/apis/config/cainjector/validation/validation_test.go, internal/apis/config/controller/validation/validation_test.go, internal/apis/config/webhook/validation/validation_test.go
Flag validation functions exist, but are not called anywhere. This adds calls to them at each command root.
fix
```release-note
NONE
```
=> fix: validation functions are not called anywhere

OWNERS
@ThatsMrTalbot
@inteon
https://github.com/cert-manager/website/pull/1372
https://github.com/cert-manager/cert-manager/pull/6559
https://github.com/cert-manager/cert-manager/pull/6562
https://github.com/cert-manager/cert-manager/pull/6565
https://github.com/cert-manager/cert-manager/issues/6530
https://kubernetes.slack.com/archives/C4NV3DWUC/p1701764729301039?thread_ts=1701763938.803159&cid=C4NV3DWUC
=> Add @ThatsMrTalbot to OWNERS as reviewer

deploy/charts/cert-manager/templates/cainjector-deployment.yaml, deploy/charts/cert-manager/templates/deployment.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml, deploy/charts/cert-manager/values.yaml
Proposed fix for [this issue](https://github.com/cert-manager/cert-manager/issues/5836)
```release-note
NONE
```
=> Fix helm loglevel parsing

pkg/controller/test/context_builder.go
The `pkg/controller/test/context_builder.go` was quite hard to understand, I added some comments in the file to make it easier to understand.
/kind cleanup
```release-note
NONE
```
=> add comments explaining the Sync function & small test bugfix

pkg/util/pki/parse_certificate_chain_test.go
Adds some extra tests that specifically test for long certificate chains.
/kind cleanup
```release-note
NONE
```
=> Add tests for the improvements made in #6561

make/tools.mk
Currently, we extract the vendored go tar.gz file in the _bin/downloaded folder.
The downloaded folder is cached in our CI. Resulting in a LOT of files being copied from and to the downloaded folder.
This PR changes the make target so the tar.gz is extracted in the _bin/go-vendor folder and the _bin/downloaded/go[...].tar.gz file is kept.
This tar.gz file will now be cached across CI runs instead of the extracted folder.
You can see the large amount of files in the output of this run: https://storage.googleapis.com/jetstack-logs/pr-logs/pull/cert-manager_cert-manager/6608/pull-cert-manager-master-e2e-v1-28/1743241077906739200/build-log.txt
```
Local cache [restore]: found latest cache directory.
...
tools/_go-1.20.12-linux-amd64/
tools/_go-1.20.12-linux-amd64/goroot/ …
```
=> Don't extract vendored go in _bin/downloaded folder

pkg/controller/test/context_builder.go
Reduces the amount of code in this test go file by merging 3 small functions into 1 using generics.
/kind cleanup
```release-note
NONE
```
=> Use generics for mustAllSync variants

internal/controller/certificates/certificates.go, internal/controller/certificates/certificates_test.go
Adds a unit test to CertificateOwnsSecret and fixes a bug in the sorting function.
/kind bug
```release-note
NONE
```
=> Fix bug in CertificateOwnsSecret and add unit test

internal/controller/certificates/certificates.go
Refactors the CertificateOwnsSecret function to start using slices.
/kind cleanup
```release-note
NONE
```
=> Improve CertificateOwnsSecret

test/e2e/framework/helper/featureset/featureset.go, test/e2e/framework/helper/validation/validation.go, test/e2e/suite/conformance/certificates/acme/acme.go, test/e2e/suite/conformance/certificates/suite.go, test/e2e/suite/conformance/certificatesigningrequests/suite.go
Replaces a lot of custom logic with the upstream  k8s.io/apimachinery/pkg/util/sets functionality.
/kind cleanup
```release-note
NONE
```
=> Use k8s.io/apimachinery/pkg/util/sets for FeatureSet

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/values.yaml, make/ci.mk, make/tools.mk
In order to avoid missing docs we can autogenerate the README from the values.yaml, this PR adds comments to all values in the values.yaml file and adds automation to update the chart README in place
Updated README can be previewed here:
https://github.com/ThatsMrTalbot/cert-manager/blob/feat/auto-generate-helm-docs/deploy/charts/cert-manager/README.template.md
```release-note
NONE
```
=> Auto generate Helm docs

test/e2e/suite/certificaterequests/approval/userinfo.go
In https://github.com/kubernetes/kubeadm/issues/2414, which was released in Kubernetes 1.29, kubeadm no longer adds the admin user to the `system:masters` group.
It uses the group name `kubeadm:cluster-admins` instead.
* https://github.com/kubernetes/kubeadm/issues/2414
* https://github.com/kubernetes/kubernetes/blob/909faa3a9b33161992af0684c5582353b5be6d9b/CHANGELOG/CHANGELOG-1.29.md?plain=1#L1186
This causes the following E2E test to fail:
https://github.com/cert-manager/cert-manager/blob/540d5b7b5743d757645989c9eb5d9581c11dbd95/test/e2e/suite/certificaterequests/approval/userinfo.go#L45-L49
* https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/pr-logs/pull/cert-manager_cert-manager/6647/pull-cert-manager-master-e2e-v1-29/1747590219391045632
Instead of hard coding the group …
=> Fix E2E test failure caused by hard coded group names which are no longer used in Kubernetes >=1.29

hack/util/checkhash.sh
This is https://github.com/cert-manager/makefile-modules/pull/46 but for cert-manager!
/kind cleanup
```release-note
NONE
```
=> Tweak checkhash script

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/values.yaml
Improve helm chart documentation by giving the comments in the values.yaml a polish
```release-note
NONE
```
=> docs: update chart values.yaml and README file

pkg/issuer/acme/dns/azuredns/azuredns.go, pkg/issuer/acme/dns/azuredns/azuredns_test.go
https://github.com/cert-manager/cert-manager/pull/6676 did not cover all error cases.
This PR fixes an additional error type reported by @weisdd, we did not solve the problem for the `azidentity.AuthenticationFailedError` errors (https://github.com/cert-manager/cert-manager/pull/5452#issuecomment-1917833009).
Additionally, I tried to simplify the `stabilizeError` function and added new tests for this new error type.
/kind bug
```release-note
NONE
```
=> Redact the body of failed authentication requests

deploy/charts/cert-manager/README.template.md
⚠️ There doesn't appear to be any working CI for this generated file, so it's not currently tested that this is correct.
/kind bug
```release-note
NONE
```
=> Run update-helm-docs to fix Helm README

deploy/charts/cert-manager/README.template.md, make/tools.mk
Depended on #6696 which has now merged.
/kind cleanup
```release-note
NONE
```
=> Update helm tool to latest version and regenerate helm README

deploy/charts/cert-manager/README.template.md, make/tools.mk
Depends on #6696 being backported first in #6704 ✅ 
Manual backport of #6701
/kind feature
```release-note
NONE
```
=> [release-1.14] Update helm-tool to latest and regenerate helm readme

make/tools.mk
/kind cleanup
```release-note
NONE
```
=> Bump golang to 1.21.7

OWNERS
/kind cleanup
```release-note
NONE
```
=> [release-1.13]: backport: update owners for supported releases

OWNERS
@erikgb 
@inteon
https://github.com/cert-manager/cert-manager/pull/3847 (reverted)
https://github.com/cert-manager/cert-manager/pull/3865
https://github.com/cert-manager/cert-manager/pull/6241
I haven't worked too much on cert-manager yet, but we are heavy users of cert-manager and the side projects https://github.com/cert-manager/trust-manager and https://github.com/cert-manager/approver-policy - to which I have made major contributions. I usually try to join the cert-manager daily stand-up when I have time and attend the bi-weekly development meeting. I love the cert-manager community and would like to participate more! 💯
=> Add erikgb to reviewers

deploy/charts/cert-manager/Chart.template.yaml, deploy/charts/cert-manager/README.template.md
- upgrades the Chart.yaml version from `apiVersion: v1` to `apiVersion: v2`.
- reorders the properties in Chart.yaml to match the format used in our other Helm charts (approver-policy, istio-csr ...)
- updates the README.md to give you a more realistic install tutorial
/kind cleanup
```release-note
NONE
```
=> Improve Chart.yaml and README.md

design/20230601.gateway-route-hostnames.md
Discussed #6051 with @irbekrm, who suggested making a design doc.
design
```release-note
NONE
```
=> Add design/20230601.gateway-route-hostnames.

deploy/crds/crd-certificaterequests.yaml, deploy/crds/crd-certificates.yaml, deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, deploy/crds/crd-orders.yaml, make/tools.mk
v0.13.0 is giving me the following errors:
```console
$ cd _bin/tools/ && ln -f -s ../downloaded/tools/controller-gen@v0.13.0_linux_amd64 controller-gen
/home/tramlot/projects/cert-manager/_bin/tools/controller-gen \
schemapatch:manifests=./deploy/crds \
output:dir=./deploy/crds \
paths=./pkg/apis/...
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0e55e]
goroutine 131 [running]:
go/types.(*Checker).handleBailout(0xc00192ba00, 0xc00113dd40)
/usr/local/go/src/go/types/check.go:367 +0x88
panic({0xbc8860?, 0x12b5880?})
/usr/local/go/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xdc4c18, 0x12be040}) …
```
=> Bump controller-gen to v0.14.0

.trivyignore
Add exception for CVE-2024-26147.
/kind cleanup
```release-note
NONE
```
=> [release-1.13] add trivy exception

.trivyignore
Add exception for CVE-2024-26147.
/kind cleanup
```release-note
NONE
```
=> [release-1.12] add trivy exception

pkg/controller/context.go
Manual backport of the fix in https://github.com/cert-manager/cert-manager/pull/6028.
The following script finds data races:
```
#!/bin/bash
cd ./cmd/controller/ && \
go run -race . --v=2 \
--kubeconfig /home/tramlot/.kube/config \
--cluster-resource-namespace="cert-manager" \
--leader-election-namespace=kube-system \
--acme-http01-solver-image=cert-manager-acmesolver-amd64:v1.12.8-9-gc47e9fb626951e \
--kube-api-qps=9000 \
--kube-api-burst=9000 \
--concurrent-workers=200 \
--feature-gates=AdditionalCertificateOutputFormats=true,ExperimentalCertificateSigningRequestControllers=true,ExperimentalGatewayAPISupport=true,ServerSideApply=true,LiteralCertificateSubject=true,UseCertificateRequestBasicConstraints=true \
--max-concurrent-challenges=60 \
--dns01-recursive-nameservers-only=true \ …
```
=> [release-1.13] BUGFIX: fix datarace due to registering and reading from scheme

pkg/controller/context.go
Manual backport of the fix in https://github.com/cert-manager/cert-manager/pull/6028.
see https://github.com/cert-manager/cert-manager/pull/6832
fixes https://github.com/cert-manager/cert-manager/issues/6822
/kind bug
```release-note
BUGFIX: fix race condition due to registering and using global runtime.Scheme variables
```
=> [release-1.12] BUGFIX: fix datarace due to registering and reading from scheme

pkg/util/pki/match.go, pkg/util/pki/match_test.go
The LiteralSubject match logic in match.go gives us false-positive detected changes.
This happens when we are working with complex subject values (using the hex encoded DN values with `=#`).
The go-representation of the AttributeTypeAndValue is different for the generated and parsed values, while the binary representation is identical for both.
This issue has appeared after we fixed support for these more complex DN values in https://github.com/cert-manager/cert-manager/pull/6761.
*Manual test:*
Apply the following resource before and after this PR:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
name: example-com
spec:
secretName: example-com-tls
literalSubject: ST=example,C=US,O=#04024869
dnsNames:
- example.com
issuerRef:
name: selfsigned-issuer
kind: Issuer
group: …
```
=> bugfix: LiteralSubject match function reports incorrect mismatch

pkg/util/pki/csr_test.go
We were only testing the case in which the SAN extension is critical.
/kind cleanup
```release-note
NONE
```
=> Add new testcase that generates a non-critical SAN extension to the GenerateCSR tests

internal/apis/certmanager/validation/util/nameserver_test.go, pkg/controller/cainjector/setup.go
=> chore: remove repetitive words

.trivyignore
/kind bug
```release-note
NONE
```
=> [release-1.13] ignore two false positive vulns

.trivyignore
/kind bug
```release-note
NONE
```
=> [release-1.12] ignore two false positive vulns

make/02_mod.mk
/kind bug
```release-note
NONE
```
=> re-add mistakenly removed make tidy target

hack/prune-junit-xml/prunexml_test.go, internal/cmd/util/signal_test.go, internal/controller/certificates/policies/checks_test.go, pkg/apis/experimental/v1alpha1/types.go, pkg/controller/certificate-shim/sync.go, pkg/issuer/acme/dns/akamai/akamai.go
remove unnecessary code
/kind cleanup
```release-note
NONE
```
=> refactoring: remove unnecessary code

.trivyignore
Similar to #6954
/kind cleanup
```release-note
NONE
```
=> [release-1.12] ignore trivy false positive CVE-2020-8559

.trivyignore
Similar to #6954
/kind cleanup
```release-note
NONE
```
=> [release-1.13] ignore trivy false positive CVE-2020-8559

deploy/crds/crd-certificates.yaml, internal/apis/certmanager/types_certificate.go, internal/controller/feature/features.go, internal/webhook/feature/features.go, pkg/apis/certmanager/v1/types_certificate.go, pkg/controller/certificates/issuing/internal/secret_test.go, test/e2e/suite/certificates/additionaloutputformats.go, test/e2e/suite/issuers/ca/certificate.go, test/integration/certificates/issuing_controller_test.go
Close https://github.com/cert-manager/cert-manager/issues/6356.
More details on the issue.
/kind feature
```release-note
Promoted the AdditionalCertificateOutputFormats feature gate to Beta (enabled by default).
```
=> Promote AdditionalCertificateOutputFormats feature gate to Beta

README.md
Simple readme update, with a typo fix
```release-note
NONE
```
=> Add note about build requirements for cert-manager

RELEASE.md
Adds documentation about the release process and cadance.
documentation
```release-note
NONE
```
=> docs: add RELEASE.md file to describe release process.

make/e2e-ci.sh
See #7022 
/kind bug
```release-note
NONE
```
=> [release-1.13] manual backport of #7022

make/e2e-ci.sh
See #7022 
/kind bug
```release-note
NONE
```
=> [release-1.14] manual backport of #7022

cmd/cainjector/app/cainjector.go, cmd/controller/app/options/options_test.go, cmd/controller/app/start.go, cmd/webhook/app/webhook.go, internal/apis/certmanager/validation/issuer_test.go, internal/apis/config/cainjector/validation/validation.go, internal/apis/config/cainjector/validation/validation_test.go, internal/apis/config/controller/validation/validation.go, internal/apis/config/controller/validation/validation_test.go, internal/apis/config/shared/validation/validation.go, internal/apis/config/shared/validation/validation_test.go, internal/apis/config/webhook/validation/validation.go, internal/apis/config/webhook/validation/validation_test.go, pkg/logs/logs.go
Improves the validation logic for the config API and unit-test all code paths.
/kind cleanup
```release-note
NONE
```
=> Improve config validation

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
=> Update cmd/ctl's go.mod to v1.14.6

cmd/ctl/go.mod, cmd/ctl/go.sum, test/integration/go.mod
=> Update cmd/ctl's go.mod to v1.12.11

pkg/issuer/acme/dns/azuredns/azuredns.go, pkg/issuer/acme/dns/azuredns/azuredns_test.go
=> backport-1.14: normalize azure errors

internal/apis/certmanager/validation/certificaterequest_test.go, pkg/controller/certificates/requestmanager/util_test.go, pkg/util/pki/match_test.go, test/e2e/suite/issuers/acme/certificaterequest/dns01.go, test/e2e/suite/issuers/acme/certificaterequest/http01.go, test/e2e/suite/issuers/ca/certificaterequest.go, test/e2e/suite/issuers/vault/certificaterequest/approle.go, test/e2e/suite/issuers/venafi/tpp/certificaterequest.go, test/e2e/util/util.go, test/integration/certificates/issuing_controller_test.go, test/integration/certificates/revisionmanager_controller_test.go, test/integration/validation/certificaterequest_test.go, test/unit/gen/csr.go
Replaces custom test construction logic with builders from the gen package.
/kind cleanup
```release-note
NONE
```
=> Cleanup test helpers by increasing usage of gen package.

LICENSES, cmd/controller/LICENSES, cmd/controller/go.mod, cmd/controller/go.sum, cmd/webhook/LICENSES, cmd/webhook/go.mod, cmd/webhook/go.sum, go.mod, go.sum, test/integration/LICENSES, test/integration/go.mod, test/integration/go.sum
Reported by trivy / govulncheck
/kind bug
```release-note
Bump grpc-go to fix GHSA-xr7q-jx4m-x55m
```
=> Fix GHSA-xr7q-jx4m-x55m

LICENSES, cmd/controller/LICENSES, cmd/controller/go.mod, cmd/controller/go.sum, cmd/webhook/LICENSES, cmd/webhook/go.mod, cmd/webhook/go.sum, go.mod, go.sum, test/integration/LICENSES, test/integration/go.mod, test/integration/go.sum
Manual backport of #7164
/kind bug
```release-note
Bump grpc-go to fix GHSA-xr7q-jx4m-x55m
```
=> [release-1.15] Bump go-grpc to fix GHSA-xr7q-jx4m-x55m

.github/workflows/govulncheck.yaml, .github/workflows/make-self-upgrade.yaml, klone.yaml, make/_shared/go/base/.github/workflows/govulncheck.yaml, make/_shared/help/help.sh, make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
Manual Makefile modules PR, which is required due to limited permissions of the self-upgrade job (which cannot update/ change github actions itself).
/kind cleanup
```release-note
NONE
```
=> Run 'make upgrade-klone' and 'make generate'

.github/workflows/govulncheck.yaml, .github/workflows/make-self-upgrade.yaml, klone.yaml, make/_shared/go/base/.github/workflows/govulncheck.yaml, make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
Manual run of self-upgrade logic
```release-note
NONE
```
=> [CI] Self-upgrade merging self-upgrade-master into master

.github/workflows/govulncheck.yaml, .github/workflows/make-self-upgrade.yaml, klone.yaml, make/_shared/go/base/.github/workflows/govulncheck.yaml, make/_shared/help/help.sh, make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml, make/_shared/tools/00_mod.mk
Manual self-upgrade.
/kind cleanup
```release-note
NONE
```
=> [release-1.15] Run 'make upgrade-klone' and 'make generate'

make/e2e-setup.mk
Also removes some trailing whitespace
/kind cleanup
```release-note
NONE
```
=> fix SHA for bind image which changed upstream

pkg/controller/certificaterequests/venafi/fuzz_test.go
This adds a fuzzer for the Venafi CR controller. It is a modified version of the Vault CR fuzzer which is why I have changed that fuzzers name too.
```release-note
NONE
```
=> add fuzzer for venafi cr controller

pkg/issuer/acme/dns/route53/route53.go
The cert-manager user-agent was only being added to Route53 API requests,
not to the STS requests when using AssumeRoleWithWebIdentity,
nor to the IMDS requests when requesting the ambient EC2 Instance role credentials.
Before:
```
[2024-09-21 16:57:36] Request
PUT /latest/api/token HTTP/1.1
Host: 169.254.169.254
User-Agent: aws-sdk-go-v2/1.30.4 os/linux lang/go#1.22.3 md/GOOS#linux md/GOARCH#amd64 ft/ec2-imds
Content-Length: 0
Amz-Sdk-Request: attempt=3; max=3
X-Aws-Ec2-Metadata-Token-Ttl-Seconds: 300
Accept-Encoding: gzip
```
After:
```
[2024-09-21 17:09:42] Request
PUT /latest/api/token HTTP/1.1
Host: 169.254.169.254
User-Agent: aws-sdk-go-v2/1.30.4 os/linux lang/go#1.22.3 md/GOOS#linux md/GOARCH#amd64 ft/ec2-imds cert-manager/cert-manager-challenges-canary--linux-amd64--cert-manager- …
```
=> Append cert-manager user-agent string to all AWS API requests

pkg/issuer/acme/dns/route53/route53.go, pkg/issuer/acme/dns/route53/route53_test.go
I find it useful to be able to see the log messages in the verbose test output, to help know which branch of code is being executed and to be able to quickly see the rendered log messages.
```bash
go test ./pkg/issuer/acme/dns/route53/...   -v > {before,after}
```
```diff
$ diff -u before after
--- before      2024-09-21 18:35:27.599394840 +0100
+++ after       2024-09-21 18:35:12.788574207 +0100
@@ -1,21 +1,37 @@
=== RUN   TestAmbientCredentialsFromEnv
+    route53.go:95: I0921 18:35:12.501680] using ambient credentials
--- PASS: TestAmbientCredentialsFromEnv (0.00s)
=== RUN   TestNoCredentialsFromEnv
--- PASS: TestNoCredentialsFromEnv (0.00s)
=== RUN   TestAmbientRegionFromEnv
+    route53.go:95: I0921 18:35:12.502048] using ambient credentials
--- PASS: TestAmbientRegionFromEnv (0.00s) …
```
=> Use context logger for Route53 operations

deploy/charts/cert-manager/README.template.md, deploy/charts/cert-manager/values.schema.json, deploy/charts/cert-manager/values.yaml
Helm chart: fix documentation for service accounts annotations
```release-note
NONE
```
=> Helm chart: fix documentation for service accounts annotations

pkg/controller/certificate-shim/sync.go, pkg/controller/certificate-shim/sync_test.go
Resources with applyset labels will be pruned, which is problematic.
Instead of a generic annotation to control label propagation, the applyset labels are always excluded. This should be a good middleground whilst an API for doing this in a more generic way is discussed. The label should not ever be propagated, and so is a safe default.
Fixes: #7306
/kind bug
```release-note
NONE
```
=> Do not propagate applyset labels

.github/ISSUE_TEMPLATE/bug.md
The issue template results in:
> **Environment details:**:
which looks really silly
/kind cleanup
```release-note
NONE
```
=> chore: Remove stray `:` from issue template

make/_shared/tools/00_mod.mk
this is a partial cherry-pick of d62d13583a8db806cc1f1e0bb8372da70b752dbb to upgrade go to 1.23.5 which fixes CVE-2024-45341
/kind bug
```release-note
update go to 1.23.5
```
=> [release-1.16] update go to 1.23.5

test/unit/gen/certificate.go, test/unit/gen/certificaterequest.go, test/unit/gen/challenge.go, test/unit/gen/order.go
fix some function names in comment
```release-note
NONE
```
=> chore: fix some function names in comment

make/e2e-setup.mk
The upstream changed the tag our tests refer to
/kind bug
```release-note
NONE
```
=> fix SHAs for upstream bind images

make/e2e-setup.mk
This is because of consistently breaking tags upstream.
Commands I ran to create the mirrored bind image:
```console
docker pull --platform=linux/arm64 docker.io/ubuntu/bind9:9.18-22.04_beta
docker tag docker.io/ubuntu/bind9:9.18-22.04_beta europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/bind9:9.18-22.04_beta-arm64
docker pull --platform=linux/amd64 docker.io/ubuntu/bind9:9.18-22.04_beta
docker tag docker.io/ubuntu/bind9:9.18-22.04_beta europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/bind9:9.18-22.04_beta-amd64
docker push europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/bind9:9.18-22.04_beta-amd64
docker push europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/bin …
```
=> [release-1.16] use a cert-manager mirrored version of bind

make/e2e-setup.mk
This is because of consistently breaking tags upstream
See #7631 and #7632
The commands I ran to mirror the image were:
```console
docker pull --platform=linux/arm64 docker.io/ubuntu/bind9:9.18-22.04_beta
docker tag docker.io/ubuntu/bind9:9.18-22.04_beta europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/bind9:9.18-22.04_beta-arm64
docker pull --platform=linux/amd64 docker.io/ubuntu/bind9:9.18-22.04_beta
docker tag docker.io/ubuntu/bind9:9.18-22.04_beta europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/bind9:9.18-22.04_beta-amd64
docker push europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/bind9:9.18-22.04_beta-amd64
docker push europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-in …
```
=> Use a cert-manager mirrored version of bind for e2e tests

pkg/issuer/acme/dns/cloudflare/cloudflare.go, pkg/webhook/configfile/configfile.go, test/acme/server/rfc2136.go, test/e2e/framework/addon/globals.go, test/e2e/framework/helper/validation/certificatesigningrequests/certificatesigningrequests.go
fix some comments
```release-note
fix some comments
```
=> chore: fix some comments

pkg/controller/acmeorders/selectors/dns_names.go, test/acme/util.go
use slices.Contains to simplify code
There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.
/kind
cleanup
```release-note
use slices.Contains to simplify code
```
=> refactor: use slices.Contains to simplify code

pkg/controller/acmechallenges/sync.go
https://github.com/cert-manager/cert-manager/issues/7337. Upon discussion on this issue, it was decided that we will bump up the timeout and check with our users to see if it fixes it. Then we would introduce a feature flag for a more long term fix.
/king bug
```release-note
Changed `authorizationTimeout` to 2 minutes
```
=> fix(acmechallenges): increasing timeout

deploy/charts/cert-manager/README.template.md
Updated the README to match the cert-manager.io website better.
This includes changes we made to our installation process.
```release-note
NONE
```
=> Update Helm chart README

deploy/crds/crd-certificaterequests.yaml, deploy/crds/crd-certificates.yaml, deploy/crds/crd-challenges.yaml, deploy/crds/crd-clusterissuers.yaml, deploy/crds/crd-issuers.yaml, deploy/crds/crd-orders.yaml, make/ci.mk
In preparation for https://github.com/cert-manager/cert-manager/pull/7842.
/kind cleanup
```release-note
NONE
```
=> Sort CRD YAML

.github/renovate.json5
Discovered bug in the config file
/king bug
```release-note
NONE
```
=> bug(ci): escaping new lines in json5

.github/renovate.json5, .github/workflows/renovate.yml
Renovate config improvements based on slack discussions and debugging sessions
/kind cleanup
```release-note
NONE
```
=> fix(ci): new improvements on renovate config

.github/renovate.json5
renovate separates major and minor versions currently. This fixes it.
/kind cleanup
```release-note
NONE
```
=> fix(ci): dont separate major minor

.github/renovate.json5
Some labels were lost on the transition to the shared Renovate preset. This PR will allow PRs like https://github.com/cert-manager/cert-manager/pull/8088 to merge after a /lgtm and /approve.
/kind cleanup
```release-note
NONE
```
/cc @ThatsMrTalbot
=> Add missing labels to Renovate PRs

pkg/controller/certificate-shim/sync.go, pkg/controller/certificates/issuing/internal/secret.go, pkg/controller/certificates/requestmanager/util_test.go, pkg/issuer/acme/http/httproute.go, pkg/issuer/acme/http/ingress.go, pkg/issuer/acme/http/pod.go
There is a [new function](https://pkg.go.dev/maps@go1.21.1#Copy) added in the go1.21 standard library, which can make the code more concise and easy to read.
/kind
```release-note
use maps.Copy for cleaner map handling
```
=> refactor: use maps.Copy for cleaner map handling

deploy/charts/cert-manager/templates/rbac.yaml, deploy/charts/cert-manager/templates/webhook-deployment.yaml
Hi,
This is a trivial PR, as I was playing with yamllint as git-hook today in my gitOps repo, and found these CRDs nits.
As this is my first contribution here, feel free to adjust, or let me know what should I adjust the PR.
Thank you!
/kind 
```release-note
NONE
```
=> chore(helm chart): Fix empty lines, and spaces found by yamllint

test/e2e/bin/cloudflare-clean/main.go, test/e2e/go.mod, test/e2e/go.sum
Fixing cloudflare upgrade to v6
/kind cleanup
```release-note
NONE
```
=> fix(e2e): upgrading cloudflare deps to v6

.github/renovate.json5
I want to see if Renovate can propose patch upgrades for release branches. This PR backports the Renovate config from our `master` branch.
/kind cleanup
```release-note
NONE
```
=> [release-1.18] Backport Renovate config
